### ISSUE TITLE
GamePad A, B, X, Y button presses are not going through

### ISSUE THREAD

**Issue by bindusadu** [MicrosoftDocs/windows-uwp#1002]
byte[] array = new byte[] { 0x01, 0xC4, 0x01, 0x00 }; - sending this byte array does not activate gamepad B
Using similar byte array message for moveDown (VK_GAMEPAD_DPAD_DOWN | 0xCC) works as expected.

Reference - https://docs.microsoft.com/en-us/windows/uwp/xbox-apps/uwp-remoteinput-api

**Comment by bindusadu** [comment]
Any updates on this? Thank you!

**Comment by WilliamsJason** [comment]
I posted a response to this on https://github.com/Microsoft/WindowsDevicePortalWrapper/issues/294 that might help. Can you give that a shot?

**Comment by bindusadu** [comment]
@WilliamsJason So sorry for late reply, got busy with another project. Sending { 0x01, 0xC4, 0x01 } followed by ClearAll worked for gamepad B. I noticed that this behaves differently for different applications on Xbox. Thank you so much for you help!

**Comment by mattwojo** [comment]
Thank you for taking the time to let us know about this issue. It sounds like this issue is resolved, so closing it now.

If you believe your feedback still requires an update to the documentation, please let us know either directly in this thread, by filing a new issue, or by filing a [Pull Request ](https://github.com/MicrosoftDocs/windows-uwp/pulls) with your recommended updates.

Though the Issue will be marked as closed, we will still receive replies and are able to reopen the issue if necessary. 

Thanks again for taking the time to contribute.
