### ISSUE TITLE
WACK test fails

### ISSUE THREAD

**Issue by Bhawna17** [MicrosoftDocs/windows-uwp#1004]
Using this API(Microsoft.Data.Sqlite) in the UWP is failing the Windows App Cert Kit test.

Supported API test 

FAILED 
Supported APIs
Error Found: The supported APIs test detected the following errors: 
API sqlite3_win32_set_directory in winsqlite3.dll is not supported for this application type. 
Impact if not fixed: Using an API that is not part of the Windows SDK for Microsoft Store apps violates the Microsoft Store certification requirements. 
How to fix: Review the error messages to identify the API that is not part of the Windows SDK for Microsoft Store apps. Please note, apps that are built in a debug configuration or without .NET Native enabled (where applicable) can fail this test as these environments may pull in unsupported APIs. Retest your app in a release configuration, and with .NET Native enabled if applicable. See the link below for more information: 
Alternatives to Windows APIs in Microsoft Store apps. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: deb3f64f-cb34-b6e2-a9a0-6ed8eb741cb3
* Version Independent ID: c8f31cef-b782-76ff-df62-9f26c54e8897
* Content: [Use a SQLite database in a UWP app - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/data-access/sqlite-databases#feedback)
* Content Source: [windows-apps-src/data-access/sqlite-databases.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/data-access/sqlite-databases.md)
* Product: **windows**
* GitHub Login: @normesta
* Microsoft Alias: **normesta**

**Comment by knicholasa** [comment]
Thanks for reaching out with your feedback. This looks like a support request to me. You'll find quicker support by consulting our developer support resources. For community assistance with development questions I recommend that you ask on our [forums](https://social.msdn.microsoft.com/Forums/newthread?category=windowsapps&forum=wpdevelop&prof=required) or [StackOverflow](https://stackoverflow.com/questions). Otherwise, please see [the developer support page](https://developer.microsoft.com/windows/support) for your support options. If you get assistance through these other resources and believe that information would help us improve the docs, please come back and let us know.
