### ISSUE TITLE
Add the minimum Windows version number for capability usage in table 

### ISSUE THREAD

**Issue by michael-hawker** [MicrosoftDocs/windows-uwp#1024]
Some capabilities only were introduced with certain versions of Windows.  It'd be nice for this table to display the minimum version required to use a capability.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 30a70676-883b-801e-2f07-881923cb0b96
* Version Independent ID: f968708e-33cd-ba83-fe9a-71672c961044
* Content: [App capability declarations - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/packaging/app-capability-declarations)
* Content Source: [windows-apps-src/packaging/app-capability-declarations.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/packaging/app-capability-declarations.md)
* Product: **windows**
* GitHub Login: @msatranjr
* Microsoft Alias: **misatran**

**Comment by msatranjr** [comment]
Thanks for this feedback, Michael! I will circulate this feedback around and look into the best approach for how we can harvest and provide this information.

**Comment by mcleanbyron** [comment]
Thanks for submitting your feedback and I apologize for the delayed response. I see that updates have not been made since the creation of this Issue so I went ahead and created an internal work item to incorporate your suggestions. The timeline for this may vary, so I will go ahead and close this and circle back when the changes are live. 

Though the Issue will be marked as Closed, I will monitor any replies that come afterwards so treat this like an open Issue. Many thanks!
