### ISSUE TITLE
Authentication key for using Maps on WP8.1

### ISSUE THREAD

**Issue by loulouMS** [MicrosoftDocs/windows-uwp#1035]
This article says :
'To use map services in apps for Windows Phone 8.1 and earlier, you need to request a map service application ID and a token to include in your app's code in the Dev Center dashboard.'
I suppose that is still possible even if WP8.1 is not supported because it's not mentioned that's not possible. So, how to do?
Do I need to create a developer account (and pay) even if the app is for only my own usage?
If I do that, is it possible to get a key?

For your information, I'm developing another app (UWP with a MapControl) with a BingMaps key. But I would like to create a new app on a WP8.1 device.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ad063546-c253-63b5-906f-3169441f2b9f
* Version Independent ID: f6aa154e-88f0-7006-0248-e34fb3ae6b7f
* Content: [Use map services - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/publish/use-map-services)
* Content Source: [windows-apps-src/publish/use-map-services.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/publish/use-map-services.md)
* Product: **windows**
* GitHub Login: @JnHs
* Microsoft Alias: **wdg-dev-content**

**Comment by JnHs** [comment]
You do have to open a developer account and pay the fee in order to use this functionality. Please note that new app submissions targeting Windows Phone 8.1 and earlier won't be accepted as of 10/31/18 - see https://blogs.windows.com/buildingapps/2018/08/20/important-dates-regarding-apps-with-windows-phone-8-x-and-earlier-and-windows-8-8-1-packages-submitted-to-microsoft-store/ for more info.
