### ISSUE TITLE
developer

### ISSUE THREAD

**Issue by crission** [MicrosoftDocs/windows-uwp#1040]
The document doesn't point out that the Appx installer can't put files in the local app data folder. This is supposed to be done by the app itself when it first runs. See https://social.msdn.microsoft.com/Forums/windowsapps/en-US/284bfaec-392a-4775-864f-225543ca9b86/uwp-desktop-bridge-local-app-data?forum=wpdevelop.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 128f1023-9ce5-846a-481d-fbf4dceba128
* Version Independent ID: 376280c4-2c3f-ee62-5886-f98617ffb3cb
* Content: [Prepare to package a desktop application (Desktop Bridge) - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/porting/desktop-to-uwp-prepare)
* Content Source: [windows-apps-src/porting/desktop-to-uwp-prepare.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/porting/desktop-to-uwp-prepare.md)
* Product: **windows**
* GitHub Login: @normesta
* Microsoft Alias: **normesta**

**Comment by mcleanbyron** [comment]
Thanks for taking the time to let us know about this and we sincerely apologize for the delayed response. 

Due to the sheer volume of feedback in our repo, we are currently prioritizing new Issues. If you believe your feedback is still actionable, let us know either directly in this thread or by filing a new issue by using the Feedback control at the bottom of [the article](https://docs.microsoft.com/en-us/windows/msix/desktop/desktop-to-uwp-prepare). 

Though the Issue will be marked as Closed, I will monitor any replies that come afterwards so feel free to treat this like an open Issue. Thank you.
