### ISSUE TITLE
Display Mode - not working

### ISSUE THREAD

**Issue by darnoldtux** [MicrosoftDocs/windows-uwp#1041]
I am working on trying to get a basic understanding of this style of development for a work project and I am trying to start the program with the navigation set to compact. When adding PaneDisplayMode that does not exist and DisplayMode has no setter. Any help on this. I have searched and I have not found a fix.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 745ab6c5-cfbe-a56f-dccd-ab55123f9223
* Version Independent ID: 54455a9f-a92f-e462-558d-78fb696dba8c
* Content: [Navigation view - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/design/controls-and-patterns/navigationview)
* Content Source: [windows-apps-src/design/controls-and-patterns/navigationview.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/design/controls-and-patterns/navigationview.md)
* Product: **windows**
* GitHub Login: @QuinnRadich
* Microsoft Alias: **quradic**

**Comment by jwmsft** [comment]
Hi @darnoldtux, PaneDisplayMode is a new property in the latest version of NavigationView. It's only available if your [minimum app version](https://docs.microsoft.com/windows/uwp/debug-test-perf/version-adaptive-apps) targets [SDK 17763](https://developer.microsoft.com/en-us/windows/downloads/windows-10-sdk) or later, or if you use the [WinUI](https://docs.microsoft.com/en-us/uwp/toolkits/winui/) version of NavigationView.

Otherwise, in previous versions of NavigationView, you can start with compact navigation by handling the Loaded event on NavigationView, and setting the IsPaneOpen property to false.

```
<NavigationView Loaded="NavigationView_Loaded"/>
```

```
private void NavigationView_Loaded(object sender, RoutedEventArgs e)
{
   ((NavigationView)sender).IsPaneOpen = false;
}
```
