### ISSUE TITLE
Please add example code of how to add native ads to GridView or ListView.

### ISSUE THREAD

**Issue by touseefbsb** [MicrosoftDocs/windows-uwp#1045]
Native Ads on any platform are best used in GridView or ListView like controls, so if we could have sample code to do that, it would be great, and it can get pretty complicated because Ad data can be shown in a GridViewItem with help of DataTemplateSelector, but we do not know how to do "RegisterAppContainer" in that scenario.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dcaa67dd-aa69-7de2-ee1e-a044a061d03d
* Version Independent ID: 96552e56-6741-cc59-e814-d347f30fe1ac
* Content: [Native ads - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/monetize/native-ads)
* Content Source: [windows-apps-src/monetize/native-ads.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/monetize/native-ads.md)
* Product: **windows**
* GitHub Login: @mcleanbyron
* Microsoft Alias: **mcleans**

**Comment by anawishnoff** [comment]
Hi @touseefbsb, my apologies for the crazy late reply! I've looked into this and found a solution for displaying an ad within a GridView (or ListView).

I solved this by creating an `Ad` class that had attributes matching the ad's visual elements (i.e. IconImageHeight, IconImageSource). I created a new `Ad` object on the page called `newAdObj`, then populated `newAdObj`'s attributes inside the `MyNativeAd_AdReady` function once all of the data was received from `e.NativeAd`. This object was added to the GridView's `ItemsSource` to be displayed on the page.

I created a `DataTemplateSelector` that switched between one data template for simple string objects (or whatever type of object your GridView contains) and another data template for `Ad` objects. The `Ad` data template had basically the same markup as shown in the current doc sample, but the `DataTemplate.DataType` was set to my custom Ad class, and so all of the fields that were previously being accessed via name in the existing code sample are now being accessed through `{x:Bind}`. See the data template markup below: 

```xml
<DataTemplate x:Key="AdTemplate" x:DataType="local:Ad">
            <StackPanel Background="#555555" Width="Auto" Height="Auto"
                                Orientation="Vertical">
                <Image HorizontalAlignment="Left" VerticalAlignment="Center"
                                Margin="20,20,20,20" Source="{x:Bind iconSource}"/>
                <TextBlock HorizontalAlignment="Left" VerticalAlignment="Center"
                                    Text="{x:Bind title}" FontSize="24" Foreground="White" Margin="20,0,0,10"/>
                <TextBlock HorizontalAlignment="Left" VerticalAlignment="Center"
                                    Foreground="White" TextWrapping="Wrap" Text="{x:Bind description}"
                                    Margin="20,0,0,0" Visibility="{x:Bind descriptionVis}"/>
                <Image HorizontalAlignment="Left"
                                VerticalAlignment="Center" Margin="20,20,20,20" Visibility="{x:Bind mainImgVis}"
                               Source="{x:Bind mainImgSource}"/>
                <Button Background="Gray" Foreground="White"
                                HorizontalAlignment="Left" VerticalAlignment="Center" Width="Auto" Height="Auto"
                                Content="{x:Bind CallToActionContent}" Margin="20,20,20,20"
                                Visibility="{x:Bind CallToActionVis}"/>
                <StackPanel x:Name="SponsoredByStackPanel" Orientation="Horizontal" Margin="20,20,20,20">
                    <TextBlock Text="{x:Bind SponsoredByTextBlock}"
                                       FontSize="24" Foreground="White" Margin="20,0,0,0" HorizontalAlignment="Left"
                                       VerticalAlignment="Center" Visibility="{x:Bind SponsoredByTextBlockVis}"/>
                    <Image Margin="40,20,20,20" HorizontalAlignment="Left"
                                   VerticalAlignment="Center" Visibility="{x:Bind iconImgVis}" Source="{x:Bind iconImgSource}"/>
                </StackPanel>
            </StackPanel>
        </DataTemplate>
```

Finally, in order to call `RegisterAdContainer`, I did the following at the end of the `MyNativeAd_AdReady` function:

```csharp
ListViewItem adContainer = AdListView.ContainerFromItem(newAdObj) as ListViewItem;
nativeAd.RegisterAdContainer(adContainer);
```

Hope that helps!

**Comment by touseefbsb** [comment]
@anawishnoff  Thankyou I will try this
