### ISSUE TITLE
RenderToFileAsync is reducing quality

### ISSUE THREAD

**Issue by omansak** [MicrosoftDocs/windows-uwp#1047]
I have a quiet video (.mp4) and a audio(.acc or .mp3). I am using .RenderToFileAsync(file, MediaTrimmingPreference.Precise) but it is reducing quality and file size. I need just add audio to video

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0533cd22-c376-587a-230e-4ffba029ba07
* Version Independent ID: a9af06f8-3a14-4b2b-6d2f-48dd15b38fe4
* Content: [Media compositions and editing - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/audio-video-camera/media-compositions-and-editing#render-the-composition-to-a-video-file)
* Content Source: [windows-apps-src/audio-video-camera/media-compositions-and-editing.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/audio-video-camera/media-compositions-and-editing.md)
* Product: **windows**
* GitHub Login: @drewbatgit
* Microsoft Alias: **drewbat**

**Comment by drewbatgit** [comment]
Thanks for taking the time to let us know about this and we sincerely apologize for the delayed response. Due to the sheer volume of feedback in our repo, we are currently prioritizing new Issues. If you believe your feedback is still actionable, let us know either directly in this thread or by filing a new Issue and we’ll work to incorporate the suggestions into the documentation. Though the Issue will be marked as Closed, I will monitor any replies that come afterwards so feel free to treat this like an open Issue. Many thanks!
