### ISSUE TITLE
Webm vp9 support for Adaptive Streaming?

### ISSUE THREAD

**Issue by linhnddev** [MicrosoftDocs/windows-uwp#1078]
Hello, 

I have tried to set a Webm vp9 codecs DASH url to Adaptive. I show "file not supported..."

If I set a Webm video file directly to MediaPlayerElement and it works. That means UWP support Webm file

I tried to debug with adaptive streaming sample app. It shows error: "the data in the stream is corrupt" while downloading InitSegment. I'm sure it's not corrupted

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d41778b2-2c38-6200-b25a-c8f840f38420
* Version Independent ID: 8b056ee8-ec3e-1371-fc24-6a0ce0d33d1a
* Content: [Adaptive streaming - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/audio-video-camera/adaptive-streaming)
* Content Source: [windows-apps-src/audio-video-camera/adaptive-streaming.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/audio-video-camera/adaptive-streaming.md)
* Product: **windows**
* GitHub Login: @drewbatgit
* Microsoft Alias: **drewbat**

**Comment by hupo376787** [comment]
It seems uwp `MediaPlayerElement` not fully support webm file. I recently found a bug, when playing webm files, the player doesn't fire `BufferingStarted` and `BufferingEnded` event.

**Comment by drewbatgit** [comment]
Thanks for taking the time to let us know about this and we sincerely apologize for the delayed response. Due to the sheer volume of feedback in our repo, we are currently prioritizing new Issues. If you believe your feedback is still actionable, let us know either directly in this thread or by filing a new Issue and we’ll work to incorporate the suggestions into the documentation. Though the Issue will be marked as Closed, I will monitor any replies that come afterwards so feel free to treat this like an open Issue. Many thanks!
