### ISSUE TITLE
Handling Prelaunch event  is ambiguous!

### ISSUE THREAD

**Issue by denizgokce** [MicrosoftDocs/windows-uwp#1085]
In this document, implementation is shown but the exact function for prelaunch state is ambiguous. Where is the function that I can call before everything starts?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7c02c96c-87a4-b8de-1aa3-03fc6bf29b4e
* Version Independent ID: 4c5d47fa-ad5e-d4cd-b78d-6da56ae7996a
* Content: [Handle app prelaunch - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/launch-resume/handle-app-prelaunch#prelaunch-and-the-app-lifecycle)
* Content Source: [windows-apps-src/launch-resume/handle-app-prelaunch.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/launch-resume/handle-app-prelaunch.md)
* Product: **windows**
* GitHub Login: @TylerMSFT
* Microsoft Alias: **twhitney**

**Comment by denizgokce** [comment]
@mcleblanc @msatranjr 

`private void TryEnablePrelaunch()
{
     Windows.ApplicationModel.Core.CoreApplication.EnablePrelaunch(true);
}`

This piece of code that is presented in official documentation not working for me.

I am building an UWP application with target version 1803 
After I called `TryEnablePrelaunch()`, I call 

`if (!canEnablePrelaunch && e.PrelaunchActivated == true)
{
    LoggingServices.Instance.WriteLine<App>("Application starting...", LogLevel.Info);
}`

but `e.PrelaunchActivated` keeps getting false.

**Comment by hkhmsft** [comment]
Thanks for submitting your feedback and I apologize for the delayed response. I see that updates have not been made since the creation of this Issue so I went ahead and created an internal work item to incorporate your suggestions. The timeline for this may vary, so I will go ahead and close this and circle back when the changes are live. 

Though the Issue will be marked as Closed, I will monitor any replies that come afterwards so treat this like an open Issue. Many thanks!
