### ISSUE TITLE
OnLaunched: No suitable found to override

### ISSUE THREAD

**Issue by frangagn** [MicrosoftDocs/windows-uwp#1088]
God I get irritated when I copy and paste your code as-is and it still generate a cryptic error message. This is what you recommend we do as of 07/01/2018, and yet..... So please either fix your documentation or delete it if it does not work.....

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5bc80d73-48ee-f480-4106-82524a0710f8
* Version Independent ID: 438e26d8-345e-0fe9-553c-1d253f4ec0a6
* Content: [Handle app activation - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/launch-resume/activate-an-app)
* Content Source: [windows-apps-src/launch-resume/activate-an-app.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/launch-resume/activate-an-app.md)
* Product: **windows**
* GitHub Login: @TylerMSFT
* Microsoft Alias: **twhitney**

**Comment by hkhmsft** [comment]
Thanks for submitting your feedback and I apologize for the delayed response. I see that updates have not been made since the creation of this Issue so I went ahead and created an internal work item to incorporate your suggestions. The timeline for this may vary, so I will go ahead and close this and circle back when the changes are live. 

Though the Issue will be marked as Closed, I will monitor any replies that come afterwards so treat this like an open Issue. Many thanks!
