### ISSUE TITLE
Having Featured Stats as persistent leaderboards per in-game level

### ISSUE THREAD

**Issue by hampuslidin** [MicrosoftDocs/windows-uwp#1093]
Hello!

As I understand it, featured stats are only temporary statistics, that are wiped at the beginning of each month. How would you go about to have (in-game) leaderboards, which are persist "forever"? We want to have about 100+ unique leaderboards for each of the levels in the game, which also would go against the 20 featured leaderboard limit. Do we need to use some other service for this use case? Thanks in advance!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 65e69968-d4a3-08b5-da8a-9f33c4298bb9
* Version Independent ID: cfa84b0e-21a3-091f-7324-91974b79332f
* Content: [Player Stats - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/xbox-live/leaderboards-and-stats-2017/stats2017)
* Content Source: [windows-apps-src/xbox-live/leaderboards-and-stats-2017/stats2017.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/xbox-live/leaderboards-and-stats-2017/stats2017.md)
* Product: **windows**
* GitHub Login: @aablackm
* Microsoft Alias: **aablackm**

**Comment by aablackm** [comment]
Hello lidin,
Featured Stats are persistent over time, but to attain the number and type of leaderboards you mentioned here you will need to use the Stats 2013 and Leaderboards 2013 services. The Stats 2013 service is described in the [Player Stats](https://docs.microsoft.com/en-us/windows/uwp/xbox-live/leaderboards-and-stats-2017/player-stats) article. However, it is not available to Creator's Program titles. In order to use this service you will need to have an ID@Xbox or Managaed partner title. You can read about the different developer programs in the [Developer Program Overview](https://docs.microsoft.com/en-us/windows/uwp/xbox-live/developer-program-overview).
