### ISSUE TITLE
The UWP Template no longer contains the Publish Symbos path task

### ISSUE THREAD

**Issue by kgreed** [MicrosoftDocs/windows-uwp#1105]
I am adding it by hand

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c024acf3-a58a-74c8-25b1-e5c88c85583a
* Version Independent ID: 81403e1d-947a-1f7d-f4b7-898105abd745
* Content: [Set up automated builds for your UWP app - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/packaging/auto-build-package-uwp-apps)
* Content Source: [windows-apps-src/packaging/auto-build-package-uwp-apps.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/packaging/auto-build-package-uwp-apps.md)
* Product: **windows**
* GitHub Login: @laurenhughes
* Microsoft Alias: **lahugh**

**Comment by kgreed** [comment]
or the publish to store task

**Comment by mcleanbyron** [comment]
Thanks for your feedback, and I apologize for the long delay in responding. Since the time you submitted this feedback we have completely rewritten [the article](https://docs.microsoft.com/en-us/windows/uwp/packaging/auto-build-package-uwp-apps) to align to the latest developer experience and recommendations. If you still have concerns/feedback, please feel free to reopen this issue with more details.
