### ISSUE TITLE
Please add Framework packages  to this table

### ISSUE THREAD

**Issue by ChrisGuzak** [MicrosoftDocs/windows-uwp#1135]
I want to understand how framework packages relate to others, please update the table at the top to include them.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 07a43e99-2699-6568-6d37-6fe72286ae3c
* Version Independent ID: dfe8c8e7-a573-32e0-cb6c-efbdadc9b00f
* Content: [Extend your app with services, extensions, and packages - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/launch-resume/extend-your-app-with-services-extensions-packages#feedback)
* Content Source: [windows-apps-src/launch-resume/extend-your-app-with-services-extensions-packages.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/launch-resume/extend-your-app-with-services-extensions-packages.md)
* Product: **uwp**
* GitHub Login: @TylerMSFT
* Microsoft Alias: **twhitney**

**Comment by hkhmsft** [comment]
Thanks for submitting your feedback and I apologize for the delayed response. I see that updates have not been made since the creation of this Issue so I went ahead and created an internal work item to incorporate your suggestions. The timeline for this may vary, so I will go ahead and close this and circle back when the changes are live. 

Though the Issue will be marked as Closed, I will monitor any replies that come afterwards so treat this like an open Issue. Many thanks!
