### ISSUE TITLE
When on top does not update selected Item

### ISSUE THREAD

**Issue by Leisvan** [MicrosoftDocs/windows-uwp#1136]
I bind MenuItemsSource to an ICollectionView in the ViewModel. When I select an item by clicking on it or by code (changing the ICollectionViewModel.SelectedItem property) both the ICollectionView and the NavigationView updates the selected item when the PaneDisplayMode property is not set to "OnTop". In that case the NavigationView does not updates its selected item when I change it in the ViewModel and the ViewModel does not update when I select an item in the NavigationView.
when PaneDisplayMode is set to "OnTop"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 745ab6c5-cfbe-a56f-dccd-ab55123f9223
* Version Independent ID: 54455a9f-a92f-e462-558d-78fb696dba8c
* Content: [Navigation view - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/design/controls-and-patterns/navigationview)
* Content Source: [windows-apps-src/design/controls-and-patterns/navigationview.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/design/controls-and-patterns/navigationview.md)
* Product: **uwp**
* GitHub Login: @jwmsft
* Microsoft Alias: **jimwalk**

**Comment by YuliKl** [comment]
@Leisvan, thank you for reporting this issue. Sounds like you have identified a bug in the NavigationView control. Now that Xaml controls have been open sourced, the best place to report this bug is on the [microsoft-ui-xaml repo](https://github.com/Microsoft/microsoft-ui-xaml/). Would you mind re-opening this issue using the [bug report template](https://github.com/Microsoft/microsoft-ui-xaml/issues/new/choose)?

Side clarification: I assume you mean PaneDisplayMode="Top". Is that correct?

**Comment by Leisvan** [comment]
@YuliKl, Indeed I assumed PaneDisplayMode="Top". I've reported the bug to the repo, as you suggested.
Thanks!
