### ISSUE TITLE
Incredibly frustrating docs...

### ISSUE THREAD

**Issue by TDodgeCo** [MicrosoftDocs/windows-uwp#1141]
How do you get these tokens? All this page does is describe what they are, but gives absolutely no direction on how to obtain the various tokens. 

What are the end points? What are the Xbox Authentication Services (XAS)? Where are they located?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ce59c936-c7ca-e27f-a493-d74410ae6783
* Version Independent ID: 1371a138-c9de-8db0-80bb-4cd65323fb88
* Content: [EDS Authorization - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/xbox-live/xbox-live-rest/additional/edsauthorization)
* Content Source: [windows-apps-src/xbox-live/xbox-live-rest/additional/edsauthorization.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/xbox-live/xbox-live-rest/additional/edsauthorization.md)
* Product: **uwp**
* GitHub Login: @KevinAsgari
* Microsoft Alias: **kevinasg**

**Comment by mattwojo** [comment]
Thank you for taking the time to let us know about this issue. Apologies for the delayed response. Due to the volume of feedback in our content, we are currently prioritizing new issues. 

If you believe your feedback still requires action to be taken, please let us know either directly in this thread, by filing a new issue, or by filing a [Pull Request ](https://github.com/MicrosoftDocs/windows-uwp/pulls) with your recommended updates.

Though the Issue will be marked as closed, we will still receive replies and are able to reopen the issue if necessary. 

Thanks again for taking the time to contribute.
