### ISSUE TITLE
Speech Synthesis (Hello World)

### ISSUE THREAD

**Issue by jawineh** [MicrosoftDocs/windows-uwp#1150]
App could not be built due to errors involving "e", Sender,, private and button_click. If the tutor would fix them asap, it will be fine with us. otherwise all others worked out nicely. Kudos!  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7f2e0944-3981-142e-2654-01ab8adc78dd
* Version Independent ID: bc455444-d972-742d-b7b1-0845b60191df
* Content: [Learn how to create a ](https://docs.microsoft.com/en-us/windows/uwp/get-started/create-a-hello-world-app-xaml-universal)
* Content Source: [windows-apps-src/get-started/create-a-hello-world-app-xaml-universal.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/get-started/create-a-hello-world-app-xaml-universal.md)
* Product: **uwp**
* GitHub Login: @GrantMeStrength
* Microsoft Alias: **jken**

**Comment by QuinnRadich** [comment]
Thank you for your feedback, and apologies for letting this issue sit for so long.

We'll soon be making larger revisions to each of our tutorials within the Get Started section. It's quite possible that your issue has been already fixed since you raised it. If not, then as we revise our code and screenshots for this article in the near future, it'll surely be caught and fixed.

Thank you.
