### ISSUE TITLE
What does package mean?

### ISSUE THREAD

**Issue by WuGing** [MicrosoftDocs/windows-uwp#1152]
What does package mean in this instance? Reading through this, it seems to refer to packages that are a part of the core UWP app, and not the core app itself. Is this code necessary for handling updates to the core app? Part of the concern is a user getting an update during a critical time during which an app update would prove quite bad. Where can we get more information on the update process etc?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3b8f3945-fed8-9d31-b718-6d17593dba18
* Version Independent ID: 174db112-dc0f-1f75-84d2-fc7668e2171a
* Content: [Download and install package updates from the Store - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/packaging/self-install-package-updates)
* Content Source: [windows-apps-src/packaging/self-install-package-updates.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/packaging/self-install-package-updates.md)
* Product: **uwp**
* GitHub Login: @mcleanbyron
* Microsoft Alias: **mcleans**

**Comment by mcleanbyron** [comment]
The term "package" in this article refers to any package that is part of your application and that you have [submitted to the Dev Center dashboard](https://docs.microsoft.com/windows/uwp/publish/upload-app-packages) as part of your app's submission. In the context of your question, this could be your "core" app package or a related/optional app package. The [RequestDownloadAndInstallStorePackageUpdatesAsync](https://docs.microsoft.com/en-us/uwp/api/windows.services.store.storecontext.requestdownloadandinstallstorepackageupdatesasync)  and [TrySilentDownloadAndInstallStorePackageUpdatesAsync](https://docs.microsoft.com/en-us/uwp/api/windows.services.store.storecontext.trysilentdownloadandinstallstorepackageupdatesasync) methods will restart your application if necessary. If you use [RequestDownloadAndInstallStorePackageUpdatesAsync](https://docs.microsoft.com/en-us/uwp/api/windows.services.store.storecontext.requestdownloadandinstallstorepackageupdatesasync), the user is shown a dialog that asks the user's permission to proceed and warns them that the app might restart.

These methods are intended to be used primarily for scenarios where you want to trigger the app update process on your own rather than waiting for the Store's scheduled app updates to roll down to your customers. For example, perhaps you publish a new app package to the Store with a critical bug fix and you want to make sure this package is installed the next time the user runs the app. If you know this is an important scenario for your app, you can call these APIs during the startup/initialization phase of your app to install any important updates.

I hope this helps.
