### ISSUE TITLE
When I run the WACK, It fails.

### ISSUE THREAD

**Issue by mikej7167** [MicrosoftDocs/windows-uwp#1177]
I am getting the following message on every WPF app I try to create for the store:

App manifest resources tests: Failed
The test was blocked from execution. Please try re-running the validation. If the test execution remains blocked then please contact support.

I started getting this message after WACK 17763.1 was installed. I have tested this version against other WPF apps I have submitted successfully to the store. They fail as well producing the same error.

Here is the XAML filed from the Manifest file:

&lt;?xml version="1.0" encoding="utf-8"?&gt;
&lt;Package xmlns="http://schemas.microsoft.com/appx/manifest/foundation/windows10" xmlns:mp="http://schemas.microsoft.com/appx/2014/phone/manifest" xmlns:uap="http://schemas.microsoft.com/appx/manifest/uap/windows10" xmlns:rescap="http://schemas.microsoft.com/appx/manifest/foundation/windows10/restrictedcapabilities" IgnorableNamespaces="uap mp rescap"&gt;
  &lt;Identity Name="50445LocalAnalytics.Excelerator" Publisher="CN=7C97CFF3-0F3A-4C86-8557-34CC54C8EFC5" Version="1.1.5.0" /&gt;
  &lt;Properties&gt;
    &lt;DisplayName&gt;Excelerator&lt;/DisplayName&gt;
    &lt;PublisherDisplayName&gt;Local Analytics&lt;/PublisherDisplayName&gt;
    &lt;Logo&gt;Images\StoreLogo.png&lt;/Logo&gt;
  &lt;/Properties&gt;
  &lt;Dependencies&gt;
    &lt;!--&lt;TargetDeviceFamily Name="Windows.Universal" MinVersion="10.0.0.0" MaxVersionTested="10.0.0.0" /&gt;--&gt;
    &lt;TargetDeviceFamily Name="Windows.Desktop" MinVersion="10.0.14393.0" MaxVersionTested="10.0.14393.0" /&gt;
  &lt;/Dependencies&gt;
  &lt;Resources&gt;
    &lt;Resource Language="x-generate" /&gt;
  &lt;/Resources&gt;
  &lt;Applications&gt;
    &lt;Application Id="App" Executable="$targetnametoken$.exe" EntryPoint="$targetentrypoint$"&gt;
      &lt;uap:VisualElements DisplayName="Excelerator" Description="WapProjTemplate1" BackgroundColor="transparent" Square150x150Logo="Images\Square150x150Logo.png" Square44x44Logo="Images\Square44x44Logo.png"&gt;
        &lt;uap:DefaultTile Wide310x150Logo="Images\Wide310x150Logo.png"&gt;
        &lt;/uap:DefaultTile&gt;
      &lt;/uap:VisualElements&gt;
    &lt;/Application&gt;
  &lt;/Applications&gt;
  &lt;Capabilities&gt;
    &lt;rescap:Capability Name="runFullTrust" /&gt;
  &lt;/Capabilities&gt;
&lt;/Package&gt;

The test will not run at all if I do not comment out one of the TargetDeviceFamily entries. This is a test app I'm using to try to trouble shoot this issue. All it does is open the main window. I can't get past the manifest execution error. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f9f4864c-3cf6-a957-dd26-c16cb4a3015e
* Version Independent ID: c9543586-cf91-3c13-50e0-1837cf4138a4
* Content: [Package a desktop application by using Visual Studio - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/porting/desktop-to-uwp-packaging-dot-net)
* Content Source: [windows-apps-src/porting/desktop-to-uwp-packaging-dot-net.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/porting/desktop-to-uwp-packaging-dot-net.md)
* Product: **uwp**
* GitHub Login: @normesta
* Microsoft Alias: **normesta**

**Comment by mikej7167** [comment]
I forgot to mention the apps that are failing the WACK install and run correctly on my clean test computer that I use to verify the apps.

**Comment by jasonjef** [comment]
I started to receive this same message from the certification kit, same version (17763.1) when running against an app that is already in the store. I regenerated the assets and otherwise inspected the manifest but all seems well. If I create an empty UWP app and run WACK it gives the same error ("test was blocked from execution"), so I'm guessing it's not my app but maybe the certification wizard...? Thanks!

**Comment by hickeys** [comment]
Thanks for reaching out with your feedback. GitHub issues in this repo are for documentation bugs only, and unfortunately this seems more like a support request than a documentation bug. 

The best way to get support is by asking the community on [Microsoft Q&A](https://docs.microsoft.com/answers/topics/uwp.html?sort=active&filter=all) or [StackOverflow](https://stackoverflow.com/questions) 

For completeness' sake, here is a list of developer resources:

- [Microsoft Q&A](https://docs.microsoft.com/answers/topics/uwp.html?sort=active&filter=all) offers relevant and timely answers to your technical problems from a community of experts and Microsoft engineers.
- For community assistance with development questions, there are our [forums](https://social.msdn.microsoft.com/Forums/newthread?category=windowsapps&forum=wpdevelop&prof=required), and [StackOverflow](https://stackoverflow.com/questions).
- The [Windows developer support](https://developer.microsoft.com/windows/support) site explains other support options.
- The [Visual Studio developer community](https://developercommunity.visualstudio.com) is available, and responsive. The former User Voice feature is now there on the **Suggest a feature** tab, if you want to lobby for a change, a feature, or to make a suggestion.
- For developer issues, or suspected product bugs, there's [Microsoft Support](https://support.microsoft.com/contactus); a support engineer will look at the repro and see whether the issue is a Microsoft product bug, or something else. If it's a bug with a Microsoft product then the ticket will be free of charge.

If you receive assistance via any support resource and you believe that information would help us improve the docs, then please let us know or consider submitting a pull request.

Thanks,
Shawn
