### ISSUE TITLE
Why should I only use folder icons for folders?

### ISSUE THREAD

**Issue by kgreed** [MicrosoftDocs/windows-uwp#1190]
Can you explain this statement please?  Surely it is up to the designer what icon they wish to use for a parent node?
"If you do this, you should use a folder icon only for nodes that represent literal folders, such as the folder structure on a disk."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d5ba995b-8bf3-407c-7b87-015d22d813f1
* Version Independent ID: 52c553b6-e94d-2810-4123-8ee215b002bf
* Content: [Tree view - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/design/controls-and-patterns/tree-view)
* Content Source: [windows-apps-src/design/controls-and-patterns/tree-view.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/design/controls-and-patterns/tree-view.md)
* Product: **uwp**
* GitHub Login: @jwmsft
* Microsoft Alias: **jimwalk**

**Comment by predavid-zz** [comment]
Hey @kgreed , please feel free to use any suitable icon of choice for the parent node. The statement in the document is a suggestion and not a mandate, which it why it reads as such to use the folder icon only if representing 'literal folders'.App designers and developers are free to use icons that best suit the design of the apps since they know best the scenarios for the app the audience being catered to.  
"You can include an icon in the tree view item data template to represent nodes. If you do this, you should use a folder icon only for nodes that represent literal folders, such as the folder structure on a disk".

**Comment by kgreed** [comment]
I get it.  However the docs are usually technical guides not design guides
Thus I read it as 
"If item is node then assert node.icon is folder icon"  
Where as the meaning as you explain is more like
"If the node is a parent node, consider using a folder icon. This is a common UI convention. "

I hope this is useful feedback.

**Comment by predavid-zz** [comment]
Thanks much for the feedback @kgreed ! We are working on updating the wording of the statement in question to be a suggestions versus a 'must-do' which is what it may seem to imply in the current form. The update will go live shortly.

**Comment by jwmsft** [comment]
Doc has been updated.
