### ISSUE TITLE
Update sideload features for RS5

### ISSUE THREAD

**Issue by rido-min** [MicrosoftDocs/windows-uwp#1201]
The table showing the capabilities by version should be updated to include what's new in 1809

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 95c40c14-add5-56b5-2138-ed0805268b94
* Version Independent ID: faf5d307-7af4-27f7-2ce8-5745a2a57605
* Content: [Troubleshoot installation issues with the App Installer file - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/packaging/troubleshoot-appinstaller-issues)
* Content Source: [windows-apps-src/packaging/troubleshoot-appinstaller-issues.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/packaging/troubleshoot-appinstaller-issues.md)
* Product: **uwp**
* GitHub Login: @ridomin
* Microsoft Alias: **rmpablos**

**Comment by mcleanbyron** [comment]
Thanks for taking the time to let us know about this and we sincerely apologize for the delayed response. 

Due to the sheer volume of feedback in our repo, we are currently prioritizing new Issues. If you believe your feedback is still actionable, let us know either directly in this thread or by filing a new issue by using the Feedback control at the bottom of [the App Installer troubleshooting article](https://docs.microsoft.com/en-us/windows/msix/app-installer/troubleshoot-appinstaller-issues). 

Though the issue will be marked as closed, I will monitor any replies that come afterwards so feel free to treat this like an open Issue. Thank you.
