### ISSUE TITLE
Microsoft.Midi.GmDls not available for ARM64

### ISSUE THREAD

**Issue by ianier** [MicrosoftDocs/windows-uwp#1214]
Already reported this via the Feedback Hub, but no response/action so far:

The processor architecture of the project being built "ARM64" is not supported by the referenced SDK "Microsoft.Midi.GmDls, Version=10.0.17134.0". Please consider changing the targeted processor architecture of your project (in Visual Studio this can be done through the Configuration Manager) to one of the architectures supported by the SDK: "x86, x64, ARM".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 90265caf-b1af-f015-674a-a015e3a35d65
* Version Independent ID: bf193eb6-cd09-7538-12ef-da3cd0188e8d
* Content: [MIDI - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/audio-video-camera/midi)
* Content Source: [windows-apps-src/audio-video-camera/midi.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/audio-video-camera/midi.md)
* Product: **uwp**
* GitHub Login: @drewbatgit
* Microsoft Alias: **drewbat**

**Comment by marswe** [comment]
The framework package Microsoft.Midi.GmDls itself is in fact neutral and therefore works on ARM64.  The issue is that the manifest file included with it in the SDK is limiting it to only x86, x64, and arm.  

That means that as a workaround before the fix ships in an upcoming SDK flight, you can edit the manifest XML file directly at `%programfiles(x86)%\Microsoft SDKs\Windows Kits\10\ExtensionSDKs\Microsoft.Midi.GmDls\10.0.17763.0\SDKManifest.xml` and add arm64 to the SupportedArchitectures field.  With that change, projects using Microsoft.Midi.GmDls will build and run successfully as ARM64.

**Comment by ianier** [comment]
The workaround does the trick so I'm closing this issue. The WoA team confirmed this will be fixed in an upcoming SDK. Thanks a lot.
