### ISSUE TITLE
Function arguments issues

### ISSUE THREAD

**Issue by JuanMejiaVelez** [MicrosoftDocs/windows-uwp#1220]
The section "Function arguments" mentions that ^ (hat) character can be used to scape quotes for literal strings, Visual Studio seems to disagree on this.

Additionally, adding a more complete example in Two way function binding won't hurt, specially showing the definition of the BindBack method.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 55e6de74-ed8f-c579-9f87-766a06efe057
* Version Independent ID: 543f6a62-4700-0774-8112-b288ffe7550b
* Content: [Functions in x:Bind - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/data-binding/function-bindings#function-arguments)
* Content Source: [windows-apps-src/data-binding/function-bindings.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/data-binding/function-bindings.md)
* Product: **uwp**
* GitHub Login: @jwmsft
* Microsoft Alias: **jimwalk**

**Comment by hkhmsft** [comment]
Thanks for submitting your feedback and I apologize for the delayed response. I see that updates have not been made since the creation of this Issue so I went ahead and created an internal work item to incorporate your suggestions. The timeline for this may vary, so I will go ahead and close this and circle back when the changes are live. 

Though the Issue will be marked as Closed, I will monitor any replies that come afterwards so treat this like an open Issue. Many thanks!
