### ISSUE TITLE
Samples should have full code to avoid others "guessing" what they are.

### ISSUE THREAD

**Issue by assassin316** [MicrosoftDocs/windows-uwp#1245]
Horrible example....lots of code missing and takes awhile for someone (whose never worked with Expression Builder) to figure out what "EF" maps to, how to get the proper value of "center", etc...

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 077d8d68-5166-ed15-4d09-7545abf4aa57
* Version Independent ID: fb6d6dc9-2ffe-8d63-d320-38ad5a036de5
* Content: [Pointer-based animations - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/composition/pointer-input-animations)
* Content Source: [windows-apps-src/composition/pointer-input-animations.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/composition/pointer-input-animations.md)
* Product: **uwp**
* GitHub Login: @jwmsft
* Microsoft Alias: **jimwalk**

**Comment by stevewhims** [comment]
Thanks for submitting your feedback, and we apologize for the delayed response. I see that updates have not been made since the creation of this Issue, so I went ahead and created an internal work item to represent your feedback. The timeline for resolving work items of this type vary, so I'll go ahead and close this Issue. The work item I created has a link to this Issue, so the writer working on it will be able to circle back when the changes are live.

Although this Issue will be marked as Closed, we'll monitor any replies that come afterwards. So feel free to treat this like an open Issue. Many thanks!
