### ISSUE TITLE
 Binary analyzer: AppContainerCheck

### ISSUE THREAD

**Issue by kasperbalink** [MicrosoftDocs/windows-uwp#1253]
Hi,

I'm currently trying to submit an app to the store. Everything works fine, but I got an error in the App Certification Kit: a Binary Analyzer error. And because of this error I can't submit this app to the store.
This error is telling me te following:

**Error Found:** The binary analyzer test detected the following errors:
```

- File C:\Program Files\windowsapps\<appname>\opencv_core310.dll has failed the AppContainerCheck check.
- File C:\Program Files\windowsapps\<appname>\opencv_highgui310.dll has failed the AppContainerCheck check.
- File C:\Program Files\windowsapps\<appname>\opencv_imgcodecs310.dll has failed the AppContainerCheck check.
- File C:\Program Files\windowsapps\<appname>\opencv_imgproc310.dll has failed the AppContainerCheck check.
- File C:\Program Files\windowsapps\<appname>\opencv_ml310.dll has failed the AppContainerCheck check.
- File C:\Program Files\windowsapps\<appname>\opencv_objdetect310.dll has failed the AppContainerCheck check.
- File C:\Program Files\windowsapps\<appname>\opencv_photo310.dll has failed the AppContainerCheck check.
- File C:\Program Files\windowsapps\<appname>\opencv_videoio310.dll has failed the AppContainerCheck check.

```

•**Impact if not fixed**: If the app doesn’t use the available Windows protections, it can increase the vulnerability of the customer's computer to malware.

•**How to fix**: Apply the required linker options - SAFESEH, DYNAMICBASE, NXCOMPAT, and APPCONTAINER - when you link the app. See links below for more information:
_Fixing Binary Analyzer Errors_

But, when I try to do the 'How to fix' part, it does not work. It's already in there. So my question is, how can I fix this error and pass this UWP app to the store? 

Kind regards,
Kasper

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fc803d18-855f-7c63-5d0d-02a3be55fa52
* Version Independent ID: 4523d58c-fd9d-4700-fd9a-f28ed3c5f312
* Content: [Windows App Certification Kit tests - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/debug-test-perf/windows-app-certification-kit-tests)
* Content Source: [windows-apps-src/debug-test-perf/windows-app-certification-kit-tests.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/debug-test-perf/windows-app-certification-kit-tests.md)
* Product: **uwp**
* GitHub Login: @PatrickFarley
* Microsoft Alias: **pafarley**

**Comment by eliotcowley** [comment]
Hi @kasperbalink, sorry for the late reply. Did you try following the directions in [the documentation](https://docs.microsoft.com/windows/uwp/debug-test-perf/windows-app-certification-kit-tests#appcontainercheck)&mdash;making sure you're using the latest compiler and linker (i.e. Visual Studio is up-to-date) and using the **/appcontainer** flag on the linker?

**Comment by Karl-Bridge-Microsoft** [comment]
Hi @kasperbalink - Closing due to lack of response, please try to find assistance from one of the following:

- For developer issues, or suspected product bugs, there's [Microsoft Support](https://support.microsoft.com/contactus); a support engineer will look at the repro and see whether the issue is a Microsoft product bug, or something else. If it's a bug with a Microsoft product then the ticket will be free of charge.
- The [Feedback Hub app](https://support.microsoft.com/help/4021566/windows-10-send-feedback-to-microsoft-with-feedback-hub-app) is the right place to lobby for a change, a feature, or to make a suggestion.
- For community assistance with development questions, there are our [forums](https://social.msdn.microsoft.com/Forums/newthread?category=windowsapps&forum=wpdevelop&prof=required), and [StackOverflow](https://stackoverflow.com/questions).
- The [Windows developer support](https://developer.microsoft.com/windows/support) site explains other support options.
- The [Visual Studio developer community](https://developercommunity.visualstudio.com) is available, and responsive. The former User Voice feature is now there on the **Suggest a feature** tab, if you want to lobby for a change, a feature, or to make a suggestion.

If you receive assistance via any support resource, and you believe that information would help us improve the docs, then please and let us know through this issue.
