### ISSUE TITLE
Is the Graphics.Capture API supported in C++/WinRT ?

### ISSUE THREAD

**Issue by techjogger** [MicrosoftDocs/windows-uwp#1265]
Is the Graphics.Capture API supported in C++/WinRT ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f607a1db-43b3-bf1c-c6d1-6283c1280743
* Version Independent ID: c1c72175-3e9c-59f6-e30e-7d6f821c5876
* Content: [Screen capture - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/audio-video-camera/screen-capture)
* Content Source: [windows-apps-src/audio-video-camera/screen-capture.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/audio-video-camera/screen-capture.md)
* Product: **uwp**
* GitHub Login: @drewbatgit
* Microsoft Alias: **drewbat**

**Comment by drewbatgit** [comment]
Thanks for taking the time to let us know about this and we sincerely apologize for the delayed response. This API is supported for C++/WinRT. Our official documentation and samples use C# so that we can easily leverage Win2D and SharpDX to interact with the graphics device.

Due to the sheer volume of feedback in our repo, we are currently prioritizing new Issues. If you believe your feedback is still actionable, let us know either directly in this thread or by filing a new Issue and we’ll work to incorporate the suggestions into the documentation. Though the Issue will be marked as Closed, I will monitor any replies that come afterwards so feel free to treat this like an open Issue. Many thanks!
