### ISSUE TITLE
Need doc for Packaging Project on Azure Blobs

### ISSUE THREAD

**Issue by clairernovotny** [MicrosoftDocs/windows-uwp#1279]
In the docs, there’s a section for hosting the AppInstaller on AWS S3, but not Azure Blobs: https://docs.microsoft.com/en-us/windows/uwp/packaging/web-install-aws. The Azure section only covers App Services, which is overkill and more expensive than the AWS option. Can a page for Azure blobs please be added?

**Comment by mcleanbyron** [comment]
Thanks for taking the time to let us know about this and we sincerely apologize for the delayed response. 

Due to the sheer volume of feedback in our repo, we are currently prioritizing new Issues. If you believe your feedback is still actionable, let us know either directly in this thread or by filing a new issue by using the Feedback control at the bottom of [the Azure deployment article](https://docs.microsoft.com/en-us/windows/msix/app-installer/web-install-azure). 

Though the issue will be marked as closed, I will monitor any replies that come afterwards so feel free to treat this like an open Issue. Thank you.
