### ISSUE TITLE
How are run apps for sideloading with a commercial trusted certificate

### ISSUE THREAD

**Issue by timteam** [MicrosoftDocs/windows-uwp#1289]
Hello,

Do we need to enable the developer mode and to import manually the certificate if the UWP app has been signed with an official trusted certificate bought on a certification site?

Regards,

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e9d1c88d-24b1-0eda-b458-105db02dca36
* Version Independent ID: c5d1634a-0ead-f68a-e5be-89acf0eef0a6
* Content: [Packaging UWP apps - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/packaging/packaging-uwp-apps)
* Content Source: [windows-apps-src/packaging/packaging-uwp-apps.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/packaging/packaging-uwp-apps.md)
* Product: **uwp**
* GitHub Login: @mcleanbyron
* Microsoft Alias: **mcleans**

**Comment by mcleanbyron** [comment]
Hi @timteam - To clarify, are you specifically referring to sideloading an app on your development computer for testing purposes? (versus sideloading an app in a production environment or publishing it to the Store).

**Comment by jashif** [comment]
We are facing a issue in sideloading app in our production environment. we have signed the app with enterprise trusted certificate. on each user login we run the script to install the appx. but for some users we are getting a error like below 

Add-AppxPackage : Deployment failed with HRESULT: 0x80073CFF, To install this application you
need either a Windows developer license or a sideloading-enabled system.

Deployment of package Microsoft.VCLibs.140.00_14.0.26706.0_x64__8wekyb3d8bbwe with package origin
Unsigned failed because no valid license or sideloading policy could be applied. A developer
license (http://go.microsoft.com/fwlink/?LinkId=233074) or enterprise sideloading configuration
(http://go.microsoft.com/fwlink/?LinkId=231020) may be required.


the min target version of appx : 10586 
max version : 17134

could you help us here ?

**Comment by mcleanbyron** [comment]
Hi @jashif - Requests for technical troubleshooting and assistance are out of scope for this repo, which is specifically about feedback on the docs. I recommend that you ask your question on the [MSIX deployment forum](https://techcommunity.microsoft.com/t5/MSIX-Deployment/bd-p/MSIX-Deployment).
