### ISSUE TITLE
Sample data on the design surface on the UWP does not take effect

### ISSUE THREAD

**Issue by Powerhelmsman** [MicrosoftDocs/windows-uwp#1299]
This issue was created by @HaoLife from https://github.com/MicrosoftDocs/feedback/issues/924
Describe the bug
I used sample data on the design surface during the development of the UWP app, but found no effect, and it was effective for me to use the method in WPF with the same example, which should be a bug for the UWP app
To Reproduce
1.Add to xmlns:ds="using:Designs.Homes"
2.Add to d:DataContext="{d:DesignInstance Type=ds:MainDesign, IsDesignTimeCreatable=True}"
3. Add class MainDesign and add Mock data.
4. Has no effect
Expected behavior
Screenshots
This place needs to show MainDesign Mock data.
Desktop (please complete the following information):
OS: windows10
Version 16299
Additional context
This question I do not know where to feedback, if the problem is not handled by you, whether you can tell where to feedback the problem

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 51100eeb-4a55-5997-eee8-2ed0047be78f
* Version Independent ID: d9d5ad3b-4932-c02f-bac0-4dd5a9dd48fb
* Content: [Sample data on the design surface, and for prototyping - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/data-binding/displaying-data-in-the-designer)
* Content Source: [windows-apps-src/data-binding/displaying-data-in-the-designer.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/data-binding/displaying-data-in-the-designer.md)
* Product: **uwp**
* GitHub Login: @mcleanbyron
* Microsoft Alias: **mcleans**

**Comment by knicholasa** [comment]
Thanks for reaching out with your feedback. This sounds like a support request to me. You'll find quicker support by consulting our developer support resources. For community assistance with development questions I recommend that you ask on our [forums](https://social.msdn.microsoft.com/Forums/newthread?category=windowsapps&forum=wpdevelop&prof=required) or [StackOverflow](https://stackoverflow.com/questions). Otherwise, please see [the developer support page](https://developer.microsoft.com/windows/support) for your support options. If you get assistance through these other resources and believe that information would help us improve the docs, please come back and let us know.
