### ISSUE TITLE
Wrong type for "consumable" property of inventoryItem

### ISSUE THREAD

**Issue by IliyaNovikov** [MicrosoftDocs/windows-uwp#1328]
This document states that "consumable" property of inventoryItem is of type array. This is wrong, in fact it is a JSON object representing consumableInventoryItem.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d0cb7cae-e53b-b9bb-cbe9-f23ca2d0f7cf
* Version Independent ID: bcaec36e-6f78-c5d2-8a94-8918d59da7eb
* Content: [inventoryItem (JSON) - Windows UWP applications](https://docs.microsoft.com/en-us/windows/uwp/xbox-live/xbox-live-rest/json/json-inventoryitem)
* Content Source: [windows-apps-src/xbox-live/xbox-live-rest/json/json-inventoryitem.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/xbox-live/xbox-live-rest/json/json-inventoryitem.md)
* Product: **uwp**
* GitHub Login: @KevinAsgari
* Microsoft Alias: **kevinasg**

**Comment by mattwojo** [comment]
Thank you for taking the time to let us know about this issue. Apologies for the delayed response. Due to the volume of feedback in our content, we are currently prioritizing new issues. 

If you believe your feedback still requires action to be taken, please let us know either directly in this thread, by filing a new issue, or by filing a [Pull Request ](https://github.com/MicrosoftDocs/windows-uwp/pulls) with your recommended updates.

Though the Issue will be marked as closed, we will still receive replies and are able to reopen the issue if necessary. 

Thanks again for taking the time to contribute.
