### ISSUE TITLE
Clarification on "When to use icons"

### ISSUE THREAD

**Issue by ischmal** [MicrosoftDocs/windows-uwp#1335]
Under the specific segment of "when to use icons," I'm not sure I really understand the "don't do this" guidelines. 

My initial interpretation was that you shouldn't use any individual MDL2 icon for something other than its explicitly designated purpose. If this is the case, would the XAML Controls Gallery app be in violation of this? (I mean this strictly as an example, I don't actually care if it technically is.) In that particular app, for example, there is a save icon being used to represent the "Menus and Toolbars" page, which is not actually related to any sort of save action per se.

However, if my interpretation is correct, then how does the "don't do this" example image demonstrate a violation? The labels "Education," "Touch," and "Calendar" with their respective icons are the same as their descriptors in the MDL2 list, which seems to be perfectly compliant under this interpretation.

With that said, I also wonder if the scope of this guideline applies only to standalone icons and not buttons or navigation items that have an accompanying label. (Meaning the XAML Controls Gallery is using icons in an acceptable manner.)

Either way, a little clarification and insight would be awesome.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 090a5bbe-1b89-c80b-4ad8-a932d38246ab
* Version Independent ID: 5166ef46-fb83-98fb-b852-f16c5ac3ef8e
* Content: [Icons - Windows UWP applications](https://docs.microsoft.com/en-us/windows/uwp/design/style/icons#feedback)
* Content Source: [windows-apps-src/design/style/icons.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/design/style/icons.md)
* Product: **uwp**
* GitHub Login: @mijacobs
* Microsoft Alias: **mijacobs**

**Comment by mijacobs** [comment]
Hi @ischmal, 
The example is saying that if a concept already has a icon associated with it (such as the disk icon being associated with saving), you shouldn't use it for something else. It doesn't matter whether the icon is a standalone item or in a navigation menu. The issue is that users get used to an icon meaning something specific, so if you use the same icon for a different concept or use a different icon for a standard concept, you might confuse the user (or at least make the app more difficult to use). 

The XAML Controls Gallery is a little complicated, because it's an app that teaches you about making other apps. That said, I'll pass your feedback onto the XAML Controls Gallery team.
