### ISSUE TITLE
Xbox does not trigger MemoryManager_AppMemoryUsageLimitChanging event in background

### ISSUE THREAD

**Issue by JimmyRespawn** [MicrosoftDocs/windows-uwp#1336]
There is a limitation of 128mb for uwp running in background. 
The scenario is app is playing background music handled by mediaPlayerElement
So basically before 1809 update, Xbox will kill off the app directly. 
After 1809, system will kill off the audio instead of triggering MemoryManager_AppMemoryUsageChanging (which I use to triggers ReduceMemoryUsage/GC/Clear UI etc).
Usually the audio will be 20-50mb around which last 60-120minutes.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6538f51a-1819-34cd-0b30-e0b2245a34b2
* Version Independent ID: 726323e1-322f-64a7-137e-93e0f36608e9
* Content: [Reduce memory usage when your app moves to the background state - Windows UWP applications](https://docs.microsoft.com/en-us/windows/uwp/launch-resume/reduce-memory-usage)
* Content Source: [windows-apps-src/launch-resume/reduce-memory-usage.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/launch-resume/reduce-memory-usage.md)
* Product: **uwp**
* GitHub Login: @eliotcowley
* Microsoft Alias: **elcowle**

**Comment by hkhmsft** [comment]
Thanks for taking the time to let us know about this and we sincerely apologize for the delayed response. Due to the sheer volume of feedback in our repo, we are currently prioritizing new Issues. If you believe your feedback is still actionable, let us know either directly in this thread or by filing a new Issue and we’ll work to incorporate the suggestions into the documentation. Though the Issue will be marked as Closed, I will monitor any replies that come afterwards so feel free to treat this like an open Issue. Many thanks!
