### ISSUE TITLE
More information

### ISSUE THREAD

**Issue by MagnusKieler** [MicrosoftDocs/windows-uwp#1346]
It would be very useful if the article had a section describing the differences between using text, buffer or stream. So one could see which one is best suited.

---
#### Dokumentinformasjon

⚠ *Ikke rediger denne delen. Den kreves for koblingen docs.microsoft.com ➟ GitHub-problem.*

* ID: b36404b8-4385-81d9-2ee8-486f0a55fc37
* Version Independent ID: 7b6ce4df-6ab2-3aa6-059f-b38aa9ea8062
* Content: [Create, write, and read a file - Windows UWP applications](https://docs.microsoft.com/nb-no/windows/uwp/files/quickstart-reading-and-writing-files)
* Content Source: [windows-apps-src/files/quickstart-reading-and-writing-files.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/files/quickstart-reading-and-writing-files.md)
* Product: **uwp**
* GitHub Login: @mcleanbyron
* Microsoft Alias: **mcleans**

**Comment by hkhmsft** [comment]
Thanks for taking the time to let us know about this and we sincerely apologize for the delayed response. Due to the sheer volume of feedback in our repo, we are currently prioritizing new Issues. If you believe your feedback is still actionable, let us know either directly in this thread or by filing a new Issue and we’ll work to incorporate the suggestions into the documentation. Though the Issue will be marked as Closed, I will monitor any replies that come afterwards so feel free to treat this like an open Issue. Many thanks!
