### ISSUE TITLE
Timestamp of when the event occurred

### ISSUE THREAD

**Issue by verelpode** [MicrosoftDocs/windows-uwp#1351]
Please document how to get the timestamp of when the key-down or key-up event occurred.  Alternatively, please explain why the timestamp is unavailable/unsupported for keyboard events.

In other words, what is the equivalent of Windows.UI.Input.PointerPoint.Timestamp for keyboard events?

In the old WPF-Classic, you could get the timestamp via System.Windows.Input.KeyEventArgs.Timestamp (inherited from System.Windows.Input.InputEventArgs).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 32569952-2610-a154-ae03-20dfdf09476a
* Version Independent ID: 857856a1-3984-ce9d-3aaa-d41fda28a845
* Content: [Keyboard events - Windows UWP applications](https://docs.microsoft.com/en-us/windows/uwp/design/input/keyboard-events)
* Content Source: [windows-apps-src/design/input/keyboard-events.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/design/input/keyboard-events.md)
* Product: **uwp**
* GitHub Login: @Karl-Bridge-Microsoft
* Microsoft Alias: **kbridge**

**Comment by Karl-Bridge-Microsoft** [comment]
@verelpode - Thanks for the suggestion! This looks like product feedback rather than documentation feedback. If you are looking for functionality that isn’t currently provided by the product, please use the [Windows developer feedback site](https://wpdev.uservoice.com/). We’d be happy to have this on record, where others can view it and upvote it.
