### ISSUE TITLE
Having Issues with the example

### ISSUE THREAD

**Issue by fearless40** [MicrosoftDocs/windows-uwp#1359]
When learning the example I had a major issue with Visual Studio. When you copy over the files from "Generated Files\sources\MainPage.cpp" and "MainPage.h" into the solution visual studio asks if you would like to overwrite them. If you say yes then the Xaml and the C++ code are no longer linked together. Therefore when compiling the solution the compiler spits out an error in "xamltypeinfo.g.cpp" that states it can't find "winrt::implementation::MainPage". I could not for the life of me get it to work without having to start the solution from scratch; and rather than overwrite the files just copy and paste the code from the generated files into the solution files. If there is a better way around this I would greatly appreciate figuring out what to do about it.  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a4db0aab-b906-9dec-381c-ceccc1e90c45
* Version Independent ID: 493a4c50-ffa1-5e32-c757-92306c952887
* Content: [XAML controls; bind to a C++/WinRT property - Windows UWP applications](https://docs.microsoft.com/en-us/windows/uwp/cpp-and-winrt-apis/binding-property)
* Content Source: [windows-apps-src/cpp-and-winrt-apis/binding-property.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/cpp-and-winrt-apis/binding-property.md)
* Product: **uwp**
* GitHub Login: @stevewhims
* Microsoft Alias: **stwhi**

**Comment by stevewhims** [comment]
Hi, @fearless40, note that in the topic we ask you to create BookSku.idl, then build, then copy the generated files across (you do the copy in File Explorer, of course). At that point, the files that you're copying have been created for the first time. So copying them, and then adding them to the project, is the right workflow. However, when you make changes to the IDL for a type that's already in your project, then copying files around isn't appropriate because you'll almost certainly overwrite some of your implementation. When you make changes to the IDL for a type that's already in your project, then the generated files contain stubs any new members you've added. Copy those stubs over into the corresponding file that's already in your project. It sounds like you're already doing that, since you say "rather than overwrite the files just copy and paste the code from the generated files into the solution files". That's right. You're essentially doing a merge at that point, which is necessary, since the generated files don't contain your implemented members, and your implementation doesn't contain the newly added members. There's another example of this in https://docs.microsoft.com/windows/uwp/cpp-and-winrt-apis/binding-collection, where the topic says, "Copy the accessor stubs from".

I hope this helps, and sorry about the confusion.

~Steve

**Comment by stevewhims** [comment]
Hi, @fearless40, I'll go ahead and close this issue now since it's been a while, and it feels resolved. Please reopen if I made a mistake in closing. ~Steve

**Comment by fearless40** [comment]
Thanks for answering and closing it.
