### ISSUE TITLE
Subscription Add-on pricing options!!!

### ISSUE THREAD

**Issue by Quico20** [MicrosoftDocs/windows-uwp#1361]
I have an app i'm developing on my own and I wish to use the subscription add-on from microsoft store, but my doubt is about the pricing, I understand that once I chose a base price it cant be changed later, and that scenario is something i dont like, you see every year inflation grows, i would love to increase the subscription price year by year, if its needed.

So what suggestions do you have to face this kind of scenario??

is it possible to cancel a subscription add-on a publish a new one with a new price, of course the costumer will be force to acquire the new subscription with an increased price. (this way for the canceled subscriptions renewal would be impossible).

Can somebody answer this or give me advise about this scenario please!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b661c3cb-9bb9-6a8d-ce97-fe661d3a1c76
* Version Independent ID: 147e7e9b-2670-86bb-1d23-f76a64fb9bfd
* Content: [Enable subscription add-ons for your app - Windows UWP applications](https://docs.microsoft.com/en-us/windows/uwp/monetize/enable-subscription-add-ons-for-your-app)
* Content Source: [windows-apps-src/monetize/enable-subscription-add-ons-for-your-app.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/monetize/enable-subscription-add-ons-for-your-app.md)
* Product: **uwp**
* GitHub Login: @Xansky
* Microsoft Alias: **mhopkins**

**Comment by mhopkins-msft** [comment]
Thank you for reaching out to the Microsoft Partner Center documentation team. Unfortunately, we don’t have the resources to offer individual technical advice to the broad array of customers who use the documentation.

You may have success posting your question in the [Microsoft Partner Community](https://www.microsoftpartnercommunity.com/) or reaching out to [Support for Microsoft Partners](https://partner.microsoft.com/support).

Again, thanks for reaching out. Best of luck with this issue.

**Comment by AdamSzofran** [comment]
@Quico20 did you ever find the answer to your question? I have exactly the same requirement but I'm not sure how to implement it. Thanks for sharing if you know!

**Comment by Quico20** [comment]
No, man, I didnt get an official answer from Microsoft, because by the time I made the question I hadn't test the store framework yet, just read of it.

Now i'm about to publish and since you can make the subscription unavailable (you can't delete them), at Microsoft Partner Center (add-on section of your application), so my strategy will be to notify my customers when i'm planning to increase the prices by push notifications with Azure Notifications Hub and social networks such as twitter, facebook and youtube, and since I'll be somehow cancelling their subscription, I'll offer the new subscription with a free month, everytime I need to increase the subscriptions, you see you can publish as many subscription as you want with the option to offer a free week trail or a free month trail, that way I'll avoid bothering my customer with subscriptions cancelations since theirs wont be available once I publish a mandatory update of my app.

Of course you gotta make that update mandatory, but fortunately the tools and options are available at Microsoft Partner Center.

That's what i'm doing as a workaround.

Hope this answer satisfy you!!!

**Comment by AdamSzofran** [comment]
Thanks for the detailed response. The procedure for switching users over to the new subscription is what I'm most worried about messing up. I had hoped it would work like the following but now I'm not so sure:

1. New subscription add-on released. Customers subscribe and start paying. Yay!
2. Later you decide to raise the price of new subscriptions.
3. You create a new subscription add-on with a higher price while simultaneously making the old lower-priced subscription unavailable.
4. Existing customers of the old subscription are allowed to keep using it until their original renewal date but then it simply doesn't renew because the add-on is now disabled.
5. You offer the customer the new higher-priced subscription option and they make the in-app purchase. Yay!

From what you said, it sounds like item 4 won't happen the way I wrote it. Are you sure that when you make a subscription add-on unavailable that it immediately cancels it for any customers that have it? Does the store make a pro-rated refund of their remaining subscription balance? I wish the documentation made this clear but it doesn't unfortunately. I'm afraid of messing this up and either alienating customers or leaving money on the table.

The other thing I didn't realize was that you could use a mandatory update to eliminate a subscription. Are you sure? Partner Center associates add-ons with the app, not with individual app submissions. That makes it seem like subscription add-ons are independent of app submissions and their lifetime can span many app submissions.

**Comment by Quico20** [comment]
well I think that scenario that you are describing can be achieve after all.
you see at the add-on subcription section when you open a submission there is a section named Pricing and Availability.
there you can schedule the release date and also you can schedule to stop acquisition, that way you can modify your app to collect only the new subscription for your customers of couse they will have to make the buy of the new and higher subscription manually, and I think after the date of stop acquisition the old subscription wont be collected anymore, this option wasnt a couple months ago. so I havent test it yet.
but I think it will fit your needs and mine as well.
I suggest to explore it and make test yourself to make sure it works as I described you.

Also the documentation links at microsoft partner center about schedule in the pricing and availability doesn't mention anything about stop acquisition I think they guess its self-explanatory.

![schedule](https://user-images.githubusercontent.com/13721058/59012457-26dcf000-87fd-11e9-8d32-e2559e1c6ae0.png)

I'm adding a screenshot of my premium subscription add-on the section where stop acquisition can be found.

I think it will meet your needs and also I'll copy you business strategy. I had another one which will cost me money lol!!!

I'll leave you for now I'll go to sleep, here is 150am and tody i gotta work early c ya pal!!!

**Comment by AdamSzofran** [comment]
Thanks @Quico20!

**Comment by Quico20** [comment]
if you happens to test it before me, please let me know the behavior through this thread please.

it will also be of great help to me!!! Its the first time I'll publish an app on my own.

wish you the best in your business strategy @AdamSzofran
