### ISSUE TITLE
Will not compile as provided

### ISSUE THREAD

**Issue by mbw-k11** [MicrosoftDocs/windows-uwp#1372]
As installed per Visual Studio with the C++/WinRT and VISIX, include files still not correct and cannot be located by Visual Studio. Solution - must remove "winrt" from #include files. e.g. &lt;winrt/Windows.Foundation.h&gt; - once "winrt" is removed, the file can be found by Visual Studio 17 (updated today). 

The "winrt" namespace is not defined as installed - identified by the editor in Visual Studio. I have not yet been able to correct that.

SyndicationClient syndicationClient : Editor reports:  identifier "SyndicationClient syndicationClient" is undefined

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a0d376e5-ada9-78e7-a7c6-028c8acd4e14
* Version Independent ID: 84bb5e64-fd06-7561-eea1-206ababc786f
* Content: [Get started with C++/WinRT - Windows UWP applications](https://docs.microsoft.com/en-us/windows/uwp/cpp-and-winrt-apis/get-started)
* Content Source: [windows-apps-src/cpp-and-winrt-apis/get-started.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/cpp-and-winrt-apis/get-started.md)
* Product: **uwp**
* GitHub Login: @stevewhims
* Microsoft Alias: **stwhi**

**Comment by stevewhims** [comment]
Hi, @mbw-k11, let's take Windows.Foundation.h as an example. There are two versions of that file in the Windows SDK. The latest publicly released Windows SDK is 10.0.17763.0. So, on my machine, I have these two versions of a file with that name:

C:\Program Files (x86)\Windows Kits\10\Include\10.0.17763.0\winrt\windows.foundation.h
C:\Program Files (x86)\Windows Kits\10\Include\10.0.17763.0\cppwinrt\winrt\Windows.Foundation.h

The first one is the the application binary interface (ABI) version of Windows.Foundation.h. When you remove the "winrt" part from your #include, then Visual Studio loads that one. But that's not the one you want.

The second one is the one you want. That's the C++/WinRT header file containing the projection (into C++/WinRT) for the Windows::Foundation namespace. The code in the topic is correct as published, and I'm finding that it does work with the latest public versions of: Visual Studio, the C++/WinRT VSIX, and the Windows SDK. Can you take a look on your system and confirm that your folder structure matches the example above. I'd also recommend confirming that the IncludePath macro in Visual Studio includes the path to C:\Program Files (x86)\Windows Kits\10\Include\10.0.17763.0\cppwinrt\. When you #include <winrt/Windows.Foundation.h>, then VS is looking relative to that \cppwinrt folder.

Also, note that the topic calls for a new Windows Console Application (C++/WinRT) project rather than Windows Console Application project. The latter would need to be set up a bit differently.

~Steve

**Comment by stevewhims** [comment]
Hi, @mbw-k11, I'll go ahead and close this issue now since it's been a while, and it feels resolved. Please reopen if I made a mistake in closing. ~Steve
