### ISSUE TITLE
Remove/Customized the Yellow Rectangular Region Highlight the Windows is in Screen Capturing?

### ISSUE THREAD

**Issue by meteorsnows** [MicrosoftDocs/windows-uwp#1375]
It is able to Remove/Customized the Yellow Rectangular Region Highlight the Windows is in Screen Capturing?
Could it be a feature / parameter allowed it to be customized?, or any overlay red dot instead of rectangular, if it for the sake of Security of user (Notify that the windows is recorded)?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f607a1db-43b3-bf1c-c6d1-6283c1280743
* Version Independent ID: c1c72175-3e9c-59f6-e30e-7d6f821c5876
* Content: [Screen capture - Windows UWP applications](https://docs.microsoft.com/en-us/windows/uwp/audio-video-camera/screen-capture#)
* Content Source: [windows-apps-src/audio-video-camera/screen-capture.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/audio-video-camera/screen-capture.md)
* Product: **uwp**
* GitHub Login: @drewbatgit
* Microsoft Alias: **drewbat**

**Comment by drewbatgit** [comment]
It looks like you have product feedback rather than documentation feedback. If you are looking for functionality that isn’t currently provided by the product, the [Feedback Hub app](https://support.microsoft.com/help/4021566/windows-10-send-feedback-to-microsoft-with-feedback-hub-app) is the right place to lobby for a change, a feature, or to make a suggestion.
