### ISSUE TITLE
StoreServicesFeedbackLauncher.GetDefault() is broken

### ISSUE THREAD

**Issue by myokeeh** [MicrosoftDocs/windows-uwp#1389]
FYI, StoreServicesFeedbackLauncher.GetDefault() is crashing UWP apps on 1809.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 443bc235-c1bd-4f01-f758-14575db6dbb6
* Version Independent ID: 9b2b7af4-870a-d423-f0d7-2f7a680d38cc
* Content: [Launch Feedback Hub from your app - Windows UWP applications](https://docs.microsoft.com/en-us/windows/uwp/monetize/launch-feedback-hub-from-your-app)
* Content Source: [windows-apps-src/monetize/launch-feedback-hub-from-your-app.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/monetize/launch-feedback-hub-from-your-app.md)
* Product: **uwp**
* GitHub Login: @Xansky
* Microsoft Alias: **mhopkins**

**Comment by Swerfer** [comment]
My app didn't pass certification because of this. See also https://stackoverflow.com/questions/52769958/microsofts-feedback-hub-now-crashes-my-uwp-app. It's a relative old issue which should get the highest priority, because lot's of people don't test all functions of the app when something small is updated and if they change the target version to 1809 (like I did besides a small bug fix).

**Comment by Swerfer** [comment]
Even with max target version set to 1803 the app failed certification in the store because of a crashing app when the feedback hub should be opened. When debugging in Visual Studio the app does not crash and the feedback hub opens as supposed. Very annoying. I'm now forced to remove the ability to give feedback from my app until there is confirmation that this bug is fixed...

**Comment by myokeeh** [comment]
@db71 https://twitter.com/ClintRutkas/status/1086058102640627717?s=20

**Comment by mhopkins-msft** [comment]
I reached out the the engineering team about this issue. They are aware of the problem but there are no plans to update the SDK. Here is the response I received.

-----------------------
Yes, we are aware of this issue, there is a work around for this which is posted on stack-overflow.
[https://stackoverflow.com/questions/53378611/storeservicesfeedbacklauncher-is-not-working/54299697#54299697](https://stackoverflow.com/questions/53378611/storeservicesfeedbacklauncher-is-not-working/54299697#54299697)

We are not actively supporting the SDK and haven’t released any new features since last March.

-----------------------

Thanks,
 ~ _Mark_

**Comment by riverar** [comment]
@Xansky That is not a valid workaround, the team needs to seek possible servicing action for apps that are in production. Recommend re-open.

**Comment by mhopkins-msft** [comment]
Hi Rafael,

As I mentioned, I've contacted the product team know about the issue. There were already aware of it. This feedback channel is for providing input about the documentation as opposed to product bug reports. So, reopening this documentation issue won't get the actual problem fixed. 

I've also passed on your feedback that you don't see this as a valid solution. However, as the team mentioned, they are not actively supporting the Microsoft Store Services SDK any longer.

Thanks,
 ~ _Mark_

**Comment by riverar** [comment]
@Xansky That's fair, thanks. I'll follow up via MVP back channels.

**Comment by mhopkins-msft** [comment]
Good news! The engineering team tells me they are working on a fix.

**Comment by benstevens48** [comment]
Hi,
Based on the info in one of the posts on StackOverflow, I've worked out how to launch the Feedback Hub on the page for the current app (still can't provide metadata though). Do this as follows.
```C#
await Launcher.LaunchUriAsync(new Uri("feedback-hub://?appid=" + appUserModelId));
```
where the easiest way I can find to get the `appUserModelId` is as follows
```C#
string appUserModelId = Package.Current.Id.FamilyName + "!" + packageRelativeApplicationId;
```
where `packageRelativeApplicationId` is hard-coded in Package.appxmanifest at `/Package/Applications/Application@Id` and is usually simply `App`.

Perhaps you could document this as an alternative?

**Comment by JerryNixon** [comment]
Yet another source of frustration for UWP developers. 
The documentation still recommends this approach.

**Comment by benstevens48** [comment]
They did actually fix this eventually. I think if you use the latest version of the Microsoft.Services.Store.Engagement package it probably works. I'm still using the method I described above though because I don't need to provide metadata and I can avoid this additional NuGet package.

**Comment by JerryNixon** [comment]
I think a little testing will change your comment.

**Comment by benstevens48** [comment]
It appears to work for me, running on Windows 10 1903 and targeting version 1903. Did you follow the method on this page https://docs.microsoft.com/en-gb/windows/uwp/monetize/microsoft-store-services-sdk with the NuGet package option? I haven't tested the MSI installer option - it's possible that's still broken.

**Comment by riverar** [comment]
Make sure you're using Microsoft.Services.Store.Engagement 10.1901.28001 or higher. Anything below is broken.
