### ISSUE TITLE
copy/paste in audio capture devices

### ISSUE THREAD

**Issue by ericleigh007** [MicrosoftDocs/windows-uwp#1394]
In the para about audio capture devices, the text says to enumerate the audio render devices.  The code sample for that para is correct.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 411e7a56-a4da-c4c4-c401-4ae28c465ab6
* Version Independent ID: ad3bbc5a-9a63-f475-f7d9-5af28ba9acd6
* Content: [Audio graphs - Windows UWP applications](https://docs.microsoft.com/en-us/windows/uwp/audio-video-camera/audio-graphs)
* Content Source: [windows-apps-src/audio-video-camera/audio-graphs.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/audio-video-camera/audio-graphs.md)
* Product: **uwp**
* GitHub Login: @drewbatgit
* Microsoft Alias: **drewbat**

**Comment by drewbatgit** [comment]
Thanks for the feedback. It looks like the copy/paste error was in the paragraph, referring to the GetAudioRenderSelector method instead of the GetAudioCaptureSelector method. The code sample correctly shows the GetAudioCaptureSelector method. This error has been fixed: https://docs.microsoft.com/en-us/windows/uwp/audio-video-camera/audio-graphs
