### ISSUE TITLE
Information on overwriting files

### ISSUE THREAD

**Issue by colinkiama** [MicrosoftDocs/windows-uwp#1397]
With the writing example shown for streams, there's an issue where if the old data is longer than the new data you are trying to write, characters from the old data will appear at the end of the new data.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b36404b8-4385-81d9-2ee8-486f0a55fc37
* Version Independent ID: 7b6ce4df-6ab2-3aa6-059f-b38aa9ea8062
* Content: [Create, write, and read a file - Windows UWP applications](https://docs.microsoft.com/en-us/windows/uwp/files/quickstart-reading-and-writing-files)
* Content Source: [windows-apps-src/files/quickstart-reading-and-writing-files.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/files/quickstart-reading-and-writing-files.md)
* Product: **uwp**
* GitHub Login: @mcleanbyron
* Microsoft Alias: **mcleans**

**Comment by colinkiama** [comment]
Here's a potential solution to the issue:

using (var outputStream = stream.GetOutputStreamAt(0))
                {
                    // We'll add more code here in the next step.
                    using (var dataWriter = new Windows.Storage.Streams.DataWriter(outputStream))
                    {
                        dataWriter.WriteString("DataWriter has methods to write to various types, such as DataTimeOffset.");
                        // Changing stream size to the size of the data in dataWriter overwrites file contents
                        stream.Size = await dataWriter.StoreAsync();
                        await outputStream.FlushAsync();
                    }
                }
                stream.Dispose(); // Or use the stream variable (see previous code snippet) with a using statement as well.

**Comment by GrantMeStrength** [comment]
Thanks for the comment, and sorry for the delay in addressing it.

Thanks for pointing out the issue, and providing a solution. I will be reaching out to the author of the topic to see if this is a good solution to use.

Thanks for taking the time to leave feedback, and again, sorry for the delay. We do read bugs as they come in, but may not add comments immediately, which gives a poor impression - I apologize. -John

**Comment by GrantMeStrength** [comment]
The issue you're encountering when using UWP to create, write, and read a file—where old data appears at the end of the new data if the old data is longer than the new data you're writing—is likely due to not properly truncating the file before writing the new data. When you write to a file using some of the UWP APIs, if you don't explicitly set the file's length or overwrite the entire content, the file system keeps the original file size, leading to remnants of the old data at the end if the new data is shorter.

To solve this issue, you should ensure that you're either:

Truncating the file to zero length before writing new data, which effectively removes all old data before starting the write operation.
Overwriting the file entirely with new data, ensuring that the file only contains the new data you intend to write.
In UWP, when you're working with files, you typically use the Windows.Storage namespace. Here's how you can handle this:

Truncating the File Before Writing
When opening the file for writing, you can use the OpenAsync method with the FileAccessMode.ReadWrite mode and then set the size of the file to 0 to truncate it before writing:

csharp
Copy code
var storageFile = await Windows.Storage.ApplicationData.Current.LocalFolder.CreateFileAsync("sample.txt", Windows.Storage.CreationCollisionOption.OpenIfExists);
using (var fileStream = await storageFile.OpenAsync(Windows.Storage.FileAccessMode.ReadWrite))
{
    // Truncate the file
    fileStream.Size = 0;

    using (var outputStream = fileStream.GetOutputStreamAt(0))
    {
        using (var dataWriter = new Windows.Storage.Streams.DataWriter(outputStream))
        {
            dataWriter.WriteString("New data to write");
            await dataWriter.StoreAsync();
            await outputStream.FlushAsync();
        }
    }
}
Overwriting the File Completely
Alternatively, you can ensure the file is completely overwritten by using the CreationCollisionOption.ReplaceExisting when creating or opening the file. This option automatically removes any existing file and creates a new one, ensuring no old data remains:

csharp
Copy code
var storageFile = await Windows.Storage.ApplicationData.Current.LocalFolder.CreateFileAsync("sample.txt", Windows.Storage.CreationCollisionOption.ReplaceExisting);
using (var fileStream = await storageFile.OpenAsync(Windows.Storage.FileAccessMode.ReadWrite))
{
    using (var outputStream = fileStream.GetOutputStreamAt(0))
    {
        using (var dataWriter = new Windows.Storage.Streams.DataWriter(outputStream))
        {
            dataWriter.WriteString("New data to write");
            await dataWriter.StoreAsync();
            await outputStream.FlushAsync();
        }
    }
}
By using one of these approaches, you can ensure that when you write new data to a file in UWP, old data will not appear at the end of the new data, regardless of the old data's length.

(Answer generated by AI)
