### ISSUE TITLE
XAML design view support by cppwinrt

### ISSUE THREAD

**Issue by mkamilov** [MicrosoftDocs/windows-uwp#1398]
We cannot access events page of a Button and create event handler by double click in Blank App (C++/WinRT). Please see below SO question and its answer for more details: https://stackoverflow.com/questions/54226053/how-do-you-add-a-c-winrt-button-click-handler 

As per following closed issue XAML design view was not supported https://github.com/Microsoft/cppwinrt/issues/279

Can anyone check if C++/WinRT is supported in XAML design view and update documentation if not. 
 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dcf7899f-689a-80c4-2c94-9575f8fc5055
* Version Independent ID: b8873e37-f4cb-de98-46f2-f2eaf01e275d
* Content: [Introduction to C++/WinRT - Windows UWP applications](https://docs.microsoft.com/en-us/windows/uwp/cpp-and-winrt-apis/intro-to-using-cpp-with-winrt#)
* Content Source: [windows-apps-src/cpp-and-winrt-apis/intro-to-using-cpp-with-winrt.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/cpp-and-winrt-apis/intro-to-using-cpp-with-winrt.md)
* Product: **uwp**
* GitHub Login: @stevewhims
* Microsoft Alias: **stwhi**

**Comment by stevewhims** [comment]
Hi, @mkamilov, thanks for filing this issue. I've added the following info to the "Blank App (C++/WinRT)" subsection of this topic, since that's the project template that uses XAML as its UI.

"Visual Studio's XAML design surface support for C++/WinRT is close to parity with C#. One exception is the **Events** tab of the **Properties** window. With a C# project, you can use that tab to add event handlers; with a C++/WinRT project, that facility is not present. But see [Handle events by using delegates in C++/WinRT](https://docs.microsoft.com/windows/uwp/cpp-and-winrt-apis/handle-events) for info on how to add event handlers to your code."

This change should be live soon. Please let me know if there's anything further I can add. Thanks! ~Steve

**Comment by stevewhims** [comment]
Hi, @mkamilov, my update is now live on the topic. So I'll go ahead and close this issue now. Thanks again for raising this issue and for helping us improve the documentation! :) ~Steve

**Comment by werto165** [comment]
Hi is there any progress on this? In the docs here: https://docs.microsoft.com/en-us/windows/uwp/cpp-and-winrt-apis/handle-events it mentions that you can get event handlers using the properties -> lightning bolt. However, it still isn't present.
