### ISSUE TITLE
Not working in Insider builds

### ISSUE THREAD

**Issue by sylveon** [MicrosoftDocs/windows-uwp#1400]
I somehow can't get this working. An exception gets thrown when I try to create a DesktopWindowXamlSource, and when I read the message provided by the exception, it tells me my Windows is too old, but the math doesn't checks out, my Windows build is over the minimum version listed:
![](https://cdn.discordapp.com/attachments/204100839806205953/536958889384476673/unknown.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4665391f-f838-ae07-8591-d8f13f41a027
* Version Independent ID: 38b6b8ed-c3d2-97b1-9852-e3779b3ea281
* Content: [Using the UWP XAML hosting API in a desktop application - Windows UWP applications](https://docs.microsoft.com/en-us/windows/uwp/xaml-platform/using-the-xaml-hosting-api)
* Content Source: [windows-apps-src/xaml-platform/using-the-xaml-hosting-api.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/xaml-platform/using-the-xaml-hosting-api.md)
* Product: **uwp**
* GitHub Login: @jwmsft
* Microsoft Alias: **jimwalk**

**Comment by mcleanbyron** [comment]
Thanks for reporting this! I followed up with the engineering team and it turns out that this is a poorly worded error message. This is actually telling you that your application needs to target 18226 or later, not that the OS you are running on needs to be 18226 or later. The engineering team is opening a bug to improve this message.

To fix this, you need to do one of the following:

- If you have packaged your desktop application (using the Desktop Bridge), set the MaxVersionTested attribute of the TargetDeviceFamily element in your package manifest to "10.0.18226.0" or higher.
- If your desktop application is not packaged, add a maxVersionTested element to the compatibility section of your [application manifest](https://docs.microsoft.com/windows/desktop/sbscs/application-manifests), as shown in the example below. Note that this maxVersionTested element is new in the next major release of Windows coming after 1809, and therefore hasn't been documented yet.

```
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<assembly xmlns="urn:schemas-microsoft-com:asm.v1" manifestVersion="1.0">
    <assemblyIdentity version=SXS_ASSEMBLY_VERSION
       processorArchitecture=SXS_PROCESSOR_ARCHITECTURE
       name=SXS_ASSEMBLY_NAME
       type="win32"/>
    <description>PerceptionSimulationInput</description>
    <compatibility xmlns="urn:schemas-microsoft-com:compatibility.v1">
      <application>
        <maxversiontested Id="10.0.18226.0"/>
      </application>
    </compatibility>
</assembly>
```
I hope this helps!

**Comment by sylveon** [comment]
Unfortunately I've set that in both the package manifest and the application manifest, but the issue still occurs. Do I also need to build using the Insider SDK? Because I wasn't able to download it, the download page would error.

**Comment by mcleanbyron** [comment]
Yes, in order to successfully build an app that explicitly targets the 18317 build of the OS, I believe you would need to build the app using the [18317 build of the Insider SDK](https://blogs.windows.com/buildingapps/2019/01/22/windows-10-sdk-preview-build-18317-available-now) (or a later version of the SDK should probably work too).

**Comment by sylveon** [comment]
Unfortunately it still happens.

I've managed to install it (Edge downloaded it fine but Firefox couldn't). I set it as target SDK for my whole solution, cleaned it and then build+ran it (with the MaxVersionTested in both manifests still set to 18266). I still get the error.

**Comment by mcleanbyron** [comment]
Have you tried setting the MaxVersionTested value to 10.0.18317.0 in your package manifest? (I'm assuming your OS version is 18317). If you set MaxVersionTested to a lower value than the version of your OS, perhaps that is causing some problems.

**Comment by sylveon** [comment]
I made a simple C++ piece of code, then built it targeting the 18317 SDK and with the same manifest than my main app (included below), and the issue still occurs.

```cpp
#include <iostream>
#include <winrt/base.h>
#include <winrt/Windows.UI.Xaml.Hosting.h>

std::wostream &operator <<(std::wostream &stream, const winrt::hstring &str)
{
	return stream << static_cast<std::wstring_view>(str);
}

int main() try
{
	winrt::Windows::UI::Xaml::Hosting::DesktopWindowXamlSource{};
}
catch (const winrt::hresult_error &err)
{
	std::wcout << err.message();

	std::wcin.get();
}
```

```xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<assembly xmlns="urn:schemas-microsoft-com:asm.v1" manifestVersion="1.0">

    <compatibility xmlns="urn:schemas-microsoft-com:compatibility.v1"> 
        <application>
            <supportedOS Id="{8e0f7a12-bfb3-4fe8-b9a5-48fd50a15a9a}" />
            <maxVersionTested Id="10.0.18317.0" />
        </application> 
    </compatibility>

    <dependency>
        <dependentAssembly>
            <assemblyIdentity type="win32" name="Microsoft.Windows.Common-Controls" version="6.0.0.0" processorArchitecture="*" publicKeyToken="6595b64144ccf1df" language="*" />
        </dependentAssembly>
    </dependency>

    <trustInfo xmlns="urn:schemas-microsoft-com:asm.v3">
        <security>
            <requestedPrivileges>
                <requestedExecutionLevel level="asInvoker" uiAccess="false" />
            </requestedPrivileges>
        </security>
    </trustInfo>

    <application xmlns="urn:schemas-microsoft-com:asm.v3">
        <windowsSettings xmlns:ws2="http://schemas.microsoft.com/SMI/2016/WindowsSettings">
            <ws2:dpiAwareness>PerMonitorV2, unaware</ws2:dpiAwareness>
            <ws2:longPathAware>true</ws2:longPathAware>
        </windowsSettings>
    </application>

</assembly>
```

**Comment by marb2000** [comment]
@sylveon I have uploaded a basic sample to this repository: https://github.com/marb2000/XamlIslands/tree/master/RS5_Samples/Win32_CppWinRT_Platform_Controls 

It demonstrate how to use Xaml Island in plain Win32 app. I hope this helps.

**Comment by sylveon** [comment]
Unfortunately, no, it doesn't. I already have fully working XAML island code, it's just that after clean installing my machine to a more up to date insider build (I was lagging a few versions behind), it doesn't works anymore.

**Comment by marb2000** [comment]
Sorry about that. The Side by Side manifest should fix this error. Please, ping me at miguelrb at Microsoft dot com, so I will happy to assist you.
