### ISSUE TITLE
Suggestion to specify that this doc works only within Dev Mode

### ISSUE THREAD

**Issue by about0** [MicrosoftDocs/windows-uwp#1404]
I might be wrong here but I has had to spend some time just to figure out that Device Portal exists only  n Dev Mode. Might be useful for other devs.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e1946cd5-a111-ba09-e226-e5614104e995
* Version Independent ID: 20d262f4-ddc0-afcb-28fe-2a3c564280ce
* Content: [Xbox Device Portal REST API - Windows UWP applications](https://docs.microsoft.com/en-us/windows/uwp/xbox-apps/reference)
* Content Source: [windows-apps-src/xbox-apps/reference.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/xbox-apps/reference.md)
* Product: **uwp**
* GitHub Login: @KevinAsgari
* Microsoft Alias: **kevinasg**

**Comment by mattwojo** [comment]
Thank you for taking the time to let us know about this issue. Apologies for the delayed response. Due to the volume of feedback in our content, we are currently prioritizing new issues. 

If you believe your feedback still requires action to be taken, please let us know either directly in this thread, by filing a new issue, or by filing a [Pull Request ](https://github.com/MicrosoftDocs/windows-uwp/pulls) with your recommended updates.

Though the Issue will be marked as closed, we will still receive replies and are able to reopen the issue if necessary. 

Thanks again for taking the time to contribute.
