### ISSUE TITLE
Logo problems in classic win32

### ISSUE THREAD

**Issue by toredk** [MicrosoftDocs/windows-uwp#1409]
I am having problems with the application logo for my classic win32 application as it has a transparent background. This turns blue when displayed automatically in the toast notification. Is there any way to get around this?
Someone else having the same problem: https://stackoverflow.com/questions/34965325/how-to-set-notification-icon-background-of-windows-10-application-as-transparent

I have also tried to use the appLogoOverride but doesn't seem to be able to get the ms-appdata syntax to work correctly. Can you like to an example of this? But as far as I understand it will only add an extra logo to the single notification leaving my blue background application logo on top of it in the notification pane.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 53415734-dd31-7cf0-a82e-02566ed82396
* Version Independent ID: e5f82c08-6c9f-c628-9a45-5df000239ae4
* Content: [Send a local toast notification from desktop C# apps - Windows UWP applications](https://docs.microsoft.com/en-us/windows/uwp/design/shell/tiles-and-notifications/send-local-toast-desktop)
* Content Source: [windows-apps-src/design/shell/tiles-and-notifications/send-local-toast-desktop.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/design/shell/tiles-and-notifications/send-local-toast-desktop.md)
* Product: **uwp**
* GitHub Login: @mijacobs
* Microsoft Alias: **mijacobs**

**Comment by toredk** [comment]
I have tried to replace the ico file in the wix code - even with a icon containing the square Microsoft logo there will be added a blue background or edge.

The UWP examples from https://github.com/WindowsNotifications/ does not do the same so maybe this is a bug/limitation of the win32 implementation.

Any suggestions on how to work around this would be greatly appreciated as this looks quite unprofessional.

**Comment by andrewleader** [comment]
Thanks @toredk for reaching out. We're having the dev team investigate whether there's any supported path for classic Win32 apps to have a transparent logo background.

**Comment by andrewleader** [comment]
Hey @toredk, I confirmed with the devs that removing the icon backplate isn't supported for classic Win32 apps. You can upgrade to using the [Desktop Bridge](https://docs.microsoft.com/en-us/windows/uwp/porting/desktop-to-uwp-root), which will allow you to have full functionality over the app logo and removing the backplate. Let us know if you need help with that.

The team will also consider adding new support for plateless icons for classic Win32 apps, but we have no timelines to share for that functionality.

**Comment by toredk** [comment]
Unfortunately, the application does share values with our main application through the registry and ProgramData, so it is not a possibility to use the Desktop Bridge. I would think that we are not the only ones out there that has a legacy application (for us it is not even legacy) that wants to take advantage of the toast notifications.

Before implementing the Toasts notifications (and for Windows 7+8) we were using NotifyIcon.ShowBalloonTip with a 'standard' ToolTipIcon. On Windows 10 these BalloonTips are squeezed into toast notification and the icon does not get a blue background/edge. So, it seems to be possible somehow.

**Comment by andrewleader** [comment]
Thanks for letting us know that Desktop Bridge isn't an option for you! We're definitely considering improving the support for legacy classic Win32 apps; we simply don't have any timeline to share (but we realize it's important). We've added you to the list of consumers of this.

And as for it being possible somehow... through the toast notification framework, it's not possible today (new functionality would have to be added... the Action Center code always applies a background plate to any toast notifications sent via the classic Win32 mechanism, we would need to change that code to either (1) never show a background plate, or (2) optionally disable the background plate based on a setting that the app provides. It's certainly a very solveable problem, but we have lots of problems to solve and limited resources as does any product :)

**Comment by toredk** [comment]
Please let me know if you need more information when you get to look at improving the support.

I am just a bit puzzled as our old implementation with NotifyIcon.ShowBalloonTip is not added a blue background when shown through Toast Notifications on Windows 10.

What is the purpose of the blue background?

**Comment by andrewleader** [comment]
The blue background is the user's selected theme color, which is expressed in the Start tiles, apps list, and other accent location (like the running indicator on taskbar)

![image](https://user-images.githubusercontent.com/13246069/53525973-e4867300-3a97-11e9-96e5-eefd75f5fc2f.png)

The user can pick any color though, like red, green, etc.

![image](https://user-images.githubusercontent.com/13246069/53526040-0ed83080-3a98-11e9-89ec-b544f921e2d4.png)

There's no great answer as to why we chose to display the theme color backplate for Win32 notification icons, since Win32 icons already look good on a dark background (since that's how they're displayed on taskbar). However, this is how it happened to be implemented. Changing this behavior might break apps that were expecting this backplate (since that's how it's worked for a while), so we might have to introduce an opt-in ability for apps to disable the backplate (so that existing apps continue to have their backplate unless they decide they want to opt into the transparent behavior).

**Comment by toredk** [comment]
I get the point about having a user defined background color and in the star menu it makes a little more sense as the icons are bigger. The problem is that the icon in notifications and in the action center is quite small making the background color drown the actual icon. Some icons are of cause better than others but it is quite impossible to design an icon that would work with any of the available colors. I can supply you some examples if you like, or you could have a look at a notification from the desktop Outlook application. Even though the icon itself uses almost the same blue as the default background it completely takes over and almost hides the real icon.

**Comment by mijacobs** [comment]
Thanks for reaching out with your feedback. I'll work on updating the documentation with this info, but in the meantime you'll find quicker support by consulting our developer support resources. For community assistance with development questions I recommend that you ask on our [forums](https://social.msdn.microsoft.com/Forums/newthread?category=windowsapps&forum=wpdevelop&prof=required) or [StackOverflow](https://stackoverflow.com/questions). Otherwise, please see [the developer support page](https://developer.microsoft.com/windows/support) for your support options. If you get assistance through these other resources and believe that information would help us improve the docs, please come back and let us know.
