### ISSUE TITLE
No Xbox Live REST endpoint for in-game screenshot captures?

### ISSUE THREAD

**Issue by ziyafenn** [MicrosoftDocs/windows-uwp#1432]
Hello. I want to be able to access user's in-game screenshots captures through RESTful API but i don't see any endpoint for that. There are only endpoints for game clips.

Is documentation missing screenshot capture endpoints or there is no way to access those?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 24222aea-2a48-1dd7-b039-63493c510ff7
* Version Independent ID: b479539a-9e30-6fb4-9bd7-45b58cbc7a1c
* Content: [Game DVR URIs - Windows UWP applications](https://docs.microsoft.com/en-us/windows/uwp/xbox-live/xbox-live-rest/uri/dvr/atoc-reference-dvr)
* Content Source: [windows-apps-src/xbox-live/xbox-live-rest/uri/dvr/atoc-reference-dvr.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/xbox-live/xbox-live-rest/uri/dvr/atoc-reference-dvr.md)
* Product: **uwp**
* GitHub Login: @KevinAsgari
* Microsoft Alias: **kevinasg**

**Comment by mattwojo** [comment]
Thank you for taking the time to let us know about this issue. Apologies for the delayed response. Due to the volume of feedback in our content, we are currently prioritizing new issues. 

If you believe your feedback still requires action to be taken, please let us know either directly in this thread, by filing a new issue, or by filing a [Pull Request ](https://github.com/MicrosoftDocs/windows-uwp/pulls) with your recommended updates.

Though the Issue will be marked as closed, we will still receive replies and are able to reopen the issue if necessary. 

Thanks again for taking the time to contribute.
