### ISSUE TITLE
Pre-selecting the application

### ISSUE THREAD

**Issue by armouroflight** [MicrosoftDocs/windows-uwp#1438]
We know the window (in many cases by the window title) that we want to be able to capture beforehand so displaying the picker isn't a good user experience for us.  Is it possible to select the window rather than using the picker?  All the APIs that would allow this seem to have problems with some windows and certainly aren't convenient.  Is there a lower level API that this is based on that might allow more control?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f607a1db-43b3-bf1c-c6d1-6283c1280743
* Version Independent ID: c1c72175-3e9c-59f6-e30e-7d6f821c5876
* Content: [Screen capture - Windows UWP applications](https://docs.microsoft.com/en-us/windows/uwp/audio-video-camera/screen-capture)
* Content Source: [windows-apps-src/audio-video-camera/screen-capture.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/audio-video-camera/screen-capture.md)
* Product: **uwp**
* GitHub Login: @drewbatgit
* Microsoft Alias: **drewbat**

**Comment by drewbatgit** [comment]
Thanks for taking the time to let us know about this and we sincerely apologize for the delayed response. Due to the sheer volume of feedback in our repo, we are currently prioritizing new Issues. If you believe your feedback is still actionable, let us know either directly in this thread or by filing a new Issue and we’ll work to incorporate the suggestions into the documentation. Though the Issue will be marked as Closed, I will monitor any replies that come afterwards so feel free to treat this like an open Issue. 

In many cases, APIs require the user to initiate the action as a demonstration of consent . I suspect that is the case here. 
It looks like you have product feedback rather than documentation feedback. If you are looking for functionality that isn’t currently provided by the product, the [Feedback Hub app](https://support.microsoft.com/help/4021566/windows-10-send-feedback-to-microsoft-with-feedback-hub-app) is the right place to lobby for a change, a feature, or to make a suggestion.
