### ISSUE TITLE
Multiple Providers authentication a single userId?

### ISSUE THREAD

**Issue by Quico20** [MicrosoftDocs/windows-uwp#1452]
I'm trying to find out a way to create custom authentication using multiple authentication providers but with a single userid?? Could you please be so kind to point me in the right direction to achieve this goal?? what could be the best practices to achieve this?? I'm trying to do this with UWP and Azure??

So far i have been able to configure Authentication providers for facebook, microsoft, twitter and google with azure but it creates a different userid for each different provider. Is there a way to achieve authentication for all providers or any providers with a single userid???

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: de82f978-c033-3ead-fc10-751e9c27f0ba
* Version Independent ID: 61fcc224-1d5c-b3fd-22bb-a61a128229b1
* Content: [Authentication and user identity - Windows UWP applications](https://docs.microsoft.com/en-us/windows/uwp/security/authentication-and-user-identity)
* Content Source: [windows-apps-src/security/authentication-and-user-identity.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/security/authentication-and-user-identity.md)
* Product: **uwp**
* GitHub Login: @msatranjr
* Microsoft Alias: **misatran**

**Comment by hickeys** [comment]
Thanks for reaching out with your feedback. GitHub issues in this repo are for documentation bugs only, and unfortunately this seems more like a support request than a documentation bug. 

The best way to get support is by asking the community on [Microsoft Q&A](https://docs.microsoft.com/answers/topics/uwp.html?sort=active&filter=all) or [StackOverflow](https://stackoverflow.com/questions) 

For completeness' sake, here is a list of developer resources:

- [Microsoft Q&A](https://docs.microsoft.com/answers/topics/uwp.html?sort=active&filter=all) offers relevant and timely answers to your technical problems from a community of experts and Microsoft engineers.
- For community assistance with development questions, there are our [forums](https://social.msdn.microsoft.com/Forums/newthread?category=windowsapps&forum=wpdevelop&prof=required), and [StackOverflow](https://stackoverflow.com/questions).
- The [Windows developer support](https://developer.microsoft.com/windows/support) site explains other support options.
- The [Visual Studio developer community](https://developercommunity.visualstudio.com) is available, and responsive. The former User Voice feature is now there on the **Suggest a feature** tab, if you want to lobby for a change, a feature, or to make a suggestion.
- For developer issues, or suspected product bugs, there's [Microsoft Support](https://support.microsoft.com/contactus); a support engineer will look at the repro and see whether the issue is a Microsoft product bug, or something else. If it's a bug with a Microsoft product then the ticket will be free of charge.

If you receive assistance via any support resource and you believe that information would help us improve the docs, then please let us know or consider submitting a pull request.

Thanks,
Shawn

**Comment by riverar** [comment]
@hickeys  Why does the Storepolicy 0431 update also link to this issue?
