### ISSUE TITLE
Design question...

### ISSUE THREAD

**Issue by WeberPJ** [MicrosoftDocs/windows-uwp#1456]
Why would any software development manager ever allow their people to develop applications that are dependant on specific versions of an os when there is no guarantee that users of said software will be running that version? Am I the only one that sees this as problematic?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 728fa4a8-ade5-b31a-c07f-de82f2402a5b
* Version Independent ID: af5243e9-37a7-ed2f-a535-ce3ba3779b79
* Content: [Create and consume an app service - Windows UWP applications](https://docs.microsoft.com/en-us/windows/uwp/launch-resume/how-to-create-and-consume-an-app-service)
* Content Source: [windows-apps-src/launch-resume/how-to-create-and-consume-an-app-service.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/launch-resume/how-to-create-and-consume-an-app-service.md)
* Product: **uwp**
* GitHub Login: @eliotcowley
* Microsoft Alias: **elcowle**

**Comment by hkhmsft** [comment]
Thanks for taking the time to let us know about this and we sincerely apologize for the delayed response. Due to the sheer volume of feedback in our repo, we are currently prioritizing new Issues. If you believe your feedback is still actionable, let us know either directly in this thread or by filing a new Issue and we’ll work to incorporate the suggestions into the documentation. Though the Issue will be marked as Closed, I will monitor any replies that come afterwards so feel free to treat this like an open Issue. Many thanks!
