### ISSUE TITLE
Compatibility Matrix

### ISSUE THREAD

**Issue by AngelMunoz** [MicrosoftDocs/windows-uwp#1460]
&gt;tldr; Is there a compatibility matrix for `.net standard/.net core/winmd` I could not find it in the widndows runtime component docs

Hello everyone, I am currently trying to create a windows runtime component in C# for it to be consumed in a JS UWP app, I want to experiment a little bit  on reasons why should one chose `JS UWP` App over `Electron` based apps; One of the strong points to that would be that you have the entire .net ecosystem to be used as well in UWP not just `web/js` assets. 

But I was not able to find a reliable way to tell if certain library should be able to just work on my windows runtime component and lately be able to be consumed by a JS app

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 24c0134e-d62c-6b78-6f15-b9ba048967d4
* Version Independent ID: 6362d6c4-8197-e18d-537d-bdb991178eb7
* Content: [Creating Windows Runtime Components in C# and Visual Basic - Windows UWP applications](https://docs.microsoft.com/en-us/windows/uwp/winrt-components/creating-windows-runtime-components-in-csharp-and-visual-basic)
* Content Source: [windows-apps-src/winrt-components/creating-windows-runtime-components-in-csharp-and-visual-basic.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/winrt-components/creating-windows-runtime-components-in-csharp-and-visual-basic.md)
* Product: **uwp**
* GitHub Login: @stevewhims
* Microsoft Alias: **stwhi**

**Comment by stevewhims** [comment]
Hi, @AngelMunoz, this topic is the only one I'm aware of along those lines: [.NET for UWP apps](https://msdn.microsoft.com/library/windows/apps/mt185501.aspx). Whether you're writing a standalone UWP app, or a Windows Runtime Component (WRC), you have the same .NET surface available; assuming that you're writing in C# or Visual Basic. For a WRC, you can consume .NET from within that component (if it's written in C# or Visual Basic), but you must expose all of the WRC's own APIs as Windows Runtime APIs so that you can consume them from any WinRT language ([Walkthrough: Creating a Simple Windows Runtime component and calling it from JavaScript](https://docs.microsoft.com/windows/uwp/winrt-components/walkthrough-creating-a-simple-windows-runtime-component-and-calling-it-from-javascript)).

Here's another topic that might be helpful if you haven't seen it before.

* [Using the Windows Runtime in JavaScript](https://docs.microsoft.com/microsoft-edge/windows-runtime/using-the-windows-runtime-in-javascript)

Please let me know if there's anything further I can add.

~Steve

**Comment by AngelMunoz** [comment]
The docs are actually very good in creating/consuming the WRC, my doubts are more along on what limitations do I have on that WRC, does any .net code is compatible with it and then with my UWP App?
I'll kind of think along this line; I could reference a `.net standard` (or perhaps `net. core` too?) library in my WRC build my classes API surface and then reference that WRC in my App and it should work?

That is what it was not clear to me I guess

**Comment by stevewhims** [comment]
As I understand it, by consuming .NET from within your WRC, you're creating a dependency on that version of .NET. So, your WRC will be able to load and execute on any system that has that version of .NET installed (in fact, I believe there are ways of packaging that dependency up, so it travels along with the WRC). As far as the application that consumes the WRC is concerned, it will be consuming regular WinRT APIs that are exposed from the WRC. The consuming application won't know nor care how the WRC is implementing those WinRT APIs; whether it's using .NET or not.

More info here:
* [Announcing UWP Support for .NET Standard 2.0](https://blogs.msdn.microsoft.com/dotnet/2017/10/10/announcing-uwp-support-for-net-standard-2-0/)
* [.NET Standard FAQ](https://github.com/dotnet/standard/blob/master/docs/faq.md)

**Comment by stevewhims** [comment]
Hi, @AngelMunoz, I'll go ahead and close this issue now since it's been a while, and it feels resolved. Please reopen if I made a mistake in closing. ~Steve

**Comment by AngelMunoz** [comment]
@stevewhims Yes sorry for the lack of feedback there
