### ISSUE TITLE
The Account tool is Crashing

### ISSUE THREAD

**Issue by KingFraud** [MicrosoftDocs/windows-uwp#1461]
it crashes after 50 request My Gamertag is Gt: Fraud  and Captain we are good at Dbox we love xbox please fix this issue

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 35971a80-8b95-9201-2133-bfa4e4cddeca
* Version Independent ID: 2e574f12-313c-b28d-863d-46d3054a27de
* Content: [Xbox Live Account Tool - Windows UWP applications](https://docs.microsoft.com/en-us/windows/uwp/xbox-live/tools/xbox-live-account-tool)
* Content Source: [windows-apps-src/xbox-live/tools/xbox-live-account-tool.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/xbox-live/tools/xbox-live-account-tool.md)
* Product: **uwp**
* GitHub Login: @KevinAsgari
* Microsoft Alias: **kevinasg**

**Comment by mattwojo** [comment]
Thank you for taking the time to let us know about this issue. Apologies for the delayed response. Due to the volume of feedback in our content, we are currently prioritizing new issues. 

If you believe your feedback still requires action to be taken, please let us know either directly in this thread, by filing a new issue, or by filing a [Pull Request ](https://github.com/MicrosoftDocs/windows-uwp/pulls) with your recommended updates.

Though the Issue will be marked as closed, we will still receive replies and are able to reopen the issue if necessary. 

Thanks again for taking the time to contribute.
