### ISSUE TITLE
I can not connect the SurefaceHub for I can not connect the IP

### ISSUE THREAD

**Issue by lindexi** [MicrosoftDocs/windows-uwp#1467]
The SurefaceHub is in the other office that is not in the same LAN as me. How can I debug it with VisualStudio?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dcd496c1-48b8-8126-ab55-d24134fecbd4
* Version Independent ID: 0995fa01-b30b-3c58-5f11-49c07612ef55
* Content: [Test Surface Hub apps using Visual Studio - Windows UWP applications](https://docs.microsoft.com/en-us/windows/uwp/debug-test-perf/test-surface-hub-apps-using-visual-studio)
* Content Source: [windows-apps-src/debug-test-perf/test-surface-hub-apps-using-visual-studio.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/debug-test-perf/test-surface-hub-apps-using-visual-studio.md)
* Product: **uwp**
* GitHub Login: @eliotcowley
* Microsoft Alias: **elcowle**

**Comment by Karl-Bridge-Microsoft** [comment]
Hi @lindexi  - This feedback is not specifically about the documentation, but rather a support request. Please contact the following support channel.

- For developer issues, or suspected product bugs, there's [Microsoft Support](https://support.microsoft.com/contactus); a support engineer will look at the repro and see whether the issue is a Microsoft product bug, or something else. If it's a bug with a Microsoft product then the ticket will be free of charge.

Here are all of the developer support resources, for completeness.

- The [Feedback Hub app](https://support.microsoft.com/help/4021566/windows-10-send-feedback-to-microsoft-with-feedback-hub-app) is the right place to lobby for a change, a feature, or to make a suggestion.
- For community assistance with development questions, there are our [forums](https://social.msdn.microsoft.com/Forums/newthread?category=windowsapps&forum=wpdevelop&prof=required), and [StackOverflow](https://stackoverflow.com/questions).
- The [Windows developer support](https://developer.microsoft.com/windows/support) site explains other support options.
- The [Visual Studio developer community](https://developercommunity.visualstudio.com) is available, and responsive. The former User Voice feature is now there on the **Suggest a feature** tab, if you want to lobby for a change, a feature, or to make a suggestion.

If you receive assistance via any support resource, and you believe that information would help us improve the docs, then please come back and let us know.
