### ISSUE TITLE
RadioButton Template Issue on Windows Phone

### ISSUE THREAD

**Issue by Quico20** [MicrosoftDocs/windows-uwp#1470]
whenever I try to modify ControlTemplate within the Template property of a radiobutton it thrown a Xaml break error, but this only happens when I try to debug using a Windows Phone OS, a real device I'm using a Lumia 950 XL to debug on a WP enviroment.
But if I debug on a x86 or x64 my app works fine. this issue should be solve, It cant be possible that trying to change the control view throw a crash error. hopefully you can still supporting Windows Phone.

since i want to publish an app in WP, x86 and x64. if this isnt solve I'll be forced to divide my project in two, one for WP and the other for x86, x64 and ARM2.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 074b185c-0325-864f-7a29-ba8dee7572ef
* Version Independent ID: bb3b9c3a-6bf9-e32d-71fa-fe4a334726cb
* Content: [Guidelines for radio buttons - Windows UWP applications](https://docs.microsoft.com/en-us/windows/uwp/design/controls-and-patterns/radio-button)
* Content Source: [windows-apps-src/design/controls-and-patterns/radio-button.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/design/controls-and-patterns/radio-button.md)
* Product: **uwp**
* GitHub Login: @jwmsft
* Microsoft Alias: **jimwalk**

**Comment by YuliKl** [comment]
@Quico20 - I'm sorry you're having problems with the RadioButton template. Since yours is a product issue, not a problem in the documentation, would you mind creating a [new bug](https://github.com/Microsoft/microsoft-ui-xaml/issues/new/choose) report in the [microsoft-ui-xaml GitHub](https://github.com/Microsoft/microsoft-ui-xaml)? Please include the code that's causing problems when you open the issue so that our engineers can investigate.

**Comment by jevansaks** [comment]
Windows Phone is end-of-life at the end of this calendar year so closing this issue.
