### ISSUE TITLE
Needs More Troubleshooting Info

### ISSUE THREAD

**Issue by Romans-I-XVI** [MicrosoftDocs/windows-uwp#1483]
The documentation just says "the modal is run through a few checks" and that if any of these checks fail you may get a "Sorry, there was an issue adding your email address". That is not enough information to be useful, I am getting this error and it's not a problem with my Xbox Live account as I can log in to it just fine and have tried with multiple accounts always getting the same error.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4cfddd1d-f430-c53c-fcdf-26fdd969035f
* Version Independent ID: 6af5f347-571a-6a1d-f9df-a26da3f23f79
* Content: [Authorize Xbox Live accounts in your test environment - Windows UWP applications](https://docs.microsoft.com/en-us/windows/uwp/xbox-live/get-started-with-creators/authorize-xbox-live-accounts)
* Content Source: [windows-apps-src/xbox-live/get-started-with-creators/authorize-xbox-live-accounts.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/xbox-live/get-started-with-creators/authorize-xbox-live-accounts.md)
* Product: **uwp**
* GitHub Login: @KevinAsgari
* Microsoft Alias: **kevinasg**

**Comment by mattwojo** [comment]
Thank you for taking the time to let us know about this issue. Apologies for the delayed response. Due to the volume of feedback in our content, we are currently prioritizing new issues. 

If you believe your feedback still requires an update to the documentation, please let us know either directly in this thread, by filing a new issue, or by filing a [Pull Request ](https://github.com/MicrosoftDocs/windows-uwp/pulls) with your recommended updates.

Though the Issue will be marked as closed, we will still receive replies and are able to reopen the issue if necessary. 

Thanks again for taking the time to contribute.
