### ISSUE TITLE
Activation app does not show the activation code

### ISSUE THREAD

**Issue by david-pratt** [MicrosoftDocs/windows-uwp#1505]
The activation app opens and shows the welcome screen.  Click "Next" and the application exits and you're back to the home screen.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cc064e49-5f24-ff80-d511-7f1947fc39da
* Version Independent ID: b8ad47c2-8264-c232-167f-b9ee69d6dce1
* Content: [Xbox One Developer Mode activation - Windows UWP applications](https://docs.microsoft.com/en-us/windows/uwp/xbox-apps/devkit-activation)
* Content Source: [windows-apps-src/xbox-apps/devkit-activation.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/xbox-apps/devkit-activation.md)
* Product: **uwp**
* GitHub Login: @KevinAsgari
* Microsoft Alias: **kevinasg**

**Comment by mattwojo** [comment]
Thank you for taking the time to let us know about this issue. Apologies for the delayed response. Due to the volume of feedback in our content, we are currently prioritizing new issues. 

If you believe your feedback still requires an update to the documentation, please let us know either directly in this thread, by filing a new issue, or by filing a [Pull Request ](https://github.com/MicrosoftDocs/windows-uwp/pulls) with your recommended updates.

Though the Issue will be marked as closed, we will still receive replies and are able to reopen the issue if necessary. 

Thanks again for taking the time to contribute.
