### ISSUE TITLE
'Manage keys for an Azure AD application' outdated?

### ISSUE THREAD

**Issue by vishnu4** [MicrosoftDocs/windows-uwp#1508]
I'm trying to go through the step on building my UWP app directly to the microsoft store with https://marketplace.visualstudio.com/items?itemName=MS-RDX-MRO.windows-store-publish, which let me to this page.  I've gotten far enough to the point where you ask me to build a key for my application.  Supposedly this is in the 'developer settings/users/' page, where i can then click on the application and see this option on the next page, but it is not.  I just see the application name, tenant/client ID, and Roles that i can grant to the app.  Nothing else.  Has the ability to create an application key been moved?  If so, the documentation should be updated

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7bf973bd-e0d9-19b0-ad24-e09a83d3a2a9
* Version Independent ID: 25d0bdd2-0487-6742-b4bd-abc1e3ee6be8
* Content: [Add users, groups, and Azure AD applications to your Partner Center account - Windows UWP applications](https://docs.microsoft.com/en-us/windows/uwp/publish/add-users-groups-and-azure-ad-applications)
* Content Source: [windows-apps-src/publish/add-users-groups-and-azure-ad-applications.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/publish/add-users-groups-and-azure-ad-applications.md)
* Product: **uwp**
* GitHub Login: @lauradolan
* Microsoft Alias: **ladolan**

**Comment by lauradolan** [comment]
Please open a support case about this issue here http://aka.ms/storesupport. Thanks!

**Comment by vishnu4** [comment]
so i can only get help with this if i pay $500?  The issue is also with your github page.  you have instructions that are wrong and can't be followed.  You'll need to update the instructions regardless of anything else, won't you?

**Comment by lauradolan** [comment]
The reason I’m closing this doc feedback issue and suggesting you contact support is because you should normally see the "Add new key" button when viewing an Azure AD application you've added to your account in Partner Center, as described at https://docs.microsoft.com/en-us/windows/uwp/publish/add-users-groups-and-azure-ad-applications#manage-keys-for-an-azure-ad-application.  

Since you’re experiencing this issue, I would suggest opening a support request at http://aka.ms/storesupport. Under "Contact us", select "Dashboard issue" then "Account setup and management". There is a live chat option (during business hours) or you can submit an incident.
