### ISSUE TITLE
Error of data binding in DataTemplate

### ISSUE THREAD

**Issue by hadayago** [MicrosoftDocs/windows-uwp#1511]
In ImageGridView_MobileItemTemplate, source of Image element could be data binding to ImageSource instead of ImagePreview.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 69746a38-2c7a-45f6-765f-2c5801a27193
* Version Independent ID: 64ee3bd3-91f2-018a-8ea7-28ae91e109ce
* Content: [Create adaptive layouts tutorial - Windows UWP applications](https://docs.microsoft.com/en-us/windows/uwp/design/basics/xaml-basics-adaptive-layout)
* Content Source: [windows-apps-src/design/basics/xaml-basics-adaptive-layout.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/design/basics/xaml-basics-adaptive-layout.md)
* Product: **uwp**
* GitHub Login: @jwmsft
* Microsoft Alias: **jimwalk**

**Comment by jevansaks** [comment]
The sample has drifted from the docs. @hadayago Does the sample work and the doc just needs to be updated?

**Comment by Karl-Bridge-Microsoft** [comment]
Thanks for taking the time to let us know about this issue and we sincerely apologize for the delayed response. 

As this page has been updated since you reported the issue, and the sheer volume of of feedback in this repo requires us to prioritize new issues, we're closing this one due to age and lack of activity.

If you think the issue still exists and should be addressed, please open a new issue with any details/suggestions you think might be helpful.
