### ISSUE TITLE
Open contained links within articles on docs.microsoft.com in new tabs

### ISSUE THREAD

**Issue by jebeld17** [MicrosoftDocs/windows-uwp#1516]
Please open contained links within articles on docs.microsoft.com in new tabs as a default action.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c403f296-ed93-2625-e414-f009194bf118
* Version Independent ID: aa0212c4-481c-7eaf-233d-c5b3f286d004
* Content: [Package an app using the Desktop App Converter (Desktop Bridge) - Windows UWP applications](https://docs.microsoft.com/en-us/windows/uwp/porting/desktop-to-uwp-run-desktop-app-converter#feedback)
* Content Source: [windows-apps-src/porting/desktop-to-uwp-run-desktop-app-converter.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/porting/desktop-to-uwp-run-desktop-app-converter.md)
* Product: **uwp**
* GitHub Login: @hickeys
* Microsoft Alias: **hickeys**

**Comment by hickeys** [comment]
It looks like you have product feedback rather than documentation feedback. If you are looking for functionality that isn’t currently provided by the product, please use the [Windows developer feedback site](https://wpdev.uservoice.com/). We’d be happy to have this on record, where others can view it and upvote it.
