### ISSUE TITLE
Not a complete sentence

### ISSUE THREAD

**Issue by PaulaScholz** [MicrosoftDocs/windows-uwp#1523]
"Otherwise your background task may be terminated prematurely when the Run method (or OnBackgroundActivated method in the case of in-process background tasks)."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8141e120-645d-a52a-cefc-aa77fac6b3f7
* Version Independent ID: 043c5b34-759d-b58c-7d02-f3cad6ec1f2f
* Content: [Guidelines for background tasks - Windows UWP applications](https://docs.microsoft.com/en-us/windows/uwp/launch-resume/guidelines-for-background-tasks#feedback)
* Content Source: [windows-apps-src/launch-resume/guidelines-for-background-tasks.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/launch-resume/guidelines-for-background-tasks.md)
* Product: **uwp**
* GitHub Login: @knicholasa
* Microsoft Alias: **nichola**

**Comment by knicholasa** [comment]
Thanks for finding this. I've update the document. The changes should be visible online in a day or two. The sentence should be "Otherwise your background task may be terminated prematurely when the Run method returns (or the OnBackgroundActivated method in the case of in-process background tasks)."
