### ISSUE TITLE
does  not work as expected

### ISSUE THREAD

**Issue by bswieser** [MicrosoftDocs/windows-uwp#1528]
ms-people:search?SearchString=Name

Does not work - it will populate the search box, but does not display the top result. You need to hit space or enter...

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a1d62e94-aa32-467f-fa2d-14e630543e1f
* Version Independent ID: 2ab8ae17-c66e-3bd8-2a28-a8804a06a66a
* Content: [Launch the People app - Windows UWP applications](https://docs.microsoft.com/en-us/windows/uwp/launch-resume/launch-people-apps)
* Content Source: [windows-apps-src/launch-resume/launch-people-apps.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/launch-resume/launch-people-apps.md)
* Product: **uwp**
* GitHub Login: @knicholasa
* Microsoft Alias: **nichola**

**Comment by knicholasa** [comment]
Hi, 

Thanks for reaching out with your feedback. Feedback here is for documentation issues. If you think this is a bug, please use the product feedback tool at the bottom of the docs page to leave feedback. For community assistance with development questions I recommend that you ask on our [forums](https://social.msdn.microsoft.com/Forums/newthread?category=windowsapps&forum=wpdevelop&prof=required) or [StackOverflow](https://stackoverflow.com/questions). Otherwise, please see [the developer support page](https://developer.microsoft.com/windows/support) for your support options.

Nick
