### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by MahmoudSaid356** [MicrosoftDocs/windows-uwp#1533]
Do you have any soon plan to support "urn:mpeg:dash:profile:isoff-on-demand:2011" profile?

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cb6fc0d8-7067-6d9c-fe52-4dc89fb24d48
* Version Independent ID: 493d1fd9-2f9a-38f6-c97d-508c5e5ba20e
* Content: [Dynamic Adaptive Streaming over HTTP (DASH) profile support - Windows UWP applications](https://docs.microsoft.com/en-gb/windows/uwp/audio-video-camera/dash-profile-support)
* Content Source: [windows-apps-src/audio-video-camera/dash-profile-support.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/audio-video-camera/dash-profile-support.md)
* Product: **uwp**
* GitHub Login: @drewbatgit
* Microsoft Alias: **drewbat**

**Comment by hkhmsft** [comment]
Thanks for taking the time to let us know about this. However, this feels not so much like feedback specifically about the documentation but rather like a support request. Here are all of the developer support resources, for completeness.

 - The [Feedback Hub app](https://support.microsoft.com/help/4021566/windows-10-send-feedback-to-microsoft-with-feedback-hub-app) is the right place to lobby for a change, a feature, or to make a suggestion.
 - For community assistance with development questions, there are our [forums](https://social.msdn.microsoft.com/Forums/newthread?category=windowsapps&forum=wpdevelop&prof=required), and [StackOverflow](https://stackoverflow.com/questions).
 - The [Windows developer support](https://developer.microsoft.com/windows/support) site explains other support options.
 - The [Visual Studio developer community](https://developercommunity.visualstudio.com) is available, and responsive. The former User Voice feature is now there on the **Suggest a feature** tab, if you want to lobby for a change, a feature, or to make a suggestion.
 - For developer issues, or suspected product bugs, there's [Microsoft Support](https://support.microsoft.com/contactus); a support engineer will look at the repro and see whether the issue is a Microsoft product bug, or something else. If it's a bug with a Microsoft product then the ticket will be free of charge.
 
 If you receive assistance via any support resource, and you believe that information would help us improve the docs, then please come back and let us know.
