### ISSUE TITLE
Update XDK docs to point to this

### ISSUE THREAD

**Issue by liviodlc** [MicrosoftDocs/windows-uwp#1534]
All of the Achievement-related documents in the XDK are referring to the old Data Platform API. These docs DO NOT mention that the Data Platform API has been replaced with a new system, and they also do not mention that the docs for the new Achievement system is on a different documentation website. Please add a page or something to the XDK docs informing users about this.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4382009e-8436-d1d7-a557-4b3b0ab8ab21
* Version Independent ID: cbd37ae6-8676-4429-875e-ba000e915f6f
* Content: [Achievements - Windows UWP applications](https://docs.microsoft.com/en-us/windows/uwp/xbox-live/achievements-2017/achievements#feedback)
* Content Source: [windows-apps-src/xbox-live/achievements-2017/achievements.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/xbox-live/achievements-2017/achievements.md)
* Product: **uwp**
* GitHub Login: @KevinAsgari
* Microsoft Alias: **kevinasg**

**Comment by mattwojo** [comment]
Thank you for taking the time to let us know about this issue. Apologies for the delayed response. Due to the volume of feedback in our content, we are currently prioritizing new issues. 

If you believe your feedback still requires an update to the documentation, please let us know either directly in this thread, by filing a new issue, or by filing a [Pull Request ](https://github.com/MicrosoftDocs/windows-uwp/pulls) with your recommended updates.

Though the Issue will be marked as closed, we will still receive replies and are able to reopen the issue if necessary. 

Thanks again for taking the time to contribute.
