### ISSUE TITLE
Confused about values

### ISSUE THREAD

**Issue by hawesg104** [MicrosoftDocs/windows-uwp#1545]
Howdy - I'm confused about the values being returned for `errorCount` and `deviceCount`. I'm seeing non-integer responses such as 1.5. Is this a calculated value that I need additional context to make sense of?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 78fd2953-4afe-5382-b336-129749b00fd3
* Version Independent ID: d6443723-7deb-0faa-3fff-e687ae1e1f52
* Content: [Get error reporting data for your app - Windows UWP applications](https://docs.microsoft.com/en-us/windows/uwp/monetize/get-error-reporting-data#feedback)
* Content Source: [windows-apps-src/monetize/get-error-reporting-data.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/monetize/get-error-reporting-data.md)
* Product: **uwp**
* GitHub Login: @Karl-Bridge-Microsoft
* Microsoft Alias: **kbridge**

**Comment by GrantMeStrength** [comment]
My understanding is that these values are not integers because they are averaged over a specific period of time set in the aggregationLevel value. If for example, the time period was a week, you might get a number like 6.25, if there were 50 devices measured over the entire month. Hope this helps! -john
