### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by jonaserikssonnet** [MicrosoftDocs/windows-uwp#1547]
"Social C Sample AsyncIntegration.cpp" is broken.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b74a8977-3a86-719c-01a9-0d8ef98d1504
* Version Independent ID: 2147a655-135c-5c30-1be6-97aa6b7aa678
* Content: [Asynchronous C API calling patterns - Windows UWP applications](https://review.docs.microsoft.com/en-us/windows/uwp/xbox-live/flatc-async-patterns?branch=xblmobile-master#feedback)
* Content Source: [windows-apps-src/xbox-live/flatc-async-patterns.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/xbox-live/flatc-async-patterns.md)
* Product: **uwp**
* GitHub Login: @KevinAsgari
* Microsoft Alias: **kevinasg**

**Comment by stevewhims** [comment]
Hi, @jonaserikssonnet, and thank you for filing this issue (I just noticed it, so I did some investigation).

I've hunted for the "Asynchronous C API calling patterns - Windows UWP applications" topic, and for the original source file, and I can't find them. It looks like the topic has been removed or relocated somewhere beyond our reach.

This issue is over a year old, so that might account for the topic being missing. I'll go ahead and close this now in light of all that.

If you find a problem with an extant topic then feel free to leave a comment on that one.

Thanks again!
Steve
