### ISSUE TITLE
Is Developer partner account required for using Windows.Networking.Vpn UWP interface APIs

### ISSUE THREAD

**Issue by defaultshr** [MicrosoftDocs/windows-uwp#1549]
Kindly clarify if developer partner account is required for getting Windows.Networking.Vpn UWP APIs to work on the Visual Studio 2017 community edition. 

Currently I have declared VPN restricted capability in the manifest. Compilation is fine. However, I do not see VPN Plugin APIs getting triggered. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fdfe599a-af5b-acbc-1405-d1030d9f6661
* Version Independent ID: 85857337-8448-af63-b543-f01ef482ea09
* Content: [App capability declarations - Windows UWP applications](https://docs.microsoft.com/en-us/windows/uwp/packaging/app-capability-declarations#special-and-restricted-capabilities)
* Content Source: [windows-apps-src/packaging/app-capability-declarations.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/packaging/app-capability-declarations.md)
* Product: **uwp**
* GitHub Login: @mcleanbyron
* Microsoft Alias: **mcleans**

**Comment by defaultshr** [comment]
Basically, even though I am launching application in debug environment, VPN plugin API don't get triggered. Therefore, I am asking if developer partner account is required to get these APIs working while we develop application.

**Comment by mcleanbyron** [comment]
Thanks for reaching out to us with your question. APIs that require restricted capabilities should work while sideloading your app on a local development machine. However, you do need to be granted access by Microsoft to use the capability in the Store version of your app, and you can request this when you submit your app to the Store. See [restricted capabilities](https://docs.microsoft.com/en-us/windows/uwp/packaging/app-capability-declarations#restricted-capabilities) for more info. 

It sounds like you are sideloading your app in your debug environment but you're not able to get the VPN code to work. I'm sorry you're encountering this problem. However, this repo is specifically for feedback on the docs, and it is not intended as a resource for technical support. For community assistance I recommend that you ask on our [forums](https://social.msdn.microsoft.com/Forums/newthread?category=windowsapps&forum=wpdevelop&prof=required) or [StackOverflow](https://stackoverflow.com/questions) and provide as much detail as you can about your code and what specifically isn't getting triggered. Otherwise, please see [the developer support page](https://developer.microsoft.com/windows/support) for your support options.
