### ISSUE TITLE
singleMediaGroupSearc

### ISSUE THREAD

**Issue by bensonlee311** [MicrosoftDocs/windows-uwp#1556]
Why [/media/en-us/singleMediaGroupSearch?q=vector&desiredMediaItemTypes=DGame&fields=all] always return only ImpressionGuid ? It can work fine several days ago

---
#### 文件詳細資料

⚠ *請勿編輯此區段。 這是 docs.microsoft.com ➟ GitHub 問題連結的必要項。*

* ID: 0b4f292e-b324-0379-bb1f-fca0a051928d
* Version Independent ID: 7bfb7dd3-e4e8-e72f-54e0-c8d036071b7a
* Content: [GET (media/{marketplaceId}/singleMediaGroupSearch) - Windows UWP applications](https://docs.microsoft.com/zh-tw/windows/uwp/xbox-live/xbox-live-rest/uri/marketplace/uri-medialocalesinglemediagroupsearchget)
* Content Source: [windows-apps-src/xbox-live/xbox-live-rest/uri/marketplace/uri-medialocalesinglemediagroupsearchget.md](https://github.com/MicrosoftDocs/windows-uwp-pr.zh-tw/blob/live-sxs/windows-apps-src/xbox-live/xbox-live-rest/uri/marketplace/uri-medialocalesinglemediagroupsearchget.md)
* Product: **uwp**
* GitHub Login: @KevinAsgari
* Microsoft Alias: **kevinasg**

**Comment by hkhmsft** [comment]
Thanks for taking the time to let us know about this. However, this feels not so much like feedback specifically about the documentation but rather like a support request. Here are all of the developer support resources, for completeness.

 - The [Feedback Hub app](https://support.microsoft.com/help/4021566/windows-10-send-feedback-to-microsoft-with-feedback-hub-app) is the right place to lobby for a change, a feature, or to make a suggestion.
 - For community assistance with development questions, there are our [forums](https://social.msdn.microsoft.com/Forums/newthread?category=windowsapps&forum=wpdevelop&prof=required), and [StackOverflow](https://stackoverflow.com/questions).
 - The [Windows developer support](https://developer.microsoft.com/windows/support) site explains other support options.
 - The [Visual Studio developer community](https://developercommunity.visualstudio.com) is available, and responsive. The former User Voice feature is now there on the **Suggest a feature** tab, if you want to lobby for a change, a feature, or to make a suggestion.
 - For developer issues, or suspected product bugs, there's [Microsoft Support](https://support.microsoft.com/contactus); a support engineer will look at the repro and see whether the issue is a Microsoft product bug, or something else. If it's a bug with a Microsoft product then the ticket will be free of charge.
 
 If you receive assistance via any support resource, and you believe that information would help us improve the docs, then please come back and let us know.
