### ISSUE TITLE
Foreground event for notification added/dismissed

### ISSUE THREAD

**Issue by dajbych** [MicrosoftDocs/windows-uwp#1557]
Is the bug with CPU loops when listening to notifications in foreground already fixed? If yes – what is the minimal Windows version where the functionality can be safely used?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d7bf8a3a-3e67-f3b9-f63c-ca53383d7f19
* Version Independent ID: b64f8103-55c0-d8bd-52b9-b4b9f7b63fdf
* Content: [Notification listener - Windows UWP applications](https://docs.microsoft.com/en-us/windows/uwp/design/shell/tiles-and-notifications/notification-listener#feedback)
* Content Source: [windows-apps-src/design/shell/tiles-and-notifications/notification-listener.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/design/shell/tiles-and-notifications/notification-listener.md)
* Product: **uwp**
* GitHub Login: @mijacobs
* Microsoft Alias: **mijacobs**

**Comment by andrewleader** [comment]
Hey @dajbych, thanks for reaching out! Looks like we fixed this in Build 17763 / October 2018 Update / Version 1809, which is the current latest non-Insider public version of Windows. I'll update the docs!

**Comment by anemomylos** [comment]
Is it possible to use the notification listener from a desktop app (not bridged) or it is only for UWP apps? Thanks.

**Comment by mijacobs** [comment]
Thanks for reaching out with your feedback. I'll work on updating the documentation with this info, but in the meantime you'll find quicker support by consulting our developer support resources. For community assistance with development questions I recommend that you ask on our [forums](https://social.msdn.microsoft.com/Forums/newthread?category=windowsapps&forum=wpdevelop&prof=required) or [StackOverflow](https://stackoverflow.com/questions). Otherwise, please see [the developer support page](https://developer.microsoft.com/windows/support) for your support options. If you get assistance through these other resources and believe that information would help us improve the docs, please come back and let us know.
