### ISSUE TITLE
20hz does not work with the Audio frame input node example

### ISSUE THREAD

**Issue by aljohnston112** [MicrosoftDocs/windows-uwp#1559]
I copied the example and tried 20hz instead of 1000hz and was surprised to hear a higher frequency playing.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 589e2eda-b495-126e-553d-65ebee87bd3c
* Version Independent ID: a850ef9a-9d08-64a2-dd6b-584d2059f392
* Content: [Audio graphs - Windows UWP applications](https://docs.microsoft.com/en-us/windows/uwp/audio-video-camera/audio-graphs#feedback)
* Content Source: [windows-apps-src/audio-video-camera/audio-graphs.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/audio-video-camera/audio-graphs.md)
* Product: **uwp**
* GitHub Login: @drewbatgit
* Microsoft Alias: **drewbat**

**Comment by drewbatgit** [comment]
Thanks for taking the time to let us know about this and we sincerely apologize for the delayed response. Due to the sheer volume of feedback in our repo, we are currently prioritizing new Issues. If you believe your feedback is still actionable, let us know either directly in this thread or by filing a new Issue and we’ll work to incorporate the suggestions into the documentation. Though the Issue will be marked as Closed, I will monitor any replies that come afterwards so feel free to treat this like an open Issue. 

The wave generation in the sample code isn't very sophisticated, so it's likely that you're hearing harmonics or other artifacts related to the waveform. The scope of our feedback channel here on GitHub covers specific documentation fixes, I can help redirect you to the right support channel to get an answer to your question. The community of experts and Microsoft Engineers over at [Microsoft Q&A](https://docs.microsoft.com/en-us/answers/topics/windows-uwp.html) offer timely answers to a multitude of technical questions surrounding windows-uwp.

If you do create a thread over at Microsoft Q&A, it would be fantastic if you could share that link here so I can track the progress and potentially incorporate the technical details into our documentation.
