### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by wldevries** [MicrosoftDocs/windows-uwp#1569]
&gt; When you use an ItemsRepeater, you should provide scrolling functionality by wrapping it in a ScrollViewer or Scroller control.
Link to Scroller is broken

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d5ae7144-fa89-cd61-6ff7-8bb4a765e6f8
* Version Independent ID: 03f41125-77b9-5761-2aba-9b3eef17e121
* Content: [ItemsRepeater - Windows UWP applications](https://docs.microsoft.com/en-us/windows/uwp/design/controls-and-patterns/items-repeater)
* Content Source: [windows-apps-src/design/controls-and-patterns/items-repeater.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/design/controls-and-patterns/items-repeater.md)
* Product: **uwp**
* Technology: **design**
* GitHub Login: @jwmsft
* Microsoft Alias: **jimwalk**

**Comment by micahl** [comment]
@jwmsft we can close this.  The last set of changes to this page removed the 'or Scroller control'.  Fwiw, I believe the link to Scroller was broken because it's under the Primitives namespace instead of just Controls.  Here's the working link for the prerelease type:
https://docs.microsoft.com/en-us/uwp/api/microsoft.ui.xaml.controls.primitives.scroller
