### ISSUE TITLE
implemented how?

### ISSUE THREAD

**Issue by wyrdo** [MicrosoftDocs/windows-uwp#1576]
The document may have said, but if it did, I missed it.

The "ms-settings:" URI is handled by the Explorer shell I think?  All of these URIs are, yes?

So, that would mean, that if explorer.exe weren't running, it might not be possible for a user to access ms-settings.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ae2608d3-38b8-2404-d138-1ba17772e72c
* Version Independent ID: 535d38b3-3174-fc77-ec58-7b5732ba803c
* Content: [Launch the default app for a URI - Windows UWP applications](https://docs.microsoft.com/en-us/windows/uwp/launch-resume/launch-default-app#feedback)
* Content Source: [windows-apps-src/launch-resume/launch-default-app.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/launch-resume/launch-default-app.md)
* Product: **uwp**
* Technology: **processes-and-threading**
* GitHub Login: @knicholasa
* Microsoft Alias: **nichola**

**Comment by knicholasa** [comment]
Thanks for reaching out with your feedback. Comments left here are meant for documentation feedback, and unfortunately we cannot provide technical support. For community assistance with development questions I recommend that you ask on our [forums](https://social.msdn.microsoft.com/Forums/newthread?category=windowsapps&forum=wpdevelop&prof=required) or [StackOverflow](https://stackoverflow.com/questions). Otherwise, please see [the developer support page](https://developer.microsoft.com/windows/support) for your support options.
