### ISSUE TITLE
Choose default app by protocol Setting Page

### ISSUE THREAD

**Issue by saubermfg** [MicrosoftDocs/windows-uwp#1577]
It seems like the "Choose default app by protocol" setting page, which is accessible with a link in the "ms-settings:defaultapps" page, should be something that could be linked directly to. Furthermore, since this list can be very long, it would also be nice to be able to link directly to a certain protocol.

Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 987ec16c-9456-93a4-177a-dbd563be7eb7
* Version Independent ID: f41f0344-f7f6-f092-a6bf-fc4184a9b460
* Content: [Launch the Windows Settings app - Windows UWP applications](https://docs.microsoft.com/en-us/windows/uwp/launch-resume/launch-settings-app#feedback)
* Content Source: [windows-apps-src/launch-resume/launch-settings-app.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/launch-resume/launch-settings-app.md)
* Product: **uwp**
* Technology: **processes-and-threading**
* GitHub Login: @knicholasa
* Microsoft Alias: **nichola**

**Comment by knicholasa** [comment]
It looks like you have product feedback rather than documentation feedback. If you are looking for functionality that isn’t currently provided by the product, please use the [Windows developer feedback site](https://wpdev.uservoice.com/). We’d be happy to have this on record, where others can view it and upvote it.
