### ISSUE TITLE
Create or edit a SoftwareBitmap programmatically doesn't show anything.

### ISSUE THREAD

**Issue by Gavin-Williams** [MicrosoftDocs/windows-uwp#1581]
I can't get this code to show anything. There is no way to invalidate the contents for the Xaml image control like there is for WriteableBitmap. And also, it has an insane amount of garbage collection, making it unusable for any realtime / graphical application.

Can we please see a sample for this demonstrating zero garbage collection and 1920x1080@60fps

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cf40397b-367e-ea99-9019-391cd86c221a
* Version Independent ID: fd1eb02e-f989-17ed-0829-41c275d281b6
* Content: [Create, edit, and save bitmap images - Windows UWP applications](https://docs.microsoft.com/en-us/windows/uwp/audio-video-camera/imaging)
* Content Source: [windows-apps-src/audio-video-camera/imaging.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/audio-video-camera/imaging.md)
* Product: **uwp**
* Technology: **audio-video-and-camera**
* GitHub Login: @drewbatgit
* Microsoft Alias: **drewbat**

**Comment by drewbatgit** [comment]
Hello and thanks for your feedback. There are two separate issues here. One is the sample code in the **Create or edit a SoftwareBitmap programmatically** section of the article. This section only creates the software bitmap and doesn't display it. I just tested the code in an empty project, using the code from the **Use SoftwareBitmap with a XAML Image control** section to display the image. The code worked as expected and displayed the image. Can you share the code that doesn't show anything?

The second issue is that I don't believe SoftwareBitmap and the Image control are designed to support full-frame, real-time animations. I have labeled this as a XAML issue so that the XAML team can look at your scenario and suggest the correct way to implement this.

**Comment by Gavin-Williams** [comment]
Ok, so this probably belongs on a forum, as it's obviously a usage issue (at least the rendering part). I can now see the rendered bitmap using this code but it's not updating. So does the source have to be set after any rendering? Because in other styles, the source need only be set once and then invalidated each frame.

Also I'm getting this after resizing the window (even when there is no resize/render collision, see below)...
System.UnauthorizedAccessException: 'Access is denied. 
Bitmap exclusive lock taken'

I'll attach what I've got. The first project demonstrates what I'm after using a different technique. The second project uses the SoftwareBitmap approach. Note that I'm also having issues with coordinating state for when the window is resized which is an asynchronous event. And although when I read through my code, it should restrict the renderer to doing one thing at a time - rendering or resizing - in action, it doesn't do that at all, and I get rendering/resizing collisions. There is something about asynchronous code that I just can't comprehend or technically deal with.

**Comment by Gavin-Williams** [comment]
[SoftwareRenderers.zip](https://github.com/MicrosoftDocs/windows-uwp/files/3051237/SoftwareRenderers.zip)

**Comment by Gavin-Williams** [comment]
I'm going to close this. I have an alternate solution which is sufficient for my needs. I was looking for something faster, but the presentation / copy to front buffer code is actually quite fast (<1ms) and it's the byte[] rendering code that is costly. Anyway I think I can get the code to work. I'll repost if I have a more specific question. Thanks.
