### ISSUE TITLE
Custom audio doesn't work in Toast Notification for Desktop Application

### ISSUE THREAD

**Issue by sergey-koryshev** [MicrosoftDocs/windows-uwp#1593]
Hi,

I use custom audio in `Toast Notification` in `Desktop Application`. But I found some problems with play this audio. I have two versions of Windows:

- 1607
- 1809

In version `1607` custom audio plays perfectly. But in version `1809` custom audio file doesn't play, there is just standard sound instead my audio.

I added audio by follow code:

```csharp
Audio = new ToastAudio()
{
    Src = new Uri("file:///...")
}
```

Am I missing something? Could someone please help me with the issue?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cfdc821a-c9bb-b8fb-3819-8d99c6ee7b03
* Version Independent ID: c32c183c-8a50-1444-fb68-c0b46d6805f2
* Content: [Custom audio on toasts - Windows UWP applications](https://docs.microsoft.com/en-us/windows/uwp/design/shell/tiles-and-notifications/custom-audio-on-toasts)
* Content Source: [windows-apps-src/design/shell/tiles-and-notifications/custom-audio-on-toasts.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/design/shell/tiles-and-notifications/custom-audio-on-toasts.md)
* Product: **uwp**
* Technology: **design**
* GitHub Login: @mijacobs
* Microsoft Alias: **mijacobs**

**Comment by andrewleader** [comment]
Thanks for reporting this! Looking into the issue with the dev team.

**Comment by andrewleader** [comment]
@Ace-Lightning your app is a classic Win32 app, correct? It is NOT using the Desktop Bridge?

**Comment by sergey-koryshev** [comment]
@andrewleader, yes, it’s classic .NET application, not Desktop Bridge

**Comment by andrewleader** [comment]
Thanks @Ace-Lightning. I've confirmed with the dev team that this is a known issue. We don't have any current plans to address it, as the fix is relatively big compared to the number of people who have asked for this functionality.

If you use the Desktop Bridge to package your application, you'll be able to use resources via the `ms-appx:///` file path and audio will work! Otherwise, if Desktop Bridge isn't an option for you, we'll continue to evaluate feedback around this area and see what happens! Thanks!

Andrew

**Comment by sergey-koryshev** [comment]
I'm not familiar with Desktop Bridge. I will investigate this way. 
But I look forward the issue will be handled for Win32 applications near future.

Thanks for looking at it!
