### ISSUE TITLE
Filter limitations

### ISSUE THREAD

**Issue by brianreinhold** [MicrosoftDocs/windows-uwp#1594]
There is nothing that I can find in the API documentation or in the more general description that states what the filter limits are. I tried filtering received advertisements by UUID. I could only add one UUID. If I added a second, nothing passed through. I am not sure if that is a bug in my implementation (don't link so) but an undocumented behavior of the filter.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: efe3c92a-ec28-648e-44b4-10ce62d6c107
* Version Independent ID: eac958bb-b09d-a0db-b08b-50c844269184
* Content: [Bluetooth Advertisements - Windows UWP applications](https://docs.microsoft.com/en-us/windows/uwp/devices-sensors/ble-beacon#feedback)
* Content Source: [windows-apps-src/devices-sensors/ble-beacon.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/devices-sensors/ble-beacon.md)
* Product: **uwp**
* Technology: **peripherals-sensors-and-power**
* GitHub Login: @eliotcowley
* Microsoft Alias: **elcowle**

**Comment by Karl-Bridge-Microsoft** [comment]
Thanks for taking the time to let us know about this issue and we sincerely apologize for the delayed response. 

Per the section at https://docs.microsoft.com/en-us/windows/uwp/devices-sensors/ble-beacon#watching-for-a-specific-advertisement-pattern, the filter demonstrated is  using an https://docs.microsoft.com/en-us/uwp/api/windows.devices.bluetooth.advertisement.bluetoothleadvertisement.manufacturerdata list. So it appears that more than one filter can be applied.

As this page has been updated since you reported the issue, the issue appears to be covered, and the sheer volume of of feedback in this repo requires us to prioritize new issues, we're closing this one due to age and lack of activity.

If you think the issue still exists and should be addressed, please open a new issue with any details/suggestions you think might be helpful.

**Comment by brianreinhold** [comment]
I have not made any more activity because I had so many difficulties with things not working our company gave up.
