### ISSUE TITLE
event_source.Event({ get_strong(), &EventRecipient::OnEvent }); not sufficiently documented

### ISSUE THREAD

**Issue by brianreinhold** [MicrosoftDocs/windows-uwp#1620]
When I do event_source.Event({ get_strong(), &EventRecipient::OnEvent }); the compiler gives me an error saying that 'get_strong()' is undefined. However, if I do
event_source.Event({ this, &EventRecipient::OnEvent });
there is no problem.
So something is missing in the documentation explaining what else I must tell the compiler so it understands 'get_strong()' and 'get_weak()'.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5c3f98fd-a779-924f-02d1-18762114a7af
* Version Independent ID: 34cec207-abe4-0ee0-72f4-1f9b8e6cae91
* Content: [Weak references in C++/WinRT - Windows UWP applications](https://docs.microsoft.com/en-us/windows/uwp/cpp-and-winrt-apis/weak-references#safely-accessing-the-this-pointer-with-an-event-handling-delegate)
* Content Source: [windows-apps-src/cpp-and-winrt-apis/weak-references.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/cpp-and-winrt-apis/weak-references.md)
* Product: **uwp**
* Technology: **platform**
* GitHub Login: @stevewhims
* Microsoft Alias: **stwhi**

**Comment by stevewhims** [comment]
Hi, @brianreinhold, see the following paragraph from the topic: "Because a C++/WinRT object directly or indirectly derives from the winrt::implements template, the C++/WinRT object can call its implements.get_strong protected member function to retrieve a strong reference to its `this` pointer. Calling get_strong increments your reference count, and keeps your implicit `this` pointer valid." So, you can call get_strong from within a member function of any runtime class implemented with C++/WinRT (that is, a class that inherits from winrt::implements). You can find more info about winrt::implements here: https://docs.microsoft.com/windows/uwp/cpp-and-winrt-apis/author-apis.

You can create a new Blank App (C++/WinRT) and add this to MainPage's constructor. Because MainPage derives from winrt::implements, the protected member function get_strong is present and can be called. It won't be present on classes that don't derive from winrt::implements.

```cppwinrt
        MainPage()
        {
            InitializeComponent();
            myButton().Click({ get_strong(), &MainPage::ClickHandler });
        }
```

~Steve

**Comment by brianreinhold** [comment]
Hi, @stevewhims In my actual use case I am looking at bluetooth low energy APIs. I am trying to solve the problem of 
`bluetoothLEDevice = co_await BluetoothLEDevice::FromBluetoothAddressAsync(eventArgs.BluetoothAddress(), BluetoothAddressType::Random);`

this method is always returning NULL when I use the BluetoothLEAdvertisementWatcher class. Though I get advertisements and my callback gets signaled, the above method always returns NULL. So it is really a stab of desperation as I don't know what else to do. But if this class does not derive from winrt::implements, then this stab of desperation cannot be attempted.

**Comment by stevewhims** [comment]
Note that get_strong() is a technique for preventing an event sink (meaning an object that handles an event, such as a Page) from being released before an event source (the object raising the event, such as a Button) attempts to notify the event sink of an event. Of course, in the case of Page/Button, because the Page contains the Button as a member, the Page naturally outlives the Button. So get_strong() is not necessary in that particular case. But it is necessary in other cases. The developer will know when such a case is in effect, and will then use get_strong(). If get_strong() is not used when it needs to be used, then the result will very likely be a crash or an exception. In your case, that doesn't seem to be happening.

If you feel that the content here is incorrect/insufficient with respect to how to program with strong and weak references with C++/WinRT, then this is the right place to describe that problem. If you feel that the BluetoothLE content (for example, the APIs you're calling) is incorrect/insufficient, then those API topics are the right place to leave that feedback. For other issues, the [Windows developer feedback site](https://wpdev.uservoice.com) is the right place to file a product bug. For issues, or suspected product bugs, there's [Microsoft Support](https://support.microsoft.com/contactus).

But at the moment, regrettably I'm not seeing anything that I can add to this particular topic to be of assistance.

~Steve

**Comment by brianreinhold** [comment]
I did not think that 'get_strong() would solve the problem but it was just a desperate attempt given I exhausted all other possibilities. What I didn't understand was why VS said it couldn't identify the method. The documentation did not help me solve that issue. From what I read I would have expected it to work _anyplace I could register for an event_. There was nothing in the documentation or examples that indicated that get_strong() or its related partner could only be used in special conditions. At least that should be present in the docs so that when VS gives me the error, it is not a total surprise.

**Comment by stevewhims** [comment]
Thanks, @brianreinhold. You're right, and I've just published an update to the topic in line with your feedback.

The detail about **get_strong** being a member of **winrt::implements** was emphasized only in the first section that deals with it (the section about coroutines). The detail wasn't emphasized in the second section (about delegates). So anyone skipping to that section could easily miss the detail. I've re-worked the content, and made sure the condition is clear in both sections. I'll go ahead and close this issue now.

Thanks for your feedback! :)
~Steve
