### ISSUE TITLE
Which previous code snippet?

### ISSUE THREAD

**Issue by BMarques** [MicrosoftDocs/windows-uwp#1635]
On this page it says: "Create a type that implements IFrameworkViewSource, as we did in the previous code snippet." Although I know how to create such a type, what "previous code snippet" are you talking about? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0edfec45-0605-31d8-c505-ba7d401b5551
* Version Independent ID: 9bdf5122-9e31-946b-a172-8c9da5987fa3
* Content: [The app object and DirectX - Windows UWP applications](https://docs.microsoft.com/en-us/windows/uwp/gaming/about-the-uwp-user-interface-and-directx#feedback)
* Content Source: [windows-apps-src/gaming/about-the-uwp-user-interface-and-directx.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/gaming/about-the-uwp-user-interface-and-directx.md)
* Product: **uwp**
* Technology: **games**
* GitHub Login: @eliotcowley
* Microsoft Alias: **elcowle**

**Comment by stevewhims** [comment]
Hi, @BMarques. I'm really sorry for the long delay in responding, and thanks for filing this issue.

You're right, there is no previous snippet. I've fixed this issue by adding a link to a code example that does show how to implemement **IFrameworkViewSource** (in C++/WinRT, since that's the language projection that we recommend).

Thanks again!
-Steve
