### ISSUE TITLE
Back-Translation "ms-設定:" → "ms-settings:"

### ISSUE THREAD

**Issue by hyoshioka0128** [MicrosoftDocs/windows-uwp#1639]
https://docs.microsoft.com/ja-jp/windows/uwp/launch-resume/launch-settings-app

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 987ec16c-9456-93a4-177a-dbd563be7eb7
* Version Independent ID: f41f0344-f7f6-f092-a6bf-fc4184a9b460
* Content: [Windows 設定アプリの起動 - Windows UWP applications](https://docs.microsoft.com/ja-jp/windows/uwp/launch-resume/launch-settings-app)
* Content Source: [windows-apps-src/launch-resume/launch-settings-app.md](https://github.com/MicrosoftDocs/windows-uwp-pr.ja-jp/blob/live-sxs/windows-apps-src/launch-resume/launch-settings-app.md)
* Product: **uwp**
* Technology: **processes-and-threading**
* GitHub Login: @knicholasa
* Microsoft Alias: **nichola**

**Comment by CeciAc** [comment]
Issue moved to [MicrosoftDocs/windows-uwp.ja-jp #8](https://github.com/MicrosoftDocs/windows-uwp.ja-jp/issues/8) via [**ZenHub**](https://www.zenhub.com/)

**Comment by CeciAc** [comment]
Hello, @hyoshioka0128 

Your feedback is much appreciated.
Since your comments are specific to the localization of the documentation, we have moved this issue to the corresponding localization repository and we will close this one.

Please review the status of this issue here https://github.com/MicrosoftDocs/windows-uwp.ja-jp/issues/8

Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
#please-close

**Comment by CeciAc** [comment]
@knicholasa This issue is already resolved in the MicrosoftDocs/windows-uwp.ja-jp#8

#please-close

**Comment by knicholasa** [comment]
Got it, thanks.
