### ISSUE TITLE
Back-Translation "Ms-チュートリアル-します。" → "ms-walk-to:"

### ISSUE THREAD

**Issue by hyoshioka0128** [MicrosoftDocs/windows-uwp#1640]
https://docs.microsoft.com/ja-jp/windows/uwp/launch-resume/launch-maps-app

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 4baead54-3332-c579-f135-6464cc228be4
* Version Independent ID: fcf9e8a0-f10e-2fdd-a24b-212d3fc935b9
* Content: [Windows マップ アプリの起動 - Windows UWP applications](https://docs.microsoft.com/ja-jp/windows/uwp/launch-resume/launch-maps-app)
* Content Source: [windows-apps-src/launch-resume/launch-maps-app.md](https://github.com/MicrosoftDocs/windows-uwp-pr.ja-jp/blob/live-sxs/windows-apps-src/launch-resume/launch-maps-app.md)
* Product: **uwp**
* Technology: **processes-and-threading**
* GitHub Login: @knicholasa
* Microsoft Alias: **nichola**

**Comment by CeciAc** [comment]
Hello, @hyoshioka0128
Your feedback is much appreciated.
Since your comments are specific to the localization of the documentation, we have moved this issue to the corresponding localization repository and we will close this one. 

Please review the status of this issue here https://github.com/MicrosoftDocs/windows-uwp.ja-jp/issues/9

Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
#please-close

**Comment by CeciAc** [comment]
@knicholasa This issue is already resolved in the https://github.com/MicrosoftDocs/windows-uwp.ja-jp/issues/9

#please-close

**Comment by knicholasa** [comment]
Got it, thanks.
