### ISSUE TITLE
[LOC] Showing "**ms 設定。" (extra asterisks appears)

### ISSUE THREAD

**Issue by hyoshioka0128** [MicrosoftDocs/windows-uwp#1643]
https://docs.microsoft.com/ja-jp/windows/uwp/launch-resume/launch-maps-app

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 4baead54-3332-c579-f135-6464cc228be4
* Version Independent ID: fcf9e8a0-f10e-2fdd-a24b-212d3fc935b9
* Content: [Windows マップ アプリの起動 - Windows UWP applications](https://docs.microsoft.com/ja-jp/windows/uwp/launch-resume/launch-maps-app)
* Content Source: [windows-apps-src/launch-resume/launch-maps-app.md](https://github.com/MicrosoftDocs/windows-uwp-pr.ja-jp/blob/live-sxs/windows-apps-src/launch-resume/launch-maps-app.md)
* Product: **uwp**
* Technology: **processes-and-threading**
* GitHub Login: @knicholasa
* Microsoft Alias: **nichola**

**Comment by CeciAc** [comment]
Hello, @hyoshioka0128 
 
We truly appreciate your comment and we strive to improve your experience in docs.microsoft.com. However, we need more information in order to be able to address your feedback. Can you please provide more detailed information and clarify your comment?

**I cannot repro this issue, ` **ms 設定。` cannot be found anywhere in the document, please, clarify.**
 
Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hello, @hyoshioka0128
 
We are following up on our previous comment. We need more information in order to be able to address your feedback. Can you please provide more detailed information and clarify your comment?
 
Kind regards,
Microsoft DOCS International Team

**Comment by hyoshioka0128** [comment]
Hello, @CeciAc (I'm poor English.)
"** ms 設定" was lost because it was updated.
![launch-maps-app_j](https://user-images.githubusercontent.com/40815708/60711387-cce05f00-9f4f-11e9-8a19-85558d98637c.png)

As you will PR later, please close it.

**Comment by CeciAc** [comment]
Hello, @hyoshioka0128 

Your feedback is much appreciated. We are glad to see that your experience with our documentation meets your expectations.
We encourage you to provide your valuable feedback so that we can continue improve your experience.

Kind regards,
Microsoft DOCS International Team

#please-close
