### ISSUE TITLE
[LOC] Back-Translation "ms 写真:" → "ms-photos:"

### ISSUE THREAD

**Issue by hyoshioka0128** [MicrosoftDocs/windows-uwp#1648]
https://docs.microsoft.com/ja-jp/windows/uwp/launch-resume/launch-default-app

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: ae2608d3-38b8-2404-d138-1ba17772e72c
* Version Independent ID: 535d38b3-3174-fc77-ec58-7b5732ba803c
* Content: [URI に応じた既定のアプリの起動 - Windows UWP applications](https://docs.microsoft.com/ja-jp/windows/uwp/launch-resume/launch-default-app)
* Content Source: [windows-apps-src/launch-resume/launch-default-app.md](https://github.com/MicrosoftDocs/windows-uwp-pr.ja-jp/blob/live-sxs/windows-apps-src/launch-resume/launch-default-app.md)
* Product: **uwp**
* Technology: **processes-and-threading**
* GitHub Login: @knicholasa
* Microsoft Alias: **nichola**

**Comment by CeciAc** [comment]
Hello, @hyoshioka0128

Your contribution is much appreciated. Our team reviewed your feedback and it appears that this issue has been already logged.
Please review issue #https://github.com/MicrosoftDocs/windows-uwp.ja-jp/issues/12 
For this reason we are closing this issue since it is duplicated.

Kind regards,
Microsoft DOCS International Team
#please-close
