### ISSUE TITLE
[LOC] Back-Translation "ms ユーザー:	" → "ms-people:"

### ISSUE THREAD

**Issue by hyoshioka0128** [MicrosoftDocs/windows-uwp#1650]
https://docs.microsoft.com/ja-jp/windows/uwp/launch-resume/launch-people-apps

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: a1d62e94-aa32-467f-fa2d-14e630543e1f
* Version Independent ID: 2ab8ae17-c66e-3bd8-2a28-a8804a06a66a
* Content: [People アプリの起動 - Windows UWP applications](https://docs.microsoft.com/ja-jp/windows/uwp/launch-resume/launch-people-apps)
* Content Source: [windows-apps-src/launch-resume/launch-people-apps.md](https://github.com/MicrosoftDocs/windows-uwp-pr.ja-jp/blob/live-sxs/windows-apps-src/launch-resume/launch-people-apps.md)
* Product: **uwp**
* Technology: **processes-and-threading**
* GitHub Login: @knicholasa
* Microsoft Alias: **nichola**

**Comment by CeciAc** [comment]
Hello, @hyoshioka0128

Your contribution is much appreciated. Our team reviewed your feedback and it appears that this issue has been already logged.
Please review issue https://github.com/MicrosoftDocs/windows-uwp.ja-jp/issues/13
For this reason we are closing this issue since it is duplicated.

Kind regards,
Microsoft DOCS International Team
#please-close
