### ISSUE TITLE
Back-Translation "ソース" → "source"

### ISSUE THREAD

**Issue by hyoshioka0128** [MicrosoftDocs/windows-uwp#1653]
https://docs.microsoft.com/ja-jp/windows/uwp/launch-resume/launch-screen-snipping

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: f601b985-8203-1b9e-3592-d6f8db289f97
* Version Independent ID: 93ea1d13-1d5a-d471-d7cb-bc54d5580a26
* Content: [画面切り取りの起動 - Windows UWP applications](https://docs.microsoft.com/ja-jp/windows/uwp/launch-resume/launch-screen-snipping)
* Content Source: [windows-apps-src/launch-resume/launch-screen-snipping.md](https://github.com/MicrosoftDocs/windows-uwp-pr.ja-jp/blob/live-sxs/windows-apps-src/launch-resume/launch-screen-snipping.md)
* Product: **uwp**
* Technology: **processes-and-threading**
* GitHub Login: @knicholasa
* Microsoft Alias: **nichola**

**Comment by CeciAc** [comment]
Issue moved to [MicrosoftDocs/windows-uwp.ja-jp #15](https://github.com/MicrosoftDocs/windows-uwp.ja-jp/issues/15) via [**ZenHub**](https://www.zenhub.com/)

**Comment by CeciAc** [comment]
Hello, @hyoshioka0128
 
Your feedback is much appreciated.
Since your comments are specific to the localization of the documentation, we have moved this issue to the corresponding localization repository and we will close this one.

Please review the status of this issue here https://github.com/MicrosoftDocs/windows-uwp.ja-jp/issues/15

Kind regards,
Microsoft DOCS International Team
#please-close
