### ISSUE TITLE
Add equivalent VB.NET examples

### ISSUE THREAD

**Issue by stevennyman** [MicrosoftDocs/windows-uwp#1660]
It would be helpful if VB.NET examples were added to this page as the Bluetooth docs are a little confusing and some people are more familiar with VB.NET than C#. Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6c57c086-3015-37b6-5318-b90a8e1fc0ba
* Version Independent ID: 94556012-dcdd-1dde-c8e5-147e1d05d5c0
* Content: [Bluetooth GATT Client - Windows UWP applications](https://docs.microsoft.com/en-us/windows/uwp/devices-sensors/gatt-client#feedback)
* Content Source: [windows-apps-src/devices-sensors/gatt-client.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/devices-sensors/gatt-client.md)
* Product: **uwp**
* Technology: **peripherals-sensors-and-power**
* GitHub Login: @eliotcowley
* Microsoft Alias: **elcowle**

**Comment by Karl-Bridge-Microsoft** [comment]
Thanks for taking the time to let us know about this issue and we sincerely apologize for the delayed response. 

As providing vb snippets on every page that has a c# snippet would be quite time consuming we recommend using an online converter in most cases. Due to the sheer volume of of feedback in this repo requires us to prioritize new issues, we're closing this one due to age and lack of activity.

If you think the issue still exists and should be addressed, please open a new issue with any details/suggestions you think might be helpful.
