### ISSUE TITLE
ms-settings:apps-volume URI deprecated in 1809

### ISSUE THREAD

**Issue by Barton-Systems** [MicrosoftDocs/windows-uwp#1682]
it seems that the ms-settings:apps-volume URI is deprecated in 1809.
can you document accordingly or is there any plan to re-introduce?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 987ec16c-9456-93a4-177a-dbd563be7eb7
* Version Independent ID: f41f0344-f7f6-f092-a6bf-fc4184a9b460
* Content: [Launch the Windows Settings app - Windows UWP applications](https://docs.microsoft.com/en-us/windows/uwp/launch-resume/launch-settings-app)
* Content Source: [windows-apps-src/launch-resume/launch-settings-app.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/launch-resume/launch-settings-app.md)
* Product: **uwp**
* Technology: **processes-and-threading**
* GitHub Login: @knicholasa
* Microsoft Alias: **nichola**

**Comment by knicholasa** [comment]
Thanks for leaving your feedback. I contacted the team to see if the docs need to be updated. I believe that this URI works in 1903 but not 1809, and if I can confirm that with the team I'll add it to the doc. 

Feedback here is meant for documentation updates rather than technical support, so here are some other resources you might find useful. For community assistance with development questions I recommend that you ask on our [forums](https://social.msdn.microsoft.com/Forums/newthread?category=windowsapps&forum=wpdevelop&prof=required) or [StackOverflow](https://stackoverflow.com/questions). Otherwise, please see [the developer support page](https://developer.microsoft.com/windows/support) for other support options.

**Comment by knicholasa** [comment]
I have confirmed that 1903 is required and will be updating the docs to say so.
