### ISSUE TITLE
Preview Screen Capture in real time.

### ISSUE THREAD

**Issue by meteorsnows** [MicrosoftDocs/windows-uwp#1689]
Hi, which video/graphic packages can i using to preview the screen capture in XAML in real time, such as in Process Frame but clearly we should do manually instead of FrameArrived right?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9b8d11e4-f9c6-383a-38d4-6cf7633edb7c
* Version Independent ID: 7015ed77-ae66-cc97-301c-b0c6ebfb2bd3
* Content: [Screen capture - Windows UWP applications](https://docs.microsoft.com/en-us/windows/uwp/audio-video-camera/screen-capture)
* Content Source: [windows-apps-src/audio-video-camera/screen-capture.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/audio-video-camera/screen-capture.md)
* Product: **uwp**
* Technology: **audio-video-and-camera**
* GitHub Login: @drewbatgit
* Microsoft Alias: **drewbat**

**Comment by drewbatgit** [comment]
Thanks for reaching out with your feedback. Issues opened on the docs GitHub are meant for documentation feedback, and unfortunately we cannot provide technical support. For community assistance with development questions I recommend that you ask on our [forums](https://social.msdn.microsoft.com/Forums/newthread?category=windowsapps&forum=wpdevelop&prof=required) or [StackOverflow](https://stackoverflow.com/questions). Otherwise, please see the [developer support page](https://developer.microsoft.com/windows/support) for your support options.
