### ISSUE TITLE
Graphics essue

### ISSUE THREAD

**Issue by vaibhav242990** [MicrosoftDocs/windows-uwp#1702]
I did't find any start or stop recording button. if i add button and start recording it stuck in StartCaptureInternal  loop. I am new in uwp please help.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9b8d11e4-f9c6-383a-38d4-6cf7633edb7c
* Version Independent ID: 7015ed77-ae66-cc97-301c-b0c6ebfb2bd3
* Content: [Screen capture - Windows UWP applications](https://docs.microsoft.com/en-us/windows/uwp/audio-video-camera/screen-capture#feedback)
* Content Source: [windows-apps-src/audio-video-camera/screen-capture.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/audio-video-camera/screen-capture.md)
* Product: **uwp**
* Technology: **audio-video-and-camera**
* GitHub Login: @drewbatgit
* Microsoft Alias: **drewbat**

**Comment by hkhmsft** [comment]
This feels not so much like feedback specifically about the documentation, but rather like a support request. Here are all of the developer support resources, for completeness.

 - The [Feedback Hub app](https://support.microsoft.com/help/4021566/windows-10-send-feedback-to-microsoft-with-feedback-hub-app) is the right place to lobby for a change, a feature, or to make a suggestion.
 - For community assistance with development questions, there are our [forums](https://social.msdn.microsoft.com/Forums/newthread?category=windowsapps&forum=wpdevelop&prof=required), and [StackOverflow](https://stackoverflow.com/questions).
 - The [Windows developer support](https://developer.microsoft.com/windows/support) site explains other support options.
 - The [Visual Studio developer community](https://developercommunity.visualstudio.com) is available, and responsive. The former User Voice feature is now there on the **Suggest a feature** tab, if you want to lobby for a change, a feature, or to make a suggestion.
 - For developer issues, or suspected product bugs, there's [Microsoft Support](https://support.microsoft.com/contactus); a support engineer will look at the repro and see whether the issue is a Microsoft product bug, or something else. If it's a bug with a Microsoft product then the ticket will be free of charge.
 
 If you receive assistance via any support resource, and you believe that information would help us improve the docs, then please come back and let us know.
