### ISSUE TITLE
crashing with out having the Filters add

### ISSUE THREAD

**Issue by MaxwellCurtis** [MicrosoftDocs/windows-uwp#1713]
The Picking will Crash the App if there are no filters added to it and the error message that is displayed sucks "Unspecified" Please add a section to this page stating that you must have the filters to have this work properly 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f98368cc-a7d2-6770-7c8f-3cb2f500676f
* Version Independent ID: 88e3393d-38a9-5737-89e2-85543d52dbfa
* Content: [Open files and folders with a picker - Windows UWP applications](https://docs.microsoft.com/en-us/windows/uwp/files/quickstart-using-file-and-folder-pickers#feedback)
* Content Source: [windows-apps-src/files/quickstart-using-file-and-folder-pickers.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/files/quickstart-using-file-and-folder-pickers.md)
* Product: **uwp**
* Technology: **data-and-files**
* GitHub Login: @knicholasa
* Microsoft Alias: **nichola**

**Comment by knicholasa** [comment]
Thanks for the feedback. I'll reach out to the team that owns the technology about adding that note to the page. In the mean time if you need technical support feel free to reach out on our support [forums](https://social.msdn.microsoft.com/Forums/newthread?category=windowsapps&forum=wpdevelop&prof=required) or [StackOverflow](https://stackoverflow.com/questions). Or see [the developer support page](https://developer.microsoft.com/windows/support) for more options.

**Comment by Canvee** [comment]
It's January 2020 and I have still the issue and I quite don't understand why should I specify a FileTypeFilter to pick a folder.

**Comment by GrantMeStrength** [comment]
AI generated answer:

In UWP (Universal Windows Platform) applications, when using a file picker to allow a user to select a folder, specifying a filter might seem unnecessary at first, especially since folders themselves do not have a "file type" in the same way files do. However, the requirement for specifying a filter, even when you're primarily interested in folder selection, stems from the architecture and design of the file and folder picker APIs in UWP.

The primary role of filters in file pickers is to limit the files that appear in the picker to those that match the specified file types, ensuring users can only select files that the application can handle. This improves user experience by preventing users from selecting incompatible files, leading to errors or unexpected behavior in the app.

When it comes to folder pickers, the concept of a "file type filter" might not directly apply because you're selecting folders, not files. However, the underlying reason for requiring at least one file type filter in the file picker (which can also be used to select folders in some contexts) is about API consistency and ensuring a baseline functionality that aligns with the security and design principles of UWP apps.

Specifying a filter, even a broad one, serves a few purposes:

Security and Privacy: UWP apps operate in a sandboxed environment, with strict permissions to ensure user data's security and privacy. Requiring a filter implicitly reinforces the idea that the app should only access files and directories relevant to its function.
Performance: By limiting the scope of accessible files, even indirectly when selecting folders, the application can perform more efficiently, avoiding unnecessary processing of irrelevant data.
User Experience: While this applies more to file selection, ensuring that only relevant file types are shown to the user streamlines the selection process, making the application easier and more intuitive to use.
In cases where an application uses a file picker for folder selection, the requirement to specify a filter might be a byproduct of these overarching principles rather than a direct necessity for the folder selection process itself. It's a part of ensuring that all apps adhere to the platform's design guidelines, which prioritize security, performance, and a consistent user experience.
