### ISSUE TITLE
Add Extended Splash to Windows Template Studio

### ISSUE THREAD

**Issue by hupo376787** [MicrosoftDocs/windows-uwp#1714]
How to add this extended splash to current windows template studio?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1a0fe87b-78e1-64a6-a7ed-51d8a6373a5d
* Version Independent ID: 71898667-5572-11bb-f53c-0d1ebc77511d
* Content: [Display a splash screen for more time - Windows UWP applications](https://docs.microsoft.com/en-us/windows/uwp/launch-resume/create-a-customized-splash-screen#feedback)
* Content Source: [windows-apps-src/launch-resume/create-a-customized-splash-screen.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/launch-resume/create-a-customized-splash-screen.md)
* Product: **uwp**
* Technology: **processes-and-threading**
* GitHub Login: @knicholasa
* Microsoft Alias: **nichola**

**Comment by knicholasa** [comment]
Thanks for reaching out with your feedback. This looks like a technical support question to me, and unfortunately we cannot provide that level of support through GitHub issues. For community assistance with development questions I recommend that you ask on our [forums](https://social.msdn.microsoft.com/Forums/newthread?category=windowsapps&forum=wpdevelop&prof=required) or [StackOverflow](https://stackoverflow.com/questions). Otherwise, please see [the developer support page](https://developer.microsoft.com/windows/support) for your support options. If you get assistance through these other resources and believe a documentation change is required, please come back and let us know.
