### ISSUE TITLE
Splash screen is not mandatory anymore

### ISSUE THREAD

**Issue by ArchieCoder** [MicrosoftDocs/windows-uwp#1721]
The first sentence is inaccurate now. The splashscreen can be optional https://docs.microsoft.com/en-us/uwp/schemas/appxpackage/uapmanifestschema/element-uap-splashscreen

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: eb89dff7-85b7-9ce7-cae4-d5190d94c5ea
* Version Independent ID: b3401dec-88cb-b7b4-1313-10dc1b30301d
* Content: [Splash screens - Windows UWP applications](https://docs.microsoft.com/en-us/windows/uwp/launch-resume/splash-screens)
* Content Source: [windows-apps-src/launch-resume/splash-screens.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/launch-resume/splash-screens.md)
* Product: **uwp**
* Technology: **processes-and-threading**
* GitHub Login: @knicholasa
* Microsoft Alias: **nichola**

**Comment by knicholasa** [comment]
Thanks for providing this feedback! I'm wondering, are you basing this feedback on the article you linked, where it says you can specify that the splash screen is optional? In the section on setting the "optional" parameter to be true, it says:
> If there is a delay in the app launch time, the splash screen will be shown. 

So I believe the splash screen is still required, it just might not be shown, and so the 
> All UWP apps must have a splash screen

language is still accurate. 

If you have reason to believe otherwise I can follow up with the team.

**Comment by ArchieCoder** [comment]
After testing the feature myself, the doc is right. I will close the issue. Thanks.
