### ISSUE TITLE
Update instructions

### ISSUE THREAD

**Issue by mdmozibur** [MicrosoftDocs/windows-uwp#1736]
It's been a long since this page was last updated, instructions given aren't appropriate anymore.
Most of us use visual studio 2019 or 2017, net standard 2.2 and many more update.  Please validate the instructions .

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6c591596-d202-244c-6fbf-31c288fe9b57
* Version Independent ID: 1473907c-0cba-8917-2fd8-d3ca1fb73cae
* Content: [Use a SQLite database in a UWP app - Windows UWP applications](https://docs.microsoft.com/en-us/windows/uwp/data-access/sqlite-databases#feedback)
* Content Source: [windows-apps-src/data-access/sqlite-databases.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/data-access/sqlite-databases.md)
* Product: **uwp**
* Technology: **data-and-files**
* GitHub Login: @knicholasa
* Microsoft Alias: **nichola**

**Comment by hkhmsft** [comment]
Thanks for submitting your feedback and I apologize for the delayed response. I see that updates have not been made since the creation of this Issue so I went ahead and created an internal work item for new content. The timeline for this may vary, so I will go ahead and close this and circle back when the remark or the code snippet has been added. 

Though the Issue will be marked as Closed, I will monitor any replies that come afterwards so treat this like an open Issue. Many thanks!
