### ISSUE TITLE
Getting error on DNS connection

### ISSUE THREAD

**Issue by moe-lok** [MicrosoftDocs/windows-uwp#1741]
UWP applications restrict network access by default. In order to connect to the database successfully, you will need to add Internet (Client & Server), Internet (Client) and Private Networks (Client & Server) capabilities in "Package.appxmanifest".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6415499a-b936-1e81-99ee-ad570820ebb2
* Version Independent ID: a33a461a-0aaf-ad99-f2d1-ddc338cd7428
* Content: [Use a MongoDB database in a UWP app - Windows UWP applications](https://docs.microsoft.com/en-us/windows/uwp/data-access/mongo-db-databases#feedback)
* Content Source: [windows-apps-src/data-access/mongo-db-databases.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/data-access/mongo-db-databases.md)
* Product: **uwp**
* Technology: **data-and-files**
* GitHub Login: @knicholasa
* Microsoft Alias: **nichola**

**Comment by hkhmsft** [comment]
Thanks for submitting your feedback and I apologize for the delayed response. I see that updates have not been made since the creation of this Issue so I went ahead and created an internal work item for new content. The timeline for this may vary, so I will go ahead and close this and circle back when the remark or the code snippet has been added. 

Though the Issue will be marked as Closed, I will monitor any replies that come afterwards so treat this like an open Issue. Many thanks!
