### ISSUE TITLE
Query for Products. orderid not required? 

### ISSUE THREAD

**Issue by mjfusa** [MicrosoftDocs/windows-uwp#1745]
In the Query for products documentation, it states "order id" isn't required in response. Could you clarify in what cases it wouldn't be there? 

Reference: https://docs.microsoft.com/en-gb/windows/uwp/monetize/query-for-products

**Comment by hickeys** [comment]
This seems a little out of scope for modifying the doc itself, and I don't have an exhaustive list for you. I can give you an example though. A user may have access to a product because they work for a company that provides LOB software to all users. That particular user never ordered the software, and if that user ever leaves the company, they will lose access to the software.
