### ISSUE TITLE
broadFileSystemAccess on all devices?

### ISSUE THREAD

**Issue by touseefbsb** [MicrosoftDocs/windows-uwp#1762]
the docs page for restricted capibilities need to clarify can we use **broadFileSystemAccess** on all windows 10 device platforms like xbox, hololens etc? or is it just limited to Desktop ? Thanks

**Comment by ginami** [comment]
Hi @touseefbsb -- thanks for your feedback! Can you give me the URL for the restricted capabilities page, please? This will help me route your comment to the correct author. Thank you!

**Comment by touseefbsb** [comment]
here you go : https://docs.microsoft.com/en-us/windows/uwp/packaging/app-capability-declarations

**Comment by mcleanbyron** [comment]
Nick, this is a question about file system capabilities. Can you please take a look?

**Comment by knicholasa** [comment]
Hi @touseefbsb, thanks for leaving your feedback. I'll look into updating the documentation with this information. I would also encourage you to check out our developer support resources if you need timely assistance. For community assistance with development questions I recommend that you ask on our [forums](https://social.msdn.microsoft.com/Forums/newthread?category=windowsapps&forum=wpdevelop&prof=required) or [StackOverflow](https://stackoverflow.com/questions). Otherwise, please see [the developer support page](https://developer.microsoft.com/windows/support) for your support options.

**Comment by touseefbsb** [comment]
yes sure @knicholasa  actually I asked it here bcz I wanted to know answer about it myself but also wanted docs to be updated so that it can help everyone else as well. Thanks.

**Comment by knicholasa** [comment]
No problem! We just don't have the resources to respond quickly, so I wanted to make sure you're aware of where you can go to get help. If you get help on the support forums and think that that information could be used to update the docs, feel free to come back here and provide a link to the conversation.
