### ISSUE TITLE
Quick actions is missing

### ISSUE THREAD

**Issue by rml1997** [MicrosoftDocs/windows-uwp#1764]
I think I've removed quick actions from the dashboard, but there is no option to re-add it like the other tools. Is there a way to reset the dashboard or some other way to get quick actions back, as I'm currently unable to view the pin to deploy my app!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f2d22122-9c64-2d5a-fc6a-2655d7b67757
* Version Independent ID: 68ac6d45-9a72-8b24-9045-e5566d2de7fe
* Content: [Set up your UWP on Xbox development environment - Windows UWP applications](https://docs.microsoft.com/en-us/windows/uwp/xbox-apps/development-environment-setup#feedback)
* Content Source: [windows-apps-src/xbox-apps/development-environment-setup.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/xbox-apps/development-environment-setup.md)
* Product: **uwp**
* Technology: **games**
* GitHub Login: @M-Stahl
* Microsoft Alias: **kevinasg**

**Comment by mattwojo** [comment]
Thank you for taking the time to let us know about this issue. Apologies for the delayed response. Due to the volume of feedback in our content, we are currently prioritizing new issues. It also sounds like this issue may be better handled by https://support.xbox.com/. 

If you believe your feedback still requires an update to the documentation, please let us know either directly in this thread, by filing a new issue, or by filing a [Pull Request ](https://github.com/MicrosoftDocs/windows-uwp/pulls) with your recommended updates.

Though the Issue will be marked as closed, we will still receive replies and are able to reopen the issue if necessary. 

Thanks again for taking the time to contribute.
