### ISSUE TITLE
App installed on external disk

### ISSUE THREAD

**Issue by mastroalbert** [MicrosoftDocs/windows-uwp#1779]
When an app is installed on a non-system disk, files stored in the ApplicationData.LocalFolder are locked, preventing some manipulation of those files. Is there any documentation on this?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 340f7839-6454-f1b5-ced5-5000964efc2e
* Version Independent ID: f83df5c8-e149-df6e-243f-07311caab297
* Content: [Store and retrieve settings and other app data - Windows UWP applications](https://docs.microsoft.com/en-us/windows/uwp/design/app-settings/store-and-retrieve-app-data#related-articles)
* Content Source: [windows-apps-src/design/app-settings/store-and-retrieve-app-data.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/design/app-settings/store-and-retrieve-app-data.md)
* Product: **uwp**
* Technology: **design**
* GitHub Login: @mijacobs
* Microsoft Alias: **mijacobs**

**Comment by mijacobs** [comment]
Thanks for reaching out with your feedback. I'll work on updating the documentation with this info, but in the meantime you'll find quicker support by consulting our developer support resources. For community assistance with development questions I recommend that you ask on our [forums](https://social.msdn.microsoft.com/Forums/newthread?category=windowsapps&forum=wpdevelop&prof=required) or [StackOverflow](https://stackoverflow.com/questions). Otherwise, please see [the developer support page](https://developer.microsoft.com/windows/support) for your support options. If you get assistance through these other resources and believe that information would help us improve the docs, please come back and let us know.
