### ISSUE TITLE
Exception thrown, even the manifest is set correctly.

### ISSUE THREAD

**Issue by dongle-the-gadget** [MicrosoftDocs/windows-uwp#1794]
Even though I have setup the manifest correctly, the InitializeComponent() throws this exception:
TypeLoadException: Could not find Windows Runtime type 'Microsoft.Toolkit.Win32.UI.XamlHost.IXamlMetadataContainer'.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: badad06e-48a0-0a8d-e5e1-d0c8573dbc3e
* Version Independent ID: 313ee3ec-bcc2-cb3a-ac3f-5434f395ab6f
* Content: [Add a UWP InkCanvas control using XAML Islands - Windows apps](https://docs.microsoft.com/en-us/windows/apps/desktop/modernize/modernize-wpf-tutorial-2#feedback)
* Content Source: [hub/apps/desktop/modernize/modernize-wpf-tutorial-2.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/hub/apps/desktop/modernize/modernize-wpf-tutorial-2.md)
* Product: **windows**
* Technology: **desktop**
* GitHub Login: @mcleanbyron
* Microsoft Alias: **mcleans**

**Comment by mcleanbyron** [comment]
Thanks for reporting this issue. It turned out that there was a bug in the 6.0.0-preview6.3 release of the Microsoft.Toolkit.Wpf.UI.Controls NuGet package. The engineering team has fixed the bug and released an updated 6.0.0-preview6.4 version of the package. Please try these steps again with the latest package, and feel free to reopen this issue if you encounter further problems.
