### ISSUE TITLE
Following this advice creates two errors in Xamarin Forms UWP

### ISSUE THREAD

**Issue by BillyMartin1964** [MicrosoftDocs/windows-uwp#1796]
UWP will only install the language resources for the languages  that are already installed on the target device. I need to install all of the languages my app provides.

I added the two xml files to my UWP project in Xamarin Forms so that I could install all of my apps languages and provide a drop down to choose the language, but when I tried to debug, I received the following two errors:

1.  Error 0xdef00534 - Initializing Indexer	Yatzy.UWP	E:\Apps\YatzyNew\Yatzy\Yatzy.UWP\GENERATEPROJECTPRIFILE	
2. Error 0xdef00534 - Invalid configuration. Failed to parse the 'allowed' node.	Yatzy.UWP E:\Apps\YatzyNew\Yatzy\Yatzy.UWP\GENERATEPROJECTPRIFILE		

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 836865ec-ea89-1baf-141b-c415940b6e5c
* Version Independent ID: 6c610dcb-0f1c-c58e-b42c-4aa06687c9d6
* Content: [Build resources into your app package, instead of into a resource pack - Windows UWP applications](https://docs.microsoft.com/en-us/windows/uwp/app-resources/build-resources-into-app-package#feedback)
* Content Source: [windows-apps-src/app-resources/build-resources-into-app-package.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/app-resources/build-resources-into-app-package.md)
* Product: **uwp**
* Technology: **data-and-files**
* GitHub Login: @knicholasa
* Microsoft Alias: **nichola**

**Comment by knicholasa** [comment]
Thanks for your feedback. This looks like a support request so I recommend you reach out to our developer support resources. For community assistance with development questions I recommend that you ask on our [forums](https://social.msdn.microsoft.com/Forums/newthread?category=windowsapps&forum=wpdevelop&prof=required) or [StackOverflow](https://stackoverflow.com/questions). Otherwise, please see [the developer support page](https://developer.microsoft.com/windows/support) for your support options. If you get assistance through these other resources and believe that information would help us improve the docs, please come back and let us know.
