### ISSUE TITLE
There is an new option "Make Alias"

### ISSUE THREAD

**Issue by teamfreytag** [MicrosoftDocs/windows-uwp#1799]
There is an new option "Make Alias".  This documentation page should be updated to include "What is the purpose of the option" and "What it does".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9763974f-11a9-793a-3927-2c5038f1fe32
* Version Independent ID: f60c21e8-cec9-a1cc-b372-840a7fe540cc
* Content: [Manage app names - Windows UWP applications](https://docs.microsoft.com/en-us/windows/uwp/publish/manage-app-names#feedback)
* Content Source: [windows-apps-src/publish/manage-app-names.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/publish/manage-app-names.md)
* Product: **uwp**
* Technology: **publish**
* GitHub Login: @hickeys
* Microsoft Alias: **hickeys**

**Comment by GrantMeStrength** [comment]
We are changing the way we track issues filed from our documentation pages: please see this [blog post](https://techcommunity.microsoft.com/t5/microsoft-learn-blog/announcing-a-new-way-to-give-feedback-on-microsoft-learn/ba-p/4027635) for more details. The Microsoft Store documentation has been updated several times since your issue was reported, and there's a good chance your problem has been addressed. Right now, this issue is being closed but if you feel it is still valid and has not been addressed, please re-open it with any more available information. Please note that if you question is more general and not related to documentation, [Microsoft Q&A](https://learn.microsoft.com/en-us/answers/questions/) is a great way to get questions answered.
