### ISSUE TITLE
mixer/Beam Partner GenaroFPS: problema de configuração do Partner Center

### ISSUE THREAD

**Issue by genarooluucas** [MicrosoftDocs/windows-uwp#1801]
Olá Boa tarde,
Lucas Santos
(lucasrodriguessantos7@gmail.com) or (lucasrodriguessantos7@outlook.com)

Estou com problemas na inscrição no Partner Center recebi a seguinte mensagem de:
''Mixer Partnerships Onboarding Team <mixeroas@microsoft.com>

Hello GenaroFPS,

Partner Center has encountered an issue with the tax information you provided during setup. Please visit Partner Center using the links below and verify that everything was entered correctly. Thank you!

Best regards,''

No mesmo dia verifiquei os dados estão ok e responde o mesmo e-mail que recebi com as seguintes prints.

![image](https://user-images.githubusercontent.com/52979713/61331427-603f4d00-a7f8-11e9-87ad-f277e45fee90.png)

![image](https://user-images.githubusercontent.com/52979713/61331438-646b6a80-a7f8-11e9-8ea1-ecb735c798ac.png)

No outro dia recebi uma outra mensagem para contatar a vocês para que possa me ajudar.

''Mixer Partnerships Onboarding Team <mixeroas@microsoft.com>

Hi GenaroFPS,

Thanks so much for the heads up, it looks like you're having issues with Partner Center setup. Please follow the instructions below to get this resolved:

Go to https://developer.. Under Contact us, choose the Developer support topic of Dashboard Issue. Then choose the Issue Type of Account setup & management. Head over to the right-hand side of your screen and click the SUBMIT AN INCIDENT button. In the New support request window, please fill out the Issue title as "Mixer/Beam Partner GenaroFPS: Partner Center Setup Issue", fill out your first and last name and the email entries, then enter information regarding the error you are experiencing and hit the submit button.

Let me know your ticket number if they don't answer you within 24 hours.

Thanks,

Michaela''

Preciso da ajuda de vocês para solucionar este problemas pois estou no processo de inscrição para parceria.

![1](https://user-images.githubusercontent.com/52979713/61331641-9ed50780-a7f8-11e9-8aae-8a0d34b50654.png)
![2](https://user-images.githubusercontent.com/52979713/61331642-9ed50780-a7f8-11e9-84b3-95eefecbee1f.png)

**Comment by hkhmsft** [comment]
Thanks for taking the time to let us know about this. However, this feels not so much like feedback specifically about the documentation but rather like a support request. Here are all of the developer support resources, for completeness.

 - The [Feedback Hub app](https://support.microsoft.com/help/4021566/windows-10-send-feedback-to-microsoft-with-feedback-hub-app) is the right place to lobby for a change, a feature, or to make a suggestion.
 - For community assistance with development questions, there are our [forums](https://social.msdn.microsoft.com/Forums/newthread?category=windowsapps&forum=wpdevelop&prof=required), and [StackOverflow](https://stackoverflow.com/questions).
 - The [Windows developer support](https://developer.microsoft.com/windows/support) site explains other support options.
 - The [Visual Studio developer community](https://developercommunity.visualstudio.com) is available, and responsive. The former User Voice feature is now there on the **Suggest a feature** tab, if you want to lobby for a change, a feature, or to make a suggestion.
 - For developer issues, or suspected product bugs, there's [Microsoft Support](https://support.microsoft.com/contactus); a support engineer will look at the repro and see whether the issue is a Microsoft product bug, or something else. If it's a bug with a Microsoft product then the ticket will be free of charge.
 
 If you receive assistance via any support resource, and you believe that information would help us improve the docs, then please come back and let us know.
