### ISSUE TITLE
Call out CommandBar's access key behavior.

### ISSUE THREAD

**Issue by YuliKl** [MicrosoftDocs/windows-uwp#1803]
Assigning an access key to CommandBar will place the key tip over the More button without changing the scope of the access keys. This behavior is currently not documented but should be.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 80f24bef-6dfe-9b8b-e6aa-5582f231e28a
* Version Independent ID: f910182d-b917-121c-fc81-e39139f5faa3
* Content: [Access keys design guidelines - Windows UWP applications](https://docs.microsoft.com/en-us/windows/uwp/design/input/access-keys)
* Content Source: [windows-apps-src/design/input/access-keys.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/design/input/access-keys.md)
* Product: **uwp**
* Technology: **design**
* GitHub Login: @Karl-Bridge-Microsoft
* Microsoft Alias: **kbridge**

**Comment by hkhmsft** [comment]
I see that updates have not been made since the creation of this Issue so I went ahead and created an internal work item to document this behavior. The timeline for this may vary, so I will go ahead and close this and circle back when the changes are live. 

Though the Issue will be marked as Closed, I will monitor any replies that come afterwards so treat this like an open Issue. Many thanks @YuliKl !
