### ISSUE TITLE
Should specify directory as well as file name for x:Uid

### ISSUE THREAD

**Issue by sjb-sjb** [MicrosoftDocs/windows-uwp#1805]
Concerning the example in the section "Factoring strings into multiple Resources Files": additional information is needed about how to also specify the directory name. In the example, how can we specify the resource directory ("/Strings") in addition to the resource file name? 

I would comment that in some situations the directory name is needed to find the resource. For example, if resource files are in multiple directories and the x:Uid is within a DataTemplate, then the directory is needed. Omitting it may result in either the template silently failing or else throwing an Argument Null exception with argument name 'key', in a dictionary operation. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f354ce8d-e4be-4974-eb8a-67d7a59efce4
* Version Independent ID: bf779ef7-e6de-fc16-5446-2e3581fdbaa4
* Content: [Localize strings in your UI and app package manifest - Windows UWP applications](https://docs.microsoft.com/en-us/windows/uwp/app-resources/localize-strings-ui-manifest)
* Content Source: [windows-apps-src/app-resources/localize-strings-ui-manifest.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/app-resources/localize-strings-ui-manifest.md)
* Product: **uwp**
* Technology: **data-and-files**
* GitHub Login: @knicholasa
* Microsoft Alias: **nichola**

**Comment by hkhmsft** [comment]
Thanks for submitting your feedback and I apologize for the delayed response. I see that updates have not been made since the creation of this Issue so I went ahead and created an internal work item for new content. The timeline for this may vary, so I will go ahead and close this and circle back when the remark or the code snippet has been added. 

Though the Issue will be marked as Closed, I will monitor any replies that come afterwards so treat this like an open Issue. Many thanks!
