### ISSUE TITLE
Rotating Ad Banners

### ISSUE THREAD

**Issue by RexfelisLOC** [MicrosoftDocs/windows-uwp#1806]
Rotating ad banners should also be a policy violation as it interferes with viewability of ads thereby reducing CTR.  When you have low CTR, advertisers pull out.

**Comment by mijacobs** [comment]
Hi @RexfelisLOC, is this feedback about UWP in-app advertising guidelines or is it about rotating ads that appear on docs.microsoft.com? If this feedback is about UWP in-app advertising, it looks like you have product feedback rather than documentation feedback. Please use the [Windows developer feedback site](https://wpdev.uservoice.com/). We’d be happy to have this on record, where others can view it and upvote it.

**Comment by RexfelisLOC** [comment]
I was told by the Microsoft Advertising SDK team that rotating ad banners is not allowed, but it is not covered in the guidelines.  If it is not allowed, shouldn't it be covered in the guidelines?

**Comment by mijacobs** [comment]
@Karl-Bridge-Microsoft , this probably is for this article:
https://docs.microsoft.com/en-us/windows/uwp/monetize/ui-and-user-experience-guidelines

**Comment by hickeys** [comment]
Thanks for logging this. I've checked with the team to get more precise information regarding our rotating banner ad policy, and will update the documentation when I understand our policy.

**Comment by GrantMeStrength** [comment]
We are changing the way we track issues filed from our documentation pages: please see this [blog post](https://techcommunity.microsoft.com/t5/microsoft-learn-blog/announcing-a-new-way-to-give-feedback-on-microsoft-learn/ba-p/4027635) for more details. The Microsoft Store documentation has been updated several times since your issue was reported, and there's a good chance your problem has been addressed. Right now, this issue is being closed but if you feel it is still valid and has not been addressed, please re-open it with any more available information. Please note that if you question is more general and not related to documentation, [Microsoft Q&A](https://learn.microsoft.com/en-us/answers/questions/) is a great way to get questions answered.
