### ISSUE TITLE
Document(ja-jp) is not translated.

### ISSUE THREAD

**Issue by CeciAc** [MicrosoftDocs/windows-uwp#1822]
Hi team, 
I'm moving this from here: https://github.com/MicrosoftDocs/windows-uwp.ja-jp/issues/51 
There's a paragrph which is not localized in all locales due a source issue

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8c611201-543d-0dba-54ba-ebf351b6cad0
* Version Independent ID: 5a4827fa-32b1-22b2-9eea-71b4144ae1d0
* Content: [Accessibility in Windows 10 - Windows apps](https://docs.microsoft.com/en-us/windows/apps/accessibility)
* Content Source: [hub/apps/accessibility.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/hub/apps/accessibility.md)
* Product: **uwp**
* Technology: **apps**
* GitHub Login: @Karl-Bridge-Microsoft
* Microsoft Alias: **kbridge**

**Comment by CeciAc** [comment]
Comment from our engineer team:

> File should be indentated in a different way, as you can see below, the unlocalized text in the localizaed languages is actually taken as codebox on the source file:

![imagen](https://user-images.githubusercontent.com/26746247/61900927-fbb97780-aef4-11e9-9bee-5d3a47caac3c.png)

**Comment by Karl-Bridge-Microsoft** [comment]
Hi @CeciAc, can you clarify this issue? I'm not sure what the fix is for "should be indented in a different way". According to the docs contributor guide, the issue might be with the heading, which is apparently not supported within the columns extension. I've revised the topic for that issue, so please reactivate if that doesn't fix your loc issue.
