### ISSUE TITLE
VSIX Templates are missing from marketplace

### ISSUE THREAD

**Issue by michael-hawker** [MicrosoftDocs/windows-uwp#1823]
This article mentions templates available in the Visual Studio Marketplace, but the link just goes to the marketplace home page and searching doesn't return any results?  It'd be nice for the templates to be re-uploaded to the marketplace?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8c161a2e-d9f4-466f-5a63-5e25648a1779
* Version Independent ID: 6032f644-b69d-622f-73df-bacebdfc4509
* Content: [Create a multi-instance Universal Windows App - Windows UWP applications](https://docs.microsoft.com/en-us/windows/uwp/launch-resume/multi-instance-uwp)
* Content Source: [windows-apps-src/launch-resume/multi-instance-uwp.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/launch-resume/multi-instance-uwp.md)
* Product: **uwp**
* Technology: **processes-and-threading**
* GitHub Login: @knicholasa
* Microsoft Alias: **nichola**

**Comment by LanceMcCarthy** [comment]
It turns out the package is still there, but the search feature of the Marketplace is broken and nothing returns a result.

May I suggest adding a hyperlink right to the package? Otherwise, there is no way to discover and download it. 

Here's the url - https://marketplace.visualstudio.com/items?itemName=AndrewWhitechapelMSFT.MultiInstanceApps

**Comment by knicholasa** [comment]
Thanks for catching that @michael-hawker , and thanks for finding the correct template @LanceMcCarthy !

I'll update the url on the page, it should show up within a day or so.
