### ISSUE TITLE
Pick a file certificate with the app manifest

### ISSUE THREAD

**Issue by jb92** [MicrosoftDocs/windows-uwp#1831]
Hello,

The doc about [Configuring an app package](https://docs.microsoft.com/fr-fr/windows/uwp/packaging/packaging-uwp-apps#configure-a-package-with-the-manifest-designer) says:
" Notes
Starting in Visual Studio 2019, a temporary certificate is no longer generated in UWP projects. To create or export certificates, use the PowerShell cmdlets described in this article."

So yes, inside the manifest design, the option to create a test certificate is not available anymore but the option to pick a file on the machine for signing the package is not available either (Select  from file …).
My issue is, than the DropDownList "Configure Certificate"
![DropdownVS2017](https://user-images.githubusercontent.com/8761620/62035390-02dfce80-b1f0-11e9-8a39-4f532e9135d9.png)
(dropdown from vs2017)
doesn’t exist anymore, 
today in VS2019 it’s just a Button name "Select a Certificate…".
![DropdownVS2019](https://user-images.githubusercontent.com/8761620/62035413-0c693680-b1f0-11e9-935c-ef39e107cc87.png)
(button from vs2019)
So is this a bug or maybe the documentation missed this point?

**Comment by jamesmcroft** [comment]
I think the function in VS 2019 to select a certificate is by design but obviously is a major change from VS 2017 which gave you the freedom to provide the certificate as you'd like.

There definitely seems to be some more information missing in the doc you referenced about the change in VS 2019. 

The link it provides in the additional article does shed some light on how creating the signing cert will be added to the certificate store through PowerShell which is how you'd access them now in VS 2019.

**Comment by jamesmcroft** [comment]
Interestingly, it looks like this has been fixed in the Visual Studio 2019 16.3 release according to the release notes. 

References:
- https://docs.microsoft.com/en-us/visualstudio/releases/2019/release-notes#top-issues-fixed-in-visual-studio-2019-version-1630
- https://developercommunity.visualstudio.com/content/problem/612872/create-test-certificate-option-missing-from-uwp-sd.html

**Comment by jamesmcroft** [comment]
Just checked and confirmed that this is fixed now. 

![Certs](https://user-images.githubusercontent.com/13505183/65508658-9835d100-dec8-11e9-9de2-9f2e602e16ab.PNG)

The docs for this will probably need to be updated to reflect this.

**Comment by jb92** [comment]
I just tested and I'm confirmed you, it’s working for me too.
I’m glad to re-use VS2019 ^^ from now.
