### ISSUE TITLE
Update of offline licensed and distributed apps

### ISSUE THREAD

**Issue by shyamvs1001** [MicrosoftDocs/windows-uwp#1845]
Could you please clarify how the extensions distributed offline along with license are updated? If it is updated in the store does it update in the user's browser also? Could you please explain this scenario? It would help us provide this option to our customers.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6ad7be45-44d1-9ebe-4731-bdc64abb2127
* Version Independent ID: 9b9197c3-1301-3405-b700-36fa3698cca9
* Content: [Organizational licensing options - Windows UWP applications](https://docs.microsoft.com/en-us/windows/uwp/publish/organizational-licensing#feedback)
* Content Source: [windows-apps-src/publish/organizational-licensing.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/publish/organizational-licensing.md)
* Product: **uwp**
* Technology: **publish**
* GitHub Login: @hickeys
* Microsoft Alias: **hickeys**

**Comment by GrantMeStrength** [comment]
We are changing the way we track issues filed from our documentation pages: please see this [blog post](https://techcommunity.microsoft.com/t5/microsoft-learn-blog/announcing-a-new-way-to-give-feedback-on-microsoft-learn/ba-p/4027635) for more details. The Microsoft Store documentation has been updated several times since your issue was reported, and there's a good chance your problem has been addressed. Right now, this issue is being closed but if you feel it is still valid and has not been addressed, please re-open it with any more available information. Please note that if you question is more general and not related to documentation, [Microsoft Q&A](https://learn.microsoft.com/en-us/answers/questions/) is a great way to get questions answered.
