### ISSUE TITLE
Payout Summary screen not updating

### ISSUE THREAD

**Issue by markseminatore** [MicrosoftDocs/windows-uwp#1848]
It has been well over a month since the Payout Summary screen has shown valid (or updated) information in Partner Center. When will this be fixed?

**Comment by hkhmsft** [comment]
Thanks for taking the time to let us know about this. However, this feels not so much like feedback specifically about the documentation but rather like a support request. Here are all of the developer support resources, for completeness.

 - The [Feedback Hub app](https://support.microsoft.com/help/4021566/windows-10-send-feedback-to-microsoft-with-feedback-hub-app) is the right place to lobby for a change, a feature, or to make a suggestion.
 - For community assistance with development questions, there are our [forums](https://social.msdn.microsoft.com/Forums/newthread?category=windowsapps&forum=wpdevelop&prof=required), and [StackOverflow](https://stackoverflow.com/questions).
 - The [Windows developer support](https://developer.microsoft.com/windows/support) site explains other support options.
 - The [Visual Studio developer community](https://developercommunity.visualstudio.com) is available, and responsive. The former User Voice feature is now there on the **Suggest a feature** tab, if you want to lobby for a change, a feature, or to make a suggestion.
 - For developer issues, or suspected product bugs, there's [Microsoft Support](https://support.microsoft.com/contactus); a support engineer will look at the repro and see whether the issue is a Microsoft product bug, or something else. If it's a bug with a Microsoft product then the ticket will be free of charge.
 
 If you receive assistance via any support resource, and you believe that information would help us improve the docs, then please come back and let us know.
