### ISSUE TITLE
UI Design

### ISSUE THREAD

**Issue by DesignPolice** [MicrosoftDocs/windows-uwp#1866]
I have some specific questions I would like to follow-up with - looking for more specifics rather than the suggestions here and the Inclusive Toolkits. My specific questions are for a new WebApp.

Thanks, Marc

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 568bc213-2c78-5fbc-e839-bb1340474680
* Version Independent ID: e21ae4d6-85e7-5837-da6f-c1e527583dc7
* Content: [Designing inclusive software in Windows 10 - Windows UWP applications](https://docs.microsoft.com/en-us/windows/uwp/design/accessibility/designing-inclusive-software#feedback)
* Content Source: [windows-apps-src/design/accessibility/designing-inclusive-software.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/design/accessibility/designing-inclusive-software.md)
* Product: **uwp**
* Technology: **design**
* GitHub Login: @Karl-Bridge-Microsoft
* Microsoft Alias: **kbridge**

**Comment by Karl-Bridge-Microsoft** [comment]
Hi @DesignPolice, please submit your doc feedback and suggestions for improvements here. If you're looking for general product support you'll find quicker support by consulting our developer support resources. For community assistance with development questions I recommend that you ask on our [forums](https://social.msdn.microsoft.com/Forums/newthread?category=windowsapps&forum=wpdevelop&prof=required) or [StackOverflow](https://stackoverflow.com/questions). Otherwise, please see [the developer support page](https://developer.microsoft.com/windows/support) for your support options. If you get assistance through these other resources and believe that information would help us improve the docs, please come back and let us know.
