### ISSUE TITLE
Exception Showing Toast: Element not found. (Exception from HRESULT: 0x80070490)

### ISSUE THREAD

**Issue by marqdouj** [MicrosoftDocs/windows-uwp#1867]
I am using Win10 1903 (18362.295).
I created both a .NET Core 3.0 and .NET 4.7.2 WPF project (VS2019 Preview); installed both nuget pkgs, copied the code example and tried to run  it.
This line of code causes the error: ToastNotificationManager.CreateToastNotifier().Show(toast);
So I downloaded the nuget samples and tried to run the HelloWorldConsoleSample app - same issue.
Any ideas what is causing this error?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8d75cb81-9ff3-f9ad-8ad4-818e45da1d62
* Version Independent ID: f21e558d-b41f-bcfd-ca8a-9daabf7fa85a
* Content: [Use UWP APIs in desktop apps - Windows apps](https://docs.microsoft.com/en-us/windows/apps/desktop/modernize/desktop-to-uwp-enhance#set-up-your-project)
* Content Source: [hub/apps/desktop/modernize/desktop-to-uwp-enhance.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/hub/apps/desktop/modernize/desktop-to-uwp-enhance.md)
* Product: **uwp**
* Technology: **apps**
* GitHub Login: @mcleanbyron
* Microsoft Alias: **mcleans**

**Comment by RehanSaeed** [comment]
Also getting this exception thrown when I call:

```c#
ToastNotificationManager.History.GetHistory();
```

```
System.Exception
  HResult=0x80070490
  Message=Element not found. (Exception from HRESULT: 0x80070490)
  Source=<Cannot evaluate the exception source>
  StackTrace:
<Cannot evaluate the exception stack trace>
```

My csproj looks like this:

```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup Label="Build">
    <TargetFramework>net48</TargetFramework>
    <LangVersion>7.3</LangVersion>
    <NeutralLanguage>en-US</NeutralLanguage>
  </PropertyGroup>

  <ItemGroup Label="References">
    <Reference Include="System.Runtime.InteropServices.WindowsRuntime">
      <HintPath>..\..\..\Windows\Microsoft.NET\Framework\v4.0.30319\System.Runtime.InteropServices.WindowsRuntime.dll</HintPath>
    </Reference>
    <Reference Include="System.Runtime.WindowsRuntime">
      <HintPath>..\..\..\Windows\Microsoft.NET\Framework\v4.0.30319\System.Runtime.WindowsRuntime.dll</HintPath>
    </Reference>
    <Reference Include="System.Runtime.WindowsRuntime.UI.Xaml">
      <HintPath>..\..\..\Windows\Microsoft.NET\Framework\v4.0.30319\System.Runtime.WindowsRuntime.UI.Xaml.dll</HintPath>
    </Reference>
    <Reference Include="System.Speech" />
    <Reference Include="Windows">
      <HintPath>..\..\..\Program Files (x86)\Windows Kits\10\UnionMetadata\10.0.19023.0\Facade\windows.winmd</HintPath>
      <IsWinMDFile>true</IsWinMDFile>
      <Private>false</Private>
    </Reference>
    <Reference Include="Windows.Foundation.FoundationContract">
      <HintPath>..\..\..\Program Files (x86)\Windows Kits\10\References\10.0.19023.0\Windows.Foundation.FoundationContract\4.0.0.0\Windows.Foundation.FoundationContract.winmd</HintPath>
      <IsWinMDFile>true</IsWinMDFile>
      <Private>false</Private>
    </Reference>
    <Reference Include="Windows.Foundation.UniversalApiContract">
      <HintPath>..\..\..\Program Files (x86)\Windows Kits\10\References\10.0.19023.0\Windows.Foundation.UniversalApiContract\10.0.0.0\Windows.Foundation.UniversalApiContract.winmd</HintPath>
      <IsWinMDFile>true</IsWinMDFile>
      <Private>false</Private>
    </Reference>
  </ItemGroup>

</Project>
```

**Comment by hkhmsft** [comment]
Thanks for taking the time to let us know about this. However, this feels not so much like feedback specifically about the documentation but rather like a support request. Here are all of the developer support resources, for completeness.

 - The [Feedback Hub app](https://support.microsoft.com/help/4021566/windows-10-send-feedback-to-microsoft-with-feedback-hub-app) is the right place to lobby for a change, a feature, or to make a suggestion.
 - For community assistance with development questions, there are our [forums](https://social.msdn.microsoft.com/Forums/newthread?category=windowsapps&forum=wpdevelop&prof=required), and [StackOverflow](https://stackoverflow.com/questions).
 - The [Windows developer support](https://developer.microsoft.com/windows/support) site explains other support options.
 - The [Visual Studio developer community](https://developercommunity.visualstudio.com) is available, and responsive. The former User Voice feature is now there on the **Suggest a feature** tab, if you want to lobby for a change, a feature, or to make a suggestion.
 - For developer issues, or suspected product bugs, there's [Microsoft Support](https://support.microsoft.com/contactus); a support engineer will look at the repro and see whether the issue is a Microsoft product bug, or something else. If it's a bug with a Microsoft product then the ticket will be free of charge.
 
 If you receive assistance via any support resource, and you believe that information would help us improve the docs, then please come back and let us know.
