### ISSUE TITLE
storagefolder.GetFileAsync() resulting is resulting in a not found error

### ISSUE THREAD

**Issue by masterneko** [MicrosoftDocs/windows-uwp#1889]
here is some of my code:
            Windows.Storage.StorageFolder storageFolder = Windows.Storage.ApplicationData.Current.LocalFolder;
            Windows.Storage.StorageFile jsfile = await storageFolder.GetFileAsync("main.js");

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f09fb804-bc3e-ad66-d52d-c33f1cdda0ed
* Version Independent ID: 9b0a2d87-65f9-7b80-73a6-29d5a4c80ba1
* Content: [Create, write, and read a file - Windows UWP applications](https://docs.microsoft.com/en-us/windows/uwp/files/quickstart-reading-and-writing-files)
* Content Source: [windows-apps-src/files/quickstart-reading-and-writing-files.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/files/quickstart-reading-and-writing-files.md)
* Product: **uwp**
* Technology: **data-and-files**
* GitHub Login: @knicholasa
* Microsoft Alias: **nichola**

**Comment by knicholasa** [comment]
Thanks for reaching out with your feedback. The best way to get developer support is to consult our developer support resources. For community assistance with development questions I recommend that you ask on our [forums](https://social.msdn.microsoft.com/Forums/newthread?category=windowsapps&forum=wpdevelop&prof=required) or [StackOverflow](https://stackoverflow.com/questions). Otherwise, please see [the developer support page](https://developer.microsoft.com/windows/support) for your support options. If you get assistance through these other resources and believe that information would help us improve the docs, please come back and reopen the issue.
