### ISSUE TITLE
Error in FaceTracker

### ISSUE THREAD

**Issue by ghost** [MicrosoftDocs/windows-uwp#1892]
While trying to use the FaceTracker class with this code, I created a function which returns a VideoFrame. However, I get a design-time error stating that VideoFrame does not contain a definition for 'GetAwaiter'.

What am I missing here?

        VideoFrame currentFrame = await GetLatestFrame();
        
        private VideoFrame GetLatestFrame()
        {
            // Get information about the preview
            var previewProperties = mediaCaptureMgr.VideoDeviceController.GetMediaStreamProperties(MediaStreamType.VideoPreview) as VideoEncodingProperties;

            // Create a video frame in the desired format for the preview frame
            VideoFrame videoFrame = new VideoFrame(BitmapPixelFormat.Bgra8, (int)previewProperties.Width, (int)previewProperties.Height);

            return videoFrame;
        }

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 43011566-eda2-5292-5239-d62782adb6b6
* Version Independent ID: ebf8566a-d12d-3760-e2ef-26048833e95e
* Content: [Detect faces in images or videos - Windows UWP applications](https://docs.microsoft.com/en-us/windows/uwp/audio-video-camera/detect-and-track-faces-in-an-image)
* Content Source: [windows-apps-src/audio-video-camera/detect-and-track-faces-in-an-image.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/audio-video-camera/detect-and-track-faces-in-an-image.md)
* Product: **uwp**
* Technology: **audio-video-and-camera**
* GitHub Login: @drewbatgit
* Microsoft Alias: **drewbat**

**Comment by ghost** [comment]
I think I see my issue: I used a VideoFrame when I think I should have just used a Frame?

**Comment by drewbatgit** [comment]
Hello, issues in this repo are specifically intended for reporting documentation issues, not technical support. For community assistance with development questions I recommend that you ask on our [forums](https://social.msdn.microsoft.com/Forums/newthread?category=windowsapps&forum=wpdevelop&prof=required) or [StackOverflow](https://stackoverflow.com/questions). Otherwise, please see [the developer support page](https://developer.microsoft.com/windows/support) for your support options. If you get assistance through these other resources and believe that information would help us improve the docs, please come back and let us know. Although, it sounds like you may have already solved your issue.
