### ISSUE TITLE
Unable to initialize winrt::hstring using nullptr

### ISSUE THREAD

**Issue by trenthoppe** [MicrosoftDocs/windows-uwp#1898]
When attempting to initialize a null winrt::hstring using the documented syntax:
```
winrt::hstring{ nullptr }
```
I receive - Error C228 'winrt::hstring::hstring(std::nullptr_t)': attempting to reference a deleted function. 

If I initialize it using an empty string: L"", which is identical to null, it works fine. Is this the correct way to initialize a null winrt::hstring? Or is this unintended behavior?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 853d8f9e-c1eb-7fe8-4ce2-a476d8cb1fc9
* Version Independent ID: 924da36c-5517-190d-edda-5bd500830d81
* Content: [Move to C++/WinRT from C++/CX - Windows UWP applications](https://docs.microsoft.com/en-us/windows/uwp/cpp-and-winrt-apis/move-to-winrt-from-cx#boxing-and-unboxing)
* Content Source: [windows-apps-src/cpp-and-winrt-apis/move-to-winrt-from-cx.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/cpp-and-winrt-apis/move-to-winrt-from-cx.md)
* Product: **uwp**
* Technology: **platform**
* GitHub Login: @stevewhims
* Microsoft Alias: **stwhi**

**Comment by stevewhims** [comment]
Yes, that looks like it was meant to be `hstring{}` instead of the syntactically invalid `hstring{ nullptr}`. I just published a fix to the topic (in the two places it was wrong).

To create a local, "null", hstring, I'd write

```cppwinrt
winrt::hstring myString;
```

To pass a "null" hstring into a function that takes an hstring, I'd write

```cppwinrt
winrt::hstring myString;
Foo(myString);

// Or

Foo(winrt::hstring{});
```

I'll go ahead and close the issue. Thanks for finding this!

Steve
