### ISSUE TITLE
Treeview with Data Binding wrong displayed

### ISSUE THREAD

**Issue by ghost** [MicrosoftDocs/windows-uwp#1902]
I just did a completely new installation of windows (Windows 1803). Now the tree view with data binding is displayed wrong. Also the sample in the XAML Controls Gallery displays the examples with data binding and ItemTemplateSelector are wrong.

![2019-09-05](https://user-images.githubusercontent.com/4369528/64367435-419b4c80-d018-11e9-90ff-5847f2a5650e.png)

**Comment by StephenLPeters** [comment]
This looks like a xaml controls gallery bug, could you file it here: https://github.com/microsoft/Xaml-Controls-Gallery? Thanks!

**Comment by hkhmsft** [comment]
I also encourage you to use the following developer resources:

 - The [Feedback Hub app](https://support.microsoft.com/help/4021566/windows-10-send-feedback-to-microsoft-with-feedback-hub-app) is the right place to lobby for a change, a feature, or to make a suggestion.
 - For community assistance with development questions, there are our [forums](https://social.msdn.microsoft.com/Forums/newthread?category=windowsapps&forum=wpdevelop&prof=required), and [StackOverflow](https://stackoverflow.com/questions).
 - The [Windows developer support](https://developer.microsoft.com/windows/support) site explains other support options.
 - The [Visual Studio developer community](https://developercommunity.visualstudio.com) is available, and responsive. The former User Voice feature is now there on the **Suggest a feature** tab, if you want to lobby for a change, a feature, or to make a suggestion.
 - For developer issues, or suspected product bugs, there's [Microsoft Support](https://support.microsoft.com/contactus); a support engineer will look at the repro and see whether the issue is a Microsoft product bug, or something else. If it's a bug with a Microsoft product then the ticket will be free of charge.
 
 If you receive assistance via any support resource, and you believe that information would help us improve the docs, then please come back and let us know.
