### ISSUE TITLE
App Promotion Product is being shut down

### ISSUE THREAD

**Issue by dospolov** [MicrosoftDocs/windows-uwp#1918]
Note: App Promotion Product is being shut down. The campaigns will stop running after 15th June and the data will be available till 30th September.

---
#### Сведения о документе

⚠ *Не вносите правки в этот раздел. Это необходимо для связывания страницы сайта docs.microsoft.com с вопросом на GitHub.*

* ID: c5246f44-3161-7cbb-0da4-ca75e02348dd
* Version Independent ID: 1385fdc0-2772-6ba4-f6ab-a481c0a0465d
* Content: [Общие вопросы о рекламных кампаниях - Windows UWP applications](https://docs.microsoft.com/ru-ru/windows/uwp/publish/common-questions#feedback)
* Content Source: [windows-apps-src/publish/common-questions.md](https://github.com/MicrosoftDocs/windows-uwp.ru-ru/blob/live/windows-apps-src/publish/common-questions.md)
* Product: **uwp**
* Technology: **publish**
* GitHub Login: @hickeys
* Microsoft Alias: **hickeys**

**Comment by julioct** [comment]
What is the alternative?

**Comment by Karl-Bridge-Microsoft** [comment]
Thanks for taking the time to let us know about this issue and we sincerely apologize for the delayed response. 

As this page has been updated since you reported the issue, and the sheer volume of of feedback in this repo requires us to prioritize new issues, we're closing this one due to age and lack of activity.

If you think the issue still exists and should be addressed, please open a new issue with any details/suggestions you think might be helpful.
