### ISSUE TITLE
Instructions not updated for Windows 1903 and Visual Studio 2019

### ISSUE THREAD

**Issue by msavazzi** [MicrosoftDocs/windows-uwp#1937]
SQLite do not work correctly on 1903 and Visual Studio 2019

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6c591596-d202-244c-6fbf-31c288fe9b57
* Version Independent ID: 1473907c-0cba-8917-2fd8-d3ca1fb73cae
* Content: [Use a SQLite database in a UWP app - Windows UWP applications](https://docs.microsoft.com/en-us/windows/uwp/data-access/sqlite-databases#feedback)
* Content Source: [windows-apps-src/data-access/sqlite-databases.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/data-access/sqlite-databases.md)
* Product: **uwp**
* Technology: **data-and-files**
* GitHub Login: @knicholasa
* Microsoft Alias: **nichola**

**Comment by akledirs** [comment]
Use SQLite.Core v2.2.6, bundle_e_sqlite v1.1.14 for VS2019 on Windows 1903

**Comment by msavazzi** [comment]
Every time I open the solution I'm asked to update the SQLite.Core to V3.0.0 and SQLitePCLRaw.bundle_e_sqlite3 v.2.0.1 but if I update then on the db.open I get an error on the file not accessible.
Why? is it correct?
why the new version does not work?

here the error:
Microsoft.Data.Sqlite.SqliteException
  HResult=0x80004005
  Message=SQLite Error 14: 'unable to open database file'.
  Source=Microsoft.Data.Sqlite
  StackTrace:
   at Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(Int32 rc, sqlite3 db)
   at Microsoft.Data.Sqlite.SqliteConnection.Open()
   at TestSQLite_1.App..ctor() in C:\Users\...\Documents\Source\TestSQLite 1\TestSQLite 1\App.xaml.vb:line 22
   at TestSQLite_1.Program._Closure$__._Lambda$__1-0(ApplicationInitializationCallbackParams p) in C:\Users\...\Documents\Source\TestSQLite 1\TestSQLite 1\obj\x64\Debug\App.g.i.vb:line 23
   at TestSQLite_1.Program._Closure$__._Lambda$__R1-1(ApplicationInitializationCallbackParams a0)

**Comment by msavazzi** [comment]
Note the issue is opening files not in localapp folders but in Documents or any other folder on the PC

**Comment by jcg3675** [comment]
SQLite.Core to V3.0.0 not work? I have the same issue

**Comment by msavazzi** [comment]
> SQLite.Core to V3.0.0 not work? I have the same issue

I was not able to have it working. is SUPER BAD! I cannot develop a UWP app in this conditions

**Comment by hkhmsft** [comment]
Thanks for taking the time to let us know about this. However, this feels not so much like feedback specifically about the documentation but rather like a product feedback as you have expressed. @msavazzi I encourage you to use the following feedback and support platforms:

 - The [Feedback Hub app](https://support.microsoft.com/help/4021566/windows-10-send-feedback-to-microsoft-with-feedback-hub-app) is the right place to lobby for a change, a feature, or to make a suggestion.
 - For community assistance with development questions, there are our [forums](https://social.msdn.microsoft.com/Forums/newthread?category=windowsapps&forum=wpdevelop&prof=required), and [StackOverflow](https://stackoverflow.com/questions).
 - The [Windows developer support](https://developer.microsoft.com/windows/support) site explains other support options.
 - The [Visual Studio developer community](https://developercommunity.visualstudio.com) is available, and responsive. The former User Voice feature is now there on the **Suggest a feature** tab, if you want to lobby for a change, a feature, or to make a suggestion.
 - For developer issues, or suspected product bugs, there's [Microsoft Support](https://support.microsoft.com/contactus); a support engineer will look at the repro and see whether the issue is a Microsoft product bug, or something else. If it's a bug with a Microsoft product then the ticket will be free of charge.
 
 If you receive assistance via any support resource, and you believe that information would help us improve the docs, then please come back and let us know.
