### ISSUE TITLE
Does UWP still support making the app for Windows 10 Mobile?

### ISSUE THREAD

**Issue by vietlubu** [MicrosoftDocs/windows-uwp#1939]
Hi, I know Windows 10 Mobile will end at the end of this year. Just questions about this. Is there anything else besides no more update?
After that, can I access to Store to download apps?
Can I still make Windows 10 Mobile with UWP?
Thank you!

---
#### Chi tiết tài liệu

⚠ *Không chỉnh sửa phần này. Điều này là bắt buộc cho docs.microsoft.com ➟ Vấn đề khi liên kết GitHub.*

* ID: 1fcd2e7e-612d-29de-6b94-3bed0b772b16
* Version Independent ID: cf067679-95df-f7d2-17ec-d15cc18c0b4b
* Content: [What's a Universal Windows Platform (UWP) app? - Windows UWP applications](https://docs.microsoft.com/vi-vn/windows/uwp/get-started/universal-application-platform-guide#feedback)
* Content Source: [windows-apps-src/get-started/universal-application-platform-guide.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/get-started/universal-application-platform-guide.md)
* Product: **uwp**
* Technology: **get-started**
* GitHub Login: @QuinnRadich
* Microsoft Alias: **quradic**

**Comment by vietlubu** [comment]
@QuinnRadich Sorry, but have any answer for this question?

**Comment by ShinraCorpMixer** [comment]
I took a quick look around the Windows 10 SDK (the latest one anyway) and there's nothing mentioning about Windows 10 Mobile. Just says to develop for Windows 10 with Win32 or UWP. But that shouldn't really stop it from developing for mobile (ARM) I know that the Windows 10 Mobile store will cease to function someday as the OS is at the EoL however so people would need to side-load apps if they want to use it.

**Comment by hkhmsft** [comment]
Thanks for taking the time to let us know about this. However, this feels not so much like feedback specifically about the documentation but rather like a support request. Here are all of the developer support resources, for completeness.

 - The [Feedback Hub app](https://support.microsoft.com/help/4021566/windows-10-send-feedback-to-microsoft-with-feedback-hub-app) is the right place to lobby for a change, a feature, or to make a suggestion.
 - For community assistance with development questions, there are our [forums](https://social.msdn.microsoft.com/Forums/newthread?category=windowsapps&forum=wpdevelop&prof=required), and [StackOverflow](https://stackoverflow.com/questions).
 - The [Windows developer support](https://developer.microsoft.com/windows/support) site explains other support options.
 - The [Visual Studio developer community](https://developercommunity.visualstudio.com) is available, and responsive. The former User Voice feature is now there on the **Suggest a feature** tab, if you want to lobby for a change, a feature, or to make a suggestion.
 - For developer issues, or suspected product bugs, there's [Microsoft Support](https://support.microsoft.com/contactus); a support engineer will look at the repro and see whether the issue is a Microsoft product bug, or something else. If it's a bug with a Microsoft product then the ticket will be free of charge.
 
 If you receive assistance via any support resource, and you believe that information would help us improve the docs, then please come back and let us know.
