### ISSUE TITLE
Error in "Obtain an Azure AD access token" and what are the various request json files?

### ISSUE THREAD

**Issue by lbrownell-gpsw** [MicrosoftDocs/windows-uwp#1941]
First,
  `tokenEndpoint = "https://login.microsoftonline.com/{0}/oauth2/token"`
should be
  `tokenEndpoint = "https://login.microsoftonline.com/{0}/oauth2/token".format(tennantId)`

Also, each of these examples includes something like 

`appSubmissionRequestJson = "";  # Your submission request JSON`

What is needed in that?  It's used but not set.  Unless null JSON is expected.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 945eca76-6f63-3ea1-a667-bf670ab8d3a9
* Version Independent ID: e77e4a75-589d-6ba3-95ca-58d7a721f072
* Content: [Python sample - submissions for apps, add-ons, and flights - Windows UWP applications](https://docs.microsoft.com/en-us/windows/uwp/monetize/python-code-examples-for-the-windows-store-submission-api#create-an-app-submission)
* Content Source: [windows-apps-src/monetize/python-code-examples-for-the-windows-store-submission-api.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/monetize/python-code-examples-for-the-windows-store-submission-api.md)
* Product: **uwp**
* Technology: **publish**
* GitHub Login: @hickeys
* Microsoft Alias: **hickeys**

**Comment by GrantMeStrength** [comment]
We are changing the way we track issues filed from our documentation pages: please see this [blog post](https://techcommunity.microsoft.com/t5/microsoft-learn-blog/announcing-a-new-way-to-give-feedback-on-microsoft-learn/ba-p/4027635) for more details. Right now, this issue is being closed but if you feel it is still valid and has not been addressed, please re-open it with any more available information. Please note that if your question is more general and not related to documentation, [Microsoft Q&A](https://learn.microsoft.com/en-us/answers/questions/) is a great way to get questions answered.
