### ISSUE TITLE
Unclear and Out of date instructions

### ISSUE THREAD

**Issue by mjfusa** [MicrosoftDocs/windows-uwp#1942]
In working with ISVs providing OEMs with thier apps, we ran into the following issues:
1. Can the text be updated to explain what an ISV needs to do in order to obtain the pre-install privileges on their Partner Center account?
2. The text needs to be updated to match the latest version of Partner Center.
3. These instructions are hard to find for partners asked by OEM to provide an app for installing in their image. It would be helpful to include text about sideloading, and explaining the difference between sideload and pre-install packages. Provide a link to the sideload docs.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 98fb27a9-dc14-fcfb-0d54-f2c2640fecda
* Version Independent ID: 5e306b46-4e3f-81c3-b80f-397d575d0374
* Content: [Generate preinstall packages for OEMs - Windows UWP applications](https://docs.microsoft.com/en-us/windows/uwp/publish/generate-preinstall-packages-for-oems)
* Content Source: [windows-apps-src/publish/generate-preinstall-packages-for-oems.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/publish/generate-preinstall-packages-for-oems.md)
* Product: **uwp**
* Technology: **publish**
* GitHub Login: @hickeys
* Microsoft Alias: **hickeys**

**Comment by GrantMeStrength** [comment]
We are changing the way we track issues filed from our documentation pages: please see this [blog post](https://techcommunity.microsoft.com/t5/microsoft-learn-blog/announcing-a-new-way-to-give-feedback-on-microsoft-learn/ba-p/4027635) for more details. The Microsoft Store documentation has been updated several times since your issue was reported, and there's a good chance your problem has been addressed. Right now, this issue is being closed but if you feel it is still valid and has not been addressed, please re-open it with any more available information. Please note that if you question is more general and not related to documentation, [Microsoft Q&A](https://learn.microsoft.com/en-us/answers/questions/) is a great way to get questions answered.
