### ISSUE TITLE
Targeted offers Error

### ISSUE THREAD

**Issue by mzhinf** [MicrosoftDocs/windows-uwp#1944]
I have encountered some problems in the Partner Center. In Partner Center, expand Engage in the left navigation menu, then select Targeted offers. Sometimes a prompt will appear: "There was an error processing your request. Please try again.", sometimes nothing will show up. I want to know if I am missing something, or what preconditions to create "Targeted offers". (My two accounts have the same problem)

![image](https://user-images.githubusercontent.com/35255621/65671036-19cc6100-e079-11e9-9f70-944573b62fe8.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 77ae80e6-33d9-38de-37a9-03338bd0612f
* Version Independent ID: 486a13a9-2bf7-79e2-44fa-54ac98d89766
* Content: [Use targeted offers to maximize engagement and conversions - Windows UWP applications](https://docs.microsoft.com/en-us/windows/uwp/publish/use-targeted-offers-to-maximize-engagement-and-conversions#feedback)
* Content Source: [windows-apps-src/publish/use-targeted-offers-to-maximize-engagement-and-conversions.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/publish/use-targeted-offers-to-maximize-engagement-and-conversions.md)
* Product: **uwp**
* Technology: **publish**
* GitHub Login: @hickeys
* Microsoft Alias: **hickeys**

**Comment by hkhmsft** [comment]
This feels not so much like feedback specifically about the documentation, but rather like a support request. Here are all of the developer support resources, for completeness.

 - The [Feedback Hub app](https://support.microsoft.com/help/4021566/windows-10-send-feedback-to-microsoft-with-feedback-hub-app) is the right place to lobby for a change, a feature, or to make a suggestion.
 - For community assistance with development questions, there are our [forums](https://social.msdn.microsoft.com/Forums/newthread?category=windowsapps&forum=wpdevelop&prof=required), and [StackOverflow](https://stackoverflow.com/questions).
 - The [Windows developer support](https://developer.microsoft.com/windows/support) site explains other support options.
 - The [Visual Studio developer community](https://developercommunity.visualstudio.com) is available, and responsive. The former User Voice feature is now there on the **Suggest a feature** tab, if you want to lobby for a change, a feature, or to make a suggestion.
 - For developer issues, or suspected product bugs, there's [Microsoft Support](https://support.microsoft.com/contactus); a support engineer will look at the repro and see whether the issue is a Microsoft product bug, or something else. If it's a bug with a Microsoft product then the ticket will be free of charge.
 
 If you receive assistance via any support resource, and you believe that information would help us improve the docs, then please come back and let us know.
