### ISSUE TITLE
The tag 'ResourceDictionary.ThemeDictionaries' does not exist in XML namespace

### ISSUE THREAD

**Issue by ajaywhiz** [MicrosoftDocs/windows-uwp#1952]
I'm getting a compilation error MC3074: The tag 'ResourceDictionary.ThemeDictionaries' does not exist in XML namespace 'http://schemas.microsoft.com/winfx/2006/xaml/presentation'. I'm WPF app is targeting framework 4.6.1. Any ideas what could be wrong?

Thanks. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 43a544cb-3e05-74ea-3ec2-b8a167c03694
* Version Independent ID: 070f4120-dcc0-4fbb-1ae9-ac3c7fc58dc5
* Content: [High-contrast themes - Windows UWP applications](https://docs.microsoft.com/en-us/windows/uwp/design/accessibility/high-contrast-themes)
* Content Source: [windows-apps-src/design/accessibility/high-contrast-themes.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/design/accessibility/high-contrast-themes.md)
* Product: **uwp**
* Technology: **design**
* GitHub Login: @Karl-Bridge-Microsoft
* Microsoft Alias: **kbridge**

**Comment by Karl-Bridge-Microsoft** [comment]
Thanks for reaching out, You'll find quicker support by consulting our developer support resources. For community assistance with development questions I recommend that you ask on our [forums](https://social.msdn.microsoft.com/Forums/newthread?category=windowsapps&forum=wpdevelop&prof=required) or [StackOverflow](https://stackoverflow.com/questions). Otherwise, please see [the developer support page](https://developer.microsoft.com/windows/support) for your support options. If you get assistance through these other resources and believe that information would help us improve the docs, please come back and let us know.
