### ISSUE TITLE
Resizing an UWP app after it being idle for long time crashes dwm.exe

### ISSUE THREAD

**Issue by someniatko** [MicrosoftDocs/windows-uwp#1969]
I am on Windows 1903 + latest cumulative patches as of now. I open Settings app. Leave it alone for say 30 minutes. During these 30 minutes I interact with other apps, doesn't matter UWP or not. Then I come back to Settings and resize it by dragging its corner. As a result, whole DWM crashes rendering my screen black for a moment. Then it automatically restores.

This happens with ALL uwp apps, including 3rdparty ones, and doesn't happen with non-UWP ones (if not counting those having some bugs interacting with low-level Windows APIs). This bug reproduces on various configurations and video cards, including AMD RX 580, Intel UHD Graphics 620, Nvidia MX150.

**Comment by stevewhims** [comment]
Hi, @someniatko, thanks for filing this issue. This feels not so much like feedback specifically about the documentation, but rather like a question/feedback/support about the product itself.

You can leave feedback about the documenation by visiting a topic and clicking **Send feedback about** \> **This page**. If instead you click **Send feedback about** \> **This product**, then you'll be taken to the [Feedback Hub app](https://support.microsoft.com/help/4021566/windows-10-send-feedback-to-microsoft-with-feedback-hub-app) (more info about that below).

Here are all of the developer support resources, for completeness.
- The [Feedback Hub app](https://support.microsoft.com/help/4021566/windows-10-send-feedback-to-microsoft-with-feedback-hub-app) is the right place to lobby for a change, a feature, or to make a suggestion.
- For community assistance with development questions, there are our [forums](https://social.msdn.microsoft.com/Forums/newthread?category=windowsapps&forum=wpdevelop&prof=required), and [StackOverflow](https://stackoverflow.com/questions).
- The [Windows developer support](https://developer.microsoft.com/windows/support) site explains other support options.
- The [Visual Studio developer community](https://developercommunity.visualstudio.com) is available, and responsive. The former User Voice feature is now there on the **Suggest a feature** tab, if you want to lobby for a change, a feature, or to make a suggestion.
- For developer issues, or suspected product bugs, there's [Microsoft Support](https://support.microsoft.com/contactus); a support engineer will look at the repro and see whether the issue is a Microsoft product bug, or something else. If it's a bug with a Microsoft product then the ticket will be free of charge.

Sorry that I couldn't be of more immediate help here.
-Steve

**Comment by someniatko** [comment]
Thank you.
