### ISSUE TITLE
PropVariantToWinRTPropertyValue and boolean values problem

### ISSUE THREAD

**Issue by benstevens48** [MicrosoftDocs/windows-uwp#1970]
I don't really know where to post this issue, since UserVoice seems to have been closed, but anyway...

Some of the WIC APIs, such as `IWICMetadataQueryReader->GetMetadataByName(L"/logscrdesc/GlobalColorTableFlag", &propVar)` return a `PROPVARIANT` with `vt` equal ot `VT_BOOL` and a `boolVal` of `1` instead of `-1` (which is the correct value according to the docs) to represent `True`. This means that `PropVariantToWinRTPropertyValue` fails to convert this `PROPVARIANT` to an `IPropertyValue`. I don't know if this is a bug in WIC or whether the function `PropVariantToWinRTPropertyValue` should also allow `1` to represent `True`. Either way, I imagine this function is used quite a lot to interop between Win32 APIs and UWP, so either the function should be fixed or WIC should be fixed.

**Comment by stevewhims** [comment]
Hi, @benstevens48, I'll give you a link to the replacement for UserVoice. See the info in this reply about the Feedback Hub app.

This feels not so much like feedback specifically about the documentation, but rather like a question/feedback/support about the product itself. As you know, you can leave feedback about the documentation by visiting a topic and clicking **Send feedback about** \> **This page**. If instead you click **Send feedback about** \> **This product**, then you'll be taken to the [Feedback Hub app](https://support.microsoft.com/help/4021566/windows-10-send-feedback-to-microsoft-with-feedback-hub-app) (more info about that below).

Here are all of the developer support resources, for completeness.
- The [Feedback Hub app](https://support.microsoft.com/help/4021566/windows-10-send-feedback-to-microsoft-with-feedback-hub-app) is the right place to lobby for a change, a feature, or to make a suggestion.
- For community assistance with development questions, there are our [forums](https://social.msdn.microsoft.com/Forums/newthread?category=windowsapps&forum=wpdevelop&prof=required), and [StackOverflow](https://stackoverflow.com/questions).
- The [Windows developer support](https://developer.microsoft.com/windows/support) site explains other support options.
- The [Visual Studio developer community](https://developercommunity.visualstudio.com) is available, and responsive. The former User Voice feature is now there on the **Suggest a feature** tab, if you want to lobby for a change, a feature, or to make a suggestion.
- For developer issues, or suspected product bugs, there's [Microsoft Support](https://support.microsoft.com/contactus); a support engineer will look at the repro and see whether the issue is a Microsoft product bug, or something else. If it's a bug with a Microsoft product then the ticket will be free of charge.

Sorry that I couldn't be of more immediate help here.
-Steve

**Comment by benstevens48** [comment]
Ok, thanks. It wasn't really a support request or product question. I was trying to be helpful and report a bug. It would actually be useful if this bug was mentioned somewhere in the WIC documentation, e.g. on this page - https://docs.microsoft.com/en-us/windows/win32/wic/-wic-native-image-format-metadata-queries - but there is no way to give feedback on that page.
