### ISSUE TITLE
Does need to call db.Close() in using statement

### ISSUE THREAD

**Issue by uponatime2019** [MicrosoftDocs/windows-uwp#1972]
sqlite-databases.md
```
    using (SqliteConnection db =
        new SqliteConnection("Filename=sqliteSample.db"))
    {
        db.Open();

        // do stuff

        db.Close();
    }
```
Does db.Close() is necessary?

**Comment by jwmsft** [comment]
https://docs.microsoft.com/windows/uwp/data-access/sqlite-databases

**Comment by hkhmsft** [comment]
Thanks for submitting your feedback and I apologize for the delayed response. I see that updates have not been made since the creation of this Issue so I went ahead and created an internal work item to incorporate your suggestions. The timeline for this may vary, so I will go ahead and close this and circle back when the changes are live. 

Though the Issue will be marked as Closed, I will monitor any replies that come afterwards so treat this like an open Issue. Many thanks!
