### ISSUE TITLE
Print HTML content

### ISSUE THREAD

**Issue by bastecklein** [MicrosoftDocs/windows-uwp#1978]
UWP needs a way to be able to print HTML content, without the gimmicky WebViewBrush method.  There are many, many scenarios, especially in enterprise tools, where you would want to quickly create a form using HTML elements and print it out.  It is universal, quick, and simple.  This is trivial on the Android, iOS, and on the Web, but near impossible with UWP.  This would make it extremely fast and easy to generate reports without having to create a bunch of custom XAML elements to print for different scenarios.

**Comment by hkhmsft** [comment]
Thanks so much for the suggestion, but this feels not so much like feedback specifically about the documentation, but rather like a product feedback. Here are all of the developer support resources, for completeness.

 - The [Feedback Hub app](https://support.microsoft.com/help/4021566/windows-10-send-feedback-to-microsoft-with-feedback-hub-app) is the right place to lobby for a change, a feature, or to make a suggestion.
 - For community assistance with development questions, there are our [forums](https://social.msdn.microsoft.com/Forums/newthread?category=windowsapps&forum=wpdevelop&prof=required), and [StackOverflow](https://stackoverflow.com/questions).
 - The [Windows developer support](https://developer.microsoft.com/windows/support) site explains other support options.
 - The [Visual Studio developer community](https://developercommunity.visualstudio.com) is available, and responsive. The former User Voice feature is now there on the **Suggest a feature** tab, if you want to lobby for a change, a feature, or to make a suggestion.
 - For developer issues, or suspected product bugs, there's [Microsoft Support](https://support.microsoft.com/contactus); a support engineer will look at the repro and see whether the issue is a Microsoft product bug, or something else. If it's a bug with a Microsoft product then the ticket will be free of charge.
 
 If you receive assistance via any support resource, and you believe that information would help us improve the docs, then please come back and let us know.
