### ISSUE TITLE
How do you stop the session from c++/cx code?

### ISSUE THREAD

**Issue by ambrybenoit** [MicrosoftDocs/windows-uwp#1979]
I am trying the Screen Capture api and everything seems to work up to the point where I want to stop the recording.
I am using Direct3D11CaptureFramePool.CreateCaptureSession(GraphicsCaptureItem).

There's no api to stop and clearing the session of capture item object crashes.

How do you stop the recording in a c++/cx application?

**Comment by stevewhims** [comment]
Hi, @ambrybenoit, thanks for filing this issue. Be aware that C++/CX is no longer current, and has been superseded by [C++/WinRT](https://docs.microsoft.com/windows/uwp/cpp-and-winrt-apis/index).

This feels not so much like feedback specifically about the documentation, but rather like a question/feedback/support about the product itself. You can leave feedback about the documentation by visiting a topic and clicking **Send feedback about** \> **This page**. If instead you click **Send feedback about** \> **This product**, then you'll be taken to the [Feedback Hub app](https://support.microsoft.com/help/4021566/windows-10-send-feedback-to-microsoft-with-feedback-hub-app) (more info about that below).

Here are all of the developer support resources, for completeness.
- The [Feedback Hub app](https://support.microsoft.com/help/4021566/windows-10-send-feedback-to-microsoft-with-feedback-hub-app) is the right place to lobby for a change, a feature, or to make a suggestion.
- For community assistance with development questions, there are our [forums](https://social.msdn.microsoft.com/Forums/newthread?category=windowsapps&forum=wpdevelop&prof=required), and [StackOverflow](https://stackoverflow.com/questions).
- The [Windows developer support](https://developer.microsoft.com/windows/support) site explains other support options.
- The [Visual Studio developer community](https://developercommunity.visualstudio.com) is available, and responsive. The former User Voice feature is now there on the **Suggest a feature** tab, if you want to lobby for a change, a feature, or to make a suggestion.
- For developer issues, or suspected product bugs, there's [Microsoft Support](https://support.microsoft.com/contactus); a support engineer will look at the repro and see whether the issue is a Microsoft product bug, or something else. If it's a bug with a Microsoft product then the ticket will be free of charge.

Sorry that I couldn't be of more immediate help here.
-Steve
