### ISSUE TITLE
Is the server blocked now?

### ISSUE THREAD

**Issue by hatasum** [MicrosoftDocs/windows-uwp#1980]
@hickeys,
Is the server blocked now?
And please notice this issue:
https://github.com/MicrosoftDocs/windows-uwp/issues?utf8=%E2%9C%93&q=%229bfcea4f-a9cb-ab64-df07-90512002d80b%22&in=body

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a2ac48f9-fd0e-0f1e-fc75-f28cf0b83f57
* Version Independent ID: 9bfcea4f-a9cb-ab64-df07-90512002d80b
* Content: [C# sample - submissions for apps, add-ons, and flights - Windows UWP applications](https://docs.microsoft.com/en-us/windows/uwp/monetize/csharp-code-examples-for-the-windows-store-submission-api)
* Content Source: [windows-apps-src/monetize/csharp-code-examples-for-the-windows-store-submission-api.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/monetize/csharp-code-examples-for-the-windows-store-submission-api.md)
* Product: **uwp**
* Technology: **publish**
* GitHub Login: @hickeys
* Microsoft Alias: **hickeys**

**Comment by hatasum** [comment]
StatusCode: 403

**Comment by hkhmsft** [comment]
This feels not so much like feedback specifically about the documentation, but rather like a support request. Here are all of the developer support resources, for completeness.

 - The [Feedback Hub app](https://support.microsoft.com/help/4021566/windows-10-send-feedback-to-microsoft-with-feedback-hub-app) is the right place to lobby for a change, a feature, or to make a suggestion.
 - For community assistance with development questions, there are our [forums](https://social.msdn.microsoft.com/Forums/newthread?category=windowsapps&forum=wpdevelop&prof=required), and [StackOverflow](https://stackoverflow.com/questions).
 - The [Windows developer support](https://developer.microsoft.com/windows/support) site explains other support options.
 - The [Visual Studio developer community](https://developercommunity.visualstudio.com) is available, and responsive. The former User Voice feature is now there on the **Suggest a feature** tab, if you want to lobby for a change, a feature, or to make a suggestion.
 - For developer issues, or suspected product bugs, there's [Microsoft Support](https://support.microsoft.com/contactus); a support engineer will look at the repro and see whether the issue is a Microsoft product bug, or something else. If it's a bug with a Microsoft product then the ticket will be free of charge.
 
 If you receive assistance via any support resource, and you believe that information would help us improve the docs, then please come back and let us know.
