### ISSUE TITLE
StreamWebSocket not accepted with VpnChannel.AssociateTransport

### ISSUE THREAD

**Issue by jcteng** [MicrosoftDocs/windows-uwp#1990]
As the document descibed ,VpnChannel.AssociateTransport(Object, Object) Method accept three types transport:
1. Windows.Networking.StreamSocket.  (Tested and goes well)
2. Windows.Networking.DatagramSocket.  (Tested and goes well)
3. Windows.Networking.StreamWebSocket ( Expection raised: Value does not fall within the expected range.)

Is there any mgaic ticks with StreamWebSocket?

```

  | 名称 | 值 | 类型
-- | -- | -- | --
◢ | $exception | {"Value does not fall within the expected range."} | System.ArgumentException
  | ▶ Data | {System.Collections.ListDictionaryInternal} | System.Collections.IDictionary {System.Collections.ListDictionaryInternal}
  | HResult | 0x80070057 | int
  | HelpLink | null | string
  | ◢ InnerException | null | System.Exception
  | ◢ Static members |   |  
  | ◢ Non-Public members |   |  
  | _COMPlusExceptionCode | 0xe0434352 | int
  | s_EDILock | {object} | object
  | Message | "Value does not fall within the expected range." | string
  | ParamName | null | string
  | Source | "Windows" | string
  | StackTrace | "   at Windows.Networking.Vpn.VpnChannel.AssociateTransport(Object mainOuterTunnelTransport, Object optionalOuterTunnelTransport)\r\n   at GlobalGateService.VpnTask.Windows.Networking.Vpn.IVpnPlugIn.Connect(VpnChannel channel) in C:\\code\\ggateUWP\\GlobalGate\\GlobalGateService\\VpnTask.cs:line 34" | string
  | ◢ Static members |   |  
  | ▶ Non-Public members |   |  
  | ◢ Non-Public members |   |  
  | IPForWatsonBuckets | 0x00007ff7d04be7cc | System.UIntPtr
  | IsTransient | false | bool
  | RemoteStackTrace | null | string
  | WatsonBuckets | null | object
  | _HResult | 0x80070057 | int
  | _className | null | string
  | ▶ _data | {System.Collections.ListDictionaryInternal} | System.Collections.IDictionary {System.Collections.ListDictionaryInternal}
  | _dynamicMethods | null | object
  | _exceptionMethod | null | System.Reflection.MethodBase
  | _exceptionMethodString | null | string
  | _helpURL | null | string
  | ▶ _innerException | null | System.Exception
  | _ipForWatsonBuckets | 0x00007ff7d04be7cc | System.UIntPtr
  | _message | "Value does not fall within the expected range." | string
  | _remoteStackIndex | 0x00000000 | int
  | _remoteStackTraceString | null | string
  | _source | "Windows" | string
  | ▶ _stackTrace | {sbyte[0x00000060]} | object {sbyte[]}
  | _stackTraceString | null | string
  | _watsonBuckets | null | object
  | _xcode | 0xe0434352 | int
  | _xptrs | 0x0000000000000000 | System.IntPtr
  | m_paramName | null | string


```

check code below 
```csharp
        void IVpnPlugIn.Connect(VpnChannel channel)
        {
            Debug.WriteLine("GlobalGateService connect++");

            /*
            var transport = new StreamSocket();
            channel.AssociateTransport(transport, null); <- Goes well with  channel.Start()
            transport.ConnectAsync(new Uri("some ip or domain"),"80").AsTask().Wait();
            */

            var transport = new StreamWebSocket();                      
            channel.AssociateTransport(transport, null); <- rise exception there
            transport.ConnectAsync(new Uri("ws://some where as websocket/race")).AsTask().Wait();
         ...
}
```

**Comment by stevewhims** [comment]
Hi, @jcteng, thanks for filing this issue.

This feels not so much like feedback specifically about the documentation, but rather like a question/feedback/support about the product itself. You can leave feedback about the documentation by visiting a topic and clicking **Send feedback about** \> **This page**. If instead you click **Send feedback about** \> **This product**, then you'll be taken to the [Feedback Hub app](https://support.microsoft.com/help/4021566/windows-10-send-feedback-to-microsoft-with-feedback-hub-app) (more info about that below).

Here are all of the developer support resources, for completeness.
- The [Feedback Hub app](https://support.microsoft.com/help/4021566/windows-10-send-feedback-to-microsoft-with-feedback-hub-app) is the right place to lobby for a change, a feature, or to make a suggestion.
- For community assistance with development questions, there are our [forums](https://social.msdn.microsoft.com/Forums/newthread?category=windowsapps&forum=wpdevelop&prof=required), and [StackOverflow](https://stackoverflow.com/questions).
- The [Windows developer support](https://developer.microsoft.com/windows/support) site explains other support options.
- The [Visual Studio developer community](https://developercommunity.visualstudio.com) is available, and responsive. The former User Voice feature is now there on the **Suggest a feature** tab, if you want to lobby for a change, a feature, or to make a suggestion.
- For developer issues, or suspected product bugs, there's [Microsoft Support](https://support.microsoft.com/contactus); a support engineer will look at the repro and see whether the issue is a Microsoft product bug, or something else. If it's a bug with a Microsoft product then the ticket will be free of charge.

If you receive assistance via any support resource, and you believe that information would help us improve the docs, then please come back and let us know.

Sorry that I couldn't be of more immediate help here.
-Steve
