### ISSUE TITLE
.net core 3 + uwp + compile with .net native => internal crash

### ISSUE THREAD

**Issue by jtorjo** [MicrosoftDocs/windows-uwp#1991]
I'm porting my app to UWP.
When I compile in release mode with .net native, i get an interanal compiler crash.
If I unselect .net native, it compiles ok.

Here's the diagnostic log of the compile:
http://phot-awe.com/test/internalerror.zip

**Comment by hkhmsft** [comment]
Thanks for reaching out with your feedback. In the meantime you'll find quicker support by consulting our developer support resources. For community assistance with development questions I recommend that you ask on our [forums](https://social.msdn.microsoft.com/Forums/newthread?category=windowsapps&forum=wpdevelop&prof=required) or [StackOverflow](https://stackoverflow.com/questions). Otherwise, please see [the developer support page](https://developer.microsoft.com/windows/support) for your support options. If you get assistance through these other resources and believe that information would help us improve the docs, please come back and let us know.
