### ISSUE TITLE
Cannot add targetted offers

### ISSUE THREAD

**Issue by carlbherbert** [MicrosoftDocs/windows-uwp#1993]
No button to add anything is shown.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 77ae80e6-33d9-38de-37a9-03338bd0612f
* Version Independent ID: 486a13a9-2bf7-79e2-44fa-54ac98d89766
* Content: [Use targeted offers to maximize engagement and conversions - Windows UWP applications](https://docs.microsoft.com/en-us/windows/uwp/publish/use-targeted-offers-to-maximize-engagement-and-conversions#feedback)
* Content Source: [windows-apps-src/publish/use-targeted-offers-to-maximize-engagement-and-conversions.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/publish/use-targeted-offers-to-maximize-engagement-and-conversions.md)
* Product: **uwp**
* Technology: **publish**
* GitHub Login: @hickeys
* Microsoft Alias: **hickeys**

**Comment by hickeys** [comment]
Thanks @carlbherbert for creating this issue. I'm happy to take a look, but I need some more information. Can you explain what steps you've taken so far and include a screenshot of the place where the button should be but is not?

Thanks,
Shawn

**Comment by carlbherbert** [comment]
![image](https://user-images.githubusercontent.com/53716161/68434778-8ce2fe80-0205-11ea-9e7b-b1362a8e87bf.png)
see attached.

**Comment by carlbherbert** [comment]
can someone show me a screenshot of how to create a targeted offer?

**Comment by aqibbanday** [comment]
i have the same issue.

**Comment by hickeys** [comment]
I apologize for the delay. Yes, that screenshot explains your issue very well. I will reach out to the engineering team and get some clarification.

**Comment by maxis2018** [comment]
Wondering if you can connect me to support as well ?
Run into similar issues, and cannot create any target campaign. Thanks!
<img width="1155" alt="Capture" src="https://user-images.githubusercontent.com/35563035/99748869-5201ef00-2b18-11eb-959c-16b2c58e842b.PNG">

**Comment by hickeys** [comment]
@maxis2018 

Resources for support:

The best way to get support is by asking the community on [Microsoft Q&A](https://docs.microsoft.com/answers/topics/uwp.html?sort=active&filter=all) or [StackOverflow](https://stackoverflow.com/questions) 

For completeness' sake, here is a list of developer resources:

- [Microsoft Q&A](https://docs.microsoft.com/answers/topics/uwp.html?sort=active&filter=all) offers relevant and timely answers to your technical problems from a community of experts and Microsoft engineers.
- For community assistance with development questions, there are our [forums](https://social.msdn.microsoft.com/Forums/newthread?category=windowsapps&forum=wpdevelop&prof=required), and [StackOverflow](https://stackoverflow.com/questions).
- The [Windows developer support](https://developer.microsoft.com/windows/support) site explains other support options.
- The [Visual Studio developer community](https://developercommunity.visualstudio.com) is available, and responsive. The former User Voice feature is now there on the **Suggest a feature** tab, if you want to lobby for a change, a feature, or to make a suggestion.
- For developer issues, or suspected product bugs, there's [Microsoft Support](https://support.microsoft.com/contactus); a support engineer will look at the repro and see whether the issue is a Microsoft product bug, or something else. If it's a bug with a Microsoft product then the ticket will be free of charge.

If you receive assistance via any support resource and you believe that information would help us improve the docs, then please let us know or consider submitting a pull request.

Thanks,
Shawn

**Comment by hickeys** [comment]
@carlbherbert 

I've reached out to the team and so far I've been unable to find an answer. My best recommendation would be to contact support at the resources listed above.
