### ISSUE TITLE
Cant change game from APP to GAME.... was working fine. (XBOX ONE)

### ISSUE THREAD

**Issue by madcowie** [MicrosoftDocs/windows-uwp#2001]
I really don't understand why it doesn't default to GAME. But at some point yesterday it stopped working! Now get the following Error Code 800A1391 

Does anyone know how to make it default to GAME?

Ive tried on both Xbox X and Xbox S and it does the same thing.

**Comment by madcowie** [comment]
I can now confirm that the new system xbox one update broke this.

**Comment by hkhmsft** [comment]
Thanks for reaching out with your feedback. I'll work on updating the documentation with this info, but in the meantime you'll find quicker support by consulting our developer support resources. For community assistance with development questions I recommend that you ask on our [forums](https://social.msdn.microsoft.com/Forums/newthread?category=windowsapps&forum=wpdevelop&prof=required) or [StackOverflow](https://stackoverflow.com/questions). Otherwise, please see [the developer support page](https://developer.microsoft.com/windows/support) for your support options. If you get assistance through these other resources and believe that information would help us improve the docs, please come back and let us know.
