### ISSUE TITLE
Property of "Animation Object" got bug when restart the Animation 

### ISSUE THREAD

**Issue by Strypper** [MicrosoftDocs/windows-uwp#2005]
`            backvisual = ElementCompositionPreview.GetElementVisual(FanIcon);

            backvisual.Size = new Vector2(100, 100);
            backvisual.CenterPoint = new Vector3(backvisual.Size / 2, 0);

            rotate = compositor.CreateScalarKeyFrameAnimation();
            rotate.InsertKeyFrame(1f, 360, compositor.CreateLinearEasingFunction());
            rotate.Duration = TimeSpan.FromMilliseconds(1000);
            rotate.IterationBehavior = AnimationIterationBehavior.Forever;`

Here is my rotate animation 
and here is how I trigger it with a toggle

`        private void ToggleFanSec1_Toggled(object sender, RoutedEventArgs e)
        {
            if (ToggleFanSec1.IsOn == true)
            {
                backvisual.StartAnimation(nameof(Visual.RotationAngleInDegrees), rotate);
            }
            else if(ToggleFanSec1.IsOn == false)
            {
                backvisual.StopAnimation(nameof(Visual.RotationAngleInDegrees));
            }
        }
`

[https://stackoverflow.com/questions/58356236/duration-of-scalarkeyframeanimation-got-shorter](url)

as you can see the animation duratation getting shorter when I restart it

**Comment by hkhmsft** [comment]
Thanks for reaching out with your feedback. I'll work on updating the documentation with this info, but in the meantime you'll find quicker support by consulting our developer support resources. For community assistance with development questions I recommend that you ask on our [forums](https://social.msdn.microsoft.com/Forums/newthread?category=windowsapps&forum=wpdevelop&prof=required) or [StackOverflow](https://stackoverflow.com/questions). Otherwise, please see [the developer support page](https://developer.microsoft.com/windows/support) for your support options. If you get assistance through these other resources and believe that information would help us improve the docs, please come back and let us know.
