### ISSUE TITLE
Menu Button Clickability when the window size is Small

### ISSUE THREAD

**Issue by sudarsanyes** [MicrosoftDocs/windows-uwp#2007]
While the document talks about various Navigation View Customization by extending the view to the TitleBar, it is not clear how to set the Back Button and the Menu Button as clickable when the window size is Small. 

If the documented snippets are followed, the Menu Button and the Back Button, when IsTitleBarAutoPaddingEnabled="False", does not receive any hit-tests, as they are processed as a part of the title bar. Can you explain how this can be overcome? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e69449df-a1ec-70dd-e563-0ad508733c47
* Version Independent ID: dc0e0acb-d92a-a039-5c16-f54a4b71d954
* Content: [Navigation view - Windows UWP applications](https://docs.microsoft.com/en-us/windows/uwp/design/controls-and-patterns/navigationview#feedback)
* Content Source: [windows-apps-src/design/controls-and-patterns/navigationview.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/design/controls-and-patterns/navigationview.md)
* Product: **uwp**
* Technology: **design**
* GitHub Login: @jwmsft
* Microsoft Alias: **jimwalk**

**Comment by jevansaks** [comment]
The doc does say this:

> If your app specifies the draggable region by calling the Window.SetTitleBar method

Did you do that?

**Comment by darovic** [comment]
I think that it would be useful to have an example showing the use of Window.SetTitleBar in the documentation of NavigationView, rather than having to piece it together. There is some ambiguity on what specifically should be set as the TitleBar when using this control (since we're not actually homebrewing an entire custom layout like we used to when implementing this pattern from scratch).

Delving into the control gallery app's source helps, but some people might not think of that or get confused as to what specifically they're looking for (new UWP developers, for example).
