### ISSUE TITLE
Enable the Windows 10 Hyper-V Default Switch to work with Cisco AnyConnect

### ISSUE THREAD

**Issue by marcus-lundgren** [MicrosoftDocs/windows-uwp#2009]
Copied the previous feedback report from here:
https://wpdev.uservoice.com/forums/110705-universal-windows-platform-closed/suggestions/32332030-enable-the-windows-10-hyper-v-default-switch-to-wo

It would be great if the default switch in Hyper-V could make use of VPN that the host is using. In my case it is Cisco AnyConnect. The VPN is used to reach internal infrastructure at my work.

**Comment by hkhmsft** [comment]
It looks like you have product feedback rather than documentation feedback. If you are looking for functionality that isn’t currently provided by the product, please use the [Windows developer feedback site](https://wpdev.uservoice.com/). We’d be happy to have this on record, where others can view it and upvote it.
