### ISSUE TITLE
allow access via System.IO API

### ISSUE THREAD

**Issue by jtorjo** [MicrosoftDocs/windows-uwp#2019]
The "great" StorageFile / StorageFolder are sooo bad and soo slow, it's an immense pain to use them.

Case in point : I have 797 files in a folder. With System.IO -> enumerating + getting length of each -> less than 1ms.
With StorageFolder enumeration -> **over 9 seconds**.

### It is > 9000 times slower 

Why can't we have System.IO function properly? They are waaaay faster, and everybody knows how to use them.
(I know I can use System.IO inside my bubble of KnownFolders, but anywhere else, I get Access Denied)

I know this is possible, because a Desktop Bridge app doesn't have *any* restrictions.

**Comment by hkhmsft** [comment]
It looks like you have product feedback rather than documentation feedback. If you are looking for functionality that isn’t currently provided by the product, please use the [Windows developer feedback site](https://wpdev.uservoice.com/). We’d be happy to have this on record, where others can view it and upvote it.
