### ISSUE TITLE
Allow audio from background task without requiring foreground activation

### ISSUE THREAD

**Issue by justcoding121** [MicrosoftDocs/windows-uwp#2023]
Originally [posted here](https://github.com/microsoft/Windows-universal-samples/issues/1067) in UWP samples repository, and later in [wpdev.uservoice](https://wpdev.uservoice.com/forums/110705-universal-windows-platform/suggestions/37012720-allow-audio-from-background-task-without-requiring) (which had many up-votes but now it disappeared after the transition to here).

I am working on a alarm clock app that will play a music playlist using MediaPlayer upon the display of alarm toast (by listening for ToastHistoryChangedType.Added event in background task). 

The problem is that audio is muted even when Background Media Playback capability is enabled. Background audio only works when app is launched first in foreground before switching to background. This is not an issue in android and iOS, since both of them let users play audio from background tasks with appropriate user permission. But this is a roadblock for development in UWP.

I tried it to find a workaround by using ToastAudio. Even though the toast audio documentation says that it will accept audio file located in ms-appdata:///, it does not work (it keeps playing default sound). ToastAudio only lets us to play custom audio located in ms-appx:///, but anything there has to be packaged with the application bundle.

I request to loosen up the security here. A genuine app won't do an audio spam from background, and if it does, users will certainly not install it in first place and its review will be terrible.

**Comment by hkhmsft** [comment]
Hi justcoding121, we really appreciate that you've consistently brought this feedback to many communication channels. Unfortunately, we only handle documentation specific feedback and I'd like your suggestions to go to the right place. Follow the below links to submit it via the Feedback Hub App.

 - The [Feedback Hub app](https://support.microsoft.com/help/4021566/windows-10-send-feedback-to-microsoft-with-feedback-hub-app) is the right place to lobby for a change, a feature, or to make a suggestion.
 - For community assistance with development questions, there are our [forums](https://social.msdn.microsoft.com/Forums/newthread?category=windowsapps&forum=wpdevelop&prof=required), and [StackOverflow](https://stackoverflow.com/questions).
 - The [Windows developer support](https://developer.microsoft.com/windows/support) site explains other support options.
 - The [Visual Studio developer community](https://developercommunity.visualstudio.com) is available, and responsive. The former User Voice feature is now there on the **Suggest a feature** tab, if you want to lobby for a change, a feature, or to make a suggestion.
 - For developer issues, or suspected product bugs, there's [Microsoft Support](https://support.microsoft.com/contactus); a support engineer will look at the repro and see whether the issue is a Microsoft product bug, or something else. If it's a bug with a Microsoft product then the ticket will be free of charge.
 
 If you receive assistance via any support resource, and you believe that information would help us improve the docs, then please come back and let us know.
