### ISSUE TITLE
Issue With Transaction Model Image

### ISSUE THREAD

**Issue by AbhiAbzs** [MicrosoftDocs/windows-uwp#2025]
There is an issue in rendering the transaction model Image when the dark mode is selected as sites theme.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a8132995-4d33-d547-f743-37cd3b3f15c4
* Version Independent ID: 19465bc3-648d-6576-ea62-5b23b50531d5
* Content: [Best practices for writing to files - Windows UWP applications](https://docs.microsoft.com/en-us/windows/uwp/files/best-practices-for-writing-to-files#feedback)
* Content Source: [windows-apps-src/files/best-practices-for-writing-to-files.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/files/best-practices-for-writing-to-files.md)
* Product: **uwp**
* Technology: **data-and-files**
* GitHub Login: @lastnameholiu
* Microsoft Alias: **alholiu**

**Comment by hkhmsft** [comment]
Thanks for reaching out with your feedback. I'll work on updating the documentation with this info, but in the meantime you'll find quicker support by consulting our developer support resources. For community assistance with development questions I recommend that you ask on our [forums](https://social.msdn.microsoft.com/Forums/newthread?category=windowsapps&forum=wpdevelop&prof=required) or [StackOverflow](https://stackoverflow.com/questions). Otherwise, please see [the developer support page](https://developer.microsoft.com/windows/support) for your support options. If you get assistance through these other resources and believe that information would help us improve the docs, please come back and let us know.
