### ISSUE TITLE
How do you specify the bundle version?

### ISSUE THREAD

**Issue by mhmd-azeez** [MicrosoftDocs/windows-uwp#2029]
Is there any msbuild argument I can send so that I can specify the version of the bundle? I am trying to use an Azure DevOps extension to manage the version of my builds.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cfd4f93a-ff30-ca5f-c45f-5e52aa553cfb
* Version Independent ID: 1e3ca639-193e-a43c-1585-5a407cad1433
* Content: [Set up automated builds for your UWP app - Windows UWP applications](https://docs.microsoft.com/en-us/windows/uwp/packaging/auto-build-package-uwp-apps#feedback)
* Content Source: [windows-apps-src/packaging/auto-build-package-uwp-apps.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/packaging/auto-build-package-uwp-apps.md)
* Product: **uwp**
* Technology: **deployment**
* GitHub Login: @mcleanbyron
* Microsoft Alias: **mcleans**

**Comment by mhmd-azeez** [comment]
A workaround is to replace the version in the appxmanifest using powershell:

```powershell
# https://stackoverflow.com/a/42699995
$xmlFileName = "Path\To\File\Package.appxmanifest"

[xml]$xmlDoc = Get-Content $xmlFileName
$xmlDoc.Package.Identity.Version = "2.0.0.0"
$xmlDoc.Save($xmlFileName)
```

**Comment by hkhmsft** [comment]
This feels not so much like feedback specifically about the documentation, but rather like a support request. Here are all of the developer support resources, for completeness.

 - The [Feedback Hub app](https://support.microsoft.com/help/4021566/windows-10-send-feedback-to-microsoft-with-feedback-hub-app) is the right place to lobby for a change, a feature, or to make a suggestion.
 - For community assistance with development questions, there are our [forums](https://social.msdn.microsoft.com/Forums/newthread?category=windowsapps&forum=wpdevelop&prof=required), and [StackOverflow](https://stackoverflow.com/questions).
 - The [Windows developer support](https://developer.microsoft.com/windows/support) site explains other support options.
 - The [Visual Studio developer community](https://developercommunity.visualstudio.com) is available, and responsive. The former User Voice feature is now there on the **Suggest a feature** tab, if you want to lobby for a change, a feature, or to make a suggestion.
 - For developer issues, or suspected product bugs, there's [Microsoft Support](https://support.microsoft.com/contactus); a support engineer will look at the repro and see whether the issue is a Microsoft product bug, or something else. If it's a bug with a Microsoft product then the ticket will be free of charge.
 
 If you receive assistance via any support resource, and you believe that information would help us improve the docs, then please come back and let us know.
