### ISSUE TITLE
Blue text command

### ISSUE THREAD

**Issue by sbeaudoin** [MicrosoftDocs/windows-uwp#2033]
I hoped to find how to create the kind of blue text command used on the Windows parameters page.  My command text is long and I thought this is the style we must use.  I have seen the HyperlinkButton, but the visual is not quite right as it is underlined when not hovered.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0b6e57c0-4d39-7608-e535-f3bf35d3f7a2
* Version Independent ID: 826f8e2b-b5be-3c62-6bb6-85abea1bfba4
* Content: [Buttons - Windows UWP applications](https://docs.microsoft.com/en-us/windows/uwp/design/controls-and-patterns/buttons)
* Content Source: [windows-apps-src/design/controls-and-patterns/buttons.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/design/controls-and-patterns/buttons.md)
* Product: **uwp**
* Technology: **design**
* GitHub Login: @jwmsft
* Microsoft Alias: **jimwalk**

**Comment by hkhmsft** [comment]
Hello,

Thanks for reaching out. Have you tried the following:

> The text does not appear underlined in the following cases:
> 
> You set a TextBlock as the value for the Content property, and set the Text property on the TextBlock.
> You re-template the HyperlinkButton and change the name of the ContentPresenter template part. If you need a button that appears as non-underlined text, consider using a standard Button control and applying the built-in TextBlockButtonStyle system resource to its Style property.

In the meantime you'll find quicker support by consulting our developer support resources. For community assistance with development questions I recommend that you ask on our [forums](https://social.msdn.microsoft.com/Forums/newthread?category=windowsapps&forum=wpdevelop&prof=required) or [StackOverflow](https://stackoverflow.com/questions). Otherwise, please see [the developer support page](https://developer.microsoft.com/windows/support) for your support options. If you get assistance through these other resources and believe that information would help us improve the docs, please come back and let us know.
