### ISSUE TITLE
No appxmanifest

### ISSUE THREAD

**Issue by BillHoag** [MicrosoftDocs/windows-uwp#2039]
Neither C++/WinRT nor C++/UX project templates generate a .appxmanifest file. Bug with the template?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e739c976-323f-bdf7-14a4-9b2d4872c62c
* Version Independent ID: c580c6b6-dc0d-296e-ffbd-0d866b34779f
* Content: [Create a Universal Windows Platform console app - Windows UWP applications](https://docs.microsoft.com/en-us/windows/uwp/launch-resume/console-uwp#feedback)
* Content Source: [windows-apps-src/launch-resume/console-uwp.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/launch-resume/console-uwp.md)
* Product: **uwp**
* Technology: **processes-and-threading**
* GitHub Login: @lastnameholiu
* Microsoft Alias: **alholiu**

**Comment by hkhmsft** [comment]
Thanks for reaching out and letting us know about this. This feels not so much like feedback specifically about the documentation, but rather like a support request regarding the product. Here are all of the developer support resources, for completeness.

 - The [Feedback Hub app](https://support.microsoft.com/help/4021566/windows-10-send-feedback-to-microsoft-with-feedback-hub-app) is the right place to lobby for a change, a feature, or to make a suggestion.
 - For community assistance with development questions, there are our [forums](https://social.msdn.microsoft.com/Forums/newthread?category=windowsapps&forum=wpdevelop&prof=required), and [StackOverflow](https://stackoverflow.com/questions).
 - The [Windows developer support](https://developer.microsoft.com/windows/support) site explains other support options.
 - The [Visual Studio developer community](https://developercommunity.visualstudio.com) is available, and responsive. The former User Voice feature is now there on the **Suggest a feature** tab, if you want to lobby for a change, a feature, or to make a suggestion.
 - For developer issues, or suspected product bugs, there's [Microsoft Support](https://support.microsoft.com/contactus); a support engineer will look at the repro and see whether the issue is a Microsoft product bug, or something else. If it's a bug with a Microsoft product then the ticket will be free of charge.
 
 If you receive assistance via any support resource, and you believe that information would help us improve the docs, then please come back and let us know.
