### ISSUE TITLE
Getting error trying to fill out the benficiary part.

### ISSUE THREAD

**Issue by MarkSmall-AV** [MicrosoftDocs/windows-uwp#2042]
the address cant be validated by Vertex - MIN_AGGREGATE_CONFIDENCE_EXCEEDED

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 98f4a20b-33aa-a616-6206-461d83fde6b8
* Version Independent ID: c28b8f31-922e-02b3-93c9-effa13395e1d
* Content: [Set up your payout account and tax forms - Windows UWP applications](https://docs.microsoft.com/en-us/windows/uwp/publish/setting-up-your-payout-account-and-tax-forms#feedback)
* Content Source: [windows-apps-src/publish/setting-up-your-payout-account-and-tax-forms.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/publish/setting-up-your-payout-account-and-tax-forms.md)
* Product: **uwp**
* Technology: **publish**
* GitHub Login: @hickeys
* Microsoft Alias: **hickeys**

**Comment by hkhmsft** [comment]
Thanks for taking the time to let us know about this. However, this feels not so much like feedback specifically about the documentation but rather like a support request. Here are all of the developer support resources, for completeness.

 - The [Feedback Hub app](https://support.microsoft.com/help/4021566/windows-10-send-feedback-to-microsoft-with-feedback-hub-app) is the right place to lobby for a change, a feature, or to make a suggestion.
 - For community assistance with development questions, there are our [forums](https://social.msdn.microsoft.com/Forums/newthread?category=windowsapps&forum=wpdevelop&prof=required), and [StackOverflow](https://stackoverflow.com/questions).
 - The [Windows developer support](https://developer.microsoft.com/windows/support) site explains other support options.
 - The [Visual Studio developer community](https://developercommunity.visualstudio.com) is available, and responsive. The former User Voice feature is now there on the **Suggest a feature** tab, if you want to lobby for a change, a feature, or to make a suggestion.
 - For developer issues, or suspected product bugs, there's [Microsoft Support](https://support.microsoft.com/contactus); a support engineer will look at the repro and see whether the issue is a Microsoft product bug, or something else. If it's a bug with a Microsoft product then the ticket will be free of charge.
 
 If you receive assistance via any support resource, and you believe that information would help us improve the docs, then please come back and let us know.

**Comment by Cassienka** [comment]
I'm having the exact same issues and NOTHING is working. I cannot seem to reach ANYONE about this particular issue. It's incredibly frustrating!

**Comment by MarkSmall-AV** [comment]
> 
> 
> I'm having the exact same issues and NOTHING is working. I cannot seem to reach ANYONE about this particular issue. It's incredibly frustrating!

I got mine fixed.  I had to use the full zip code not just the first 5 numbers

**Comment by Cassienka** [comment]
I tried that and it's still not working. I even checked my bank paperwork
and matched everything exactly. It's still reading an error
