### ISSUE TITLE
Not response any data

### ISSUE THREAD

**Issue by linhll** [MicrosoftDocs/windows-uwp#2044]
Dear development team,
I tried to use this API but it didn't response any analytic data.
This is my request:
GET /v1.0/my/analytics/failurehits?applicationId=9P9DNW6KMT9B&amp; startDate=10/20/2019&amp; endDate=10/28/2019 HTTP/1.1
Host: manage.devcenter.microsoft.com
: 
Authorization: Bearer &lt;token&gt;
User-Agent: PostmanRuntime/7.19.0
Accept: */*
Cache-Control: no-cache
Host: manage.devcenter.microsoft.com
Accept-Encoding: gzip, deflate
Connection: keep-alive
cache-control: no-cache

and this is the response that i received:

{
  "Value": [],
  "@nextLink": null,
  "TotalCount": 0
}

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 78fd2953-4afe-5382-b336-129749b00fd3
* Version Independent ID: d6443723-7deb-0faa-3fff-e687ae1e1f52
* Content: [Get error reporting data for your app - Windows UWP applications](https://docs.microsoft.com/en-us/windows/uwp/monetize/get-error-reporting-data#feedback)
* Content Source: [windows-apps-src/monetize/get-error-reporting-data.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/monetize/get-error-reporting-data.md)
* Product: **uwp**
* Technology: **publish**
* GitHub Login: @hickeys
* Microsoft Alias: **hickeys**

**Comment by hkhmsft** [comment]
Thanks for reaching out with your feedback. In the meantime, you'll find quicker support by consulting our developer support resources. For community assistance with development questions I recommend that you ask on our [forums](https://social.msdn.microsoft.com/Forums/newthread?category=windowsapps&forum=wpdevelop&prof=required) or [StackOverflow](https://stackoverflow.com/questions). Otherwise, please see [the developer support page](https://developer.microsoft.com/windows/support) for your support options. If you get assistance through these other resources and believe that information would help us improve the docs, please come back and let us know.
