### ISSUE TITLE
Onecoreuap errors

### ISSUE THREAD

**Issue by Changed-Daily** [MicrosoftDocs/windows-uwp#2045]
Hi, I am developing a UWP application for Bluetooth. I am using the Microsoft.Toolkit.Uwp datagrid and other controls from that toolkit. During debug I get loads of the following error:

onecoreuap\windows\wgi\winrt\display\displaycommon.cpp(411)\Windows.Graphics.dll!00007FFF68BE04B0: (caller: 00007FFF68BE027B) ReturnHr(54) tid(2230) 80070490 Element not found.

It is not preventing the program from running correctly but it makes finding other debug information very difficult. I haven't worked out a way to filter these messages out either.

Fixing the underlying issue would be preferable if anyone has any ideas.

Thanks

**Comment by hkhmsft** [comment]
Thanks for taking the time to let us know about this. However, this feels not so much like feedback specifically about the documentation but rather like a support request. Here are all of the developer support resources, for completeness.

 - The [Feedback Hub app](https://support.microsoft.com/help/4021566/windows-10-send-feedback-to-microsoft-with-feedback-hub-app) is the right place to lobby for a change, a feature, or to make a suggestion.
 - For community assistance with development questions, there are our [forums](https://social.msdn.microsoft.com/Forums/newthread?category=windowsapps&forum=wpdevelop&prof=required), and [StackOverflow](https://stackoverflow.com/questions).
 - The [Windows developer support](https://developer.microsoft.com/windows/support) site explains other support options.
 - The [Visual Studio developer community](https://developercommunity.visualstudio.com) is available, and responsive. The former User Voice feature is now there on the **Suggest a feature** tab, if you want to lobby for a change, a feature, or to make a suggestion.
 - For developer issues, or suspected product bugs, there's [Microsoft Support](https://support.microsoft.com/contactus); a support engineer will look at the repro and see whether the issue is a Microsoft product bug, or something else. If it's a bug with a Microsoft product then the ticket will be free of charge.
 
 If you receive assistance via any support resource, and you believe that information would help us improve the docs, then please come back and let us know.
