### ISSUE TITLE
Attaching to email using Outlook does not work

### ISSUE THREAD

**Issue by db-007** [MicrosoftDocs/windows-uwp#205]
Attaching email to a new email generated by Outlook is not working in desktop Windows 10 environment.

This is a reported issue all over the net and a known issue for at least 2 years already:

[https://stackoverflow.com/questions/46534908/uwp-app-sending-email-with-emailmanager-showcomposenewemailasync-wont-add-attach](https://stackoverflow.com/questions/46534908/uwp-app-sending-email-with-emailmanager-showcomposenewemailasync-wont-add-attach)

[https://stackoverflow.com/questions/33053358/sending-email-attachments-via-uwp-emailmanager-not-working](https://stackoverflow.com/questions/33053358/sending-email-attachments-via-uwp-emailmanager-not-working)

**STEPS TO REPRODUCE**
1. Set Outlook (in my case Outlook 2016) as default email app in Windows 10 Settings
2. Close Outlook so it is not running
2. Create a simple UWP app to send email using EmailManager.ShowComposeNewEmailAsync
3. New email dialog opens shortly, recipient, subject and email body is created but attachment is not added

**EXPECTED OUTCOME**
App should offer user to choose which app to use to send email with attachment or simply use default email app including Outlook as set in Windows 10 Settings and send the email including the attachments.

**ACTUAL OUTCOME**
Attachments are ignored

**ENVIRONMENT**
Windows 10 Desktop
Visual Studio 2015
Xamarin UWP Application
Outlook 2016 (but any Outlook should work since many many customers are using it)

**Comment by normesta** [comment]
This is a known issue. I've updated the doc with a note to that effect and I've removed the part of that code sample that showcases attachments to avoid the suggestion that it should work with all mail apps. The technical limitation still exists, but at least the content won't be misleading. Thx

**Comment by gsingh11** [comment]
@normesta Is that issue resolved now? Also can you send the Link for the mentioned issue / Documentation.

**Comment by RuddyOne** [comment]
@gsingh11  [Here is the documentation](https://docs.microsoft.com/en-us/windows/uwp/contacts-and-calendar/sending-email). Nothing appears to be happening with this at all.

**Comment by lorant-csonka-ICE** [comment]
@normesta Will this issue be ever solved? Is there any other ways to add attachments like this?

**Comment by mijacobs** [comment]
Norm added this note: Attachments that you add to an email by using the EmailAttachment class will appear only in the Mail app. If users have any other mail program configured as their default mail program, the compose window will appear without the attachment. This is a known issue.

The documentation has been updated, but there's an issue with an underlying platform feature, which we consider a product feedback or support request.  Here's a list of developer support resources: 

 - The [Feedback Hub app](https://support.microsoft.com/help/4021566/windows-10-send-feedback-to-microsoft-with-feedback-hub-app) is the right place to lobby for a change, a feature, or to make a suggestion.
 - For community assistance with development questions, there are our [forums](https://social.msdn.microsoft.com/Forums/newthread?category=windowsapps&forum=wpdevelop&prof=required), and [StackOverflow](https://stackoverflow.com/questions).
 - The [Windows developer support](https://developer.microsoft.com/windows/support) site explains other support options.
 - For developer issues, or suspected product bugs, there's [Microsoft Support](https://support.microsoft.com/contactus); a support engineer will look at the repro and see whether the issue is a Microsoft product bug, or something else. If it's a bug with a Microsoft product then the ticket will be free of charge.
> 
> If you receive assistance via any support resource, and you believe that information would help us improve the docs, then please come back and let us know.
