### ISSUE TITLE
Seek for help for problems about bluetooth ble! 

### ISSUE THREAD

**Issue by jiangxincode** [MicrosoftDocs/windows-uwp#2066]
When i use the interface about bluetooth ble, there are some problems:
https://docs.microsoft.com/en-us/uwp/api/windows.devices.bluetooth.advertisement

1. When I invoke publisher.start, i must wait many seconds before windows really sends the bluetooth broadcast
2. Everytime i invoke publisher.start, the mac address will be changed.
I konw this repo is only for docs of winrt-api, but i can not find a effect method to contact resposive team, please help me to transfer or give me a link.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: efe3c92a-ec28-648e-44b4-10ce62d6c107
* Version Independent ID: eac958bb-b09d-a0db-b08b-50c844269184
* Content: [Bluetooth Advertisements - Windows UWP applications](https://docs.microsoft.com/en-us/windows/uwp/devices-sensors/ble-beacon#feedback)
* Content Source: [windows-apps-src/devices-sensors/ble-beacon.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/devices-sensors/ble-beacon.md)
* Product: **uwp**
* Technology: **peripherals-sensors-and-power**
* GitHub Login: @Karl-Bridge-Microsoft
* Microsoft Alias: **kbridge**

**Comment by Karl-Bridge-Microsoft** [comment]
Thanks for the feedback! However, this appears to be a product issue and not a doc bug (at this time), so please consider posting the issue at https://github.com/microsoft/microsoft-ui-xaml/issues/new/choose for the product team to track publicly.

**Comment by jiangxincode** [comment]
Maybe this problem is not belonged to a UI team? it is an UWP interface about bluetooth

**Comment by Karl-Bridge-Microsoft** [comment]
Sorry @jiangxincode, you're right. Probably not the best resource.

Here's a selection of developer support resources that might be able to help with your issue.

The [Feedback Hub app](https://support.microsoft.com/help/4021566/windows-10-send-feedback-to-microsoft-with-feedback-hub-app) is the right place to lobby for a change, a feature, or to make a suggestion.
For community assistance with development questions, there are our [forums](https://social.msdn.microsoft.com/Forums/newthread?category=windowsapps&forum=wpdevelop&prof=required), and [StackOverflow](https://stackoverflow.com/questions).
The [Windows developer support](https://developer.microsoft.com/windows/support) site explains other support options.
The [Visual Studio developer community](https://developercommunity.visualstudio.com/) is available, and responsive. The former User Voice feature is now there on the **Suggest a feature** tab, if you want to lobby for a change, a feature, or to make a suggestion.
For developer issues, or suspected product bugs, there's [Microsoft Support](https://support.microsoft.com/contactus); a support engineer will look at the repro and see whether the issue is a Microsoft product bug, or something else. If it's a bug with a Microsoft product then the ticket will be free of charge.
If you receive assistance via any support resource, and you believe that information would help us improve the docs, then please come back and let us know.
