### ISSUE TITLE
certificate url not available

### ISSUE THREAD

**Issue by fwrq41251** [MicrosoftDocs/windows-uwp#2078]
https://go.microsoft.com/fwlink/p/?linkid=246509&cid=CertificateId
this url is not available since 2019/11/11

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 58237b3e-0baa-92c4-caa7-023be22ccf40
* Version Independent ID: ef2f5a25-f75d-f62d-b52f-c18c72e8540b
* Content: [Use receipts to verify product purchases - Windows UWP applications](https://docs.microsoft.com/en-us/windows/uwp/monetize/use-receipts-to-verify-product-purchases)
* Content Source: [windows-apps-src/monetize/use-receipts-to-verify-product-purchases.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/monetize/use-receipts-to-verify-product-purchases.md)
* Product: **uwp**
* Technology: **publish**
* GitHub Login: @hickeys
* Microsoft Alias: **hickeys**

**Comment by hickeys** [comment]
the code in this example is designed to be used with a user-supplied receipt that you load from disk. The certificate ID is extracted from the receipt and appended to that link. The link you've made, with "cid=CertificateId" should never work, as you need an actual certificate ID instead of the string "CertificateId
