### ISSUE TITLE
Remove folder issue from video library

### ISSUE THREAD

**Issue by singhwong** [MicrosoftDocs/windows-uwp#2084]
`bool result = await myPictures.RequestRemoveFolderAsync(folder);`
The following exceptions occasionally occur when deleting a folder from a video library using the 
code above.
[System.Exception:The remote procedure call failed.(Exception from HRESULT: 0x800706BE)
at Windows.Storage.StorageLibrary.RequestRemoveFolderAsync(StorageFolder folder)].

Because this exception does not occur every time, I don't know how to solve it.

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: 7f59ce84-4e55-82be-a007-fed934e3f41b
* Version Independent ID: 6d5d61e5-d4bf-4e56-c0c5-ca6fb19e6e6d
* Content: [音乐、图片和视频库中的文件和文件夹 - Windows UWP applications](https://docs.microsoft.com/zh-cn/windows/uwp/files/quickstart-managing-folders-in-the-music-pictures-and-videos-libraries)
* Content Source: [windows-apps-src/files/quickstart-managing-folders-in-the-music-pictures-and-videos-libraries.md](https://github.com/MicrosoftDocs/windows-uwp.zh-cn/blob/live/windows-apps-src/files/quickstart-managing-folders-in-the-music-pictures-and-videos-libraries.md)
* Product: **uwp**
* Technology: **data-and-files**
* GitHub Login: @lastnameholiu
* Microsoft Alias: **alholiu**

**Comment by hkhmsft** [comment]
Hi @singhwong, thanks for reaching out with your feedback. Is there anything you'd like to see on our documentation that could potentially help solve your roadblock? 

If else, I'm thinking there might be answers to your exception issue on our developer resources. For community assistance with development questions I recommend that you ask on our [forums](https://social.msdn.microsoft.com/Forums/newthread?category=windowsapps&forum=wpdevelop&prof=required) or [StackOverflow](https://stackoverflow.com/questions). Otherwise, please see [the developer support page](https://developer.microsoft.com/windows/support) for your support options. If you get assistance through these other resources and believe that information would help us improve the docs, please come back and let us know.

**Comment by singhwong** [comment]
The code below is my solution, so far this is feasible.Every time the folder deletion operation is performed, the folders in the video library are obtained again.
`var removeLibrary = await StorageLibrary.GetLibraryAsync(KnownLibraryId.Videos);`
 `var myLibraryFolders = removeLibrary.Folders;`
`foreach (var folder in myLibraryFolders)`
   ` {`
       `if (folder.Path == remove_library.FolderPath)`
         ` {`
             `result_bool = await removeLibrary.RequestRemoveFolderAsync(folder);`
         `  }`
    `}`
