### ISSUE TITLE
Error when trying to Debug.

### ISSUE THREAD

**Issue by DSBloom** [MicrosoftDocs/windows-uwp#2093]
I am following these instructions to try and package up my .NET Framework (not core) WPF application. I am getting the following error when I attempt to debug:

`MSB3779	The processor architecture of the project being built "Any CPU" is not supported by the referenced SDK "Microsoft.VCLibs, Version=14.0". Please consider changing the targeted processor architecture of your project (in Visual Studio this can be done through the Configuration Manager) to one of the architectures supported by the SDK: "x86, x64, ARM, ARM64"`

**Comment by bartlannoeye** [comment]
@nadcraker the error says exactly what to do: select one of "x86, x64, ARM, ARM64" as "Any CPU" is not a valid option.

**Comment by hkhmsft** [comment]
Thanks for reaching out with your feedback. Is there anything you'd like to see on our documentation that could potentially help solve your roadblock? If else, I'm thinking there might be answers to your specific issue on our developer resources. For community assistance with development questions I recommend that you ask on our [forums](https://social.msdn.microsoft.com/Forums/newthread?category=windowsapps&forum=wpdevelop&prof=required) or [StackOverflow](https://stackoverflow.com/questions). Otherwise, please see [the developer support page](https://developer.microsoft.com/windows/support) for your support options. If you get assistance through these other resources and believe that information would help us improve the docs, please come back and let us know.
