### ISSUE TITLE
ms-appdata image source not working

### ISSUE THREAD

**Issue by dpaulino** [MicrosoftDocs/windows-uwp#2101]
I am building a toast notification with a hero image whose source is ms-appdata:///temp/image.png. However when I use the following code below, I'm not seeing a hero image in the toast notification.

```
            var imagePath = "ms-appdata:///temp/image.png";
            var toastContent = GetToastContent(imagePath);
            var toast = new ToastNotification(toastContent.GetXml());
            ToastNotificationManager.CreateToastNotifier().Show(toast);
```

Here is the `GetToastContent` method:
```
        public ToastContent GetToastContent(string image)
        {
            // In a real app, these would be initialized with actual data
            string title = "Andrew sent you a picture";
            string content = "Check this out, Happy Canyon in Utah!";

            // Construct the visuals of the toast
            ToastVisual visual = new ToastVisual()
            {
                BindingGeneric = new ToastBindingGeneric()
                {
                    Children =
                    {
                        new AdaptiveText()
                        {
                            Text = title
                        },
                        new AdaptiveText()
                        {
                            Text = content
                        }
                    },
                    HeroImage = new ToastGenericHeroImage()
                    {
                        Source = image
                    }
                }
            };

            ToastContent toastContent = new ToastContent()
            {
                Visual = visual,
            };

            return toastContent;
        }
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 59a52407-2fba-405c-267d-076b4306d0ab
* Version Independent ID: 946bec03-cbc7-a7e6-8174-01f5195c290e
* Content: [Send a local toast notification - UWP apps](https://docs.microsoft.com/en-us/windows/uwp/design/shell/tiles-and-notifications/send-local-toast#feedback)
* Content Source: [windows-apps-src/design/shell/tiles-and-notifications/send-local-toast.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/design/shell/tiles-and-notifications/send-local-toast.md)
* Product: **uwp**
* Technology: **design**
* GitHub Login: @hickeys
* Microsoft Alias: **hickeys**

**Comment by dpaulino** [comment]
I managed to find a workaround by providing the full system path to the file. I would still like to understand why the `ms-appdata` uri scheme wasn't working since the documentation says that this should work.

**Comment by dpaulino** [comment]
@hickeys any advice?

**Comment by hickeys** [comment]
As far as I can tell, you seem to be doing things correctly, so it should work. I'd double check the path to make sure the ms-appdata path is correct, but I'm sure you've already done that. Unfortunately this forum is for documentation bugs only, not tech support so I can't give you much help. 

If you find the reason this is not working for you, and you believe it should be documented, please let me know.

Thanks,
Shawn

**Comment by dpaulino** [comment]
@hickeys I do believe this should be documented

**Comment by hickeys** [comment]
I'm happy that you found a workaround. 

There are many reasons why loading an image from a resource file might fail - the image path could be wrong, the resource file could be corrupt or malformed, you may have loaded an incorrect image file that does not contain the requested image, etc. Loading images from appdata does work as documented on the page, so the issue goes back to what I said earlier about tech support. 

I also notice that you are doing many things not documented on this page, such as using the ToastGenericHeroImage, setting the image's Source property to a string instead of a Uri, manually setting the source property, etc. All of these introduce additional complications outside of the scope of the documentation in question, any of which could cause problems loading an image not related to the resource file. 

Ultimately, as I said, if there is a specific reason that loading images is not working as documented, I'd be happy to update this or any other article. As this stands, however, it's unclear what, if any, changes are called for. I'm open to working with you to update the documentation, but this is not the place for going through your code to discover why you're unable to load images from a resource file.
