### ISSUE TITLE
Certification failure

### ISSUE THREAD

**Issue by brabebhin** [MicrosoftDocs/windows-uwp#2103]
Updating to the latest nuget packages cause a store certification failure on all architectures. Are we supposed to not use sqlite anymore?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6c591596-d202-244c-6fbf-31c288fe9b57
* Version Independent ID: 1473907c-0cba-8917-2fd8-d3ca1fb73cae
* Content: [Use a SQLite database in a UWP app - UWP apps](https://docs.microsoft.com/en-us/windows/uwp/data-access/sqlite-databases#feedback)
* Content Source: [windows-apps-src/data-access/sqlite-databases.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/data-access/sqlite-databases.md)
* Product: **uwp**
* Technology: **data-and-files**
* GitHub Login: @lastnameholiu
* Microsoft Alias: **alholiu**

**Comment by hkhmsft** [comment]
Thanks for taking the time to let us know about this and we sincerely apologize for the delayed response. Due to the sheer volume of feedback in our repo, we are currently prioritizing new Issues. If you believe your feedback is still actionable, let us know either directly in this thread or by filing a new Issue and we’ll work to incorporate the suggestions into the documentation. Though the Issue will be marked as Closed, I will monitor any replies that come afterwards so feel free to treat this like an open Issue. Many thanks!
