### ISSUE TITLE
The "Record a video" example is very sparse

### ISSUE THREAD

**Issue by ffMathy** [MicrosoftDocs/windows-uwp#2105]
There are no examples online and plenty of StackOverflow questions that are unanswered about the topic of how to record a video.

See: https://github.com/MicrosoftDocs/windows-uwp/issues/612
And: https://github.com/MicrosoftDocs/winrt-api/issues/856

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9b8d11e4-f9c6-383a-38d4-6cf7633edb7c
* Version Independent ID: 7015ed77-ae66-cc97-301c-b0c6ebfb2bd3
* Content: [Screen capture - UWP apps](https://docs.microsoft.com/en-us/windows/uwp/audio-video-camera/screen-capture#feedback)
* Content Source: [windows-apps-src/audio-video-camera/screen-capture.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/audio-video-camera/screen-capture.md)
* Product: **uwp**
* Technology: **audio-video-and-camera**
* GitHub Login: @drewbatgit
* Microsoft Alias: **drewbat**

**Comment by drewbatgit** [comment]
Hello, thanks for your feedback on the documentation. It turns out that using AppRecordingManager to capture the screen to a video file was a temporary workaround to the preferred method of using WIndows.Media.Transcoding APIs to encode frames captured with the ScreenCapture class. To get you unblocked, you can check out this sample of the recommended technique here:

https://github.com/robmikh/SimpleRecorder

I've created a work item internally to track adding a write up of this technique to the existing screen capture documentation, replacing the insufficient blurb on AppRecordingManager you called out. I don't have an ETA for when this new content will be published, but it's in our queue. Thanks again for helping to improve the docs.

**Comment by ffMathy** [comment]
What encoding profiles are supported by this method? Is there a way to determine that?
