### ISSUE TITLE
XML Scheme for Toast does not contain information about HeroImage feature

### ISSUE THREAD

**Issue by MustrumRidcully0** [MicrosoftDocs/windows-uwp#2107]
The documentation for the Notifications Library (https://docs.microsoft.com/en-us/windows/uwp/design/shell/tiles-and-notifications/toast-schema#toastgenericheroimage) mentions the HeroImage feature, and als links to this XML Schema for people that rather use the XML Schema rather than the library. But the HeroImage is not included in this documentation. 
It is unclear whether this means it's impossible to use or just undocumented  how to use it correctly. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b41740ef-87bc-0eb4-214a-2f847b9ad948
* Version Independent ID: 8b90529d-f872-a6a3-1089-c317dee5c005
* Content: [Toast content XML schema - UWP apps](https://docs.microsoft.com/en-us/windows/uwp/design/shell/tiles-and-notifications/toast-xml-schema#feedback)
* Content Source: [windows-apps-src/design/shell/tiles-and-notifications/toast-xml-schema.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/design/shell/tiles-and-notifications/toast-xml-schema.md)
* Product: **uwp**
* Technology: **design**
* GitHub Login: @hickeys
* Microsoft Alias: **hickeys**

**Comment by hickeys** [comment]
It sounds like you're looking for the src attribute in the image element as documented [here](https://docs.microsoft.com/en-us/windows/uwp/design/shell/tiles-and-notifications/toast-xml-schema)

If I am misunderstanding your question please let me know.

**Comment by MustrumRidcully0** [comment]
After further research I found out that if you're using the XML interface for Toasts, HeroImage is a specific value for the placement tag. But this documentation only mentions "inline" and "appLogoOverride". 
Documentation for that can be found here: https://docs.microsoft.com/en-us/windows/uwp/design/shell/tiles-and-notifications/adaptive-interactive-toasts
However, it seems I can't get that to work with this Toast library: https://github.com/mohabouje/WinToast
Guess I'll have to experiment with using the DesktopNotificationManagerCompat referenced in the adaptive interactive toasts documentation.

**Comment by rarao90** [comment]
[‎4/‎9/‎2020 10:29 AM]  
HI ,

I just want know how the snooze will work, where the snooze data gets stored . If user click on 15 minutes Snooze button then where that 15 minutes will get stored ?. I need to execute the Toast by comparing the left over deployment end time and with the current time and then i need to delete the Snooze options if the deployment end time  is less than 2 hours then i should display with only 2 snooze option 15min and 30 min.

**Comment by hickeys** [comment]
Thanks for reaching out with your feedback. GitHub issues in this repo are for documentation bugs only, and unfortunately this seems more like a support request than a documentation bug. 

The best way to get support is by asking the community on [Microsoft Q&A](https://docs.microsoft.com/answers/topics/uwp.html?sort=active&filter=all) or [StackOverflow](https://stackoverflow.com/questions) 

For completeness' sake, here is a list of developer resources:

- [Microsoft Q&A](https://docs.microsoft.com/answers/topics/uwp.html?sort=active&filter=all) offers relevant and timely answers to your technical problems from a community of experts and Microsoft engineers.
- For community assistance with development questions, there are our [forums](https://social.msdn.microsoft.com/Forums/newthread?category=windowsapps&forum=wpdevelop&prof=required), and [StackOverflow](https://stackoverflow.com/questions).
- The [Windows developer support](https://developer.microsoft.com/windows/support) site explains other support options.
- The [Visual Studio developer community](https://developercommunity.visualstudio.com) is available, and responsive. The former User Voice feature is now there on the **Suggest a feature** tab, if you want to lobby for a change, a feature, or to make a suggestion.
- For developer issues, or suspected product bugs, there's [Microsoft Support](https://support.microsoft.com/contactus); a support engineer will look at the repro and see whether the issue is a Microsoft product bug, or something else. If it's a bug with a Microsoft product then the ticket will be free of charge.

If you receive assistance via any support resource and you believe that information would help us improve the docs, then please let us know or consider submitting a pull request.

Thanks,
Shawn
