### ISSUE TITLE
does fully cover how to debug connectivity issues from Visual Studio to the Xbox

### ISSUE THREAD

**Issue by rebroad** [MicrosoftDocs/windows-uwp#2108]
I am getting:-

DEP6957 : Failed to connect to device '192.168.1.202' using Universal Authentication. Please verify the correct remote authentication mode is specified in the project debug settings. 0x801C0003: Exception from HRESULT: 0x801C0003

when trying to deploy code to the Xbox - there is very little information online for troubleshooting this. The device responds to pings. Have tried via a cabled connection and a wireless connection.

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d9dc8af9-74fd-31ae-9215-0bef3d6a3ae5
* Version Independent ID: 35200a57-132f-1f11-8243-26145743cb7a
* Content: [Frequently asked questions - UWP apps](https://docs.microsoft.com/en-us/windows/uwp/xbox-apps/frequently-asked-questions?redirectedfrom=MSDN#feedback)
* Content Source: [windows-apps-src/xbox-apps/frequently-asked-questions.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/xbox-apps/frequently-asked-questions.md)
* Product: **uwp**
* Technology: **games**
* GitHub Login: @M-Stahl
* Microsoft Alias: **kevinasg**

**Comment by mattwojo** [comment]
Thank you for taking the time to let us know about this issue. Apologies for the delayed response. Due to the volume of feedback in our content, we are currently prioritizing new issues. It also sounds like this issue may be better handled by https://support.xbox.com/. 

If you believe your feedback still requires an update to the documentation, please let us know either directly in this thread, by filing a new issue, or by filing a [Pull Request ](https://github.com/MicrosoftDocs/windows-uwp/pulls) with your recommended updates.

Though the Issue will be marked as closed, we will still receive replies and are able to reopen the issue if necessary. 

Thanks again for taking the time to contribute.
