### ISSUE TITLE
Crucial Step Missing

### ISSUE THREAD

**Issue by menonGitHub** [MicrosoftDocs/windows-uwp#2109]
The following step needs to occur to be able to use the Python Interpreter
- Install the Python extension for VS Code from the Visual Studio Marketplace

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e6092806-2037-a886-8895-12012f37ef7e
* Version Independent ID: 8b5aff2a-668b-f79d-ba29-e5348a09a0b5
* Content: [Get started with using Python on Windows for beginners](https://docs.microsoft.com/en-us/windows/python/beginners#feedback)
* Content Source: [hub/python/beginners.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/hub/python/beginners.md)
* Product: **dev-environment**
* Technology: **windows-python**
* GitHub Login: @mattwojo
* Microsoft Alias: **mattwoj**

**Comment by zentril** [comment]
I had trouble with the Python app install from Microsoft Store. There is a comment in the reviews on the store for Python 3.8 which helped me. I had the same error trying to install 3.7. I had to: "open 'Manage App Execution Aliases' through Start and disable all the Python entries before installing." 

App Execution Aliases came back to bother me again when I tried to run python from the shell. It started up the Windows Store page. I moved the folder for these aliases further down in my PATH environment variable. That made it so that an installed instance of python came first before those redirects. 

Finally after learning more about what App. Ex. Aliases are...I cleaned up the settings on the Manage App Execution Aliases page in Control Panel. It allows me to default which version of Python is my default when I type "python" from a command prompt.

I found this helpful:
https://docs.microsoft.com/en-us/windows/python/faqs#why-does-running-pythonexe-open-the-microsoft-store

**Comment by mattwojo** [comment]
Thanks for catching this @menonGitHub. You're totally right -- need that Python Extension installed on VS Code in order to select a Python interpreter, just added the step in this PR: https://github.com/MicrosoftDocs/windows-uwp-pr/pull/494.   Thank you!

**Comment by mattwojo** [comment]
Going to close this as the update should resolve the issue.
