### ISSUE TITLE
Examples for preview with x:Bind 

### ISSUE THREAD

**Issue by MythreyaK** [MicrosoftDocs/windows-uwp#2113]
I can't seem to get designer previews when I use x:Bind. I converted the Bookstore example to use only x:Bind, and I don't get designer previews. Some examples on how to do so would be really helpful. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 64d8500f-a77e-00eb-c179-b72209f25949
* Version Independent ID: f4b970f5-af50-d626-68de-2c8b39140687
* Content: [Sample data on the design surface, and for prototyping - UWP apps](https://docs.microsoft.com/en-in/windows/uwp/data-binding/displaying-data-in-the-designer)
* Content Source: [windows-apps-src/data-binding/displaying-data-in-the-designer.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/data-binding/displaying-data-in-the-designer.md)
* Product: **uwp**
* Technology: **data-and-files**
* GitHub Login: @lastnameholiu
* Microsoft Alias: **alholiu**

**Comment by hkhmsft** [comment]
Hi, we appreciate you submitting through our feedback channel. However, this feels not so much like feedback specifically about the documentation, but rather like a support request. Here are all of the developer support resources, for completeness.

- [Microsoft Q&A](https://docs.microsoft.com/answers/topics/uwp.html?sort=active&filter=all) is the right place to lobby for a change, a feature, or to make a suggestion.
- For community assistance with development questions, there are our [forums](https://social.msdn.microsoft.com/Forums/newthread?category=windowsapps&forum=wpdevelop&prof=required), and [StackOverflow](https://stackoverflow.com/questions).
- The [Windows developer support](https://developer.microsoft.com/windows/support) site explains other support options.
- The [Visual Studio developer community](https://developercommunity.visualstudio.com) is available, and responsive. The former User Voice feature is now there on the **Suggest a feature** tab, if you want to lobby for a change, a feature, or to make a suggestion.
- For developer issues, or suspected product bugs, there's [Microsoft Support](https://support.microsoft.com/contactus); a support engineer will look at the repro and see whether the issue is a Microsoft product bug, or something else. If it's a bug with a Microsoft product then the ticket will be free of charge.

If you receive assistance via any support resource, and you believe that information would help us improve the docs, we'd appreciate if you came back and let us know.

**Comment by MythreyaK** [comment]
Please allow me to rephrase. The docs does not contain examples that show designer previews with `x:bind`.
