### ISSUE TITLE
Distribution methods for enterprises

### ISSUE THREAD

**Issue by fox-on-the-run** [MicrosoftDocs/windows-uwp#2125]
[Enter feedback here]
Would be great to add Intune for MSIX deployment. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 870a8fd2-b4c6-8fb6-91a5-9f758645c167
* Version Independent ID: cf118c1e-5bb9-9486-5502-8d29d11df173
* Content: [Distribute LOB apps to enterprises - UWP apps](https://docs.microsoft.com/en-us/windows/uwp/publish/distribute-lob-apps-to-enterprises?context=/windows/msix/render)
* Content Source: [windows-apps-src/publish/distribute-lob-apps-to-enterprises.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/publish/distribute-lob-apps-to-enterprises.md)
* Product: **uwp**
* Technology: **publish**
* GitHub Login: @hickeys
* Microsoft Alias: **hickeys**

**Comment by HUBBER12** [comment]
For some reason the Private Store is no longer visible from the Windows Store in Windows 10.  My Enterprise users that have not logged out can still see the private store.. but if one logs out of the "Work or School Account" from the windows 10 store app, then logging back in the Private Store for Business is no longer visible. (as of 3/21/2020).  Same goes for new users trying to log in for the first time.  Did something happen to the private store, is it still an option for distribution?

**Comment by hickeys** [comment]
It looks like your feedback concerns the product itself, rather than the documentation for the product. Unfortunately, GitHub issues in this repo are only used for documentation issues. 

The best way to leave product feedback is through the [Feedback Hub app](https://support.microsoft.com/help/4021566/windows-10-send-feedback-to-microsoft-with-feedback-hub-app). If you return to the documentation page related to this issue and scroll to the bottom, there is a button to **leave feedback about this product**

For completeness' sake, here is a list of developer resources:

- The [Feedback Hub app](https://support.microsoft.com/help/4021566/windows-10-send-feedback-to-microsoft-with-feedback-hub-app) is the right place to suggest or lobby for a change or feature.
- Try our [forums](https://social.msdn.microsoft.com/Forums/newthread?category=windowsapps&forum=wpdevelop&prof=required) and [StackOverflow](https://stackoverflow.com/questions) for community assistance with development questions.
- The [Windows developer support](https://developer.microsoft.com/windows/support) site explains other support options.
- The [Visual Studio developer community](https://developercommunity.visualstudio.com) is helpful and responsive. You can also suggest or lobby for a change or feature by clicking the **report a problem** or **suggest a feature** buttons.
- For developer issues or suspected product bugs, visit [Microsoft Support](https://support.microsoft.com/contactus). A support engineer will determine whether the issue is a Microsoft product bug. If it is, the ticket will be free of charge.

If you receive assistance via any support resource and you believe that information would help us improve the docs, then please let us know or consider submitting a pull request.

Thanks,
Shawn
