### ISSUE TITLE
Problem with MONETISE - Provide Tax Info

### ISSUE THREAD

**Issue by CARTER-BNW** [MicrosoftDocs/windows-uwp#2136]
My Tax Profile is Valid on the Microsoft Partner Center website.
i have accepted all agreements and provided a payout options.

Waited weeks for the MONETISE - "Provide Tax Info" to have a tick. Can you please help!

From Australia 
Streaming on Mixer

**Comment by CARTER-BNW** [comment]
![tax1](https://user-images.githubusercontent.com/58977770/70990525-a6853900-2115-11ea-908f-f9a9911a3077.PNG)

**Comment by CARTER-BNW** [comment]
![tax2](https://user-images.githubusercontent.com/58977770/70990601-cfa5c980-2115-11ea-9e2a-753c2ee36adb.PNG)

**Comment by CARTER-BNW** [comment]
![tax3](https://user-images.githubusercontent.com/58977770/70990710-04198580-2116-11ea-864a-3e7627915b2c.PNG)

**Comment by hkhmsft** [comment]
Thanks for reaching out with your feedback. Is there anything you'd like to see on our documentation that could potentially help solve your roadblock? If else, I'm thinking there might be answers to your specific issue on our developer resources instead. For community assistance with development questions I recommend that you ask on our [forums](https://social.msdn.microsoft.com/Forums/newthread?category=windowsapps&forum=wpdevelop&prof=required) or [StackOverflow](https://stackoverflow.com/questions). Otherwise, please see [the developer support page](https://developer.microsoft.com/windows/support) for your support options. If you get assistance through these other resources and believe that information would help us improve the docs, please come back and let us know.
