### ISSUE TITLE
In AddData() method, we may want to use ExecuteNonQuery() instead of ExecuteReader()

### ISSUE THREAD

**Issue by saf-itpro** [MicrosoftDocs/windows-uwp#2139]
In the section [Insert data into the SQLite database](https://docs.microsoft.com/en-us/windows/uwp/data-access/sqlite-databases#insert-data-into-the-sqlite-database) why we are returning DataReader? The goal is to just insert data not retrieve it - GetData() does that job.
Returning DataReader is more resource intensive and probably should be avoided if not needed.

Instead, should we use: insertCommand.ExecuteNonQuery() there?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6c591596-d202-244c-6fbf-31c288fe9b57
* Version Independent ID: 1473907c-0cba-8917-2fd8-d3ca1fb73cae
* Content: [Use a SQLite database in a UWP app - UWP apps](https://docs.microsoft.com/en-us/windows/uwp/data-access/sqlite-databases#feedback)
* Content Source: [windows-apps-src/data-access/sqlite-databases.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/data-access/sqlite-databases.md)
* Product: **uwp**
* Technology: **data-and-files**
* GitHub Login: @lastnameholiu
* Microsoft Alias: **alholiu**

**Comment by hkhmsft** [comment]
Thanks for taking the time to let us know about this and we sincerely apologize for the delayed response. Due to the sheer volume of feedback in our repo, we are currently prioritizing new Issues. If you believe your feedback is still actionable, let us know either directly in this thread or by filing a new Issue and we’ll work to incorporate the suggestions into the documentation. Though the Issue will be marked as Closed, we will monitor any replies that come afterwards so feel free to treat this like an open Issue. Many thanks!
