### ISSUE TITLE
no Data panel in Blend for VS2019

### ISSUE THREAD

**Issue by OZ1** [MicrosoftDocs/windows-uwp#2141]
Data panel is absent in Blend for Visual Studio 2019 so "Create Sample Data from Class" feature mentioned in this article can not be used

---
#### Сведения о документе

⚠ *Не вносите правки в этот раздел. Это необходимо для связывания страницы сайта docs.microsoft.com с вопросом на GitHub.*

* ID: 64d8500f-a77e-00eb-c179-b72209f25949
* Version Independent ID: f4b970f5-af50-d626-68de-2c8b39140687
* Content: [Демонстрационные данные в рабочей области конструирования и демонстрационные данные для создания прототипов - UWP apps](https://docs.microsoft.com/ru-ru/windows/uwp/data-binding/displaying-data-in-the-designer)
* Content Source: [windows-apps-src/data-binding/displaying-data-in-the-designer.md](https://github.com/MicrosoftDocs/windows-uwp.ru-ru/blob/live/windows-apps-src/data-binding/displaying-data-in-the-designer.md)
* Product: **uwp**
* Technology: **data-and-files**
* GitHub Login: @lastnameholiu
* Microsoft Alias: **alholiu**

**Comment by hkhmsft** [comment]
Thanks for bringing this to our attention, @OZ1 . I've taken your note and relayed to our internal folks. once we've confirmed the appropriate action, I'll circle back here. Thanks once again.

**Comment by GrantMeStrength** [comment]
We are changing the way we track issues filed from our documentation pages: please see this [blog post](https://techcommunity.microsoft.com/t5/microsoft-learn-blog/announcing-a-new-way-to-give-feedback-on-microsoft-learn/ba-p/4027635) for more details. Right now, this issue is being closed but if you feel it is still valid and has not been addressed, please re-open it with any more available information. Please note that if you question is more general and not related to documentation, [Microsoft Q&A](https://learn.microsoft.com/en-us/answers/questions/) is a great way to get questions answered.
