### ISSUE TITLE
Would be great to talk about credential manager and gpg signing for git

### ISSUE THREAD

**Issue by neo** [MicrosoftDocs/windows-uwp#2149]
I think it would be very helpful if it also mentions how to setup credential manager in WSL (I had to install git-bash) as well as using gpg to sign commits with the passphrase cached/remembered

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c6995595-66c4-f26a-b307-89a068b4b5ba
* Version Independent ID: 69400ed1-5d98-4d6e-47a3-5c409564e77d
* Content: [Set up NodeJS on WSL 2](https://docs.microsoft.com/en-us/windows/nodejs/setup-on-wsl2#feedback)
* Content Source: [hub/nodejs/setup-on-wsl2.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/hub/nodejs/setup-on-wsl2.md)
* Product: **dev-environment**
* Technology: **windows-nodejs**
* GitHub Login: @mattwojo
* Microsoft Alias: **mattwoj**

**Comment by mattwojo** [comment]
Thanks @neo  -- investigating.

**Comment by neo** [comment]
I can show you or work with you in terms of how to set up with the credential manager, but I could find a good enough way to set up gpg signing...

**Comment by mattwojo** [comment]
Hi @neo -- I've added instructions on setting up Git credential manager to the FAQs in WSL. Please take a look and provide feedback if you are willing: https://github.com/MicrosoftDocs/WSL/pull/556/files

I'm going to close this issue and move the conversation over to my Pull Request in the WSL docs repo. 

Thanks again for your contribution!!! ~Matt

**Comment by neo** [comment]
hey Matt! thank you for making it!
but I think the PR only solves half the problem? The other (harder) half is signing with GPG in vscode, I have seen discussions about it, but I couldn't find a good way to not having to enter the passphrase every time or even better stored in credential manager.
also I'm not sure if it's a good idea to include what you added there in the FAQ here too? maybe as a link? because this is where I (and I supposed most web dev/nodejs dev) land on when they get started with WSL.
thanks! 🎉

**Comment by mattwojo** [comment]
Thank you and good points! Reopening this and will add some additional content to the FAQ and link from the NodeJS page(s).

**Comment by mattwojo** [comment]
Hey @neo - clearly I got distracted from making this update. I've moved the git setup instructions our of the NodeJS guide and into the WSL docs (as it applies across a variety of languages/workflows): https://docs.microsoft.com/windows/wsl/tutorials/wsl-git

In regard to the GPG signing, I may need some help better understanding the issue. Does associating yoru email with your GPG key resolve the problem? > https://help.github.com/en/github/authenticating-to-github/associating-an-email-with-your-gpg-key

I'm closing the issue here, please reopen in the WSL docs if the email associate doesn't resolve the issue: https://github.com/MicrosoftDocs/WSL/issues

Thanks again and sorry for my delay!
Matt
