### ISSUE TITLE
Problem publishing toast notification Application

### ISSUE THREAD

**Issue by dross005** [MicrosoftDocs/windows-uwp#2152]
After reviewing and double checking the guide your team provided I'm having trouble with the published version of the toast notification.  When working in Visual Studio the notifications appear fine and do exactly as expected but when publishing the file and running the code (setup.exe) no notifications appear.  I have set up some logs output to verify if any exceptions are thrown or methods aren't getting called but everything comes back good and the information that should appear in notification is ready to be pushed.  I did see in your troubleshooting section that AUMID may not be matching but I am still very new to coding and am not clear on where I would configure this setting in the published files (the files are either dlls or the app manifest).  In visual studio i know where to set the parameter but that value is different when i check the AUMID for the publish code.  Since I'm new to this a breakdown would be very appreciated.  Thank you.

**Comment by hickeys** [comment]
Thanks for reaching out with your feedback. GitHub issues in this repo are for documentation bugs only, and unfortunately this seems more like a support request than a documentation bug. 

The best way to get support is by asking the community on [Microsoft Q&A](https://docs.microsoft.com/answers/topics/uwp.html?sort=active&filter=all) or [StackOverflow](https://stackoverflow.com/questions) 

For completeness' sake, here is a list of developer resources:

- [Microsoft Q&A](https://docs.microsoft.com/answers/topics/uwp.html?sort=active&filter=all) offers relevant and timely answers to your technical problems from a community of experts and Microsoft engineers.
- For community assistance with development questions, there are our [forums](https://social.msdn.microsoft.com/Forums/newthread?category=windowsapps&forum=wpdevelop&prof=required), and [StackOverflow](https://stackoverflow.com/questions).
- The [Windows developer support](https://developer.microsoft.com/windows/support) site explains other support options.
- The [Visual Studio developer community](https://developercommunity.visualstudio.com) is available, and responsive. The former User Voice feature is now there on the **Suggest a feature** tab, if you want to lobby for a change, a feature, or to make a suggestion.
- For developer issues, or suspected product bugs, there's [Microsoft Support](https://support.microsoft.com/contactus); a support engineer will look at the repro and see whether the issue is a Microsoft product bug, or something else. If it's a bug with a Microsoft product then the ticket will be free of charge.

If you receive assistance via any support resource and you believe that information would help us improve the docs, then please let us know or consider submitting a pull request.

Thanks,
Shawn
