### ISSUE TITLE
Cannot connect to retail kit using Dev mode companion with latest OS upgrade

### ISSUE THREAD

**Issue by bindusadu** [MicrosoftDocs/windows-uwp#2153]
With latest OS update, not able to connect to retail kit or dev kit remotely using dev mode companion. It says Unavailable and turn on although kit is turned on and available. 

OS version: | 10.0.18363.7194 (19h1_release_xbox_dev_1910.190929-1945)
-- | --
OS edition: | October 2019

Console Type: | Xbox One
-- | --

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b87f278f-9f2f-12f4-8a8c-a35e822029b3
* Version Independent ID: cc581b2b-5923-98a6-b3c4-02837f181a0b
* Content: [Xbox Dev Mode Companion - UWP apps](https://docs.microsoft.com/en-us/windows/uwp/xbox-apps/xbox-dev-mode-companion)
* Content Source: [windows-apps-src/xbox-apps/xbox-dev-mode-companion.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/xbox-apps/xbox-dev-mode-companion.md)
* Product: **uwp**
* Technology: **games**
* GitHub Login: @M-Stahl
* Microsoft Alias: **kevinasg**

**Comment by drewbatgit** [comment]
Hello, GitHub issues in this repository are for feedback specifically about the documentation. It seems like your issue is a developer support request. Here are all of the developer support resources:

- The [Microsoft Q&A](https://docs.microsoft.com/en-us/answers/products/) site is the home for technical questions and answers at Microsoft.
- The [Feedback Hub app](https://support.microsoft.com/help/4021566/windows-10-send-feedback-to-microsoft-with-feedback-hub-app) is the right place to lobby for a change, a feature, or to make a suggestion.
- For community assistance with development questions, there are our [forums](https://social.msdn.microsoft.com/Forums/newthread?category=windowsapps&forum=wpdevelop&prof=required), and [StackOverflow](https://stackoverflow.com/questions).
- The [Windows developer support](https://developer.microsoft.com/windows/support) site explains other support options.
- The [Visual Studio developer community](https://developercommunity.visualstudio.com) is available, and responsive. The former User Voice feature is now there on the **Suggest a feature** tab, if you want to lobby for a change, a feature, or to make a suggestion.
- For developer issues, or suspected product bugs, there's [Microsoft Support](https://support.microsoft.com/contactus); a support engineer will look at the repro and see whether the issue is a Microsoft product bug, or something else. If it's a bug with a Microsoft product then the ticket will be free of charge.

If you receive assistance via any support resource, and you believe that information would help us improve the documentation, then please come back and let us know.
