### ISSUE TITLE
Applications not in the Microsoft Store

### ISSUE THREAD

**Issue by mdell-seradex** [MicrosoftDocs/windows-uwp#2168]
We have applications that are not in the Microsoft store.  Can we still get things like the Health Report and access to crash reports and dump files?

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7361de4b-d8ca-fcac-b7e2-5b4d014e3daf
* Version Independent ID: 06dd75a0-a983-7059-01e6-f7e27f2e7ef5
* Content: [Analyze app performance - UWP applications](https://docs.microsoft.com/en-ca/windows/uwp/publish/analytics)
* Content Source: [windows-apps-src/publish/analytics.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/publish/analytics.md)
* Product: **uwp**
* Technology: **publish**
* GitHub Login: @hickeys
* Microsoft Alias: **hickeys**

**Comment by hickeys** [comment]
No, you cannot. If you're interested in seeing how other developers have approached this, your best shot is to ask the community on [Microsoft Q&A](https://docs.microsoft.com/answers/topics/uwp.html?sort=active&filter=all) or [StackOverflow](https://stackoverflow.com/questions) 

For completeness' sake, here is a list of developer resources:

- [Microsoft Q&A](https://docs.microsoft.com/answers/topics/uwp.html?sort=active&filter=all) offers relevant and timely answers to your technical problems from a community of experts and Microsoft engineers.
- For community assistance with development questions, there are our [forums](https://social.msdn.microsoft.com/Forums/newthread?category=windowsapps&forum=wpdevelop&prof=required), and [StackOverflow](https://stackoverflow.com/questions).
- The [Windows developer support](https://developer.microsoft.com/windows/support) site explains other support options.
- The [Visual Studio developer community](https://developercommunity.visualstudio.com) is available, and responsive. The former User Voice feature is now there on the **Suggest a feature** tab, if you want to lobby for a change, a feature, or to make a suggestion.
- For developer issues, or suspected product bugs, there's [Microsoft Support](https://support.microsoft.com/contactus); a support engineer will look at the repro and see whether the issue is a Microsoft product bug, or something else. If it's a bug with a Microsoft product then the ticket will be free of charge.

If you receive assistance via any support resource and you believe that information would help us improve the docs, then please let us know or consider submitting a pull request.

Thanks,
Shawn
