### ISSUE TITLE
UWP Game project set up page - New Project dialog screenshot is out of date

### ISSUE THREAD

**Issue by colin-home** [MicrosoftDocs/windows-uwp#2179]
The screenshot after Step 4 in the "Use DirectX template to create a project" procedure doesn't reflect what Visual Studio's New Project dialog looks like in either VS 2017 or VS 2019. 

It might also be worth mentioning after "The template used for this tutorial is titled DirectX 11 App (Universal Windows)" that the template is only available if you've installed the "Universal Windows Platform development" workload. Or, at least mention the requirement somewhere in the prerequisites in the previous Simple UWP Game article.

(I'm relaying customer comments from elsewhere. Thanks!)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0aa02bcc-0841-3108-8f7e-47abbe6850a1
* Version Independent ID: 91c62675-45a3-5cc6-7d4a-55fbf511ad8e
* Content: [Set up the game project - UWP applications](https://docs.microsoft.com/en-us/windows/uwp/gaming/tutorial--setting-up-the-games-infrastructure#feedback)
* Content Source: [windows-apps-src/gaming/tutorial--setting-up-the-games-infrastructure.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/gaming/tutorial--setting-up-the-games-infrastructure.md)
* Product: **uwp**
* Technology: **games**
* GitHub Login: @stevewhims
* Microsoft Alias: **stwhi**

**Comment by stevewhims** [comment]
Hi, @corob-msft, thanks for the heads up. I'll take a look, and update this comment when I have more info.

Thanks again!
Steve

**Comment by stevewhims** [comment]
Hi, Colin! So, I have a work item lined up to go through this whole series of topics and update the code to use C++/WinRT instead of C++/CX. I have the sample app already ported, I'm just awaiting code review before taking the next step. So I'll do something about the images while I'm doing that work.

Feel free to ping me internally if you like. For here, I'll go ahead and close the GitHub issue since I'm tracking it already with my internal work item.

Thanks again!
Steve
