### ISSUE TITLE
Support for disabling screen capture

### ISSUE THREAD

**Issue by ChaosWorrier** [MicrosoftDocs/windows-uwp#2181]
Is there any intention of empowering  apps to disable screenshots (by UI or other apps) by setting an attribute, similar to the way the UWP ApplicationView.IsScreenCaptureDisabled works (e.g. via the GraphicsCaptureSession.IsSupported attribute or the ScreenCapture namespace)?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9b8d11e4-f9c6-383a-38d4-6cf7633edb7c
* Version Independent ID: 7015ed77-ae66-cc97-301c-b0c6ebfb2bd3
* Content: [Screen capture - UWP applications](https://docs.microsoft.com/en-us/windows/uwp/audio-video-camera/screen-capture#feedback)
* Content Source: [windows-apps-src/audio-video-camera/screen-capture.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/audio-video-camera/screen-capture.md)
* Product: **uwp**
* Technology: **audio-video-and-camera**
* GitHub Login: @drewbatgit
* Microsoft Alias: **drewbat**

**Comment by drewbatgit** [comment]
It looks like you have product feedback rather than documentation feedback. If you are looking for functionality that isn’t currently provided by the product, the [Feedback Hub app](https://support.microsoft.com/help/4021566/windows-10-send-feedback-to-microsoft-with-feedback-hub-app) is the right place to lobby for a change, a feature, or to make a suggestion.
