### ISSUE TITLE
Incorrect URI

### ISSUE THREAD

**Issue by Xotikos** [MicrosoftDocs/windows-uwp#2189]
The stated URI to pass to the client is "https://onestore.microsoft.com/b2b/keys/create/collections".  This results in a NULL id from the new API or a 401 error from the old API.  The actual working URI is "https://onestore.microsoft.com"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5efda84a-67f8-73d2-e9dd-ce9e5b26f17f
* Version Independent ID: 150aa4b2-23b4-e314-a5fc-6efd1185a8a1
* Content: [Manage product entitlements from a service - UWP applications](https://docs.microsoft.com/en-us/windows/uwp/monetize/view-and-grant-products-from-a-service#feedback)
* Content Source: [windows-apps-src/monetize/view-and-grant-products-from-a-service.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/monetize/view-and-grant-products-from-a-service.md)
* Product: **uwp**
* Technology: **publish**
* GitHub Login: @hickeys
* Microsoft Alias: **hickeys**

**Comment by hickeys** [comment]
@Xotikos 

This UIR is used in a number of places in the document. Can you share more about your workflow, where you're encountering the errors, and what behavior you're seeing with the working URI?

**Comment by GrantMeStrength** [comment]
Shawn - I updated what I believe is the reference here - https://github.com/MicrosoftDocs/windows-uwp-pr/pull/1263

in the paragraph

If you want to call a method in the Microsoft Store collection API to query for products owned by a user or report a consumable product as fulfilled, you must also create a token with the https://onestore.microsoft.com/b2b/keys/create/collections audience URI. In a later step, you will pass this token to a client method in the Windows SDK to request a Microsoft Store ID key that you can use with the Microsoft Store collection API.

Hopefully this is the right one, and can be confirmed as such.

**Comment by jeffc111** [comment]
@GrantMeStrength indeed...  I'm pretty sure that you edited the wrong thing, and this, coupled with the overall poor quality of this documentation has caused me a ton of confusion.  I can confirm that passing the original URI (https://onestore.microsoft.com/b2b/keys/create/collections) absolutely gives a response that appears appropriate.  I still don't know if it's right, but it works with the client GetCustomerCollectionsIdAsync as it should to give what appears to be a valid response from THAT api.  Passing the resulting store id to an API like https://collections.mp.microsoft.com/v6.0/collections/query then at least results in a 200, even if I can't for the life of me get it to return a list of items that isn't empty.  But I'm pretty sure that's something else entirely.

**Comment by GrantMeStrength** [comment]
Sorry Jeffc111 if I made it worse. Hopefully, Shawn can step in and correct it.

**Comment by GrantMeStrength** [comment]
We are changing the way we track issues filed from our documentation pages: please see this [blog post](https://techcommunity.microsoft.com/t5/microsoft-learn-blog/announcing-a-new-way-to-give-feedback-on-microsoft-learn/ba-p/4027635) for more details. The Microsoft Store documentation has been updated several times since your issue was reported, and there's a good chance your problem has been addressed. Right now, this issue is being closed but if you feel it is still valid and has not been addressed, please re-open it with any more available information. Please note that if your question is more general and not related to documentation, [Microsoft Q&A](https://learn.microsoft.com/en-us/answers/questions/) is a great way to get questions answered.
