### ISSUE TITLE
Sample needs updating to use C++/WinRT

### ISSUE THREAD

**Issue by trojanfoe** [MicrosoftDocs/windows-uwp#2193]
This sample uses C++/CX, however in other https://docs.microsoft.com/en-us/windows/uwp/gaming it is recommended that C++/WinRT be used.  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f375db84-d770-3a7c-2a9c-54795b36288e
* Version Independent ID: a3ab6f17-0b50-c44a-f7f7-50f5c949b56d
* Content: [Create a DirectX Universal Windows Platform (UWP) game - UWP applications](https://docs.microsoft.com/en-us/windows/uwp/gaming/tutorial--create-your-first-uwp-directx-game#feedback)
* Content Source: [windows-apps-src/gaming/tutorial--create-your-first-uwp-directx-game.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/gaming/tutorial--create-your-first-uwp-directx-game.md)
* Product: **uwp**
* Technology: **games**
* GitHub Login: @stevewhims
* Microsoft Alias: **stwhi**

**Comment by stevewhims** [comment]
Hi, @trojanfoe, thanks for filing this issue. I've added a work item to my backlog to port this sample from C++/CX to C++/WinRT.  As a game, the code is relatively "simple", as the topics imply. But relative to typical sample apps, I'd say this one is particularly large and involved, so I can't say exactly when I'll get around to porting it.

Since I have a work item to track this task internally, I'll go ahead and close this GitHub issue. You can still reply to a closed issue; and you can always re-open one if you feel it's been closed in error.

Thanks!
Steve

**Comment by stevewhims** [comment]
**UPDATE**: The ported code is currently in code review and is having corrections made to it.

**Comment by stevewhims** [comment]
UPDATE: I've now updated all the snippets in all the topics that show code from the Simple3DGameDX sample app. I've replaced the former C++/CX snippets with C++/WinRT and the sample app itself is also ported. Details in the topics.

Thanks!
Steve
