### ISSUE TITLE
What do I do after adding the Microsoft.Toolkit.Win32.UI.SDK package?

### ISSUE THREAD

**Issue by AzAgarampur** [MicrosoftDocs/windows-uwp#2212]
I have added that package along with my C++/WinRT package. But I still cannot run my program without getting the error "...are supported for apps targeting Windows version 10.0.18226.0 and later." The only way it works for me is to add a maxversiontested in my program's manifest file manually.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8f2fc66b-ffa8-5128-8658-a8ea1d064e47
* Version Independent ID: ce50830e-9947-ad68-709c-1e3fd049bb71
* Content: [Using the UWP XAML hosting API in a C++ Win32 app](https://docs.microsoft.com/en-us/windows/apps/desktop/modernize/using-the-xaml-hosting-api#feedback)
* Content Source: [hub/apps/desktop/modernize/using-the-xaml-hosting-api.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/hub/apps/desktop/modernize/using-the-xaml-hosting-api.md)
* Product: **uwp**
* Technology: **apps**
* GitHub Login: @mcleanbyron
* Microsoft Alias: **mcleans**

**Comment by mcleanbyron** [comment]
Thanks for providing your feedback. I can confirm the behavior you're seeing, and it appears that this is not intentional in the v6.0 version of the NuGet package mentioned in the article. I added the instructions about adding the <maxversiontested> element back to the article for now, and am following up with the product team to confirm whether this is a bug or the new by design behavior.
