### ISSUE TITLE
differentiation between an acquisition and an install

### ISSUE THREAD

**Issue by myusrn** [MicrosoftDocs/windows-uwp#2213]
its not clear from the details of this page, at least to me, how a customer would go about doing an "acquisition" of my store app's license without that involving an install.  I might suggest explaining how that can happen given i'm having difficulty how to interpret what to interpret from these two values being different in my store app's analytics page.  Also my usage numbers show up as 0 but i'm wondering if that is because of the nature of my app where the store app is used to launch a full trust notification area win32 app process and then essentially get out of the way.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b3b543c3-6901-508a-40b3-2fc86ea13b86
* Version Independent ID: 498c432a-80e3-2ce0-8686-218ef3cc3953
* Content: [Acquisitions report - UWP applications](https://docs.microsoft.com/en-us/windows/uwp/publish/acquisitions-report#feedback)
* Content Source: [windows-apps-src/publish/acquisitions-report.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/publish/acquisitions-report.md)
* Product: **uwp**
* Technology: **publish**
* GitHub Login: @hickeys
* Microsoft Alias: **hickeys**

**Comment by GrantMeStrength** [comment]
We are changing the way we track issues filed from our documentation pages: please see this [blog post](https://techcommunity.microsoft.com/t5/microsoft-learn-blog/announcing-a-new-way-to-give-feedback-on-microsoft-learn/ba-p/4027635) for more details. The Microsoft Store documentation has been updated several times since your issue was reported, and there's a good chance your problem has been addressed. Right now, this issue is being closed but if you feel it is still valid and has not been addressed, please re-open it with any more available information. Please note that if you question is more general and not related to documentation, [Microsoft Q&A](https://learn.microsoft.com/en-us/answers/questions/) is a great way to get questions answered.
