### ISSUE TITLE
Catastrophic Failure of Bluetooth LE Explorer

### ISSUE THREAD

**Issue by GUOPengfe1** [MicrosoftDocs/windows-uwp#2226]
[在此处输入反馈]
when I tried to connect my laptop(win10, BLE supported) to a BLE peripheral by Bluetooth LE Explorer, it shows a catastrophic failure(Excep_FromHResult 0x8000FFF).

﻿What can I do to solve it? Thanks!

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: d7618e33-68a1-8a4d-0247-e4f3bbb1ebbb
* Version Independent ID: 48c2c28d-9b52-4d83-343f-df35f4219b0d
* Content: [蓝牙 GATT 服务器 - UWP applications](https://docs.microsoft.com/zh-cn/windows/uwp/devices-sensors/gatt-server#feedback)
* Content Source: [windows-apps-src/devices-sensors/gatt-server.md](https://github.com/MicrosoftDocs/windows-uwp.zh-cn/blob/live/windows-apps-src/devices-sensors/gatt-server.md)
* Product: **uwp**
* Technology: **peripherals-sensors-and-power**
* GitHub Login: @Karl-Bridge-Microsoft
* Microsoft Alias: **kbridge**

**Comment by Karl-Bridge-Microsoft** [comment]
Hi @CQUGuoPengfei - This feedback is not specifically about the documentation, but rather a support request. Please contact the following support channel.

- For developer issues, or suspected product bugs, there's [Microsoft Support](https://support.microsoft.com/contactus); a support engineer will look at the repro and see whether the issue is a Microsoft product bug, or something else. If it's a bug with a Microsoft product then the ticket will be free of charge.

Here are all of the developer support resources, for completeness.

- The [Feedback Hub app](https://support.microsoft.com/help/4021566/windows-10-send-feedback-to-microsoft-with-feedback-hub-app) is the right place to lobby for a change, a feature, or to make a suggestion.
- For community assistance with development questions, there are our [forums](https://social.msdn.microsoft.com/Forums/newthread?category=windowsapps&forum=wpdevelop&prof=required), and [StackOverflow](https://stackoverflow.com/questions).
- The [Windows developer support](https://developer.microsoft.com/windows/support) site explains other support options.
- The [Visual Studio developer community](https://developercommunity.visualstudio.com) is available, and responsive. The former User Voice feature is now there on the **Suggest a feature** tab, if you want to lobby for a change, a feature, or to make a suggestion.

If you receive assistance via any support resource, and you believe that information would help us improve the docs, then please come back and let us know.
