### ISSUE TITLE
No keyboard input support

### ISSUE THREAD

**Issue by to87al** [MicrosoftDocs/windows-uwp#2227]
this control has no keyboard support so it takes an eternity to input time, therefore the use in desktop applications is not optimized to say the least.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0d61d8e1-c0c9-e605-8ddd-714ffa400204
* Version Independent ID: 6d753cc1-93a9-adf4-00bf-1b967df8b7c8
* Content: [Time picker - UWP applications](https://docs.microsoft.com/en-us/windows/uwp/design/controls-and-patterns/time-picker#feedback)
* Content Source: [windows-apps-src/design/controls-and-patterns/time-picker.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/design/controls-and-patterns/time-picker.md)
* Product: **uwp**
* Technology: **design**
* GitHub Login: @jwmsft
* Microsoft Alias: **jimwalk**

**Comment by jwmsft** [comment]
Hi, it looks like your feedback is about the control, rather than about the documentation. To ensure that the correct team gets your feedback about the control, please consider leaving product feeback. (You got here by clicking _Send feedback about > This page_. If you instead click _Send feedback about > This product_, then you'll be taken to the right channel to leave product questions/feedback. Or [click here](https://github.com/microsoft/microsoft-ui-xaml/issues/new/choose).)

For TimePicker, I've found this existing issue that addresses your feedback. Feel free to join the discussion there. https://github.com/microsoft/microsoft-ui-xaml/issues/918.
