### ISSUE TITLE
Use of UserControl with VisualStateManager to achieve same results

### ISSUE THREAD

**Issue by jess-rod** [MicrosoftDocs/windows-uwp#2242]
In the list of examples given for when we might use different templates, I was wondering why not just reference (or embed) a UserControl inside the DataTemplate. This way, you could use VisualStateManager to change the background color, the font-size, the visibility, etc. of an UIElement depending on an object property value (e.g. IsSpecialItem).
Is this use of UserControl discouraged by some reason? Is it especially less performant?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2f2e0771-b6f5-66c6-affa-c09f317e911f
* Version Independent ID: 06169075-6507-7ca5-14a3-0ae7a0a867ff
* Content: [Data template selection - UWP applications](https://docs.microsoft.com/en-us/windows/uwp/design/controls-and-patterns/data-template-selector)
* Content Source: [windows-apps-src/design/controls-and-patterns/data-template-selector.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/design/controls-and-patterns/data-template-selector.md)
* Product: **uwp**
* Technology: **design**
* GitHub Login: @jwmsft
* Microsoft Alias: **jimwalk**

**Comment by jess-rod** [comment]
Nobody cares. Great.

**Comment by jwmsft** [comment]
Hi, sorry for the delayed response to this issue. The feedback channel you're using here (_Send feedback about > This page_) is for feedback about the documentation in this topic. For example, if you find a typo or believe that the documentation in this topic is incorrect.

- For questions or assistance, we recommend you visit [Microsoft Q&A](https://docs.microsoft.com/answers/index.html) to post your question. 
- To engage with the XAML product team or file a product bug, you can click [_Send feedback about > This product_](https://github.com/microsoft/microsoft-ui-xaml/issues/new/choose) from the doc page. This will let you open an issue with the development team in the WinUI repo on GitHub.

I'll go ahead and close this issue now, since there's no action I can see to take in the documentation. You can always reply to a closed issue, or even re-open it if you feel it's been closed in error.
