### ISSUE TITLE
Update Adobe XD design toolkit to WinUI 2.3

### ISSUE THREAD

**Issue by brunofpa** [MicrosoftDocs/windows-uwp#2244]
Hi, it would be great if you update the Adobe XD design toolkit to WinUI 2.3, not only Figma. Thanks.

---
#### Detalhes do documento

⚠ *Não edite esta seção. É necessário para a vinculação do problema do docs.microsoft.com ➟ GitHub.*

* ID: 7489a614-ddc3-d1ff-5ffd-b6d4228d9079
* Version Independent ID: 99b83fb8-3491-95eb-b4e1-ba326f82d784
* Content: [Projetar kits de ferramentas e amostras para aplicativos UWP - UWP applications](https://docs.microsoft.com/pt-br/windows/uwp/design/downloads/#feedback)
* Content Source: [windows-apps-src/design/downloads/index.md](https://github.com/MicrosoftDocs/windows-uwp.pt-br/blob/live/windows-apps-src/design/downloads/index.md)
* Product: **uwp**
* Technology: **design**
* GitHub Login: @Karl-Bridge-Microsoft
* Microsoft Alias: **kbridge**

**Comment by ranjeshj** [comment]
@chigy FYI

**Comment by Karl-Bridge-Microsoft** [comment]
Hi @brunofpa  - This feedback is not specifically about the documentation, but rather a feature/product request. Please contact the following support channel.

- The [Feedback Hub app](https://support.microsoft.com/help/4021566/windows-10-send-feedback-to-microsoft-with-feedback-hub-app) is the right place to lobby for a change, a feature, or to make a suggestion.

For future reference, here are all of the developer support resources.

- For developer issues, or suspected product bugs, there's [Microsoft Support](https://support.microsoft.com/contactus); a support engineer will look at the repro and see whether the issue is a Microsoft product bug, or something else. If it's a bug with a Microsoft product then the ticket will be free of charge.
- For community assistance with development questions, there are our [forums](https://social.msdn.microsoft.com/Forums/newthread?category=windowsapps&forum=wpdevelop&prof=required), and [StackOverflow](https://stackoverflow.com/questions).
- The [Windows developer support](https://developer.microsoft.com/windows/support) site explains other support options.
- The [Visual Studio developer community](https://developercommunity.visualstudio.com) is available, and responsive. The former User Voice feature is now there on the **Suggest a feature** tab, if you want to lobby for a change, a feature, or to make a suggestion.

If you receive assistance via any support resource, and you believe that information would help us improve the docs, then please come back and let us know.

**Comment by chigy** [comment]
@brunofpa , actually, please feel free to post issue at GitHub repo for WinUI:
https://github.com/microsoft/microsoft-ui-xaml/issues/new/choose
