### ISSUE TITLE
Cannot input 7 digits bank code

### ISSUE THREAD

**Issue by ctxhou** [MicrosoftDocs/windows-uwp#2246]
Hey,
I am wondering the meaning of 7 digits bank code. ![this page](https://imgur.com/q8Ct4lg)
My bank doesn't provide the 7 digits bank code but SWIFT. It supported SWIFT code but now the system doesn't have this field.
Could you let me know how can I input my bank info if my bank doesn't have bank code?
Thanks!

---
#### 文件詳細資料

⚠ *請勿編輯此區段。 這是 docs.microsoft.com ➟ GitHub 問題連結的必要項。*

* ID: 98f4a20b-33aa-a616-6206-461d83fde6b8
* Version Independent ID: c28b8f31-922e-02b3-93c9-effa13395e1d
* Content: [設定您的支出及納稅申報表 - UWP applications](https://docs.microsoft.com/zh-tw/windows/uwp/publish/setting-up-your-payout-account-and-tax-forms#feedback)
* Content Source: [windows-apps-src/publish/setting-up-your-payout-account-and-tax-forms.md](https://github.com/MicrosoftDocs/windows-uwp.zh-tw/blob/live/windows-apps-src/publish/setting-up-your-payout-account-and-tax-forms.md)
* Product: **uwp**
* Technology: **publish**
* GitHub Login: @hickeys
* Microsoft Alias: **hickeys**

**Comment by ctxhou** [comment]
the correct screenshot link: https://imgur.com/q8Ct4lg

**Comment by ctxhou** [comment]
hey @lastnameholiu any update about the issue?

**Comment by antoniodiego** [comment]
The seven digits are the bank number, that have 3 digits and the four digit of the AGENCY number.

**Comment by ctxhou** [comment]
@antoniodiego thanks for answering my question. However, my question is more related to `how can I input my bank info if my bank doesn't have bank code`. AFAIK, most of the banks only provide the SWIFT code.
Take [Citibank](https://www.bank-codes.com/citibank-n-a-swift-code-CITIUS33XXX-bic-code) as an example, I don't see they provide `7 digit bank code`.

Without this information, developers cannot receive the payment. Please help us figure out the issue.

**Comment by antoniodiego** [comment]
@ctxhou in Hong Kong the code is 250
http://www.thebankcodes.com/hongkong_banks/CITIBANK_(HONG_KONG)_LIMITED

**Comment by hickeys** [comment]
#
Thanks for reaching out with your feedback. Unfortunately, it looks like you're requesting technical support, and GitHub issues in this repo are only used for documentation issues. 

The best way to get support is by asking the community on the [Microsoft Developer Forums](https://social.msdn.microsoft.com/Forums/newthread?category=windowsapps&forum=wpdevelop&prof=required) or [StackOverflow](https://stackoverflow.com/questions) 

For completeness' sake, here is a list of developer resources:

- The [Feedback Hub app](https://support.microsoft.com/help/4021566/windows-10-send-feedback-to-microsoft-with-feedback-hub-app) is the right place to suggest or lobby for a change or feature.
- Try our [forums](https://social.msdn.microsoft.com/Forums/newthread?category=windowsapps&forum=wpdevelop&prof=required) and [StackOverflow](https://stackoverflow.com/questions) for community assistance with development questions.
- The [Windows developer support](https://developer.microsoft.com/windows/support) site explains other support options.
- The [Visual Studio developer community](https://developercommunity.visualstudio.com) is helpful and responsive. You can also suggest or lobby for a change or feature by clicking the **report a problem** or **suggest a feature** buttons.
- For developer issues or suspected product bugs, visit [Microsoft Support](https://support.microsoft.com/contactus). A support engineer will determine whether the issue is a Microsoft product bug. If it is, the ticket will be free of charge.

If you receive assistance via any support resource and you believe that information would help us improve the docs, then please let us know or consider submitting a pull request.

Thanks,
Shawn
