### ISSUE TITLE
For the add-on of "Subscription" type, will the original user continue to subscribe after Stop acquisition ?

### ISSUE THREAD

**Issue by mzhinf** [MicrosoftDocs/windows-uwp#2261]
![image](https://user-images.githubusercontent.com/35255621/75840656-ad634400-5e06-11ea-9d67-7e4c94b12d1b.png)

I don't think the description here is clear enough. If I choose Stop acquisition for one of my add-on (Product type: Subscription), I am not sure whether the original subscriber will continue to subscribe. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 70a1979d-7dc1-32f5-6ad4-86aaa880902f
* Version Independent ID: 271dd665-b978-ed57-969f-33023104a4aa
* Content: [Set add-on pricing and availability - UWP applications](https://docs.microsoft.com/en-us/windows/uwp/publish/set-add-on-pricing-and-availability)
* Content Source: [windows-apps-src/publish/set-add-on-pricing-and-availability.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/publish/set-add-on-pricing-and-availability.md)
* Product: **uwp**
* Technology: **publish**
* GitHub Login: @hickeys
* Microsoft Alias: **hickeys**

**Comment by GrantMeStrength** [comment]
We are changing the way we track issues filed from our documentation pages: please see this [blog post](https://techcommunity.microsoft.com/t5/microsoft-learn-blog/announcing-a-new-way-to-give-feedback-on-microsoft-learn/ba-p/4027635) for more details. The Microsoft Store documentation has been updated several times since your issue was reported, and there's a good chance your problem has been addressed. Right now, this issue is being closed but if you feel it is still valid and has not been addressed, please re-open it with any more available information. Please note that if you question is more general and not related to documentation, [Microsoft Q&A](https://learn.microsoft.com/en-us/answers/questions/) is a great way to get questions answered.
