### ISSUE TITLE
There is no documentation for animating a custom property on a custom control.

### ISSUE THREAD

**Issue by ghost** [MicrosoftDocs/windows-uwp#2266]
I have a custom control with a background that I want to light up and then fade after the content has been updated.  I don't want the entire control to fade, just the background.  So I created a custom property for this control called 'MaskOpacity' and I've tried to animate it without any luck.

Apparently there's something going on that's buried in the UWP controls that supports animation.  It may possibly have something to do with a **ScalarTransition**, however, I can't find ANY documentation at all on the subject.

I've attached a zip of the project.  Please either tell me how to make this work, or point me in the direction of some documentation (or an example of a control like 'Border') and I'll figure it out on my own.
[App1.zip](https://github.com/MicrosoftDocs/windows-uwp/files/4294984/App1.zip)

**Comment by hkhmsft** [comment]
This feels not so much like feedback specifically about the documentation, but rather like a support request. Here are all of the developer support resources, for completeness.

- [Microsoft Q&A](https://docs.microsoft.com/answers/topics/uwp.html?sort=active&filter=all) is the right place to lobby for a change, a feature, or to make a suggestion.
- For community assistance with development questions, there are our [forums](https://social.msdn.microsoft.com/Forums/newthread?category=windowsapps&forum=wpdevelop&prof=required), and [StackOverflow](https://stackoverflow.com/questions).
- The [Windows developer support](https://developer.microsoft.com/windows/support) site explains other support options.
- The [Visual Studio developer community](https://developercommunity.visualstudio.com) is available, and responsive. The former User Voice feature is now there on the **Suggest a feature** tab, if you want to lobby for a change, a feature, or to make a suggestion.
- For developer issues, or suspected product bugs, there's [Microsoft Support](https://support.microsoft.com/contactus); a support engineer will look at the repro and see whether the issue is a Microsoft product bug, or something else. If it's a bug with a Microsoft product then the ticket will be free of charge.

If you receive assistance via any support resource, and you believe that information would help us improve the docs, then please come back and let us know.
