### ISSUE TITLE
Verification is taking much time

### ISSUE THREAD

**Issue by antoniodiego** [MicrosoftDocs/windows-uwp#2270]
The verification of the my payment profiles have already taken more than 48 hours and yet not get the completed status

---
#### Detalhes do documento

⚠ *Não edite esta seção. É necessário para a vinculação do problema do docs.microsoft.com ➟ GitHub.*

* ID: 98f4a20b-33aa-a616-6206-461d83fde6b8
* Version Independent ID: c28b8f31-922e-02b3-93c9-effa13395e1d
* Content: [Configurar a conta de pagamento e formulários de imposto - UWP applications](https://docs.microsoft.com/pt-br/windows/uwp/publish/setting-up-your-payout-account-and-tax-forms#feedback)
* Content Source: [windows-apps-src/publish/setting-up-your-payout-account-and-tax-forms.md](https://github.com/MicrosoftDocs/windows-uwp.pt-br/blob/live/windows-apps-src/publish/setting-up-your-payout-account-and-tax-forms.md)
* Product: **uwp**
* Technology: **publish**
* GitHub Login: @hickeys
* Microsoft Alias: **hickeys**

**Comment by hkhmsft** [comment]
Thanks for reaching out with your feedback. Is there anything you'd like to see on our documentation that could potentially help solve your roadblock? If else, I'm thinking there might be answers to your specific issue on our developer resources. For community assistance with development questions I recommend that you ask on our [forums](https://social.msdn.microsoft.com/Forums/newthread?category=windowsapps&forum=wpdevelop&prof=required) or [StackOverflow](https://stackoverflow.com/questions). Otherwise, please see [the developer support page](https://developer.microsoft.com/windows/support) for your support options. If you get assistance through these other resources and believe that information would help us improve the docs, please come back, file a new Issue or Pull Request, and let us know.
