### ISSUE TITLE
Add support to download the preinstallkit pacakge for OEM

### ISSUE THREAD

**Issue by cjw1115** [MicrosoftDocs/windows-uwp#2271]
I din't find out any RESTful api here about the preinstall kit. I want to find such api to get the preinstall kit packages. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 09b9e01b-4634-641e-3e84-6806943cd171
* Version Independent ID: 384b901f-84e6-3145-1bd4-1f523c5f4cd6
* Content: [Microsoft Store services - UWP applications](https://docs.microsoft.com/en-us/windows/uwp/monetize/using-windows-store-services#feedback)
* Content Source: [windows-apps-src/monetize/using-windows-store-services.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/monetize/using-windows-store-services.md)
* Product: **uwp**
* Technology: **publish**
* GitHub Login: @hickeys
* Microsoft Alias: **hickeys**

**Comment by hickeys** [comment]
@cjw1115 I'm not sure what you are requesting. It sounds like maybe you'd like documentation about the REST APIs for the store? this docset is strictly for Windows app related store articles; REST APIs are out of the scope of this repo. Perhaps you can clarify?

**Comment by cjw1115** [comment]
> @cjw1115 I'm not sure what you are requesting. It sounds like maybe you'd like documentation about the REST APIs for the store? this docset is strictly for Windows app related store articles; REST APIs are out of the scope of this repo. Perhaps you can clarify?

Hi, I mean there are many RESTful api about the store, such as get flight, get submission. get app information.
I don't know if you know the PreinstallKit, for the OEM, the dev center account of them have ability to enable download the PreinstallKit from a flight or base submission. After enabling this feature, the user can download the package(PreinstallKit) from a flight. 

I want to know if you have such RESTFul api, so we can download the preinstall kit automatically. Or we have to login into the dev center, then download it manually. It's not convenient for our QA to do some package verification. Because QA have no permission to access our dev center.

**Comment by hickeys** [comment]
Thanks for reaching out with your feedback. GitHub issues in this repo are for documentation bugs only, and unfortunately this seems more like a support request than a documentation bug. 

The best way to get support is by asking the community on [Microsoft Q&A](https://docs.microsoft.com/answers/topics/uwp.html?sort=active&filter=all) or [StackOverflow](https://stackoverflow.com/questions) 

For completeness' sake, here is a list of developer resources:

- [Microsoft Q&A](https://docs.microsoft.com/answers/topics/uwp.html?sort=active&filter=all) offers relevant and timely answers to your technical problems from a community of experts and Microsoft engineers.
- For community assistance with development questions, there are our [forums](https://social.msdn.microsoft.com/Forums/newthread?category=windowsapps&forum=wpdevelop&prof=required), and [StackOverflow](https://stackoverflow.com/questions).
- The [Windows developer support](https://developer.microsoft.com/windows/support) site explains other support options.
- The [Visual Studio developer community](https://developercommunity.visualstudio.com) is available, and responsive. The former User Voice feature is now there on the **Suggest a feature** tab, if you want to lobby for a change, a feature, or to make a suggestion.
- For developer issues, or suspected product bugs, there's [Microsoft Support](https://support.microsoft.com/contactus); a support engineer will look at the repro and see whether the issue is a Microsoft product bug, or something else. If it's a bug with a Microsoft product then the ticket will be free of charge.

If you receive assistance via any support resource and you believe that information would help us improve the docs, then please let us know or consider submitting a pull request.

Thanks,
Shawn
