### ISSUE TITLE
Error in code snipped

### ISSUE THREAD

**Issue by 0x000eHx** [MicrosoftDocs/windows-uwp#2273]
I get the following error from running the first code snipped (getting serialcommunication devices in an async task with lambda expression).
If I just include this code snipped into a freshly made Visual Studio 2019 Community Edition UWP C++ project I get the following errormessage about "this" in the lambda expression brakets:
"Error (active)	E1740	lambda captured variable of type "App1::App ^*" cannot be copied to closure class field of type "App1::App ^"

If I found out correctly the error is present since a long time?
https://developercommunity.visualstudio.com/content/problem/488185/e1740-reported-in-vs2019-rc-when-capture-ccx-this.html
Sadly the accepted "solution" with:
auto _this = this;
does not work.

The code will still compile successfully even with the error.

How to solve this problem?

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: df902334-d9ec-5bf1-c61f-f68e79787e47
* Version Independent ID: b0fe703c-5fab-d672-1260-c04018340c8b
* Content: [Asynchrone Programmierung in C++ - UWP applications](https://docs.microsoft.com/de-de/windows/uwp/threading-async/asynchronous-programming-in-cpp-universal-windows-platform-apps#feedback)
* Content Source: [windows-apps-src/threading-async/asynchronous-programming-in-cpp-universal-windows-platform-apps.md](https://github.com/MicrosoftDocs/windows-uwp.de-de/blob/live/windows-apps-src/threading-async/asynchronous-programming-in-cpp-universal-windows-platform-apps.md)
* Product: **uwp**
* Technology: **processes-and-threading**
* GitHub Login: @drewbatgit
* Microsoft Alias: **drewbat**

**Comment by hkhmsft** [comment]
Hi @0x000eHx , we appreciate you submitting through our feedback channel. However, this feels not so much like feedback specifically about the documentation, but rather like a support request. Here are all of the developer support resources, for completeness.

- [Microsoft Q&A](https://docs.microsoft.com/answers/topics/uwp.html?sort=active&filter=all) is the right place to lobby for a change, a feature, or to make a suggestion.
- For community assistance with development questions, there are our [forums](https://social.msdn.microsoft.com/Forums/newthread?category=windowsapps&forum=wpdevelop&prof=required), and [StackOverflow](https://stackoverflow.com/questions).
- The [Windows developer support](https://developer.microsoft.com/windows/support) site explains other support options.
- The [Visual Studio developer community](https://developercommunity.visualstudio.com) is available, and responsive. The former User Voice feature is now there on the **Suggest a feature** tab, if you want to lobby for a change, a feature, or to make a suggestion.
- For developer issues, or suspected product bugs, there's [Microsoft Support](https://support.microsoft.com/contactus); a support engineer will look at the repro and see whether the issue is a Microsoft product bug, or something else. If it's a bug with a Microsoft product then the ticket will be free of charge.

If you receive assistance via any support resource, and you believe that information would help us improve the docs, then please come back and let us know.
