### ISSUE TITLE
Support options for UWP Bluetooth issues? 

### ISSUE THREAD

**Issue by almertes** [MicrosoftDocs/windows-uwp#2277]
What is the support path for UWP Bluetooth issues if a customer has Premier Support? Is it only GitHub forum support? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 30fb091c-b8a3-47f4-4c97-6c46eefb846c
* Version Independent ID: b05831db-1b39-eb91-41d1-daecdb320db2
* Content: [Bluetooth - UWP applications](https://docs.microsoft.com/en-us/windows/uwp/devices-sensors/bluetooth#feedback)
* Content Source: [windows-apps-src/devices-sensors/bluetooth.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/devices-sensors/bluetooth.md)
* Product: **uwp**
* Technology: **peripherals-sensors-and-power**
* GitHub Login: @Karl-Bridge-Microsoft
* Microsoft Alias: **kbridge**

**Comment by Karl-Bridge-Microsoft** [comment]
Hi @almertes - Premier Support is not a dev doc issue. If you've exhausted the Premier Support channels, please try one of the following alternatives.

- For developer issues, or suspected product bugs, there's [Microsoft Support](https://support.microsoft.com/contactus); a support engineer will look at the repro and see whether the issue is a Microsoft product bug, or something else. If it's a bug with a Microsoft product then the ticket will be free of charge.
- The [Feedback Hub app](https://support.microsoft.com/help/4021566/windows-10-send-feedback-to-microsoft-with-feedback-hub-app) is the right place to lobby for a change, a feature, or to make a suggestion.
- For community assistance with development questions, there are our [forums](https://social.msdn.microsoft.com/Forums/newthread?category=windowsapps&forum=wpdevelop&prof=required), and [StackOverflow](https://stackoverflow.com/questions).
- The [Windows developer support](https://developer.microsoft.com/windows/support) site explains other support options.
- The [Visual Studio developer community](https://developercommunity.visualstudio.com) is available, and responsive. The former User Voice feature is now there on the **Suggest a feature** tab, if you want to lobby for a change, a feature, or to make a suggestion.

If you receive assistance via any support resource, and you believe that information would help us improve the docs, then please come back and let us know.
