### ISSUE TITLE
Microsoft Pay window is empty

### ISSUE THREAD

**Issue by Vlad7772333** [MicrosoftDocs/windows-uwp#2286]
I ran your example for the first time and it worked. I then logged into my account, filled in the payment details and clicked buy. But now the Microsoft Pay window opens blank (https://monosnap.com/file/lb8ZlLCZTUSRavM6HZ5ZgmAe3dqMNj). I used a test project from GitHub and the code above. The Microsoft Pay window in the Microsoft Store works fine.
What can you advise to solve this problem?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 896f74b1-cd3a-c60e-2f99-b64f2b768a06
* Version Independent ID: fcb3a6ad-de4a-90cf-0513-ac25d95006f6
* Content: [Simplify payments with the Payment Request API - UWP applications](https://docs.microsoft.com/en-us/windows/uwp/monetize/payment-request#feedback)
* Content Source: [windows-apps-src/monetize/payment-request.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/monetize/payment-request.md)
* Product: **uwp**
* Technology: **publish**
* GitHub Login: @hickeys
* Microsoft Alias: **hickeys**

**Comment by hkhmsft** [comment]
Hi, we appreciate you submitting through our feedback channel. However, this feels not so much like feedback specifically about the documentation, but rather like a support request. Here are all of the developer support resources, for completeness.

- [Microsoft Q&A](https://docs.microsoft.com/answers/topics/uwp.html?sort=active&filter=all) is the right place to lobby for a change, a feature, or to make a suggestion.
- For community assistance with development questions, there are our [forums](https://social.msdn.microsoft.com/Forums/newthread?category=windowsapps&forum=wpdevelop&prof=required), and [StackOverflow](https://stackoverflow.com/questions).
- The [Windows developer support](https://developer.microsoft.com/windows/support) site explains other support options.
- The [Visual Studio developer community](https://developercommunity.visualstudio.com) is available, and responsive. The former User Voice feature is now there on the **Suggest a feature** tab, if you want to lobby for a change, a feature, or to make a suggestion.
- For developer issues, or suspected product bugs, there's [Microsoft Support](https://support.microsoft.com/contactus); a support engineer will look at the repro and see whether the issue is a Microsoft product bug, or something else. If it's a bug with a Microsoft product then the ticket will be free of charge.

If you receive assistance via any support resource, and you believe that information would help us improve the docs, we'd appreciate if you came back and let us know.

**Comment by Vlad7772333** [comment]
Thank you very much for your reply.
