### ISSUE TITLE
Performace SQL Server Express vs SQLite

### ISSUE THREAD

**Issue by msavazzi** [MicrosoftDocs/windows-uwp#2292]
Team,
I was working on a conversion of an access database into a "new" format that can work with UWP.
I've developed a simple app that reads the data from Access and writes it in to either SQL Server Express either SQLite.

Here is the perfromance:
SQLite:
START: 18/03/2020 12:23:52
END: 18/03/2020 14:05:59
DURATION: 01:42:07 (6.127 sec)

SQL Server Express
START: 18/03/2020 12:14:52
END: 18/03/2020 12:22:03
DURATION: 00:07:11 (431 sec)

SQLite is 14 time slower than SQL Server
The database are absolutely identical, same indexes, same foreign keys, same structure (using on both db the native data format to avoid on the fly conversion!)

Note: SQL Server is running on the same machine as the prog...

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6c591596-d202-244c-6fbf-31c288fe9b57
* Version Independent ID: 1473907c-0cba-8917-2fd8-d3ca1fb73cae
* Content: [Use a SQLite database in a UWP app - UWP applications](https://docs.microsoft.com/en-us/windows/uwp/data-access/sqlite-databases#feedback)
* Content Source: [windows-apps-src/data-access/sqlite-databases.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/data-access/sqlite-databases.md)
* Product: **uwp**
* Technology: **data-and-files**
* GitHub Login: @lastnameholiu
* Microsoft Alias: **alholiu**

**Comment by hkhmsft** [comment]
Thanks for taking the time to let us know about this. However, this feels not so much like feedback specifically about the documentation but rather like product feedback. Here are all of the developer support resources, for completeness.

 - The [Feedback Hub app](https://support.microsoft.com/help/4021566/windows-10-send-feedback-to-microsoft-with-feedback-hub-app) is the right place to lobby for a change, a feature, or to make a suggestion.
 - For community assistance with development questions, there are our [forums](https://social.msdn.microsoft.com/Forums/newthread?category=windowsapps&forum=wpdevelop&prof=required), and [StackOverflow](https://stackoverflow.com/questions).
 - The [Windows developer support](https://developer.microsoft.com/windows/support) site explains other support options.
 - The [Visual Studio developer community](https://developercommunity.visualstudio.com) is available, and responsive. The former User Voice feature is now there on the **Suggest a feature** tab, if you want to lobby for a change, a feature, or to make a suggestion.
 - For developer issues, or suspected product bugs, there's [Microsoft Support](https://support.microsoft.com/contactus); a support engineer will look at the repro and see whether the issue is a Microsoft product bug, or something else. If it's a bug with a Microsoft product then the ticket will be free of charge.
 
 If you receive assistance via any support resource, and you believe that information would help us improve the docs, then please come back and let us know.
