### ISSUE TITLE
For PaneCustomContent Property there is no sample code

### ISSUE THREAD

**Issue by jawahar603** [MicrosoftDocs/windows-uwp#2300]
Can I get a Sample Code for PaneCustomContent in Top Navigation View. Sample code with both front end and back end.
 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e69449df-a1ec-70dd-e563-0ad508733c47
* Version Independent ID: dc0e0acb-d92a-a039-5c16-f54a4b71d954
* Content: [Navigation view - UWP applications](https://docs.microsoft.com/en-us/windows/uwp/design/controls-and-patterns/navigationview#feedback)
* Content Source: [windows-apps-src/design/controls-and-patterns/navigationview.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/design/controls-and-patterns/navigationview.md)
* Product: **uwp**
* Technology: **design**
* GitHub Login: @jwmsft
* Microsoft Alias: **jimwalk**

**Comment by jwmsft** [comment]
There is some example code available in the XAML Controls Gallery, which is linked at the top of the navigation view page. The simple example looks like this:
```
<muxc:NavigationView.PaneCustomContent>
       <HyperlinkButton x:Name="PaneHyperlink" Content="More info" Margin="12,0" Visibility="Collapsed" />
</muxc:NavigationView.PaneCustomContent>
```

Because _any_ content can be placed in the PaneCustomContent, more complex examples for custom scenarios are outside the scope of what we can provide here.
