### ISSUE TITLE
windows.updateTask running multiple times

### ISSUE THREAD

**Issue by meenanarendra** [MicrosoftDocs/windows-uwp#2308]
We have implemented windows.updateTask for our application. This background task should run once, when user receive the updated version.

We have noticed that some of our clients are running this background task multiple times

count(ET) | ET | eventdate | TS
-- | -- | -- | --
1 | Application_Update_Task | 3/3/2020 | 3/3/2020 18:26
2 | Application_Update_Task | 3/3/2020 | 3/3/2020 23:07
1 | Application_Update_Task | 3/3/2020 | 3/3/2020 20:08
2 | Application_Update_Task | 3/3/2020 | 3/3/2020 22:37
2 | Application_Update_Task | 3/3/2020 | 3/3/2020 22:39
1 | Application_Update_Task | 3/3/2020 | 3/3/2020 21:04
1 | Application_Update_Task | 3/3/2020 | 3/3/2020 21:56
1 | Application_Update_Task | 3/3/2020 | 3/3/2020 21:04
1 | Application_Update_Task | 3/3/2020 | 3/3/2020 20:28
1 | Application_Update_Task | 3/3/2020 | 3/3/2020 23:10
1 | Application_Update_Task | 3/3/2020 | 3/3/2020 22:06
1 | Application_Update_Task | 3/3/2020 | 3/3/2020 9:44
2 | Application_Update_Task | 3/3/2020 | 3/3/2020 23:48
1 | Application_Update_Task | 3/3/2020 | 3/3/2020 9:44
2 | Application_Update_Task | 3/3/2020 | 3/3/2020 22:45
2 | Application_Update_Task | 3/3/2020 | 3/3/2020 17:48

What could cause this issue?

**Comment by hkhmsft** [comment]
Hi, we appreciate you submitting through our feedback channel. However, this feels not so much like feedback specifically about the documentation, but rather like a support request. Here are all of the developer support resources, for completeness.

- [Microsoft Q&A](https://docs.microsoft.com/answers/topics/uwp.html?sort=active&filter=all) is the right place to lobby for a change, a feature, or to make a suggestion.
- For community assistance with development questions, there are our [forums](https://social.msdn.microsoft.com/Forums/newthread?category=windowsapps&forum=wpdevelop&prof=required), and [StackOverflow](https://stackoverflow.com/questions).
- The [Windows developer support](https://developer.microsoft.com/windows/support) site explains other support options.
- The [Visual Studio developer community](https://developercommunity.visualstudio.com) is available, and responsive. The former User Voice feature is now there on the **Suggest a feature** tab, if you want to lobby for a change, a feature, or to make a suggestion.
- For developer issues, or suspected product bugs, there's [Microsoft Support](https://support.microsoft.com/contactus); a support engineer will look at the repro and see whether the issue is a Microsoft product bug, or something else. If it's a bug with a Microsoft product then the ticket will be free of charge.

If you receive assistance via any support resource, and you believe that information would help us improve the docs, we'd appreciate if you came back and let us know.
