### ISSUE TITLE
Cannot sign into my Azure AD Account

### ISSUE THREAD

**Issue by SamSaprunoff** [MicrosoftDocs/windows-uwp#2312]
I have not logged into my Win 10 partner center in a while and when I try and log into my Azure AD account I am unable to.  Basically if I select the "Sign into Azure AD" button I am redirected back to the "Get started with the Hardware Developer Program" page.  If I try and recreate my Azure AD account it says that my domain is already taken.... please advise.
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1603df77-580d-a332-ace4-10c4b6f1484b
* Version Independent ID: 7f70b8d6-5146-f327-86c8-9c17acbcac23
* Content: [Associate Azure Active Directory with your Partner Center account - UWP applications](https://docs.microsoft.com/en-us/windows/uwp/publish/associate-azure-ad-with-partner-center)
* Content Source: [windows-apps-src/publish/associate-azure-ad-with-partner-center.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/publish/associate-azure-ad-with-partner-center.md)
* Product: **uwp**
* Technology: **publish**
* GitHub Login: @hickeys
* Microsoft Alias: **hickeys**

**Comment by hkhmsft** [comment]
Hi, we appreciate you submitting through our feedback channel. However, this feels not so much like feedback specifically about the documentation, but rather like a support request. Here are all of the developer support resources, for completeness.

- [Microsoft Q&A](https://docs.microsoft.com/answers/topics/uwp.html?sort=active&filter=all) is the right place to lobby for a change, a feature, or to make a suggestion.
- For community assistance with development questions, there are our [forums](https://social.msdn.microsoft.com/Forums/newthread?category=windowsapps&forum=wpdevelop&prof=required), and [StackOverflow](https://stackoverflow.com/questions).
- The [Windows developer support](https://developer.microsoft.com/windows/support) site explains other support options.
- The [Visual Studio developer community](https://developercommunity.visualstudio.com) is available, and responsive. The former User Voice feature is now there on the **Suggest a feature** tab, if you want to lobby for a change, a feature, or to make a suggestion.
- For developer issues, or suspected product bugs, there's [Microsoft Support](https://support.microsoft.com/contactus); a support engineer will look at the repro and see whether the issue is a Microsoft product bug, or something else. If it's a bug with a Microsoft product then the ticket will be free of charge.

If you receive assistance via any support resource, and you believe that information would help us improve the docs, we'd appreciate if you came back and let us know.
