### ISSUE TITLE
This page is somewhat outdated

### ISSUE THREAD

**Issue by lukeblevins** [MicrosoftDocs/windows-uwp#2321]
When WinUI 3.0 is finalized and becomes an option, this page should be updated to reflect the fact that a desktop app framework now exists which empowers developers to pick the right blend of technology for their Windows App. Specialized platforms like WPF and WinForms should be labeled as such.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c56f2824-b04c-1e07-2de1-2f78f84834d1
* Version Independent ID: b73656a9-ba3d-2411-dfca-031586aad016
* Content: [Choose your app platform](https://docs.microsoft.com/en-us/windows/apps/desktop/choose-your-platform#feedback)
* Content Source: [hub/apps/desktop/choose-your-platform.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/hub/apps/desktop/choose-your-platform.md)
* Product: **uwp**
* Technology: **apps**
* GitHub Login: @mcleanbyron
* Microsoft Alias: **mcleans**

**Comment by mcleanbyron** [comment]
Thanks for your feedback. We are already tracking a number of future doc updates related to WinUI 3.0 and it's relation to UWP, WPF, Windows Forms, and C++ Win32 app development, and this article is absolutely on the list to be revised. Since this work is already being tracked internally for the future WinUI 3.0 final release, I'm closing this issue for now. If you have feedback about content that is incorrect in this article as of the current state of these technologies, today, please feel free to reopen this issue with further info.

**Comment by lukeblevins** [comment]
@mcleanbyron Thanks for the speedy response!
