### ISSUE TITLE
Response does not appear?

### ISSUE THREAD

**Issue by jevansAN** [MicrosoftDocs/windows-uwp#2324]
We've attempted to respond to a customer review but find that the response does not appear in the store. The response appears in the Partner page, where there is an "update your response" button, but clicking that produces a "you cannot respond to this review" message. Is this undoable? Would like readers to know we've responded.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 179cbc73-e5ec-0ecd-b3d8-968ee593905c
* Version Independent ID: 4b0e61f6-8b6a-fc8f-91bd-792ab97fef53
* Content: [Respond to customer reviews - UWP applications](https://docs.microsoft.com/en-us/windows/uwp/publish/respond-to-customer-reviews?redirectedfrom=MSDN)
* Content Source: [windows-apps-src/publish/respond-to-customer-reviews.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/publish/respond-to-customer-reviews.md)
* Product: **uwp**
* Technology: **publish**
* GitHub Login: @hickeys
* Microsoft Alias: **hickeys**

**Comment by hickeys** [comment]
Thanks for reaching out with your feedback. GitHub issues in this repo are for documentation bugs only, and unfortunately this seems more like a support request than a documentation bug. 

The best way to get support is by asking the community on [Microsoft Q&A](https://docs.microsoft.com/answers/topics/uwp.html?sort=active&filter=all) or [StackOverflow](https://stackoverflow.com/questions) 

For completeness' sake, here is a list of developer resources:

- [Microsoft Q&A](https://docs.microsoft.com/answers/topics/uwp.html?sort=active&filter=all) offers relevant and timely answers to your technical problems from a community of experts and Microsoft engineers.
- For community assistance with development questions, there are our [forums](https://social.msdn.microsoft.com/Forums/newthread?category=windowsapps&forum=wpdevelop&prof=required), and [StackOverflow](https://stackoverflow.com/questions).
- The [Windows developer support](https://developer.microsoft.com/windows/support) site explains other support options.
- The [Visual Studio developer community](https://developercommunity.visualstudio.com) is available, and responsive. The former User Voice feature is now there on the **Suggest a feature** tab, if you want to lobby for a change, a feature, or to make a suggestion.
- For developer issues, or suspected product bugs, there's [Microsoft Support](https://support.microsoft.com/contactus); a support engineer will look at the repro and see whether the issue is a Microsoft product bug, or something else. If it's a bug with a Microsoft product then the ticket will be free of charge.

If you receive assistance via any support resource and you believe that information would help us improve the docs, then please let us know or consider submitting a pull request.

Thanks,
Shawn
