### ISSUE TITLE
Update produce info?

### ISSUE THREAD

**Issue by jevansAN** [MicrosoftDocs/windows-uwp#2331]
We would like to update some of the imagery in the product info page, but cannot find a condition under which the page  is not locked. Submitting a package update is not unlocking the product information page - shouldn't it unlock when a new package is uploaded?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8731a612-b63e-55c4-b7d7-58c9e4b92448
* Version Independent ID: 1fc9f5e5-2b51-0b59-2419-ae428d98d737
* Content: [Create app Store listings - UWP applications](https://docs.microsoft.com/en-us/windows/uwp/publish/create-app-store-listings?redirectedfrom=MSDN)
* Content Source: [windows-apps-src/publish/create-app-store-listings.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/publish/create-app-store-listings.md)
* Product: **uwp**
* Technology: **publish**
* GitHub Login: @hickeys
* Microsoft Alias: **hickeys**

**Comment by radujipa** [comment]
@jevansAN I ran into the same issue today but was able to resolve it by following https://docs.microsoft.com/en-us/windows/uwp/publish/create-app-store-listings#add-and-edit-store-listing-info 

To clarify:

1. Go to your application overview page
2. Go to Submissions
3. Click `Update` on your latest submission. This will prepare a new submission for the app
4. From the submission overview page, under Store Listings, select the listing for the language you want to update.

![Capture](https://user-images.githubusercontent.com/3577547/80705384-3d0f3100-8ade-11ea-970f-5db9cfd5ed5d.PNG)

You should be able to update everything from there and submit your changes to the Store. If you don't see the options mentioned, double check you have the necessary permissions in Partner Center on your account to make those changes.

**Comment by hickeys** [comment]
Thanks for reaching out with your feedback. GitHub issues in this repo are for documentation bugs only, and unfortunately this seems more like a support request than a documentation bug. 

The best way to get support is by asking the community on [Microsoft Q&A](https://docs.microsoft.com/answers/topics/uwp.html?sort=active&filter=all) or [StackOverflow](https://stackoverflow.com/questions) 

For completeness' sake, here is a list of developer resources:

- [Microsoft Q&A](https://docs.microsoft.com/answers/topics/uwp.html?sort=active&filter=all) offers relevant and timely answers to your technical problems from a community of experts and Microsoft engineers.
- For community assistance with development questions, there are our [forums](https://social.msdn.microsoft.com/Forums/newthread?category=windowsapps&forum=wpdevelop&prof=required), and [StackOverflow](https://stackoverflow.com/questions).
- The [Windows developer support](https://developer.microsoft.com/windows/support) site explains other support options.
- The [Visual Studio developer community](https://developercommunity.visualstudio.com) is available, and responsive. The former User Voice feature is now there on the **Suggest a feature** tab, if you want to lobby for a change, a feature, or to make a suggestion.
- For developer issues, or suspected product bugs, there's [Microsoft Support](https://support.microsoft.com/contactus); a support engineer will look at the repro and see whether the issue is a Microsoft product bug, or something else. If it's a bug with a Microsoft product then the ticket will be free of charge.

If you receive assistance via any support resource and you believe that information would help us improve the docs, then please let us know or consider submitting a pull request.

Thanks,
Shawn
