### ISSUE TITLE
Custom Events not showing

### ISSUE THREAD

**Issue by mseminatore** [MicrosoftDocs/windows-uwp#2339]
I no longer see Custom Events on the Usage Report page. Is the documentation incorrect?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 568a22fa-574e-f7e6-f5f8-4a6bb89739a0
* Version Independent ID: c87e6bbc-64f6-0cf3-7033-69dd632b073a
* Content: [Usage report - UWP applications](https://docs.microsoft.com/en-us/windows/uwp/publish/usage-report?redirectedfrom=MSDN&source=docs#feedback)
* Content Source: [windows-apps-src/publish/usage-report.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/publish/usage-report.md)
* Product: **uwp**
* Technology: **publish**
* GitHub Login: @hickeys
* Microsoft Alias: **hickeys**

**Comment by HALOCORE** [comment]
Are the Custom Events obsoleted ? I still cannot see Custom Events on the Usage Report page. I think several months ago it's visible.

**Comment by GrantMeStrength** [comment]
We are changing the way we track issues filed from our documentation pages: please see this [blog post](https://techcommunity.microsoft.com/t5/microsoft-learn-blog/announcing-a-new-way-to-give-feedback-on-microsoft-learn/ba-p/4027635) for more details. The Microsoft Store documentation has been updated several times since your issue was reported, and there's a good chance your problem has been addressed. Right now, this issue is being closed but if you feel it is still valid and has not been addressed, please re-open it with any more available information. Please note that if your question is more general and not related to documentation, [Microsoft Q&A](https://learn.microsoft.com/en-us/answers/questions/) is a great way to get questions answered.
