### ISSUE TITLE
Support for CP_UTF8 by c-runtime

### ISSUE THREAD

**Issue by maxderhak** [MicrosoftDocs/windows-uwp#2342]
When will C-runtime libraries in visual studio be changed to support MBCS with more than 2 bytes?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8a28119a-77f2-160c-a4f1-f90ef9153423
* Version Independent ID: 28b24e82-f0ef-cceb-2136-f8dbfabfcadc
* Content: [Use the Windows UTF-8 code page - UWP applications](https://docs.microsoft.com/en-us/windows/uwp/design/globalizing/use-utf8-code-page#feedback)
* Content Source: [windows-apps-src/design/globalizing/use-utf8-code-page.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/design/globalizing/use-utf8-code-page.md)
* Product: **uwp**
* Technology: **design**
* GitHub Login: @Karl-Bridge-Microsoft
* Microsoft Alias: **kbridge**

**Comment by Karl-Bridge-Microsoft** [comment]
Hi @maxderhak  - This is product feedback and not specifically about the documentation. Please contact the following support channel.

- The [Feedback Hub app](https://support.microsoft.com/help/4021566/windows-10-send-feedback-to-microsoft-with-feedback-hub-app) is the right place to lobby for a change, a feature, or to make a suggestion.

Here are all of the developer support resources, for completeness.

- For developer issues, or suspected product bugs, there's [Microsoft Support](https://support.microsoft.com/contactus); a support engineer will look at the repro and see whether the issue is a Microsoft product bug, or something else. If it's a bug with a Microsoft product then the ticket will be free of charge.
- For community assistance with development questions, there are our [forums](https://social.msdn.microsoft.com/Forums/newthread?category=windowsapps&forum=wpdevelop&prof=required), and [StackOverflow](https://stackoverflow.com/questions).
- The [Windows developer support](https://developer.microsoft.com/windows/support) site explains other support options.
- The [Visual Studio developer community](https://developercommunity.visualstudio.com) is available, and responsive. The former User Voice feature is now there on the **Suggest a feature** tab, if you want to lobby for a change, a feature, or to make a suggestion.

If you receive assistance via any support resource, and you believe that information would help us improve the docs, then please come back and let us know.
