### ISSUE TITLE
Which Markets can do payout?

### ISSUE THREAD

**Issue by exp154** [MicrosoftDocs/windows-uwp#2349]
In your article, you state "In certain markets, developers can only submit free apps. If your account is registered in one of these markets, you will not have the option to set up a payout account."
However, clicking into that 'certain markets' link gives a list of 'Developer account and app-submission markets' which doesn't specify which regions can or cannot do payout. How do we know which regions are limited to free apps (no payout) only?
.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 98f4a20b-33aa-a616-6206-461d83fde6b8
* Version Independent ID: c28b8f31-922e-02b3-93c9-effa13395e1d
* Content: [Set up your payout account and tax forms - UWP applications](https://docs.microsoft.com/en-us/windows/uwp/publish/setting-up-your-payout-account-and-tax-forms)
* Content Source: [windows-apps-src/publish/setting-up-your-payout-account-and-tax-forms.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/publish/setting-up-your-payout-account-and-tax-forms.md)
* Product: **uwp**
* Technology: **publish**
* GitHub Login: @hickeys
* Microsoft Alias: **hickeys**

**Comment by GrantMeStrength** [comment]
We are changing the way we track issues filed from our documentation pages: please see this [blog post](https://techcommunity.microsoft.com/t5/microsoft-learn-blog/announcing-a-new-way-to-give-feedback-on-microsoft-learn/ba-p/4027635) for more details. The Microsoft Store documentation has been updated several times since your issue was reported, and there's a good chance your problem has been addressed. Right now, this issue is being closed but if you feel it is still valid and has not been addressed, please re-open it with any more available information. Please note that if you question is more general and not related to documentation, [Microsoft Q&A](https://learn.microsoft.com/en-us/answers/questions/) is a great way to get questions answered.
