### ISSUE TITLE
API changes?

### ISSUE THREAD

**Issue by ethanbb** [MicrosoftDocs/windows-uwp#2352]
I don't see the AddPackageByUriAsync method of PackageManager or the AddPackageOptions class in the API reference or in IntelliSense when replicating the example in Visual Studio. Have these APIs changed? If so, what is the current method for including an external location when registering a sparse package?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cf28a713-4e81-45e0-a3c7-0274ba6b2e85
* Version Independent ID: 19dd0436-a27d-8e50-5e7b-06c8fcd49a3f
* Content: [Grant identity to non-packaged desktop apps](https://docs.microsoft.com/en-us/windows/apps/desktop/modernize/grant-identity-to-nonpackaged-apps#feedback)
* Content Source: [hub/apps/desktop/modernize/grant-identity-to-nonpackaged-apps.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/hub/apps/desktop/modernize/grant-identity-to-nonpackaged-apps.md)
* Product: **uwp**
* Technology: **apps**
* GitHub Login: @mcleanbyron
* Microsoft Alias: **mcleans**

**Comment by mcleanbyron** [comment]
The features described in this article (including the PackageManager.AddPackageByUriAsync method) are available starting in Windows 10, version 2004. Previously, this article stated that the feature was introduced in Windows 10 Insider Preview Build 10.0.19000, since that was the specific build that first included these features. I have updated the article to clarify in several places that it requires Windows 10, version 2004 (including the section that refers to AddPackageByUriAsync).

**Comment by ethanbb** [comment]
Makes sense - thanks for your attention.
