### ISSUE TITLE
AudioGraph freezes and breaks when seeking Flac and Ogg files

### ISSUE THREAD

**Issue by chadfranklin47** [MicrosoftDocs/windows-uwp#2366]
I am developing a music application and have a slider set to seek through the audio file with mediaSourceAudioInputNode.Seek(). When seeking through Mp3 files, I have not encountered the problem yet, but when seeking through some Flac or Ogg files, the seek may work properly a few to several times, then the seek method will freeze for a few seconds and the AudioGraph will stop playback and not be able to play that file again (though it can switch to another file). I set up a Debug.WriteLine() before and after the Seek() and when the problem occurs, it takes a few seconds for the Debug.WriteLine() after the Seek() to get called whereas it normally happens instantly. I can provide specific problematic files if necessary. I have tested and gotten this problem on two Windows 10 machines.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 589e2eda-b495-126e-553d-65ebee87bd3c
* Version Independent ID: a850ef9a-9d08-64a2-dd6b-584d2059f392
* Content: [Audio graphs - UWP applications](https://docs.microsoft.com/en-us/windows/uwp/audio-video-camera/audio-graphs#feedback)
* Content Source: [windows-apps-src/audio-video-camera/audio-graphs.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/audio-video-camera/audio-graphs.md)
* Product: **uwp**
* Technology: **audio-video-and-camera**
* GitHub Login: @drewbatgit
* Microsoft Alias: **drewbat**

**Comment by drewbatgit** [comment]
Hello, GitHub issues in this repository are for feedback specifically about the documentation. It seems like your issue is a developer support request. Here are all of the developer support resources:

- The [Feedback Hub app](https://support.microsoft.com/help/4021566/windows-10-send-feedback-to-microsoft-with-feedback-hub-app) is the right place to lobby for a change, a feature, or to make a suggestion.
- For community assistance with development questions, there are our [forums](https://social.msdn.microsoft.com/Forums/newthread?category=windowsapps&forum=wpdevelop&prof=required), and [StackOverflow](https://stackoverflow.com/questions).
- The [Windows developer support](https://developer.microsoft.com/windows/support) site explains other support options.
- The [Visual Studio developer community](https://developercommunity.visualstudio.com) is available, and responsive. The former User Voice feature is now there on the **Suggest a feature** tab, if you want to lobby for a change, a feature, or to make a suggestion.
- For developer issues, or suspected product bugs, there's [Microsoft Support](https://support.microsoft.com/contactus); a support engineer will look at the repro and see whether the issue is a Microsoft product bug, or something else. If it's a bug with a Microsoft product then the ticket will be free of charge.

If you receive assistance via any support resource, and you believe that information would help us improve the documentation, then please come back and let us know.
