### ISSUE TITLE
Cannot fill in the correct tax id in the Taiwan market

### ISSUE THREAD

**Issue by ctxhou** [MicrosoftDocs/windows-uwp#2369]
Hi Microsoft support

I am a developer in your Microsoft store. I report the issue here since I cannot find any link/mail/contact to report this issue.

I am trying to file my Taiwanese tax status in your dashboard. The problem is, the max length of the Tax id field is only `8 digit`. However, the format of Taiwanese tax id is `10 digit`. Please reference the `Identity card number` section of [National_identification_card_(Taiwan)](https://en.wikipedia.org/wiki/National_identification_card_(Taiwan)).

![img](https://i.imgur.com/si1uZBX.png)

With this issue, I cannot properly report my tax id which means I cannot receive the payment.

Please help me report the issue to the proper team. Raising the issue in Github seems the only channel to me.
Or if you can provide me other ways to report this issue I would be really appreciated.

Thanks!

---
#### 文件詳細資料

⚠ *請勿編輯此區段。 這是 docs.microsoft.com ➟ GitHub 問題連結的必要項。*

* ID: 98f4a20b-33aa-a616-6206-461d83fde6b8
* Version Independent ID: c28b8f31-922e-02b3-93c9-effa13395e1d
* Content: [設定您的支出及納稅申報表 - UWP applications](https://docs.microsoft.com/zh-tw/windows/uwp/publish/setting-up-your-payout-account-and-tax-forms)
* Content Source: [windows-apps-src/publish/setting-up-your-payout-account-and-tax-forms.md](https://github.com/MicrosoftDocs/windows-uwp.zh-tw/blob/live/windows-apps-src/publish/setting-up-your-payout-account-and-tax-forms.md)
* Product: **uwp**
* Technology: **publish**
* GitHub Login: @hickeys
* Microsoft Alias: **hickeys**

**Comment by hkhmsft** [comment]
Hi @ctxhou , thanks for submitting your feedback. Here are all of the developer support resources, for completeness.

[Microsoft Q&A](https://docs.microsoft.com/answers/topics/uwp.html?sort=active&filter=all) offers relevant and timely answers to your technical problems from a community of experts and Microsoft engineers.
- For community assistance with development questions, there are our [forums](https://social.msdn.microsoft.com/Forums/newthread?category=windowsapps&forum=wpdevelop&prof=required), and [StackOverflow](https://stackoverflow.com/questions).
- The [Windows developer support](https://developer.microsoft.com/windows/support) site explains other support options.
- The [Visual Studio developer community](https://developercommunity.visualstudio.com) is available, and responsive. The former User Voice feature is now there on the **Suggest a feature** tab, if you want to lobby for a change, a feature, or to make a suggestion.
- For developer issues, or suspected product bugs, there's [Microsoft Support](https://support.microsoft.com/contactus); a support engineer will look at the repro and see whether the issue is a Microsoft product bug, or something else. If it's a bug with a Microsoft product then the ticket will be free of charge.

If you receive assistance via any support resource, and you believe that information would help us improve the docs, we'd appreciate if you came back and let us know.
