### ISSUE TITLE
Confused by the parameters

### ISSUE THREAD

**Issue by LuyTech** [MicrosoftDocs/windows-uwp#2371]
POST https://login.microsoftonline.com/&lt;tenant_id&gt;/oauth2/token HTTP/1.1
Host: login.microsoftonline.com
Content-Type: application/x-www-form-urlencoded; charset=utf-8

grant_type=client_credentials
&client_id=&lt;your_client_id&gt;
&client_secret=&lt;your_client_secret&gt;
&resource=https://onestore.microsoft.com

What do the parameters exactly mean????? put them as query params ?? or as body params????, can you give an explicit sample？？？？？ 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5efda84a-67f8-73d2-e9dd-ce9e5b26f17f
* Version Independent ID: 150aa4b2-23b4-e314-a5fc-6efd1185a8a1
* Content: [Manage product entitlements from a service - UWP applications](https://docs.microsoft.com/en-us/windows/uwp/monetize/view-and-grant-products-from-a-service#feedback)
* Content Source: [windows-apps-src/monetize/view-and-grant-products-from-a-service.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/monetize/view-and-grant-products-from-a-service.md)
* Product: **uwp**
* Technology: **publish**
* GitHub Login: @hickeys
* Microsoft Alias: **hickeys**

**Comment by GrantMeStrength** [comment]
We are changing the way we track issues filed from our documentation pages: please see this [blog post](https://techcommunity.microsoft.com/t5/microsoft-learn-blog/announcing-a-new-way-to-give-feedback-on-microsoft-learn/ba-p/4027635) for more details. Right now, this issue is being closed but if you feel it is still valid and has not been addressed, please re-open it with any more available information. Please note that if your question is more general and not related to documentation, [Microsoft Q&A](https://learn.microsoft.com/en-us/answers/questions/) is a great way to get questions answered.
