### ISSUE TITLE
Scheduling a sale for 'Owners of'

### ISSUE THREAD

**Issue by schemburkar** [MicrosoftDocs/windows-uwp#2384]
Can you clarify in the docs if when I Scheduling a sale for 'Owners of' for my app, does it apply to trial users of app or paid users of app. I would like to target paid and trail users of the app separetly, but 'Owners of' does not seem to provide information if it targets trail users or paid users or both.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7c06d6c6-6cf6-781b-590e-8a4774024bf1
* Version Independent ID: 79999d02-f758-8eda-bbfb-7e7aa4f4df7d
* Content: [Put apps and add-ons on sale - UWP applications](https://docs.microsoft.com/en-us/windows/uwp/publish/put-apps-and-add-ons-on-sale#feedback)
* Content Source: [windows-apps-src/publish/put-apps-and-add-ons-on-sale.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/publish/put-apps-and-add-ons-on-sale.md)
* Product: **uwp**
* Technology: **publish**
* GitHub Login: @hickeys
* Microsoft Alias: **hickeys**

**Comment by GrantMeStrength** [comment]
We are changing the way we track issues filed from our documentation pages: please see this [blog post](https://techcommunity.microsoft.com/t5/microsoft-learn-blog/announcing-a-new-way-to-give-feedback-on-microsoft-learn/ba-p/4027635) for more details. The Microsoft Store documentation has been updated several times since your issue was reported, and there's a good chance your problem has been addressed. Right now, this issue is being closed but if you feel it is still valid and has not been addressed, please re-open it with any more available information. Please note that if you question is more general and not related to documentation, [Microsoft Q&A](https://learn.microsoft.com/en-us/answers/questions/) is a great way to get questions answered.
