### ISSUE TITLE
DEV: Cannot connect to XDK with Dev Companion UWP app and does not show in list.

### ISSUE THREAD

**Issue by AM2petterk** [MicrosoftDocs/windows-uwp#2386]
Tried disabling Fiddler, did not work.

**Comment by hkhmsft** [comment]
Hi, we appreciate you submitting through our feedback channel. However, this feels not so much like feedback specifically about the documentation, but rather like a support request. Here are all of the developer support resources, for completeness.

[Microsoft Q&A](https://docs.microsoft.com/answers/topics/uwp.html?sort=active&filter=all) offers relevant and timely answers to your technical problems from a community of experts and Microsoft engineers.
- For community assistance with development questions, there are our [forums](https://social.msdn.microsoft.com/Forums/newthread?category=windowsapps&forum=wpdevelop&prof=required), and [StackOverflow](https://stackoverflow.com/questions).
- The [Windows developer support](https://developer.microsoft.com/windows/support) site explains other support options.
- The [Visual Studio developer community](https://developercommunity.visualstudio.com) is available, and responsive. The former User Voice feature is now there on the **Suggest a feature** tab, if you want to lobby for a change, a feature, or to make a suggestion.
- For developer issues, or suspected product bugs, there's [Microsoft Support](https://support.microsoft.com/contactus); a support engineer will look at the repro and see whether the issue is a Microsoft product bug, or something else. If it's a bug with a Microsoft product then the ticket will be free of charge.

If you receive assistance via any support resource, and you believe that information would help us improve the docs, we'd appreciate if you came back and let us know.

**Comment by AM2petterk** [comment]
Sorry, posted in a hurry! My bad...
