### ISSUE TITLE
useless

### ISSUE THREAD

**Issue by brabebhin** [MicrosoftDocs/windows-uwp#2396]
This has to be one of those useless pages in microsoft docs.
I got error 1201 and was redirected here, and this didn't do anything to narrow down the issue.

Delete this page and stop linking it from official stores.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7e281513-bb4e-c6d4-4429-bd92e3a3994a
* Version Independent ID: b3653e85-a2c1-0a84-5f47-8070121210e1
* Content: [Resolve submission errors - UWP applications](https://docs.microsoft.com/en-us/windows/uwp/publish/resolve-submission-errors?redirectedfrom=MSDN)
* Content Source: [windows-apps-src/publish/resolve-submission-errors.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/publish/resolve-submission-errors.md)
* Product: **uwp**
* Technology: **publish**
* GitHub Login: @hickeys
* Microsoft Alias: **hickeys**

**Comment by GrantMeStrength** [comment]
We are changing the way we track issues filed from our documentation pages: please see this [blog post](https://techcommunity.microsoft.com/t5/microsoft-learn-blog/announcing-a-new-way-to-give-feedback-on-microsoft-learn/ba-p/4027635) for more details. The Microsoft Store documentation has been updated several times since your issue was reported, and there's a good chance your problem has been addressed. Right now, this issue is being closed but if you feel it is still valid and has not been addressed, please re-open it with any more available information. Please note that if you question is more general and not related to documentation, [Microsoft Q&A](https://learn.microsoft.com/en-us/answers/questions/) is a great way to get questions answered.
