### ISSUE TITLE
Not able to connect with Microsoft HoloLens program to HoloLens2

### ISSUE THREAD

**Issue by FelixWeichselgartner** [MicrosoftDocs/windows-uwp#2407]
Hi,
I'm trying to add my hololens 2 device to the app. After I entered the IP and credentials I get the following error:
```
Can't connect
Make sure your HoloLens is on, Device Portal is turned on, and you're using the right user name, password, and IP address. Then try again.
```

However I can log on over the webinterface with the same credentials + ip I entered in the app. 

Any help is appreciated. If necessary I can provide further information. Have a nice day.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 399b4574-244e-6f47-322d-b8f52692beb7
* Version Independent ID: 04dafd8b-13d4-1940-49d5-22af6ad81fe5
* Content: [Device Portal for HoloLens - UWP applications](https://docs.microsoft.com/en-us/windows/uwp/debug-test-perf/device-portal-hololens)
* Content Source: [windows-apps-src/debug-test-perf/device-portal-hololens.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/debug-test-perf/device-portal-hololens.md)
* Product: **uwp**
* Technology: **deployment**
* GitHub Login: @Karl-Bridge-Microsoft
* Microsoft Alias: **kbridge**

**Comment by Karl-Bridge-Microsoft** [comment]
Hi @FelixWeichselgartner - This is not a developer doc issue, please try [HoloLens help](https://support.microsoft.com/en-us/hub/4338666/hololens-help). You might also find assistance from one of the following:

- For developer issues, or suspected product bugs, there's [Microsoft Support](https://support.microsoft.com/contactus); a support engineer will look at the repro and see whether the issue is a Microsoft product bug, or something else. If it's a bug with a Microsoft product then the ticket will be free of charge.
- The [Feedback Hub app](https://support.microsoft.com/help/4021566/windows-10-send-feedback-to-microsoft-with-feedback-hub-app) is the right place to lobby for a change, a feature, or to make a suggestion.
- For community assistance with development questions, there are our [forums](https://social.msdn.microsoft.com/Forums/newthread?category=windowsapps&forum=wpdevelop&prof=required), and [StackOverflow](https://stackoverflow.com/questions).
- The [Windows developer support](https://developer.microsoft.com/windows/support) site explains other support options.
- The [Visual Studio developer community](https://developercommunity.visualstudio.com) is available, and responsive. The former User Voice feature is now there on the **Suggest a feature** tab, if you want to lobby for a change, a feature, or to make a suggestion.

If you receive assistance via any support resource, and you believe that information would help us improve the docs, then please and let us know through this issue.
