### ISSUE TITLE
How to create layout for C# app from MSBuild

### ISSUE THREAD

**Issue by asklar** [MicrosoftDocs/windows-uwp#2412]
VS creates the layout folder by default but I can't figure out how to get MSBuild to do the same from the command line

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e8ee9c97-d766-6c25-eb40-0c7a2a41f908
* Version Independent ID: d17a0a28-ce1c-dd24-6b2d-05083a6e2809
* Content: [Deploy an app through loose file registration - UWP applications](https://docs.microsoft.com/en-us/windows/uwp/debug-test-perf/loose-file-registration)
* Content Source: [windows-apps-src/debug-test-perf/loose-file-registration.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/debug-test-perf/loose-file-registration.md)
* Product: **uwp**
* Technology: **deployment**
* GitHub Login: @Karl-Bridge-Microsoft
* Microsoft Alias: **kbridge**

**Comment by Karl-Bridge-Microsoft** [comment]
Hi @asklar - This feedback is not specifically about the documentation, but rather a support request. Please contact the following support channel.

- For developer issues, or suspected product bugs, there's [Microsoft Support](https://support.microsoft.com/contactus); a support engineer will look at the repro and see whether the issue is a Microsoft product bug, or something else. If it's a bug with a Microsoft product then the ticket will be free of charge.

Here are all of the developer support resources, for completeness.

- The [Feedback Hub app](https://support.microsoft.com/help/4021566/windows-10-send-feedback-to-microsoft-with-feedback-hub-app) is the right place to lobby for a change, a feature, or to make a suggestion.
- For community assistance with development questions, there are our [forums](https://social.msdn.microsoft.com/Forums/newthread?category=windowsapps&forum=wpdevelop&prof=required), and [StackOverflow](https://stackoverflow.com/questions).
- The [Windows developer support](https://developer.microsoft.com/windows/support) site explains other support options.
- The [Visual Studio developer community](https://developercommunity.visualstudio.com) is available, and responsive. The former User Voice feature is now there on the **Suggest a feature** tab, if you want to lobby for a change, a feature, or to make a suggestion.

If you receive assistance via any support resource, and you believe that information would help us improve the docs, then please come back and let us know.

**Comment by asklar** [comment]
Answering my own question: https://github.com/asklar/RegisterFromLayoutUWP.net
