### ISSUE TITLE
API Issues unresolved

### ISSUE THREAD

**Issue by cekageka** [MicrosoftDocs/windows-uwp#2415]
Hi, it looks like this API is orphaned. API responses (with valid key) are always 'unauthorised' and a bunch of issues in the API dashboard are unanswered for months. Any hint? Thanks, Christian

(See here: https://admetadata.portal.azure-api.net/issues) 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0e291bd6-f015-c848-acb5-2fad69b32ebd
* Version Independent ID: 36f59c20-e0c4-a30f-20df-5ffa06bfbf89
* Content: [App metadata API for advertising networks - UWP applications](https://docs.microsoft.com/en-us/windows/uwp/monetize/app-metadata-api-for-advertising-networks#feedback)
* Content Source: [windows-apps-src/monetize/app-metadata-api-for-advertising-networks.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/monetize/app-metadata-api-for-advertising-networks.md)
* Product: **uwp**
* Technology: **publish**
* GitHub Login: @hickeys
* Microsoft Alias: **hickeys**

**Comment by GrantMeStrength** [comment]
Hi - I'm sorry it's taken so long to get to this issue. I believe this is related to the closure of the Advertising features:

"As a reminder, we have shut down the Microsoft Ad Monetization services for Windows UWP apps per the sunset announcement made January 2020: "

https://social.msdn.microsoft.com/Forums/windowsapps/en-US/db8d44cb-1381-47f7-94d3-c6ded3fea36f/microsoft-ad-monetization-platform-shut-down-as-of-june-1st?forum=aiamgr

If this is not the case, and your issue is still a problem, please re-open this issue. Thanks - john
