### ISSUE TITLE
Error in MyUWPApp build.

### ISSUE THREAD

**Issue by wmacdonald-gpsw** [MicrosoftDocs/windows-uwp#2418]
I am getting a compile error when following these instructions, just after finishing the changes to MyUWPApp where the code for App.xaml is added.

1&gt;MyUserControl.xaml : XamlCompiler error WMC1002: x:Class type 'MyUWPApp.MyUserControl' is not found in 'MyUWPApp'

Visual Studio version is 16.5.4.
My Microsoft.Windows.CppWinRT package is v2.0.200316.3
My Microsoft.Toolkit.Win32.UI.XamlApplication package is v6.0.1

I reached this point once before, and could not figure out what was wrong. I gave up and started over from scratch, and have arrived at the same point...

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f62891dc-cad0-0ea2-66c3-a5b58d9e3f9a
* Version Independent ID: 911ab9f0-1c11-b2bf-9ecf-9fbed29df211
* Content: [Host a custom UWP control in a C++ Win32 app using the XAML Hosting API](https://docs.microsoft.com/en-us/windows/apps/desktop/modernize/host-custom-control-with-xaml-islands-cpp#feedback)
* Content Source: [hub/apps/desktop/modernize/host-custom-control-with-xaml-islands-cpp.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/hub/apps/desktop/modernize/host-custom-control-with-xaml-islands-cpp.md)
* Product: **uwp**
* Technology: **apps**
* GitHub Login: @mcleanbyron
* Microsoft Alias: **mcleans**

**Comment by mcleanbyron** [comment]
Thanks for submitting your feedback, and I'm sorry you're encountering this. If the MyUserControl.xaml you added to the project (per the instructions in this walkthrough) don't include any code-behind files, then you're almost certainly hitting a bug introduced in Visual Studio 16.5 that breaks the Blank User Control and Blank Page items for C++/WinRT projects. For more details about the bug, see these threads:

- [https://github.com/windows-toolkit/Microsoft.Toolkit.Win32/issues/252#issuecomment-611724739](https://github.com/windows-toolkit/Microsoft.Toolkit.Win32/issues/252#issuecomment-611724739)
- [https://github.com/microsoft/cppwinrt/issues/581](https://github.com/microsoft/cppwinrt/issues/581)
- [https://developercommunity.visualstudio.com/content/problem/959456/item-template-dependent-nesting-behavior-broken-in.html](https://developercommunity.visualstudio.com/content/problem/959456/item-template-dependent-nesting-behavior-broken-in.html)

According to [https://github.com/microsoft/cppwinrt/issues/581](https://github.com/microsoft/cppwinrt/issues/581), the bug fix is coming in Visual Studio 16.6, and the fix is included in [Preview 3](https://devblogs.microsoft.com/visualstudio/new-in-visual-studio-2019-v16-6-preview-3/).

**Comment by wmacdonald-gpsw** [comment]
Thank you, I had reached the same conclusion myself just now. I had to manually create the code-behind and recreate the file dependencies in the project. I am able to build it now. I am glad to see the bug is already fixed in 16.6.

**Comment by mcleanbyron** [comment]
I'm glad you were able to work through it by creating the code-behind on your own.
