### ISSUE TITLE
Maybe the sample code is not working 

### ISSUE THREAD

**Issue by elda27** [MicrosoftDocs/windows-uwp#2423]
I found following code and try it like this.

```cpp
winrt::fire_and_forget RunAsync(DispatcherQueue queue)
{
    ... // Begin on the calling thread...
 
    co_await winrt::resume_foreground(queue);
 
    ... // ...resume on the dispatcher thread.
}
```

This sample code pass the DispatcherQueue to `winrt::resume_foreground`.
But the `winrt::resume_foreground` is not accept DispatcherQueue (I'm understanding to accept only CoreDispatcher and DispatcherQueue is not derrived CoreDispatcher.)

And also the following code block occured compile error. 
I seem `DispatcherQueue` is not awaitable object. (don't have `await_ready` and etc).

```
winrt::fire_and_forget RunAsync(DispatcherQueue queue)
{
    ...
 
    co_await queue;
 
    ...
}
```

What is the correct information in this page?
I'm newbee of WinRT so maybe this issue is misunderstanding.

My envrionment informations
- Windows 10 x64 Build 1809 
- Visual Studio 2019 version 16.5.4

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: bd174fcd-dc5c-7536-9a12-0e7b5926e739
* Version Independent ID: b66899fb-46a5-ac2c-b9e0-a23ddb351b2b
* Content: [C++/WinRT でのより高度な同時実行操作と非同期操作 - UWP applications](https://docs.microsoft.com/ja-jp/windows/uwp/cpp-and-winrt-apis/concurrency-2#feedback)
* Content Source: [windows-apps-src/cpp-and-winrt-apis/concurrency-2.md](https://github.com/MicrosoftDocs/windows-uwp.ja-jp/blob/live/windows-apps-src/cpp-and-winrt-apis/concurrency-2.md)
* Product: **uwp**
* Technology: **platform**
* GitHub Login: @stevewhims
* Microsoft Alias: **stwhi**

**Comment by stevewhims** [comment]
Hi, @elda27, and thanks for filing this issue. The pattern shown in the topic is correct. You're right that you can pass a CoreDispatcher to winrt::resume_foreground (that implementation is in `winrt/Windows.UI.Core.h`). But you can also pass a DispatcherQueue to winrt::resume_foreground (that implementation is in `winrt/Windows.System.h`).

For the `winrt::fire_and_forget RunAsync(DispatcherQueue queue)` function, be sure to `#include <winrt/Windows.System.h>, and `using namespace winrt::Windows::System;`.

Thanks!
Steve

**Comment by elda27** [comment]
Thank you for reply.
I tried your answer but the problem isn't solved.

The `resume_foreground` accept by conversion operator to `CoreDispatcher` from `DispatcherQueue`. 
So I need `using namespace winrt::Windows::System;`. (I seem the conversion operator is defined in `winrt/Windows.System.h`)

Is it right?

I tried the following code.
Where is wrong?

```cpp
#include <iostream>
#include <cstdint>
#include <string>
#include <sstream>
#include <winrt/base.h>
#include <winrt/Windows.System.h>
#include <winrt/Windows.UI.Core.h>
#include <winrt/Windows.ApplicationModel.DataTransfer.h>

#include <random>
#include <sstream>

using namespace winrt;
using namespace winrt::Windows::System;
using namespace winrt::Windows::UI::Core;
using namespace winrt::Windows::ApplicationModel::DataTransfer;

#pragma comment(lib, "WindowsApp")

winrt::fire_and_forget run_async(DispatcherQueue queue)
{
  co_await winrt::resume_background();
  auto x = 10;
  auto y = 20;
  auto z = x * y;
  
  std::ostringstream oss;
  oss << "X:" << x << ",Y:" << y << "Z:" << z;
  /* I will run the something coroutine*/

  co_await winrt::resume_foreground(queue); ; // C2440, compile error, failed to solve override.

  DataPackage package{ nullptr };
  package.SetText(winrt::to_hstring(oss.str()));
  Clipboard::SetContent(package)
  Clipboard::Flush();
}

int main()
{
  winrt::init_apartment();
  
  auto controller{ DispatcherQueueController::CreateOnDedicatedThread() };
  
  run_async(controller.DispatcherQueue());

  return 0;
}
```

**Comment by stevewhims** [comment]
Hi, @elda27, I wasn't sure what kind of project you created but I notice you're explicitly linking [WindowsApp.lib](https://docs.microsoft.com/en-us/windows/uwp/cpp-and-winrt-apis/faq#why-is-the-linker-giving-me-a-lnk2019-unresolved-external-symbol-error). See that link for details about why you shouldn't need to do that.

If you set things up as per this info: [Visual Studio support for C++/WinRT, XAML, the VSIX extension, and the NuGet package](https://docs.microsoft.com/en-us/windows/uwp/cpp-and-winrt-apis/intro-to-using-cpp-with-winrt#visual-studio-support-for-cwinrt-xaml-the-vsix-extension-and-the-nuget-package), and if you create a project using one of the C++/WinRT project templates, then that's the recommended way.

There are very rare cases where the kind of project you create means you have to explicitly link WindowsApp.lib. But if you use a C++/WinRT project template, then you don't.

Anyway, in order to try and repro with something close to your setup, and based on that pragma, I thought I'd create a regular Windows Desktop Application project, instead of creating a C++/WinRT project. I pasted your code in, manually set C++17 as the standard, manually added the NuGet package (the NuGet package is described in the second link above), and added a semicolon after the call to Clipboard::SetContent. Once I'd done all that, the code compiled fine. So I wasn't able to repro your issue in my experiment.

Also, note that resume_foreground doesn't depend on a conversion operator. There are separate, different, implementations of resume_foreground in the two header files I mentioned.

My first recommendation would be to set up Visual Studio as described in that second link above. Then try creating a projected based on one of the C++/WinRT project templates that you get with the VSIX that's described at that link. And then see whether you can get your code to build in that project.

Thanks!
Steve

**Comment by elda27** [comment]
I solve problems after I recreate new project and configure such as reference page.
The old project can't solve problems by same procedure so maybe have any wrong configuration.
Thank you very much.

**Comment by stevewhims** [comment]
Thanks for the update! I'll go ahead and close the issue now.

-Steve
