### ISSUE TITLE
Definition of user

### ISSUE THREAD

**Issue by brynhr** [MicrosoftDocs/windows-uwp#2425]
Hi,

Please could you explain how you are identifying unique users. I have set up 2 test accounts in different groups, and signing in with different accounts in-app, in the store and in the OS seem to yield the default values only. Thanks.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 06258b5b-b13f-74be-210d-69b75a520925
* Version Independent ID: 62df4102-d658-4839-f6d8-41565deff355
* Content: [Run app experiments with A/B testing - UWP applications](https://docs.microsoft.com/en-gb/windows/uwp/monetize/run-app-experiments-with-a-b-testing#feedback)
* Content Source: [windows-apps-src/monetize/run-app-experiments-with-a-b-testing.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/monetize/run-app-experiments-with-a-b-testing.md)
* Product: **uwp**
* Technology: **publish**
* GitHub Login: @hickeys
* Microsoft Alias: **hickeys**

**Comment by GrantMeStrength** [comment]
We are changing the way we track issues filed from our documentation pages: please see this [blog post](https://techcommunity.microsoft.com/t5/microsoft-learn-blog/announcing-a-new-way-to-give-feedback-on-microsoft-learn/ba-p/4027635) for more details. Right now, this issue is being closed but if you feel it is still valid and has not been addressed, please re-open it with any more available information. Please note that if your question is more general and not related to documentation, [Microsoft Q&A](https://learn.microsoft.com/en-us/answers/questions/) is a great way to get questions answered.
