### ISSUE TITLE
Can not see my earnings from selling UPW

### ISSUE THREAD

**Issue by dorinionescu** [MicrosoftDocs/windows-uwp#2426]
I entered the developer site and redirected to the partner site and office store
There is no information about a cumulative amount from sales
The whole site is a mess about last 30 days stuff
It looks like Developper.Microsoft moved to Windows & XBox
I found it {Aquisition}{Custom}{1.jan.2010}{Gross Sales}
Now that you mixed everything together into Partner Site you should ask somebody to put the dashboards back - all this millions dollars work and integration of tons of business lines and the result is that your site looks primitive 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 65a40199-aaff-a750-b2df-cc8533606f0a
* Version Independent ID: 76160f31-f715-009a-e73e-202f8ed27006
* Content: [Payout reports - UWP applications](https://docs.microsoft.com/en-us/windows/uwp/publish/payout-summary#feedback)
* Content Source: [windows-apps-src/publish/payout-summary.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/publish/payout-summary.md)
* Product: **uwp**
* Technology: **publish**
* GitHub Login: @hickeys
* Microsoft Alias: **hickeys**

**Comment by dorinionescu** [comment]
full menu link 
{Windows & XBox}{Products}{choose one product}{Analytics}{Aquisitions}{Custom}{1.jan.2010}{Gross Sales}

**Comment by hickeys** [comment]
It looks like your feedback concerns the product itself, rather than the documentation for the product. Unfortunately, GitHub issues in this repo are only used for documentation issues. 

The best way to leave product feedback is through the [Feedback Hub app](https://support.microsoft.com/help/4021566/windows-10-send-feedback-to-microsoft-with-feedback-hub-app). If you return to the documentation page related to this issue and scroll to the bottom, there is a button to **leave feedback about this product**

For completeness' sake, here is a list of developer resources:

- The [Feedback Hub app](https://support.microsoft.com/help/4021566/windows-10-send-feedback-to-microsoft-with-feedback-hub-app) is the right place to suggest or lobby for a change or feature.
- Try our [forums](https://social.msdn.microsoft.com/Forums/newthread?category=windowsapps&forum=wpdevelop&prof=required) and [StackOverflow](https://stackoverflow.com/questions) for community assistance with development questions.
- The [Windows developer support](https://developer.microsoft.com/windows/support) site explains other support options.
- The [Visual Studio developer community](https://developercommunity.visualstudio.com) is helpful and responsive. You can also suggest or lobby for a change or feature by clicking the **report a problem** or **suggest a feature** buttons.
- For developer issues or suspected product bugs, visit [Microsoft Support](https://support.microsoft.com/contactus). A support engineer will determine whether the issue is a Microsoft product bug. If it is, the ticket will be free of charge.

If you receive assistance via any support resource and you believe that information would help us improve the docs, then please let us know or consider submitting a pull request.

Thanks,
Shawn
