### ISSUE TITLE
Transaction History Fields in documentation don't appear in transaction query results

### ISSUE THREAD

**Issue by mjfusa** [MicrosoftDocs/windows-uwp#2432]
Transactions: Microsoft Store Apps
The following fields documented, but are not in the output of the transaction history query results. Can you please update the documentation if this is the correct expectation? 

quantityType
paymentAmountWOTax
paymentCurrency
paymentExchangeRate
planId
customerCity
customerState
customerZip
programOfferingLevel
TenantID

Docs: https://docs.microsoft.com/en-us/windows/uwp/publish/payout-summary#transaction-history
API: https://apidocs.microsoft.com/services/partnerpayouts

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 65a40199-aaff-a750-b2df-cc8533606f0a
* Version Independent ID: 76160f31-f715-009a-e73e-202f8ed27006
* Content: [Payout reports - UWP applications](https://docs.microsoft.com/en-us/windows/uwp/publish/payout-summary)
* Content Source: [windows-apps-src/publish/payout-summary.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/publish/payout-summary.md)
* Product: **uwp**
* Technology: **publish**
* GitHub Login: @hickeys
* Microsoft Alias: **hickeys**

**Comment by hickeys** [comment]
Most of these fields have already been added as part of a change in report format. However, programOfferingLevel and TenantId, while in the list, are both missing descriptions, I've reached out to the engineering team, and will update these two items when I receive a response.

**Comment by GrantMeStrength** [comment]
We are changing the way we track issues filed from our documentation pages: please see this [blog post](https://techcommunity.microsoft.com/t5/microsoft-learn-blog/announcing-a-new-way-to-give-feedback-on-microsoft-learn/ba-p/4027635) for more details. The Microsoft Store documentation has been updated several times since your issue was reported, and there's a good chance your problem has been addressed. Right now, this issue is being closed but if you feel it is still valid and has not been addressed, please re-open it with any more available information. Please note that if you question is more general and not related to documentation, [Microsoft Q&A](https://learn.microsoft.com/en-us/answers/questions/) is a great way to get questions answered.
