### ISSUE TITLE
Transaction History Fields in query results need documentation

### ISSUE THREAD

**Issue by mjfusa** [MicrosoftDocs/windows-uwp#2433]
The following fields are in the output of the transaction history query results. However, they are not documented. Can you please include the definition for these fields in the documentation?

transactionCountryCode
licensingProgramName
taxCountry
taxState
taxCity
taxZipCode
programCode
earningAmountInLastPaymentCurrency
lastPaymentCurrency
assetId
orderId
lineItemId
resellerCountry
customerEmail
skuId
customerTenantId
invoiceDate
instantRebateAmount

Docs: https://docs.microsoft.com/en-us/windows/uwp/publish/payout-summary#transaction-history
API: https://apidocs.microsoft.com/services/partnerpayouts

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 65a40199-aaff-a750-b2df-cc8533606f0a
* Version Independent ID: 76160f31-f715-009a-e73e-202f8ed27006
* Content: [Payout reports - UWP applications](https://docs.microsoft.com/en-us/windows/uwp/publish/payout-summary)
* Content Source: [windows-apps-src/publish/payout-summary.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/publish/payout-summary.md)
* Product: **uwp**
* Technology: **publish**
* GitHub Login: @hickeys
* Microsoft Alias: **hickeys**

**Comment by hickeys** [comment]
I've reached out to the engineering team regarding these fields. I will reply on this issue as soon as I get a response. Thank you.

**Comment by GrantMeStrength** [comment]
We are changing the way we track issues filed from our documentation pages: please see this [blog post](https://techcommunity.microsoft.com/t5/microsoft-learn-blog/announcing-a-new-way-to-give-feedback-on-microsoft-learn/ba-p/4027635) for more details. The Microsoft Store documentation has been updated several times since your issue was reported, and there's a good chance your problem has been addressed. Right now, this issue is being closed but if you feel it is still valid and has not been addressed, please re-open it with any more available information. Please note that if you question is more general and not related to documentation, [Microsoft Q&A](https://learn.microsoft.com/en-us/answers/questions/) is a great way to get questions answered.
