### ISSUE TITLE
Store id key is related to the device and the Microsoft account. How can we detect changes to the Microsoft account?

### ISSUE THREAD

**Issue by frankcai4real** [MicrosoftDocs/windows-uwp#2438]
During the test, we found that the store id key is related to the device and the Microsoft account.
When we change the device or change the Microsoft account used for payment,  the store id key generated at the beginning cannot find the corresponding purchase information.
What we need to do is to regenerate the store id key when the device changes or when the Microsoft account changes.
The question is coming :
How can we detect changes to the Microsoft account?
Or I should regenerate the store id key every time I pay? Do not cache store id key?

**Comment by hickeys** [comment]
Thanks for reaching out with your feedback. GitHub issues in this repo are for documentation bugs only, and unfortunately this seems more like a support request than a documentation bug. 

The best way to get support is by asking the community on [Microsoft Q&A](https://docs.microsoft.com/answers/topics/uwp.html?sort=active&filter=all) or [StackOverflow](https://stackoverflow.com/questions) 

For completeness' sake, here is a list of developer resources:

- [Microsoft Q&A](https://docs.microsoft.com/answers/topics/uwp.html?sort=active&filter=all) offers relevant and timely answers to your technical problems from a community of experts and Microsoft engineers.
- For community assistance with development questions, there are our [forums](https://social.msdn.microsoft.com/Forums/newthread?category=windowsapps&forum=wpdevelop&prof=required), and [StackOverflow](https://stackoverflow.com/questions).
- The [Windows developer support](https://developer.microsoft.com/windows/support) site explains other support options.
- The [Visual Studio developer community](https://developercommunity.visualstudio.com) is available, and responsive. The former User Voice feature is now there on the **Suggest a feature** tab, if you want to lobby for a change, a feature, or to make a suggestion.
- For developer issues, or suspected product bugs, there's [Microsoft Support](https://support.microsoft.com/contactus); a support engineer will look at the repro and see whether the issue is a Microsoft product bug, or something else. If it's a bug with a Microsoft product then the ticket will be free of charge.

If you receive assistance via any support resource and you believe that information would help us improve the docs, then please let us know or consider submitting a pull request.

Thanks,
Shawn
