### ISSUE TITLE
No beforeunload event when exiting Take a Test

### ISSUE THREAD

**Issue by echao2012** [MicrosoftDocs/windows-uwp#2440]
The beforeunload event does not get fired when exiting Take a Test with either Ctrl+Alt+Delete, or Alt+Tab to the lock screen and logging in. I would like to sync with the server that the student has exited the test. Is there an alternative to this?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b75a82cd-e530-bc8e-b822-04cd0138dfd1
* Version Independent ID: 89efbaaf-77f3-6fbe-0616-29c129b4f475
* Content: [Take a Test JavaScript API. - UWP applications](https://docs.microsoft.com/en-us/windows/uwp/apps-for-education/take-a-test-api?redirectedfrom=MSDN#feedback)
* Content Source: [windows-apps-src/apps-for-education/take-a-test-api.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/apps-for-education/take-a-test-api.md)
* Product: **uwp**
* Technology: **app-types**
* GitHub Login: @hickeys
* Microsoft Alias: **hickeys**

**Comment by hickeys** [comment]
Thanks for reaching out with your feedback. GitHub issues in this repo are for documentation bugs only, and unfortunately this seems more like a support request than a documentation bug. 

The best way to get support is by asking the community on [Microsoft Q&A](https://docs.microsoft.com/answers/topics/uwp.html?sort=active&filter=all) or [StackOverflow](https://stackoverflow.com/questions) 

For completeness' sake, here is a list of developer resources:

- [Microsoft Q&A](https://docs.microsoft.com/answers/topics/uwp.html?sort=active&filter=all) offers relevant and timely answers to your technical problems from a community of experts and Microsoft engineers.
- For community assistance with development questions, there are our [forums](https://social.msdn.microsoft.com/Forums/newthread?category=windowsapps&forum=wpdevelop&prof=required), and [StackOverflow](https://stackoverflow.com/questions).
- The [Windows developer support](https://developer.microsoft.com/windows/support) site explains other support options.
- The [Visual Studio developer community](https://developercommunity.visualstudio.com) is available, and responsive. The former User Voice feature is now there on the **Suggest a feature** tab, if you want to lobby for a change, a feature, or to make a suggestion.
- For developer issues, or suspected product bugs, there's [Microsoft Support](https://support.microsoft.com/contactus); a support engineer will look at the repro and see whether the issue is a Microsoft product bug, or something else. If it's a bug with a Microsoft product then the ticket will be free of charge.

If you receive assistance via any support resource and you believe that information would help us improve the docs, then please let us know or consider submitting a pull request.

Thanks,
Shawn
