### ISSUE TITLE
Toast Notification of type reminder does not stay on screen indefinitely

### ISSUE THREAD

**Issue by WhiteDogBe** [MicrosoftDocs/windows-uwp#2442]
Hello,

My understanding is that a Toast Notification of the scenario type "reminder" or "alert" stays on the screen until the user interacts with it. This has also been my experience the past months, when creating these types of Toast Notifications. Since recently this behavior seems to have changed: after roughly 6 minutes, the Toast Notification is moved to the Message Center.

A number of observations lead me to believe this is some sort of bug:
- After roughly 6 minutes the toast notification is removed from the screen, though the documentation specifies it should remain on the screen until the user interacts with it.
- The toast notification does not get a status "TimedOut", there is no direct feedback in code at this time.
- If you interact with the Message Center at this point, a "TimedOut" is eventually returned.
- If, at any point, any other Toast Notification is shown, the message stays on the screen longer or re-appears. So for example, my message has disappeared, Outlook shows a toast Notification, then my reminder is back on screen as well.

I'm able to reproduce this behavior on various machines with different Windows OS versions (1809 through 1909). As a simple test, I can reproduce this using the "Notification Visualizer" Store App. Just pop a "Reminder" and wait 6 minutes. I've also tried a few other implementations (DesktopToast dll, own low-level implementation) and they do the same.

As a side question, I notice that the files in C:\Windows\System32\WinMetadata are from 2018 on my systems. I see that for example Windows.UI.Xaml.winmd has newer versions available via NuGet. Do I need to somehow update Windows.UI.winmd or use a newer version of it?

Many thanks for your time, I would really appreciate if someone could just give this a try and confirm or debunk they get the same behavior.

**Comment by hkhmsft** [comment]
Hi @WhiteDogBe , really appreciate the detailed feedback regarding Toast Notification. I could try and repro it, but I think it would be way more efficient if you submitted this directly to our [msdn forums](https://social.msdn.microsoft.com/Forums/newthreadcategory=windowsapps&forum=wpdevelop&prof=required) or to [Microsoft Q&A](https://docs.microsoft.com/answers/topics/uwp.html?sort=active&filter=all) .The community of experts and Microsoft engineers there is pretty active and may have better answers for you.

Alternatively, you can escalate it to [Windows developer support (navigate to Contact Us)](https://developer.microsoft.com/windows/support) or [Microsoft Support](https://support.microsoft.com/contactus) where a support engineer will look at the repro and see whether the issue is a Microsoft product bug, or something else. If it's a bug with a Microsoft product then the ticket will be free of charge.

If you receive assistance and you believe that information would help us improve the docs, we'd appreciate if you came back and let us know.
