### ISSUE TITLE
The WACK always returns an error

### ISSUE THREAD

**Issue by TechPhil** [MicrosoftDocs/windows-uwp#2448]
No matter what I do, the app manifest resources test is 'blocked from execution'
I'm not at my PC right now, so don't have the exact error to hand

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bea36edd-22d6-7d1e-73c3-63d8f276d679
* Version Independent ID: a50a03aa-e89d-55da-43ba-b23155b9bbaf
* Content: [Windows App Certification Kit - UWP applications](https://docs.microsoft.com/en-gb/windows/uwp/debug-test-perf/windows-app-certification-kit)
* Content Source: [windows-apps-src/debug-test-perf/windows-app-certification-kit.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/debug-test-perf/windows-app-certification-kit.md)
* Product: **uwp**
* Technology: **deployment**
* GitHub Login: @Karl-Bridge-Microsoft
* Microsoft Alias: **kbridge**

**Comment by Karl-Bridge-Microsoft** [comment]
Hi @TechPhil - This feedback is not specifically about the documentation, but rather a support request. Please contact the following support channel.

- For developer issues, or suspected product bugs, there's [Microsoft Support](https://support.microsoft.com/contactus); a support engineer will look at the repro and see whether the issue is a Microsoft product bug, or something else. If it's a bug with a Microsoft product then the ticket will be free of charge.

Here are all of the developer support resources, for completeness.

- The [Feedback Hub app](https://support.microsoft.com/help/4021566/windows-10-send-feedback-to-microsoft-with-feedback-hub-app) is the right place to lobby for a change, a feature, or to make a suggestion.
- For community assistance with development questions, there are our [forums](https://social.msdn.microsoft.com/Forums/newthread?category=windowsapps&forum=wpdevelop&prof=required), and [StackOverflow](https://stackoverflow.com/questions).
- The [Windows developer support](https://developer.microsoft.com/windows/support) site explains other support options.
- The [Visual Studio developer community](https://developercommunity.visualstudio.com) is available, and responsive. The former User Voice feature is now there on the **Suggest a feature** tab, if you want to lobby for a change, a feature, or to make a suggestion.

If you receive assistance via any support resource, and you believe that information would help us improve the docs, then please come back and let us know.
