### ISSUE TITLE
UWP not ready for production and real app development

### ISSUE THREAD

**Issue by msavazzi** [MicrosoftDocs/windows-uwp#2454]
Team, the page is misleading. I've opened several issues and bugs, as of today the UWP UI libraries are not usable. Something it could be done in couple of days with Forms of WPF like a very simple app that reads some data, shows a treeview and sorts the data... is simply impossible in UWP. Looks like controls are not stable enough to build apps

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c56f2824-b04c-1e07-2de1-2f78f84834d1
* Version Independent ID: b73656a9-ba3d-2411-dfca-031586aad016
* Content: [Choose your app platform](https://docs.microsoft.com/en-us/windows/apps/desktop/choose-your-platform#uwp)
* Content Source: [hub/apps/desktop/choose-your-platform.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/hub/apps/desktop/choose-your-platform.md)
* Product: **uwp**
* Technology: **apps**
* GitHub Login: @mcleanbyron
* Microsoft Alias: **mcleans**

**Comment by mcleanbyron** [comment]
I'm sorry you had a dissatisfactory experience with UWP development. Do you have specific feedback about particular controls that I can pass on to the product team?

In the mean time, the following samples may be of interest to you:

* [Inventory sample](https://github.com/Microsoft/InventorySample)
* [Customer orders database sample](https://github.com/Microsoft/Windows-appsample-customers-orders-database)

Also, it's not clear from your response whether you were aware that UWP apps provide controls such as treeviews, so just in case:

* [TreeView](https://docs.microsoft.com/en-us/windows/uwp/design/controls-and-patterns/tree-view)
* [DataGrid (in the Windows Community Toolkit](https://docs.microsoft.com/en-us/windows/communitytoolkit/controls/datagrid)

Since your feedback is about the UWP platform itself rather than issues with the docs, I'm going to pre-emptively close this issue. However, if you have further specific feedback about your UWP development experience, please add it here and I'll pass it on to the product team.

**Comment by msavazzi** [comment]
@mcleanbyron thank you for your prompt reply. As you can see here [Treeview selection leads to a complete crash](https://github.com/microsoft/microsoft-ui-xaml/issues/2465?notification_referrer_id=MDE4Ok5vdGlmaWNhdGlvblRocmVhZDg4MTUwMTA1MDoyNjYwMDMy#issuecomment-630921212) and here [Expand messes up selected item](https://github.com/microsoft/microsoft-ui-xaml/issues/2463) and several issues I've opened on StackOverflow (i.e. [UWP TreeView sort leads to random events](https://stackoverflow.com/questions/61826953/uwp-treeview-sort-leads-to-random-events/61861509?noredirect=1#comment109460596_61861509)). I'm aware of those controls but they are not usable. I opened a bug on the page as it leads people to think that UWP is ready to develop real world apps while it is not. I spent more than 2 month around bugs un the Xaml.UI and in the control and not related to my code :(

**Comment by mcleanbyron** [comment]
Thanks for your detailed reply. The microsoft-ui-xaml repo is the best place to submit issues like these against the product team, so I'm glad you opened those issues there. The product team does triage those issues on a regular basis.
