### ISSUE TITLE
Query for Products Fails if a large number of products (> 5000) are associated with client id

### ISSUE THREAD

**Issue by mjfusa** [MicrosoftDocs/windows-uwp#2469]
1) Microsoft Subscriptions Validation Failing - Purchase API returns Service Unavailable.
Summary: Calling https://purchase.mp.microsoft.com/v8.0/b2b/recurrences/query result in error: 503 Service Unavailable
Research: The total number of products that are associated with the AAD app client id it seems to be exceeding an internal limit  which forces the 503 error.

2) IAP Validation Failure
Summary: https://collections.mp.microsoft.com/v6.0/collections/query recently purchased IAP are not appearing in query results.
Research: The total number of products that are associated with the AAD client id seems to be exceeding an internal limit. This is causing the query to not return complete results. 

Workaround: Register a separate AAD app (client id) with each app or game. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5efda84a-67f8-73d2-e9dd-ce9e5b26f17f
* Version Independent ID: 150aa4b2-23b4-e314-a5fc-6efd1185a8a1
* Content: [Manage product entitlements from a service - UWP applications](https://docs.microsoft.com/en-us/windows/uwp/monetize/view-and-grant-products-from-a-service#feedback)
* Content Source: [windows-apps-src/monetize/view-and-grant-products-from-a-service.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/monetize/view-and-grant-products-from-a-service.md)
* Product: **uwp**
* Technology: **publish**
* GitHub Login: @hickeys
* Microsoft Alias: **hickeys**

**Comment by hickeys** [comment]
It looks like your feedback concerns the product itself, rather than the documentation for the product. Unfortunately, GitHub issues in this repo are only used for documentation issues. 

The best way to leave product feedback is through the [Feedback Hub app](https://support.microsoft.com/help/4021566/windows-10-send-feedback-to-microsoft-with-feedback-hub-app). If you return to the documentation page related to this issue and scroll to the bottom, there is a button to **leave feedback about this product**

For completeness' sake, here is a list of developer resources:

- The [Feedback Hub app](https://support.microsoft.com/help/4021566/windows-10-send-feedback-to-microsoft-with-feedback-hub-app) is the right place to suggest or lobby for a change or feature.
- Try our [forums](https://social.msdn.microsoft.com/Forums/newthread?category=windowsapps&forum=wpdevelop&prof=required) and [StackOverflow](https://stackoverflow.com/questions) for community assistance with development questions.
- The [Windows developer support](https://developer.microsoft.com/windows/support) site explains other support options.
- The [Visual Studio developer community](https://developercommunity.visualstudio.com) is helpful and responsive. You can also suggest or lobby for a change or feature by clicking the **report a problem** or **suggest a feature** buttons.
- For developer issues or suspected product bugs, visit [Microsoft Support](https://support.microsoft.com/contactus). A support engineer will determine whether the issue is a Microsoft product bug. If it is, the ticket will be free of charge.

If you receive assistance via any support resource and you believe that information would help us improve the docs, then please let us know or consider submitting a pull request.

Thanks,
Shawn
