### ISSUE TITLE
Leading letters missing

### ISSUE THREAD

**Issue by Marv51** [MicrosoftDocs/windows-uwp#2487]
Further down in the list, starting with "TappedEventArgs" some leading letters are clearly missing.

Unless there really is a new namespace called "nagement" 😁 (Clearly must be "Management")

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: c68dc509-816d-26b2-4e61-c87e52171b6b
* Version Independent ID: 7d8d4517-28f1-19e5-a102-6bfa4ce21173
* Content: [Windows 10 Build 19041 API changes - UWP applications](https://docs.microsoft.com/de-de/windows/uwp/whats-new/windows-10-build-19041-api-diff)
* Content Source: [windows-apps-src/whats-new/windows-10-build-19041-api-diff.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/whats-new/windows-10-build-19041-api-diff.md)
* Product: **uwp**
* Technology: **whats-new**
* GitHub Login: @QuinnRadich
* Microsoft Alias: **quradic**

**Comment by Marv51** [comment]
Any update on this?

**Comment by QuinnRadich** [comment]
For now, I'm removing the malformed entries. We generate this page from scripting in our side, so I need to track down exactly what broke it.

It's possible that the malformed entries were never intended to be added to this list, as they might be APIs which are internal or otherwise not documented. I'll evaluate, and re-add them in a fixed state if neccesary.
