### ISSUE TITLE
restrictedcapabilities returns 404

### ISSUE THREAD

**Issue by mark99i** [MicrosoftDocs/windows-uwp#2501]
Link http://schemas.microsoft.com/appx/manifest/foundation/windows10/restrictedcapabilities returns 404 error

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fdfe599a-af5b-acbc-1405-d1030d9f6661
* Version Independent ID: 85857337-8448-af63-b543-f01ef482ea09
* Content: [App capability declarations - UWP applications](https://docs.microsoft.com/en-us/windows/uwp/packaging/app-capability-declarations)
* Content Source: [windows-apps-src/packaging/app-capability-declarations.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/packaging/app-capability-declarations.md)
* Product: **uwp**
* Technology: **deployment**
* GitHub Login: @mcleanbyron
* Microsoft Alias: **mcleans**

**Comment by mcleanbyron** [comment]
The URL `http://schemas.microsoft.com/appx/manifest/foundation/windows10/restrictedcapabilities` is used in the context of the package manifest as an XML namespace in which the rescap:Capability element is defined. Just think of this as a unique string that defines a specific XML namespace. It is by design that this URL does not lead to a live web site.
