### ISSUE TITLE
Dependencies and references

### ISSUE THREAD

**Issue by rolandoglez** [MicrosoftDocs/windows-uwp#2508]
Hello,

Guide: https://docs.microsoft.com/en-us/windows/apps/desktop/modernize/host-standard-control-with-xaml-islands

I'm having issues on this step: 
_In your WPF project, right-click the Dependencies node and add a reference to your UWP app project._

I can't find the _Dependencies node_. 

I can only find:
1. right-click on WPF project > Build dependences (this works), or
2. right click on WPF project > Add > Reference (this doesn't work, I get error)

Document Details
⚠ Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.

ID: 6ba9095f-57b4-267d-8896-5375c68b01ee
Version Independent ID: 514d7e51-6f16-8199-aabf-26ee901a6ed3
Content: Host a standard UWP control in a WPF app using XAML Islands
Content Source: hub/apps/desktop/modernize/host-standard-control-with-xaml-islands.md
Product: uwp
Technology: apps
GitHub Login: @mcleanbyron
Microsoft Alias: mcleans

**Comment by mcleanbyron** [comment]
Thanks for your feedback. It looks like the "Dependencies" node is only available for WPF projects that target .NET Core, whereas projects that target .NET Framework require the alternate procedure you followed. I have updated this section in the article to clarify this step.

**Comment by lkwapien** [comment]
I have tried this tutorial several times.   The tutorial seems to suggest that the WPF App can target the .NET Framework. 

Step 1 of this section (Create a WPF project) 
https://docs.microsoft.com/en-us/windows/apps/desktop/modernize/host-standard-control-with-xaml-islands#create-a-wpf-project
States "In Visual Studio 2019, create a new WPF App (.NET Framework) or..."

But every time I try to use a WPF app (.NET Framework), I will fail Step 2 of this later section (Instantiate the XamlApplication object in the entry point of your WPF app )
https://docs.microsoft.com/en-us/windows/apps/desktop/modernize/host-standard-control-with-xaml-islands#instantiate-the-xamlapplication-object-in-the-entry-point-of-your-wpf-app.

I will always get an error CS0246 "Tye type or namespace name [my UWP project name] could not be found (are you missing a using directive or an assembly reference?).   And I am not able to add a reference to [ my UWP project].  

Is this because an application targeting .NET Framework cannot reference a Universal Windows project?

If yes, then there is an error in the tutorial.  Do NOT state  "In Visual Studio 2019, create a new WPF App (.NET Framework) or..." if this cannot be done! 

 

When I repeat the tutorial, and in Step 1 of this section (Create a WPF project) 
https://docs.microsoft.com/en-us/windows/apps/desktop/modernize/host-standard-control-with-xaml-islands#create-a-wpf-project
 I do THIS instead:  "In Visual Studio 2019, create a new ...WPF App (.NET Core)"
then I can successfully get past Instantiation of the XamlApplication object in the entry point of the WPF app.
