### ISSUE TITLE
Example showing third-party runtime classes with EventHandler<T>

### ISSUE THREAD

**Issue by tewarid** [MicrosoftDocs/windows-uwp#2518]
Section https://docs.microsoft.com/en-us/windows/uwp/cpp-and-winrt-apis/author-events#parameterized-delegates-and-simple-signals-across-an-abi mentions that "first- and third-party runtime classes, as well as primitive types such as numbers and strings" may be used with EventHandler<T> but doesn't give an example.

I've defined my own runtime class such as

```idl
    [default_interface]
    runtimeclass MyEventArgs 
    {
        MyEventArgs();
        ...
    }
```

But I still get "must be WinRT type" error when using EventHandler<MyEventArgs>.

Is it possible to pass a UInt8[] i.e. com_array through EventHandler?

Any help is highly appreciated.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 565e1bd5-9e15-fc88-8ccc-05d09cbde209
* Version Independent ID: 63b7ce5c-d2e7-d742-4fbd-b9729595a797
* Content: [Author events in C++/WinRT - UWP applications](https://docs.microsoft.com/en-us/windows/uwp/cpp-and-winrt-apis/author-events)
* Content Source: [windows-apps-src/cpp-and-winrt-apis/author-events.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/cpp-and-winrt-apis/author-events.md)
* Product: **uwp**
* Technology: **platform**
* GitHub Login: @stevewhims
* Microsoft Alias: **stwhi**

**Comment by stevewhims** [comment]
Hi, @tewarid, is it possible that you're using an instance of the implementation type for **MyEventArgs**, rather than the projected type, when you're raising the event? In the code below, I create an object of the implementation type simply so that I can use the non-projected non-default constructor. Constructing an object of the implementation type actually returns a com_ptr (in the variable `args`). Then just dereference `args` back to a pointer to the implementation type when using it to raise the event (`*args`).

```cppwinrt
void BankAccount::AdjustBalance(float value)
{
    m_balance += value;

    if (m_balance < 0.f)
    {
        auto args = winrt::make_self<winrt::BankAccountWRC::implementation::MyEventArgs>(m_balance);
        m_accountIsInDebitEvent(*this, *args);
    }
}
```

Yes, I would expect that you would be able to use a winrt::com_array (https://docs.microsoft.com/uwp/cpp-ref-for-winrt/com-array) as the type parameter for EventHandler.

Thanks!
-Steve

**Comment by tewarid** [comment]
> Hi, @tewarid, is it possible that you're using an instance of the implementation type for **MyEventArgs**, rather than the projected type, when you're raising the event? In the code below, I create an object of the implementation type simply so that I can use the non-projected non-default constructor. Constructing an object of the implementation type actually returns a com_ptr (in the variable `args`). Then just dereference `args` back to a pointer to the implementation type when using it to raise the event (`*args`).
> 
> ```
> void BankAccount::AdjustBalance(float value)
> {
>     m_balance += value;
> 
>     if (m_balance < 0.f)
>     {
>         auto args = winrt::make_self<winrt::BankAccountWRC::implementation::MyEventArgs>(m_balance);
>         m_accountIsInDebitEvent(*this, *args);
>     }
> }
> ```

Your example and an idl I found in unit tests of [cppwinrt](https://github.com/microsoft/cppwinrt) have been immensely helpful!

Here's how I am declaring the event in the idl

```idl
        event Windows.Foundation.EventHandler<IInspectable> MyEvent;
```

In the implementation, I've got

```cpp
        winrt::event_token MyEvent(winrt::Windows::Foundation::EventHandler<IInspectable> const& handler)
        {
            return this->myEvent.add(handler);
        }
        void MyEvent(winrt::event_token const& token)
        {
            this->myEvent.remove(token);
        }

private:
    winrt::event<winrt::Windows::Foundation::EventHandler<IInspectable>> myEvent;
```

> 
> Yes, I would expect that you would be able to use a winrt::com_array (https://docs.microsoft.com/uwp/cpp-ref-for-winrt/com-array) as the type parameter for EventHandler.
> 

I'm stuck at the idl on this. I've tried

```idl
    event Windows.Foundation.EventHandler<UInt8[]> MyEvent;
```

But, I get the following compilation error

```text
error MIDL2025: [msg]syntax error [context]: expecting > or , near "["
```

> Thanks!
> -Steve

Thanks,
Devendra

**Comment by stevewhims** [comment]
Ah, yes, I was wrong about the array. There is a corner case where you can't use an array as a parameter type argument to a parameterized interface. But see whether the example here helps you: https://docs.microsoft.com/windows/uwp/cpp-and-winrt-apis/concurrency-2#returning-an-array-asynchronously.

For the **MyEventArgs** scenario, I've added more example code to https://docs.microsoft.com/windows/uwp/cpp-and-winrt-apis/author-events#parameterized-delegates-across-an-abi. I would suggest you do something more like that, rather than using **IInspectable**.

Thanks!
Steve

**Comment by tewarid** [comment]
Thanks for the prompt responses and help! I'll close this issue as I've been able to do what I wanted, by wrapping a com_array in a winrt runtime class.

**Comment by Walkramis** [comment]
Hi @tewarid, I know this is an old issue but I want to do the same thing you wanted to do (return UInt8[] from an event) but I am unable to do so. Would you mind explaining a bit closer how you did? Thanks!
/Amdreas
