### ISSUE TITLE
can not click/select

### ISSUE THREAD

**Issue by tharun916** [MicrosoftDocs/windows-uwp#2534]
![image](https://user-images.githubusercontent.com/34917430/85197934-101f1380-b302-11ea-9db7-bbbe7041f7c2.png)
![image](https://user-images.githubusercontent.com/34917430/85197974-65f3bb80-b302-11ea-9ed5-77595d1daca6.png)

can not select/click menubar item -> File
pls help to solve this issue

**Comment by hkhmsft** [comment]
Hi @tharun916, thanks for bringing this to our attention. Could you instead submit this through [Microsoft Q&A](https://docs.microsoft.com/answers/topics/uwp.html?sort=active&filter=all) or through [Microsoft Support](https://support.microsoft.com/contactus)? A support engineer can look at the repro and see whether the issue is a Microsoft product bug, or something else. If it's a bug with a Microsoft product then the ticket will be free of charge. The folks over at Q&A might also have an answer for you. The scope of our team handles documentation issues, so I'm afraid I can't offer the right answer for you.
 
 If you receive assistance via Q&A or Microsoft Support, and you believe that information would help us improve the docs, then please come back and let us know!
