### ISSUE TITLE
How to debug payment errors?

### ISSUE THREAD

**Issue by mc0re** [MicrosoftDocs/windows-uwp#2554]
[Enter feedback here]
If during the sign up procedure one has got an error with a correlation ID, how to find out what went wrong?

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c4ddd610-d6de-7a7c-2d59-fdc08dd98371
* Version Independent ID: 1ed74795-fa40-80a5-4fc2-6f4e87efa594
* Content: [Opening a developer account - UWP applications](https://docs.microsoft.com/en-gb/windows/uwp/publish/opening-a-developer-account)
* Content Source: [windows-apps-src/publish/opening-a-developer-account.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/publish/opening-a-developer-account.md)
* Product: **uwp**
* Technology: **publish**
* GitHub Login: @hickeys
* Microsoft Alias: **hickeys**

**Comment by Pololot64** [comment]
I have the same issue. I see an error reported on the status page but I do not know if it is related...

**Comment by hickeys** [comment]
Thanks for reaching out with your feedback. GitHub issues in this repo are for documentation bugs only, and unfortunately this seems more like a support request than a documentation bug. 

The best way to get support is by asking the community on [Microsoft Q&A](https://docs.microsoft.com/answers/topics/uwp.html?sort=active&filter=all) or [StackOverflow](https://stackoverflow.com/questions) 

For completeness' sake, here is a list of developer resources:

- [Microsoft Q&A](https://docs.microsoft.com/answers/topics/uwp.html?sort=active&filter=all) offers relevant and timely answers to your technical problems from a community of experts and Microsoft engineers.
- For community assistance with development questions, there are our [forums](https://social.msdn.microsoft.com/Forums/newthread?category=windowsapps&forum=wpdevelop&prof=required), and [StackOverflow](https://stackoverflow.com/questions).
- The [Windows developer support](https://developer.microsoft.com/windows/support) site explains other support options.
- The [Visual Studio developer community](https://developercommunity.visualstudio.com) is available, and responsive. The former User Voice feature is now there on the **Suggest a feature** tab, if you want to lobby for a change, a feature, or to make a suggestion.
- For developer issues, or suspected product bugs, there's [Microsoft Support](https://support.microsoft.com/contactus); a support engineer will look at the repro and see whether the issue is a Microsoft product bug, or something else. If it's a bug with a Microsoft product then the ticket will be free of charge.

If you receive assistance via any support resource and you believe that information would help us improve the docs, then please let us know or consider submitting a pull request.

Thanks,
Shawn
