### ISSUE TITLE
Re-word description of remote-wsl

### ISSUE THREAD

**Issue by JacksonKearl** [MicrosoftDocs/windows-uwp#2568]
> We recommend using Visual Studio Code with the Remote-WSL Extension for Node.js projects. This splits VS Code into a “client-server” architecture, with the client (the user interface) running on your Windows machine and the server (your code, Git, plugins, etc) running remotely.

Both the client and the server are running locally in the remote-wsl case. cc @bamurtaugh

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c6995595-66c4-f26a-b307-89a068b4b5ba
* Version Independent ID: 69400ed1-5d98-4d6e-47a3-5c409564e77d
* Content: [Set up NodeJS on WSL 2](https://docs.microsoft.com/en-us/windows/nodejs/setup-on-wsl2)
* Content Source: [hub/nodejs/setup-on-wsl2.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/hub/nodejs/setup-on-wsl2.md)
* Product: **dev-environment**
* Technology: **windows-nodejs**
* GitHub Login: @mattwojo
* Microsoft Alias: **mattwoj**

**Comment by mattwojo** [comment]
Hi @JacksonKearl - Thanks for contributing this issue. I think this may be getting into semantics a bit. The statement you've identified is correct --the VS Code Remote extension defines the WSL instance as 'remote', even though you're correct that it's all still running on your local machine. This is because of the architecture of WSL running as it's own separated OS... so we've found it helpful to think as the client/user interface/Windows OS side as 'local' and the server / WSL / Linux OS side as 'remote' (even though it's not in the cloud as one may typically think about remote).

**Comment by bamurtaugh** [comment]
Hi @mattwojo, thanks for considering this issue. While it is semantics, I'd say the semantics here are important. We've had multiple users find defining this as "remote" to be confusing as they think they need a server running remotely in Azure to use WSL. Could we consider either rewording the explanation, or adding an additional explanation to clear up confusion? For instance,

> Note: The server was defined as "remote" because WSL runs as its own OS, but this server is actually running on your local machine. In WSL, your host machine and "remote instance," which is your Linux distribution, are all on your same local machine, making it different than other remote scenarios that leverage the cloud or another computer.

**Comment by mattwojo** [comment]
Interesting. Thanks @bamurtaugh. That's a strange assumption to draw. We can certainly add a note to improve clarity here. I'll follow up on email. I'd like to know more about where the user feedback is coming in from.

**Comment by mattwojo** [comment]
Added a note further explaining the client/local - server/remote context here. :)
https://github.com/MicrosoftDocs/windows-uwp-pr/pull/927

Thanks for bringing this issue to our attention!
