### ISSUE TITLE
How to get to the "Notes for certification" page?

### ISSUE THREAD

**Issue by mc0re** [MicrosoftDocs/windows-uwp#2575]
I wanted to amend some info, but I couldn't find that **Notes** page anymore. How to get to it?

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4b926c9e-ab41-f8cc-d2f9-df92cc1992a8
* Version Independent ID: 91f91c74-a4eb-8104-d094-d4012867b180
* Content: [Notes for certification - UWP applications](https://docs.microsoft.com/en-gb/windows/uwp/publish/notes-for-certification)
* Content Source: [windows-apps-src/publish/notes-for-certification.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/publish/notes-for-certification.md)
* Product: **uwp**
* Technology: **publish**
* GitHub Login: @hickeys
* Microsoft Alias: **hickeys**

**Comment by hickeys** [comment]
I'm not sure I understand what you mean. It looks like you were on the notes page when you submitted this issue, in which case you've already found it. There is an edit button at the top right of the page if you'd like to edit the content. 

Please let me know if I've misunderstood. Otherwise I'll close this issue in a couple days.

Thanks,
Shawn

**Comment by GrantMeStrength** [comment]
We are changing the way we track issues filed from our documentation pages: please see this [blog post](https://techcommunity.microsoft.com/t5/microsoft-learn-blog/announcing-a-new-way-to-give-feedback-on-microsoft-learn/ba-p/4027635) for more details. The Microsoft Store documentation has been updated several times since your issue was reported, and there's a good chance your problem has been addressed. Right now, this issue is being closed but if you feel it is still valid and has not been addressed, please re-open it with any more available information. Please note that if you question is more general and not related to documentation, [Microsoft Q&A](https://learn.microsoft.com/en-us/answers/questions/) is a great way to get questions answered.
