### ISSUE TITLE
Context Menu Sample

### ISSUE THREAD

**Issue by MelbourneDeveloper** [MicrosoftDocs/windows-uwp#2580]
The [context menu sample](https://github.com/Microsoft/Windows-universal-samples/tree/master/Samples/XamlContextMenu) doesn't work. 

We need a working context menu sample.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 24777eff-7485-a1ba-17b8-d56547bbd26d
* Version Independent ID: c5da8413-6441-3d07-4b84-02f145336771
* Content: [Menus and context menus - UWP applications](https://docs.microsoft.com/en-us/windows/uwp/design/controls-and-patterns/menus)
* Content Source: [windows-apps-src/design/controls-and-patterns/menus.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/design/controls-and-patterns/menus.md)
* Product: **uwp**
* Technology: **design**
* GitHub Login: @jwmsft
* Microsoft Alias: **jimwalk**

**Comment by jwmsft** [comment]
Sorry for the delayed response to this issue. The documentation team does not own the sample linked to, but I ran the sample and did not see any errors. If this issue is still is still relevant, please consider opening a new issue in the [sample repo](https://github.com/microsoft/Windows-universal-samples/issues) and providing details about what doesn't work. Thanks.
