### ISSUE TITLE
Unable to register for "Windows & Xbox" developer program for Azure AD

### ISSUE THREAD

**Issue by ramondeklein** [MicrosoftDocs/windows-uwp#2592]
I am global administrator for our company's Azure AD account, but I am unable to enroll in the "Windows & Xbox" developer program. This makes it impossible to deploy a UWP application. It seems that an Azure AD account cannot be used to enroll in the developer program. Is that correct? We don't want to use live accounts for the developer program, because we cannot administer them.

**Comment by hkhmsft** [comment]
Thanks for taking the time to let us know about this and we apologize for the delayed feedback. Unfortunately, this feedback channel covers specific documentation fixes rather than broader product feedback or questions. 

May I suggest that you direct your question over at [Microsoft Q&A](https://docs.microsoft.com/en-us/answers/topics/windows-uwp.html)? The community of experts and Microsoft engineers can provide timely answers to your technical questions. If you do create a thread over at Microsoft Q&A, it would be fantastic if you could share that link here so I can track the progress and potentially incorporate the technical details into our documentation.

Though I'm marking this Issue as closed now, please treat this thread as an open thread for follow-ups. Thanks!
