### ISSUE TITLE
Document error responses

### ISSUE THREAD

**Issue by geoffreyharding** [MicrosoftDocs/windows-uwp#2628]
This page should document the error responses given when:
- the product is not owned by the player
- the product quantity is too low
- the transaction Id is invalid
etc.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e88c05ee-343d-365a-742c-d7dceaa6d885
* Version Independent ID: f87ef3c0-b4ec-c113-8944-feb17f19f691
* Content: [Report consumable products as fulfilled - UWP applications](https://docs.microsoft.com/en-us/windows/uwp/monetize/report-consumable-products-as-fulfilled)
* Content Source: [windows-apps-src/monetize/report-consumable-products-as-fulfilled.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/monetize/report-consumable-products-as-fulfilled.md)
* Product: **uwp**
* Technology: **publish**
* GitHub Login: @hickeys
* Microsoft Alias: **hickeys**

**Comment by GrantMeStrength** [comment]
We are changing the way we track issues filed from our documentation pages: please see this [blog post](https://techcommunity.microsoft.com/t5/microsoft-learn-blog/announcing-a-new-way-to-give-feedback-on-microsoft-learn/ba-p/4027635) for more details. The Microsoft Store documentation has been updated several times since your issue was reported, and there's a good chance your problem has been addressed. Right now, this issue is being closed but if you feel it is still valid and has not been addressed, please re-open it with any more available information. Please note that if you question is more general and not related to documentation, [Microsoft Q&A](https://learn.microsoft.com/en-us/answers/questions/) is a great way to get questions answered.
