### ISSUE TITLE
.NET Framework 4.x apps on Windows 10 on ARM/ARM64

### ISSUE THREAD

**Issue by lostmsu** [MicrosoftDocs/windows-uwp#2640]
Can you clarify if it is possible to develop and distribute .NET Framework 4.x apps to Windows 10 on ARM devices (like Surface Pro X) via Windows Store?

I have [a .NET 4.x-based app](https://www.microsoft.com/en-us/p/stack-window-manager/9p4rj8rl7qgs) packaged with Desktop Bridge with **Architecture: Neutral** (.NET AnyCPU). However, it is not showing up in the Store on Surface Pro X.

Is there anything special, that needs to be set for it to show up, or is this scenario unsupported?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5c920a34-495e-ae99-365a-f6bc0afa2052
* Version Independent ID: 1e3c088d-3ca5-7f26-b1f6-23d9c97918e7
* Content: [Windows 10 on ARM - UWP applications](https://docs.microsoft.com/en-us/windows/uwp/porting/apps-on-arm)
* Content Source: [windows-apps-src/porting/apps-on-arm.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/porting/apps-on-arm.md)
* Product: **uwp**
* Technology: **porting-apps**
* GitHub Login: @hickeys
* Microsoft Alias: **hickeys**

**Comment by hkhmsft** [comment]
Thanks for taking the time to let us know about this. It seems your Issue leans more towards a product question rather than specific documentation fixes. 

May I suggest that you direct your question over at [Microsoft Q&A](https://docs.microsoft.com/en-us/answers/topics/windows-uwp.html)? The community of experts and Microsoft engineers can provide timely answers to your technical questions. If you do create a thread over at Microsoft Q&A, it would be fantastic if you could share that link here so I can track the progress and potentially incorporate the technical details into our documentation.

Though I'm marking this Issue as closed now, please treat this thread as an open thread for follow-ups. Thanks!
