### ISSUE TITLE
Inconsistent use of the term Publisher and Developer. We should consistently use Publisher.

### ISSUE THREAD

**Issue by hepais-microsoft** [MicrosoftDocs/windows-uwp#2650]
On the tax details page, https://docs.microsoft.com/en-us/windows/uwp/publish/tax-details-for-paid-apps, I noticed that the “Tax Responsibility” column says “Developer” in some situations and “Publisher” in others. Are the terms “Developer” and “Publisher” the same? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 58a4c7de-a435-db43-f36b-7711f14601fc
* Version Independent ID: 9d1d6b61-dd84-fd6a-1eb6-0fd472075b07
* Content: [Tax details - UWP applications](https://docs.microsoft.com/en-us/windows/uwp/publish/tax-details-for-paid-apps)
* Content Source: [windows-apps-src/publish/tax-details-for-paid-apps.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/publish/tax-details-for-paid-apps.md)
* Product: **uwp**
* Technology: **publish**
* GitHub Login: @hickeys
* Microsoft Alias: **hickeys**

**Comment by GrantMeStrength** [comment]
We are changing the way we track issues filed from our documentation pages: please see this [blog post](https://techcommunity.microsoft.com/t5/microsoft-learn-blog/announcing-a-new-way-to-give-feedback-on-microsoft-learn/ba-p/4027635) for more details. The Microsoft Store documentation has been updated several times since your issue was reported, and there's a good chance your problem has been addressed. Right now, this issue is being closed but if you feel it is still valid and has not been addressed, please re-open it with any more available information. Please note that if you question is more general and not related to documentation, [Microsoft Q&A](https://learn.microsoft.com/en-us/answers/questions/) is a great way to get questions answered.
