### ISSUE TITLE
Remove this page (ContentLinkProvider) as it is not working anymore

### ISSUE THREAD

**Issue by luishdemetrio** [MicrosoftDocs/windows-uwp#2658]
I noticed that ContentLinkProvider is not working anymore and that there is the internal 20189381 bug opened. My suggestion is to remove this page (https://docs.microsoft.com/en-us/windows/uwp/design/controls-and-patterns/content-links#content-link-providers)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ef2a71dc-50b1-5f99-7a22-c7854253ea2e
* Version Independent ID: e869333a-1bef-0f5e-7e40-516b31b13367
* Content: [Content links in text controls - UWP applications](https://docs.microsoft.com/en-us/windows/uwp/design/controls-and-patterns/content-links#content-link-providers)
* Content Source: [windows-apps-src/design/controls-and-patterns/content-links.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/design/controls-and-patterns/content-links.md)
* Product: **uwp**
* Technology: **design**
* GitHub Login: @jwmsft
* Microsoft Alias: **jimwalk**

**Comment by drewbatgit** [comment]
Thanks for taking the time to let us know about this and we sincerely apologize for the delayed response. We are aware of the status of this feature, but in order to support existing apps, we generally don't just delete pages altogether. For now, we have added this important note to the top of the page:

"The Windows features that enable content links are not available in versions of Windows after Windows 10 version 1903. Content links for XAML text controls will not function in versions of Windows later than version 1903."

Periodically we "archive" pages, which keeps them available to users that are using deprecated features but gets them out of the primary content. This page is on our list of pages to potentially archive in the future.

Thanks again for your help in keeping our docs up to date and accurate!
