### ISSUE TITLE
Is there C++ API for Windows.Services.Store

### ISSUE THREAD

**Issue by ronggong** [MicrosoftDocs/windows-uwp#2665]
Hi,

Is there C++ API for Windows.Services.Store? I am writing my app in C++, and creating the app package upload file using visual studio 2019. Is there any document to tell me how to add package updates functionality in the app for this case?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d3aae6d8-4751-8713-cb47-180ca2a1af01
* Version Independent ID: e46c9be3-742b-a831-5b7e-8363cd61bba9
* Content: [Download and install package updates from the Store - UWP applications](https://docs.microsoft.com/en-us/windows/uwp/packaging/self-install-package-updates)
* Content Source: [windows-apps-src/packaging/self-install-package-updates.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/packaging/self-install-package-updates.md)
* Product: **uwp**
* Technology: **deployment**
* GitHub Login: @mcleanbyron
* Microsoft Alias: **mcleans**

**Comment by mcleanbyron** [comment]
Windows apps written in C++ can use [C++/WinRT](https://docs.microsoft.com/en-us/windows/uwp/cpp-and-winrt-apis/intro-to-using-cpp-with-winrt) to easily call any WinRT API, including the Windows.Services.Store APIs. Since it sounds like you have an existing project, you'll probably want to just install the Microsoft.Windows.CppWinRT NuGet package (although you could certainly install the VSIX as well for new projects). 

You may also see this [get started](https://docs.microsoft.com/en-us/windows/uwp/cpp-and-winrt-apis/get-started) guide helpful for getting started with C++/WinRT.
