### ISSUE TITLE
"Microsoft accounts" can be an ambiguous term

### ISSUE THREAD

**Issue by WikkidEdd** [MicrosoftDocs/windows-uwp#2667]
"These are groups of specific customers, created from the email addresses associated with their Microsoft accounts."

Through a bit of testing, it appears that this feature doesn't support "Work or School" Microsoft accounts. If that is indeed the case, it could be made more explicit that it only works for personal Microsoft accounts and the Work or School accounts do not work.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 96b0cb0b-7d5e-cfd7-2bc4-071503570874
* Version Independent ID: f4d91bc4-6467-eca7-b9e3-e7316f24397b
* Content: [Create customer groups - UWP applications](https://docs.microsoft.com/en-gb/windows/uwp/publish/create-customer-groups)
* Content Source: [windows-apps-src/publish/create-customer-groups.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/publish/create-customer-groups.md)
* Product: **uwp**
* Technology: **publish**
* GitHub Login: @hickeys
* Microsoft Alias: **hickeys**

**Comment by GrantMeStrength** [comment]
We are changing the way we track issues filed from our documentation pages: please see this [blog post](https://techcommunity.microsoft.com/t5/microsoft-learn-blog/announcing-a-new-way-to-give-feedback-on-microsoft-learn/ba-p/4027635) for more details. The Microsoft Store documentation has been updated several times since your issue was reported, and there's a good chance your problem has been addressed. Right now, this issue is being closed but if you feel it is still valid and has not been addressed, please re-open it with any more available information. Please note that if you question is more general and not related to documentation, [Microsoft Q&A](https://learn.microsoft.com/en-us/answers/questions/) is a great way to get questions answered.
