### ISSUE TITLE
Image control become black sometimes

### ISSUE THREAD

**Issue by hupo376787** [MicrosoftDocs/windows-uwp#2670]
I'm using `Image` control in `ItemsRepeater`. The general XAML is like below.
```
<ScrollViewer>
   <ItemsRepeater> //vertical
      <StackPanel>
         <TextBlock/>
         <ItemsRepeater>//horizontal 
             <Image/>
         </ItemsRepeater>
      </StackPanel>
   </ItemsRepeater>
</ScrollViewer>
```

But sometimes, when I go to other pages and back, some `Image` control becomes black. I guess the image is disposed of by `Image` when navigating to other pages. But I'm not sure.
Are there any solutions?

![image](https://user-images.githubusercontent.com/14960168/91599543-1c29f000-e999-11ea-8757-2fc6c71766db.png)

**Comment by Karl-Bridge-Microsoft** [comment]
Hi @hupo376787 - This is not documentation feedback, but rather a support request. Please contact the following support channel.

- For developer issues, or suspected product bugs, contact [Microsoft Support](https://support.microsoft.com/contactus). A support engineer will look at the repro and see whether the issue is a Microsoft product bug, or something else. If it's a bug with a Microsoft product then the ticket will be free of charge.

Here are all of the developer support resources, for completeness.

- The [Feedback Hub app](https://support.microsoft.com/help/4021566/windows-10-send-feedback-to-microsoft-with-feedback-hub-app) is the right place to lobby for a change, a feature, or to make a suggestion.
- For community assistance with development questions, there are our [forums](https://social.msdn.microsoft.com/Forums/newthread?category=windowsapps&forum=wpdevelop&prof=required), and [StackOverflow](https://stackoverflow.com/questions).
- The [Windows developer support](https://developer.microsoft.com/windows/support) site explains other support options.
- The [Visual Studio developer community](https://developercommunity.visualstudio.com) is available, and responsive. The former User Voice feature is now there on the **Suggest a feature** tab, if you want to lobby for a change, a feature, or to make a suggestion.

If you receive assistance via any support resource, and you believe that information would help us improve the docs, then please come back and let us know.
