### ISSUE TITLE
What exactly is the meaning of the fourth number in the version?

### ISSUE THREAD

**Issue by mc0re** [MicrosoftDocs/windows-uwp#2680]
If the technical details are not supposed to be opened to the public, then please mention the purpose of changing it. I would very much like to know, what is the difference between versions `1.0.30.0` and `1.0.30.70` - when I only published `1.0.30.0`.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4b22af89-6a3d-ed21-8fc5-e0ffdce511de
* Version Independent ID: dd201571-1779-7c85-feb4-6cc2d8f3679e
* Content: [Package version numbering - UWP applications](https://docs.microsoft.com/en-us/windows/uwp/publish/package-version-numbering)
* Content Source: [windows-apps-src/publish/package-version-numbering.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/publish/package-version-numbering.md)
* Product: **uwp**
* Technology: **publish**
* GitHub Login: @hickeys
* Microsoft Alias: **hickeys**

**Comment by mc0re** [comment]
For those seeking the answer - I figure, "70" in the end of the version means "executed on XBox".

**Comment by GrantMeStrength** [comment]
We are changing the way we track issues filed from our documentation pages: please see this [blog post](https://techcommunity.microsoft.com/t5/microsoft-learn-blog/announcing-a-new-way-to-give-feedback-on-microsoft-learn/ba-p/4027635) for more details. The Microsoft Store documentation has been updated several times since your issue was reported, and there's a good chance your problem has been addressed. Right now, this issue is being closed but if you feel it is still valid and has not been addressed, please re-open it with any more available information. Please note that if you question is more general and not related to documentation, [Microsoft Q&A](https://learn.microsoft.com/en-us/answers/questions/) is a great way to get questions answered.
