### ISSUE TITLE
Webhook or api method to track subscription events (renew, cancel and etc.)

### ISSUE THREAD

**Issue by AlexMisiulia** [MicrosoftDocs/windows-uwp#2681]
Hi. I'm trying to synchronize subscription information between Microsoft Store and my database. Is there any way to subscribe to webhooks for subscription events like in other services (Apple, Google, Paddle, etc.)? I checked the docs, but didn't found anything for my use case. 

If this is not implemented what is the best way to cover my use case? I have these thoughts right now:
- Store user `b2bKey` in the database during the subscription creating
- Every day (or another period) run the method [getSubscriptionsForUser](https://docs.microsoft.com/en-us/windows/uwp/monetize/get-subscriptions-for-a-user) for each user and store updated subscription information in database.

Thank you!

**Comment by mcleanbyron** [comment]
Thanks for submitting your question. It seems you have a support related question. Unfortunately, that's outside of the scope of things we can offer a solution for via this documentation repo. Here are all of the developer support resources, for completeness.

- [Microsoft Q&A](https://docs.microsoft.com/answers/topics/uwp.html?sort=active&filter=all) offers relevant and timely answers to your technical problems from a community of experts and Microsoft engineers.
- For community assistance with development questions, there are our [forums](https://social.msdn.microsoft.com/Forums/newthread?category=windowsapps&forum=wpdevelop&prof=required), and [StackOverflow](https://stackoverflow.com/questions).
- The [Windows developer support](https://developer.microsoft.com/windows/support) site explains other support options.
- For developer issues, or suspected product bugs, there's [Microsoft Support](https://support.microsoft.com/contactus); a support engineer will look at the repro and see whether the issue is a Microsoft product bug, or something else. If it's a bug with a Microsoft product then the ticket will be free of charge.

If you receive assistance there, and you believe that information would help us improve the docs, we'd appreciate if you came back and let us know.
