### ISSUE TITLE
How to set a default for a theme resource only present in some versions of Windows?

### ISSUE THREAD

**Issue by mc0re** [MicrosoftDocs/windows-uwp#2685]
Some resources (e.g. `AppBarButtonContentHeight`) seem to be missing in older versions of *Windows* (in this case, it's not present in 1809 - at least, the runtime throws an exception). How can I add a default value for such a resource in case it is missing in a theme dictionary?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 204b712a-a1ec-eaa6-11a7-27ed289a6ef0
* Version Independent ID: 13825441-2c1c-4cba-9249-39d348bb83c6
* Content: [ThemeResource markup extension - UWP applications](https://docs.microsoft.com/en-us/windows/uwp/xaml-platform/themeresource-markup-extension)
* Content Source: [windows-apps-src/xaml-platform/themeresource-markup-extension.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/xaml-platform/themeresource-markup-extension.md)
* Product: **uwp**
* Technology: **platform**
* GitHub Login: @jwmsft
* Microsoft Alias: **jimwalk**

**Comment by jwmsft** [comment]
Hi, sorry for the delayed response to this issue. The feedback channel you're using here (_Send feedback about > This page_) is for feedback about the documentation in this topic. For example, if you find a typo or believe that the documentation in this topic is incorrect.

- For questions or assistance, we recommend you visit [Microsoft Q&A](https://docs.microsoft.com/answers/index.html) to post your question. 
- To engage with the XAML product team or file a product bug, you can click [_Send feedback about > This product_](https://github.com/microsoft/microsoft-ui-xaml/issues/new/choose) from the doc page. This will let you open an issue with the development team in the WinUI repo on GitHub.

I'll go ahead and close this issue now, since there's no action I can see to take in the documentation. You can always reply to a closed issue, or even re-open it if you feel it's been closed in error.
