### ISSUE TITLE
The example doesn't build

### ISSUE THREAD

**Issue by twhall-umich** [MicrosoftDocs/windows-uwp#2696]
[Windows 10 version 1909; Visual Studio 2019]

Greetings,

I've hit multiple issues trying to follow this example and build the application:

====================================================================
*  MyUWPApp fails to build:

1>------ Build started: Project: MyUWPApp, Configuration: Debug x64 ------
1>App.cpp
1>$(SolutionDir)\obj\x64\Debug\MyUWPApp\Generated Files\winrt\base.h(645,33): error C2131: expression did not evaluate to a constant
1>$(SolutionDir)\obj\x64\Debug\MyUWPApp\Generated Files\winrt\base.h(270,24): message : failure was caused by a read of an uninitialized symbol
1>$(SolutionDir)\obj\x64\Debug\MyUWPApp\Generated Files\winrt\base.h(270,24): message : see usage of '_GUID::Data1'
1>$(SolutionDir)\obj\x64\Debug\MyUWPApp\Generated Files\winrt\base.h(801): message : see reference to variable template 'const winrt::guid guid_v<IUnknown>' being compiled
1>$(SolutionDir)\obj\x64\Debug\MyUWPApp\Generated Files\winrt\base.h(1983): message : see reference to function template instantiation 'const winrt::guid &winrt::guid_of<To>(void) noexcept' being compiled
1>        with
1>        [
1>            To=IUnknown
1>        ]
1>$(SolutionDir)\obj\x64\Debug\MyUWPApp\Generated Files\winrt\base.h(2072): message : see reference to function template instantiation 'winrt::com_ptr<To> winrt::impl::as<To,winrt::impl::unknown_abi,0>(From *)' being compiled
1>        with
1>        [
1>            To=IUnknown,
1>            From=winrt::impl::unknown_abi
1>        ]
1>$(SolutionDir)\MyUWPApp\App.cpp(13): message : see reference to function template instantiation 'winrt::com_ptr<To> winrt::Windows::Foundation::IUnknown::as<IUnknown>(void) const' being compiled
1>        with
1>        [
1>            To=IUnknown
1>        ]
1>C:\Program Files (x86)\Windows Kits\10\bin\10.0.18362.0\XamlCompiler\Microsoft.Windows.UI.Xaml.Common.targets(482,5): error MSB4181: The "CompileXaml" task returned false but did not log an error.
1>Done building project "MyUWPApp.vcxproj" -- FAILED.
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========

The offending code is:

```
640]      template <typename T>
641]  #ifdef WINRT_IMPL_IUNKNOWN_DEFINED
642]  #ifdef __clang__
643]      inline const guid guid_v{ __uuidof(T) };
644]  #else
645]      inline constexpr guid guid_v{ __uuidof(T) };  //<- here
646]  #endif
647]  #else
648]      inline constexpr guid guid_v{};
649]  #endif

```

====================================================================
*  MyDesktopWin32App fails to find the "Generated Files" under MyUWPApp.  Is there a discrepancy between the Solution.props and the edited MyDesktopWin32.vcxproj settings for the location of the Generated Files?

Solution.props:
```
    <IntDir>$(SolutionDir)\obj\$(Platform)\$(Configuration)\$(MSBuildProjectName)\</IntDir>
    <OutDir>$(SolutionDir)\bin\$(Platform)\$(Configuration)\$(MSBuildProjectName)\</OutDir>
    <GeneratedFilesDir>$(IntDir)Generated Files\</GeneratedFilesDir>

```
MyDesktopWin32.vcxproj (edited per instructions):
```
  <!-- Configure these for your UWP project -->
  <PropertyGroup>
    <AppProjectName>MyUWPApp</AppProjectName>
  </PropertyGroup>
  <PropertyGroup>
    <AppIncludeDirectories>$(SolutionDir)\obj\$(Platform)\$(Configuration)\$(AppProjectName)\;$(SolutionDir)\obj\$(Platform)\$(Configuration)\$(AppProjectName)\Generated Files\;</AppIncludeDirectories>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\$(AppProjectName)\$(AppProjectName).vcxproj" />
  </ItemGroup>
  <!-- End Section-->

```
It appears that MyDesktopWin32 is looking in its own empty "Generated Files" folder.

I was able to fix that by changing the Solution.props:
```
    <!-- GeneratedFilesDir>$(IntDir)Generated Files\</GeneratedFilesDir -->
    <GeneratedFilesDir>$(SolutionDir)\obj\$(Platform)\$(Configuration)\MyUWPApp\Generated Files\</GeneratedFilesDir>


```---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f62891dc-cad0-0ea2-66c3-a5b58d9e3f9a
* Version Independent ID: 911ab9f0-1c11-b2bf-9ecf-9fbed29df211
* Content: [Host a custom UWP control in a C++ Win32 app using the XAML Hosting API](https://docs.microsoft.com/en-us/windows/apps/desktop/modernize/host-custom-control-with-xaml-islands-cpp)
* Content Source: [hub/apps/desktop/modernize/host-custom-control-with-xaml-islands-cpp.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/hub/apps/desktop/modernize/host-custom-control-with-xaml-islands-cpp.md)
* Product: **uwp**
* Technology: **apps**
* GitHub Login: @mcleanbyron
* Microsoft Alias: **mcleans**

**Comment by mcleanbyron** [comment]
I'm sorry you're running into errors when trying to complete this walkthrough. I just tested it twice and was able to successfully complete it without errors each time. I took a look at the Solution.props entries and the <AppIncludeDirectories> element in the MyDesktopWin32.vcxproj file you're referring to, and the specified values look correct to me. 

* The entries in the Solution.props file are added to each project in a later step, and the $(MSBuildProjectName) will expand to the subfolder for each project during build time. 
* As for the <AppIncludeDirectories> element in the MyDesktopWin32.vcxproj file, note that each of the paths specified in this element include the $(AppProjectName) variable, which should expand to the "MyUWPApp" subfolder at build time. On my computer, this expands to C:\Users\<my folder>\source\repos\MyDesktopWin32App\obj\Win32\Debug\MyUWPApp\Generated Files, which contains several many generated files from the build process.

Unfortunately, because I cannot reproduce the errors you are reporting, my only guidance is to try it again and make sure you are not missing any important steps. One thing you might check: make sure that in the [Configure your solution](https://docs.microsoft.com/en-us/windows/apps/desktop/modernize/host-custom-control-with-xaml-islands-cpp#configure-the-solution) section, make sure in step 5 that you're selecting the Solution.props file in the solution folder. The MyUWPApp project folder also has its own different .props file.
