### ISSUE TITLE
Example Question: Does it make sense to iterate through a vector when each item is the same?

### ISSUE THREAD

**Issue by SetTrend** [MicrosoftDocs/windows-uwp#2701]
At [Retrieve pointer properties](https://docs.microsoft.com/en-us/windows/uwp/design/input/identify-input-devices#retrieve-pointer-properties) it reads:

> Note  The values returned by the properties discussed here are based on all detected pointer devices: Boolean properties return non-zero if at least one device supports a specific capability, and numeric properties return the maximum value exposed by any one pointer device.

So ...

```c#
IReadOnlyList<PointerDevice> pointerDevices = Windows.Devices.Input.PointerDevice.GetPointerDevices();
```
... returns a list of [`PointerDevice`](https://docs.microsoft.com/en-us/uwp/api/Windows.Devices.Input.PointerDevice) objects, and each and every object in this list returns the same information?

Why should it make sense to iterate through this list then, if each item in the iteration returns the same values?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1641e1a8-9b76-2985-3e12-49e20b79581d
* Version Independent ID: 30097945-bda2-fd54-9f39-871a79aac7f8
* Content: [Identify input devices - UWP applications](https://docs.microsoft.com/en-us/windows/uwp/design/input/identify-input-devices#retrieve-pointer-properties)
* Content Source: [windows-apps-src/design/input/identify-input-devices.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/design/input/identify-input-devices.md)
* Product: **uwp**
* Technology: **design**
* GitHub Login: @Karl-Bridge-Microsoft
* Microsoft Alias: **kbridge**

**Comment by Karl-Bridge-Microsoft** [comment]
Hi @SetTrend - This is not documentation feedback, but rather a support request. Please contact the following support channel.

- For community assistance with development questions, there are our [forums](https://social.msdn.microsoft.com/Forums/newthread?category=windowsapps&forum=wpdevelop&prof=required), and [StackOverflow](https://stackoverflow.com/questions).

Here are all of the developer support resources, for completeness.

-The [Feedback Hub app](https://support.microsoft.com/help/4021566/windows-10-send-feedback-to-microsoft-with-feedback-hub-app) is the right place to lobby for a change, a feature, or to make a suggestion.
- For developer issues, or suspected product bugs, contact [Microsoft Support](https://support.microsoft.com/contactus). A support engineer will look at the repro and see whether the issue is a Microsoft product bug, or something else. If it's a bug with a Microsoft product then the ticket will be free of charge.
- The [Windows developer support](https://developer.microsoft.com/windows/support) site explains other support options.
- The [Visual Studio developer community](https://developercommunity.visualstudio.com) is available, and responsive. The former User Voice feature is now there on the **Suggest a feature** tab, if you want to lobby for a change, a feature, or to make a suggestion.

If you receive assistance via any support resource, and you believe that information would help us improve the docs, then please come back and let us know.
