### ISSUE TITLE
is Windows Graphics Capture API return such as DXGI_OUTDUPL_FRAME_INFO(LastPresentTime,LastMouseUpdateTime)

### ISSUE THREAD

**Issue by chllcy** [MicrosoftDocs/windows-uwp#2704]
hi,I'm used dxgi to capture the windows screen, but it draw cursor on the texture2d too slow with DrawIconEx.
and I find windows graphics capture can capture cursor,but there is some problem. it can't detect the image change or cursor change(such as LastPresentTime,LastMouseUpdateTime),so I can't filter the duplicate frames.Is there any other way?thanks

**Comment by drewbatgit** [comment]
Hello, GitHub issues in this repository are for feedback specifically about the documentation. It seems like your issue is a developer support request. Here are all of the developer support resources:

- The [Microsoft Q&A](https://docs.microsoft.com/en-us/answers/products/) site is the home for technical questions and answers at Microsoft.
- The [Feedback Hub app](https://support.microsoft.com/help/4021566/windows-10-send-feedback-to-microsoft-with-feedback-hub-app) is the right place to lobby for a change, a feature, or to make a suggestion.
- For community assistance with development questions, there are our [forums](https://social.msdn.microsoft.com/Forums/newthread?category=windowsapps&forum=wpdevelop&prof=required), and [StackOverflow](https://stackoverflow.com/questions).
- The [Windows developer support](https://developer.microsoft.com/windows/support) site explains other support options.
- The [Visual Studio developer community](https://developercommunity.visualstudio.com) is available, and responsive. The former User Voice feature is now there on the **Suggest a feature** tab, if you want to lobby for a change, a feature, or to make a suggestion.
- For developer issues, or suspected product bugs, there's [Microsoft Support](https://support.microsoft.com/contactus); a support engineer will look at the repro and see whether the issue is a Microsoft product bug, or something else. If it's a bug with a Microsoft product then the ticket will be free of charge.

If you receive assistance via any support resource, and you believe that information would help us improve the documentation, then please come back and let us know.
