### ISSUE TITLE
DevCenter Analytics Returning HTTP 429 Error Code

### ISSUE THREAD

**Issue by kennywyland** [MicrosoftDocs/windows-uwp#2705]
I can't find the right place to report this, so this is the best I can do. Please help. 

We sell Windows apps on the Windows App Store and we download our sales each day using the [Acquisitions API](https://docs.microsoft.com/en-us/windows/uwp/monetize/acquisitions-data). We only make 2 requests per DAY (one for app acquisitions and one for in-app acquisitions), but we're getting a 429 Error Code which is supposed to mean Too Many Requests, as if we're hitting a rate limit. 

IOException: Server returned HTTP response code: 429 for URL: https://manage.devcenter.microsoft.com/v1.0/my/analytics/inappacquisitions?startDate=09%2F14%2F2020&endDate=09%2F14%2F2020&top=1000&skip=0&inAppProductId=XXXXXXXXXXX&

(with my real app product id in place of the Xs)

It seems to work when I run the code from my development desktop machine, but not when I run it from our production server.

**Comment by hkhmsft** [comment]
Hey @kennywyland , have you tried reaching out to [Microsoft Support](https://support.microsoft.com/contactus)? I'm thinking this is your best bet; a support engineer will look at the repro and see whether the issue is a Microsoft product bug, or something else. [Microsoft Q&A](https://docs.microsoft.com/answers/topics/uwp.html?sort=active&filter=all) also offers relevant and timely answers to technical problems from a community of experts and Microsoft engineers.

Because this is not a specific documentation fix, I'm marking the thread as Closed. But feel free to treat this as open and reply with any additional questions.
