### ISSUE TITLE
Please change the view on mouse support for apps

### ISSUE THREAD

**Issue by Pschirki** [MicrosoftDocs/windows-uwp#2708]
Xbox users love their controllers. For gaming. Seems like you missed that. Especially browser devs should have the possibillity to let their software be navigated by mouse, as it's a real pain in the ass when you try to navigate with the controller in one hand and write on keyboard with the other hand. 

And as you can see at [XBOX Requests,](https://www.reddit.com/r/xboxinsiders/comments/iqt1si/xbox_requests_week_of_september_11th_2020/) i am not the only one waiting for a change to the better!

I hope to get some feedback on this please!

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ca17d8c8-4d20-e6ea-23ec-096a5cea88f8
* Version Independent ID: 4391d163-d6db-a995-4539-cc971230ec88
* Content: [Xbox best practices - UWP applications](https://docs.microsoft.com/en-us/windows/uwp/xbox-apps/tailoring-for-xbox#feedback)
* Content Source: [windows-apps-src/xbox-apps/tailoring-for-xbox.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/xbox-apps/tailoring-for-xbox.md)
* Product: **uwp**
* Technology: **games**
* GitHub Login: @M-Stahl
* Microsoft Alias: **kevinasg**

**Comment by Karl-Bridge-Microsoft** [comment]
Hi @Pschirki - This is not documentation feedback, but rather a support request. Please contact the following support channel.

-The [Feedback Hub app](https://support.microsoft.com/help/4021566/windows-10-send-feedback-to-microsoft-with-feedback-hub-app) is the right place to lobby for a change, a feature, or to make a suggestion.

Here are all of the developer support resources, for completeness.

- For developer issues, or suspected product bugs, contact [Microsoft Support](https://support.microsoft.com/contactus). A support engineer will look at the repro and see whether the issue is a Microsoft product bug, or something else. If it's a bug with a Microsoft product then the ticket will be free of charge.
- For community assistance with development questions, there are our [forums](https://social.msdn.microsoft.com/Forums/newthread?category=windowsapps&forum=wpdevelop&prof=required), and [StackOverflow](https://stackoverflow.com/questions).
- The [Windows developer support](https://developer.microsoft.com/windows/support) site explains other support options.
- The [Visual Studio developer community](https://developercommunity.visualstudio.com) is available, and responsive. The former User Voice feature is now there on the **Suggest a feature** tab, if you want to lobby for a change, a feature, or to make a suggestion.

If you receive assistance via any support resource, and you believe that information would help us improve the docs, then please come back and let us know.
