### ISSUE TITLE
DirectCompute 404 Hyperlink.

### ISSUE THREAD

**Issue by codenameone-akshat** [MicrosoftDocs/windows-uwp#2709]
The **DirectCompute** link is missing(404).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2ba6c679-c622-5e64-363f-567efbe650aa
* Version Independent ID: 56dd0f71-899d-9684-c570-46b46cfb19ca
* Content: [Compute Shader (CS) stage - UWP applications](https://docs.microsoft.com/en-us/windows/uwp/graphics-concepts/compute-shader-stage--cs-)
* Content Source: [windows-apps-src/graphics-concepts/compute-shader-stage--cs-.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/graphics-concepts/compute-shader-stage--cs-.md)
* Product: **uwp**
* Technology: **platform**
* GitHub Login: @stevewhims
* Microsoft Alias: **stwhi**

**Comment by stevewhims** [comment]
Hi, @codenameone-akshat, and thanks for filing this issue. Since the blog post is now out of date, and can't be found (the ephemeral nature of blog posts is one reason we don't link to them very often), I've removed the link to it. Instead I've made it clear that "Compute shader technology" and "DirectCompute technology" are more or less synonymous, and I've added a link to the Win32 content that describes the technology in more details.

These changes are now live, so I'll go ahead and close the issue.

Thanks again!
Steve
