### ISSUE TITLE
Why???? Mouse mode is only supported on Xbox One with gamepad/remote. On other device families and input types it is silently ignored.

### ISSUE THREAD

**Issue by Pschirki** [MicrosoftDocs/windows-uwp#2711]
Since the XBOX Console has mouse support for over a year now, this "silent ignoration" should be  deactivated please, at least for browser apps on XBOX..

And as you can see at [XBOX Requests,](https://www.reddit.com/r/xboxinsiders/comments/iqt1si/xbox_requests_week_of_september_11th_2020/) i am not the only one waiting for a change to the better!

I hope to get some feedback on this please!
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cc1368ed-19ff-b8d4-1718-86448d4d7658
* Version Independent ID: 02d037c4-5c42-64c0-7de5-28fb7b21305f
* Content: [Gamepad and remote control interactions - UWP applications](https://docs.microsoft.com/en-us/windows/uwp/design/input/gamepad-and-remote-interactions#mouse-mode)
* Content Source: [windows-apps-src/design/input/gamepad-and-remote-interactions.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/design/input/gamepad-and-remote-interactions.md)
* Product: **uwp**
* Technology: **design**
* GitHub Login: @Karl-Bridge-Microsoft
* Microsoft Alias: **kbridge**

**Comment by Karl-Bridge-Microsoft** [comment]
Hi @Pschirki - This is not documentation feedback, but rather a support request. Please contact the following support channel.

-The [Feedback Hub app](https://support.microsoft.com/help/4021566/windows-10-send-feedback-to-microsoft-with-feedback-hub-app) is the right place to lobby for a change, a feature, or to make a suggestion.

Here are all of the developer support resources, for completeness.

- For developer issues, or suspected product bugs, contact [Microsoft Support](https://support.microsoft.com/contactus). A support engineer will look at the repro and see whether the issue is a Microsoft product bug, or something else. If it's a bug with a Microsoft product then the ticket will be free of charge.
- For community assistance with development questions, there are our [forums](https://social.msdn.microsoft.com/Forums/newthread?category=windowsapps&forum=wpdevelop&prof=required), and [StackOverflow](https://stackoverflow.com/questions).
- The [Windows developer support](https://developer.microsoft.com/windows/support) site explains other support options.
- The [Visual Studio developer community](https://developercommunity.visualstudio.com) is available, and responsive. The former User Voice feature is now there on the **Suggest a feature** tab, if you want to lobby for a change, a feature, or to make a suggestion.

If you receive assistance via any support resource, and you believe that information would help us improve the docs, then please come back and let us know.
