### ISSUE TITLE
Issues with starting up my new Microsoft Store Account

### ISSUE THREAD

**Issue by LenYates** [MicrosoftDocs/windows-uwp#2717]
Hello,

Today I started a Store Account and paid the $99 fee.  Microsoft sent me an email to verify my e-mail address.  I clicked the link in the e-mail but it did not function correctly.  

In another e-mail from Microsoft, you invited me to reserve a name for my app, but this link did not take me to a place where I could do so.  I spent 15+ minutes fishing around in your web pages but never found the place where I could enter the name of my app.   Tons of pages with instructions and explanations, but never any page where I could actually get going.

I'll need to have some help pretty soon, or else I'm going to give up and ask for my $99 back.

Leonard Yates
lyates709@gmail.com

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8ef171c5-88d6-8133-d812-5c21267fb52a
* Version Independent ID: c25a2364-0502-03c7-cb2a-69faee046a24
* Content: [App resources and the Resource Management System - UWP applications](https://docs.microsoft.com/en-us/windows/uwp/app-resources/)
* Content Source: [windows-apps-src/app-resources/index.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/app-resources/index.md)
* Product: **uwp**
* Technology: **data-and-files**
* GitHub Login: @lastnameholiu
* Microsoft Alias: **alholiu**

**Comment by hkhmsft** [comment]
Thanks for taking the time to let us know about this. However, this feels not so much like feedback specifically about the documentation, but rather like a support request. Unfortunately, I cannot assist you with your current issue. Here are all of the developer support resources, for completeness.

- [Microsoft Q&A](https://docs.microsoft.com/en-us/answers/topics/windows-uwp.html) offers relevant and timely answers to your technical problems from a community of experts and Microsoft engineers.
- For community assistance with development questions, there are our [forums](https://social.msdn.microsoft.com/Forums/newthread?category=windowsapps&forum=wpdevelop&prof=required), and [StackOverflow](https://stackoverflow.com/questions).
- The [Windows developer support](https://developer.microsoft.com/windows/support) site explains other support options.
- The [Visual Studio developer community](https://developercommunity.visualstudio.com) is available, and responsive. The former User Voice feature is now there on the **Suggest a feature** tab, if you want to lobby for a change, a feature, or to make a suggestion.
- For developer issues, or suspected product bugs, there's [Microsoft Support](https://support.microsoft.com/contactus); a support engineer will look at the repro and see whether the issue is a Microsoft product bug, or something else. If it's a bug with a Microsoft product then the ticket will be free of charge.

If you receive assistance via any of these support resources, and you believe that information would help us improve the docs, then please come back and let us know.
