### ISSUE TITLE
Write One line at a time to txt file

### ISSUE THREAD

**Issue by ghd796** [MicrosoftDocs/windows-uwp#2722]
How do you write a new line each time you write to a text file instead of it just adding to the end of the previous line written [UWP} c#

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f09fb804-bc3e-ad66-d52d-c33f1cdda0ed
* Version Independent ID: 9b0a2d87-65f9-7b80-73a6-29d5a4c80ba1
* Content: [Create, write, and read a file - UWP applications](https://docs.microsoft.com/en-us/windows/uwp/files/quickstart-reading-and-writing-files?source=docs)
* Content Source: [windows-apps-src/files/quickstart-reading-and-writing-files.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/files/quickstart-reading-and-writing-files.md)
* Product: **uwp**
* Technology: **data-and-files**
* GitHub Login: @lastnameholiu
* Microsoft Alias: **alholiu**

**Comment by hkhmsft** [comment]
Thanks for taking the time to let us know about this. It seems your Issue leans more towards product question rather than specific documentation fixes. 

May I suggest that you direct your question over at [Microsoft Q&A](https://docs.microsoft.com/en-us/answers/topics/windows-uwp.html)? The community of experts and Microsoft engineers can provide timely answers to your technical questions. If you do create a thread over at Microsoft Q&A, it would be fantastic if you could share that link here so I can track the progress and potentially incorporate the technical details into our documentation.

Though I'm marking this Issue as closed now, please treat this thread as an open thread for follow-ups. Thanks!
