### ISSUE TITLE
Error Code 2201

### ISSUE THREAD

**Issue by violetskyzz** [MicrosoftDocs/windows-uwp#2729]
While Registering for a Microsoft Partner Center Account I filled out all information required. When I click "next" I receive Error code 2201. Correlation ID [90cd6f76-aeba-424f-9703-4ca05a9821c5,C6jNu8ZEWkeFbrmv.0.0.] 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fc9d4d96-2865-5f2d-8737-66fe44db7cce
* Version Independent ID: 239560a3-7506-bb73-b436-6eec162e5196
* Content: [Account types, locations, and fees - UWP applications](https://docs.microsoft.com/en-us/windows/uwp/publish/account-types-locations-and-fees)
* Content Source: [windows-apps-src/publish/account-types-locations-and-fees.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/publish/account-types-locations-and-fees.md)
* Product: **uwp**
* Technology: **publish**
* GitHub Login: @hickeys
* Microsoft Alias: **hickeys**

**Comment by hkhmsft** [comment]
This feels not so much like feedback specifically about the documentation, but rather like a support request. Here are all of the developer support resources, for completeness.

- [Microsoft Q&A](https://docs.microsoft.com/answers/topics/uwp.html?sort=active&filter=all) offers relevant and timely answers to your technical problems from a community of experts and Microsoft engineers.
- For community assistance with development questions, there are our [forums](https://social.msdn.microsoft.com/Forums/newthread?category=windowsapps&forum=wpdevelop&prof=required), and [StackOverflow](https://stackoverflow.com/questions).
- The [Windows developer support](https://developer.microsoft.com/windows/support) site explains other support options.
- The [Visual Studio developer community](https://developercommunity.visualstudio.com) is available, and responsive. The former User Voice feature is now there on the **Suggest a feature** tab, if you want to lobby for a change, a feature, or to make a suggestion.
- For developer issues, or suspected product bugs, there's [Microsoft Support](https://support.microsoft.com/contactus); a support engineer will look at the repro and see whether the issue is a Microsoft product bug, or something else. If it's a bug with a Microsoft product then the ticket will be free of charge.

If you receive assistance via any of these support resources, and you believe that information would help us improve the docs, then please come back and let us know.
