### ISSUE TITLE
credit issue 103 created a 404 in life when i aplied for a credit card that destroyed a server of a bank that i had to fix.

### ISSUE THREAD

**Issue by gardmkdg1** [MicrosoftDocs/windows-uwp#2745]
I think data binding is being used to target people and they are getting sick cause their credit is no good or something.
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cb6d0294-8ced-a7c7-9f73-f1ee7c46ed74
* Version Independent ID: 3848a55e-3f34-36df-d23f-4446093a625e
* Content: [Data binding - UWP applications](https://docs.microsoft.com/en-us/windows/uwp/data-binding/)
* Content Source: [windows-apps-src/data-binding/index.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/data-binding/index.md)
* Product: **uwp**
* Technology: **data-and-files**
* GitHub Login: @lastnameholiu
* Microsoft Alias: **alholiu**

**Comment by lastnameholiu** [comment]
Thanks for taking the time to let us know about this. It seems your Issue leans more towards product feedback rather than specific documentation fixes. 

May I suggest that you direct your question over at [Microsoft Q&A](https://docs.microsoft.com/en-us/answers/topics/windows-uwp.html)? The community of experts and Microsoft engineers can provide timely responses to your technical feedback. Thanks!
