### ISSUE TITLE
Windows Hello Integration does not Address Office/AAD Use

### ISSUE THREAD

**Issue by laultman** [MicrosoftDocs/windows-uwp#2749]
**This article is OLD - 2016**. It hardly applies to real use and does not even attempt to cover applications that are built to use Azure services and AAD as the "server" of credentials. The integration is convoluted. If this article does cover this integration then it totally fails at describing the process. 
Consider HoloLens 2 - this is a Windows 10 device and UWP. There is no keyboard/mouse and it is not practical to even think about a login MFA experience with the built in capability of HoloLens 2.
There MUST be a way to use Hello on tablets and devices not equipped for keyboard/mouse.
This article should be updated and expanded to include "modern" Windows and cloud use. At least a new section should be developed and added to address implement the "Passwordless" application.
The sample referenced in the Overview are VS2015 - [Here](https://github.com/Microsoft/Windows-universal-samples/tree/master/Samples/MicrosoftPassport). Typical Microsoft - write once and forget! Nobody would use this model today.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4b1a69a3-81e8-4ef3-e928-6cf348d402c3
* Version Independent ID: 395b9716-26fa-c43a-6f45-a691b729f3ff
* Content: [Create a Windows Hello login app - UWP applications](https://docs.microsoft.com/en-us/windows/uwp/security/microsoft-passport-login)
* Content Source: [windows-apps-src/security/microsoft-passport-login.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/security/microsoft-passport-login.md)
* Product: **uwp**
* Technology: **platform**
* GitHub Login: @hickeys
* Microsoft Alias: **hickeys**

**Comment by alvinashcraft** [comment]
Thanks for submitting your feedback and we apologize for the delayed response. I see that updates have not been made since the creation of this Issue, so I went ahead and created an internal work item to incorporate your suggestions for the new Windows Hello docs for WinUI apps. The timeline for this may vary, so I will go ahead and close this and circle back when the changes are live. 

Though the Issue will be marked as Closed, we will monitor any replies that come afterwards so treat this like an open Issue. Many thanks!
