### ISSUE TITLE
Old Out of Date - 

### ISSUE THREAD

**Issue by laultman** [MicrosoftDocs/windows-uwp#2750]
Unusable, does not reflect shipping versions of Windows, or Visual Studio.
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d504f58b-e998-291d-2bf0-fd8925ca9a61
* Version Independent ID: 04fb7b13-7fbb-181f-b111-2f1c0525b94c
* Content: [Windows Hello - UWP applications](https://docs.microsoft.com/en-us/windows/uwp/security/microsoft-passport)
* Content Source: [windows-apps-src/security/microsoft-passport.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/security/microsoft-passport.md)
* Product: **uwp**
* Technology: **platform**
* GitHub Login: @hickeys
* Microsoft Alias: **hickeys**

**Comment by alvinashcraft** [comment]
Thanks for submitting your feedback and we apologize for the delayed response. I see that updates have not been made since the creation of this Issue, so I went ahead and created an internal work item to create a version of these docs for WinUI and the Windows App SDK. The timeline for this may vary, so I will go ahead and close this and circle back when the changes are live. 

Though the Issue will be marked as Closed, we will monitor any replies that come afterwards so treat this like an open Issue. Many thanks!
