### ISSUE TITLE
ms-settings:easeofaccess-cursorandpointersize not working

### ISSUE THREAD

**Issue by wldevries** [MicrosoftDocs/windows-uwp#2754]
`ms-settings:easeofaccess-cursorandpointersize` does not open the settings page "Cursor & pointer size". Instead it opens the start page of the Settings app. This used to work on earlier versions of Windows 10.

OS version: Windows 10 Pro version 2004

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 987ec16c-9456-93a4-177a-dbd563be7eb7
* Version Independent ID: f41f0344-f7f6-f092-a6bf-fc4184a9b460
* Content: [Launch the Windows Settings app - UWP applications](https://docs.microsoft.com/en-us/windows/uwp/launch-resume/launch-settings-app)
* Content Source: [windows-apps-src/launch-resume/launch-settings-app.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/launch-resume/launch-settings-app.md)
* Product: **uwp**
* Technology: **processes-and-threading**
* GitHub Login: @lastnameholiu
* Microsoft Alias: **alholiu**

**Comment by GrantMeStrength** [comment]
We are changing the way we track issues filed from our documentation pages: please see this [blog post](https://techcommunity.microsoft.com/t5/microsoft-learn-blog/announcing-a-new-way-to-give-feedback-on-microsoft-learn/ba-p/4027635) for more details. Right now, this issue is being closed but if you feel it is still valid and has not been addressed, please re-open it with any more available information. Please note that if your question is more general and not related to documentation, [Microsoft Q&A](https://learn.microsoft.com/en-us/answers/questions/) is a great way to get questions answered.
