### ISSUE TITLE
nvm is not compatible with the npm config "prefix" option: currently set to "/mnt/c/nodejs/node_global"

### ISSUE THREAD

**Issue by xianghongai** [MicrosoftDocs/windows-uwp#2762]
Each time I start Terminal Tips:

```
nvm is not compatible with the npm config "prefix" option: currently set to "/mnt/c/nodejs/node_global"
Run `npm config delete prefix` or `nvm use --delete-prefix v12.19.0 --silent` to unset it.
```

Linux version 4.19.128-microsoft-standard (oe-user@oe-host) (gcc version 8.2.0 (GCC)) #1 SMP Tue Jun 23 12:58:10 UTC 2020
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.1 LTS
Release:        20.04
Codename:       focal

![2020-10-17-143343](https://user-images.githubusercontent.com/2075006/96330173-cbc03c00-1085-11eb-926b-5ac6bb0aaf40.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c6995595-66c4-f26a-b307-89a068b4b5ba
* Version Independent ID: 69400ed1-5d98-4d6e-47a3-5c409564e77d
* Content: [Set up NodeJS on WSL 2](https://docs.microsoft.com/en-us/windows/nodejs/setup-on-wsl2)
* Content Source: [hub/nodejs/setup-on-wsl2.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/hub/nodejs/setup-on-wsl2.md)
* Product: **dev-environment**
* Technology: **windows-nodejs**
* GitHub Login: @mattwojo
* Microsoft Alias: **mattwoj**

**Comment by mattwojo** [comment]
Thanks for raising this issue @xianghongai. The solution suggested on StackOverflow is to follow the suggestion listed in the terminal tip to [Delete and Reset the prefix](https://stackoverflow.com/questions/34718528/nvm-is-not-compatible-with-the-npm-config-prefix-option). Have you tried this? 
I don't think this issue is specific to a WSL context, so I'm not sure that it's something to include in this specific doc.. though if I'm wrong and this is specific to the WSL context, please let me know.
