### ISSUE TITLE
Add settings docs for Winget

### ISSUE THREAD

**Issue by ghost** [MicrosoftDocs/windows-uwp#2763]
Exactly what the title says. Like the documentation Windows Terminal settings

cc @denelon

**Comment by mcleanbyron** [comment]
Thanks for your feedback. The engineering team that owns Windows Package Manager and the winget client tool confirmed that for now the currently available settings are documented on the open source GitHub repo for the tool at https://aka.ms/winget-settings. Due to the preview state of the tool, the settings are still in an experimental state and not finalized. We’ll document the settings in the official docs after the settings are finalized. For now, I added a brief section to the winget overview article with a link to the currently available settings docs.
