### ISSUE TITLE
Move to C++/WinRT from MFC

### ISSUE THREAD

**Issue by dr-eck** [MicrosoftDocs/windows-uwp#2769]
The sections on Moving to C++/WinRT from C++/CX and C# look like they would be great for most folks, but some of us have been trying to stick to vanilla C++, so we've been stuck with MFC for a very long time.  Kenny Kerr appears to be making a way for us to get up to date, but the learning curve is really steep.  How about adding documentation for "Moving to C++/WinRT from MFC"?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 69a5ba76-77cf-1233-2903-fd3c34b5044c
* Version Independent ID: 163d07f1-7860-cd16-a572-ff429cdf7008
* Content: [C++/WinRT - UWP applications](https://docs.microsoft.com/en-us/windows/uwp/cpp-and-winrt-apis/)
* Content Source: [windows-apps-src/cpp-and-winrt-apis/index.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/cpp-and-winrt-apis/index.md)
* Product: **uwp**
* Technology: **platform**
* GitHub Login: @stevewhims
* Microsoft Alias: **stwhi**

**Comment by stevewhims** [comment]
Hi, @dr-eck, and thanks for filing this issue. This additional content is certainly something I'd be willing to create, but it's really a matter of priority, so I'll take it upon myself to pursue this internally, and see what can be done. Meanwhile, I'm curious which aspects of your use of MFC that you're (most) interested in updating. Are you thinking of moving away from the GDI and USER aspects of Win32 apps entirely, and perhaps using UWP/WinRT/XAML/WinUI instead? Or sticking with MFC and just removing dependencies on the MFC runtime? Do you have any interest in using any of the DirectX-related technologies for your UI? Have you begun to port from MFC to C++/WinRT, and you've run into any specific issues already? Any info of this sort will help.

Thank you!
Steve

**Comment by dr-eck** [comment]
Hi Steve,

            Thanks for getting back to me.  You asked questions, so I’ll do my best to provide answers.

I understand your point about priorities.  For me, the priority is high because almost all of the Microsoft documentation assumes that the reader has been using the non-standard C++ extensions Microsoft introduced over the last decade or so (C++/CLI, C++/CX…) and is familiar with XAML and the Windows API.  This assumption is not good for those of us who have chosen to stick with standard C++, and have been stuck with MFC.  It also doesn’t work for people who have never done Windows programming before.

            I am ready to drop everything to do with MFC as soon as possible.  This means that WinUI 3.0 and its ability to create desktop apps is crucial.  WinRT is a huge deal for standard C++ users wanting to work with WinUI.  And XAML tooling appears to be a robust way to generate the UI.  So the Desktop/WinRT/XAML/WinUI stack looks like the way to go.

            The applications I’m working on are small, and mostly used internally.  Three of them involve capturing video from one or more cameras, manipulating the frames using OpenCV, and displaying the results.  Some of the cameras are UVC and others are GenICam, so I’m sure I’ll still have to dig into a lot of details, but the UWP camera samples look very promising.  For now, I’m having to deal with DirectShow and Media Foundation for camera enumeration and frame capture, which is a pain.  And the only way I’ve found to display smooth video is with Direct2D, so I guess I’m using DirectX-related technologies for my UI.  A fourth program involves heavy-duty number crunching (ray tracing and matrix operations), with a UI that is mostly ribbonbar, spreadsheets and line plots.  I expect this program to be easy to port.

            At this point, I have several failed attempts at beginning to port from MFC to C++/WinRT.  My current approach is to work my way through Petzold’s “Programming Windows, 6th ed.”, and replicate all of his examples using C++/WinRT.  It’s almost tempting to rewrite the book as I go, but writing a book is more work than I can add to my plate right now.

            I hope this wasn’t too long.  Let me know if you want more information.

 

Best regards,

Steve Eckhardt

 <mailto:steve@eckop.com> steve@eckop.com

651-315-8249

Eckhardt Optics LLC

http://www.eckop.com

**Comment by stevewhims** [comment]
Hi, @dr-eck (Steve), and thanks for the additional context there. I think you're doing the right thing working through Programming Windows 6ed, since that will get you ramped up on XAML, which is certainly a big (possibly the biggest) piece when you're moving to developing apps for Windows 10, and is of course the precursor (and close relative) to WinUI.

Moving to C++/WinRT seems like the intuitive choice from MFC (since C++/WinRT is standard C++, with no language extensions). But there's also the option of moving to another language, perhaps C#. Yes, going with C++ would mean going with the same core language. But on the other hand much of the move to modern apps is about the change in approach, mindset, architecture, frameworks, especially UI. And C#, while perhaps not as performant, does have many productivity and convenience features (especially when it comes to XAML). The kinds of things it's easy to take for granted when you're developing with C#, but that can be painful gaps in the C++ story. Something to consider.

In terms of actual content about porting MFC => C++/WinRT, that's going to have to go on to my backlog. From asking around, I haven't detected much of a sense of it being a priority, as we talked about, so I don't have any scheduled date for that. So, I'll go ahead and close this issue since I usually only keep these open while I'm actively investigating, and until the item goes onto my backlog.

Thanks, and sorry I couldn't give a better answer here!
-Steve

**Comment by dr-eck** [comment]
Hi @stevewhims,  Thanks for the response.  I'm not surprised that this is low priority.  My major effort is on a program that uses Intel's Math Kernel Library and intrinsics, so C# really doesn't seem like the way to go for this project.  I was amazed to see that C# supports intrinsics, but I suspect that Intel's MKL would be more problematic.

**Comment by stevewhims** [comment]
I see, that makes sense!

Thanks!
Steve
