### ISSUE TITLE
Single wide activebutton centered

### ISSUE THREAD

**Issue by Mavix42** [MicrosoftDocs/windows-uwp#2807]
Hey, first of all i wanna say how awesome the notificationcenter got and how complex you can design new whole notification menus!!!
Im only missing one thing. I want to implement a single ToastButton on (almost all of) my notifications that redirects the user to (a certain point of) my application. I am well aware that just clicking the notification does the same thing but i still want to implement it.
The button should be displayed centered over the entire length.
Currently all Buttons i tried were placed right-justified half the length of the toast.
Am i doing it wrong? 
Did you not implement it on purpose and if yes why?

**Comment by hkhmsft** [comment]
Hi @Mavix42 , it seems your Issue leans is more of a product question rather than a specific documentation fixes. Your best bet is to direct your question over at [Microsoft Q&A](https://docs.microsoft.com/en-us/answers/topics/windows-uwp.html)? The community of experts and Microsoft engineers can provide timely answers to your technical questions. Thanks!
