### ISSUE TITLE
Is asking for donations on apps directly from users allowed?

### ISSUE THREAD

**Issue by Path2Freedom** [MicrosoftDocs/windows-uwp#2808]
Hi,
I am an UWP developer and I am about to publish a "free" application on Windows 10 Store. However, I would like to ask users for donations to support my work for UWP platform through PayPal or other such means. I would like to know if this is allowed, and if not, then is there an alternate way to do this?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 685f6fdf-a803-1184-44a8-e7a88e553c05
* Version Independent ID: c0c87be8-61e4-eb92-a5b0-09ec34526187
* Content: [Monetization, engagement, and Store services - UWP applications](https://docs.microsoft.com/en-us/windows/uwp/monetize/)
* Content Source: [windows-apps-src/monetize/index.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/monetize/index.md)
* Product: **uwp**
* Technology: **publish**
* GitHub Login: @hickeys
* Microsoft Alias: **hickeys**

**Comment by hickeys** [comment]
Please refer to the [Store Policies](https://docs.microsoft.com/windows/uwp/publish/store-policies-and-code-of-conduct) page for guidance such as this. I don't want to provide an answer here because guidelines change from time to time, and I don't want to give an answer that's correct now but incorrect in 6 months.

Thanks,
Shawn
