### ISSUE TITLE
nvm install --lts is the correct way to install current lts node not nvm install node --lts

### ISSUE THREAD

**Issue by bc1121** [MicrosoftDocs/windows-uwp#2814]
You've got a crucial typo on this page...
nvm install --lts is the correct way to install current lts node not nvm install node --lts

The incorrect version results in failure

Correct
---
nvm install --lts

Incorrect
---
nvm install node --lts

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c6995595-66c4-f26a-b307-89a068b4b5ba
* Version Independent ID: 69400ed1-5d98-4d6e-47a3-5c409564e77d
* Content: [Set up NodeJS on WSL 2](https://docs.microsoft.com/en-us/windows/nodejs/setup-on-wsl2)
* Content Source: [hub/nodejs/setup-on-wsl2.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/hub/nodejs/setup-on-wsl2.md)
* Product: **dev-environment**
* Technology: **windows-nodejs**
* GitHub Login: @mattwojo
* Microsoft Alias: **mattwoj**

**Comment by bc1121** [comment]
please see pull request https://github.com/MicrosoftDocs/windows-uwp/pull/2815

**Comment by mattwojo** [comment]
Merged your PR. Thanks again @bc1121! 

*As a side note, for some reason I can install with `nvm install node --lts` just fine... ? I'm using Ubuntu-18.04 right now. Looks like you're correct that your change is the best way though. Thanks again!
![image](https://user-images.githubusercontent.com/7566797/103587043-3ae64900-4e9b-11eb-813c-06b140d62403.png)

**Comment by mattwojo** [comment]
Oh strange... just discovered that:
`nvm install node --lts` installs node v15.5.1
`nvm install --lts` installs node v14.15.4

..??

**Comment by bc1121** [comment]
I agree the syntax choice is strange.

Fair enough that node is an alias for current latest node but it seems `lts` might make a better alias for current lts node, than `--lts`, bringing it in line with the other "special default aliases". Oh well, I'm sure there's some technical reason for it given how lts versions show up in `nvm list`.

Side note:
`nvm install --lts node` installs node v14.15.4 (current version of lts)

I guess nvm operates on the first indicated node version whether indicated by alias or option like syntax and ignores any other indicated versions that follow.

Thanks for maintaining and updating the docs. I like having another best practice source to refer to, especially one that comes with some authority (or at least from another direction or type of authority) I've been downloading software from BBSs since the 80's but I am always wary. I like that Microsoft has put some skin in the game by maintaining these docs. It's a nice source to refer to in addition to the random person on the internet who has nothing to lose. It's a welcome asset to the wild wild west of opinions that exist on the internet. Even if it's just the basics, I find the reinforcement to be invaluable as a timesaver when sifting through readmes and support forums and as a good second opinion often backing a chosen or recommended route.

**Comment by mattwojo** [comment]
Wow - thank you so much! That feels very validating. It's been a tough line to ride regarding how much to cover on some of these topics when much of it is already in blog posts, on StackO, etc., but I'm just learning some of this myself so trying to consider what I would want to see from an authority in order to get setup and started. I've been doing lots of fact-checking with PMs and stakeholders. (As an example, I floated this question about why `nvm install node --lts` still works to the community in the nvm issues and got a great response explaining that it's a legacy carry-over that passes --lts to node's `make`, in the event you're compiling node... it's an artifact of nvm install's legacy support for passing extra arguments to `make`.) https://github.com/nvm-sh/nvm/issues/2399

I also found that someone had previously corrected me on this same issue, but in the wrong direction (LoL - I guess I wasn't in the mood for doing my homework that day and just accepted that it was correct). https://github.com/MicrosoftDocs/windows-uwp/issues/2743

Thanks again for your insight and kind words here. Please keep any feedback coming! We've also got a twitter handle where we make content announcements and encourage input on any new content you'd like to see us write about. https://twitter.com/WindowsDocs
