### ISSUE TITLE
Is there an SDK/Library for retrieving analytics data? 

### ISSUE THREAD

**Issue by jignesh-fandco** [MicrosoftDocs/windows-uwp#2818]
Raw API is ok, but Is there any library available for retrieving analytics data?  if yes, there should be a reference here on this page. 

Regards

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1bf48dba-fe0d-96df-0ee6-22d76418b157
* Version Independent ID: ba30d323-3727-a973-12c5-72203e78157f
* Content: [Access analytics data using Store services - UWP applications](https://docs.microsoft.com/en-us/windows/uwp/monetize/access-analytics-data-using-windows-store-services#call-the-windows-store-analytics-api)
* Content Source: [windows-apps-src/monetize/access-analytics-data-using-windows-store-services.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/monetize/access-analytics-data-using-windows-store-services.md)
* Product: **uwp**
* Technology: **publish**
* GitHub Login: @hickeys
* Microsoft Alias: **hickeys**

**Comment by GrantMeStrength** [comment]
We are changing the way we track issues filed from our documentation pages: please see this [blog post](https://techcommunity.microsoft.com/t5/microsoft-learn-blog/announcing-a-new-way-to-give-feedback-on-microsoft-learn/ba-p/4027635) for more details. The Microsoft Store documentation has been updated several times since your issue was reported, and there's a good chance your problem has been addressed. Right now, this issue is being closed but if you feel it is still valid and has not been addressed, please re-open it with any more available information. Please note that if you question is more general and not related to documentation, [Microsoft Q&A](https://learn.microsoft.com/en-us/answers/questions/) is a great way to get questions answered.
