### ISSUE TITLE
Insights API returning error and not returning results

### ISSUE THREAD

**Issue by mjfusa** [MicrosoftDocs/windows-uwp#2837]
Prerequisites:
Published Store App with acquisitions and crashes.

Query:
https://manage.devcenter.microsoft.com/v1.0/my/analytics/insights
Returns error:
{
    "error": "Object reference not set to an instance of an object."
}

Expected output:
Insights data

Workaround: Specify at least one dataType. For example: https://manage.devcenter.microsoft.com/v1.0/my/analytics/insights?applicationID=9MZJNFFBGM33&filter=dataType eq 'usage' or dataType eq 'health' or dataType eq 'acquisition'

The above request does not return the error.

If 'dataType' is required, it should be indicated as such in the documentation. (Doc indicate all parameters are not required.)
Also, Shouldn't the app id be required since 'Insights' are app and not account specific?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 40a03102-3ed7-453d-883d-6a7214f1db1d
* Version Independent ID: b2629404-ca53-3bb9-85aa-85694c430068
* Content: [Get insights data - UWP applications](https://docs.microsoft.com/en-us/windows/uwp/monetize/get-insights-data-for-your-app)
* Content Source: [windows-apps-src/monetize/get-insights-data-for-your-app.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/monetize/get-insights-data-for-your-app.md)
* Product: **uwp**
* Technology: **publish**
* GitHub Login: @hickeys
* Microsoft Alias: **hickeys**

**Comment by GrantMeStrength** [comment]
We are changing the way we track issues filed from our documentation pages: please see this [blog post](https://techcommunity.microsoft.com/t5/microsoft-learn-blog/announcing-a-new-way-to-give-feedback-on-microsoft-learn/ba-p/4027635) for more details. The Microsoft Store documentation has been updated several times since your issue was reported, and there's a good chance your problem has been addressed. Right now, this issue is being closed but if you feel it is still valid and has not been addressed, please re-open it with any more available information. Please note that if you question is more general and not related to documentation, [Microsoft Q&A](https://learn.microsoft.com/en-us/answers/questions/) is a great way to get questions answered.
