### ISSUE TITLE
Deep link from browser.

### ISSUE THREAD

**Issue by halaharr** [MicrosoftDocs/windows-uwp#2848]
Hi, 
     I was going through the article to have deep linking for my UWP app. Deep linking works from outlook email and by typing the link (ex: https://mydomain/accept) in Win + R. It does not work when I click on browser like Edge or Chrome.Is there something I am missing. I am using https domain.

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c7e251da-3cab-4aa0-2915-21189cf71bef
* Version Independent ID: b244b311-a0e5-185d-df82-1dadf3fe6416
* Content: [Enable apps for websites using app URI handlers - UWP applications](https://docs.microsoft.com/en-us/windows/uwp/launch-resume/web-to-app-linking)
* Content Source: [windows-apps-src/launch-resume/web-to-app-linking.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/launch-resume/web-to-app-linking.md)
* Product: **uwp**
* Technology: **processes-and-threading**
* GitHub Login: @lastnameholiu
* Microsoft Alias: **alholiu**

**Comment by scott-wowzers** [comment]
@lastnameholiu Will Edge support for app uri handlers be restored at some point? The documentation here says they are supported, but this support seems to have been dropped at some point. Also, in Edge 87+ **Settings > Cookies and site permissions** menu there is a curious "Application links" setting that leads to an options page that reads "Allows apps to automatically open when launched from a link. All other apps will ask for permission before opening." However, there are no controls on that page. Can you help shed some light on all this?

**Comment by Karl-Bridge-Microsoft** [comment]
We are changing the way we track issues filed from our documentation pages: please see this [blog post](https://techcommunity.microsoft.com/t5/microsoft-learn-blog/announcing-a-new-way-to-give-feedback-on-microsoft-learn/ba-p/4027635) for more details. Right now, this issue is being closed but if you feel it is still valid and has not been addressed, please re-open it with any more available information. Please note that if your question is more general and not related to documentation, [Microsoft Q&A](https://learn.microsoft.com/en-us/answers/questions/) is a great way to get questions answered.
