### ISSUE TITLE
Where do I get started?

### ISSUE THREAD

**Issue by LenYates** [MicrosoftDocs/windows-uwp#2851]
In this page I read "From the Overview page, click Create a new app."  So where is the "Overview page"?  I have no idea where to find it.  Why don't you make "the Overview page" a link, taking me directly there?

Len Yates

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6e0a6489-50c7-af46-241a-272719fc2404
* Version Independent ID: 889d635c-2cb5-ce4c-2917-8e2a342106c2
* Content: [Create your app by reserving a name - UWP applications](https://docs.microsoft.com/en-us/windows/uwp/publish/create-your-app-by-reserving-a-name)
* Content Source: [windows-apps-src/publish/create-your-app-by-reserving-a-name.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/publish/create-your-app-by-reserving-a-name.md)
* Product: **uwp**
* Technology: **publish**
* GitHub Login: @hickeys
* Microsoft Alias: **hickeys**

**Comment by GrantMeStrength** [comment]
We are changing the way we track issues filed from our documentation pages: please see this [blog post](https://techcommunity.microsoft.com/t5/microsoft-learn-blog/announcing-a-new-way-to-give-feedback-on-microsoft-learn/ba-p/4027635) for more details. The Microsoft Store documentation has been updated several times since your issue was reported, and there's a good chance your problem has been addressed. Right now, this issue is being closed but if you feel it is still valid and has not been addressed, please re-open it with any more available information. Please note that if you question is more general and not related to documentation, [Microsoft Q&A](https://learn.microsoft.com/en-us/answers/questions/) is a great way to get questions answered.
