### ISSUE TITLE
In the Partner centre, I cannot find the Monetize App page

### ISSUE THREAD

**Issue by stewa11** [MicrosoftDocs/windows-uwp#2861]
In the Partner centre, I cannot find the Monetize App page

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 40e691c3-7810-63f8-721a-aa29129e6fa6
* Version Independent ID: ec9729f4-5ebf-e6cd-fb92-c1e0bb8ff2fc
* Content: [In-app ads - UWP applications](https://docs.microsoft.com/en-us/windows/uwp/publish/in-app-ads)
* Content Source: [windows-apps-src/publish/in-app-ads.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/publish/in-app-ads.md)
* Product: **uwp**
* Technology: **publish**
* GitHub Login: @hickeys
* Microsoft Alias: **hickeys**

**Comment by GrantMeStrength** [comment]
We are changing the way we track issues filed from our documentation pages: please see this [blog post](https://techcommunity.microsoft.com/t5/microsoft-learn-blog/announcing-a-new-way-to-give-feedback-on-microsoft-learn/ba-p/4027635) for more details. The Microsoft Store documentation has been updated several times since your issue was reported, and there's a good chance your problem has been addressed. Right now, this issue is being closed but if you feel it is still valid and has not been addressed, please re-open it with any more available information. Please note that if your question is more general and not related to documentation, [Microsoft Q&A](https://learn.microsoft.com/en-us/answers/questions/) is a great way to get questions answered.
