### ISSUE TITLE
Can't start a project

### ISSUE THREAD

**Issue by gewarren** [MicrosoftDocs/windows-uwp#2863]
---
**Issue moved from MicrosoftDocs/feedback#3315**
- Please respond to @LenYates.

---

_From @LenYates on Tuesday, December 8, 2020 4:06:34 PM_

I registered my company and paid $99.  Now I'd like to begin a project by entering the name of my game.  However, there seems to be no way.  Instructions say: **From the Overview page, click Create a new app.**  However, there seems to be nothing of the kind on the Overview page.

Len Yates

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6e0a6489-50c7-af46-241a-272719fc2404
* Version Independent ID: 889d635c-2cb5-ce4c-2917-8e2a342106c2
* Content: [Create your app by reserving a name - UWP applications](https://docs.microsoft.com/en-us/windows/uwp/publish/create-your-app-by-reserving-a-name)
* Content Source: [windows-apps-src/publish/create-your-app-by-reserving-a-name.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/publish/create-your-app-by-reserving-a-name.md)
* Product: **uwp**
* Technology: **publish**
* GitHub Login: @hickeys
* Microsoft Alias: **hickeys**

**Comment by gewarren** [comment]
---
**Issue moved from MicrosoftDocs/feedback#3315**
- Please respond to @welcome[bot].

---

_From @welcome[bot] on Tuesday, December 8, 2020 4:06:35 PM_

Thank you for creating the issue! One of our team members will get back to you shortly with additional information. If this is a product issue, please close this and contact the particular product's support instead (see https://support.microsoft.com/allproducts for the list of support websites).

**Comment by GrantMeStrength** [comment]
We are changing the way we track issues filed from our documentation pages: please see this [blog post](https://techcommunity.microsoft.com/t5/microsoft-learn-blog/announcing-a-new-way-to-give-feedback-on-microsoft-learn/ba-p/4027635) for more details. The Microsoft Store documentation has been updated several times since your issue was reported, and there's a good chance your problem has been addressed. Right now, this issue is being closed but if you feel it is still valid and has not been addressed, please re-open it with any more available information. Please note that if your question is more general and not related to documentation, [Microsoft Q&A](https://learn.microsoft.com/en-us/answers/questions/) is a great way to get questions answered.

**Comment by LenYates** [comment]
On the Properties Page is this:

[image: image.png]
I need to be able to select the "No" option, but both the "Yes" and "No"
buttons are grayed out.

PLEASE, PLEASE fix this.

Len Yates
