### ISSUE TITLE
PowerRename使用中的问题："替换为"文字输入框与"预览"框下面"已重命名"结果 有出入 

### ISSUE THREAD

**Issue by feng476915396** [MicrosoftDocs/windows-uwp#2868]
[Enter feedback here]

P1：填写"搜索"输入框内容
![image](https://user-images.githubusercontent.com/49358548/102442375-3c241300-405f-11eb-9203-5a65c77c5747.png)
P2：通过输入法输入(此次使用搜狗输入法，用微软自带输入法也用过，也出现同样问题)
![image](https://user-images.githubusercontent.com/49358548/102442408-4d6d1f80-405f-11eb-8fc6-8b789e71ba71.png)
P3：文字输入到"被替换"
![image](https://user-images.githubusercontent.com/49358548/102442472-6f66a200-405f-11eb-90b6-44a9b761e142.png)
最后出现的结果就是 "被替换" 输入框内的文字只有第一个 被成功替换了 我尝试了很多次，当通过输入法键入很多文字而并非一个字一个字输入到框内，就会出现此问题

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4c2786bc-ad98-974e-d7b0-a6ce82f8b576
* Version Independent ID: 0be1b400-5349-7dd9-43d2-abd3a91884a6
* Content: [PowerToys PowerRename utility for Windows 10](https://docs.microsoft.com/en-us/windows/powertoys/powerrename)
* Content Source: [hub/powertoys/powerrename.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/hub/powertoys/powerrename.md)
* Product: **dev-environment**
* Technology: **powertoys**
* GitHub Login: @GrantMeStrength
* Microsoft Alias: **jken**

**Comment by hkhmsft** [comment]
Hi @feng476915396 , it seems that you have a product issue rather than a specific documentation fix issue. May I suggest your file this as a product feedback instead? You got here by clicking Send feedback about > This page. If instead you click Send feedback about > This product, then you'll be taken to the right channel to leave product questions/feedback.

Alternatively, you could also ask the community of experts and Microsoft Engineers over at [Microsoft Q&A](https://docs.microsoft.com/en-us/answers/topics/windows-10-general.html), they offer timely answers to a multitude of technical questions surrounding windows-uwp.
