### ISSUE TITLE
Client ID location seems to be faulty

### ISSUE THREAD

**Issue by alfaunits** [MicrosoftDocs/windows-uwp#2875]
When a new Azure AD app's key is created, it also has a Client ID field. However that is not the same as the Client ID that we get when clicking on the Azure AD App itself.
The problem is the Client ID, where the key is located, does not work for Hardware Dashboard submissions. It is the "main" one that is required.

The docs are misleading, but also, there is no reason for the Key generation output to have the other (useless?) Client ID.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 59b3ff12-c450-4912-9509-e83831d452a1
* Version Independent ID: 6563901d-adc1-4cdb-144b-94306d082e46
* Content: [Add users, groups, and Azure AD applications to your Partner Center account - UWP applications](https://docs.microsoft.com/en-us/windows/uwp/publish/add-users-groups-and-azure-ad-applications#manage-keys-for-an-azure-ad-application)
* Content Source: [windows-apps-src/publish/add-users-groups-and-azure-ad-applications.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/publish/add-users-groups-and-azure-ad-applications.md)
* Product: **uwp**
* Technology: **publish**
* GitHub Login: @hickeys
* Microsoft Alias: **hickeys**

**Comment by GrantMeStrength** [comment]
We are changing the way we track issues filed from our documentation pages: please see this [blog post](https://techcommunity.microsoft.com/t5/microsoft-learn-blog/announcing-a-new-way-to-give-feedback-on-microsoft-learn/ba-p/4027635) for more details. The Microsoft Store documentation has been updated several times since your issue was reported, and there's a good chance your problem has been addressed. Right now, this issue is being closed but if you feel it is still valid and has not been addressed, please re-open it with any more available information. Please note that if you question is more general and not related to documentation, [Microsoft Q&A](https://learn.microsoft.com/en-us/answers/questions/) is a great way to get questions answered.
