### ISSUE TITLE
Ink toolbar sample missing InkPresenter.InputDeviceTypes

### ISSUE THREAD

**Issue by PieEatingNinjas** [MicrosoftDocs/windows-uwp#288]
I was browsing the [docs page about adding a Ink Toolbar](https://docs.microsoft.com/en-us/windows/uwp/design/input/ink-toolbar)

I noticed that nowhere on this page it is stated that you should set the InputDevicesTypes on the InkPresenter of your canvas in order to be able to draw something on it.
For example, the very first sample XAML looks like you can just grab it and paste it in your own app. However, you wouldn't be able to draw anything on the canvas as the InputDevicesTypes property is not set and defaults to None. (If you want, I can do a PR for that, just showing the ctor of a page in which the InputDevicesTypes is set)

Moreover, the downloadable [sample on that page](https://github.com/MicrosoftDocs/windows-topic-specific-samples/archive/uwp-ink-toolbar-handedness.zip) also doesn't set the InputDevicesTypes.

Although this page and code sample really is about the InkToolbar, I think it might confuse developers: they download the sample code, or paste the code listed on the page in their own app, but they won't be able to draw on the canvas.

**Comment by ginami** [comment]
Thank you @PieEatingNinjas for this feedback. 

@Karl-Bridge-Microsoft, can you please follow up? Thank you!

**Comment by Karl-Bridge-Microsoft** [comment]
Hello @PieEatingNinjas, inking is supported only for pen, by default. You have to set InputDeviceTypes only if you need ink support for touch or mouse. Touch inking is covered in the Custom Toggle section of this topic (where it is explained why touch is not supported by default), and is also covered in the Basic customization section of the intro topic (https://docs.microsoft.com/en-us/windows/uwp/design/input/pen-and-stylus-interactions). As the topic is focused on the InkToolbar control and how to customize it, rather than basic inking, a note re. InputDeviceTypes outside of the Custom Toggle section would be out of place. 

Thanks for your feedback, keep it coming!
