### ISSUE TITLE
Microsoft Store purchase API can not be used.

### ISSUE THREAD

**Issue by Chris1-Fu** [MicrosoftDocs/windows-uwp#2890]
Following instruction of the [docs](https://docs.microsoft.com/en-us/windows/uwp/monetize/view-and-grant-products-from-a-service), I failed to get the access token to create a Microsoft Store ID key for the Microsoft Store purchase API, the following error is returned. 

**"AADSTS500011: The resource principal named https://onestore.microsoft.com/b2b/keys/create/purchase was not found in the tenant named XXXXXXXXXXXX. This can happen if the application has not been installed by the administrator of the tenant or consented to by any user in the tenant. You might have sent your authentication request to the wrong tenant."**

How can I fixed it?
Thanks!

**Comment by GrantMeStrength** [comment]
We are changing the way we track issues filed from our documentation pages: please see this [blog post](https://techcommunity.microsoft.com/t5/microsoft-learn-blog/announcing-a-new-way-to-give-feedback-on-microsoft-learn/ba-p/4027635) for more details. The Microsoft Store documentation has been updated several times since your issue was reported, and there's a good chance your problem has been addressed. Right now, this issue is being closed but if you feel it is still valid and has not been addressed, please re-open it with any more available information. Please note that if you question is more general and not related to documentation, [Microsoft Q&A](https://learn.microsoft.com/en-us/answers/questions/) is a great way to get questions answered.
