### ISSUE TITLE
Missing Info

### ISSUE THREAD

**Issue by BBloom81** [MicrosoftDocs/windows-uwp#2896]
Page was provided by Sebastian S. as a solution to changing my dev account address that I'm getting constant emails from you to update.  Nowhere does this page inform how to do that.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c4ddd610-d6de-7a7c-2d59-fdc08dd98371
* Version Independent ID: 1ed74795-fa40-80a5-4fc2-6f4e87efa594
* Content: [Opening a developer account - UWP applications](https://docs.microsoft.com/en-us/windows/uwp/publish/opening-a-developer-account#the-account-signup-process)
* Content Source: [windows-apps-src/publish/opening-a-developer-account.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/publish/opening-a-developer-account.md)
* Product: **uwp**
* Technology: **publish**
* GitHub Login: @hickeys
* Microsoft Alias: **hickeys**

**Comment by GrantMeStrength** [comment]
We are changing the way we track issues filed from our documentation pages: please see this [blog post](https://techcommunity.microsoft.com/t5/microsoft-learn-blog/announcing-a-new-way-to-give-feedback-on-microsoft-learn/ba-p/4027635) for more details. The Microsoft Store documentation has been updated several times since your issue was reported, and there's a good chance your problem has been addressed. Right now, this issue is being closed but if you feel it is still valid and has not been addressed, please re-open it with any more available information. Please note that if you question is more general and not related to documentation, [Microsoft Q&A](https://learn.microsoft.com/en-us/answers/questions/) is a great way to get questions answered.
