### ISSUE TITLE
[Question] How to properly resize DesktopWindowXamlSource to avoid flicker & jitter

### ISSUE THREAD

**Issue by AzAgarampur** [MicrosoftDocs/windows-uwp#2902]
UWP applications are resizable, and they do not experience the ugly resize jitter & flicker that most classic Win32 applications do. However, I was expecting the same experience while using the XAML hosting API, but it looks like the problem still persists. 

Is there a proper way to resize the `DesktopWindowXamlSource` XAML window so that we can achieve the same clean resize behavior that UWP applications have? This jitter/flicker looks terrible, especially when using `HostBackdrop` acrylic - its something you'd not expect when rendering XAML controls with animations, shadows, etc.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0e91baa2-93e1-4a14-d058-829c104b595f
* Version Independent ID: 48e643a4-d86f-a0ac-fbe1-902f89762f77
* Content: [Advanced scenarios for XAML Islands in C++ Win32 apps - Windows applications](https://docs.microsoft.com/en-us/windows/apps/desktop/modernize/advanced-scenarios-xaml-islands-cpp)
* Content Source: [hub/apps/desktop/modernize/advanced-scenarios-xaml-islands-cpp.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/hub/apps/desktop/modernize/advanced-scenarios-xaml-islands-cpp.md)
* Product: **uwp**
* Technology: **apps**
* GitHub Login: @mcleanbyron
* Microsoft Alias: **mcleans**

**Comment by mcleanbyron** [comment]
Thanks for submitting your feedback. Because this is technical feedback about the behavior of the DesktopWindowsXamlSource API (instead of feedback about the docs in particular), can you please submit this feedback in a new issue in the [Microsoft.Toolkit.Win32](https://github.com/windows-toolkit/Microsoft.Toolkit.Win32/issues) repo? This is the open source repo where the source code for this API is published and maintained, and the engineering team that owns this API reviews the issues posted there.

**Comment by AzAgarampur** [comment]
Will do
