### ISSUE TITLE
Calls to the acquisitions-data API endpoint only returns partial data

### ISSUE THREAD

**Issue by madshaun1984** [MicrosoftDocs/windows-uwp#2906]
Submitting requests to the acquisitions-data endpoint fails to retrieve the full response detailed in the API documentation.

At best, it responds with a smaller set of array values.

`{
    "Value": [
        {
            "applicationId": "[Redacted]",
            "date": "2021-01-14",
            "acquisitionQuantity": 1,
            "purchasePriceUSDAmount": 0.0,
            "purchasePriceLocalAmount": 0.0,
            "purchaseTaxUSDAmount": 0.0,
            "purchaseTaxLocalAmount": 0.0
        }
    ],
    "TotalCount": 1,
    "DataFreshnessTimestamp": "2021-01-14T21:34:00"
}`

Either the documentations severely outdated, or the API is broken.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 06465920-b24d-5001-c32d-db426efbd0f1
* Version Independent ID: 3ad9f1fe-9ed4-0fa5-a30f-38a5f2372300
* Content: [Get acquisitions data for your games and apps - UWP applications](https://docs.microsoft.com/en-us/windows/uwp/monetize/acquisitions-data)
* Content Source: [windows-apps-src/monetize/acquisitions-data.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/monetize/acquisitions-data.md)
* Product: **uwp**
* Technology: **publish**
* GitHub Login: @hickeys
* Microsoft Alias: **hickeys**

**Comment by GrantMeStrength** [comment]
We are changing the way we track issues filed from our documentation pages: please see this [blog post](https://techcommunity.microsoft.com/t5/microsoft-learn-blog/announcing-a-new-way-to-give-feedback-on-microsoft-learn/ba-p/4027635) for more details. The Microsoft Store documentation has been updated several times since your issue was reported, and there's a good chance your problem has been addressed. Right now, this issue is being closed but if you feel it is still valid and has not been addressed, please re-open it with any more available information. Please note that if your question is more general and not related to documentation, [Microsoft Q&A](https://learn.microsoft.com/en-us/answers/questions/) is a great way to get questions answered.
