### ISSUE TITLE
ReceiptDate and ReceiptDeviceId are missing from product receipt

### ISSUE THREAD

**Issue by artyom-kolesnikov** [MicrosoftDocs/windows-uwp#2950]
Hello,

We are trying to implement verification of purchased product for our UWP application. It is stated in the [article](https://docs.microsoft.com/en-us/windows/uwp/monetize/use-receipts-to-verify-product-purchases#element-and-attribute-descriptions-for-a-receipt) that Receipt element should contain ReceiptDate and ReceiptDeviceId attributes, but these attributes are missing from all receipts which we obtained from the API. Could you please clarify, is it normal behavior for now and receipts without these attributes can be treated as valid?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 58237b3e-0baa-92c4-caa7-023be22ccf40
* Version Independent ID: ef2f5a25-f75d-f62d-b52f-c18c72e8540b
* Content: [Use receipts to verify product purchases - UWP applications](https://docs.microsoft.com/en-us/windows/uwp/monetize/use-receipts-to-verify-product-purchases)
* Content Source: [windows-apps-src/monetize/use-receipts-to-verify-product-purchases.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/monetize/use-receipts-to-verify-product-purchases.md)
* Product: **uwp**
* Technology: **publish**
* GitHub Login: @hickeys
* Microsoft Alias: **hickeys**

**Comment by GrantMeStrength** [comment]
We are changing the way we track issues filed from our documentation pages: please see this [blog post](https://techcommunity.microsoft.com/t5/microsoft-learn-blog/announcing-a-new-way-to-give-feedback-on-microsoft-learn/ba-p/4027635) for more details. The Microsoft Store documentation has been updated several times since your issue was reported, and there's a good chance your problem has been addressed. Right now, this issue is being closed but if you feel it is still valid and has not been addressed, please re-open it with any more available information. Please note that if you question is more general and not related to documentation, [Microsoft Q&A](https://learn.microsoft.com/en-us/answers/questions/) is a great way to get questions answered.
