### ISSUE TITLE
Documentation not reflecting reality about signing up

### ISSUE THREAD

**Issue by JanRajnoha** [MicrosoftDocs/windows-uwp#3020]
I tried to create dev account, but according to documentation, I could choose between individual or company account, but on sign up page is nothing about it. Next is fee, that is not mention nowhere.

Page: https://docs.microsoft.com/en-us/windows/uwp/publish/opening-a-developer-account

**Comment by JanRajnoha** [comment]
@hickeys

**Comment by GrantMeStrength** [comment]
We are changing the way we track issues filed from our documentation pages: please see this [blog post](https://techcommunity.microsoft.com/t5/microsoft-learn-blog/announcing-a-new-way-to-give-feedback-on-microsoft-learn/ba-p/4027635) for more details. The Microsoft Store documentation has been updated several times since your issue was reported, and there's a good chance your problem has been addressed. Right now, this issue is being closed but if you feel it is still valid and has not been addressed, please re-open it with any more available information. Please note that if you question is more general and not related to documentation, [Microsoft Q&A](https://learn.microsoft.com/en-us/answers/questions/) is a great way to get questions answered.
