### ISSUE TITLE
Assembling the Simple3DGameXaml Source Code as a Visual Studio Project

### ISSUE THREAD

**Issue by Robert-Tortorelli** [MicrosoftDocs/windows-uwp#3032]
This tutorial is primarily focused on Simple3DGameDX ("Uses DirectX to render game UI and implements its own layout"), however later Topics (see 'Extend the sample game' at https://docs.microsoft.com/en-us/windows/uwp/gaming/tutorial-resources) do reference Simple3DGameXaml ("Uses XAML to render game UI and handle layout").

The link on the page I'm commenting on (https://docs.microsoft.com/en-us/windows/uwp/gaming/tutorial--create-your-first-uwp-directx-game) named 'Direct3D sample game' (https://docs.microsoft.com/en-us/samples/microsoft/windows-universal-samples/simple3dgamedx/) does not provide easy to use source code for Simple3DGameXaml, as it is combined with the source code for Simple3DGameDX.

A better place to reference Simple3DGameXaml source code is https://docs.microsoft.com/en-us/samples/microsoft/windows-universal-samples/simple3dgamexaml/
This URL contains Simple3DGameXaml source code (downloaded as **DirectX_and_XAML_game_sample.zip**) without the complication of mixing source code for Simple3DGameDX.
For this reason this URL is better for beginners who are interested in using Simple3DGameXaml as a template.

Note that even **DirectX_and_XAML_game_sample.zip** is not complete. Building a Visual Studio Project with this Simple3DGameXaml source code results in errors such as, “error APPX0702: Payload file 'source\solution-name\Simple3DGameDX\Cpp\Assets\seafloor.dds' does not exist”.
To resolve this, a Simple3DGameDX\cpp\Assets\ folder must be created at the path shown in the error message. The source for this Assets folder can be found in **Windows-universal-samples-master.zip** at the folder Windows-universal-samples-master\Samples\Simple3DGameDX\cpp\Assets\
**Windows-universal-samples-master.zip** can be downloaded at https://github.com/microsoft/Windows-universal-samples/archive/master.zip
It would further simplify building Simple3DGameXaml if the assets of Simple3DGameDX\cpp\Assets\ were preloaded in folder Simple3DGameXaml\cpp\Assets\ of **DirectX_and_XAML_game_sample.zip**, making **Windows-universal-samples-master.zip** unnecessary.

And while I do realize it's a big ask, and beyond the scope of this comment, a further improvement would be to provide a tutorial focused solely on Simple3DGameXaml, without mixing its tutorial with that of Simple3DGameDX.

  Thank you,
    Robert

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f375db84-d770-3a7c-2a9c-54795b36288e
* Version Independent ID: a3ab6f17-0b50-c44a-f7f7-50f5c949b56d
* Content: [Create a DirectX Universal Windows Platform (UWP) game - UWP applications](https://docs.microsoft.com/en-us/windows/uwp/gaming/tutorial--create-your-first-uwp-directx-game)
* Content Source: [windows-apps-src/gaming/tutorial--create-your-first-uwp-directx-game.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/gaming/tutorial--create-your-first-uwp-directx-game.md)
* Product: **uwp**
* Technology: **games**
* GitHub Login: @stevewhims
* Microsoft Alias: **stwhi**

**Comment by stevewhims** [comment]
Hi, @Robert-Tortorelli, and thanks for your feedback.

Yes, Simple3DGameXaml has a dependency on some of the assets from Simple3DGameDX, and that's by design. I think you're right that we should link to [DirectX and XAML game sample](/samples/microsoft/windows-universal-samples/simple3dgamexaml/), so I have a fix for that in progress. The readme says "In addition, to reduce disk space usage, Simple3DGameXaml references some its assets from the Simple3DGameDX\Cpp\Assets folder," so I've added a reminder for folks to check the readme.

It's only the very last topic in the series (the "Extend the sample game" topic) that mentions Simple3DGameXaml ("the version of this game that uses XAML for the overlay"). So I think that that version of the game is nicely encapsulted in that topic. However I do think it's inevitable (and, again, intentional) that the sequence of events is a) learn about and study Simple3DGameDX and then b) build on that knowledge with Simple3DGameXaml.

As for a tutorial focused solely on Simple3DGameXaml, that's not in scope right now, but I'll bear it in mind for possible future work. My main concern with that would be either a) in such a tutorial we'd be duplicating nearly all the ground we'd covered with Simple3DGameDX, or else b) we'd be sending folks off to study Simple3DGameDX first, which is pretty much the place we're at now.

Thanks again!
Steve

**Comment by Robert-Tortorelli** [comment]
Thank you Steve. Your explanation makes sense.

  Robert
