### ISSUE TITLE
The link provided for Simple3DGameXaml source code is missing assets

### ISSUE THREAD

**Issue by Robert-Tortorelli** [MicrosoftDocs/windows-uwp#3036]
The link at 'Direct3D shooting sample game (XAML)' (https://github.com/Microsoft/Windows-universal-samples/tree/master/Samples/Simple3DGameXaml) does not include the following assets required for the Visual Studio Build:

1. the folder SharedContent\ needs to be included in the Project folder at source\solution-name\Simple3DGameXaml\SharedContent
This folder is included in the copy of Simple3DGameXaml provided in DirectX_and_XAML_game_sample.zip, which is located at https://github.com/microsoft/Windows-universal-samples/releases/download/143670/DirectX_and_XAML_game_sample.zip, which is the ‘Download Zip’ button’s link on webpage https://docs.microsoft.com/en-us/samples/microsoft/windows-universal-samples/simple3dgamexaml/
For this reason DirectX_and_XAML_game_sample.zip is a better source for Simple3DGameXaml than https://github.com/Microsoft/Windows-universal-samples/tree/master/Samples/Simple3DGameXaml

2. the folder Simple3DGameDX\cpp\Assets\ needs to be included in the Project folder at source\solution-name\Simple3DGameDX\cpp\Assets
This folder is included in the copy of Simple3DGameDX provided in Windows-universal-samples-master.zip. It is located in this zip file at Windows-universal-samples-master\Samples\Simple3DGameDX\cpp\Assets
Windows-universal-samples-master.zip can be downloaded at https://github.com/microsoft/Windows-universal-samples/archive/master.zip
If Simple3DGameDX\cpp\Assets is missing then Visual Studio Build errors occur, such as “error APPX0702: Payload file 'source\solution-name\Simple3DGameDX\cpp\Assets\seafloor.dds' does not exist.”

Thank you,
Robert

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 57ba16b2-6122-0499-b61d-ba93bf2781cf
* Version Independent ID: 9fb03c83-3f5c-dc72-09d6-0b571d2cf86d
* Content: [Extend the sample game - UWP applications](https://docs.microsoft.com/en-us/windows/uwp/gaming/tutorial-resources)
* Content Source: [windows-apps-src/gaming/tutorial-resources.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/gaming/tutorial-resources.md)
* Product: **uwp**
* Technology: **games**
* GitHub Login: @stevewhims
* Microsoft Alias: **stwhi**

**Comment by stevewhims** [comment]
Hi, @Robert-Tortorelli, and thanks for your feedback.

In the last topic of the series (the only one that mentions Simple3DGameXaml), I think it's best to link the url you mention here, which is [DirectX and XAML game sample](/samples/microsoft/windows-universal-samples/simple3dgamexaml/). So I have a fix for that in progress.

Simple3DGameXaml has a dependency on some of the assets from Simple3DGameDX, and that's by design. The readme says "In addition, to reduce disk space usage, Simple3DGameXaml references some its assets from the Simple3DGameDX\Cpp\Assets folder," so I've added a reminder for folks to check the readme.

Thanks again!
Steve
