### ISSUE TITLE
Create a Tutorial Based on Simple3DGameXaml

### ISSUE THREAD

**Issue by Robert-Tortorelli** [MicrosoftDocs/windows-uwp#3038]
The current tutorial largely follows Simple3DGameDX. One based on Simple3DGameXaml that fully shows how to use XAML to render game UI and handle layout would be very helpful.

  Thank you,
    Robert

**Comment by stevewhims** [comment]
Hi, @Robert-Tortorelli, and thanks for your feedback.

As you know, at the moment learning-wise the sequence of events is a) learn about and study Simple3DGameDX and then b) build on that knowledge with Simple3DGameXaml. As for a tutorial focused solely on Simple3DGameXaml, that's not in scope right now, but I'll bear it in mind for possible future work. My main concern with that would be either a) in such a tutorial we'd be duplicating nearly all the ground we'd covered with Simple3DGameDX, or else b) we'd be sending folks off to study Simple3DGameDX first, which is pretty much the place we're at now.

Incidentally, rather than leaving feedback against a repo (which usually takes more time to find an owner), feel free to visit a relevant published topic, scroll down to the Feedback section, and click Submit and view feedback for > This product (if you have feedback about the API itself), or This page (if you have feedback about the documentation itself). That'll get routed to the right place more quickly than filing against the repo.

Many thanks!
Steve
