### ISSUE TITLE
How to add package id to Unit test project?

### ISSUE THREAD

**Issue by steam3d** [MicrosoftDocs/windows-uwp#3050]
Unit test can't test method like this `ApplicationData.Current.TemporaryFolder;`. It required packed id.

---
#### Сведения о документе

⚠ *Не вносите правки в этот раздел. Это необходимо для связывания страницы сайта docs.microsoft.com с вопросом на GitHub.*

* ID: cf28a713-4e81-45e0-a3c7-0274ba6b2e85
* Version Independent ID: 19dd0436-a27d-8e50-5e7b-06c8fcd49a3f
* Content: [Предоставление идентификаторов для неупакованных классических приложений - Windows applications](https://docs.microsoft.com/ru-ru/windows/apps/desktop/modernize/grant-identity-to-nonpackaged-apps#feedback)
* Content Source: [hub/apps/desktop/modernize/grant-identity-to-nonpackaged-apps.md](https://github.com/MicrosoftDocs/windows-uwp.ru-ru/blob/live/hub/apps/desktop/modernize/grant-identity-to-nonpackaged-apps.md)
* Product: **uwp**
* Technology: **apps**
* GitHub Login: @mcleanbyron
* Microsoft Alias: **mcleans**

**Comment by mcleanbyron** [comment]
Thanks for reaching out to us. This repo is unfortunately not intended for technical questions and support requests. Please see the following resources.

- [Microsoft Q&A](https://docs.microsoft.com/answers/topics/windows-uwp.html) offers relevant and timely answers to your technical problems from a community of experts and Microsoft engineers.
- For community assistance with development questions, there are our [forums](https://social.msdn.microsoft.com/Forums/newthread?category=windowsapps&forum=wpdevelop&prof=required), and [StackOverflow](https://stackoverflow.com/questions).
- The [Windows developer support](https://developer.microsoft.com/windows/support) site explains other support options.
- For developer issues, or suspected product bugs, there's [Microsoft Support](https://support.microsoft.com/contactus); a support engineer will look at the repro and see whether the issue is a Microsoft product bug, or something else. If it's a bug with a Microsoft product then the ticket will be free of charge.
