### ISSUE TITLE
Where's the full source code?

### ISSUE THREAD

**Issue by knat** [MicrosoftDocs/windows-uwp#3122]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: aac4115a-6482-734f-15cd-4601ffafa4df
* Version Independent ID: 37664920-b9b0-1457-1711-b2ed848dd8fb
* Content: [Multisampling in UWP apps - UWP applications](https://docs.microsoft.com/en-us/windows/uwp/gaming/multisampling--multi-sample-anti-aliasing--in-windows-store-apps)
* Content Source: [windows-apps-src/gaming/multisampling--multi-sample-anti-aliasing--in-windows-store-apps.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/gaming/multisampling--multi-sample-anti-aliasing--in-windows-store-apps.md)
* Product: **uwp**
* Technology: **games**
* GitHub Login: @stevewhims
* Microsoft Alias: **stwhi**

**Comment by stevewhims** [comment]
Thanks, @knat. This looks like a similar task to my recent updates to https://docs.microsoft.com/windows/uwp/gaming/directx-and-xaml-interop. That involved a) finding out which sample application the snippets were taken from, b) adding to the topic links to those samples, and c) porting the code in the topic from C++/CX to C++/WinRT.

So I'll approach this the same way. I'll also track the work the same way, so I've created an internal work item for myself on my backlog. Since I'm tracking that work internally, I'll temporarily close this issue now and reopen it once I start the work (in the future), and report back here when that's done.

-Steve
