### ISSUE TITLE
"add-on" docs make reference to un-find-able "import/export" feature

### ISSUE THREAD

**Issue by Brantone** [MicrosoftDocs/windows-uwp#3123]
On the "Create add-on Store listings", there's a Tip "You can also import and export Store listings for your add-on if you'd like to enter your listing info offline in a .csv file" ; however, does not go into detail about how / where that's possible to accomplish. Additionally - can't find it anywhere in PartnerCenter.
Is export/import via CSV even feasible?
TIA

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 523e3353-05af-29f8-932a-b87cbc6cade3
* Version Independent ID: 9a920d45-67be-14f8-c1ee-8be74a96706c
* Content: [Create add-on Store listings - UWP applications](https://docs.microsoft.com/en-us/windows/uwp/publish/create-add-on-store-listings)
* Content Source: [windows-apps-src/publish/create-add-on-store-listings.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/publish/create-add-on-store-listings.md)
* Product: **uwp**
* Technology: **publish**
* GitHub Login: @hickeys
* Microsoft Alias: **hickeys**

**Comment by GrantMeStrength** [comment]
We are changing the way we track issues filed from our documentation pages: please see this [blog post](https://techcommunity.microsoft.com/t5/microsoft-learn-blog/announcing-a-new-way-to-give-feedback-on-microsoft-learn/ba-p/4027635) for more details. The Microsoft Store documentation has been updated several times since your issue was reported, and there's a good chance your problem has been addressed. Right now, this issue is being closed but if you feel it is still valid and has not been addressed, please re-open it with any more available information. Please note that if your question is more general and not related to documentation, [Microsoft Q&A](https://learn.microsoft.com/en-us/answers/questions/) is a great way to get questions answered.
