### ISSUE TITLE
Outdated information about package flight deletion

### ISSUE THREAD

**Issue by fralik** [MicrosoftDocs/windows-uwp#3144]
It looks like the information about package deletion is outdated or it is not possible to delete published flights. If the second option is true, then it is not clear from the documentation.

See screenshot that shows that there is no **Modify** button
![flights](https://user-images.githubusercontent.com/191278/119782039-fef46480-becb-11eb-910e-933a3762901f.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 17105757-d0a7-1427-6461-0c98f1a6ffa2
* Version Independent ID: e6f704bd-5b5e-d601-81bd-c92e1301bdd8
* Content: [Package flights - UWP applications](https://docs.microsoft.com/en-us/windows/uwp/publish/package-flights)
* Content Source: [windows-apps-src/publish/package-flights.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/publish/package-flights.md)
* Product: **uwp**
* Technology: **publish**
* GitHub Login: @hickeys
* Microsoft Alias: **hickeys**

**Comment by GrantMeStrength** [comment]
We are changing the way we track issues filed from our documentation pages: please see this [blog post](https://techcommunity.microsoft.com/t5/microsoft-learn-blog/announcing-a-new-way-to-give-feedback-on-microsoft-learn/ba-p/4027635) for more details. The Microsoft Store documentation has been updated several times since your issue was reported, and there's a good chance your problem has been addressed. Right now, this issue is being closed but if you feel it is still valid and has not been addressed, please re-open it with any more available information. Please note that if you question is more general and not related to documentation, [Microsoft Q&A](https://learn.microsoft.com/en-us/answers/questions/) is a great way to get questions answered.
