### ISSUE TITLE
Hotkey remapping stops working

### ISSUE THREAD

**Issue by btukus** [MicrosoftDocs/windows-uwp#3184]
Hotkey remapping suddenly stops working during a active session. I have reversed the alt+tab and ctrl+tab functionality. However, sometimes they revert to their original binding. To resolve this, I have to restart the application

**Comment by GrantMeStrength** [comment]
We are changing the way we track issues filed from our documentation pages: please see this [blog post](https://techcommunity.microsoft.com/t5/microsoft-learn-blog/announcing-a-new-way-to-give-feedback-on-microsoft-learn/ba-p/4027635) for more details. Right now, this issue is being closed but if you feel it is still valid and has not been addressed, please re-open it with any more available information. Please note that if you question is more general and not related to documentation, [Microsoft Q&A](https://learn.microsoft.com/en-us/answers/questions/) is a great way to get questions answered.
