### ISSUE TITLE
Please add italics and Black Weight for Windows 11 Segoe UI (Segoe UI Variable) font

### ISSUE THREAD

**Issue by RodneyAraujo** [MicrosoftDocs/windows-uwp#3217]
Hello, I have a suggestion: Please add _italics_ and Black Weight for Windows 11 Segoe UI (Segoe UI Variable) font. Thanks.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f94d411c-212f-d301-5ed2-4b5cb3e9b897
* Version Independent ID: bc4d9a15-03d1-cbc4-1dff-0d44dd1c2b35
* Content: [Typography in Windows 11 - Windows apps](https://docs.microsoft.com/en-us/windows/apps/design/signature-experiences/typography)
* Content Source: [hub/apps/design/signature-experiences/typography.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/hub/apps/design/signature-experiences/typography.md)
* Product: **uwp**
* Technology: **design**
* GitHub Login: @hickeys
* Microsoft Alias: **hickeys**

**Comment by hickeys** [comment]
Can you tell me a little more about what you'd like to see on this page? I don't see any section where italics is obviously missing. Are you looking for an example of what italics look like?

**Comment by mdtauk** [comment]
AFAIK There is no Black Weight with this new version of the typeface - and there is no Italic option either.

Perhaps what is being asked for, is for Microsoft to add Black weight to the Variable axis, and for an Italic form to also be added to the new Variable Font?

**Comment by hickeys** [comment]
@mdtauk Yeah, that makes sense. Thanks for the assist 👍

@RodneyAraujo @mdtauk is correct, then this is a product enhancement request, not a docs bug. I've added information about logging product feature requests below to help you get this request logged in the correct place. 

If, on the other hand, @mdtauk is incorrect and you're requesting a change to this document, please reopen this issue and let me know more about the changes you're requesting. Happy to work with you to make the docs better!


------


The best way to leave product feedback is through the [Feedback Hub app](https://support.microsoft.com/help/4021566/windows-10-send-feedback-to-microsoft-with-feedback-hub-app). If you return to the documentation page related to this issue and scroll to the bottom, there is a button to **leave feedback about this product**

For completeness' sake, here is a list of developer resources:

- The [Feedback Hub app](https://support.microsoft.com/help/4021566/windows-10-send-feedback-to-microsoft-with-feedback-hub-app) is the right place to suggest or lobby for a change or feature.
- Try our [forums](https://social.msdn.microsoft.com/Forums/newthread?category=windowsapps&forum=wpdevelop&prof=required) and [StackOverflow](https://stackoverflow.com/questions) for community assistance with development questions.
- The [Windows developer support](https://developer.microsoft.com/windows/support) site explains other support options.
- The [Visual Studio developer community](https://developercommunity.visualstudio.com) is helpful and responsive. You can also suggest or lobby for a change or feature by clicking the **report a problem** or **suggest a feature** buttons.
- For developer issues or suspected product bugs, visit [Microsoft Support](https://support.microsoft.com/contactus). A support engineer will determine whether the issue is a Microsoft product bug. If it is, the ticket will be free of charge.

If you receive assistance via any support resource and you believe that information would help us improve the docs, then please let us know or consider submitting a pull request.

Thanks,
Shawn
