### ISSUE TITLE
Rust in Visual Studio 2019, (not Visual Studio Code)

### ISSUE THREAD

**Issue by rossy62** [MicrosoftDocs/windows-uwp#3231]
[Enter feedback here]
It is possible to "edit" RUST programs using VIsual Studio 2019, and then just build them with cargo build on the powershell command line.  This is the route I choose as I use Visual Stdio2019 every day, and forcing users to install yet another thing is a barrier to acceptance.   It would be *nice* if there were some breadcrumbs on how to build a plug-in or update the VS2017 plug in for VS2019.  I tried the VS2017 plug in and it didin't work.  (I still get "language server" errors).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 200916ea-06cb-d017-a9e8-18d2216c5bac
* Version Independent ID: f872813c-0ab2-0f5a-45e0-e81e8479470b
* Content: [Set up your dev environment on Windows for Rust](https://docs.microsoft.com/en-us/windows/dev-environment/rust/setup)
* Content Source: [hub/dev-environment/rust/setup.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/hub/dev-environment/rust/setup.md)
* Product: **dev-environment**
* Technology: **windows-rust**
* GitHub Login: @stevewhims
* Microsoft Alias: **stwhi**

**Comment by stevewhims** [comment]
Hi, @rossy62, and thanks for filing this issue!

I don't interpret the documentation here as forcing folks to install anything. The wording is along the lines of "By using Visual Studio Code [...], you can take advantage of [...]". It's really just espousing reasons *to* use VS Code (not saying that you must). Note that we also link (a few times) to the [Rust website](https://www.rust-lang.org/), where the Learn resources show folks how to do all their development from the command-line. That way folks can choose the way they prefer. Using VS to edit, and the command-line to build, makes perfect sense. I just didn't include that in the documentation, because most Rust users are using Rust on Windows via VS Code.

Plugins are going to be out of scope for this set of content.

Thanks!
Steve
