### ISSUE TITLE
Test Purchases?

### ISSUE THREAD

**Issue by sp-stuart-harrison** [MicrosoftDocs/windows-uwp#3260]
Hi, we would like to know whether it's possible to "test" purchase items within the store as it is with other online stores, e.g. Google Play, App Store, etc.
For Google Play, you can set certain accounts as test accounts, and these have a virtual card that always succeeds in payment, but no money changes hands.
Ideally, we'd love to be able to test whether payments for in-game products is 100% functional whenever we release a new version of the game, and the voucher system that currently exists is very cumbersome for this purpose.

I've read through much documentation without finding any hint of this functionality, so if it exists, please explain how to access it on this page.  If it doesn't exist, then please take this comment/feedback as a feature request for something to be implemented!

Many thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 45e80e2c-f648-2232-eda5-dbf60ed3c45f
* Version Independent ID: d3341110-0411-f7df-3191-a700d5a814f4
* Content: [In-app purchases and trials - UWP applications](https://docs.microsoft.com/en-us/windows/uwp/monetize/in-app-purchases-and-trials#testing)
* Content Source: [windows-apps-src/monetize/in-app-purchases-and-trials.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/monetize/in-app-purchases-and-trials.md)
* Product: **uwp**
* Technology: **publish**
* GitHub Login: @hickeys
* Microsoft Alias: **hickeys**

**Comment by sp-stuart-harrison** [comment]
Hi just wondering if there is any update on this issue please?

**Comment by GrantMeStrength** [comment]
We are changing the way we track issues filed from our documentation pages: please see this [blog post](https://techcommunity.microsoft.com/t5/microsoft-learn-blog/announcing-a-new-way-to-give-feedback-on-microsoft-learn/ba-p/4027635) for more details. The Microsoft Store documentation has been updated several times since your issue was reported, and there's a good chance your problem has been addressed. Right now, this issue is being closed but if you feel it is still valid and has not been addressed, please re-open it with any more available information. Please note that if you question is more general and not related to documentation, [Microsoft Q&A](https://learn.microsoft.com/en-us/answers/questions/) is a great way to get questions answered.
