### ISSUE TITLE
marketSpecificPricings does not have support for free form prices

### ISSUE THREAD

**Issue by yxia-rblx** [MicrosoftDocs/windows-uwp#3263]
In the UWP store portal, we have the ability to create market specific pricing override with Free-form price instead of using a preset price tier, however, the REST API response doesn't have a key for that, can we add support for free-form price in the API?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c23c01e8-56f0-c7b9-206e-d840ebb3a846
* Version Independent ID: 8362e90e-94a8-102d-7d03-8e5324834ff6
* Content: [Manage add-on submissions - UWP applications](https://docs.microsoft.com/en-us/windows/uwp/monetize/manage-add-on-submissions#pricing-object)
* Content Source: [windows-apps-src/monetize/manage-add-on-submissions.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/monetize/manage-add-on-submissions.md)
* Product: **uwp**
* Technology: **publish**
* GitHub Login: @hickeys
* Microsoft Alias: **hickeys**

**Comment by hkhmsft** [comment]
Thanks so much for letting us know @yxia-rblx ! It might be worth your pursuing this as a question/feedback about the product rather than a doc bug. You got here by clicking Send feedback about > This page. If instead you click Send feedback about > This product, then you'll be taken to the right channel to leave product questions/feedback.
