### ISSUE TITLE
Missing an FAQ answer about widespread use of east const in C++/WinRT code

### ISSUE THREAD

**Issue by pjmlp** [MicrosoftDocs/windows-uwp#3264]
West const is the prevalent way of declaring const reference parameters across in industry, and also other C++ based products on the Microsoft platforms.

Why does C++/WinRT falls out of this expectation and imposes east const on our code?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cd5f0bc3-f03b-76ad-b9e2-6349a9469fcf
* Version Independent ID: ef7c2b70-1414-3880-c774-09c02a4a1634
* Content: [Frequently-asked questions about C++/WinRT - UWP applications](https://docs.microsoft.com/en-us/windows/uwp/cpp-and-winrt-apis/faq)
* Content Source: [windows-apps-src/cpp-and-winrt-apis/faq.yml](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/cpp-and-winrt-apis/faq.yml)
* Product: **uwp**
* Technology: **uwp-conceptual-docs**
* GitHub Login: @GrantMeStrength
* Microsoft Alias: **jken**

**Comment by stevewhims** [comment]
Hi, @pjmlp, and thanks for filing this issue. We feel that a FAQ isn't the right place to address this decision (and the debate behind it). Our main goal with C++/WinRT is internal consistency; we want the library to be consistent within itself, so that the code is understandable and maintainable.

I'll go ahead and close the issue, but you can still respond to it.

Thanks again!
Steve

**Comment by pjmlp** [comment]
While being inconsistent with everything else that Microsoft has released for Visual C++ customers.

I guess that is the goal of C++/WinRT, be an internal tool for Microsoft teams while we just use .NET, Win32 and WIL  instead.
