### ISSUE TITLE
Query capabilities at runtime?

### ISSUE THREAD

**Issue by pinkwerks** [MicrosoftDocs/windows-uwp#3299]
My app relies on microphone, camera and eye gaze capabilities. Is there an API to query the capabilities listed on the page, in some generic manner? At the moment it appears I have to try and use capability's API separately, and see if things go wrong. Any links to "related articles" would be helpful, thanks.

I've seen internet advice that suggests to just look in th AppxManifiest.xml, but I'm unclear if this is viable at runtime?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fdfe599a-af5b-acbc-1405-d1030d9f6661
* Version Independent ID: 85857337-8448-af63-b543-f01ef482ea09
* Content: [App capability declarations - UWP applications](https://docs.microsoft.com/en-us/windows/uwp/packaging/app-capability-declarations)
* Content Source: [windows-apps-src/packaging/app-capability-declarations.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/packaging/app-capability-declarations.md)
* Product: **uwp**
* Technology: **deployment**
* GitHub Login: @mcleanbyron
* Microsoft Alias: **mcleans**

**Comment by pinkwerks** [comment]
I think I found an answer to my question - this seems like a good link for related articles or similar:

using Windows.Security.Authorization.AppCapabilityAccess;

https://github.com/microsoft/Windows-universal-samples/blob/main/Samples/Capabilities/cs/Scenario2_RequestMany.xaml.cs

**Comment by mcleanbyron** [comment]
By "query the capabilities", do you mean a general API to prompt the user to grant access for a specified capability at run time (instead of at design time via declarations in the package manifest)? If so, yes - the [AppCapability.RequestAccessForCapabilitiesAsync](https://docs.microsoft.com/en-us/uwp/api/windows.security.authorization.appcapabilityaccess.appcapability.requestaccessforcapabilitiesasync) method is the API for doing that. Certain other APIs for specific feature areas also provide their own **RequestAccessAsync** methods to request access for the specific capability for that feature area - for example, the gaze input feature provides the [EyesPose.RequestAccessAsync](https://docs.microsoft.com/en-us/uwp/api/windows.perception.people.eyespose.requestaccessasync) method.
