### ISSUE TITLE
Win32 app UI not allowing Hide or Stop acquisitions in Partner Center

### ISSUE THREAD

**Issue by knockling** [MicrosoftDocs/windows-uwp#3329]
[There is no option in Partner Center to hide to stop acquisitions for a Win32 app for Windows 11 (preview)]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 46193979-3543-9631-f1f1-e18fb41e32aa
* Version Independent ID: 25479dfd-52f6-38ce-13a3-2390f6d8d133
* Content: [Manage your MSI or EXE app's store listing - UWP applications](https://docs.microsoft.com/en-us/windows/uwp/publish/msiexe/manage-submission-options)
* Content Source: [windows-apps-src/publish/msiexe/manage-submission-options.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/publish/msiexe/manage-submission-options.md)
* Product: **uwp**
* Technology: **uwp-conceptual-docs**
* GitHub Login: @GrantMeStrength
* Microsoft Alias: **jken**

**Comment by GrantMeStrength** [comment]
We are changing the way we track issues filed from our documentation pages: please see this [blog post](https://techcommunity.microsoft.com/t5/microsoft-learn-blog/announcing-a-new-way-to-give-feedback-on-microsoft-learn/ba-p/4027635) for more details. The Microsoft Store documentation has been updated several times since your issue was reported, and there's a good chance your problem has been addressed. Right now, this issue is being closed but if you feel it is still valid and has not been addressed, please re-open it with any more available information. Please note that if you question is more general and not related to documentation, [Microsoft Q&A](https://learn.microsoft.com/en-us/answers/questions/) is a great way to get questions answered.
