### ISSUE TITLE
Win-` or Win-Shift-`

### ISSUE THREAD

**Issue by raygivler** [MicrosoftDocs/windows-uwp#3353]
[Enter feedback here]
Online doc (https://docs.microsoft.com/en-us/windows/powertoys/fancyzones) says Win-` for fancyzones, but the installation defaulted to Win-Shift-`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6a11237d-cd08-35d0-ae4f-4b7d57df93f1
* Version Independent ID: d7eaa04f-a054-4ea7-2eb8-e7a5979b0a59
* Content: [PowerToys FancyZones utility for Windows 10](https://docs.microsoft.com/en-us/windows/powertoys/fancyzones)
* Content Source: [hub/powertoys/fancyzones.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/hub/powertoys/fancyzones.md)
* Product: **dev-environment**
* Technology: **powertoys**
* GitHub Login: @mattwojo
* Microsoft Alias: **mattwoj**

**Comment by mattwojo** [comment]
Thanks @raygivler! Just confirmed that you're right... there was a change made after PowerToys v0.39 to change from Win + ` to Win + Shift + ` to launch FancyZones so that it did not conflict with Windows Terminal shortcut to launch Quake mode. Apparently the doc update was missed to represent this change.
Thanks for bringing this to attention! Made the fix. :)
