### ISSUE TITLE
Missing C# examples

### ISSUE THREAD

**Issue by pjmlp** [MicrosoftDocs/windows-uwp#3358]
It would be nice for new developers that Windows features that are accessible from all Microsoft languages do provide samples across those languages.

It should not be expected that all .NET developers must also learn C++ to be able to read MSDN documentation.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4a609f14-2f8a-705c-84ea-4fab7e48bf85
* Version Independent ID: acbb3a6f-bfd4-68ec-f0e3-d076a0279c30
* Content: [Power management in AppLifecycle (Windows App SDK) - Windows apps](https://docs.microsoft.com/en-us/windows/apps/windows-app-sdk/applifecycle/applifecycle-power)
* Content Source: [hub/apps/windows-app-sdk/applifecycle/applifecycle-power.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/hub/apps/windows-app-sdk/applifecycle/applifecycle-power.md)
* Product: **reunion**
* Technology: **app-lifecycle**
* GitHub Login: @hickeys
* Microsoft Alias: **hickeys**

**Comment by alvinashcraft** [comment]
Thanks for submitting your feedback and we apologize for the extremely delayed response. I see that updates have not been made since the creation of this Issue, so I went ahead and added C# samples to the page. There are tabs to switch between C++ and C# now. The changes should be live shortly. 

Though the Issue will be marked as Closed, we will monitor any replies that come afterwards so treat this like an open Issue. Many thanks!
