### ISSUE TITLE
Xbox Info

### ISSUE THREAD

**Issue by TS-MSFT** [MicrosoftDocs/windows-uwp#3381]
This is the only documentation I can find about durables/consumables. It would be great to have a page for Xbox/GDK that is specific to the details for that process as well.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0b6bf4ec-0bce-52c9-124f-0d1174612745
* Version Independent ID: cd918916-1b2c-35d0-c247-824dfa4c3bdb
* Content: [Set your add-on product type and product ID - UWP applications](https://docs.microsoft.com/en-us/windows/uwp/publish/set-your-add-on-product-id)
* Content Source: [windows-apps-src/publish/set-your-add-on-product-id.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/publish/set-your-add-on-product-id.md)
* Product: **uwp**
* Technology: **publish**
* GitHub Login: @hickeys
* Microsoft Alias: **hickeys**

**Comment by GrantMeStrength** [comment]
We are changing the way we track issues filed from our documentation pages: please see this [blog post](https://techcommunity.microsoft.com/t5/microsoft-learn-blog/announcing-a-new-way-to-give-feedback-on-microsoft-learn/ba-p/4027635) for more details. The Microsoft Store documentation has been updated several times since your issue was reported, and there's a good chance your problem has been addressed. Right now, this issue is being closed but if you feel it is still valid and has not been addressed, please re-open it with any more available information. Please note that if you question is more general and not related to documentation, [Microsoft Q&A](https://learn.microsoft.com/en-us/answers/questions/) is a great way to get questions answered.
