### ISSUE TITLE
Tutorial is still failing

### ISSUE THREAD

**Issue by Gavin-Williams** [MicrosoftDocs/windows-uwp#3429]
I still can't follow this tutorial. I've reassembled the solution. When I get to the step where I build the solution I have 2 errors:

```
Path 'D:\Projects\DxWrapperProjects\_build\x64\Debug\XYRenderer\bin\XYRenderer\XYRenderer.winmd' is not a file or directory	XYRenderer.Projection	D:\Projects\DxWrapperProjects\XYRenderer.Projection\EXEC	1	

MSB3073	The command ""C:\Users\deads\.nuget\packages\microsoft.windows.cswinrt\1.3.5\cswinrt.exe" @"D:\Projects\DxWrapperProjects\_build\x64\Debug\XYRenderer.Projection\bin\cswinrt.rsp"" exited with code 1.	XYRenderer.Projection	C:\Users\deads\.nuget\packages\microsoft.windows.cswinrt\1.3.5\build\Microsoft.Windows.CsWinRT.targets	115	
```
The winmd file path is correct, Here's a copy of the path from explorer:
 
D:\Projects\DxWrapperProjects\_build\x64\Debug\XYRenderer\bin\XYRenderer
And here is the filename: XYRenderer.winmd from file properties.

Question posted here again: https://github.com/microsoft/CsWinRT/issues/1029

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a40b34b2-1bc9-25ed-b91e-cee68bc9edc1
* Version Independent ID: ecfcea0e-cad5-f4c7-6ab2-6970d4e8adcb
* Content: [Make a C# projection from a C++/WinRT component, distribute as a NuGet for .NET 5+ apps - UWP applications](https://docs.microsoft.com/en-us/windows/uwp/csharp-winrt/net-projection-from-cppwinrt-component)
* Content Source: [windows-apps-src/csharp-winrt/net-projection-from-cppwinrt-component.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/csharp-winrt/net-projection-from-cppwinrt-component.md)
* Product: **uwp**
* Technology: **platform**
* GitHub Login: @stevewhims
* Microsoft Alias: **stwhi**

**Comment by stevewhims** [comment]
Thanks, @Gavin-Williams, I'm in the process of making corrections to the docs. I also tried following along with the walkthrough, and found several points of failure that I was able to troubleshoot and resolve. I'm in the process of making fixes to the docs, so once I'm done with that I'll recommend that you try following the walkthrough again from the start. However, I would recommend following the walkthrough exactly as written.

I'll comment again here further (and in the older issue that you raised against this topic) just as soon as I've published all the fixes.

Thanks!
Steve

**Comment by stevewhims** [comment]
**UPDATE**: Late last week I tried to follow this tutorial myself, and I too was unable to be successful with the steps.

But with help, I figured out what I was doing wrong and/or where the instructions in the tutorial were wrong. I've now made 4 edit passes through this topic making many changes and corrections and those changes are now live.

I tried again today (from scratch) to follow the updated steps (exactly as they're now written), and I successfully got to the end of the tutorial in about 10-15 mins and everything worked 100%.

I don't know whether the issues you're running into are related to the changes I made to the topic, or whether they're because you're not using the sample app that the topic mentions (I see that the names in the error messages don't match the steps in the tutorial). So what I'd suggest is to follow the tutorial now exactly as written. Once you've gone through the steps, and you've been successful with the **SimpleMathComponent**, **SimpleMathProjection**, and **SampleConsoleApp** projects that the tutorial directs the reader to open/create, then you'll be in a good position to apply a similar process to your own projects.

Thanks!
Steve
