### ISSUE TITLE
Type-o "SparesePackages"

### ISSUE THREAD

**Issue by chendrixson** [MicrosoftDocs/windows-uwp#3443]
The link to the sample has a type-o.  Says Sparese instead of Sparse.  Sample itself is fine, it's just the link name.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cf28a713-4e81-45e0-a3c7-0274ba6b2e85
* Version Independent ID: 19dd0436-a27d-8e50-5e7b-06c8fcd49a3f
* Content: [Grant identity to non-packaged desktop apps - Windows apps](https://docs.microsoft.com/en-us/windows/apps/desktop/modernize/grant-identity-to-nonpackaged-apps)
* Content Source: [hub/apps/desktop/modernize/grant-identity-to-nonpackaged-apps.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/hub/apps/desktop/modernize/grant-identity-to-nonpackaged-apps.md)
* Product: **uwp**
* Technology: **apps**
* GitHub Login: @stevewhims
* Microsoft Alias: **stwhi**

**Comment by stevewhims** [comment]
Thanks, @chendrixson! I've fixed the typo (typographical error), and the fix is now live.

FYI, there's also open authoring, as described here (it's an internal site): [Quickstart—contribute to Windows developer content](https://review.docs.microsoft.com/windows-authoring-guide/quickstart?branch=main).

Thanks again!
-Steve
