### ISSUE TITLE
StoreContext in desktop app snippet needs to be corrected.

### ISSUE THREAD

**Issue by bitbound** [MicrosoftDocs/windows-uwp#3456]
The following snippet:

```
IInitializeWithWindow initWindow = (IInitializeWithWindow)(object)context;
```

produces an invalid cast error in .NET 5/6.  It needs to be changed to:

```
IInitializeWithWindow initWindow = ((object)context).As<IInitializeWithWindow>();
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 45e80e2c-f648-2232-eda5-dbf60ed3c45f
* Version Independent ID: d3341110-0411-f7df-3191-a700d5a814f4
* Content: [In-app purchases and trials - UWP applications](https://docs.microsoft.com/en-us/windows/uwp/monetize/in-app-purchases-and-trials#desktop)
* Content Source: [windows-apps-src/monetize/in-app-purchases-and-trials.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/monetize/in-app-purchases-and-trials.md)
* Product: **uwp**
* Technology: **publish**
* GitHub Login: @hickeys
* Microsoft Alias: **hickeys**

**Comment by GrantMeStrength** [comment]
We are changing the way we track issues filed from our documentation pages: please see this [blog post](https://techcommunity.microsoft.com/t5/microsoft-learn-blog/announcing-a-new-way-to-give-feedback-on-microsoft-learn/ba-p/4027635) for more details. The Microsoft Store documentation has been updated several times since your issue was reported, and there's a good chance your problem has been addressed. Right now, this issue is being closed but if you feel it is still valid and has not been addressed, please re-open it with any more available information. Please note that if you question is more general and not related to documentation, [Microsoft Q&A](https://learn.microsoft.com/en-us/answers/questions/) is a great way to get questions answered.
