### ISSUE TITLE
"get-app-reviews" endpoint not returning new reviews in Microsoft Store services API

### ISSUE THREAD

**Issue by tipa** [MicrosoftDocs/windows-uwp#3460]
I was using the "get-app-reviews" endpoint Microsoft Store services API more or less successfully the last 1.5 years.
Now, all of the sudden, it doesn't return new reviews any more. Only reviews from October 28th '21 or before are returned.
This happens both when specifying the "startDate" parameter or not. I do not use any other request parameters (except the "applicationId" of course) 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 323ca42b-9a8a-fcdd-9ef0-f69c72040897
* Version Independent ID: 693c9cdc-8f8e-a52d-6559-bbc997934292
* Content: [Get app reviews - UWP applications](https://docs.microsoft.com/en-us/windows/uwp/monetize/get-app-reviews)
* Content Source: [windows-apps-src/monetize/get-app-reviews.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/monetize/get-app-reviews.md)
* Product: **uwp**
* Technology: **publish**
* GitHub Login: @hickeys
* Microsoft Alias: **hickeys**

**Comment by GrantMeStrength** [comment]
We are changing the way we track issues filed from our documentation pages: please see this [blog post](https://techcommunity.microsoft.com/t5/microsoft-learn-blog/announcing-a-new-way-to-give-feedback-on-microsoft-learn/ba-p/4027635) for more details. The Microsoft Store documentation has been updated several times since your issue was reported, and there's a good chance your problem has been addressed. Right now, this issue is being closed but if you feel it is still valid and has not been addressed, please re-open it with any more available information. Please note that if your question is more general and not related to documentation, [Microsoft Q&A](https://learn.microsoft.com/en-us/answers/questions/) is a great way to get questions answered.
