### ISSUE TITLE
Bug when build for store submission

### ISSUE THREAD

**Issue by nickprotop** [MicrosoftDocs/windows-uwp#3486]
I have follow the provided instructions, but the app can't be build when using store submission. I can't select any target. BTW can be build normally. VS 2022, Project Reunion 0.8.

**Comment by GrantMeStrength** [comment]
We are changing the way we track issues filed from our documentation pages: please see this [blog post](https://techcommunity.microsoft.com/t5/microsoft-learn-blog/announcing-a-new-way-to-give-feedback-on-microsoft-learn/ba-p/4027635) for more details. The Microsoft Store documentation has been updated several times since your issue was reported, and there's a good chance your problem has been addressed. Right now, this issue is being closed but if you feel it is still valid and has not been addressed, please re-open it with any more available information. Please note that if you question is more general and not related to documentation, [Microsoft Q&A](https://learn.microsoft.com/en-us/answers/questions/) is a great way to get questions answered.
