### ISSUE TITLE
Why not merging the common topic pages into one place

### ISSUE THREAD

**Issue by spinningwatt** [MicrosoftDocs/windows-uwp#3494]
[Problem]
Doc structure is confusing.

I find that there are two graphic pipeline pages. One is under UWP and the other is under Win32. And the structures are quite different, when I dive into compute shader, I can only get little information under UWP doc and then be linked to the graphics pipeline pages under Win32 where the compute shader pages are way more rich in detail.

please optimize the doc structure, current doc structure is confusing. 

[Suggestion]
Maybe we can set two different entrances under respectively UWP and Win32, and all lead to the same DirectX doc deck.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9d3f1688-78fd-f4f8-0e2d-6690ff80ae35
* Version Independent ID: c5602f14-c268-8cf5-7a95-69c223f3598c
* Content: [Graphics pipeline - UWP applications](https://docs.microsoft.com/en-us/windows/uwp/graphics-concepts/graphics-pipeline)
* Content Source: [windows-apps-src/graphics-concepts/graphics-pipeline.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/graphics-concepts/graphics-pipeline.md)
* Product: **uwp**
* Technology: **platform**
* GitHub Login: @stevewhims
* Microsoft Alias: **stwhi**

**Comment by stevewhims** [comment]
Hi, @spinningwatt, and thanks for filing this issue.

Yes, it does seem that the UWP and the Win32 DirectX content would benefit from some rethinking and refactoring. I've created a backlog work item for myself, with a link back to this issue. When I get around to that work item I'll return here and reactivate this issue so that you know I'm working on it. Meanwhile, so that I'm not tracking the work in two places, I'll close this issue for now.

Thanks again!
-Steve

**Comment by spinningwatt** [comment]
Hi, @stevewhims , Thanks for reply.

It's reasonable that your team currently focus on the most important work. Waiting for a better documentation.

Thanks for your effort!
-Watt
