### ISSUE TITLE
Please provide C# examples too

### ISSUE THREAD

**Issue by harvinders** [MicrosoftDocs/windows-uwp#3496]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 165dd8a4-727f-7789-4bb2-fb98bd76380b
* Version Independent ID: d362e3da-c88c-a4d7-c51d-dd9d98487c2a
* Content: [App instancing with the app lifecycle API (Windows App SDK) - Windows apps](https://docs.microsoft.com/en-us/windows/apps/windows-app-sdk/applifecycle/applifecycle-instancing)
* Content Source: [hub/apps/windows-app-sdk/applifecycle/applifecycle-instancing.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/hub/apps/windows-app-sdk/applifecycle/applifecycle-instancing.md)
* Product: **reunion**
* Technology: **app-lifecycle**
* GitHub Login: @hickeys
* Microsoft Alias: **hickeys**

**Comment by alvinashcraft** [comment]
Thanks for submitting your feedback and we apologize for the extremely delayed response. I see that updates have not been made since the creation of this Issue, so I went ahead and added a note to this topic that points to a Windows developer blog post that shows how to do single instancing with WinUI 3 and C#. The changes should be live shortly. 

Though the Issue will be marked as Closed, we will monitor any replies that come afterwards so treat this like an open Issue. Many thanks!
