### ISSUE TITLE
Get-app-acquisitions Groupby "ageGroup" details isn't being returned

### ISSUE THREAD

**Issue by mohamad-ali-nasser** [MicrosoftDocs/windows-uwp#3517]
Hello,

I am trying to get the acquisition data on Xbox using the provided API. I am following the instructions from the below page:
[Get acquisitions data for your games and apps](https://docs.microsoft.com/en-us/windows/uwp/monetize/acquisitions-data)

Everything works fine, given a date range, sometime DeviceType doesn't works if the date is far in the past.

But whenever I use Groupby "ageGroup", I can see that the data is being groupedby but the column and the values related to the age group doesn't show. 
For example, for the same date if I don't include the "ageGroup" in the request then I will get a response that is aggregated, but if I add the "ageGroup" I receive more details but without the age information.

FYI, If I manually retrieve the same information from the [download report page](https://partner.microsoft.com/en-us/dashboard/analytics/reports/export) I am able to see the age groups, which means they are available.

Code:
```
endpoint = "https://manage.devcenter.microsoft.com/v1.0/my/analytics/appacquisitions?applicationId=<APP_ID>&startDate=11/01/2021&endDate=11/15/2021&groupby=ageGroup" 
headers = {"Authorization": 'Bearer ' + token_response['accessToken']}
response = requests.get(endpoint,  headers=headers)
response.json()
```
**Expected response:**
A json response with the age included 

```
{'DataFreshnessTimestamp': '2021-11-26T16:30:00',
 'TotalCount': 205,
 'Value': [{'acquisitionQuantity': 1,
   'applicationId': 'APP_ID',
   'date': '2020-11-07',
   **'age': '0-17',**
   'purchasePriceLocalAmount': 24.35,
   'purchasePriceUSDAmount': 24.35,
   'purchaseTaxLocalAmount': 1.86,
   'purchaseTaxUSDAmount': 1.86},
  {'acquisitionQuantity': 1,
   'applicationId': 'APP_ID',
   'date': '2020-11-07',
   **'age': 'over50',**
   'purchasePriceLocalAmount': 42.95,
   'purchasePriceUSDAmount': 7.48055808022618,
   'purchaseTaxLocalAmount': 5.22,
   'purchaseTaxUSDAmount': 0.909162122905254}}
```

**Actual Resposne:**
Json that is more detailed except the age key isn't showing.

```
{'DataFreshnessTimestamp': '2021-11-26T16:30:00',
 'TotalCount': 205,
 'Value': [{'acquisitionQuantity': 1,
   'applicationId': 'APP_ID',
   'date': '2020-11-07',
   'purchasePriceLocalAmount': 24.35,
   'purchasePriceUSDAmount': 24.35,
   'purchaseTaxLocalAmount': 1.86,
   'purchaseTaxUSDAmount': 1.86},
  {'acquisitionQuantity': 1,
   'applicationId': 'APP_ID',
   'date': '2020-11-07',
   'purchasePriceLocalAmount': 42.95,
   'purchasePriceUSDAmount': 7.48055808022618,
   'purchaseTaxLocalAmount': 5.22,
   'purchaseTaxUSDAmount': 0.909162122905254}}
```

**Comment by GrantMeStrength** [comment]
We are changing the way we track issues filed from our documentation pages: please see this [blog post](https://techcommunity.microsoft.com/t5/microsoft-learn-blog/announcing-a-new-way-to-give-feedback-on-microsoft-learn/ba-p/4027635) for more details. The Microsoft Store documentation has been updated several times since your issue was reported, and there's a good chance your problem has been addressed. Right now, this issue is being closed but if you feel it is still valid and has not been addressed, please re-open it with any more available information. Please note that if you question is more general and not related to documentation, [Microsoft Q&A](https://learn.microsoft.com/en-us/answers/questions/) is a great way to get questions answered.
