### ISSUE TITLE
When will Multilingual app toolkit 4.0 Editor support Visual Studio 2022

### ISSUE THREAD

**Issue by robloo** [MicrosoftDocs/windows-uwp#3521]
As titled, the Multilingual app toolkit 4.0 Editor tooling needs an update to support Visual Studio 2022. The existing application works just fine; however, the Visual Studio extension does not. The extension needs to be updated: https://marketplace.visualstudio.com/items?itemName=MultilingualAppToolkit.MultilingualAppToolkit-18308

I don't know where to file this or who to contact so just put it here for now.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 91476ebf-8385-e698-7bdf-08481be7cf21
* Version Independent ID: 91476ebf-8385-e698-7bdf-08481be7cf21
* Content: [Multilingual App Toolkit Editor - Windows app development - Windows apps](https://docs.microsoft.com/en-us/windows/apps/design/globalizing/multilingual-app-toolkit-editor-downloads#feedback)
* Content Source: [hub/apps/design/globalizing/multilingual-app-toolkit-editor-downloads.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/hub/apps/design/globalizing/multilingual-app-toolkit-editor-downloads.md)
* Product: **uwp**
* Technology: **design**
* GitHub Login: @Karl-Bridge-Microsoft
* Microsoft Alias: **kbridge**

**Comment by Karl-Bridge-Microsoft** [comment]
Thanks for logging this issue. As this is a product issue and not a documentation issue, I suggest using the [q&a](https://marketplace.visualstudio.com/items?itemName=MultilingualAppToolkit.MultilingualAppToolkit-18308&ssr=false#qna) and [review ](https://marketplace.visualstudio.com/items?itemName=MultilingualAppToolkit.MultilingualAppToolkit-18308&ssr=false#review-details)feedback options for this product download.

Other developer support resources include:

- [Microsoft Q&A](https://docs.microsoft.com/answers/topics/windows-uwp.html) offers relevant and timely answers to your technical problems from a community of experts and Microsoft engineers.
- For community assistance with development questions, there are our [forums](https://social.msdn.microsoft.com/Forums/newthread?category=windowsapps&forum=wpdevelop&prof=required), and [StackOverflow](https://stackoverflow.com/questions).
- The [Windows developer support](https://developer.microsoft.com/windows/support) site explains other support options.
- The [Visual Studio developer community](https://developercommunity.visualstudio.com) is available, and responsive. The former User Voice feature is now there on the **Suggest a feature** tab, if you want to lobby for a change, a feature, or to make a suggestion.
- For developer issues, or suspected product bugs, there's [Microsoft Support](https://support.microsoft.com/contactus); a support engineer will look at the repro and see whether the issue is a Microsoft product bug, or something else. If it's a bug with a Microsoft product then the ticket will be free of charge.

If you receive assistance via any of these support resources, and you believe that information would help us improve the docs, then please come back and let us know.
