### ISSUE TITLE
Not correct for VS 2022

### ISSUE THREAD

**Issue by Meister1867** [MicrosoftDocs/windows-uwp#3522]
The page instructions for the creation of a WinUI app does not appear to be correct for VS 2022.  There is no WinUI type.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9564158a-dfea-b690-7b5e-5f6987019710
* Version Independent ID: 1a90b127-6ad9-a28e-0ee4-16170021b104
* Content: [Create a new project that uses the Windows App SDK - Windows apps](https://docs.microsoft.com/en-us/windows/apps/winui/winui3/create-your-first-winui3-app)
* Content Source: [hub/apps/winui/winui3/create-your-first-winui3-app.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/hub/apps/winui/winui3/create-your-first-winui3-app.md)
* Product: **reunion**
* Technology: **winui-conceptual**
* GitHub Login: @Karl-Bridge-Microsoft
* Microsoft Alias: **kbridge**

**Comment by stevewhims** [comment]
Sorry for the delay in responding.

The problem was probably that this topic didn't have a link to [Install tools for the Windows App SDK](https://docs.microsoft.com/windows/apps/windows-app-sdk/set-up-your-development-environment). The instructions there are tailored for the version of Visual Studio you're using. For example, for VS2022 17.1, in the **Installation details** pane of the installation dialog, for the C# and/or C++ workload, you'd need to check **Windows App SDK C#/C++ Templates" (at the bottom of the list). Once you've done that, you'll have the WinUI 3 project and item templates in Visual Studio. For other versions of VS, you'll need to install the VSIX. All details are at the link above.

I've fixed both topics now.

-Steve
