### ISSUE TITLE
Is \ must in cid?

### ISSUE THREAD

**Issue by shisbn** [MicrosoftDocs/windows-uwp#3529]
[Enter feedback here]
I have a question.
There is an example **&cid=custom\_campaign** in this page.  Can I use **&cid=custom_campaign** without ** \ ** because it works well when I test in browser? Currently both could open my app page in MS store.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 19da496f-5bb3-8b60-ad77-93aebb828725
* Version Independent ID: ba0ef101-89fa-77b5-be17-a0b8b92ca0eb
* Content: [Create a custom app promotion campaign - UWP applications](https://docs.microsoft.com/en-us/windows/uwp/publish/create-a-custom-app-promotion-campaign#embed-a-custom-campaign-id-to-your-apps-microsoft-store-page-url)
* Content Source: [windows-apps-src/publish/create-a-custom-app-promotion-campaign.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/publish/create-a-custom-app-promotion-campaign.md)
* Product: **uwp**
* Technology: **publish**
* GitHub Login: @hickeys
* Microsoft Alias: **hickeys**

**Comment by GrantMeStrength** [comment]
We are changing the way we track issues filed from our documentation pages: please see this [blog post](https://techcommunity.microsoft.com/t5/microsoft-learn-blog/announcing-a-new-way-to-give-feedback-on-microsoft-learn/ba-p/4027635) for more details. The Microsoft Store documentation has been updated several times since your issue was reported, and there's a good chance your problem has been addressed. Right now, this issue is being closed but if you feel it is still valid and has not been addressed, please re-open it with any more available information. Please note that if your question is more general and not related to documentation, [Microsoft Q&A](https://learn.microsoft.com/en-us/answers/questions/) is a great way to get questions answered.
