### ISSUE TITLE
mica material windows 11 only work on one screen

### ISSUE THREAD

**Issue by andikasujanadi** [MicrosoftDocs/windows-uwp#3534]
If I open window that have mica material, for example setting app, mica material only work on one monitor, when I move the window to second monitor it just show solid color

**Comment by Karl-Bridge-Microsoft** [comment]
As this is not feedback specifically about the documentation, but more a product support request. Here are some developer support resources to try instead:

- [Microsoft Q&A](https://docs.microsoft.com/answers/topics/windows-uwp.html) offers relevant and timely answers to your technical problems from a community of experts and Microsoft engineers.
- For community assistance with development questions, there are our [forums](https://social.msdn.microsoft.com/Forums/newthread?category=windowsapps&forum=wpdevelop&prof=required), and [StackOverflow](https://stackoverflow.com/questions).
- The [Windows developer support](https://developer.microsoft.com/windows/support) site explains other support options.
- The [Visual Studio developer community](https://developercommunity.visualstudio.com) is available, and responsive. The former User Voice feature is now there on the **Suggest a feature** tab, if you want to lobby for a change, a feature, or to make a suggestion.
- For developer issues, or suspected product bugs, there's [Microsoft Support](https://support.microsoft.com/contactus); a support engineer will look at the repro and see whether the issue is a Microsoft product bug, or something else. If it's a bug with a Microsoft product then the ticket will be free of charge.

If you receive assistance via any of these support resources, and you believe that information would help us improve the docs, then please come back and let us know.
