### ISSUE TITLE
Is there a reference to HDR page?

### ISSUE THREAD

**Issue by andkirby** [MicrosoftDocs/windows-uwp#3585]
Hi team,

[I'm looking a way to open the Display > HDR page](https://stackoverflow.com/questions/70487069/how-to-create-a-shortcut-or-a-link-to-the-windows-11-settings-hdr-page).
The mentioned page does not have it.

Is it  missing or it wasn't implemented?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 987ec16c-9456-93a4-177a-dbd563be7eb7
* Version Independent ID: f41f0344-f7f6-f092-a6bf-fc4184a9b460
* Content: [Launch the Windows Settings app - UWP applications](https://docs.microsoft.com/en-us/windows/uwp/launch-resume/launch-settings-app)
* Content Source: [windows-apps-src/launch-resume/launch-settings-app.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/launch-resume/launch-settings-app.md)
* Product: **uwp**
* Technology: **processes-and-threading**
* GitHub Login: @GrantMeStrength
* Microsoft Alias: **jken**

**Comment by Karl-Bridge-Microsoft** [comment]
There doesn't appear to be a direct ms-settings uri launcher for the hdr settings page.

Here are some developer support resources you could try to get more info from:

- [Microsoft Q&A](https://docs.microsoft.com/answers/topics/windows-uwp.html) offers relevant and timely answers to your technical problems from a community of experts and Microsoft engineers.
- For community assistance with development questions, there are our [forums](https://social.msdn.microsoft.com/Forums/newthread?category=windowsapps&forum=wpdevelop&prof=required), and [StackOverflow](https://stackoverflow.com/questions).
- The [Windows developer support](https://developer.microsoft.com/windows/support) site explains other support options.
- For developer issues, or suspected product bugs, there's [Microsoft Support](https://support.microsoft.com/contactus); a support engineer will look at the repro and see whether the issue is a Microsoft product bug, or something else. If it's a bug with a Microsoft product then the ticket will be free of charge.

If you receive assistance via any of these support resources, and you believe that information would help us improve the docs, then please come back and let us know.
