### ISSUE TITLE
Controversial recommendations/requirements

### ISSUE THREAD

**Issue by QuasimodoPrograms** [MicrosoftDocs/windows-uwp#3588]
Recommendations say "Frame rate and resolution should match the source material. For example, content shot at 720p60 should be encoded and uploaded at 720p60."

While below is the requirement:
The video resolution must be 1920 x 1080 pixels.

Although the requirement makes less sense, it seems to have a higher priority.
I suggest:

- reformulating the requirement to "at least 720p60"
- changing the recommendation to "1920 x 1080 pixels"
- putting requirements earlier than recommendations

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c806b00b-2775-bffd-54a8-8c564b80eb44
* Version Independent ID: 8b176274-ef89-ff27-140f-29a6193843a4
* Content: [App screenshots, images, and trailers - UWP applications](https://docs.microsoft.com/en-us/windows/uwp/publish/app-screenshots-and-images#trailers)
* Content Source: [windows-apps-src/publish/app-screenshots-and-images.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/publish/app-screenshots-and-images.md)
* Product: **uwp**
* Technology: **publish**
* GitHub Login: @hickeys
* Microsoft Alias: **hickeys**

**Comment by GrantMeStrength** [comment]
We are changing the way we track issues filed from our documentation pages: please see this [blog post](https://techcommunity.microsoft.com/t5/microsoft-learn-blog/announcing-a-new-way-to-give-feedback-on-microsoft-learn/ba-p/4027635) for more details. The Microsoft Store documentation has been updated several times since your issue was reported, and there's a good chance your problem has been addressed. Right now, this issue is being closed but if you feel it is still valid and has not been addressed, please re-open it with any more available information. Please note that if you question is more general and not related to documentation, [Microsoft Q&A](https://learn.microsoft.com/en-us/answers/questions/) is a great way to get questions answered.
