### ISSUE TITLE
Outdated windows-rs

### ISSUE THREAD

**Issue by SBeausoleil** [MicrosoftDocs/windows-uwp#3591]
The version of windows-rs that is used for this tutorial is completely outdated and incompatible with the latest version (0.29.0) of windows-rs. As of such, this tutorial is not useful for learning the current version of the windows api for rust.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9a621c9b-3a97-3d49-4de9-b309a491a75b
* Version Independent ID: 492ab689-9940-02ee-2f38-bafcd1dc9ad2
* Content: [RSS reader tutorial (Rust for Windows with VS Code)](https://docs.microsoft.com/en-us/windows/dev-environment/rust/rss-reader-rust-for-windows)
* Content Source: [hub/dev-environment/rust/rss-reader-rust-for-windows.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/hub/dev-environment/rust/rss-reader-rust-for-windows.md)
* Product: **dev-environment**
* Technology: **windows-rust**
* GitHub Login: @stevewhims
* Microsoft Alias: **stwhi**

**Comment by stevewhims** [comment]
Thanks for the heads up, @SBeausoleil. I've created a work item for myself (on my backlog) to take a look at this. That work item contains a link to this GitHub issue, so I'll go ahead and close this issue for now (so that I'm not tracking the work in two places), and I'll reopen this issue when I get to my work item.

Thanks again!
Steve
