### ISSUE TITLE
(Link to) Microsoft Form for creating PFN mapping request not working

### ISSUE THREAD

**Issue by mvldk** [MicrosoftDocs/windows-uwp#3594]
The Microsoft Form used to create the PFN mapping request is not working. The form gives the following error when opened: "We will be back soon.". Underlying error: "{error: {code: "5000", message: "This form is closed.", @ms.form.error.type: "ExpectedFailure",…}}"

[The link to the form](https://aka.ms/windowsappsdk-push-mapping) is found under [Step 4: Map your app's package family name to its Azure AppId](https://docs.microsoft.com/en-us/windows/apps/windows-app-sdk/notifications/push/push-quickstart#step-4-map-your-apps-package-family-name-to-its-azure-appid). If this step can not be completed, I guess this whole page/quickstart is obsolete.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3b81f1e6-4945-60eb-76bf-0f60d68ba480
* Version Independent ID: 41f4799e-83ba-f0a8-43ae-770f8f0edb3e
* Content: [Quickstart Push notifications in the Windows App SDK - Windows apps](https://docs.microsoft.com/en-us/windows/apps/windows-app-sdk/notifications/push/push-quickstart)
* Content Source: [hub/apps/windows-app-sdk/notifications/push/push-quickstart.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/hub/apps/windows-app-sdk/notifications/push/push-quickstart.md)
* Product: **reunion**
* Technology: ****
* GitHub Login: @hickeys
* Microsoft Alias: **hickeys**

**Comment by GrantMeStrength** [comment]
We are changing the way we track issues filed from our documentation pages: please see this [blog post](https://techcommunity.microsoft.com/t5/microsoft-learn-blog/announcing-a-new-way-to-give-feedback-on-microsoft-learn/ba-p/4027635) for more details. The Microsoft Store documentation has been updated several times since your issue was reported, and there's a good chance your problem has been addressed. Right now, this issue is being closed but if you feel it is still valid and has not been addressed, please re-open it with any more available information. Please note that if you question is more general and not related to documentation, [Microsoft Q&A](https://learn.microsoft.com/en-us/answers/questions/) is a great way to get questions answered.
