### ISSUE TITLE
Return statusCode 500 when getting ad campaign performance data

### ISSUE THREAD

**Issue by shawnz42** [MicrosoftDocs/windows-uwp#3614]
I got `{ "statusCode": 500, "message": "Internal server error", "activityId": "xxxx-xxxxx-xxxxx" }` when call this api

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1cf06dba-b858-dfae-d94b-df7d03bf13e2
* Version Independent ID: 542ba960-0576-1aa0-7f82-17cc54ce9308
* Content: [Get ad campaign performance data - UWP applications](https://docs.microsoft.com/en-us/windows/uwp/monetize/get-ad-campaign-performance-data)
* Content Source: [windows-apps-src/monetize/get-ad-campaign-performance-data.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/monetize/get-ad-campaign-performance-data.md)
* Product: **uwp**
* Technology: **publish**
* GitHub Login: @hickeys
* Microsoft Alias: **hickeys**

**Comment by GrantMeStrength** [comment]
We are changing the way we track issues filed from our documentation pages: please see this [blog post](https://techcommunity.microsoft.com/t5/microsoft-learn-blog/announcing-a-new-way-to-give-feedback-on-microsoft-learn/ba-p/4027635) for more details. The Microsoft Store documentation has been updated several times since your issue was reported, and there's a good chance your problem has been addressed. Right now, this issue is being closed but if you feel it is still valid and has not been addressed, please re-open it with any more available information. Please note that if you question is more general and not related to documentation, [Microsoft Q&A](https://learn.microsoft.com/en-us/answers/questions/) is a great way to get questions answered.
