### ISSUE TITLE
emoji and HTML codes issue in the description

### ISSUE THREAD

**Issue by Sissiexiao** [MicrosoftDocs/windows-uwp#3635]
[Could you please let us know whether we can add emoji and HTML codes to format/structure the text, like <b>text</b>? Just like the description in GooglePlay.]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ba2b2242-0353-38ec-b5ef-4de5154fe6e2
* Version Independent ID: c88195fd-0ff9-c076-37cf-fe78ebb09897
* Content: [Write a great app description - UWP applications](https://docs.microsoft.com/en-us/windows/uwp/publish/write-a-great-app-description)
* Content Source: [windows-apps-src/publish/write-a-great-app-description.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/publish/write-a-great-app-description.md)
* Product: **uwp**
* Technology: **publish**
* GitHub Login: @hickeys
* Microsoft Alias: **hickeys**

**Comment by GrantMeStrength** [comment]
We are changing the way we track issues filed from our documentation pages: please see this [blog post](https://techcommunity.microsoft.com/t5/microsoft-learn-blog/announcing-a-new-way-to-give-feedback-on-microsoft-learn/ba-p/4027635) for more details. The Microsoft Store documentation has been updated several times since your issue was reported, and there's a good chance your problem has been addressed. Right now, this issue is being closed but if you feel it is still valid and has not been addressed, please re-open it with any more available information. Please note that if you question is more general and not related to documentation, [Microsoft Q&A](https://learn.microsoft.com/en-us/answers/questions/) is a great way to get questions answered.
