### ISSUE TITLE
Access to application windows and display broken for (some?) UWP applications like Snip & Sketch when some/a virtualized display device (Windows Mixed Reality Headset) is connected.

### ISSUE THREAD

**Issue by ErrorRaffyline0** [MicrosoftDocs/windows-uwp#3647]
[deleted]

**Comment by Karl-Bridge-Microsoft** [comment]
Hi @TheJokingTeen - This feedback is not specifically about the documentation, but rather a support request. Please click the product feedback link at the bottom of the topic, or contact the following support channel:

- For developer issues, or suspected product bugs, use [Microsoft Support](https://support.microsoft.com/contactus) where a support engineer will look at the repro and see whether the issue is a Microsoft product bug, or something else.

Here is a list of other developer support resources that might be able to help with your issue:

- For community assistance with development questions, there are our [forums](https://social.msdn.microsoft.com/Forums/newthread?category=windowsapps&forum=wpdevelop&prof=required), and [StackOverflow](https://stackoverflow.com/questions).
- The [Windows developer support](https://developer.microsoft.com/windows/support) site explains other support options.
- The [Visual Studio developer community](https://developercommunity.visualstudio.com) is available, and responsive. The former User Voice feature is now there on the **Suggest a feature** tab, if you want to lobby for a change, a feature, or to make a suggestion.
- The [Feedback Hub app](https://support.microsoft.com/help/4021566/windows-10-send-feedback-to-microsoft-with-feedback-hub-app) is the right place to lobby for a change, a feature, or to make a suggestion.

If you receive assistance via any support resource, and you believe that information would help us improve the docs, then please come back and let us know.

**Comment by ErrorRaffyline0** [comment]
It is not a support request...
