### ISSUE TITLE
User Activity features sync is ended / no support for MSA user?

### ISSUE THREAD

**Issue by visionarylab** [MicrosoftDocs/windows-uwp#3678]
> Note
> 
> Starting in July 2021, users who have activity history synced across their Windows devices through their Microsoft Account (MSA) will no longer have the option to upload new activity in Timeline. They'll still be able to use Timeline and see their activity history (information about recent apps, websites and files) on their local PC. AAD-connected accounts won't be impacted.

Above quote, may already mention the issue. So if anyone develop against the user activity api, the upload new activity will give error for Microsoft Account"(MSA)?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d5de106a-1c57-7d56-2297-0a90d63e4aab
* Version Independent ID: 4c59211e-710a-8d9c-fb2a-1e0c0cae8550
* Content: [Continue user activity, even across devices - UWP applications](https://docs.microsoft.com/en-us/windows/uwp/launch-resume/useractivities)
* Content Source: [windows-apps-src/launch-resume/useractivities.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/launch-resume/useractivities.md)
* Product: **uwp**
* Technology: **processes-and-threading**
* GitHub Login: @GrantMeStrength
* Microsoft Alias: **jken**

**Comment by GrantMeStrength** [comment]
We are changing the way we track issues filed from our documentation pages: please see this [blog post](https://techcommunity.microsoft.com/t5/microsoft-learn-blog/announcing-a-new-way-to-give-feedback-on-microsoft-learn/ba-p/4027635) for more details. Right now, this issue is being closed but if you feel it is still valid and has not been addressed, please re-open it with any more available information. Please note that if your question is more general and not related to documentation, [Microsoft Q&A](https://learn.microsoft.com/en-us/answers/questions/) is a great way to get questions answered.
