### ISSUE TITLE
No WinUI Project Type!

### ISSUE THREAD

**Issue by markolbert** [MicrosoftDocs/windows-uwp#3682]
Gee, so I follow the instructions, download and install almost 20GB of additional stuff for VS2022 (v17.1)...and the very first instructions on adding a WinUI3 app to my C# solution are flat out wrong. Because there is no WinUI project type listed in the filter dropdown.

Does anyone bother to test this stuff before the software and the documentation is released?!?

Sheesh.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9564158a-dfea-b690-7b5e-5f6987019710
* Version Independent ID: 1a90b127-6ad9-a28e-0ee4-16170021b104
* Content: [Create a new project that uses the Windows App SDK - Windows apps](https://docs.microsoft.com/en-us/windows/apps/winui/winui3/create-your-first-winui3-app)
* Content Source: [hub/apps/winui/winui3/create-your-first-winui3-app.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/hub/apps/winui/winui3/create-your-first-winui3-app.md)
* Product: **reunion**
* Technology: **winui-conceptual**
* GitHub Login: @Karl-Bridge-Microsoft
* Microsoft Alias: **kbridge**

**Comment by stevewhims** [comment]
Hi, @markolbert, and thanks for filing this issue.

It looks like this topic doesn't have a link to [Install tools for the Windows App SDK](https://docs.microsoft.com/windows/apps/windows-app-sdk/set-up-your-development-environment). The instructions there  are tailored for the version of Visual Studio you're using. For 17.1, in the **Installation details** pane of the installation dialog, for the C# and/or C++ workload, you'd need to **Windows App SDK C#/C++ Templates" (at the bottom of the list). Once you've done, that you'll have the WinUI 3 project and item templates in Visual Studio.

That might be the missing step for you. I'm currently working on adding that missing hyperlink so that folks will know what to install, and how.

-Steve

**Comment by markolbert** [comment]
Thanx, Steve.

-          Mark

**Comment by stevewhims** [comment]
Just an update. I added the link I mentioned. While I was editing the topic I also removed the duplicated content (it was duplicated across the tabs), removed the tabs, and tidied up, corrected, and simplified the topic. I feel it's a lot better now, but I'm open to feedback. :)

I'll go ahead and close the issue.

Many thanks!
-Steve
