### ISSUE TITLE
"Building unpackaged app" tutorial should explain how to get XAML to work in unpackaged

### ISSUE THREAD

**Issue by asklar** [MicrosoftDocs/windows-uwp#3695]
The content only goes as far as calling the DD APIs, but doesn't provide an offramp to creating a GUI app

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2a490a57-1f12-5646-2906-dca6ead89518
* Version Independent ID: 7ea6aaad-bf8d-2a2e-3012-11e8e2ebe917
* Content: [Advanced tutorial - Build and deploy an unpackaged app that uses the Windows App SDK - Windows apps](https://docs.microsoft.com/en-us/windows/apps/windows-app-sdk/tutorial-unpackaged-deployment?tabs=cpp)
* Content Source: [hub/apps/windows-app-sdk/tutorial-unpackaged-deployment.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/hub/apps/windows-app-sdk/tutorial-unpackaged-deployment.md)
* Product: **reunion**
* Technology: **deployment**
* GitHub Login: @zaryaf
* Microsoft Alias: **zafaraj**

**Comment by stevewhims** [comment]
Yes, as it's currently written this topic is focused solely on a console app. But a while ago I went through this topic except I created a WPF project instead, and that worked. I had to add \<RuntimeIdentifiers\>win10-x64\</RuntimeIdentifiers\>, and I proved that WinAppSDK was being loaded ok, and that I could call some WinAppSDK APIs (not necessarily exactly the code in the tutorial, but something equally interesting, I think).

That was about a month ago and I keep planning to update this topic with that experiment when I get some time. So at the same time I'll see what I can do about providing the offramp you mention. Of course, the "GUI app" in question could be WPF or WinForms or Win32, but it wouldn't be a WinUI 3 app (since you wouldn't need to bootstrap that).

So I've back-logged that work for myself and I'll track it along with my existing workstreams. I'll go ahead and close this so that I'm not tracking it twice, and I'll come back here and update when I get around to doing the work.

Thanks!
-Steve

**Comment by asklar** [comment]
thanks @stevewhims ! Just to clarify, when building a winui3 _unpackaged_ app, I expect that _someone_ still needs to bootstrap the framework, as well as whatever manifest entries we need, CRT requirements, etc. I realize some of these are changing between 1.0 and future, but as of today we don't have a public sample that shows how to build a WinUI 3 unpackaged app.

**Comment by stevewhims** [comment]
I see, good point! Ok, I'll investigate that scenario, too. :)
