### ISSUE TITLE
Issue with rich activation availability

### ISSUE THREAD

**Issue by zhaparoff** [MicrosoftDocs/windows-uwp#3699]
Documentation states that rich activation is available for preview and experimental channels only.
But the feature list reports that is should be available for 1.0 stable
https://docs.microsoft.com/en-us/windows/apps/windows-app-sdk/release-channels#features-available-by-release-channel
https://portal.productboard.com/winappsdk/1-windows-app-sdk/c/11-activation-apis

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2d56a3de-3af1-6b72-ab58-c4cecf7b7dc7
* Version Independent ID: ef4aff1b-9f9c-2300-34c8-dff5e54aceb6
* Content: [Rich activation with the app lifecycle API (Windows App SDK) - Windows apps](https://docs.microsoft.com/en-us/windows/apps/windows-app-sdk/applifecycle/applifecycle-rich-activation)
* Content Source: [hub/apps/windows-app-sdk/applifecycle/applifecycle-rich-activation.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/hub/apps/windows-app-sdk/applifecycle/applifecycle-rich-activation.md)
* Product: **reunion**
* Technology: **app-lifecycle**
* GitHub Login: @hickeys
* Microsoft Alias: **hickeys**

**Comment by alvinashcraft** [comment]
Thanks for submitting your feedback and we apologize for the extremely delayed response. I see that updates have not been made since the creation of this Issue, so I went ahead and updated this section to remove the preview/experimental info. The changes should be live shortly. 

Though the Issue will be marked as Closed, we will monitor any replies that come afterwards so treat this like an open Issue. Many thanks!
