### ISSUE TITLE
CngKey and low level topics

### ISSUE THREAD

**Issue by SuperJMN** [MicrosoftDocs/windows-uwp#370]
In this page, you say this:  "Next, the server must validate the signature. When you request the public key and send it to the server to use for future validation, it is in an ASN.1-encoded publicKeyInfo blob.If you look at the Windows Hello code sample on GitHub, you will see there are helper classes to wrap Crypt32 functions to translate the ASN.1-encoded blob to a CNG blob, which is more commonly used. The blob contains the public key algorithm, which is RSA, and the RSA public key."

I think that paragraph is pretty obscure. Why are you using helper classes? We are you using functions of an unmanaged DLL? What do you mean that the public is an "ASN.1-encoded publicKeyInfo"? Why do you have to convert it "to a CNG blob". What is that? Later, you state the blob contains the public key algorithm, which is RSA, and the RSA public key".

Another question. Which algorith does Windows Hello use when it signs data?

Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b178d625-6b36-0bfb-6944-31bd7c2dfef6
* Version Independent ID: 45a7d78c-d23a-9f9a-1b7e-83728a9032f8
* Content: [Windows Hello - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/security/microsoft-passport#comments-container)
* Content Source: [windows-apps-src/security/microsoft-passport.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/security/microsoft-passport.md)
* Service: **unspecified**
* GitHub Login: @awkoren
* Microsoft Alias: **alkoren**

**Comment by stevewhims** [comment]
Hi, @SuperJMN, I'm sorry for the delay in getting back to you, I know that you filed this issue a long time ago.

I've passed your request for more info along to the subject-matter experts. If/when they get back to me with that info, I'll relay it to you and I'll also update this topic with it.

Thanks for your patience.
~Steve

**Comment by stevewhims** [comment]
Hi, @SuperJMN, again I really apologize for the delay in resolving this issue. I've just sent a reminder ping to the subject-matter experts. I'll periodically do that again until we get info.

~Steve

**Comment by stevewhims** [comment]
Hi, @SuperJMN, my contact within the product team has helped us out with the following info. I will incorporate this info into the topic itself.

In the example, we're converting the ASN.1 encoded blob to a CNG blob so that it can be used with CNG (https://docs.microsoft.com/en-us/windows/desktop/SecCNG/cng-portal) and the BCrypt API. If you do a quick lookup of the CNG blob it will point you to the related BCrypt structure (https://docs.microsoft.com/en-us/windows/desktop/api/bcrypt/ns-bcrypt-_bcrypt_key_blob). This API surface can be used for authentication and encryption in Windows applications. ASN.1 is a documented standard for communicating data structures that can be serialized, and it's commonly used in public key cryptography and with certificates. That's why the public key information is returned in this manner. The public key is an RSA key; so that's the algorithm that Windows Hello uses when it signs data.

Hope that helps! And again sorry for the delay in getting back to you.

**Comment by stevewhims** [comment]
Hi, @SuperJMN, my updates are now published within the topic. Again, thanks for raising this issue and for helping us improve the documentation. I'll go ahead and close this issue now, but please reopen it if you feel I closed it prematurely. ~Steve

**Comment by SuperJMN** [comment]
Thanks! the fix comes a bit late for, but it's fixed! :) Ready for the next who may need it.

**Comment by stevewhims** [comment]
Thanks, José, you're right, and my apologies that it took so long to get an answer! ~Steve

**Comment by SuperJMN** [comment]
No problem!
