### ISSUE TITLE
Feedback forum is closed

### ISSUE THREAD

**Issue by gekka** [MicrosoftDocs/windows-uwp#3701]
> If you have feedback on the policies, please let us know by commenting in [our forum](https://social.msdn.microsoft.com/Forums/windowsapps/home?forum=windowsstore). We will consider every comment.

Many forums in social.msdn.microsoft.com is closed, and moved to [Q&A](https://docs.microsoft.com/en-us/answers/products/).
As a result, it is no longer possible feedback by current link.
No one can know where the correct link is now.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8e47bfea-cf8e-d716-9880-6c15c31fcbdf
* Version Independent ID: ba95989d-2cb0-1644-7b38-24b2eab3b8c7
* Content: [Microsoft Store Policies - UWP applications](https://docs.microsoft.com/en-us/windows/uwp/publish/store-policies)
* Content Source: [windows-apps-src/publish/store-policies.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/publish/store-policies.md)
* Product: **uwp**
* Technology: **publish**
* GitHub Login: @hickeys
* Microsoft Alias: **hickeys**

**Comment by GrantMeStrength** [comment]
We are changing the way we track issues filed from our documentation pages: please see this [blog post](https://techcommunity.microsoft.com/t5/microsoft-learn-blog/announcing-a-new-way-to-give-feedback-on-microsoft-learn/ba-p/4027635) for more details. The Microsoft Store documentation has been updated several times since your issue was reported, and there's a good chance your problem has been addressed. Right now, this issue is being closed but if you feel it is still valid and has not been addressed, please re-open it with any more available information. Please note that if you question is more general and not related to documentation, [Microsoft Q&A](https://learn.microsoft.com/en-us/answers/questions/) is a great way to get questions answered.
