### ISSUE TITLE
Missing documentation for --query

### ISSUE THREAD

**Issue by paulomorgado** [MicrosoftDocs/windows-uwp#3708]
This command (and others) mentions `--query`, but the explanation is very simple and there are no examples.

* How can I use `--query`?
* What can I do with `--query` for that I can't do without it?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cffe194d-966f-9c21-c7c7-c5470d2bad72
* Version Independent ID: 77750236-9104-a3aa-89ad-92bbd7e72ed3
* Content: [search Command](https://docs.microsoft.com/en-us/windows/package-manager/winget/search)
* Content Source: [hub/package-manager/winget/search.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/hub/package-manager/winget/search.md)
* Product: **dev-environment**
* Technology: **package-manager**
* GitHub Login: @KevinLaMS
* Microsoft Alias: **kevinla**

**Comment by mattwojo** [comment]
Hey @paulomorgado - 
That `--query` is the default argument in the `winget search` ...so it doesn't really do anything. It's only needed in the context of using it for an API. I just updated the page to make that more clear -- https://github.com/MicrosoftDocs/windows-uwp/commit/97d6db83b6fc39bbf1240237b9055cd2ee315998
Sorry for the confusion. And thanks for contributing this issue so that it could be improved!
