### ISSUE TITLE
Fulfillment status

### ISSUE THREAD

**Issue by 4026** [MicrosoftDocs/windows-uwp#372]
Is there a reliable way to detect whether a consumable item in the response data has been fulfilled already or not? I see that there's a "fulfillmentData" property in the response data, but it is not currently documented.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3b95f043-9483-170e-3aef-fa675bfc0fb7
* Version Independent ID: 819f2b1e-a55b-7b05-bf54-111eed1a9916
* Content: [Query for products - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/monetize/query-for-products)
* Content Source: [windows-apps-src/monetize/query-for-products.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/monetize/query-for-products.md)
* Service: **unspecified**
* GitHub Login: @mcleanbyron
* Microsoft Alias: **mcleans**

**Comment by mcleanbyron** [comment]
According to the engineering team that owns this service, the fulfillmentData property is never populated (it is present in the response body only for completeness with an internal data contract). To determine whether a consumable product has been fulfilled, specify "All" for validityType in the request and then check for products where status is "Expired". However, if there is a presently active instance of the consumable for the user, you won't see any expired items because the service removes duplicates and favors the active, unfulfilled item. When you use the related [consume](https://docs.microsoft.com/en-us/windows/uwp/monetize/report-consumable-products-as-fulfilled) method to report a consumable as fulfilled, that will set the status of the product to "Expired".
