### ISSUE TITLE
File Explorer add on - Enhancement Idea/Feature Request - Custom Metadata

### ISSUE THREAD

**Issue by 0xNinshu** [MicrosoftDocs/windows-uwp#3722]
Hello,

I think it would be a great addition to this plugin to add the ability to add tags to files or custom columns there are already a ton of columns that don't get used. It would be nice to be able to go into a table edit mode or something similar and change tags for files or other columns.
![image](https://user-images.githubusercontent.com/96320396/158503179-3fb22837-82d4-42d4-a7d2-364b9fcf0b9e.png)
![image](https://user-images.githubusercontent.com/96320396/158503191-3050524f-f070-4903-8758-99665cbad392.png)

I love the work though keep it up!

**Comment by mattwojo** [comment]
Hi @DesuNinshu - Could you provide more context for your issue here? Which docs page / plugin are you referring to?

If this is in relation to the PowerToys utilities, please file your issue/request in the product repo here: https://github.com/microsoft/PowerToys/issues

Closing, but please reopen if this is in relation to the docs and I have that PowerToys context wrong and just let us know a bit more about what this is in relation to. Thanks for filing and glad you're using and enjoying the plugin!
