### ISSUE TITLE
broadFileSystemAccess capability doesn't work

### ISSUE THREAD

**Issue by GrahamAsher** [MicrosoftDocs/windows-uwp#3723]
[Enter feedback here]

I just tried to add file system access using this system:

<?xml version="1.0" encoding="utf-8"?>
<Package
    ...
    xmlns:rescap="http://schemas.microsoft.com/appx/manifest/foundation/windows10/restrictedcapabilities"
    IgnorableNamespaces="... rescap">
...
<Capabilities>
    <rescap:Capability Name="appCaptureSettings"/>
</Capabilities>
</Package>

It doesn't work. I get a wiggly green line under rescap:Capability and a long error message telling me that the child element Capability is not allowed.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9b665f33-4a40-510a-86d3-019ba9c79c44
* Version Independent ID: df96e262-813d-9143-9d91-a29c49a01b4f
* Content: [File access permissions - UWP applications](https://docs.microsoft.com/en-gb/windows/uwp/files/file-access-permissions)
* Content Source: [windows-apps-src/files/file-access-permissions.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/files/file-access-permissions.md)
* Product: **uwp**
* Technology: **data-and-files**
* GitHub Login: @GrantMeStrength
* Microsoft Alias: **jken**

**Comment by alvinashcraft** [comment]
Thanks for submitting this issue. I will look further into it.

Note that it is a warning and not an error. When I perform the steps in the docs, I also see the warning squiggle and in the Error List window under Warnings. I am still able to build and run the application. I am able to use Visual Studio to successfully create an installer to sideload the app with this capability added. Launching the installer lists the restricted capabilities that I added to my package manifest. So, I believe it is working as expected.

It's possible that the documentation needs to be updated to provide a note about this warning message.

**Comment by alvinashcraft** [comment]
Thanks for submitting your feedback and we apologize for the delayed response. I see that there has been no follow since my last comment on this Issue, so I went ahead and created an internal work item to engage with our engineering folks and update the docs with info on the build warning. The timeline for this may vary, so I will go ahead and close this and circle back when the changes are live. 

Though the Issue will be marked as Closed, we will monitor any replies that come afterwards so treat this like an open Issue. Many thanks!
