### ISSUE TITLE
Not all the dependencies are added to the AppxPackage

### ISSUE THREAD

**Issue by harvinders** [MicrosoftDocs/windows-uwp#3744]
[Enter feedback here]

I tried but not all the dependencies are added in the Dependencies folder. Only `Microsoft.WindowsAppRuntime.1.0.msix` was added. Because of this installation fails.

Microsoft.VCLibs.x64.14.00.Desktop.appx, and
Microsoft.VCLibs.x64.14.00.appx

are missing from the package

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 544d5847-b3e1-70d6-14b6-733c5d85d649
* Version Independent ID: 544d5847-b3e1-70d6-14b6-733c5d85d649
* Content: [Set up continuous integration for your WinUI 3 app - Windows apps](https://docs.microsoft.com/en-us/windows/apps/package-and-deploy/ci-for-winui3?pivots=winui3-packaged-csharp)
* Content Source: [hub/apps/package-and-deploy/ci-for-winui3.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/hub/apps/package-and-deploy/ci-for-winui3.md)
* Product: **reunion**
* Technology: **deployment**
* GitHub Login: @stevewhims
* Microsoft Alias: **stwhi**

**Comment by stevewhims** [comment]
Thanks, @harvinders. This sounds like a general problem with using the single packaging project rather than a problem with Continuous Integration setup specifically. It doesn't sound like an issue with the specific documentation in this topic.

For questions (or requests for help) regarding your specific scenario, please use the main [Windows App SDK GitHub Issues](https://github.com/microsoft/WindowsAppSDK/issues), and please submit a more detailed bug report (be detailed with the info you provide). Repro steps, as well as *details* on the expected outcome (for example, "the expected dependencies (X, Y Z) were not present").

Thanks!
-Steve

**Comment by harvinders** [comment]
@stevewhims I think Microsoft should unpublish the docs till the issue is resolved, as the end goal is not going to be achieved by following the guidance. Developers are going to be wasting their time unnecessarily to debug the issue.
