### ISSUE TITLE
Not Helpful

### ISSUE THREAD

**Issue by markolbert** [MicrosoftDocs/windows-uwp#3745]
I was referred to this page when I ran into a problem trying to submit an app to the Windows Store. It provided no useful information on how to resolve an "incomplete" Properties error. In fact, from what I can read there shouldn't be anything wrong with my Properties submission. 

I was expecting some kind of email or forum link where I could raise a question. While I realize the documentation is not meant to be a support community, I urge you to tell the folks over at the Windows Store that, if they want the store to succeed, they need to do a much, much better job at providing avenues for getting help with submissions.

Sorry, not sure why this stuff is showing up in bigger/bolded text. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3354f0d4-e417-7896-6230-a5d7eee0fa97
* Version Independent ID: f544086d-b6f2-7e59-b099-b690eecb91ff
* Content: [App submissions - UWP applications](https://docs.microsoft.com/en-us/windows/uwp/publish/app-submissions)
* Content Source: [windows-apps-src/publish/app-submissions.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/publish/app-submissions.md)
* Product: **uwp**
* Technology: **publish**
* GitHub Login: @hickeys
* Microsoft Alias: **hickeys**

**Comment by Jay-o-Way** [comment]
> not sure why this stuff is showing up in bigger/bolded text

Probably the sentence starting with (one or more) `#`

**Comment by markolbert** [comment]
Seems to be caused by not having a blank line before the next section header

**Comment by GrantMeStrength** [comment]
We are changing the way we track issues filed from our documentation pages: please see this [blog post](https://techcommunity.microsoft.com/t5/microsoft-learn-blog/announcing-a-new-way-to-give-feedback-on-microsoft-learn/ba-p/4027635) for more details. The Microsoft Store documentation has been updated several times since your issue was reported, and there's a good chance your problem has been addressed. Right now, this issue is being closed but if you feel it is still valid and has not been addressed, please re-open it with any more available information. Please note that if you question is more general and not related to documentation, [Microsoft Q&A](https://learn.microsoft.com/en-us/answers/questions/) is a great way to get questions answered.
