### ISSUE TITLE
Is the Pivot deprecated as per the warning on this page, or isn't it?

### ISSUE THREAD

**Issue by AlanPBourke** [MicrosoftDocs/windows-uwp#3749]
Because this Github discussion would seem to indicate that it is now back in WinUI 3.

https://github.com/microsoft/microsoft-ui-xaml/issues/4492

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a3fff26e-5145-7d06-accb-0382cc7e4fb5
* Version Independent ID: 20060cef-8b8f-f407-35d3-3312470423da
* Content: [Pivot - Windows apps](https://docs.microsoft.com/en-ie/windows/apps/design/controls/pivot)
* Content Source: [hub/apps/design/controls/pivot.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/hub/apps/design/controls/pivot.md)
* Product: **reunion**
* Technology: **design**
* GitHub Login: @jwmsft
* Microsoft Alias: **jimwalk**

**Comment by Jay-o-Way** [comment]
Key words are **could** and **might**. It was marked for deprecation in the past, but after protest still included in WinUI3.

**Comment by AlanPBourke** [comment]
It also says 'The [Pivot](https://docs.microsoft.com/en-us/uwp/api/Windows.UI.Xaml.Controls.Pivot) control is no longer recommended' which is not true if it has been reinstated and is a valid option.

**Comment by Jay-o-Way** [comment]
Well, they (MS / developers) **did** want to remove it all together, so one should be aware that this is still a likely option in the future.

**Comment by jwmsft** [comment]
Thanks for asking this question. Pivot is still a supported control. The guidance is being updated to state only that Pivot is not a recommended design pattern for Windows 11.

_The Pivot control is not recommended for [Windows 11 design patterns](../basics/app-silhouette.md). When designing for Windows 11, consider using a [NavigationView](navigationview.md) or [TabView](tab-view.md) control instead of a Pivot control. See the [Use NavigationView instead of Pivot](#use-navigationview-instead-of-pivot) section for an example._

**Comment by Jay-o-Way** [comment]
@jwmsft is that last comment still valid today?
