### ISSUE TITLE
WindowsPhone.ExternalStorageId does not seem to be supported on Windows IoT Core

### ISSUE THREAD

**Issue by JohnDrinkall** [MicrosoftDocs/windows-uwp#378]
Using the above sample, await allProperties.RetrievePropertiesAsync(propertiesToRetrieve); throws System.ArgumentException, The parameter is incorrect.

Documentation for RetrievePropertiesAsync links to https://msdn.microsoft.com/library/e86e5836-522f-4084-8bb3-4c0d4da9cb26, which specifies the acceptable values for a property name. WindowsPhone isn't in there. Has this functionality been deprecated? Or are there other steps in order to get this working on IoT Core?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6736c485-452b-0052-935a-7c88a0c07d9d
* Version Independent ID: 70f62f8d-0afb-37f4-e86e-34be3152d074
* Content: [Access the SD card - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/files/access-the-sd-card)
* Content Source: [windows-apps-src/files/access-the-sd-card.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/files/access-the-sd-card.md)
* Service: **unspecified**
* GitHub Login: @laurenhughes
* Microsoft Alias: **lahugh**

**Comment by knicholasa** [comment]
Thanks for reaching out with your feedback. This looks like a support issue to me, but it would help improve the docs if you come back and let me know what fixed it once you get help. You can find support by consulting our developer support resources. For community assistance with development questions I recommend that you ask on our [forums](https://social.msdn.microsoft.com/Forums/newthread?category=windowsapps&forum=wpdevelop&prof=required) or [StackOverflow](https://stackoverflow.com/questions). Otherwise, please see [the developer support page](https://developer.microsoft.com/windows/support) for your support options. If you get assistance through these other resources and believe that information would help us improve the docs, please come back and let us know.
