### ISSUE TITLE
Bluetooth GATT server restricted service

### ISSUE THREAD

**Issue by phuongtran7** [MicrosoftDocs/windows-uwp#3781]
Hi,

I'm trying to create a simple HID over GATT server with C++/WinRT and it seems that the document on the GATT server is a bit outdated. The `Human Interface Device Service` seems to be no longer restricted. I can create the service with Windows 10 build 19044. Seems to be in line with [#64](https://github.com/MicrosoftDocs/windows-uwp/issues/64) when it's mentioned that restriction on `HID service` would be removed soon.

However, the `Device Information Service` is still under restrictive mode. Is there any plan to unblock the service like the `HID serivce`? I'm trying to write a simple BLE server to emulate a Bluetooth mouse and control other devices, like an iPad. And in order to do that I need to implement at least the `Device Information Service`, `Human Interface Device Service` and `Battery Service`.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d7618e33-68a1-8a4d-0247-e4f3bbb1ebbb
* Version Independent ID: 48c2c28d-9b52-4d83-343f-df35f4219b0d
* Content: [Bluetooth GATT Server - UWP applications](https://docs.microsoft.com/en-us/windows/uwp/devices-sensors/gatt-server)
* Content Source: [windows-apps-src/devices-sensors/gatt-server.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/devices-sensors/gatt-server.md)
* Product: **uwp**
* Technology: **peripherals-sensors-and-power**
* GitHub Login: @Karl-Bridge-Microsoft
* Microsoft Alias: **kbridge**

**Comment by rohitsangwan01** [comment]
Any update on this ?, am also facing same issue, and blocked by `Device Information Service` restriction to create an HID device

**Comment by Karl-Bridge-Microsoft** [comment]
The last info I got from the feature team was:

the HID service for GATT server is confirmed to be unblocked. (Note this applies to GATT server and not GATT client) The Device Information Service (DIS) for GATT server is still blocked and we don’t have any plan to open the Device Information Service to the API as it is entirely reserved by the system.

NOTE: We are changing the way we track issues filed from our documentation pages: please see this [blog post](https://techcommunity.microsoft.com/t5/microsoft-learn-blog/announcing-a-new-way-to-give-feedback-on-microsoft-learn/ba-p/4027635) for more details. Right now, this issue is being closed but if you feel it is still valid and has not been addressed, please re-open it with any more available information. Please note that if your question is more general and not related to documentation, [Microsoft Q&A](https://learn.microsoft.com/en-us/answers/questions/) is a great way to get questions answered.
