### ISSUE TITLE
CSS for "alerts" in docs are incorrect?

### ISSUE THREAD

**Issue by Jay-o-Way** [MicrosoftDocs/windows-uwp#3784]
# This seems to be a `docs.microsoft.com` general thing!

I noticed the following when looking at the documentation:
![icons for Note and Important](https://user-images.githubusercontent.com/65828559/163676127-ae0d4e3a-0752-4ce6-8849-1677b668b795.png)

This is because
![Message CSS](https://user-images.githubusercontent.com/65828559/163676145-2853fbfb-7597-4971-9020-429e2a49811d.png)

On a different page:
![TIP visual + CSS](https://user-images.githubusercontent.com/65828559/163676341-64dfe98f-a9bc-4e4c-baab-67fe640d1b5c.png)
A `TIP` ≠ "succes"

Please check the cause and fix.

**Comment by Jay-o-Way** [comment]
This seems to be a `docs.microsoft.com` general thing.
The strange part is: the banner at the top _does_ seem to be correct?
![image](https://user-images.githubusercontent.com/65828559/163680513-14aeb8fa-e790-4ce2-aa6b-021077cdd516.png)

**Comment by Jay-o-Way** [comment]
Off-topic: where do I find a list of all the possible style of these kind of notes? So far I know of [Important, Note, Tip] and recently saw [Caution, Warning] but would like to see a list.

```
> ![NOTE]
> Message.
```

**Comment by mattwojo** [comment]
Hey @Jay-o-Way - Thanks for filing this. I think the CSS is operating as expected. The "Note" and "Important" blocks just happen to use the same icon, unlike the others - "Tips", "Caution", and "Warning" have their own icons.
You can see the possible note styles here: 
https://docs.microsoft.com/en-us/contribute/markdown-reference#alerts-note-tip-important-caution-warning

In the bottom of every docs page (wayyy down in the footer), there is a link to the "Contribute" docs that outline how to get set up for contributing, including some basic markdown reference, etc. But you can always file an issue like this as well in order to get help from some of the docs folks. :)

I'm going to close this issue as it doesn't seem to require a docs update, but please reopen if I've misunderstood. Thanks for all of the ways you've been contributing!! It is seen and appreciated!! <3

**Comment by Jay-o-Way** [comment]
Hi Matt. If you look close, the Note message has a (!) icon and the Important message has a (i) icon. If you ask me, these are (or should be) swapped.
Also i see a message with `<div>` with class "info", followed by a `<span>` with class "error". Does that sound like they belong together? (Same thing for "primary" + "info")
PTAL

(thanks for the link)

**Comment by Jay-o-Way** [comment]
I do see that the md reference _shows_ the same icons and colors, but it just doesn't feel right to me. Blue is a very neutral color and red and yellow are more typical for danger. I assume that page uses the same kind of source (meaning: something is translating the `![NOTE]` from the source files into formatted HTML/CSS.) as any other page on docs.microsoft.com.

**Comment by mattwojo** [comment]
Oh - you're totally right! I missed that difference between the ! and i.  I can't speak to the design choices on these, but I can say that writers have been told to use these alerts sparingly as some of our user testing has shown that readers tend to just skip over these blocks. 
I'm also partially colorblind, so while I can tell that there are differences, it requires a good amount of focus for me to see them. 
I'm not sure who the designer is currently for the docs platform, but I'll see if I can find out and pass your feedback along. Thanks again!
