### ISSUE TITLE
No reviews and feedback button in Apps & games workspace

### ISSUE THREAD

**Issue by infinitepower18** [MicrosoftDocs/windows-uwp#3798]
The "Access Engage and Attract features in the new Apps and Games workspace" section of [this page](https://docs.microsoft.com/en-us/windows/uwp/publish/partner-center-workspaces#access-engage-and-attract-features-in-the-new-apps-and-games-workspace) has a screenshot which contains Reviews and feedback under the Engage section of the left navigation menu. However I don't see this in my partner portal.

This is what that same screen looks like when logged into my partner portal:

![image](https://user-images.githubusercontent.com/44692189/165643064-457e66ce-79c7-417a-acc3-0cf6606cbe57.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 47213237-5d66-e7ed-c616-0b6023be4c61
* Version Independent ID: 47213237-5d66-e7ed-c616-0b6023be4c61
* Content: [Partner Center workspaces - UWP applications](https://docs.microsoft.com/en-us/windows/uwp/publish/partner-center-workspaces#feedback)
* Content Source: [windows-apps-src/publish/partner-center-workspaces.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/publish/partner-center-workspaces.md)
* Product: **uwp**
* Technology: **publish**
* GitHub Login: @hickeys
* Microsoft Alias: **hickeys**

**Comment by GrantMeStrength** [comment]
Assigning the issue to Shawn.

**Comment by GrantMeStrength** [comment]
We are changing the way we track issues filed from our documentation pages: please see this [blog post](https://techcommunity.microsoft.com/t5/microsoft-learn-blog/announcing-a-new-way-to-give-feedback-on-microsoft-learn/ba-p/4027635) for more details. The Microsoft Store documentation has been updated several times since your issue was reported, and there's a good chance your problem has been addressed. Right now, this issue is being closed but if you feel it is still valid and has not been addressed, please re-open it with any more available information. Please note that if you question is more general and not related to documentation, [Microsoft Q&A](https://learn.microsoft.com/en-us/answers/questions/) is a great way to get questions answered.
