### ISSUE TITLE
Partner Center registration doesn't explain why Company option is not selectable

### ISSUE THREAD

**Issue by Christian-Toney** [MicrosoftDocs/windows-uwp#3802]
When pressing "Learn more", I'd expect to learn more on why the Company option is not selectable.

![image](https://user-images.githubusercontent.com/37517470/166123474-9fa7e01b-8590-4343-bc09-5936cefbd7b3.png)

Unfortunately, the page doesn't explain this at all. It simply gives the fees per country, and shows what the requirements are for both types of accounts.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fc9d4d96-2865-5f2d-8737-66fe44db7cce
* Version Independent ID: 239560a3-7506-bb73-b436-6eec162e5196
* Content: [Account types, locations, and fees - UWP applications](https://docs.microsoft.com/en-us/windows/uwp/publish/account-types-locations-and-fees)
* Content Source: [windows-apps-src/publish/account-types-locations-and-fees.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/publish/account-types-locations-and-fees.md)
* Product: **uwp**
* Technology: **publish**
* GitHub Login: @hickeys
* Microsoft Alias: **hickeys**

**Comment by GrantMeStrength** [comment]
We are changing the way we track issues filed from our documentation pages: please see this [blog post](https://techcommunity.microsoft.com/t5/microsoft-learn-blog/announcing-a-new-way-to-give-feedback-on-microsoft-learn/ba-p/4027635) for more details. The Microsoft Store documentation has been updated several times since your issue was reported, and there's a good chance your problem has been addressed. Right now, this issue is being closed but if you feel it is still valid and has not been addressed, please re-open it with any more available information. Please note that if you question is more general and not related to documentation, [Microsoft Q&A](https://learn.microsoft.com/en-us/answers/questions/) is a great way to get questions answered.
