### ISSUE TITLE
Documentation does not describe how to remove a Known User Group

### ISSUE THREAD

**Issue by roelvandersteen** [MicrosoftDocs/windows-uwp#3843]
The [Create Known User Groups](https://docs.microsoft.com/en-us/windows/uwp/publish/create-known-user-groups) page describes how to create a Known User Group on the Engage tab of the Apps and Games section of the Partner Center.

It also describes how to edit the content of the Known User Group. However, it does not describe how to change the name of an existing group or how to delete it.

Also, "User Groups" in the documentation are called "Customer Groups" in the Partner Center. This is confusing.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 66930160-c19a-885b-29cc-1d2d69c8f0a0
* Version Independent ID: d5494564-da0e-4320-d820-0845dc0b3bc6
* Content: [Create known user groups - UWP applications](https://docs.microsoft.com/en-us/windows/uwp/publish/create-known-user-groups)
* Content Source: [windows-apps-src/publish/create-known-user-groups.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/publish/create-known-user-groups.md)
* Product: **uwp**
* Technology: **publish**
* GitHub Login: @hickeys
* Microsoft Alias: **hickeys**

**Comment by GrantMeStrength** [comment]
We are changing the way we track issues filed from our documentation pages: please see this [blog post](https://techcommunity.microsoft.com/t5/microsoft-learn-blog/announcing-a-new-way-to-give-feedback-on-microsoft-learn/ba-p/4027635) for more details. The Microsoft Store documentation has been updated several times since your issue was reported, and there's a good chance your problem has been addressed. Right now, this issue is being closed but if you feel it is still valid and has not been addressed, please re-open it with any more available information. Please note that if you question is more general and not related to documentation, [Microsoft Q&A](https://learn.microsoft.com/en-us/answers/questions/) is a great way to get questions answered.
