### ISSUE TITLE
WinUI2 UWP Styles - Rendering cutoff on NavigationView drawer button

### ISSUE THREAD

**Issue by Aurumaker72** [MicrosoftDocs/windows-uwp#3844]
# Summary
The `NavigationView`'s drawer button is cut off on the right side at first open of app.

### Photographic Evidence

![grafik](https://user-images.githubusercontent.com/48759429/169086770-f304dc64-559c-4c21-8570-3601dd4e6511.png)
_A: outline cutoff_

![grafik](https://user-images.githubusercontent.com/48759429/169086857-e7f1dc8b-71f9-4988-9996-32060e1c89a1.png)

_B (after expanding and retracting drawer): no cutoff_

# Minimum Repro Steps
```xml
        xmlns:muxc="using:Microsoft.UI.Xaml.Controls"

        <muxc:NavigationView
            x:Name="MainNavigationView"
            IsSettingsVisible="True"
            IsBackButtonVisible="Collapsed"
            IsBackEnabled="False"
            CompactModeThresholdWidth="640"
            ExpandedModeThresholdWidth="1008"
            IsTabStop="False"
            AlwaysShowHeader="True"
            IsPaneToggleButtonVisible="True">
            <muxc:NavigationView.MenuItems>
                <muxc:NavigationViewItem Icon="Home" Content="Home" Tag="HomePage"/>
                <muxc:NavigationViewItem Icon="Shop" Content="Shop" Tag="StorePage"/>
                <muxc:NavigationViewItem Icon="ZeroBars" Content="Statistics" Tag="StatisticsPage"/>
                <muxc:NavigationViewItem Icon="Favorite" Content="Upgrades" Tag="UpgradesPage"/>
            </muxc:NavigationView.MenuItems>

            <Grid>
                ... frame
            </Grid>
        </muxc:NavigationView>
```

**Comment by Karl-Bridge-Microsoft** [comment]
Hi @Aurumaker72  - This feedback is for a product issue, not the documentation. Please click the product feedback link at the bottom of the topic, or contact the following support channel:

- For developer issues, or suspected product bugs, use [Microsoft Support](https://support.microsoft.com/contactus) where a support engineer will look at the repro and see whether the issue is a Microsoft product bug, or something else.

For completeness, here is a list of other developer support resources:

- For community assistance with development questions, there are our [forums](https://social.msdn.microsoft.com/Forums/newthread?category=windowsapps&forum=wpdevelop&prof=required), and [StackOverflow](https://stackoverflow.com/questions).
- The [Windows developer support](https://developer.microsoft.com/windows/support) site explains other support options.
- The [Feedback Hub app](https://support.microsoft.com/help/4021566/windows-10-send-feedback-to-microsoft-with-feedback-hub-app) is the right place to lobby for a change, a feature, or to make a suggestion.

If you receive assistance via any support resource, and you believe that information would help us improve the docs, then please come back and let us know.
