### ISSUE TITLE
Access to MS Store Promotions API & Partner Center Ad Campaigns

### ISSUE THREAD

**Issue by mryderie** [MicrosoftDocs/windows-uwp#3865]
Is the MS Store Promotions API described on this page active and open to new users? - https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/monetize/run-ad-campaigns-using-windows-store-services.md

One of the prerequisites for using the API is to: "create one paid ad campaign using the Ad campaigns page in Partner Center", however, I am unable to find any Ad Campaigns page in Partner Center.

If this API is active, can someone provide a link for the Ad Campaigns page in Partner Center?

**Comment by GrantMeStrength** [comment]
We are changing the way we track issues filed from our documentation pages: please see this [blog post](https://techcommunity.microsoft.com/t5/microsoft-learn-blog/announcing-a-new-way-to-give-feedback-on-microsoft-learn/ba-p/4027635) for more details. The Microsoft Store documentation has been updated several times since your issue was reported, and there's a good chance your problem has been addressed. Right now, this issue is being closed but if you feel it is still valid and has not been addressed, please re-open it with any more available information. Please note that if you question is more general and not related to documentation, [Microsoft Q&A](https://learn.microsoft.com/en-us/answers/questions/) is a great way to get questions answered.
