### ISSUE TITLE
Store badge script 404

### ISSUE THREAD

**Issue by pekatete** [MicrosoftDocs/windows-uwp#3879]
The following script used to load Store badges on sites is now producing 404 errors: https://getbadgecdn.azureedge.net/ms-store-badge.bundled.js
The issue seems to be that the images directory no longer exists on the CDN as the script is still served by the server.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 784ae922-b4ec-4e0e-78a9-d529f9ae8dda
* Version Independent ID: bc000ff6-d301-45c2-3c57-3961612081f4
* Content: [Microsoft Store marketing guidelines for apps - UWP applications](https://docs.microsoft.com/en-gb/windows/uwp/publish/app-marketing-guidelines)
* Content Source: [windows-apps-src/publish/app-marketing-guidelines.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/publish/app-marketing-guidelines.md)
* Product: **uwp**
* Technology: **publish**
* GitHub Login: @hickeys
* Microsoft Alias: **hickeys**

**Comment by GrantMeStrength** [comment]
We are changing the way we track issues filed from our documentation pages: please see this [blog post](https://techcommunity.microsoft.com/t5/microsoft-learn-blog/announcing-a-new-way-to-give-feedback-on-microsoft-learn/ba-p/4027635) for more details. The Microsoft Store documentation has been updated several times since your issue was reported, and there's a good chance your problem has been addressed. Right now, this issue is being closed but if you feel it is still valid and has not been addressed, please re-open it with any more available information. Please note that if you question is more general and not related to documentation, [Microsoft Q&A](https://learn.microsoft.com/en-us/answers/questions/) is a great way to get questions answered.
