### ISSUE TITLE
Bulk Import does not work for Indonesian (ID)

### ISSUE THREAD

**Issue by datvm** [MicrosoftDocs/windows-uwp#3883]
Sorry I know this is issue repo for Docs but I don't know where I can report this bug.

When exporting the CSV, Indonesia column name is `id` and you also have `ID` column for the ID of the field. However when Import back, everything works well except for Indonesia. No info is updated. I guess because it uses the same header name as `ID`. Is there any fix for this? Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 90ed6a49-f6d4-d69c-0b60-9013569b9f7b
* Version Independent ID: dc552a7c-4409-d673-1fc6-939f88e4f833
* Content: [Import and export Store listings - UWP applications](https://docs.microsoft.com/en-us/windows/uwp/publish/import-and-export-store-listings)
* Content Source: [windows-apps-src/publish/import-and-export-store-listings.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/publish/import-and-export-store-listings.md)
* Product: **uwp**
* Technology: **publish**
* GitHub Login: @hickeys
* Microsoft Alias: **hickeys**

**Comment by GrantMeStrength** [comment]
We are changing the way we track issues filed from our documentation pages: please see this [blog post](https://techcommunity.microsoft.com/t5/microsoft-learn-blog/announcing-a-new-way-to-give-feedback-on-microsoft-learn/ba-p/4027635) for more details. The Microsoft Store documentation has been updated several times since your issue was reported, and there's a good chance your problem has been addressed. Right now, this issue is being closed but if you feel it is still valid and has not been addressed, please re-open it with any more available information. Please note that if you question is more general and not related to documentation, [Microsoft Q&A](https://learn.microsoft.com/en-us/answers/questions/) is a great way to get questions answered.
