### ISSUE TITLE
US only.

### ISSUE THREAD

**Issue by MUJaCHe66** [MicrosoftDocs/windows-uwp#3895]
Please make it clear that this only works in the US.
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 31f9a801-c5b5-94e7-41b9-1b2b4a1d27de
* Version Independent ID: 31f9a801-c5b5-94e7-41b9-1b2b4a1d27de
* Content: [Windows Subsystem for Android™️](https://docs.microsoft.com/en-us/windows/android/wsa/?WT.mc_id=dotnet-29192-cxa)
* Content Source: [hub/android/wsa/index.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/hub/android/wsa/index.md)
* Product: **dev-environment**
* Technology: **windows-android**
* GitHub Login: @mattwojo
* Microsoft Alias: **mattwoj**

**Comment by mattwojo** [comment]
@MUJaCHe66 - We do call out in this doc that Windows Subsystem for Android is currently only available in the US. The program is still in "public preview" from what I understand and they are still working out bugs. You can learn a bit more about what they're currently working on in the Windows Insider blogs: https://blogs.windows.com/windows-insider/2022/05/20/update-to-windows-subsystem-for-android-on-windows-11/

I'm closing this issue since we already call out that the program is US-only, but if you have any suggestions on ways you think that we could make this more clear on the page and reduce any confusion, please add a comment/reply. ...and thanks for filing this issue.  

![image](https://user-images.githubusercontent.com/7566797/177624473-29ffcde5-9e37-4236-865a-176b20e1e142.png)
