### ISSUE TITLE
RequestPurchaseAsync infinity loading

### ISSUE THREAD

**Issue by akargapolov** [MicrosoftDocs/windows-uwp#3898]
Hello!
I our UWP in WinUI3 games some users can make purchases, some users can't make purchases.
After execute RequestPurchaseAsync method purchase window opened and show Wait a moment..., then text dissapear and white loading window stays.

**Comment by akargapolov** [comment]
![RequestPurchaseAsync](https://user-images.githubusercontent.com/4668942/174957251-b87fe67f-2596-4f28-b95b-18c418d4ebd5.jpg)

**Comment by GrantMeStrength** [comment]
We are changing the way we track issues filed from our documentation pages: please see this [blog post](https://techcommunity.microsoft.com/t5/microsoft-learn-blog/announcing-a-new-way-to-give-feedback-on-microsoft-learn/ba-p/4027635) for more details. The Microsoft Store documentation has been updated several times since your issue was reported, and there's a good chance your problem has been addressed. Right now, this issue is being closed but if you feel it is still valid and has not been addressed, please re-open it with any more available information. Please note that if you question is more general and not related to documentation, [Microsoft Q&A](https://learn.microsoft.com/en-us/answers/questions/) is a great way to get questions answered.
