### ISSUE TITLE
Found the code

### ISSUE THREAD

**Issue by kcovert** [MicrosoftDocs/windows-uwp#3902]
I found the code, another thing seems incorrect here and that's with deploying the service. The article makes you thing you deploy the service project directedly but it has no deploy option. I again assume it means deploy the containing UWP project which will bring the references service with it?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: edde9dbc-6e04-69cf-206e-123792666abf
* Version Independent ID: 9894e78f-3270-9485-4769-11050669b805
* Content: [Create and consume an app service - UWP applications](https://docs.microsoft.com/en-us/windows/uwp/launch-resume/how-to-create-and-consume-an-app-service)
* Content Source: [windows-apps-src/launch-resume/how-to-create-and-consume-an-app-service.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/launch-resume/how-to-create-and-consume-an-app-service.md)
* Product: **uwp**
* Technology: **processes-and-threading**
* GitHub Login: @alvinashcraft
* Microsoft Alias: **aashcraft**

**Comment by alvinashcraft** [comment]
Hello. I'm going to close your original [issue](https://github.com/MicrosoftDocs/windows-dev-docs/issues/3901) asking if there's a code sample for the content on this page. I'm adding the question here for reference:

> Things on this page get confusing mostly with the names of each product. I'm not sure what this article seems to consider the service project to be. It is contained in an app to run in proc but I think the containing app is referred to as the service which it's not. Making it worse the article describes getting the package family name from the package manifest fie in the service project but the project type this article calls to create for the service doesn't have a manifest file. So I'm assuming the package family name you need is of the containing UWP project through which you'll make the call?

**Comment by alvinashcraft** [comment]
Hi @kcovert. I followed the steps of this article today, and it worked as expected. The deployment step says to select Build-->Deploy Solution. This will deploy the AppServiceProvider project and its reference to the MyAppService project if you created the projects in the order given. Because AppServiceProvider was created first, it is the start-up project and the project that gets deployed.

I am going to go ahead and close this issue, but if you have any specific suggestions for improving the wording somewhere, you can submit a PR with your suggestions. Thanks for your feedback!

**Comment by kcovert** [comment]
Yes close it Alvin, the service is included in the app, working great,
Kirk

Sent from my Verizon, Samsung Galaxy smartphone
Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
