### ISSUE TITLE
Helpful extensions -node.js extension pack

### ISSUE THREAD

**Issue by MenasheKoren** [MicrosoftDocs/windows-uwp#3914]
The Node.js extension pack is recommended [here](https://docs.microsoft.com/en-us/windows/dev-environment/javascript/nodejs-on-wsl#helpful-vs-code-extensions). However, that extension runs off of the [Node npm extension](https://marketplace.visualstudio.com/items?itemName=eg2.vscode-npm-script), which has been depreciated.

How are we supposed to proceed, bearing this in mind? 

Please update the page accordingly.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 39f94295-ca73-b090-6347-21e123925177
* Version Independent ID: 504dcc6c-fc86-bd6a-8944-2c0f2280dda7
* Content: [Set up Node.js on WSL 2](https://docs.microsoft.com/en-us/windows/dev-environment/javascript/nodejs-on-wsl)
* Content Source: [hub/dev-environment/javascript/nodejs-on-wsl.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/hub/dev-environment/javascript/nodejs-on-wsl.md)
* Product: **dev-environment**
* Technology: **windows-javascript**
* GitHub Login: @mattwojo
* Microsoft Alias: **mattwoj**

**Comment by mattwojo** [comment]
Hmm... that's a good question @MenasheKoren. I see that it was deprecated because there is already an npm extension built-into VS Code. It also looks like the Node.js extension pack hasn't really been updated since 2017.  
Maybe it's time to remove the Node.js extension pack as a helpful one to consider from this 'Get started' doc.... have you found the extension helpful at all? Any opinion on removing it as a suggestion?

**Comment by mattwojo** [comment]
Closing - If you have an opinion on what extensions would be most helpful to share here, please feel welcome to reopen! In the meantime, I have a list of updates to the JS get started docs in my backlog and have included this. Thanks for contributing the issue.
