### ISSUE TITLE
Explain Usage of ContainerContentChangingEventArgs

### ISSUE THREAD

**Issue by mastry** [MicrosoftDocs/windows-uwp#3916]
It's not clear how `ImageGridView_ContainerContentChanging` and `ShowImage` work. There's a useful technique here for loading item data asynchronously, but it's not explained in the article. The documentation for `InRecycleQueue` and `Phase` don't help either. 

I would like to see a paragraph or two added that explain what is happening here and why. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 51e8cf41-f09a-864d-26de-66d17727ebfc
* Version Independent ID: 51e8cf41-f09a-864d-26de-66d17727ebfc
* Content: [Tutorial--Create a simple photo viewer with WinUI 3 (C#) - Windows apps](https://docs.microsoft.com/en-us/windows/apps/get-started/simple-photo-viewer-winui3)
* Content Source: [hub/apps/get-started/simple-photo-viewer-winui3.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/hub/apps/get-started/simple-photo-viewer-winui3.md)
* Product: **reunion**
* Technology: **get-started**
* GitHub Login: @stevewhims
* Microsoft Alias: **stwhi**

**Comment by stevewhims** [comment]
Hi, @mastry, and thanks for filing this issue.

There was a link to [ListView and GridView UI optimization](https://docs.microsoft.com/windows/uwp/debug-test-perf/optimize-gridview-and-listview) right above the code example. But I've made it more prominent. And before the link I've mentioned the methods and properties that you mention. So if anyone searches for those names in the topic, then they'll find the link. But I think the link stands out better now in any case.

I like the idea of linking to pre-existing info about updating items progressively, rather than copying (duplicating) any info.

Thanks again!
-Steve
