### ISSUE TITLE
Incorrect documentation for recurrences/{recurrenceId}/change

### ISSUE THREAD

**Issue by pnico** [MicrosoftDocs/windows-uwp#3919]
From the documentation:

Response
This method returns a JSON response body that contains information about the subscription add-on that was modified, including any fields that were modified. The following example demonstrates a response body for this method.

```
{
  "items": [
    {
      "autoRenew":true,
      "beneficiary":"pub:gFVuEBiZHPXonkYvtdOi+tLE2h4g2Ss0ZId0RQOwzDg=",
      "expirationTime":"2017-06-16T03:07:49.2552941+00:00",
      "id":"mdr:0:bc0cb6960acd4515a0e1d638192d77b7:77d5ebee-0310-4d23-b204-83e8613baaac",
      "lastModified":"2017-01-10T21:08:13.1459644+00:00",
      "market":"US",
      "productId":"9NBLGGH52Q8X",
      "skuId":"0024",
      "startTime":"2017-01-10T21:07:49.2552941+00:00",
      "recurrenceState":"Active"
    }
  ]
}
```

In fact, the response looks like this:
```
{
  "autoRenew":true,
  "beneficiary":"pub:gFVuEBiZHPXonkYvtdOi+tLE2h4g2Ss0ZId0RQOwzDg=",
  "expirationTime":"2017-06-16T03:07:49.2552941+00:00",
  "id":"mdr:0:bc0cb6960acd4515a0e1d638192d77b7:77d5ebee-0310-4d23-b204-83e8613baaac",
  "lastModified":"2017-01-10T21:08:13.1459644+00:00",
  "market":"US",
  "productId":"9NBLGGH52Q8X",
  "skuId":"0024",
  "startTime":"2017-01-10T21:07:49.2552941+00:00",
  "recurrenceState":"Active"
}
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1eed782e-83e0-a192-bdff-96c7925abeed
* Version Independent ID: 34d08784-1452-f981-f3db-99b3ee463ece
* Content: [Change the billing state of a subscription for a user - UWP applications](https://docs.microsoft.com/en-us/windows/uwp/monetize/change-the-billing-state-of-a-subscription-for-a-user)
* Content Source: [windows-apps-src/monetize/change-the-billing-state-of-a-subscription-for-a-user.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/monetize/change-the-billing-state-of-a-subscription-for-a-user.md)
* Product: **uwp**
* Technology: **publish**
* GitHub Login: @hickeys
* Microsoft Alias: **hickeys**

**Comment by GrantMeStrength** [comment]
We are changing the way we track issues filed from our documentation pages: please see this [blog post](https://techcommunity.microsoft.com/t5/microsoft-learn-blog/announcing-a-new-way-to-give-feedback-on-microsoft-learn/ba-p/4027635) for more details. The Microsoft Store documentation has been updated several times since your issue was reported, and there's a good chance your problem has been addressed. Right now, this issue is being closed but if you feel it is still valid and has not been addressed, please re-open it with any more available information. Please note that if you question is more general and not related to documentation, [Microsoft Q&A](https://learn.microsoft.com/en-us/answers/questions/) is a great way to get questions answered.
