### ISSUE TITLE
Missing documentation about how subscription refunds work

### ISSUE THREAD

**Issue by pnico** [MicrosoftDocs/windows-uwp#3925]
One of the possible actions that `recurrences/{recurrenceId}/change` can perform is `Refund`. But there is no information about what this specifically does, or when it can or cannot be done. It does seem to do the same as 'Cancel' as far as ending the subscription entitlement immediately, although this also isn't made clear in the documentation. Sometimes we see this error response: `'The timeframe over which full refunds are allowed for this purchase is past.'` But there is no information provided about what determines this timeframe. Note: This issue specifically refers to Refund, but the same questions could be asked about the other possible values of the `changeType` parameter, because the explanations of the others are similarly incomplete.

- Does it refund the last payment, or all the payments that have been made so far on this subscription?
- Does it issue a full refund for the (month) renewal period, or some part based on how much of the current period has been used?
- When can a Refund be issued? When can it not (or no longer) be issued?
- What are the possible errors that can be returned from this API, and what are the conditions that cause them?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1eed782e-83e0-a192-bdff-96c7925abeed
* Version Independent ID: 34d08784-1452-f981-f3db-99b3ee463ece
* Content: [Change the billing state of a subscription for a user - UWP applications](https://docs.microsoft.com/en-us/windows/uwp/monetize/change-the-billing-state-of-a-subscription-for-a-user)
* Content Source: [windows-apps-src/monetize/change-the-billing-state-of-a-subscription-for-a-user.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/monetize/change-the-billing-state-of-a-subscription-for-a-user.md)
* Product: **uwp**
* Technology: **publish**
* GitHub Login: @hickeys
* Microsoft Alias: **hickeys**

**Comment by GrantMeStrength** [comment]
We are changing the way we track issues filed from our documentation pages: please see this [blog post](https://techcommunity.microsoft.com/t5/microsoft-learn-blog/announcing-a-new-way-to-give-feedback-on-microsoft-learn/ba-p/4027635) for more details. The Microsoft Store documentation has been updated several times since your issue was reported, and there's a good chance your problem has been addressed. Right now, this issue is being closed but if you feel it is still valid and has not been addressed, please re-open it with any more available information. Please note that if you question is more general and not related to documentation, [Microsoft Q&A](https://learn.microsoft.com/en-us/answers/questions/) is a great way to get questions answered.
