### ISSUE TITLE
Incomplete code examples

### ISSUE THREAD

**Issue by mariongothier** [MicrosoftDocs/windows-uwp#3933]
Hi, it would be really helpful to provide the full code for each document after each step in the tutorial, rather than the abbreviated versions with just the changes. Or provide the actual Photo Viewer code on github. 

With only the abbreviated versions available in the tutorial, if you make a mistake somewhere it's pretty much impossible to recover, and since the project in the tutorial (the Photo Viewer) isn't the same as the Photo Editor, looking at the code for the Photo Editor doesn't help.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 51e8cf41-f09a-864d-26de-66d17727ebfc
* Version Independent ID: 51e8cf41-f09a-864d-26de-66d17727ebfc
* Content: [Tutorial--Create a simple photo viewer with WinUI 3 (C#) - Windows apps](https://docs.microsoft.com/en-us/windows/apps/get-started/simple-photo-viewer-winui3)
* Content Source: [hub/apps/get-started/simple-photo-viewer-winui3.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/hub/apps/get-started/simple-photo-viewer-winui3.md)
* Product: **reunion**
* Technology: **get-started**
* GitHub Login: @stevewhims
* Microsoft Alias: **stwhi**

**Comment by stevewhims** [comment]
Hi, @mariongothier, and thanks for filing this issue! Yes, it would be easier if we provided the full code (a copy of the project) for each stage of the tutorial. Here are some thoughts that make me inclined to add that to my backlog, rather than prioritize working on it right now:

It'd be relatively expensive to build out the various stages of the project, find somewhere to host them, and keep all the projects up to date (over time), keep them compiling, and targeting the latest versions of the Windows App SDK, the Windows SDK, Visual Studio, etc.

The project that you build in this topic is a much simplified version of the [Photo Editor sample application](https://github.com/microsoft/WindowsAppSDK-Samples/tree/main/Samples/PhotoEditor). As you say, not the same. But perhaps sufficient for cloning and looking in for the particular pieces that you want to see in a functioning state (should following the tutorial not yield that functioning state).

There's value in the topic even if the reader doesn't follow along with the steps. Many aspects of the XAML framework, development, patterns, tooling, etc., are described there.

If, in following along with the steps, the reader makes a mistake, there's great value in tracking down where the mistake was made. In that way, the mistake might be a happy accident if it helps the reader really focus on, and understand, what the code is doing, to the degree that they can see where the mistake was made.

Just some thoughts.

Thanks!
-Steve
