### ISSUE TITLE
Page needs update

### ISSUE THREAD

**Issue by newscientist101** [MicrosoftDocs/windows-uwp#3937]
This page seems out-of-date. The features command appears to only work with pre-release builds. Otherwise it only outputs: `This is a stable release of the Windows Package Manager. If you would like to try experimental features, please install a pre-release build. Instructions are available on GitHub at https://github.com/microsoft/winget-cli.`
Also, https://aka.ms/winget-experimentalfeatures has an out-of-date id in the link. It should be `https://github.com/microsoft/winget-cli/blob/master/doc/Settings.md#experimental-features` instead of `https://github.com/microsoft/winget-cli/blob/master/doc/Settings.md#experimentalfeatures`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 900d187f-94af-3b5f-a8e0-a0546a789334
* Version Independent ID: b1b424c6-3a30-9890-d71a-23bf8a02c964
* Content: [features Command](https://docs.microsoft.com/en-us/windows/package-manager/winget/features)
* Content Source: [hub/package-manager/winget/features.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/hub/package-manager/winget/features.md)
* Product: **dev-environment**
* Technology: **package-manager**
* GitHub Login: @KevinLaMS
* Microsoft Alias: **kevinla**

**Comment by mattwojo** [comment]
Thanks @newscientist101! Working with the Package Manager team to get that aka link anchor fixed and see about adding a preview tag and link. Will update once these are complete.

**Comment by mattwojo** [comment]
This has been updated. Thanks for bringing the issue to our attention @newscientist101!

Sounds like there was a change to disable "experimental features" in stable releases so that now experimental features are only available in preview builds in order to avoid risk for enterprise company use-cases so that they can set a policy to prevent using experimental features.

The aka forwarding link was fixed as well.
Closing as resolved. :)
