### ISSUE TITLE
Why does WebMatrix appear on this page if it has been discontinued?

### ISSUE THREAD

**Issue by avinatbezeq** [MicrosoftDocs/windows-uwp#3943]
[Enter feedback here]
Why does WebMatrix appear on this page if it has been discontinued?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 36e9a6a5-7a1d-f87a-68ba-e68c0787595d
* Version Independent ID: 6b4a59fa-44f2-525f-11ab-8b336f6ffcd1
* Content: [Web development on Windows](https://docs.microsoft.com/en-us/windows/web/)
* Content Source: [hub/web/index.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/hub/web/index.md)
* Product: **windows**
* Technology: **web**
* GitHub Login: @mattwojo
* Microsoft Alias: **mattwoj**

**Comment by mattwojo** [comment]
Took me a minute to figure out what you're talking about... finally went to the live site instead of the source file and see what you mean... WebMatrix is listed in the bottom "Recommended content" section... which is autogenerated. :( 
I don't have any control over these recommendations as a writer. It's a somewhat new "feature" of the platform. I'll look into how to improve this. Thanks for bringing to my attention.
