### ISSUE TITLE
XboxLiveUser.User.Privilege in Unity editor

### ISSUE THREAD

**Issue by GregLukosek** [MicrosoftDocs/windows-uwp#395]
XboxLiveUser.User.Privilege will return null when tested in Unity Editor. It's worth mentioning that in the documentation, or amending Unity Xbox Live plugin.
Overall instructions how to test privileges would be very useful here.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4b31d99e-6d2d-2920-46f4-70113c928e04
* Version Independent ID: dab334e9-d385-1946-ed23-5fb94acca7b7
* Content: [Check user privilege settings in Unity - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/xbox-live/get-started-with-creators/check-user-privileges-in-unity#feedback)
* Content Source: [windows-apps-src/xbox-live/get-started-with-creators/check-user-privileges-in-unity.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/xbox-live/get-started-with-creators/check-user-privileges-in-unity.md)
* Service: **unspecified**
* GitHub Login: @staceyhaffner
* Microsoft Alias: **sthaff**

**Comment by KevinAsgari** [comment]
You are correct.  The Unity editor does not actually connect to the Xbox Live service and uses fake data to simulate a connection, thus you will currently get a null response. In order to test with real data, you will need to export your game to Visual Studio and test as described in https://docs.microsoft.com/en-us/windows/uwp/xbox-live/get-started-with-creators/test-visual-studio-build.

I will update the topic to reflect this.
