### ISSUE TITLE
Facebook Login

### ISSUE THREAD

**Issue by Lupin1st** [MicrosoftDocs/windows-uwp#396]
Could you please add a sample for using WebAuthenticationCoreManager to login with Facebook.
I have tried this using the following code with the account provider "https://www.facebook.com":
private async void GetFacebookTokenAsync(WebAccountProviderCommand command)
        {
            var applicationSid = WebAuthenticationBroker.GetCurrentApplicationCallbackUri().ToString();
            var request = new WebTokenRequest(command.WebAccountProvider, "public_profile", "");
            request.Properties.Add("redirect_uri", applicationSid);
            var result = await WebAuthenticationCoreManager.RequestTokenAsync(request);
I can see the Facebook Login Window for a short time and then get a UserCancel as ResponseStatus.
Also a list of providers that currently support the WebAuthenticationCoreManager would be great.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2c167684-f810-f987-5383-30fd7856a0c6
* Version Independent ID: d482e60b-b261-0db4-1c51-17db205a67d2
* Content: [Web Account Manager - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/security/web-account-manager)
* Content Source: [windows-apps-src/security/web-account-manager.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/security/web-account-manager.md)
* Service: **unspecified**
* GitHub Login: @PatrickFarley
* Microsoft Alias: **pafarley**

**Comment by viswanathr88** [comment]
When I try to use currently logged in MSA user in Windows 10 to authenticate against the Graph API, i'm getting a ProviderError when requesting for a token:
Authentication target is invalid.

Anyone knows how to solve this?

**Comment by ghost** [comment]
Hi. Is there any result or update?
@PatrickFarley ^

**Comment by hickeys** [comment]
Thanks for reaching out with your feedback. GitHub issues in this repo are for documentation bugs only, and unfortunately this seems more like a support request than a documentation bug. 

The best way to get support is by asking the community on [Microsoft Q&A](https://docs.microsoft.com/answers/topics/uwp.html?sort=active&filter=all) or [StackOverflow](https://stackoverflow.com/questions) 

For completeness' sake, here is a list of developer resources:

- [Microsoft Q&A](https://docs.microsoft.com/answers/topics/uwp.html?sort=active&filter=all) offers relevant and timely answers to your technical problems from a community of experts and Microsoft engineers.
- For community assistance with development questions, there are our [forums](https://social.msdn.microsoft.com/Forums/newthread?category=windowsapps&forum=wpdevelop&prof=required), and [StackOverflow](https://stackoverflow.com/questions).
- The [Windows developer support](https://developer.microsoft.com/windows/support) site explains other support options.
- The [Visual Studio developer community](https://developercommunity.visualstudio.com) is available, and responsive. The former User Voice feature is now there on the **Suggest a feature** tab, if you want to lobby for a change, a feature, or to make a suggestion.
- For developer issues, or suspected product bugs, there's [Microsoft Support](https://support.microsoft.com/contactus); a support engineer will look at the repro and see whether the issue is a Microsoft product bug, or something else. If it's a bug with a Microsoft product then the ticket will be free of charge.

If you receive assistance via any support resource and you believe that information would help us improve the docs, then please let us know or consider submitting a pull request.

Thanks,
Shawn
