### ISSUE TITLE
"Engage" in left nav menu no longer visible, now in Apps and games | Overview page

### ISSUE THREAD

**Issue by DaveVoyles** [MicrosoftDocs/windows-uwp#3960]
Step 1 in section **To create a known user group** reads:
"1. In [Partner Center](https://partner.microsoft.com/dashboard), expand **Engage** in the left navigation menu and then select **Customer groups**."

However, I could not find **engage** until I navigated to the **Apps and Games | Overview page.**

Could I recommend adding a line of text to this document to illustrate that **Engage** is now found on that page since Partner Center migrated to Workspaces?

![engage](https://user-images.githubusercontent.com/1786053/181035189-a56a0783-0dff-4fb7-bdb2-728e159e6474.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 66930160-c19a-885b-29cc-1d2d69c8f0a0
* Version Independent ID: d5494564-da0e-4320-d820-0845dc0b3bc6
* Content: [Create known user groups - UWP applications](https://docs.microsoft.com/en-us/windows/uwp/publish/create-known-user-groups?source=docs)
* Content Source: [windows-apps-src/publish/create-known-user-groups.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/publish/create-known-user-groups.md)
* Product: **uwp**
* Technology: **publish**
* GitHub Login: @hickeys
* Microsoft Alias: **hickeys**

**Comment by GrantMeStrength** [comment]
We are changing the way we track issues filed from our documentation pages: please see this [blog post](https://techcommunity.microsoft.com/t5/microsoft-learn-blog/announcing-a-new-way-to-give-feedback-on-microsoft-learn/ba-p/4027635) for more details. The Microsoft Store documentation has been updated several times since your issue was reported, and there's a good chance your problem has been addressed. Right now, this issue is being closed but if you feel it is still valid and has not been addressed, please re-open it with any more available information. Please note that if you question is more general and not related to documentation, [Microsoft Q&A](https://learn.microsoft.com/en-us/answers/questions/) is a great way to get questions answered.
