### ISSUE TITLE
[Windows 11] `ms-settings:privacy-backgroundapps` do nothing and users need to edit manually the registry in some cases

### ISSUE THREAD

**Issue by ChristopheLav** [MicrosoftDocs/windows-uwp#3996]
Hello,

Since Windows 11, this URI does nothing: `ms-settings:privacy-backgroundapps`. Is it expected ? If yes, the documentation page does not indicate the depreciation.

No matter the answer, this is an issue for Windows 11 users because the global Background Apps setting page is no more available on Windows 11 and the Advanced Settings of each application don't always include the Background Apps/tasks options. In Windows 10, the users can disable globally the Background Apps and when the migration to Windows 11 occurs - the global settings page is gone so there is no more possibility to reactivate the Background Apps. When the option is globally disabled, the advanced settings page of each application don't display the Backgroud Tasks settings...

I can understand the deprecation of the global page and associated option, but the Windows 11 setup/migration should reactivate the thing automatically to prevent user confusion. Today, I need to indicates to my users to open the registry and remove the key `GlobalUserDisabled` under `HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\BackgroundAccessApplications` *and* to restart.

This is may good for advanced users but not for all. And this is not a good user experience at all :-)

According to received feedbacks from my users, this mainly occurs when users migrate to Windows 11 from Windows 10 but maybe a clean installation has this issue as well in some cases.

I create this issue here because the documentation is not up-to-date but maybe the Windows Team is also required to fix all aspect of this issue in Windows itself. I created this Feedback Hub issue too: https://aka.ms/AAhozet

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 987ec16c-9456-93a4-177a-dbd563be7eb7
* Version Independent ID: f41f0344-f7f6-f092-a6bf-fc4184a9b460
* Content: [Launch the Windows Settings app - UWP applications](https://docs.microsoft.com/en-us/windows/uwp/launch-resume/launch-settings-app#privacy)
* Content Source: [windows-apps-src/launch-resume/launch-settings-app.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/launch-resume/launch-settings-app.md)
* Product: **uwp**
* Technology: **processes-and-threading**
* GitHub Login: @alvinashcraft
* Microsoft Alias: **aashcraft**

**Comment by alvinashcraft** [comment]
Thanks for submitting your feedback and we apologize for the delayed response. I see that updates have not been made since the creation of this Issue, so I went ahead and created an internal work item to engage with our engineering folks and resolve this doc bug. I am seeing the same behavior you describe in Windows 11. It appears that the Background apps settings page is gone. The timeline for this may vary, so I will go ahead and close this and circle back when the changes are live. 

Though the Issue will be marked as Closed, we will monitor any replies that come afterwards so treat this like an open Issue. Many thanks!

**Comment by alvinashcraft** [comment]
Hi. I'm circling back to let you know that the Background apps settings docs have been updated to indicate where to find the individual app settings in Windows 11. Once the product team decides what to do about the scenario where the settings have been hidden because you disabled it before upgrading to Windows 11, I'll circle back again.

**Comment by ChristopheLav** [comment]
Thank you @alvinashcraft for your help!
