### ISSUE TITLE
App Management changes in Partner Center settings

### ISSUE THREAD

**Issue by Simon-Syd** [MicrosoftDocs/windows-uwp#4008]
hello,

you documentation is out of date, because it does not reflect the actual menu in the "home > account settings"
I'm kind of lost reading the documentation !

Simon

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 59b3ff12-c450-4912-9509-e83831d452a1
* Version Independent ID: 6563901d-adc1-4cdb-144b-94306d082e46
* Content: [Add users, groups, and Azure AD applications to your Partner Center account - Microsoft Store](https://docs.microsoft.com/en-us/windows/uwp/publish/add-users-groups-and-azure-ad-applications#create-a-new-azure-ad-application-account-in-your-organizations-directory-and-add-it-to-your-partner-center-account)
* Content Source: [windows-apps-src/publish/add-users-groups-and-azure-ad-applications.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/publish/add-users-groups-and-azure-ad-applications.md)
* Product: **uwp**
* Technology: **publish**
* GitHub Login: @hickeys
* Microsoft Alias: **hickeys**

**Comment by GrantMeStrength** [comment]
We are changing the way we track issues filed from our documentation pages: please see this [blog post](https://techcommunity.microsoft.com/t5/microsoft-learn-blog/announcing-a-new-way-to-give-feedback-on-microsoft-learn/ba-p/4027635) for more details. The Microsoft Store documentation has been updated several times since your issue was reported, and there's a good chance your problem has been addressed. Right now, this issue is being closed but if you feel it is still valid and has not been addressed, please re-open it with any more available information. Please note that if you question is more general and not related to documentation, [Microsoft Q&A](https://learn.microsoft.com/en-us/answers/questions/) is a great way to get questions answered.
