### ISSUE TITLE
Clipboard App sample instructions do not reflect new generated "Blank App" C++/WinRT templates.

### ISSUE THREAD

**Issue by PaulaScholz** [MicrosoftDocs/windows-uwp#4032]
[Enter feedback here]
This page and its instructions need to be updated to encompass the new source files generated by the "Blank App" template for C++/WinRT.

The App constructor created by VS2002 17.3.3 with UWP C++ Workloads creates:

App::App()
{
    Suspending({ this, &App::OnSuspending });

#if defined _DEBUG && !defined DISABLE_XAML_GENERATED_BREAK_ON_UNHANDLED_EXCEPTION
    UnhandledException([this](IInspectable const&, UnhandledExceptionEventArgs const& e)
    {
        if (IsDebuggerPresent())
        {
            auto errorMessage = e.Message();
            __debugbreak();
        }
    });
#endif
}

The Suspending call is undefined, Unhandled Exception is undefined, and when compared to the C++/WinRT solution provided with the Clipboard sample, these don't even exist there.

At the end of this step: https://docs.microsoft.com/en-us/windows/uwp/cpp-and-winrt-apis/clipboard-to-winrt-from-csharp#update-all-remaining-namespace-declarationsreferences-and-build

I am instructed to save and build, but when I do so I receive the following errors because the "Blank App" template has completely changed, and the sample instructions do not reflect this.

1>XamlTypeInfo.Impl.g.cpp
1>D:\scratchPrograms\Clipboard\Clipboard\Generated Files\App.xaml.g.h(43,24): error C2065: 'XamlMetaDataProvider': undeclared identifier (compiling source file App.cpp)
1>D:\scratchPrograms\Clipboard\Clipboard\Generated Files\App.xaml.g.h(52): message : see reference to class template instantiation 'winrt::Clipboard::implementation::AppT<D,Interfaces...>' being compiled (compiling source file App.cpp)
1>D:\scratchPrograms\Clipboard\Clipboard\Generated Files\App.xaml.g.h(43,16): error C2923: 'winrt::com_ptr': 'XamlMetaDataProvider' is not a valid template type argument for parameter 'T' (compiling source file App.cpp)
1>D:\scratchPrograms\Clipboard\Clipboard\Generated Files\App.xaml.g.h(43): message : see declaration of 'XamlMetaDataProvider' (compiling source file App.cpp)
1>D:\scratchPrograms\Clipboard\Clipboard\Generated Files\App.xaml.g.h(43,46): error C2955: 'winrt::com_ptr': use of class template requires template argument list (compiling source file App.cpp)
1>D:\scratchPrograms\Clipboard\Clipboard\Generated Files\winrt\base.h(2347): message : see declaration of 'winrt::com_ptr' (compiling source file App.cpp)
1>D:\scratchPrograms\Clipboard\Clipboard\Generated Files\App.xaml.g.h(44,24): error C2065: 'XamlMetaDataProvider': undeclared identifier (compiling source file App.cpp)
1>D:\scratchPrograms\Clipboard\Clipboard\Generated Files\App.xaml.g.h(44,16): error C2923: 'winrt::com_ptr': 'XamlMetaDataProvider' is not a valid template type argument for parameter 'T' (compiling source file App.cpp)
1>D:\scratchPrograms\Clipboard\Clipboard\Generated Files\App.xaml.g.h(44): message : see declaration of 'XamlMetaDataProvider' (compiling source file App.cpp)
1>D:\scratchPrograms\Clipboard\Clipboard\Generated Files\App.xaml.g.h(45,1): error C2955: 'winrt::com_ptr': use of class template requires template argument list (compiling source file App.cpp)
1>D:\scratchPrograms\Clipboard\Clipboard\Generated Files\winrt\base.h(2347): message : see declaration of 'winrt::com_ptr' (compiling source file App.cpp)
1>D:\scratchPrograms\Clipboard\Clipboard\App.h(6,22): error C2504: 'AppT': base class undefined (compiling source file App.cpp)
1>D:\scratchPrograms\Clipboard\Clipboard\App.h(6,22): error C2143: syntax error: missing ',' before '<' (compiling source file App.cpp)
1>D:\scratchPrograms\Clipboard\Clipboard\MainPage.cpp(22,96): warning C4100: 'type': unreferenced formal parameter
1>D:\scratchPrograms\Clipboard\Clipboard\MainPage.cpp(22,46): warning C4100: 'strMessage': unreferenced formal parameter
1>Done building project "Clipboard.vcxproj" -- FAILED.

The sample needs to be updated to reflect the new "Blank App" code generated by the new project templates.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 635488bb-48b9-ec76-7a09-c545b0d2b317
* Version Independent ID: ea91feb7-3995-32fb-bc6e-99a23741e9a8
* Content: [Porting the Clipboard sample to C++/WinRT from C# (a case study) - UWP applications](https://docs.microsoft.com/en-us/windows/uwp/cpp-and-winrt-apis/clipboard-to-winrt-from-csharp)
* Content Source: [windows-apps-src/cpp-and-winrt-apis/clipboard-to-winrt-from-csharp.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/cpp-and-winrt-apis/clipboard-to-winrt-from-csharp.md)
* Product: **uwp**
* Technology: **platform**
* GitHub Login: @stevewhims
* Microsoft Alias: **stwhi**

**Comment by stevewhims** [comment]
Thanks for filing this issue, @PaulaScholz!

That **Suspending** syntax is registering an event-handling delegate to handle the **Application::Suspending** event. See [Handle events by using delegates in C++/WinRT](https://docs.microsoft.com/windows/uwp/cpp-and-winrt-apis/handle-events). The handler is **App::OnSuspending**. I believe something similar is going on with the **Application.UnhandledException** event. In that case, though, the delegate is a lambda function rather than a member of App. So that code is all correct.

Yes, it looks like the **Blank App** project template has changed since this sample was ported to C++. It was ported in May 2020. However, that change doesn't seem to affect the tutorial. I followed the entire tutorial yesterday and today, and everything worked as expected. I was able to build the project at every stage, and at the end. As I was following the tutorial, I did make a lot of small tweaks and improvements as I went (where things weren't as clear as they could be). So I've now published those changes now.

Let's close this issue (since the tutorial looks correct), and continue talking on Teams to see if we can resolve the build errors that you mention.

Thanks!
-Steve
