### ISSUE TITLE
AdaptiveMediaSource.CreateFromUriAsync doesn't support ms-appx/resource in unpackaged apps

### ISSUE THREAD

**Issue by MikeHillberg** [MicrosoftDocs/windows-uwp#4047]
I'm not sure how to present it on this page, but the
[AdaptiveMediaSource.CreateFromUriAsync](https://docs.microsoft.com/uwp/api/Windows.Media.Streaming.Adaptive.AdaptiveMediaSource.CreateFromUriAsync)
(overloaded) API doesn't support the ms-appx or ms-resource URI format in an unpackaged Desktop app.

Or maybe this should be on that API page and doesn't belong here at all?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 909f1773-1e55-eb5a-206f-b32ce6f9dd9d
* Version Independent ID: 24ea5c87-1c21-884d-f05f-833bbd894ba9
* Content: [Windows Runtime APIs not supported in desktop apps - Windows apps](https://docs.microsoft.com/en-us/windows/apps/desktop/modernize/desktop-to-uwp-supported-api)
* Content Source: [hub/apps/desktop/modernize/desktop-to-uwp-supported-api.md](https://github.com/MicrosoftDocs/windows-dev-docs/blob/docs/hub/apps/desktop/modernize/desktop-to-uwp-supported-api.md)
* Product: **reunion**
* Technology: **apps**
* GitHub Login: @stevewhims
* Microsoft Alias: **stwhi**

**Comment by stevewhims** [comment]
Thanks, Mike. I've added this info to both topics. I'm working on the belief that "unpackaged" in this case means "doesn't have package identity". But I've started an email thread with you to confirm that, so we needn't talk about it here.

I think in general, any info in that conceptual topic ought to also appear on the individual topic for each affected API. So that folks don't need to happen upon that conceptual topic in order to find the info. But that's a larger work item, and I've added that to my backlog. I'll get to it when I can. Again, no need to discuss here, just FYI.

I'll close this, then.

Thanks!
-Steve
