### ISSUE TITLE
General comments in XML format page

### ISSUE THREAD

**Issue by almedina-ms** [MicrosoftDocs/windows-uwp#4072]
Widgets will be introduced in Windows App SDK 1.2 Preview 2

Element Hierarchy could be shown in a diagram or through some other means, as it's hard to read. Having empty lines and tabs makes it prone to get "&nbsp" showing up as next to "Size"

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: e9395d81-bd55-f476-fd05-736a13583111
* Version Independent ID: e9395d81-bd55-f476-fd05-736a13583111
* Content: [Widget provider package manifest XML format - Windows apps](https://review.learn.microsoft.com/en-us/windows/apps/develop/widgets/widget-provider-manifest?branch=pr-en-us-2886)
* Content Source: [hub/apps/develop/widgets/widget-provider-manifest.md](https://github.com/MicrosoftDocs/windows-dev-docs/blob/docs/hub/apps/develop/widgets/widget-provider-manifest.md)
* Product: **reunion**
* Technology: **apps**
* GitHub Login: @drewbatgit
* Microsoft Alias: **drewbat**

**Comment by drewbatgit** [comment]
I have fixed the &nspb; typo and updated the boilerplate to refer to App SDK 1.2 Preview 2. The formatting for the element hierarchy is not ideal, but it is the current standard across the Windows schema docs. It looks bad in those docs as well, but because the hierarchies are smaller, it's not as bad. There are a lot of considerations here such as accessibility and standards across our docs content (we used to format these with html tags that are no longer allowed in the docs). I have escalated this issue and will update this content when we have a resolution, but I'm going to close this issue for now as it's not a ship-stopper.
