### ISSUE TITLE
incorrect example

### ISSUE THREAD

**Issue by TBugReporter** [MicrosoftDocs/windows-uwp#4083]
Line:

(^\w+\.$)¦(^\w+$) | $2.txt | Appends ".txt" extension to existing file name only if it does not have an extension

"¦" is wrong here; it should be the UNbroken vertical bar ("|").

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 4c2786bc-ad98-974e-d7b0-a6ce82f8b576
* Version Independent ID: 0be1b400-5349-7dd9-43d2-abd3a91884a6
* Content: [PowerToys PowerRename utility for Windows](https://learn.microsoft.com/en-us/windows/powertoys/powerrename)
* Content Source: [hub/powertoys/powerrename.md](https://github.com/MicrosoftDocs/windows-dev-docs/blob/docs/hub/powertoys/powerrename.md)
* Product: **dev-environment**
* Technology: **powertoys**
* GitHub Login: @mattwojo
* Microsoft Alias: **mattwoj**

**Comment by Jay-o-Way** [comment]
I know, I chose this character
(a) for readability (vertical bar can quickly be mistaken for lowercase `l`, uppercase `I`, or number `1`)

- ![image](https://user-images.githubusercontent.com/65828559/204413912-8c6bc3b3-9a37-4fe6-8ea1-5f0ad95a3eb5.png)

(b) prevent incorrect interpretation in the MarkDown table, since `|` is the cell delimiter
(c) because it is also printed on keyboards, for the exact same character (and probably because of _a_)

@mattwojo

**Comment by TBugReporter** [comment]
Ok, understood, but then you should mention that, because id10ts like me will come along, copy and paste, and complain about it not working. ;-)
