### ISSUE TITLE
[Teams-Manifest]: localization with zh language throws error on uploading manifest

### ISSUE THREAD

**Issue by raguravindran** [MicrosoftDocs/windows-uwp#4092]
When we have translation for generic Chinese localization _(top-level as **zh**)_ language, the manifest upload is failing and throws error. Though documents specifically mentioned 
- _"you must provide top level, language only translations in your manifest. For example, en instead of en-us. You must provide region level overrides only for the few strings that need them."_ (as mentioned in the document [here](https://learn.microsoft.com/en-us/microsoftteams/platform/concepts/build-and-test/apps-localization#example-localization-json-change))

<img width="988" alt="Screenshot 2022-10-11 at 1 40 49 PM" src="https://user-images.githubusercontent.com/36010645/195035026-65a0b5b4-e4f9-4407-9290-5b03c4e14d88.png">

- When I see supported languages the top level for chinese is not available. Can you please confirm if **"zh"** is officially not supported by Microsoft teams?
- When we change it as **zh-cn** and verify in [appValidation portal](https://dev.teams.microsoft.com/appvalidation.html) it seems to be passing, but **zh** as top level throws error. Please confirm.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 81b708c0-0754-a016-66b4-c1416f64da39
* Version Independent ID: 5f436e1a-aac8-0a5d-cab3-8bad9dbca012
* Content: [Supported languages - Microsoft Store](https://learn.microsoft.com/en-us/windows/uwp/publish/supported-languages)
* Content Source: [windows-apps-src/publish/supported-languages.md](https://github.com/MicrosoftDocs/windows-dev-docs/blob/docs/windows-apps-src/publish/supported-languages.md)
* Product: **uwp**
* Technology: **publish**
* GitHub Login: @hickeys
* Microsoft Alias: **hickeys**

**Comment by Paul-Dempsey** [comment]
This is likely By Design for Chinese. One must specify Traditional/Simplified -- there is no compatible generic.

**Comment by GrantMeStrength** [comment]
We are changing the way we track issues filed from our documentation pages: please see this [blog post](https://techcommunity.microsoft.com/t5/microsoft-learn-blog/announcing-a-new-way-to-give-feedback-on-microsoft-learn/ba-p/4027635) for more details. Right now, this issue is being closed but if you feel it is still valid and has not been addressed, please re-open it with any more available information. Please note that if your question is more general and not related to documentation, [Microsoft Q&A](https://learn.microsoft.com/en-us/answers/questions/) is a great way to get questions answered.
