### ISSUE TITLE
Add Section 10.7 - Permitted Use of 'Microsoft Store Edition' Suffix.  

### ISSUE THREAD

**Issue by rfreytag** [MicrosoftDocs/windows-uwp#4111]
Section 10.1 does not cover permitted descriptive use of "Microsoft Store Edition" in app names.  For example "CorelDRAW Microsoft Store Edition" is a permitted use (said app is currently in the Microsoft Store).  Suggest addition of following text ...

Section 10.7 - Permitted Use of 'Microsoft Store Edition' Suffix.  

Your product may use the text "Microsoft Store Edition" as a suffix in its name if and only if your product is offered through or for use with the Microsoft Store.

... end suggested new section text.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 8e47bfea-cf8e-d716-9880-6c15c31fcbdf
* Version Independent ID: ba95989d-2cb0-1644-7b38-24b2eab3b8c7
* Content: [Microsoft Store Policies - Microsoft Store](https://learn.microsoft.com/en-us/windows/uwp/publish/store-policies)
* Content Source: [uwp/publish/store-policies.md](https://github.com/MicrosoftDocs/windows-dev-docs/blob/docs/uwp/publish/store-policies.md)
* Product: **uwp**
* Technology: **publish**
* GitHub Login: @hickeys
* Microsoft Alias: **hickeys**

**Comment by rfreytag** [comment]
Current search of Microsoft Store offerings turns up five (5) apps using the suffix "Microsoft Store Edition" in their name.  For example, "CorelDRAW Microsoft Store Edition" is currently available in the Microsoft Store.  Freytag & Company, LLC app "App Publisher Microsoft Store Edition" is being rejected for using "Microsoft Store Edition."  Either we CAN use "Microsoft Store Edition" as a suffix or CorelDraw CANNOT use "Microsoft Store Edition" as a suffix in its name.  The Microsoft Store Policy needs to be clarified and uniformly enforced as to the use of the suffix "Microsoft Store Edition."

**Comment by GrantMeStrength** [comment]
We are changing the way we track issues filed from our documentation pages: please see this [blog post](https://techcommunity.microsoft.com/t5/microsoft-learn-blog/announcing-a-new-way-to-give-feedback-on-microsoft-learn/ba-p/4027635) for more details. The Microsoft Store documentation has been updated several times since your issue was reported, and there's a good chance your problem has been addressed. Right now, this issue is being closed but if you feel it is still valid and has not been addressed, please re-open it with any more available information. Please note that if you question is more general and not related to documentation, [Microsoft Q&A](https://learn.microsoft.com/en-us/answers/questions/) is a great way to get questions answered.
