### ISSUE TITLE
Unclear how exactly users are managed 

### ISSUE THREAD

**Issue by bestofbothworlds** [MicrosoftDocs/windows-uwp#4113]
This page is missing a lot of detail - how and where are users managed.
Which menu, how to navigate, limitations (user roles cannot be removed if the user has the same role, not higher).

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 83cdf72e-17b7-597a-de39-89cdd9ceb496
* Version Independent ID: 83cdf72e-17b7-597a-de39-89cdd9ceb496
* Content: [Manage account users - Windows apps](https://learn.microsoft.com/en-us/windows/apps/publish/partner-center/manage-account-users?source=recommendations)
* Content Source: [hub/apps/publish/partner-center/manage-account-users.md](https://github.com/MicrosoftDocs/windows-dev-docs/blob/docs/hub/apps/publish/partner-center/manage-account-users.md)
* Product: **reunion**
* Technology: **apps**
* GitHub Login: @Karl-Bridge-Microsoft
* Microsoft Alias: **kbridge**

**Comment by GrantMeStrength** [comment]
We are changing the way we track issues filed from our documentation pages: please see this [blog post](https://techcommunity.microsoft.com/t5/microsoft-learn-blog/announcing-a-new-way-to-give-feedback-on-microsoft-learn/ba-p/4027635) for more details. The Microsoft Store documentation has been updated several times since your issue was reported, and there's a good chance your problem has been addressed. Right now, this issue is being closed but if you feel it is still valid and has not been addressed, please re-open it with any more available information. Please note that if you question is more general and not related to documentation, [Microsoft Q&A](https://learn.microsoft.com/en-us/answers/questions/) is a great way to get questions answered.
