### ISSUE TITLE
Page does not explain how to set roles

### ISSUE THREAD

**Issue by bestofbothworlds** [MicrosoftDocs/windows-uwp#4114]
Hi,

this page has a long list of role permissions etc, but it does not explain how they are actually set, screenshot etc (navigation in the UI).
It is also not clear how the owner can be changed and why this can't be part of the Azure AD tenant (I have a long conversation with support with no conclusion about this).

Best regards, Ingmar

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: d21c8ca4-68c7-571f-48e6-38b1d9069b71
* Version Independent ID: d21c8ca4-68c7-571f-48e6-38b1d9069b71
* Content: [Set roles or custom permissions for account users - Windows apps](https://learn.microsoft.com/en-us/windows/apps/publish/partner-center/set-custom-permissions-for-account-users)
* Content Source: [hub/apps/publish/partner-center/set-custom-permissions-for-account-users.md](https://github.com/MicrosoftDocs/windows-dev-docs/blob/docs/hub/apps/publish/partner-center/set-custom-permissions-for-account-users.md)
* Product: **reunion**
* Technology: **apps**
* GitHub Login: @Karl-Bridge-Microsoft
* Microsoft Alias: **kbridge**

**Comment by GrantMeStrength** [comment]
We are changing the way we track issues filed from our documentation pages: please see this [blog post](https://techcommunity.microsoft.com/t5/microsoft-learn-blog/announcing-a-new-way-to-give-feedback-on-microsoft-learn/ba-p/4027635) for more details. The Microsoft Store documentation has been updated several times since your issue was reported, and there's a good chance your problem has been addressed. Right now, this issue is being closed but if you feel it is still valid and has not been addressed, please re-open it with any more available information. Please note that if you question is more general and not related to documentation, [Microsoft Q&A](https://learn.microsoft.com/en-us/answers/questions/) is a great way to get questions answered.
