### ISSUE TITLE
Error description not sufficient, troubleshooting steps not mentioned anywhere else as required for partner center

### ISSUE THREAD

**Issue by bestofbothworlds** [MicrosoftDocs/windows-uwp#4115]
Hi all, 

this page is confusing :
* the error description is extremely broad
* it is unexpected that Azure AD user config/roles is required while there is a dedicated user management in Partner center
* unclear if this refers to interactive users or Azure AD services for automation
* why is Azure AD application developer role suddenly required for Partner center ? This is the first time this is mentioned in the whole documentation
* why the need to have the permission to register applications in Azure AD? The published apps in the Windows store do not necessarily have an Azure AD integration

Best regards, Ingmar

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 7bea293a-15e7-2a22-93ff-34a65b96483b
* Version Independent ID: 7bea293a-15e7-2a22-93ff-34a65b96483b
* Content: [Troubleshoot App Creation in Partner Center - Windows apps](https://learn.microsoft.com/en-us/windows/apps/publish/partner-center/troubleshoot-app-creation)
* Content Source: [hub/apps/publish/partner-center/troubleshoot-app-creation.md](https://github.com/MicrosoftDocs/windows-dev-docs/blob/docs/hub/apps/publish/partner-center/troubleshoot-app-creation.md)
* Product: **reunion**
* Technology: **apps**
* GitHub Login: @Karl-Bridge-Microsoft
* Microsoft Alias: **kbridge**

**Comment by GrantMeStrength** [comment]
We are changing the way we track issues filed from our documentation pages: please see this [blog post](https://techcommunity.microsoft.com/t5/microsoft-learn-blog/announcing-a-new-way-to-give-feedback-on-microsoft-learn/ba-p/4027635) for more details. The Microsoft Store documentation has been updated several times since your issue was reported, and there's a good chance your problem has been addressed. Right now, this issue is being closed but if you feel it is still valid and has not been addressed, please re-open it with any more available information. Please note that if you question is more general and not related to documentation, [Microsoft Q&A](https://learn.microsoft.com/en-us/answers/questions/) is a great way to get questions answered.
