### ISSUE TITLE
Get 403 when using "api/taskmanager/process" to kill a process

### ISSUE THREAD

**Issue by LimingRenPA** [MicrosoftDocs/windows-uwp#4118]
Here is what I did on my Windows machine:
(0) my HoloLens2 is connect to my Windows machine, developer enabled, with username and password, 
(1) Open HoloLens2  Device portal  https://ipaddress/#Home, using  the username and password, .
(2) C# code ,  HttpClient Get "api/resourcemanager/processes" to get all processes using basic security,

All above steps finished successfully. 

(3) Select a specific HoloLens2  process (created by me and started by me) using basic security,
     call  HttpClient Delete "api/taskmanager/process?pid=XXXX",

**This step returns 403**

Need help to troubleshoot this, where can I find a sample code.

Thanks,

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 606c1247-47ba-a3fd-3abc-c072336bf019
* Version Independent ID: 729ff3d9-ebe0-bf23-605c-1ea1b0f2d3bd
* Content: [Windows Device Portal core REST API reference - UWP applications](https://learn.microsoft.com/en-us/windows/uwp/debug-test-perf/device-portal-api-core)
* Content Source: [uwp/debug-test-perf/device-portal-api-core.md](https://github.com/MicrosoftDocs/windows-dev-docs/blob/docs/uwp/debug-test-perf/device-portal-api-core.md)
* Product: **uwp**
* Technology: **deployment**
* GitHub Login: @Karl-Bridge-Microsoft
* Microsoft Alias: **kbridge**

**Comment by Karl-Bridge-Microsoft** [comment]
For community assistance with development questions, there are our [forums](https://social.msdn.microsoft.com/Forums/newthread?category=windowsapps&forum=wpdevelop&prof=required), and [StackOverflow](https://stackoverflow.com/questions).

For completeness, here are a few more developer support resources.

-The [Feedback Hub app](https://support.microsoft.com/help/4021566/windows-10-send-feedback-to-microsoft-with-feedback-hub-app) is the right place to lobby for a change, a feature, or to make a suggestion.
- For developer issues, or suspected product bugs, contact [Microsoft Support](https://support.microsoft.com/contactus). A support engineer will look at the repro and see whether the issue is a Microsoft product bug, or something else. If it's a bug with a Microsoft product then the ticket will be free of charge.
- The [Windows developer support](https://developer.microsoft.com/windows/support) site explains other support options.
- The [Visual Studio developer community](https://developercommunity.visualstudio.com) is available, and responsive. The former User Voice feature is now there on the **Suggest a feature** tab, if you want to lobby for a change, a feature, or to make a suggestion.

If you receive assistance via any support resource, and you believe that information would help us improve the docs, then please come back and let us know.
