### ISSUE TITLE
cid as described no longer tracked

### ISSUE THREAD

**Issue by sanjayssk** [MicrosoftDocs/windows-uwp#4129]
This was working before the new Store. Campaign ID reports on cid were produced. Now with new store, this no longer works. Campaign report is just empty.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 277ad2da-517f-7d8d-bc27-b0b89928db6b
* Version Independent ID: 277ad2da-517f-7d8d-bc27-b0b89928db6b
* Content: [Create a custom app promotion campaign - Windows apps](https://learn.microsoft.com/en-us/windows/apps/publish/create-a-custom-app-promotion-campaign)
* Content Source: [hub/apps/publish/create-a-custom-app-promotion-campaign.md](https://github.com/MicrosoftDocs/windows-dev-docs/blob/docs/hub/apps/publish/create-a-custom-app-promotion-campaign.md)
* Product: **reunion**
* Technology: **apps**
* GitHub Login: @Karl-Bridge-Microsoft
* Microsoft Alias: **kbridge**

**Comment by GrantMeStrength** [comment]
We are changing the way we track issues filed from our documentation pages: please see this [blog post](https://techcommunity.microsoft.com/t5/microsoft-learn-blog/announcing-a-new-way-to-give-feedback-on-microsoft-learn/ba-p/4027635) for more details. The Microsoft Store documentation has been updated several times since your issue was reported, and there's a good chance your problem has been addressed. Right now, this issue is being closed but if you feel it is still valid and has not been addressed, please re-open it with any more available information. Please note that if you question is more general and not related to documentation, [Microsoft Q&A](https://learn.microsoft.com/en-us/answers/questions/) is a great way to get questions answered.
