### ISSUE TITLE
Page lacks definition of what a Memory Failure is and what it means for the app (crash?)

### ISSUE THREAD

**Issue by yamoinza** [MicrosoftDocs/windows-uwp#4146]
The page mentions "memory" failures but doesn't explain what this category of issue means.
It could be an Out of Memory failure, an invalid access type failure, or ...
It also isn't necessarily clear that this means the app was "killed"/"crashed" or not? Eg is this a caught exception or is the implication that this is an unhandled error and caused the app to quit?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 64421026-2df7-86fa-e829-6b7bfa293cde
* Version Independent ID: 64421026-2df7-86fa-e829-6b7bfa293cde
* Content: [Health report - Windows apps](https://learn.microsoft.com/en-us/windows/apps/publish/health-report#failure-hits)
* Content Source: [hub/apps/publish/health-report.md](https://github.com/MicrosoftDocs/windows-dev-docs/blob/docs/hub/apps/publish/health-report.md)
* Product: **reunion**
* Technology: **apps**
* GitHub Login: @Karl-Bridge-Microsoft
* Microsoft Alias: **kbridge**

**Comment by GrantMeStrength** [comment]
We are changing the way we track issues filed from our documentation pages: please see this [blog post](https://techcommunity.microsoft.com/t5/microsoft-learn-blog/announcing-a-new-way-to-give-feedback-on-microsoft-learn/ba-p/4027635) for more details. The Microsoft Store documentation has been updated several times since your issue was reported, and there's a good chance your problem has been addressed. Right now, this issue is being closed but if you feel it is still valid and has not been addressed, please re-open it with any more available information. Please note that if you question is more general and not related to documentation, [Microsoft Q&A](https://learn.microsoft.com/en-us/answers/questions/) is a great way to get questions answered.
