### ISSUE TITLE
ECONNREFUSED: Install React Step 3 - WSL2 proxy error?

### ISSUE THREAD

**Issue by Oertlig** [MicrosoftDocs/windows-uwp#4149]
npx create-react-app my-app always fails to run with an ECONNREFUSED error. The error suggests that my proxy config isn't set up properly, the instructions don't mention anything about proxies. 

From my quick searching, it sounds like WSL2 is being used now and is more of a virtual machine than the first WSL, which might have something to do with the error.
![Screenshot 2022-11-15 200658](https://user-images.githubusercontent.com/43556661/202081843-7c188fcd-0593-417d-9310-df81f7f4eba9.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 89f5b5f4-c9f6-2618-5711-554436d4592c
* Version Independent ID: d37910a5-4903-81a7-7450-b827cd7ddfbe
* Content: [Install React on Windows Subsystem for Linux](https://learn.microsoft.com/en-us/windows/dev-environment/javascript/react-on-wsl)
* Content Source: [hub/dev-environment/javascript/react-on-wsl.md](https://github.com/MicrosoftDocs/windows-dev-docs/blob/docs/hub/dev-environment/javascript/react-on-wsl.md)
* Product: **dev-environment**
* Technology: **windows-javascript**
* GitHub Login: @mattwojo
* Microsoft Alias: **mattwoj**

**Comment by mattwojo** [comment]
Yes, I would definitely recommend using the WSL 2 architecture. Currently it looks like you're storing your project files on a mounted C-drive, which can lead to compat issues because your crossing file systems. 
There's also some info in this StackOverflow post about clearing proxy settings on NPM that you could try, but first switch to WSL 2 and see if that resolves the issue: https://learn.microsoft.com/windows/wsl/basic-commands#set-wsl-version-to-1-or-2

Clear NPM proxy settings: https://stackoverflow.com/questions/21228995/how-to-clear-https-proxy-setting-of-npm

I'm closing this issue as it doesn't appear to require an update to the documentation, but please re-open if that isn't the case. For any further technical assistance, I'd recommend looking at the issues in the WSL product repo: https://github.com/microsoft/WSL/issues/ (You may also check out this issue: https://github.com/microsoft/WSL/issues/4885)
Or in the npm repo: https://github.com/npm/npx/issues
Both feedback areas will likely be more visible to folks with further expertise on this topic. (And please do let me know if you discover anything that should be better documented in this guide to help folks get started. Thank you!!!
