### ISSUE TITLE
No mention on what "Top 10" an "Top 15" mean

### ISSUE THREAD

**Issue by marco-de-angelis** [MicrosoftDocs/windows-uwp#4163]
"Install" analytics reports 3 metrics (actually, 4 in our view, with a duplicate "Page views" metric):
* "Page views"
* "Top 10"
* "Top 15"

There's currently no mention of what they represent. My (personal) guess is that the MS Store ranks apps, takes the top 10 apps, calculates the *average* number of page views, and shows them in the chart for you to compare your performance against the top 10 and 15 apps.  It's also not clear what is the ranking category: is it based on all apps, or the major app category, or the major and secondary app categories?

---
#### Document details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: cd054b09-3354-bacc-9cb9-3bcc80fe14d2
* Version Independent ID: cd054b09-3354-bacc-9cb9-3bcc80fe14d2
* Content: [Acquisitions report - Windows apps](https://learn.microsoft.com/en-gb/windows/apps/publish/acquisitions-report)
* Content Source: [hub/apps/publish/acquisitions-report.md](https://github.com/MicrosoftDocs/windows-dev-docs/blob/docs/hub/apps/publish/acquisitions-report.md)
* Product: **reunion**
* Technology: **apps**
* GitHub Login: @Karl-Bridge-Microsoft
* Microsoft Alias: **kbridge**

**Comment by GrantMeStrength** [comment]
We are changing the way we track issues filed from our documentation pages: please see this [blog post](https://techcommunity.microsoft.com/t5/microsoft-learn-blog/announcing-a-new-way-to-give-feedback-on-microsoft-learn/ba-p/4027635) for more details. The Microsoft Store documentation has been updated several times since your issue was reported, and there's a good chance your problem has been addressed. Right now, this issue is being closed but if you feel it is still valid and has not been addressed, please re-open it with any more available information. Please note that if you question is more general and not related to documentation, [Microsoft Q&A](https://learn.microsoft.com/en-us/answers/questions/) is a great way to get questions answered.
