### ISSUE TITLE
Windows Push Service returns wrong status code 406 instead of 429

### ISSUE THREAD

**Issue by collimarco** [MicrosoftDocs/windows-uwp#4166]
Please take a look at this related issue in the web push libraries:

https://github.com/zaru/webpush/pull/103

It doesn't make sense and **it is against web standards to return a 406 for rate limiting**. 406 has a [very specific meaning](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/406).

This causes serious problems to the web push libraries, but it cannot be solved inside the libraries (because the libraries are correct and need to follow the standard).

Please consider fixing this wrong behavior and updating your documentation here:

https://learn.microsoft.com/en-us/windows/apps/design/shell/tiles-and-notifications/push-request-response-headers#response-codes

Please mention/tag the right team. Thanks

**Comment by drewbatgit** [comment]
@collimarco Thanks for your feedback about this issue. I've notified the feature team and asked them to take a look. Since this appears to be a code issue with the feature and issues in this repo are specifically intended to address the documentation, I'm going to go ahead and mark this issue as closed, but the feature team will revisit the issue and may continue the conversation.
