### ISSUE TITLE
Attempted to read or write protected memory. this is often an indication that other memory is corrupt

### ISSUE THREAD

**Issue by git102347501** [MicrosoftDocs/windows-uwp#4167]
Env:

GUI: WinUi3
IDE: VS2022
System: Win11

Question:

I try to add the List content to the DataSource again after clearing the DataSource, and there is a chance to throw the following error：
Attempted to read or write protected memory. this is often an indication that other memory is corrupt

![d6dea131713bd1e6931e44a35eaba66](https://user-images.githubusercontent.com/37917403/204255542-2b725112-9e93-426b-836d-175c79983cc4.png)

My Code：

```
 public ObservableCollection<ExplorerItem> DataSource = new ObservableCollection<ExplorerItem>();
 public List<Object> List = new List<Object>();
 // ..
 this.DataSource.Clear();
 List.ForEach(c => DataSource.Add(new ExplorerItem() { 
      Name = c.Name,
      Id = c.Id
  }));

```

**Comment by Karl-Bridge-Microsoft** [comment]
For community assistance with development questions, there are our [forums](https://social.msdn.microsoft.com/Forums/newthread?category=windowsapps&forum=wpdevelop&prof=required), and [StackOverflow](https://stackoverflow.com/questions). If this is a WinUI/WinApp SDK issue, please post your issue/question at https://github.com/microsoft/WindowsAppSDK.

For completeness, here are a few more developer support resources.

-The [Feedback Hub app](https://support.microsoft.com/help/4021566/windows-10-send-feedback-to-microsoft-with-feedback-hub-app) is the right place to lobby for a change, a feature, or to make a suggestion.
- For developer issues, or suspected product bugs, contact [Microsoft Support](https://support.microsoft.com/contactus). A support engineer will look at the repro and see whether the issue is a Microsoft product bug, or something else. If it's a bug with a Microsoft product then the ticket will be free of charge.
- The [Windows developer support](https://developer.microsoft.com/windows/support) site explains other support options.
- The [Visual Studio developer community](https://developercommunity.visualstudio.com) is available, and responsive. The former User Voice feature is now there on the **Suggest a feature** tab, if you want to lobby for a change, a feature, or to make a suggestion.

If you receive assistance via any support resource, and you believe that information would help us improve the docs, then please come back and let us know.
