### ISSUE TITLE
Toast Notification IOException

### ISSUE THREAD

**Issue by ghost** [MicrosoftDocs/windows-uwp#4170]
After copy and pasting the exact code from the documentation, this following exception comes up:

```
System.InvalidOperationException: 'Failed initializing notifications'

Inner Exception
IOException: Cannot create a stable subkey under a volatile parent key.
```

The app compiles without any issues or anything, but will not work when the code runs. I have tried on fresh Console Applications and Windows Forms applications, and both have the same error when the code is ran.

Currently running Windows 11 22H2 if that matters.
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 11bc1ceb-510e-22c9-1f7a-a421ae52901b
* Version Independent ID: 0efae90c-e517-b54d-8e81-ebbd69d2270d
* Content: [Send a local toast notification from a C# app - Windows apps](https://learn.microsoft.com/en-us/windows/apps/design/shell/tiles-and-notifications/send-local-toast?tabs=uwp)
* Content Source: [hub/apps/design/shell/tiles-and-notifications/send-local-toast.md](https://github.com/MicrosoftDocs/windows-dev-docs/blob/docs/hub/apps/design/shell/tiles-and-notifications/send-local-toast.md)
* Product: **reunion**
* Technology: **design**
* GitHub Login: @hickeys
* Microsoft Alias: **hickeys**

**Comment by pmpurifoy** [comment]
Do you have the specific API call which is the source of failure?

**Comment by ghost** [comment]
I made a new console application (.NET framework) and pasted the code into the `Main()` as a test and it gave me that error. Also tested in fresh .NET framework WinForm app.

**Comment by drewbatgit** [comment]
@verlox I reached out to the Notifications feature team and the issue that you are encountering is described here: [Diagnosing why you cannot create a stable subkey under a volatile parent key](https://devblogs.microsoft.com/oldnewthing/20170525-00/?p=96225). Unfortunately, this indicates that your issue is likely an environment issue rather than an API issue. We are not equipped to provide developer support through the documentation repo. I would recommend that you post this issue at [Microsoft Q&A](https://learn.microsoft.com/en-us/answers/questions/) to get help.
