### ISSUE TITLE
Update request: How to build a hello world app

### ISSUE THREAD

**Issue by QueuQ** [MicrosoftDocs/windows-uwp#4188]
Is it possible to update a C++ version? 

By the way, is there any more advanced tutorials beyond this simple Hello World example?

Thanks

**Comment by mattwojo** [comment]
Hey @QueuQ -- Could you specify which How to build a hello world app tutorial you're referring to?

**Comment by mattwojo** [comment]
@QueuQ -- Closing this issue as we need more information about what tutorial you're referring to in order to take action, but please feel welcome to re-open and add more specifics.

**Comment by sotanakamura** [comment]
@mattwojo This issue is generated by a link in following page;
Build a Hello World app using C# and WinUI 3 / Windows App SDK
https://learn.microsoft.com/en-us/windows/apps/how-tos/hello-world-winui3

I think this tutorials is important for WinUI 3 app developers who do both design and development. Design and Development chapters are too general. 

WinUI 3 app development in C++ is very difficult because C++ developer should learn many things about C++/WinRT and IDL before starting development. Generated files from project template is different in C# and C++. I suggest that we should create following contents;

- Create a WinUI 3 app from scratch (C#): If it is needed
-  Create a WinUI 3 app from scratch (C++): Create a WinUI 3 app in C++ without XAML to start with minimal code and understand a concept of C++/WinRT.
-  Explore a WinUI 3 app project template (C#)
-  Explore a WinUI 3 app project template (C++): Explain what generated files are needed for and basic concepts of C++/WinRT and IDL.
- WinUI 3 Styles (C#/C++): Contents about styles and controls are almost the same in C# and C++.
- WinUI 3 Controls (C#/C++)
- ...

If I have a time I want to contribute.

**Comment by sotanakamura** [comment]
@mattwojo  Some beginner needs step by step guide to create WinUI 3 app C++ without XAML. I created an article how to do it. It is good for  not only creating WinUI 3 app C++ without XAML but also understanding what happens inside. Please consider to include it to the official document. 

WinUI 3 in C++ Without XAML
https://github.com/sotanakamura/winui3-without-xaml

**Comment by b224618** [comment]
Many thanks to the help from @sotanakamura and @mattwojo, especially the detailed explanation from @sotanakamura  . Sorry @mattwojo that I didn't respond in time, since I got some trouble accessing GitHub when I received email notification of your comment, and I forgot this issue later.

**Comment by QueuQ** [comment]
Many thanks to the help from @sotanakamura and @mattwojo, especially the detailed explanation from @sotanakamura . Sorry @mattwojo that I didn't respond in time, since I got some trouble accessing GitHub when I received email notification of your comment, and I forgot this issue later.
