### ISSUE TITLE
pretty useless page

### ISSUE THREAD

**Issue by stan-ac** [MicrosoftDocs/windows-uwp#4192]
[Enter feedback here]
crappy page - it assumes you need help running a wizard to set up a c++ file but then you're on your own after a bit of unclear information, and links which offer various options without any guidance. why bother?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 9564158a-dfea-b690-7b5e-5f6987019710
* Version Independent ID: 1a90b127-6ad9-a28e-0ee4-16170021b104
* Content: [Create your first WinUI 3 (Windows App SDK) project - Windows apps](https://learn.microsoft.com/en-us/windows/apps/winui/winui3/create-your-first-winui3-app)
* Content Source: [hub/apps/winui/winui3/create-your-first-winui3-app.md](https://github.com/MicrosoftDocs/windows-dev-docs/blob/docs/hub/apps/winui/winui3/create-your-first-winui3-app.md)
* Product: **reunion**
* Technology: **winui-conceptual**
* GitHub Login: @stevewhims
* Microsoft Alias: **stwhi**

**Comment by stevewhims** [comment]
Hi, @stan-ac, and thanks for filing an issue. This topic is really just meant to show how to create a WinUI 3 project in Visual Studio.

In its first section ("Packaged, unpackaged, and packaged with external location"), the topic provides (a link to) info about the advantages and disadvantages of packaging your app. With that info, you can decide which of the sections of the topic to follow along with (the Packaged or Unpackaged sections). The topic also provides info about the third (rare) option, which is an app that's "packaged with external location".

The topic also walks through, and describes, some of the high-level features of the source code in the project that VS generates.

The topic ends by directing the reader to the main body of the documentation for the Windows App SDK (and desktop apps in general) so that they can take the skeleton project and turn it into an app with features.

When you say "links that offer various options without any guidance", is that in reference to the "Related topics" section at the end? That's essentially just all of the links that have been mentioned within the body of the topic gathered together in one place. The use case for that is that you've read the topic, you remember that there's a certain link in there (when the link first appears in the topic, that's where the guidance/rationale is for it), and you can then find that link immediately without hunting for it again in the topic.

Is there any other specific guidance that's missing from the topic?

Thanks!
-Steve

**Comment by stan-ac** [comment]
HI Steve

Thanks for taking the trouble to write back, to be honest I was not
expecting it.
I really have not got a lot to say specifically about this page, since the
entire flow does not work imho.

If you come to this page as I am with experience using vs c++ with qt or
wxwidgets etc since microsoft is finally offering a gui in c++ again you
will find that each step offers you "if you are using this go here or that
go there".

But each "this and that" underlying technology is a huge topic in itself
and the flows tend to be at a page level only (that's why wer'e discussing
a page only ).
Nothing fills in the gaps or even tells you where to go next.

So while one page (no only this one) purports to hold you're hand with a
nice wizard, once you build that page there is no guidance about how to use
it, or where to go next.
So for example I built a nice page which when run says click me. But now
what? how to add extra pages, controls? where should my c++ code go? how do
they interact? is there a gui designer? There is a pretty demo on github
showing what you can do.

So is my best option to reverse-engineer the demo?
You get the idea.
I hope you can do more than just adjust the page.
sincerely
Stan

**Comment by stevewhims** [comment]
Thanks, @stan-ac!

I've just updated the topic to add a little bit more substance to the "Next steps" section. Now it directs you to the following topic (the "simple photo viewer" topic). That's where you not only create a new project, but also add functionality to it. I think that addresses the "where to go next" issue. However, that "simple photo viewer" topic is for C#, so I've updated it with links to the C++/WinRT content. And that C++/WinRT content addresses the "how to add extra pages, controls? where should my c++ code go?" issues.

I'm afraid that this is not the outcome you're looking for, but I do feel that the current topic is factored and scoped correctly. It exists really just to introduce the Visual Studio project templates. But to do that, we then bumped into the packaged/unpackaged decision. And then of course we had to cover the C# and C++ flavors of the template. And then there was a customer request to explain a little about what the templates contain, and what they do (source-code wise). So the topic has now grown to a decent size, and I feel that if it were made any longer then it wouldn't be attractive as a modest "start here" type topic. When you've finished the topic, you're meant to (and you do!) know about the templates and packaging (so you know more than before you read it). But it definitely doesn't answer/address everything. It must link off to lots of other places for lots of further details (and folks might land on those other places first, so we don't want to duplicate info, but we do want the info to be reachable from anywhere). And that's what the rest of the docs is for.

While I don't see the page as "useless", I would call it a page with (intentionally) modest ambitions. Its ambitions are to, as I say, introduce the templates, and packaging, and then to send the reader on to the next port of call to learn more (to learn the kinds of things that you mention).

I'll go ahead and close the issue, since I don't have plans to significantly update/refactor/re-scope this topic. Again, I understand that that might not be a satisfactory answer for this thread.

Thanks!
-Steve
