### ISSUE TITLE
"Switch between windows in the current zone" is too "blind"

### ISSUE THREAD

**Issue by h2oicsaba** [MicrosoftDocs/windows-uwp#4202]
This remark is regarding "Switch between windows in the current zone".
Can we have here some popups to see what are the possible selections in that zone? Like using the well-known Alt+Tab switching method. 
Ok, it is doing the job but somehow, I feel this functionality too blind (for 2022 :)
If this original Window switcher style, is not available, maybe the icons of the programs could be used.   

Thank you!

**Comment by mattwojo** [comment]
Same as previous issue -- this repo is just for keeping documentation up to date. For feature requests like this, please check the issues in the PowerToys product repo to see if anyone has already filed a similar request: https://github.com/microsoft/PowerToys/issues
If you don't see a similar request to thumbs up and express support for, select "New issue" and add your request.
Closing the issue here in the docs repo.
Thanks again @h2oicsaba
