### ISSUE TITLE
There should be an example for Azure DevOps too

### ISSUE THREAD

**Issue by jfranki** [MicrosoftDocs/windows-uwp#4218]
All the document is focused on GitHub Actions. There should be an option to choose the code for Azure DevOps pipelines.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 544d5847-b3e1-70d6-14b6-733c5d85d649
* Version Independent ID: 544d5847-b3e1-70d6-14b6-733c5d85d649
* Content: [Set up continuous integration for your WinUI 3 app - Windows apps](https://learn.microsoft.com/en-us/windows/apps/package-and-deploy/ci-for-winui3?pivots=winui3-packaged-csharp)
* Content Source: [hub/apps/package-and-deploy/ci-for-winui3.md](https://github.com/MicrosoftDocs/windows-dev-docs/blob/docs/hub/apps/package-and-deploy/ci-for-winui3.md)
* Product: **reunion**
* Technology: **deployment**
* GitHub Login: @stevewhims
* Microsoft Alias: **stwhi**

**Comment by stevewhims** [comment]
Thanks, @jfranki! I don't have the info to hand about how to do these steps with Azure DevOps rather than GitHub Actions. But I've reached out internally for that info. If/when I receive it, I'll update the topic. Meanwhile closing this issue, since I'm tracking the request internally.

Thanks again!
-Steve
