### ISSUE TITLE
WASDK article on apps packaged with external location is missing a hyperlink

### ISSUE THREAD

**Issue by houserrob** [MicrosoftDocs/windows-uwp#4230]
There is a hyperlink missing in this article.  The doc currently states:

_then you can instead call the bootstrapper API explicitly. More info about that in this topic._

But I don't see a hyperlink.    I'm guessing it's intending to point to https://learn.microsoft.com/en-us/windows/windows-app-sdk/api/win32/_bootstrap/?  

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: f3419ef8-7c06-8d25-45fb-7db9e1757845
* Version Independent ID: f3419ef8-7c06-8d25-45fb-7db9e1757845
* Content: [Use the Windows App SDK runtime for apps packaged with external location or unpackaged - Windows apps](https://learn.microsoft.com/en-us/windows/apps/windows-app-sdk/use-windows-app-sdk-run-time)
* Content Source: [hub/apps/windows-app-sdk/use-windows-app-sdk-run-time.md](https://github.com/MicrosoftDocs/windows-dev-docs/blob/docs/hub/apps/windows-app-sdk/use-windows-app-sdk-run-time.md)
* Product: **reunion**
* Technology: **get-started**
* GitHub Login: @stevewhims
* Microsoft Alias: **stwhi**

**Comment by stevewhims** [comment]
Thanks, @houserrob, I'll re-word it because it's not clear enough. It means "this topic" as in "the topic you're currently reading". One of our writing guidelines is never to use text such as "here" or "this topic" as link text (linking someplace else); the reason being that there's no info in link text like that as to where you're being taken (so you don't know until you get there). However, using such language is fairly prevalent across the web, so I can see how the phrase "this topic" has become ambiguous.

I'll say something like, "continue reading this topic for more info about that". The "this topic" part of that might still feel like it should be hyperlinked, but I'm thinking that the "continue reading" part will help.

Thanks again!
-Steve

**Comment by stevewhims** [comment]
UPDATE: I ended up changing the wording to "But if you have advanced needs (such as handling errors by showing your own custom UI or logging, or if you need to load a version of the Windows App SDK that's different from the version you built with), then continue reading this topic.". I think that's better than before.

-Steve

**Comment by houserrob** [comment]
Thanks Steve for the super quick response and resolution.
________________________________
