### ISSUE TITLE
Elaborate on types of failures

### ISSUE THREAD

**Issue by avakhrushev** [MicrosoftDocs/windows-uwp#4307]
>Each type of event that your app experienced is tracked separately: crashes, hangs, JavaScript exceptions, and memory failures.

What is the purpose of this separation? What conclusions about apps health are to be drawn from it? What defines each category, how events are assigned into one or another? The explanation is cut short, and there does not seem to be another source that would go in-depth on these.

For example, we investigate a case where an app is terminated via fastfail 7 ; the corresponding reports are placed under the Memory failures. Is this a useful insight into the underlying cause, or just an artefact of the failure not fitting in with "crashes" or "hangs", how does one tell?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 64421026-2df7-86fa-e829-6b7bfa293cde
* Version Independent ID: 64421026-2df7-86fa-e829-6b7bfa293cde
* Content: [Health report - Windows apps](https://learn.microsoft.com/en-us/windows/apps/publish/health-report)
* Content Source: [hub/apps/publish/health-report.md](https://github.com/MicrosoftDocs/windows-dev-docs/blob/docs/hub/apps/publish/health-report.md)
* Product: **reunion**
* Technology: **apps**
* GitHub Login: @hickeys
* Microsoft Alias: **hickeys**

**Comment by GrantMeStrength** [comment]
We are changing the way we track issues filed from our documentation pages: please see this [blog post](https://techcommunity.microsoft.com/t5/microsoft-learn-blog/announcing-a-new-way-to-give-feedback-on-microsoft-learn/ba-p/4027635) for more details. The Microsoft Store documentation has been updated several times since your issue was reported, and there's a good chance your problem has been addressed. Right now, this issue is being closed but if you feel it is still valid and has not been addressed, please re-open it with any more available information. Please note that if you question is more general and not related to documentation, [Microsoft Q&A](https://learn.microsoft.com/en-us/answers/questions/) is a great way to get questions answered.
