### ISSUE TITLE
// main.cpp #include "pch.h"  #include <winrt/base.h> #include <windows.h>  template <typename T> struct completion_source {     ... // Paste the listing of completion_source here. }  using namespace std::literals; using namespace winrt; using namespace Windows::Foundation;  fire_and_forget CompleteAfterFiveSecondsAsync(completion_source<bool>& completionSource) {     co_await 5s;     completionSource.set(true); }  IAsyncAction CompletionSourceExample1Async() {     completion_source<bool> completionSource;     CompleteAfterFiveSecondsAsync(completionSource);     co_await completionSource; }  int main() {     auto asyncAction { CompletionSourceExample1Async() };     puts("waiting");     asyncAction.get();     puts("done"); }

### ISSUE THREAD

**Issue by adndrk99** [MicrosoftDocs/windows-uwp#4308]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 09a2d527-a517-f396-87f8-083f8d2b4b07
* Version Independent ID: b7888a99-245d-7dbb-2789-ee671093bbfa
* Content: [Windows Runtime components with C++/WinRT - UWP applications](https://learn.microsoft.com/en-us/windows/uwp/winrt-components/create-a-windows-runtime-component-in-cppwinrt)
* Content Source: [uwp/winrt-components/create-a-windows-runtime-component-in-cppwinrt.md](https://github.com/MicrosoftDocs/windows-dev-docs/blob/docs/uwp/winrt-components/create-a-windows-runtime-component-in-cppwinrt.md)
* Product: **uwp**
* Technology: **platform**
* GitHub Login: @stevewhims
* Microsoft Alias: **stwhi**

**Comment by stevewhims** [comment]
The title here is a just a copy of the source code example in the section [Offload completion to a separate coroutine](https://learn.microsoft.com/windows/uwp/cpp-and-winrt-apis/concurrency-3#offload-completion-to-a-separate-coroutine), which is in a different topic from the one against which this issue was filed. And there's no feedback.

It looks like this issue was created in error, so closing.

Thanks!
-Steve
