### ISSUE TITLE
Ready to upload my app's installer

### ISSUE THREAD

**Issue by LenYates** [MicrosoftDocs/windows-uwp#4325]
I'm ready to upload my app's installer, but your website just keeps taking me in circles.  Instead of just giving me lots of test about uploading the MSIX file, how about letting me actually do it?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 1da800f3-fb5b-3774-b32f-5da9a24a2ff1
* Version Independent ID: 1da800f3-fb5b-3774-b32f-5da9a24a2ff1
* Content: [Upload app packages - Windows apps](https://learn.microsoft.com/en-us/windows/apps/publish/publish-your-app/upload-app-packages)
* Content Source: [hub/apps/publish/publish-your-app/upload-app-packages.md](https://github.com/MicrosoftDocs/windows-dev-docs/blob/docs/hub/apps/publish/publish-your-app/upload-app-packages.md)
* Product: **reunion**
* Technology: **apps**
* GitHub Login: @hickeys
* Microsoft Alias: **hickeys**

**Comment by hickeys** [comment]
@LenYates You can upload your app using [Partner Center](https://partner.microsoft.com/dashboard/apps-and-games/overview)

The publish documentation is designed to walk you through the publish process on Partner Center. Can I ask if this was how you were using it? If that isn't coming across, then I might need to look at ways to clarify.

**Comment by LenYates** [comment]
Viewing your main web page, https://www.advancedinstaller.com/, it seems to
me that this is a system for creating a .msix file.

I already created my .msix file, so no need to create it again.

The question I have is this:  Do you have a system that walks me through
the process of publishing a Microsoft game?  If so, that would be
wonderful, as the Microsoft system itself is a gigantic mess.

Len

**Comment by hickeys** [comment]
Len,

Several comments. First, the website you linked is not a Microsoft website. I cannot speak to the details of how to use their technology, or what you can/can't do with its outputs. For the rest of this comment, I'll assume you have an MSIX installer file that you want to upload to the store, and I won't worry about how you created it. 

Second, you're in the right place. The documentation you were reading when you filed this issue is part of a step-by-step guide to get your app or game in the store. It's designed to be followed start-to-finish. I'd recommend reviewing the [process](https://learn.microsoft.com/windows/apps/publish/publish-your-app/overview?pivots=store-installer-msix), starting with step 1: [Reserve your app's name in the Microsoft Store](https://learn.microsoft.com/windows/apps/publish/publish-your-app/reserve-your-apps-name?pivots=store-installer-msix).

Note - publishing your app is not as simple as just uploading the installer. You need to provide us with information about your app, about you (or your company), about your privacy and support policies, etc. 

The documentation I've linked to covers all of the required and optional information - it should be everything you need.

Thanks,
Shawn

**Comment by LenYates** [comment]
Hi Shawn,

I appreciate your input.  I want to mention that I have already provided
complete information about our app and our company.  This is our status:

[image: image.png]

So, you can see that we are not at the beginning.  We are far down the
road.  The problem is that we cannot seem to be able to complete the
"Packages" area.  Here is the status:

[image: image.png]


I do not understand what is lacking or what needs to be done.  Can you
provide some advice?  I want the one msix file to be provided for both
Desktop and Mobile.

Len
