### ISSUE TITLE
TabNavigation="Local" does not work like Gridview

### ISSUE THREAD

**Issue by dyyMsft** [MicrosoftDocs/windows-uwp#433]
Is the style template available? It might just be missing the TemplateBinding

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 745ab6c5-cfbe-a56f-dccd-ab55123f9223
* Version Independent ID: 54455a9f-a92f-e462-558d-78fb696dba8c
* Content: [Navigation view - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/design/controls-and-patterns/navigationview)
* Content Source: [windows-apps-src/design/controls-and-patterns/navigationview.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/design/controls-and-patterns/navigationview.md)
* Service: **unspecified**
* GitHub Login: @serenaz
* Microsoft Alias: **sezhen**

**Comment by serenaz** [comment]
Could you please clarify what you mean by style template? NavigationView does not behave like Gridview.

**Comment by dyyMsft** [comment]
Here’s an example of a style template for a TargetType=Button

https://msdn.microsoft.com/en-us/library/windows/apps/mt299109.aspx

At the current time, we don’t need the style template, but I am hoping the TabNavigation=”Local” issue can be fixed. This properties controls the tab behavior for controls like the GridView and the NavigationView also has this property.

**Comment by serenaz** [comment]
Ok! Can you explain what kind of TabNavigation behavior you'd like to see in the NavigationView? TabNavigation seems to work fine in NavigationView for me.

**Comment by dyyMsft** [comment]
Sure thing Serenaz, 

When you set TabNavigation="Local" to the NavigationView control, the behavior while using the app via keyboard is you should be be able to tab cycle through the menu items without having to use the keyboard arrow keys. I haven't verified it in a while, but last time I tried, it didn't work.

**Comment by serenaz** [comment]
Gotcha - thanks for clarifying! We've filed the bug and hope to fix it in the next Windows 10 release.

**Comment by YuliKl** [comment]
The current tabbing behavior is a deliberate choice intended to be consistent with other aspects of the platform. Our expected mental model for users is that Tab key moves them between larger chunks of UI while arrow keys are for more local navigation (usually within a control). So default ListView and NavigationView behavior is deliberate: we want users to tab to the list and arrow within the list. By eliminating unnecessary tab stops we allow keyboard users to navigate through an app more rapidly.

In addition, there's a problem with current ListView TabNavigation="Local" behavior. This works as intended when no items in ListView are selected. However, if a user clicks on a list item or arrows through the list (because by default selection follows focus), the Tab key, by design, puts focus on the selected list item. When this happens, the user can no longer Tab to the list items prior to the selected item and must use arrow keys to reach these.

With both of these considerations in mind, we will not be adding this TabNavigation behavior to NavigationView.
