### ISSUE TITLE
Not accurately for fingerprint

### ISSUE THREAD

**Issue by zhangl1201** [MicrosoftDocs/windows-uwp#434]
Windows.Security.Credentials.UI.UserConsentVerifier.CheckAvailabilityAsync(), I have checked the doc for this api, and it is said that this api is to check the availability of user consent verifier, including fingerprint, windows password PIN, windows hello and etc. If any one of these are available, this api will return Available, it not for fingerprint only and it can't tell the status of fingerprint. I have tested in a machine that set the PIN but no fingerprint it return available. 
https://docs.microsoft.com/en-us/uwp/api/windows.security.credentials.ui.userconsentverifier.checkavailabilityasync#Windows_Security_Credentials_UI_UserConsentVerifier_CheckAvailabilityAsync

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: feadf273-2dac-2af0-1fa6-c2bad76a9c23
* Version Independent ID: 2fec4ec8-7290-df7e-5514-82b0ca729915
* Content: [Fingerprint biometrics - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/security/fingerprint-biometrics)
* Content Source: [windows-apps-src/security/fingerprint-biometrics.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/security/fingerprint-biometrics.md)
* Service: **unspecified**
* GitHub Login: @msatranjr
* Microsoft Alias: **misatran**

**Comment by hickeys** [comment]
It looks like your feedback concerns the product itself, rather than the documentation for the product. Unfortunately, GitHub issues in this repo are only used for documentation issues. 

The best way to leave product feedback is through the [Feedback Hub app](https://support.microsoft.com/help/4021566/windows-10-send-feedback-to-microsoft-with-feedback-hub-app). If you return to the documentation page related to this issue and scroll to the bottom, there is a button to **leave feedback about this product**

For completeness' sake, here is a list of developer resources:

- The [Feedback Hub app](https://support.microsoft.com/help/4021566/windows-10-send-feedback-to-microsoft-with-feedback-hub-app) is the right place to suggest or lobby for a change or feature.
- Try our [forums](https://social.msdn.microsoft.com/Forums/newthread?category=windowsapps&forum=wpdevelop&prof=required) and [StackOverflow](https://stackoverflow.com/questions) for community assistance with development questions.
- The [Windows developer support](https://developer.microsoft.com/windows/support) site explains other support options.
- The [Visual Studio developer community](https://developercommunity.visualstudio.com) is helpful and responsive. You can also suggest or lobby for a change or feature by clicking the **report a problem** or **suggest a feature** buttons.
- For developer issues or suspected product bugs, visit [Microsoft Support](https://support.microsoft.com/contactus). A support engineer will determine whether the issue is a Microsoft product bug. If it is, the ticket will be free of charge.

If you receive assistance via any support resource and you believe that information would help us improve the docs, then please let us know or consider submitting a pull request.

Thanks,
Shawn
