### ISSUE TITLE
lost dependency does not excist

### ISSUE THREAD

**Issue by Zwarthoed** [MicrosoftDocs/windows-uwp#4340]
No information on how to solve:

The declared package dependency does not exist. Dependency: Microsoft.NET.Native.Framework.Debug.2.2. Minimum version: 2.2.29512.0. Please upload the .msixupload or .appxupload file generated by Visual Studio for the Store. [Learn more](http://go.microsoft.com/fwlink/?LinkId=620193)

totaly iost here!

[Voer hier feedback in]

---
#### Documentdetails

⚠ *Dit gedeelte niet bewerken. Het is vereist voor de koppeling learn.microsoft.com ➟ GitHub-probleem.*

* ID: 1da800f3-fb5b-3774-b32f-5da9a24a2ff1
* Version Independent ID: 1da800f3-fb5b-3774-b32f-5da9a24a2ff1
* Content: [Upload app packages - Windows apps](https://learn.microsoft.com/nl-nl/windows/apps/publish/publish-your-app/upload-app-packages?pivots=store-installer-msix)
* Content Source: [hub/apps/publish/publish-your-app/upload-app-packages.md](https://github.com/MicrosoftDocs/windows-dev-docs/blob/docs/hub/apps/publish/publish-your-app/upload-app-packages.md)
* Product: **reunion**
* Technology: **apps**
* GitHub Login: @hickeys
* Microsoft Alias: **hickeys**

**Comment by GrantMeStrength** [comment]
We are changing the way we track issues filed from our documentation pages: please see this [blog post](https://techcommunity.microsoft.com/t5/microsoft-learn-blog/announcing-a-new-way-to-give-feedback-on-microsoft-learn/ba-p/4027635) for more details. The Microsoft Store documentation has been updated several times since your issue was reported, and there's a good chance your problem has been addressed. Right now, this issue is being closed but if you feel it is still valid and has not been addressed, please re-open it with any more available information. Please note that if you question is more general and not related to documentation, [Microsoft Q&A](https://learn.microsoft.com/en-us/answers/questions/) is a great way to get questions answered.
