### ISSUE TITLE
Need to add WindowsAppSDK to the projection project.

### ISSUE THREAD

**Issue by vmx17** [MicrosoftDocs/windows-uwp#4343]
I think, at the time moment, we need to add `WindowsAppSDK` to the projection project otherwise, it fails with output;
`EXEC : error : 'Type 'Microsoft.UI.Xaml.Controls.ContentControl' could not be found' when processing brabrabra...` Please mention WAS there. This took me a whole day before finding [this article](https://github.com/microsoft/CsWinRT/issues/1264).
This part, for me, seems still fragile. I know you have been maintaining this page for long time but still, I don't think I can rewrite without looking it.
Making WRC into NuGet package, I feel it reduce efficiency for debug and test. Is it possible to use WRC without making NuGet?
Or, in very short, how can I pass `Microsoft.UI.XAML.Controls.SwapChainPanel` in `*.idl`?
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 16cfa258-50bc-5d50-c3f3-76b2f81e0b8a
* Version Independent ID: 16cfa258-50bc-5d50-c3f3-76b2f81e0b8a
* Content: [Generate a C# projection from a C++/WinRT component, distribute as a NuGet for .NET apps - Windows apps](https://learn.microsoft.com/en-us/windows/apps/develop/platform/csharp-winrt/net-projection-from-cppwinrt-component)
* Content Source: [hub/apps/develop/platform/csharp-winrt/net-projection-from-cppwinrt-component.md](https://github.com/MicrosoftDocs/windows-dev-docs/blob/docs/hub/apps/develop/platform/csharp-winrt/net-projection-from-cppwinrt-component.md)
* Product: **reunion**
* Technology: **apps**
* GitHub Login: @stevewhims
* Microsoft Alias: **stwhi**

**Comment by stevewhims** [comment]
Thanks, @vmx17. This sounds like not an issue with this topic as currently written (since the tutorial doesn't mention using WinUI 3 types), but a request for additional info. I'll investigate the answer and get back to you.

Thanks!
-Steve

**Comment by stevewhims** [comment]
I've updated the topic (see the last section in there) with more info to address your questions about needing to reference the Windows App SDK NuGet in the projection project (you do if the WRC you're wrapping uses Windows App SDK types), and about whether distributing the projection via NuGet is necessary currently (it is).

We didn't understand the question "Or, in very short, how can I pass Microsoft.UI.XAML.Controls.SwapChainPanel in *.idl?", nor how that relates to the other questions. Since that's more of a product/support question, you might want to use this resource:

- [Microsoft Q&A](https://docs.microsoft.com/answers/topics/windows-uwp.html) is the right place to lobby for a change or a new feature, to make a suggestion, or to ask a product question.

Thanks!
-Steve

**Comment by vmx17** [comment]
Thanks for update. Though there seem some referencing projection projects (like example [here](https://github.com/RobsonPontin/WinUI3/blob/de75a56f4428a0fb7f794c13cb1566f2ba239939/WinUI3_GenCsProjection/WinRtComponentProjection/WinRtComponentProjection.csproj#L18)) seems to exist, I recognize as officially there is requirement to use WRC via NuGet package.
As for "in very short ...", yes, there are missing explanation. The motivation is to use interop C# and C++, just in my personal thought, the most probable use case is for DirectX. I also read your article "Interop DirectX and XAML". Still I'm looking for the way to use "Interop DirectX (in C++) and XAML (in C#) with Windows App SDK's _SwapChainPanel_".  So, in very short, how to pass the _SwapChainPanel_ in MIDL to backend _SetSwapChain_ in C++ (WRC) is shortsighted purpose. Though I think you're the last person who can write such articles but yes, as you guided, I'll ask Microsoft Q&A first. Thank you anyway.
