### ISSUE TITLE
Odd Error and Non-existent Reference Page

### ISSUE THREAD

**Issue by markolbert** [MicrosoftDocs/windows-uwp#4366]
I'm running into a problem trying to use x:Bind in a ControlTemplate (with a TargetType defined) per the documentation:

```
 Value="{x:Bind MapScale, Mode=TwoWay}"
```

MapScale is a property defined on the target type.

The error message is:

Severity	Code	Description	Project	File	Line	Suppression State
Error	WMC1119	This Xaml file must have a code-behind class to use {x:Bind}. See http://go.microsoft.com/fwlink/?LinkID=532920&clcid=0x409 for more information	J4JMapWinLibrary	C:\Programming\J4JMapControl2\J4JMapWinLibrary\Themes\Generic.xaml	64	

The link in the error message does not resolve to a useful page. Instead, it takes you to:

https://developer.microsoft.com/en-us/windows/

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 51f84e98-7384-1ccf-1e3c-f0ccd090aabc
* Version Independent ID: 57c8db16-c30e-8607-d009-fd65bf82b0c7
* Content: [TemplateBinding markup extension - UWP applications](https://learn.microsoft.com/en-us/windows/uwp/xaml-platform/templatebinding-markup-extension)
* Content Source: [uwp/xaml-platform/templatebinding-markup-extension.md](https://github.com/MicrosoftDocs/windows-dev-docs/blob/docs/uwp/xaml-platform/templatebinding-markup-extension.md)
* Product: **uwp**
* Technology: **platform**
* GitHub Login: @jwmsft
* Microsoft Alias: **jimwalk**

**Comment by jwmsft** [comment]
The error indicates that you're using x:Bind in a XAML file that doesn't have an associated code-behind file. See this issue in the XAML repo for more information: https://github.com/microsoft/microsoft-ui-xaml/issues/6411, in particular:
"_To use x:Bind, the .xaml file must have a backing x:Class in code-behind. ... A common scenario is defining a ResourceDictionary in its own .xaml file, and being unable to use x:Bind because it doesn't have a backing x:Class. The workaround is to add a backing x:Class to the file, but it adds overhead to the development experience._"

I'll be updating the documentation with this additional information, and I'll let the team that owns the error message know about the problem with the link.

(Sorry for the delayed response. These issues are mainly for feedback about the documentation, and we're not always able to respond quickly to questions. For questions or assistance, we recommend you visit [Microsoft Q&A](https://docs.microsoft.com/answers/index.html) to post your question.)
