### ISSUE TITLE
Capture a photo to a SoftwareBitmap - is the await lowLagCapture.FinishAsync() necessary?

### ISSUE THREAD

**Issue by robunoki-microsoft** [MicrosoftDocs/windows-uwp#4387]
In the Capture a photo to a SoftwareBitmap section, is the `await lowLagCapture.FinishAsync();` necessary?  If so, why is it after the bitmap retrieved?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: fc1d9bcc-262c-d083-fec6-c49b6bc5acd5
* Version Independent ID: deb61f0f-885e-8fc2-48b8-8908c28ffc56
* Content: [Basic photo, video, and audio capture with MediaCapture - UWP applications](https://learn.microsoft.com/en-us/windows/uwp/audio-video-camera/basic-photo-video-and-audio-capture-with-mediacapture)
* Content Source: [uwp/audio-video-camera/basic-photo-video-and-audio-capture-with-MediaCapture.md](https://github.com/MicrosoftDocs/windows-dev-docs/blob/docs/uwp/audio-video-camera/basic-photo-video-and-audio-capture-with-MediaCapture.md)
* Product: **uwp**
* Technology: **audio-video-and-camera**
* GitHub Login: @drewbatgit
* Microsoft Alias: **drewbat**

**Comment by drewbatgit** [comment]
It has been a while since I have worked on that code, but yes, the call to FinishAsync is necessary. In the software bitmap example, PrepareLowLagPhotoCaptureAsync configures the capture device for capturing with a small amount of lag. FinishAsync shuts down the low-lag configuration and disposes of the associated resources. You can call CaptureAsync multiple times, and retrieve the bitmap each time, between calls to PrepareLowLagPhotoCaptureAsync and FinishAsync. After calling FinishAsync, you will need to call PrepareLowLagPhotoCaptureAsync before you can call CaptureAsync again. I.e. FinishAsync does not "finish" the CaptureAsync operation, it finishes the PrepareLowLagPhotoCaptureAsync operation,
