### ISSUE TITLE
Provide more details about the neutral architecture option in the documentation

### ISSUE THREAD

**Issue by yaronelh** [MicrosoftDocs/windows-uwp#4392]
There is an option in architecture type " you should write something like", but the documentation does not explain exactly what it means

you should write something like
Architecture
- x86
- x64
- neutral*
- arm
- arm64

* Note: When selecting neutral the installer is responsible to determine the correct architecture.

**of course if that's the case, Since the sentences in the documentation does not expand on what exactly is neutral know what it actually refers to.**

#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 1da800f3-fb5b-3774-b32f-5da9a24a2ff1
* Version Independent ID: 1da800f3-fb5b-3774-b32f-5da9a24a2ff1
* Content: [Upload app packages - Windows apps](https://learn.microsoft.com/en-us/windows/apps/publish/publish-your-app/upload-app-packages?pivots=store-installer-msi-exe)
* Content Source: [hub/apps/publish/publish-your-app/upload-app-packages.md](https://github.com/MicrosoftDocs/windows-dev-docs/blob/docs/hub/apps/publish/publish-your-app/upload-app-packages.md)
* Product: **reunion**
* Technology: **apps**
* GitHub Login: @hickeys
* Microsoft Alias: **hickeys**

**Comment by GrantMeStrength** [comment]
We are changing the way we track issues filed from our documentation pages: please see this [blog post](https://techcommunity.microsoft.com/t5/microsoft-learn-blog/announcing-a-new-way-to-give-feedback-on-microsoft-learn/ba-p/4027635) for more details. The Microsoft Store documentation has been updated several times since your issue was reported, and there's a good chance your problem has been addressed. Right now, this issue is being closed but if you feel it is still valid and has not been addressed, please re-open it with any more available information. Please note that if you question is more general and not related to documentation, [Microsoft Q&A](https://learn.microsoft.com/en-us/answers/questions/) is a great way to get questions answered.
