### ISSUE TITLE
Wrong currency for Croatian developer account

### ISSUE THREAD

**Issue by danijelt** [MicrosoftDocs/windows-uwp#4395]
Croatia switched to euro on 1/1/2023. The docs still list HRK. The registration page also tries to bill me in HRK so the payment fails and it's impossible to buy developer account in Croatia. 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: fc18f020-f66b-61fe-e482-7d67b4e24b52
* Version Independent ID: fc18f020-f66b-61fe-e482-7d67b4e24b52
* Content: [Account types, locations, and fees - Windows apps](https://learn.microsoft.com/en-gb/windows/apps/publish/partner-center/account-types-locations-and-fees)
* Content Source: [hub/apps/publish/partner-center/account-types-locations-and-fees.md](https://github.com/MicrosoftDocs/windows-dev-docs/blob/docs/hub/apps/publish/partner-center/account-types-locations-and-fees.md)
* Product: **reunion**
* Technology: **apps**
* GitHub Login: @hickeys
* Microsoft Alias: **hickeys**

**Comment by GrantMeStrength** [comment]
We are changing the way we track issues filed from our documentation pages: please see this [blog post](https://techcommunity.microsoft.com/t5/microsoft-learn-blog/announcing-a-new-way-to-give-feedback-on-microsoft-learn/ba-p/4027635) for more details. The Microsoft Store documentation has been updated several times since your issue was reported, and there's a good chance your problem has been addressed. Right now, this issue is being closed but if you feel it is still valid and has not been addressed, please re-open it with any more available information. Please note that if you question is more general and not related to documentation, [Microsoft Q&A](https://learn.microsoft.com/en-us/answers/questions/) is a great way to get questions answered.
