### ISSUE TITLE
why return 401 and request with right access_token

### ISSUE THREAD

**Issue by lsc153** [MicrosoftDocs/windows-uwp#4407]
[Enter feedback here]

"Identity cannot be authorized. CorrelationId: 912a71f4-22f1-426a-889c-f9905d0a3f50\"}","url":"https://manage.devcenter.microsoft.com/v1.0/my/inappproducts"
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b8e664b8-cb37-de30-9609-19fae6628a4f
* Version Independent ID: 2b040c07-9886-dbc3-dac1-08e8c1e0335d
* Content: [Python sample - app submission with game options and trailers - Microsoft Store](https://learn.microsoft.com/en-us/windows/uwp/monetize/python-code-examples-for-submissions-game-options-and-trailers)
* Content Source: [uwp/monetize/python-code-examples-for-submissions-game-options-and-trailers.md](https://github.com/MicrosoftDocs/windows-dev-docs/blob/docs/uwp/monetize/python-code-examples-for-submissions-game-options-and-trailers.md)
* Product: **uwp**
* Technology: **publish**
* GitHub Login: @hickeys
* Microsoft Alias: **hickeys**

**Comment by GrantMeStrength** [comment]
We are changing the way we track issues filed from our documentation pages: please see this [blog post](https://techcommunity.microsoft.com/t5/microsoft-learn-blog/announcing-a-new-way-to-give-feedback-on-microsoft-learn/ba-p/4027635) for more details. The Microsoft Store documentation has been updated several times since your issue was reported, and there's a good chance your problem has been addressed. Right now, this issue is being closed but if you feel it is still valid and has not been addressed, please re-open it with any more available information. Please note that if you question is more general and not related to documentation, [Microsoft Q&A](https://learn.microsoft.com/en-us/answers/questions/) is a great way to get questions answered.
