### ISSUE TITLE
Mailwasher Pro Version 5

### ISSUE THREAD

**Issue by BobBxB** [MicrosoftDocs/windows-uwp#4414]
I know the program is very old but it is what I have used for many, many years. 
No matter how many times I bring it to the front of my screen and press "win + ctrl + T" the program now starts minimized.
A year ago it always opened on top, but on a windows update it stopped doing that and started minimised.
I am disappointed that the one and only program I look to start always on top does not work.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 9724cfd6-ee22-bb48-56fe-9797bf29eed6
* Version Independent ID: 9724cfd6-ee22-bb48-56fe-9797bf29eed6
* Content: [PowerToys Always on Top utility for Windows](https://learn.microsoft.com/en-us/windows/powertoys/always-on-top)
* Content Source: [hub/powertoys/always-on-top.md](https://github.com/MicrosoftDocs/windows-dev-docs/blob/docs/hub/powertoys/always-on-top.md)
* Product: **dev-environment**
* Technology: **powertoys**
* GitHub Login: @mattwojo
* Microsoft Alias: **mattwoj**

**Comment by mattwojo** [comment]
Hey @BobBxB - Did you try using the Always on Top PowerToys utility for this? I think this was the intention it's designed for. I need to close this issue because it doesn't involve any update to the PowerToys documentation, but you might try seeing if others had similar issues in the PowerToys product repo -- here's a link to the issues related to the Always on Top utility: https://github.com/microsoft/PowerToys/issues?q=is%3Aissue+always+on+top
