### ISSUE TITLE
Exception on GetAppAndOptionalStorePackageUpdatesAsync call

### ISSUE THREAD

**Issue by sharathppss** [MicrosoftDocs/windows-uwp#442]
How do you guys go about testing the Update flows for the App. The best I can think of is to have a dummy app and publish an update to store and try to invoke the update code paths. 
Currently when I am trying this mechanism I am getting the below exception for the API call GetAppAndOptionalStorePackageUpdatesAsync.

{System.Exception: The service cannot be started, either because it is disabled or because it has no enabled devices associated with it. (Exception from HRESULT: 0x80070422)
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult())}

Also the test app in consideration is showing as publishing(for more than a day) but the support team informed me that the update as been successful and its just not updated on the developer portal.
I did try the GetAppAndOptionalStorePackageUpdatesAsync call with same code for another App ID without updates and the call was successful.(Although without app updates as expected).

Can someone please help out if they are aware of any information regarding this.

**Comment by sharathppss** [comment]
Happens only on Insider preview build 17063. Got it working successfully on Windows 10 pro 16299 build. Do you have better suggestions to test it though?

**Comment by mcleanbyron** [comment]
Sorry for the response delay. To test the package updates API, the recommended approach is to submit your updated package to the Dev Center dashboard as a [package flight](https://docs.microsoft.com/en-us/windows/uwp/publish/package-flights) that is only available to you (or your testers) while you test the update process. If you're continuing to encounter problems with publishing to the Store, please open a support request at http://aka.ms/storesupport so that someone can investigate further.

**Comment by RehanSaeed** [comment]
I'm also seeing this strange behaviour. In addition, I also see the current app version appear as an update (See https://github.com/MicrosoftDocs/windows-uwp/issues/1726).
