### ISSUE TITLE
Clarify terms of name reservation 

### ISSUE THREAD

**Issue by Zulu-Inuoe** [MicrosoftDocs/windows-uwp#4466]
Hi, in reading this page 'Reserve your app's name', it is unclear to me when my application name is "safe" from the 3 month expiry period. Specifically - if I am in the middle of development and have made **private audience** and **have disabled discoverability** on my Work In Progress submissions, will my name reservation expire?

Asked differently - Do I need to make a **public audience** submission in order to keep my reserved name past 3 months?

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: c2e595ca-9d04-63e4-5967-13e6b822ddb7
* Version Independent ID: c2e595ca-9d04-63e4-5967-13e6b822ddb7
* Content: [Reserve your app's name - Windows apps](https://learn.microsoft.com/en-us/windows/apps/publish/publish-your-app/reserve-your-apps-name?pivots=store-installer-msix)
* Content Source: [hub/apps/publish/publish-your-app/reserve-your-apps-name.md](https://github.com/MicrosoftDocs/windows-dev-docs/blob/docs/hub/apps/publish/publish-your-app/reserve-your-apps-name.md)
* Product: **reunion**
* Technology: **apps**
* GitHub Login: @hickeys
* Microsoft Alias: **hickeys**

**Comment by GrantMeStrength** [comment]
We are changing the way we track issues filed from our documentation pages: please see this [blog post](https://techcommunity.microsoft.com/t5/microsoft-learn-blog/announcing-a-new-way-to-give-feedback-on-microsoft-learn/ba-p/4027635) for more details. The Microsoft Store documentation has been updated several times since your issue was reported, and there's a good chance your problem has been addressed. Right now, this issue is being closed but if you feel it is still valid and has not been addressed, please re-open it with any more available information. Please note that if you question is more general and not related to documentation, [Microsoft Q&A](https://learn.microsoft.com/en-us/answers/questions/) is a great way to get questions answered.
