### ISSUE TITLE
Handle API response errors

### ISSUE THREAD

**Issue by Shivam7-1** [MicrosoftDocs/windows-uwp#4467]
The API calls `get_application `and `create_submission `can return a tuple with a boolean and the response data. You can check the boolean value to determine if the API call was successful and then proceed accordingly.
code link:https://github.com/MicrosoftDocs/windows-dev-docs/blob/c2d851608549905e4b36803ca5180acc4e760e62/uwp/monetize/code/StoreServicesExamples_SubmissionAdvancedListings/python/CreateAndSubmitAppSubmissionExample.py

**Comment by GrantMeStrength** [comment]
We are changing the way we track issues filed from our documentation pages: please see this [blog post](https://techcommunity.microsoft.com/t5/microsoft-learn-blog/announcing-a-new-way-to-give-feedback-on-microsoft-learn/ba-p/4027635) for more details. The Microsoft Store documentation has been updated several times since your issue was reported, and there's a good chance your problem has been addressed. Right now, this issue is being closed but if you feel it is still valid and has not been addressed, please re-open it with any more available information. Please note that if you question is more general and not related to documentation, [Microsoft Q&A](https://learn.microsoft.com/en-us/answers/questions/) is a great way to get questions answered.
