### ISSUE TITLE
Implement state management

### ISSUE THREAD

**Issue by Shivam7-1** [MicrosoftDocs/windows-uwp#4469]
The `OnLaunched `method includes a comment to load the state from a previously suspended application. The implement state management logic to save and restore the application state during suspend and resume events.
code repo link:  https://github.com/MicrosoftDocs/windows-dev-docs/edit/docs/uwp/monetize/code/PaymentsApiSample/PaymentsApiSample/App.xaml.cs

**Comment by GrantMeStrength** [comment]
We are changing the way we track issues filed from our documentation pages: please see this [blog post](https://techcommunity.microsoft.com/t5/microsoft-learn-blog/announcing-a-new-way-to-give-feedback-on-microsoft-learn/ba-p/4027635) for more details. The Microsoft Store documentation has been updated several times since your issue was reported, and there's a good chance your problem has been addressed. Right now, this issue is being closed but if you feel it is still valid and has not been addressed, please re-open it with any more available information. Please note that if you question is more general and not related to documentation, [Microsoft Q&A](https://learn.microsoft.com/en-us/answers/questions/) is a great way to get questions answered.
