### ISSUE TITLE
Enabling the preview handlers will override other preview handlers already installed - there have been reports of incompatibility between Outlook and the PDF Preview Handler.

### ISSUE THREAD

**Issue by manthanvishana** [MicrosoftDocs/windows-uwp#4500]
i have no outlook but show bellow error

Enabling the preview handlers will override other preview handlers already installed - there have been reports of incompatibility between Outlook and the PDF Preview Handler.

so please be needful for this.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: a388e163-12c0-f8f9-c560-29e72ad78f40
* Version Independent ID: 3ad933cb-9112-c3a2-f257-754c5613c5c2
* Content: [PowerToys File Explorer add-ons utility for Windows](https://learn.microsoft.com/en-us/windows/powertoys/file-explorer)
* Content Source: [hub/powertoys/file-explorer.md](https://github.com/MicrosoftDocs/windows-dev-docs/blob/docs/hub/powertoys/file-explorer.md)
* Product: **dev-environment**
* Technology: **powertoys**
* GitHub Login: @mattwojo
* Micro
![Screenshot 2023-06-20 132855](https://github.com/MicrosoftDocs/windows-dev-docs/assets/137151180/3b7d9100-be00-45a3-9631-bc706807e905)
soft Alias: **mattwoj**

**Comment by Jay-o-Way** [comment]
@manthanvishana this is a general warning. What exactly do you expect?

**Comment by alvinashcraft** [comment]
Hi @manthanvishana. Do you have a suggestion to improve the documentation around this feature? Were you intending to leave feedback for the product instead? You can do that on the [PowerToys repo](https://github.com/microsoft/PowerToys/issues).

**Comment by alvinashcraft** [comment]
Thanks for taking the time to let us know about this and we sincerely apologize for the delayed response. Due to the sheer volume of feedback in our repo, we are currently prioritizing new Issues. If you believe your feedback is still actionable, let us know either directly in this thread or by filing a new Issue and we’ll work to incorporate the suggestions into the documentation. Though the Issue will be marked as Closed, we will monitor any replies that come afterwards so feel free to treat this like an open Issue. Many thanks!
