### ISSUE TITLE
Where are search terms specified?

### ISSUE THREAD

**Issue by sterneric** [MicrosoftDocs/windows-uwp#4511]
Great definition of search terms but I can't find where I add them in my VS project or my app store submission. Maybe it's just me but it would sure be nice to have a link or a screen shot showing where the search terms go. thanks 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 192a2d51-1199-f800-9355-f60248bd57b0
* Version Independent ID: 192a2d51-1199-f800-9355-f60248bd57b0
* Content: [Add additional information - Windows apps](https://learn.microsoft.com/en-us/windows/apps/publish/publish-your-app/add-additional-information)
* Content Source: [hub/apps/publish/publish-your-app/add-additional-information.md](https://github.com/MicrosoftDocs/windows-dev-docs/blob/docs/hub/apps/publish/publish-your-app/add-additional-information.md)
* Product: **reunion**
* Technology: **apps**
* GitHub Login: @hickeys
* Microsoft Alias: **hickeys**

**Comment by GrantMeStrength** [comment]
Reaching out to Store team.

**Comment by GrantMeStrength** [comment]
We are changing the way we track issues filed from our documentation pages: please see this [blog post](https://techcommunity.microsoft.com/t5/microsoft-learn-blog/announcing-a-new-way-to-give-feedback-on-microsoft-learn/ba-p/4027635) for more details. The Microsoft Store documentation has been updated several times since your issue was reported, and there's a good chance your problem has been addressed. Right now, this issue is being closed but if you feel it is still valid and has not been addressed, please re-open it with any more available information. Please note that if you question is more general and not related to documentation, [Microsoft Q&A](https://learn.microsoft.com/en-us/answers/questions/) is a great way to get questions answered.
