### ISSUE TITLE
ms command-settings to access the display > graphics > standard graphics settings

### ISSUE THREAD

**Issue by vlad11z** [MicrosoftDocs/windows-uwp#4557]
Hello everyone, I need a command for quick access 
(ms-settings) to access the display > graphics > standard settings graphics
![Screenshot 2023-08-02 234806](https://github.com/MicrosoftDocs/windows-dev-docs/assets/56939824/f7e436cf-4082-49b3-b50d-727e0683c79c)

**Comment by alvinashcraft** [comment]
Hi @vlad11z. Which version of Windows are you using. I do not see a "Display | Graphics | Standard Graphics" page on the latest builds of Windows 11, although the available pages can vary depending on device hardware. The ms-settings URIs support most standard configurations. There are a couple of graphics shortcuts available:

* `ms-settings:display-advancedgraphics` --> This one launches "System | Display | Graphics"
* `ms-settings:display-advancedgraphics-default` --> This URI launches "System | Display | Default graphics settings"
* `ms-settings:display-advanced` --> On some supported hardware, this will launch the "System | Display | Advanced display settings" page, otherwise it defaults to "System | Display"
* `ms-settings:display` --> This URI opens "System | Display" on all devices

There is no `ms-settings` shortcut available to launch a page named **Standard graphics settings**.

If you would like to suggest a new URI, you can submit product feedback through the Feedback Hub app in Windows.

There is also the community of experts and Microsoft Engineers over at [Microsoft Q&A](https://docs.microsoft.com/answers/topics/windows-uwp.html), who offer timely answers to a multitude of technical questions surrounding windows-dev-docs.

If you do create a thread over at Microsoft Q&A, we would appreciate if you could share that link here so we can track the progress and incorporate any technical details into our documentation. Though I'm marking this Issue as closed now, please treat this thread as an open thread for follow-ups. Thanks!
