### ISSUE TITLE
Why do you not tell if it works with Visual Studio (not VS Code!)?

### ISSUE THREAD

**Issue by NoteToSelfFindGoodNickname** [MicrosoftDocs/windows-uwp#4564]
Thanks for keeping this secret from us.
Why bother telling?

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 200916ea-06cb-d017-a9e8-18d2216c5bac
* Version Independent ID: f872813c-0ab2-0f5a-45e0-e81e8479470b
* Content: [Set up your dev environment on Windows for Rust](https://learn.microsoft.com/en-us/windows/dev-environment/rust/setup)
* Content Source: [hub/dev-environment/rust/setup.md](https://github.com/MicrosoftDocs/windows-dev-docs/blob/docs/hub/dev-environment/rust/setup.md)
* Product: **dev-environment**
* Technology: **windows-rust**
* GitHub Login: @stevewhims
* Microsoft Alias: **stwhi**

**Comment by stevewhims** [comment]
We haven't yet tried out these steps with Visual Studio. So far, we focused on Visual Studio Code. And since the Rust dev experience there is good, we wanted to documented that you *can* do this with VS Code. There's no intended implication about what can and can't be done with other IDEs.

However, if I get chance, I'll try this out with Visual Studio.

Thanks!
-Steve
