### ISSUE TITLE
Single-project MSIX project compiles fine as a desktop non-packaged app even when Properties folder is missing

### ISSUE THREAD

**Issue by chitturs** [MicrosoftDocs/windows-uwp#4565]
I had the Properties folder missing since it was added to .gitignore. That was my bug. However, it was _very difficult_ to debug it since the symptom was that when I synced the project from a different machine, it compiled fine but it did not run and failed to load Microsoft.UI.XAML.Dll.

Why is this project compiling when the Properties folder is missing? Sounds like a bug.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 0401c948-1dda-c819-ee88-902ac6fcbbd9
* Version Independent ID: c1748244-0f46-8dec-a88e-020f12d9a387
* Content: [Package your app using single-project MSIX - Windows apps](https://learn.microsoft.com/en-us/windows/apps/windows-app-sdk/single-project-msix?tabs=csharp)
* Content Source: [hub/apps/windows-app-sdk/single-project-msix.md](https://github.com/MicrosoftDocs/windows-dev-docs/blob/docs/hub/apps/windows-app-sdk/single-project-msix.md)
* Product: **reunion**
* Technology: **get-started**
* GitHub Login: @Karl-Bridge-Microsoft
* Microsoft Alias: **kbridge**

**Comment by stevewhims** [comment]
Hi, @chitturs, and thanks for filing this issue. As you say, this is more likely to be a bug (or something that could be sorted out by talking directly to the product team) than a problem with the actual docs themselves. I wouldn't know what to say in the docs to resolve this circumstance, and we shouldn't document bugs in the docs.

For questions (or requests for help) regarding a specific scenario, like this, one option is to click **Submit and view feedback for** \> **This product**, and you'll be taken to [Microsoft Q&A](https://docs.microsoft.com/answers/topics/uwp.html?sort=active&filter=all) (more info about that below).

Here are all of the developer support resources, for completeness.
- [Microsoft Q&A](https://docs.microsoft.com/answers/topics/windows-uwp.html) is the right place to lobby for a change or a new feature, to make a suggestion, or to ask a product question.
- For community assistance with development questions, there are our [forums](https://social.msdn.microsoft.com/Forums/newthread?category=windowsapps&forum=wpdevelop&prof=required), and [StackOverflow](https://stackoverflow.com/questions).
- The [Windows developer support](https://developer.microsoft.com/windows/support) site explains other support options.
- The [Visual Studio developer community](https://developercommunity.visualstudio.com) is available, and responsive. The former User Voice feature is now there on the **Suggest a feature** tab, if you want to lobby for a change, a feature, or to make a suggestion.
- For developer issues, or suspected product bugs, there's [Microsoft Support](https://support.microsoft.com/contactus); a support engineer will look at the repro and see whether the issue is a Microsoft product bug, or something else. If it's a bug with a Microsoft product then the ticket will be free of charge.
