### ISSUE TITLE
Cannot run in WinUI 3, with show it cannot support .Net5 or above

### ISSUE THREAD

**Issue by CityUCSHowardStudentHelper1** [MicrosoftDocs/windows-uwp#4576]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: badad06e-48a0-0a8d-e5e1-d0c8573dbc3e
* Version Independent ID: 313ee3ec-bcc2-cb3a-ac3f-5434f395ab6f
* Content: [Add a UWP InkCanvas control using XAML Islands - Windows apps](https://learn.microsoft.com/en-us/windows/apps/desktop/modernize/modernize-wpf-tutorial-2)
* Content Source: [hub/apps/desktop/modernize/modernize-wpf-tutorial-2.md](https://github.com/MicrosoftDocs/windows-dev-docs/blob/docs/hub/apps/desktop/modernize/modernize-wpf-tutorial-2.md)
* Product: **reunion**
* Technology: **apps**
* GitHub Login: @stevewhims
* Microsoft Alias: **stwhi**

**Comment by stevewhims** [comment]
Hi! Based on the title, I can't make out what the problem is with this topic. But I'll plan to go ahead and test out the topic, and see what I find. Meanwhile, if you could describe what the problem is with the topic, that'd be helpful.

Thank you!
-Steve

**Comment by stevewhims** [comment]
UPDATE: So, looking more deeply at this section, I realized that it's necessary to start at the beginning of the series of topics, and work through until you reach the topic in question. So, on second thought, it didn't seem like an efficient use of time to do all of that without concrete info of what I'm testing/looking for and/or what the issue is.

If you could explain what the problem is with this topic, that'd be great. I'll leave the issue open another week or so.

Meanwhile, if it's of interest, Xaml Islands for the Windows App SDK is now in preview. See [Version 1.4 Preview 2 (1.4.0-preview2)](https://learn.microsoft.com/windows/apps/windows-app-sdk/preview-channel#version-14-preview-2-140-preview2).

-Steve

**Comment by CityUCSHowardStudentHelper1** [comment]
I have just tried to update the SDK to preview. Now seems ok. Thanks for the help.
