### ISSUE TITLE
Clarity of purpose for Crop and Lock

### ISSUE THREAD

**Issue by davidberman** [MicrosoftDocs/windows-uwp#4600]
I'm eagerly checking out this new Power Toy. 
However, I'm unclear on what its purpose is.
Could someone who understands it improve the documentation to introduce it with an example of what problem it seeks to solve and/or an example of how it can improve one's life? Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 7fbf8c62-357c-fd22-c533-7a9644b6f0bd
* Version Independent ID: 7fbf8c62-357c-fd22-c533-7a9644b6f0bd
* Content: [PowerToys Crop And Lock for Windows](https://learn.microsoft.com/en-ca/windows/powertoys/crop-and-lock)
* Content Source: [hub/powertoys/crop-and-lock.md](https://github.com/MicrosoftDocs/windows-dev-docs/blob/docs/hub/powertoys/crop-and-lock.md)
* Product: **dev-environment**
* Technology: **powertoys**
* GitHub Login: @alvinashcraft
* Microsoft Alias: **aashcraft**

**Comment by alvinashcraft** [comment]
Hi @davidberman. Thanks for submitting your feedback and we apologize for the delayed response. I see that updates have not been made since the creation of this Issue, so I went ahead and created an internal work item to work with the PowerToys team to document some sample use cases on this page. The timeline for this may vary, so I will go ahead and close this and circle back when the changes are live.

Though the Issue will be marked as Closed, we will monitor any replies that come afterwards so treat this like an open Issue. Many thanks!
