### ISSUE TITLE
Windows Phone 10

### ISSUE THREAD

**Issue by Lk9gcAG** [MicrosoftDocs/windows-uwp#466]
As soon as manual integration with System Media Transport Control is implemented, background audio stops working on Windows Phone 10

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4cec2ecd-7c7b-8b22-d592-17ef1776c342
* Version Independent ID: a55428d6-9091-0f58-78b6-bdad27002bc8
* Content: [Play media in the background - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/audio-video-camera/background-audio)
* Content Source: [windows-apps-src/audio-video-camera/background-audio.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/audio-video-camera/background-audio.md)
* Service: **unspecified**
* GitHub Login: @drewbatgit
* Microsoft Alias: **drewbat**

**Comment by weitzhandler** [comment]
I'm using the `MediaPlayer` element to play a sequence of various audio files. After enabling the _Background Media Playback_ capability, the audio will mute once I minimize the app window (on Windows).

**Comment by drewbatgit** [comment]
Thanks for taking the time to let us know about this and we sincerely apologize for the delayed response. Due to the sheer volume of feedback in our repo, we are currently prioritizing new Issues. If you believe your feedback is still actionable, let us know either directly in this thread or by filing a new Issue and we’ll work to incorporate the suggestions into the documentation. Though the Issue will be marked as Closed, I will monitor any replies that come afterwards so feel free to treat this like an open Issue. Many thanks!
