### ISSUE TITLE
How did I delete this space and reattribute the space to my original space C: ?

### ISSUE THREAD

**Issue by Speed60580** [MicrosoftDocs/windows-uwp#4661]
I'm a newby, can you help me please !

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: bfda7965-bc34-ab88-fdc9-efef4a5d8a9e
* Version Independent ID: bfda7965-bc34-ab88-fdc9-efef4a5d8a9e
* Content: [Set up a Dev Drive on Windows 11](https://learn.microsoft.com/en-us/windows/dev-drive/)
* Content Source: [hub/dev-drive/index.md](https://github.com/MicrosoftDocs/windows-dev-docs/blob/docs/hub/dev-drive/index.md)
* Product: **dev-environment**
* Technology: **windows-devhome**
* GitHub Login: @mattwojo
* Microsoft Alias: **mattwoj**

**Comment by mattwojo** [comment]
Hi @Speed60580 - I'm not quite understanding your question. Could you elaborate on what you're having trouble with?

**Comment by mattwojo** [comment]
Without more context, I have to guess at exactly what you're asking here, but if you're referring to deleting a Dev Drive that you've created so that the storage space on your C-drive will be available for you to use again for another reason, see: https://learn.microsoft.com/en-us/windows/dev-drive#how-to-delete-a-dev-drive

Closing this issue, but feel welcome to re-open if this did not address your concern.
