### ISSUE TITLE
[WIP] Dev Drive dissapeared suddenly

### ISSUE THREAD

**Issue by ZeroDotNet** [MicrosoftDocs/windows-uwp#4669]
I just discovered that my only dev drive created is missing. 
Last time used (yesterday) everything was normal, no changes made by me since then. 
Currently, doing my research to see if windows updates or any other update might caused this. 

Since the impact of the issue, I considered to post this issue even  before collecting more details about the scenario. 

_Running Windows 11 Pro
OS Build 22621.2428
Under Windows Insider Release Preview program._

**Comment by mattwojo** [comment]
Hi @ZeroDotNet - Have you resolved this issue yet? Dev Drive has since moved out of Windows Insider to the latest general Windows 11 release (see https://devblogs.microsoft.com/engineering-at-microsoft/dev-drive-is-now-available/).  I'm not currently aware of any bugs involving Dev Drives disappearing that would require an update to the docs, but if your issue has persisted, please re-open this issue and we will try to help.
