### ISSUE TITLE
Lost 70GB storage after canceling dev drive creation

### ISSUE THREAD

**Issue by BimalPandeyCode** [MicrosoftDocs/windows-uwp#4675]
Hey everyone, I created a dev drive in win 11 and cancled midway. Now that storage isn't shown anywhere. It reads 238 GB in settings but in file explorer it says 168GB. Exactly 70GB is lost.
![image](https://github.com/MicrosoftDocs/windows-dev-docs/assets/76998974/bf3fadac-df9b-4b45-aa40-386144eaee13)
![image](https://github.com/MicrosoftDocs/windows-dev-docs/assets/76998974/3a5b9ea5-f969-4e03-a7ea-f9f9d5a0b433)
I don't have dev drive in disks & volumes either:
![image](https://github.com/MicrosoftDocs/windows-dev-docs/assets/76998974/24181021-5714-46d6-8d26-82b34b0dba7a)

**Comment by niirmaaltwaatii** [comment]
@mattwojo @Karl-Bridge-Microsoft 
The same thing happened to me as well. It was taking up too much time, so I canceled it, and now the allocated memory is gone from my disk. Please help me fix this and let me know what I should do to get it back.

**Comment by mattwojo** [comment]
Thank you for filing this issue @BimalPandeyCode and for sharing this isn't isolated @niirmaaltwaatii. 
I'm investigating with one of the devs and they have asked if you could share more details. Specifically for the lost 70 GB, they are thinking that the file system may have shrunk, but not the partition and that `EXTEND FILESYSTEM` from diskpart for the corresponding volume may help recover the space.  Could you share the output for:

- select volume c
- list volume
- list partition

**Comment by mattwojo** [comment]
Hey @BimalPandeyCode -- Turns out that if you create a Dev Drive as a virtual disk, you need to detach the virtual disk that you created and delete it using the Disk Management tool. This will reclaim the lost storage space. Instructions are now on the doc here: https://learn.microsoft.com/en-us/windows/dev-drive/#how-to-delete-a-dev-drive  Apologies for the trouble here and thanks for filing this issue. It helped the dev team realize the issue and how to resolve it.
 
Resolved - doc updated in https://github.com/MicrosoftDocs/windows-dev-docs/commit/fea31041c3896aefc0b7f6ccdcc4cd058d060432.
