### ISSUE TITLE
Can't use Dev Drive again

### ISSUE THREAD

**Issue by hminhdev** [MicrosoftDocs/windows-uwp#4677]
![image](https://github.com/MicrosoftDocs/windows-dev-docs/assets/143872031/069bffce-a6a7-4af6-9580-1c661f968eb2)
Lastly, I created a Dev Drive and stored many datas to develop. And, because some reasons, I need to reinstall to Windows 10. But, when I was in Windows 10, I tried to mount the Dev Drive but it said like the picture (But different from the theme). Then, I upgraded to Windows 11 again, and now, I mount the Dev Drive but still said like this. How to mount it? There are many datas about develop in that and if I can't open it, I can't develop :<<, help meeee

**Comment by mattwojo** [comment]
Hi @hminhdev - I'm sorry that you are experiencing trouble mounting your saved Dev Drive and for my delay in replying. Have you sorted out this issue yet? 
The first thing that comes to mind is to ask whether you may have encountered any of these unsupported scenarios: https://learn.microsoft.com/windows/dev-drive/#what-scenarios-are-unsupported-by-dev-drive-what-are-the-limitations
I am looking into whether there is anything unique to mounting a Dev Drive that should be listed in the docs.

**Comment by mattwojo** [comment]
If this issue hasn't yet been resolved, you might try detaching the VHD hosting your Dev Drive and re-attaching it again. You can find instructions on how to detach under "How to delete a Dev Drive" in the doc: https://learn.microsoft.com/en-us/windows/dev-drive/#how-to-delete-a-dev-drive  ...rather than deleting it, just re-attach it and see if that resolves your issue. Thanks for posting this!
