### ISSUE TITLE
Logo suitability tester

### ISSUE THREAD

**Issue by mysorian** [MicrosoftDocs/windows-uwp#468]
Is it possible to have a logo tester? Provide suitability information for an uploaded logo.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ac89746a-7629-6a95-6c5c-9498a9d7989f
* Version Independent ID: 044558cb-9f69-42df-362c-6c35317c3411
* Content: [Tile and icon assets - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/design/shell/tiles-and-notifications/app-assets)
* Content Source: [windows-apps-src/design/shell/tiles-and-notifications/app-assets.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/design/shell/tiles-and-notifications/app-assets.md)
* Service: **unspecified**
* GitHub Login: @mijacobs
* Microsoft Alias: **mijacobs**

**Comment by toncho11** [comment]
Yes. Good idea.

**Comment by mijacobs** [comment]
It looks like you have product feedback rather than documentation feedback. If you are looking for functionality that isn’t currently provided by the product, please use the [Windows developer feedback site](https://wpdev.uservoice.com/). We’d be happy to have this on record, where others can view it and upvote it.
