### ISSUE TITLE
Wait for AccountsSettingsPane.Show() "results"?

### ISSUE THREAD

**Issue by myokeeh** [MicrosoftDocs/windows-uwp#473]
How can I wait for the results of AccountsSettingsPane.Show()? How can I tell if the user dismissed it by clicking "X"?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2c167684-f810-f987-5383-30fd7856a0c6
* Version Independent ID: d482e60b-b261-0db4-1c51-17db205a67d2
* Content: [Web Account Manager - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/security/web-account-manager)
* Content Source: [windows-apps-src/security/web-account-manager.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/security/web-account-manager.md)
* Service: **unspecified**
* GitHub Login: @PatrickFarley
* Microsoft Alias: **pafarley**

**Comment by dbqt** [comment]
I would also like to know how to tell if the user dismissed the accounts settings pane.

**Comment by hickeys** [comment]
Thanks for reaching out with your feedback. GitHub issues in this repo are for documentation bugs only, and unfortunately this seems more like a support request than a documentation bug. 

The best way to get support is by asking the community on [Microsoft Q&A](https://docs.microsoft.com/answers/topics/uwp.html?sort=active&filter=all) or [StackOverflow](https://stackoverflow.com/questions) 

For completeness' sake, here is a list of developer resources:

- [Microsoft Q&A](https://docs.microsoft.com/answers/topics/uwp.html?sort=active&filter=all) offers relevant and timely answers to your technical problems from a community of experts and Microsoft engineers.
- For community assistance with development questions, there are our [forums](https://social.msdn.microsoft.com/Forums/newthread?category=windowsapps&forum=wpdevelop&prof=required), and [StackOverflow](https://stackoverflow.com/questions).
- The [Windows developer support](https://developer.microsoft.com/windows/support) site explains other support options.
- The [Visual Studio developer community](https://developercommunity.visualstudio.com) is available, and responsive. The former User Voice feature is now there on the **Suggest a feature** tab, if you want to lobby for a change, a feature, or to make a suggestion.
- For developer issues, or suspected product bugs, there's [Microsoft Support](https://support.microsoft.com/contactus); a support engineer will look at the repro and see whether the issue is a Microsoft product bug, or something else. If it's a bug with a Microsoft product then the ticket will be free of charge.

If you receive assistance via any support resource and you believe that information would help us improve the docs, then please let us know or consider submitting a pull request.

Thanks,
Shawn
