### ISSUE TITLE
How can I declare Tobii Device ?

### ISSUE THREAD

**Issue by ghost** [MicrosoftDocs/windows-uwp#4782]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: d46f3f23-87a7-ca99-8245-04629410c00a
* Version Independent ID: 51d0ddfc-12bf-951e-1411-cda9f9d539aa
* Content: [Gaze interactions - Windows apps](https://learn.microsoft.com/en-us/windows/apps/design/input/gaze-interactions)
* Content Source: [hub/apps/design/input/gaze-interactions.md](https://github.com/MicrosoftDocs/windows-dev-docs/blob/docs/hub/apps/design/input/gaze-interactions.md)
* Product: **reunion**
* Technology: **design**
* GitHub Login: @Karl-Bridge-Microsoft
* Microsoft Alias: **kbridge**

**Comment by ghost** [comment]
Hello,
I would like to use your solution but I do not know how to define any device in your application. Could you help me where i can define it, because I would like to use Tobii 5. 
Thanks!
Best regards, 
Christophe

**Comment by Karl-Bridge-Microsoft** [comment]
Hi @czimmer69, we are changing the way we track issues filed from our documentation pages: please see this [blog post](https://techcommunity.microsoft.com/t5/microsoft-learn-blog/announcing-a-new-way-to-give-feedback-on-microsoft-learn/ba-p/4027635) for more details. Right now, this issue is being closed but if you feel it is still valid and has not been addressed, please re-open it with any more available information. Please note that if your question is more general and not related to documentation, [Microsoft Q&A](https://learn.microsoft.com/en-us/answers/questions/) is a great way to get questions answered.
