### ISSUE TITLE
Wrong Link

### ISSUE THREAD

**Issue by ghost** [MicrosoftDocs/windows-uwp#4846]
In Partner Center, I created a Flight Group. The instructions there state:
"In order to get package flights for your app, people will need to have a Microsoft account associated with an email address. Enter the Microsoft accounts of the people you'd like to add to this group. The group can include up to 10,000 people. Be sure that these people have agreed to get package flights instead of your non-flighted submissions. [Learn more](http://go.microsoft.com/fwlink/?LinkId=626106)"

[Enter feedback here]
I clicked the link because I dont understand what "people will need to have a Microsoft account associated with an email address" means for the people in my company that I want to give access to via their corporate email address (zzz@mycompany.com).

The link takes me to a location that has Package Flight info, but not what I need.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: bc24dcd1-0e36-8613-cde9-eeca573fcffa
* Version Independent ID: bc24dcd1-0e36-8613-cde9-eeca573fcffa
* Content: [Package flights - Windows apps](https://learn.microsoft.com/en-us/windows/apps/publish/package-flights#add-and-rank-additional-package-flights)
* Content Source: [hub/apps/publish/package-flights.md](https://github.com/MicrosoftDocs/windows-dev-docs/blob/docs/hub/apps/publish/package-flights.md)
* Service: **windows-app-sdk**
* Sub-service: **apps**
* GitHub Login: @GrantMeStrength
* Microsoft Alias: **jken**

**Comment by GrantMeStrength** [comment]
Investigating.

**Comment by GrantMeStrength** [comment]
We are changing the way we track issues filed from our documentation pages: please see this [blog post](https://techcommunity.microsoft.com/t5/microsoft-learn-blog/announcing-a-new-way-to-give-feedback-on-microsoft-learn/ba-p/4027635) for more details. The Microsoft Store documentation has been updated several times since your issue was reported, and there's a good chance your problem has been addressed. Right now, this issue is being closed but if you feel it is still valid and has not been addressed, please re-open it with any more available information. Please note that if you question is more general and not related to documentation, [Microsoft Q&A](https://learn.microsoft.com/en-us/answers/questions/) is a great way to get questions answered.
