### ISSUE TITLE
Unable to reserve name, always redirected to partner center starting page

### ISSUE THREAD

**Issue by giorgio79** [MicrosoftDocs/windows-uwp#4853]
Hello,

I checked my perms and I have permission to create new apps, yet I am always redirected from https://partner.microsoft.com/dashboard/apps-and-games/overview to https://partner.microsoft.com/en-us/dashboard/home?redirect=v1
whats going on?

**Comment by giorgio79** [comment]
Oh, lots of similar issues without replies https://github.com/MicrosoftDocs/windows-dev-docs/issues?q=is%3Aissue+is%3Aopen+reserve

wow

**Comment by GrantMeStrength** [comment]
Reaching out to Store team.

**Comment by GrantMeStrength** [comment]
We are changing the way we track issues filed from our documentation pages: please see this [blog post](https://techcommunity.microsoft.com/t5/microsoft-learn-blog/announcing-a-new-way-to-give-feedback-on-microsoft-learn/ba-p/4027635) for more details. The Microsoft Store documentation has been updated several times since your issue was reported, and there's a good chance your problem has been addressed. Right now, this issue is being closed but if you feel it is still valid and has not been addressed, please re-open it with any more available information. Please note that if you question is more general and not related to documentation, [Microsoft Q&A](https://learn.microsoft.com/en-us/answers/questions/) is a great way to get questions answered.
