### ISSUE TITLE
Developer Account registration won't move to Payment step

### ISSUE THREAD

**Issue by ramonmata** [MicrosoftDocs/windows-uwp#4856]
Trying to open a Developer Account does not work following the instructions in the document.
Event setting browser locale to en-us.

**Steps to reproduce**:

- Account Country / Region : Mexico
- Account Type: Individual
- Fill all required data in form below

**Expected results**:
- Move forward to Payment step

**Actual Results**:
- Page shows form data
- Form data for "Email address" and "State" is missing
- Sometimes when you try several times it shows a box with the following message:
```
Error code 2201.
Correlation ID f733110e-c0b9-4c58-8309-eef4ce71bf83,FnptZvaM90GlBk38.0.1.
```

```---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 3e1454e7-b65d-5cce-834a-d2b6bb57bbc7
* Version Independent ID: 3e1454e7-b65d-5cce-834a-d2b6bb57bbc7
* Content: [Open a developer account in Partner Center - Windows apps](https://learn.microsoft.com/en-us/windows/apps/publish/partner-center/open-a-developer-account)
* Content Source: [hub/apps/publish/partner-center/open-a-developer-account.md](https://github.com/MicrosoftDocs/windows-dev-docs/blob/docs/hub/apps/publish/partner-center/open-a-developer-account.md)
* Service: **windows-app-sdk**
* Sub-service: **apps**
* GitHub Login: @GrantMeStrength
* Microsoft Alias: **jken**

**Comment by GrantMeStrength** [comment]
Reaching out to Store team.

**Comment by GrantMeStrength** [comment]
We are changing the way we track issues filed from our documentation pages: please see this [blog post](https://techcommunity.microsoft.com/t5/microsoft-learn-blog/announcing-a-new-way-to-give-feedback-on-microsoft-learn/ba-p/4027635) for more details. The Microsoft Store documentation has been updated several times since your issue was reported, and there's a good chance your problem has been addressed. Right now, this issue is being closed but if you feel it is still valid and has not been addressed, please re-open it with any more available information. Please note that if you question is more general and not related to documentation, [Microsoft Q&A](https://learn.microsoft.com/en-us/answers/questions/) is a great way to get questions answered.
