### ISSUE TITLE
The script for installing winget in Windows Sandbox does work out of the box

### ISSUE THREAD

**Issue by bent-rasmussen** [MicrosoftDocs/windows-uwp#4883]
### Type of issue

Code doesn't work

### Feedback

Steps to reproduce:

1. Start a new Windows Sandbox instance (Windows 11 Pro, Version 10.0.22631 Build 22631)
2. Open a powershell promt
3. Run the script, as copied from the documentation
4. Fail, as below:

![image](https://github.com/MicrosoftDocs/windows-dev-docs/assets/2722728/779dabfe-4a1f-4786-beb9-f8d7a1c9c29b)

```
Add-AppxPackage : Deployment failed with HRESULT: 0x80073CF3, Package failed updates, dependency or conflict validation.
Windows cannot install package Microsoft.DesktopAppInstaller_1.22.10582.0_x64__8wekyb3d8bbwe because this package depends on a framework that could not be found. Provide the framework
"Microsoft.UI.Xaml.2.8" published by "CN=Microsoft Corporation, O=Microsoft Corporation, L=Redmond, S=Washington, C=US", with neutral or x64 processor architecture and minimum version
8.2310.30001.0, along with this package to install.
NOTE: For additional information, look for [ActivityId] 6e69e1c0-6684-0007-ce4f-6a6e8466da01 in the Event Log or use the command line Get-AppPackageLog -ActivityID
6e69e1c0-6684-0007-ce4f-6a6e8466da01
At line:8 char:1
+ Add-AppxPackage Microsoft.DesktopAppInstaller_8wekyb3d8bbwe.msixbundl ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : WriteError: (C:\Users\WDAGUt...bbwe.msixbundle:String) [Add-AppxPackage], IOException
    + FullyQualifiedErrorId : DeploymentError,Microsoft.Windows.Appx.PackageManager.Commands.AddAppxPackageCommand
```

### Page URL

https://learn.microsoft.com/en-us/windows/package-manager/winget/#install-winget-on-windows-sandbox

### Content source URL

https://github.com/MicrosoftDocs/windows-dev-docs/blob/docs/hub/package-manager/winget/index.md

### Author

@mattwojo

### Document Id

b49c32ea-2efa-b090-7123-87c31d10279b

**Comment by mattwojo** [comment]
Hey @bent-rasmussen - Thanks for filing this issue. I just heard from the WinGet PM that there is a new dependency due to a new version of the UI.Xaml framework release for WinGet 1.7. The PR to fix the PowerShell module is in progress:
https://github.com/microsoft/winget-cli/pull/4218
Once the fix is merged and we are able to test and ensure that the WinGet installation works properly in Windows Sandbox, we will update the doc to reflect the new install script. 
Since this is a duplicate issue of https://github.com/MicrosoftDocs/windows-dev-docs/issues/4882, I will close this one, but will post updates in #4882.
