### ISSUE TITLE
Can I already play with the Microsoft Store API before the submitted app being approved?

### ISSUE THREAD

**Issue by ghost** [MicrosoftDocs/windows-uwp#4892]
### Type of issue

Missing information

### Feedback

I am learning and developing a new app. Thats why I sumitted a test app for certification. Before approved or after I would like to play with the Microsoft Store Api to test whether I can see if the user is logged in/authorised and if so, I would like to see if he or see downloaded and installed the app, if he or she has any purchases or subscriptions on it. I would like to find out if and how I can relate my Azure AD B2C user flow bearer token to the user id which I hope to receive from the Microsoft Store Api. All of this flow I wanna test in Postman first before using any c#. Please share with my all the steps I have to go through and if possible screenshots. Also, which permissions I have to fix. Many thanks.

### Page URL

https://learn.microsoft.com/nl-nl/windows/apps/publish/publish-your-app/app-certification-process?pivots=store-installer-msix

### Content source URL

https://github.com/MicrosoftDocs/windows-dev-docs/blob/docs/hub/apps/publish/publish-your-app/app-certification-process.md

### Author

@GrantMeStrength

### Document Id

4e55fb53-7eb0-d5ef-e32f-e558461d6e88

**Comment by GrantMeStrength** [comment]
We are changing the way we track issues filed from our documentation pages: please see this [blog post](https://techcommunity.microsoft.com/t5/microsoft-learn-blog/announcing-a-new-way-to-give-feedback-on-microsoft-learn/ba-p/4027635) for more details. Right now, this issue is being closed but if you feel it is still valid and has not been addressed, please re-open it with any more available information. Please note that if your question is more general and not related to documentation, [Microsoft Q&A](https://learn.microsoft.com/en-us/answers/questions/) is a great way to get questions answered.
