### ISSUE TITLE
tutorial is incomplete or does not work

### ISSUE THREAD

**Issue by josersleal** [MicrosoftDocs/windows-uwp#5010]
### Type of issue

Code doesn't work

### Feedback

nothing works, not even the android studio setup, the java setup for example returns an error that the java home env var is pointing to an invalid folder. emulator does not start. too much to write here.

### Page URL

https://learn.microsoft.com/en-us/windows/dev-environment/javascript/react-native-for-android

### Content source URL

https://github.com/MicrosoftDocs/windows-dev-docs/blob/docs/hub/dev-environment/javascript/react-native-for-android.md

### Author

@drewbatgit

### Document Id

e39706ca-3548-03e8-672f-9e7d5bff92ae

**Comment by drewbatgit** [comment]
@josersleal Thanks for reporting this issue. We have updated the page to refer to the [Set Up Your Environment](https://reactnative.dev/docs/set-up-your-environment?platform=android) in the React native docs. And we have updated the instructions to recommend retrieving the JDK install directory from the settings page in Android Studio rather than hardcoding the path in the page. Hopefully, both of these changes will help to prevent the tutorial from breaking when the underlying, external technologies make changes. I have run through the new page content successfully end-to-end, so hopefully this will allow you to complete the tutorial. Although there are certain details, such as the specifics of your Android Studio installation, that I am unable to reproduce or validate. Thanks again for reporting the errors you found in this page.
