### ISSUE TITLE
Doesn't cover getting a handle from a control

### ISSUE THREAD

**Issue by dotMorten** [MicrosoftDocs/windows-uwp#5080]
### Type of issue

Missing information

### Feedback

The article describes how to get a window handle from an app that has a MainWindow property exposed. However if you have for instance a control, you can't rely on a window property on the app. How would for instance a control that has a Save button in it show a save picker, if it can't get the handle that it needs to attach the picker to?

### Page URL

https://learn.microsoft.com/en-us/windows/apps/develop/ui-input/retrieve-hwnd

### Content source URL

https://github.com/MicrosoftDocs/windows-dev-docs/blob/docs/hub/apps/develop/ui-input/retrieve-hwnd.md

### Author

@stevewhims

### Document Id

add08135-2edb-f3a8-4673-11ae268c955e

**Comment by stevewhims** [comment]
Thanks, @dotMorten, I've pinged the product team subject-matter experts for help.

-Steve

**Comment by stevewhims** [comment]
I'll go ahead and update the topic with the small amount of info that I have (from https://github.com/microsoft/microsoft-ui-xaml/issues/9857, and from the SMEs). But this issue seems to overlap https://github.com/microsoft/microsoft-ui-xaml/issues/9857. So I'll go ahead and close this. When the platform can do more, then we'll document it.

Thanks!
-Steve
