### ISSUE TITLE
PC restart msg push invalid

### ISSUE THREAD

**Issue by xiaozhaoGithub** [MicrosoftDocs/windows-uwp#5133]
### Type of issue

Missing information

### Feedback

Hello, after the PC restarts, the message like the channel URI pushes and cannot be reached. Status code: 200, X-WNS-DEVICECONNECTIONSTATUS: connected, X-WNS-NOTIFICATIONSTATUS: droped. What is the solution?

### Page URL

https://learn.microsoft.com/zh-cn/windows/apps/design/shell/tiles-and-notifications/raw-notification-overview

### Content source URL

https://github.com/MicrosoftDocs/windows-dev-docs/blob/docs/hub/apps/design/shell/tiles-and-notifications/raw-notification-overview.md

### Author

@drewbatgit

### Document Id

fd84157d-eaf7-82e6-7a18-9d24e2c36266

**Comment by drewbatgit** [comment]
Thanks again for reporting this possible issue. If you'd like to report the potential product bug in the API, you can open a new question with the community of experts and Microsoft Engineers over at [Microsoft Q&A](https://learn.microsoft.com/en-us/answers/tags/105/windows-uwp) offer timely answers to a multitude of technical questions surrounding Windows APIs.
If you do create a thread over at Microsoft Q&A, we would appreciate if you could share that link here so we can track the progress and incorporate any technical details into our documentation. I'm also going to forward this information along to one of my product team contacts for investigation. Though this issue is closed, please treat this thread as an open thread for follow-ups. Thanks!

**Comment by xiaozhaoGithub** [comment]
ok，look at this link：https://learn.microsoft.com/en-us/answers/questions/2119734/wns(raw-notification)-fail-after-pc-restart-and-ca       


> Thanks again for reporting this possible issue. If you'd like to report the potential product bug in the API, you can open a new question with the community of experts and Microsoft Engineers over at [Microsoft Q&A](https://learn.microsoft.com/en-us/answers/tags/105/windows-uwp) offer timely answers to a multitude of technical questions surrounding Windows APIs.
> If you do create a thread over at Microsoft Q&A, we would appreciate if you could share that link here so we can track the progress and incorporate any technical details into our documentation. I'm also going to forward this information along to one of my product team contacts for investigation. Though this issue is closed, please treat this thread as an open thread for follow-ups. Thanks!
