### ISSUE TITLE
Outdated video

### ISSUE THREAD

**Issue by ChristopherDrum** [MicrosoftDocs/windows-uwp#514]
While it is useful, seeing Xcode 4.x when we're on Xcode 9.x is a little jarring. Would be useful to keep such a comparison video up to date.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 18c3052d-d0a4-8eec-39f3-bdc493351fd8
* Version Independent ID: 8ede4331-aecc-bf05-e39a-778260a8a38f
* Content: [Creating a project in Visual Studio - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/porting/getting-started-creating-a-project#feedback)
* Content Source: [windows-apps-src/porting/getting-started-creating-a-project.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/porting/getting-started-creating-a-project.md)
* Service: **unspecified**
* GitHub Login: @stevewhims
* Microsoft Alias: **stwhi**

**Comment by stevewhims** [comment]
Thanks for the feedback, Christopher! I'll see whether there's anything we can do, taking priorities into consideration.

**Comment by hickeys** [comment]
Thanks for opening this issue, @ChristopherDrum. Like @stevewhims said, this is something we'd like to update, but it has to be balanced against other priorities. Instead of leaving this issue open, I've created a task in our bug tracking system so that this work can be better tracked and prioritized. Because it's tracked somewhere else, I'm going to close this issue.

Thanks,
Shawn
