### ISSUE TITLE
 winget - Argument name was not recognized for the current command: '--download-directory'

### ISSUE THREAD

**Issue by cosmin-vasu** [MicrosoftDocs/windows-uwp#5142]
### Type of issue

Code doesn't work

### Feedback

the option "-d, --download-directory	Directory where the installers are downloaded to." that is mentioned on the learn page does not seem to be implemented.

Windows Package Manager v1.8.1911
Copyright (c) Microsoft Corporation. All rights reserved.

Argument name was not recognized for the current command: '--download-directory'

Windows Package Manager (Preview) v1.9.2411-preview
Copyright (c) Microsoft Corporation. All rights reserved.

Argument alias was not recognized for the current command: '-d'

### Page URL

https://learn.microsoft.com/en-us/windows/package-manager/winget/download

### Content source URL

https://github.com/MicrosoftDocs/windows-dev-docs/blob/docs/hub/package-manager/winget/download.md

### Author

@mattwojo

### Document Id

ffd25a38-f0e8-bf19-292d-fe609b4deb78

**Comment by zaochih** [comment]
**_EDITED:_ Please re-confirm you were running `winget download` when using this arg since it may not apply to the other commands.**

![](https://github.com/user-attachments/assets/4d846fe9-2949-4f5f-a1ad-a25b5f914b78)  
![](https://github.com/user-attachments/assets/ce23e74c-153b-4ed2-943c-7a59788ed42e)  
![](https://github.com/user-attachments/assets/837a342c-8910-4785-9b70-add484f0c184)

It looks strange... Both `--download-directory` and `-d` works for me.  
Can you go to _**Windows Settings - Apps - Installed Apps**_, enter the _Advanced Options_ for _**Windows Package Manager Source (winget) V2**_, and try repairing or resetting it?

![](https://github.com/user-attachments/assets/79d6d4ba-d26c-4148-8a1e-34746e38cf0c)  
![](https://github.com/user-attachments/assets/76c43519-97f4-4bdd-9486-f0e2a975b052)

If it still couldn't work properly after taking these actions, creating a bug report [here at microsoft/winget-cli](https://github.com/microsoft/winget-cli/issues/new?assignees=&labels=&projects=&template=Bug_Report.yml) may be better for you :)

**Comment by cosmin-vasu** [comment]
Thanks LiCaoZ,

I just realize that "--download-directory" is an option for download command only and not available for upgrade or install commands (which is ashamed, but that is another story )
