### ISSUE TITLE
Documentation mixes WinUI2 and WinUI3;

### ISSUE THREAD

**Issue by PerArneS68** [MicrosoftDocs/windows-uwp#5229]
### Type of issue

Typo

### Feedback

I started reading about WuinUI3, presses a link for more details and all samples are UWP, WinUI2,
This is extremely confusing in a tutorial.

### Page URL

https://learn.microsoft.com/en-us/windows/apps/develop/win2d/quick-start

### Content source URL

https://github.com/MicrosoftDocs/windows-dev-docs/blob/docs/hub/apps/develop/win2d/quick-start.md

### Author

@stevewhims

### Document Id

fd2206a7-becd-770f-14f0-6471d416868a

**Comment by stevewhims** [comment]
Hi, @PerArneS68, and thanks for filing this issue.

When you say you "started reading about WinUI 3", do you mean in this topic? I'm just curious, because this topic contains only a single mention of "WinUI 3", and it simply says that you can use it. It doesn't really say anything *about* WinUI 3. At least, not here.

"Pressed a link for more details"--to really understand the problem, it'd be great to know what link was clicked. Now, right where the topic mentions WinUI 3, there is a link. To the quickstart topic. And that looks fine. It shows how to do the steps with WinUI 3 first, which is great, and UWP second.

And that's it; I can't seem to see a problem. So I'll go ahead and close the issue. But you can always comment, or reopen if you feel it's been closed in error.

Thanks again!
-Steve
