### ISSUE TITLE
It didn't work

### ISSUE THREAD

**Issue by xiaoyuzhzh** [MicrosoftDocs/windows-uwp#540]
I installed this template and create a project，but this app can only open one instance. And I find some warning in Package.appxmanifest that is  未声明 “http://schemas.microsoft.com/appx/manifest/desktop/windows10/4:SupportsMultipleInstances”特性

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: 9554b9f2-2f49-1833-1143-0103c18c37c8
* Version Independent ID: ef28f9ce-bd72-0435-6238-95d574eabee1
* Content: [Create a multi-instance Universal Windows App - UWP app developer](https://docs.microsoft.com/zh-cn/windows/uwp/launch-resume/multi-instance-uwp)
* Content Source: [windows-apps-src/launch-resume/multi-instance-uwp.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/launch-resume/multi-instance-uwp.md)
* Service: **windows**
* GitHub Login: @TylerMSFT
* Microsoft Alias: **twhitney**

**Comment by xiaoyuzhzh** [comment]
Hope you can understand this. haha

**Comment by xiaoyuzhzh** [comment]
I am wrong. I should upgrade sdk to 17134. It's working.

**Comment by michael-hawker** [comment]
@TylerMSFT the only mention of the version is the intro 'Prior to 1803,' and doesn't have the build number.

Could be useful to clarify that as was the initial confusion that opened this bug.

Would it make sense on these more tutorial articles to also have a version dialog like we do on the API calls?


Device family | Windows 10, version 1803 (introduced v10.0.17134.0)
-- | --
API contract | Windows.Foundation.UniversalApiContract (introduced v6)

**Comment by stevewhims** [comment]
Thanks, @xiaoyuzhzh and @michael-hawker! I've just merged in a change to this topic to add the missing version numbers. The version table is appropriate for API reference topics, which deal with a single API. But that's not always going to work for a conceptual topic, which always covers many APIs. However, I agree that there was version info missing, so that'll be rectified when the updated topic appears on the live site, which will happen tomorrow morning.

Thanks!
Steve
