### ISSUE TITLE
Secured Web locations

### ISSUE THREAD

**Issue by endyb66** [MicrosoftDocs/windows-uwp#554]
When providing an appinstaller file with a web location for updates, is it possible to set credentials somewhere, which are used to acces the web location?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3eebf940-9282-41a2-f236-55984ff76aeb
* Version Independent ID: a1b3c572-c6ba-eff7-637d-cbcb20801c57
* Content: [Create an App Installer file with Visual Studio - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/packaging/create-appinstallerfile-vs)
* Content Source: [windows-apps-src/packaging/create-appinstallerfile-vs.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/packaging/create-appinstallerfile-vs.md)
* Service: **windows**
* GitHub Login: @ridomin
* Microsoft Alias: **rmpablos**

**Comment by endyb66** [comment]
Any news on this issue?

**Comment by rido-min** [comment]
Hi @endyb66  thanks for the suggestion, we are evaluating different options and would be helpful if you describe your scenario. Which kind of credentials (Basic, NTLM, OAuth) ?

If you want to provide further details, please contact me: rmpablos at microsoft dot com.

**Comment by endyb66** [comment]
Hi @rido-min, for my app package service, i'm using Basig and Digest Auth, so it would be really helpful, if there would be an option to provide username / password credentials for that.

**Comment by mcleanbyron** [comment]
Thanks for taking the time to let us know about this and we sincerely apologize for the delayed response. 

Due to the sheer volume of feedback in our repo, we are currently prioritizing new Issues. If you believe your feedback is still actionable, let us know either directly in this thread or by filing a new issue by using the Feedback control at the bottom of [the App Installer article](https://docs.microsoft.com/en-us/windows/msix/app-installer/create-appinstallerfile-vs). 

Though the issue will be marked as closed, I will monitor any replies that come afterwards so feel free to treat this like an open Issue. Thank you.
