### ISSUE TITLE
broadFileSystemAccess issue

### ISSUE THREAD

**Issue by kevin-jing** [MicrosoftDocs/windows-uwp#558]
broadFileSystemAccess works when min version = 15036. But error occurs when min version >= 16299, Access to the path 'C:\Users\xxx\OneDrive\invest\xxx.db' is denied.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0d92df11-eaec-44ea-d130-e84304af9b8f
* Version Independent ID: d8ada2a7-dcea-96cc-210b-5b446ee88cad
* Content: [File access permissions - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/files/file-access-permissions)
* Content Source: [windows-apps-src/files/file-access-permissions.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/files/file-access-permissions.md)
* Service: **windows**
* GitHub Login: @laurenhughes
* Microsoft Alias: **lahugh**

**Comment by kevin-jing** [comment]
resolved.

**Comment by moyanming** [comment]
Hi @kevin-jing ,
Same problem here on the 17763 (1809), could you tell me how to solve this problem?
Best regards.

**Comment by touseefbsb** [comment]
strangely I also have app min version as 1809 and the app is supposed to ask the user about allowing file system access, but it never does, and then it denies access. So I checked in settings -> file system access, and I saw that my app name is there in the list but access to it is turned off, if I turn it on then access works as expected, but the problem is the app never asks for the access from user on first run so it is turned off by default. @kevin-jing  @laurenhughes
