### ISSUE TITLE
what may make GraphicsCaptureSession.IsSupported() return false?

### ISSUE THREAD

**Issue by Airborne76** [MicrosoftDocs/windows-uwp#586]
I added graphicsCapture in Package.appxmanifest, but GraphicsCaptureSession.IsSupported() still return false。 I packaged my application and installed it on other devices but it returned true. My system version is 17134.48, Visual Studio version is 15.7.1, DirectX12 installed, and other screen capture application like OBS run smoothly. So which may cause GraphicsCaptureSession.IsSupported() return false?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f607a1db-43b3-bf1c-c6d1-6283c1280743
* Version Independent ID: c1c72175-3e9c-59f6-e30e-7d6f821c5876
* Content: [Screen capture - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/audio-video-camera/screen-capture)
* Content Source: [windows-apps-src/audio-video-camera/screen-capture.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/audio-video-camera/screen-capture.md)
* Service: **unspecified**
* Product: **windows**
* GitHub Login: @eliotcowley
* Microsoft Alias: **elcowle**

**Comment by eliotcowley** [comment]
Hi @Airborne76, sorry to hear that you're having issues. I've reached out to the feature team and will get back to you shortly.

**Comment by eliotcowley** [comment]
Hi @Airborne76, which version of Windows 10 are you using for development? Unfortunately, the screen capture APIs currently only work on Windows 10 Pro/Enterprise. However, in a future update, they should also work on Windows 10 Home.

**Comment by ychsue** [comment]
This is a very nice functionality so that I added it to my App once 1803 is released.
 However, I am facing a problem that my App will crash when the user navigates to the usercontrol with the namespace  Windows.Graphics.Capture when their version is lower than 1803.
Now, it is not the problem of GraphicsCaptureSession.IsSupported() but lack of the namespace for the older version of Windows 10 and crashing my App.
Please help me to solve this problem. Thanks a lot.

**Comment by Airborne76** [comment]
Hi @eliotcowley Got it. My vseion is Windows10 Home. Thanks for your information.

**Comment by ychsue** [comment]
I'm not sure whether the method shown below is work.

I have moved all the part related to the namespace Windows.Graphics.Capture into a provider class and then use 

IsSupported = ApiInformation.IsTypePresent("Windows.Graphics.Capture.GraphicsCaptureItem");

to check whether I should create that provider object for this screen capture picker.

Although it works on my PC, I am not sure if it worked on an older version of Windows 10.

**Comment by eliotcowley** [comment]
Hi @ychsue, because the Windows.Graphics.Capture APIs require Windows 10, version 1803, they will not work on a device that has a Windows 10 build that is lower than that. The method you described should work, however. Check out [this article](https://docs.microsoft.com/windows/uwp/debug-test-perf/version-adaptive-apps) for more info on writing code that adapts to the device's Windows 10 version.

Also @Airborne76, just to follow up, I've added a note to the doc that the screen capture APIs require Windows 10 Pro/Enterprise.

Thanks!
