### ISSUE TITLE
URI missing for April Update

### ISSUE THREAD

**Issue by pixartist** [MicrosoftDocs/windows-uwp#588]
This reference is missing the URI for App-Specific Audio Settings from the April Update

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c6a2ae18-080e-3470-d1c7-ab2990d4da85
* Version Independent ID: 3d0d02af-c1d7-e2e7-ba01-15e0904dc9a6
* Content: [Launch the Windows Settings app - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/launch-resume/launch-settings-app)
* Content Source: [windows-apps-src/launch-resume/launch-settings-app.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/launch-resume/launch-settings-app.md)
* Service: **unspecified**
* Product: **windows**
* GitHub Login: @TylerMSFT
* Microsoft Alias: **twhitney**

**Comment by icecreamsellah** [comment]
Did you ever find out how to make a shortcut for this? Looking for the URI for this to try..

**Comment by pixartist** [comment]
Nope, sorry :/

**Comment by knicholasa** [comment]
Hi all, thanks for the feedback, and sorry for the long wait. I'm taking over this issue and looking into it now. I'll update the page and this thread ASAP.

**Comment by knicholasa** [comment]
Hi again, I believe I've found the URI you're looking for. It should be "ms-settings:apps-volume", which is for the "App volume and device preferences" menu.

**Comment by knicholasa** [comment]
I'm going to close the issue since there is no documentation update necessary. If you need further technical support, I recommend that you ask on our [forums](https://social.msdn.microsoft.com/Forums/newthread?category=windowsapps&forum=wpdevelop&prof=required) or [StackOverflow](https://stackoverflow.com/questions). Otherwise, please see [the developer support page](https://developer.microsoft.com/windows/support) for your support options.
