### ISSUE TITLE
Sql Connection fails.

### ISSUE THREAD

**Issue by eowarren625** [MicrosoftDocs/windows-uwp#592]
Carefully followed step by step but when executed fails when trying to make the sql server connection with the esql = null.
Note: the document could be improved by adding which file belongs to which code snippet and/or provide a working solution for download.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c7f63491-26ec-52f6-e124-dec2ecea8477
* Version Independent ID: 72aa55f1-766a-c015-a5f7-104359382d53
* Content: [Use a SQL Server database in a UWP app - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/data-access/sql-server-databases#feedback)
* Content Source: [windows-apps-src/data-access/sql-server-databases.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/data-access/sql-server-databases.md)
* Service: **unspecified**
* Product: **windows**
* GitHub Login: @normesta
* Microsoft Alias: **normesta**

**Comment by normesta** [comment]
Thank you for the note. I've rebuilt my local environment and I've also received this error. I'm currently investigating and will post back as soon as I have answers. Thank you!

**Comment by eowarren625** [comment]
I have gotten a connection to work, built a new UWP, added system.data.sqlserver to the usings on page1, then only system.data.sqlserver connection. It worked. I have not gotten anything else to connect.

Thanks for the feedback, at least I know it’s not just me.


Edward O. Warren
mailto:eowarren@live.com

Home: 402.235.2627
Cell: 402.350.0873

**Comment by normesta** [comment]
Thank you for the info. So after a lot of troubleshooting, I found the reason I was unable to connect successfully from UWP. In my case, TCP/IP was not enabled in the Computer Management console for SQL, and the SQL Server Browser service had to be started. To share with others, I've gone ahead and added this information to the bottom of the topic here - https://docs.microsoft.com/en-us/windows/uwp/data-access/sql-server-databases#trouble-connecting-to-your-database . I **Believe** the project-related steps in this guide are accurate and in most cases connection issues should come down to something in SQL Server configuration (Which this topic doesn't go into much detail about - by design). That said, if more of these sorts of things pop up, I may have to add workarounds for common config issues.

**Comment by eowarren625** [comment]
I had already checked all of the sql server settings and the changes that worked for you do not solve my issues.  But thanks for the work anyway.  If I find out what the problems are I will let you know.

Eowarren.

**Comment by normesta** [comment]
Thank you! Yes please do share if you find a workaround that helped you get past your issue. If it's something that is likely to affect other folks, I'll add it to the doc.

Thanks again!
