### ISSUE TITLE
How to Handle "Always Use This App" Checkbox on Open With Dialog

### ISSUE THREAD

**Issue by lukeblevins** [MicrosoftDocs/windows-uwp#630]
I am able to show my users an Open With Dialog, but if they select the "Always use this app to open [.EXT] files" checkbox, Windows will not remember their preferences. I have searched the documentation for help with no luck. How would I handle these preferences in my code?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 86fe00a4-e3cc-099f-0172-1274c3478291
* Version Independent ID: b99d4fbc-e13f-009f-dcda-5e77694744b4
* Content: [Launch the default app for a file - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/launch-resume/launch-the-default-app-for-a-file)
* Content Source: [windows-apps-src/launch-resume/launch-the-default-app-for-a-file.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/launch-resume/launch-the-default-app-for-a-file.md)
* Service: **unspecified**
* Product: **windows**
* GitHub Login: @TylerMSFT
* Microsoft Alias: **twhitney**

**Comment by stevewhims** [comment]
Hi, @duke7553, thanks for raising this issue, I know you filed it a long time ago, and I'm sorry for the really delayed response here.

I've just tried out the code under the "Open With launch" section in the topic.

What I did was: I created a new file (containing text) in my app's Assets folder on disk, and named it foo.unique. In Visual Studio, I added that new file to my app (in the Assets folder in Solution Explorer) as as Content, Do not copy, just like the other assets. Looking at the new file in File Explorer, it had no special icon, so no app associated with the .unique file extension. When I double-clicked it in File Explorer the Open With dialog appeared. I canceled.

I changed the example code from the topic to open that file. As I say, initially there was no file association so when I ran my app the first time I picked Notepad, but I left "always use this app" unchecked. The file opened in Notepad, and in File Explorer the icon was unchanged from the default. Then I repeated the experiment but this time I checked "always use". This time, in File Explorer the icon for foo.unique changed to the Notepad icon and I was able to double-click the file (in File Explorer) and it opened automatically in Notepad. I repeated the above two experiments but chose the Visual Studio Code editor instead of Notepad, with the same results (icon changed, double-clicking opened it in the appropriate app).

My conclusion is that you're not meant to handle that checkbox in your own app. Instead, the Windows shell is responsible for setting and updating the associated of a default app for a file extension. There are limitations to the kinds of files that you can successfully associate with a default app, though, as the topic discusses. I don't know whether that's a factor with your case.

Are you able to reproduce my experiments above with the same results? And, if so, is there anything that you can detect that's different about your desired scenario that might explain why you're not getting the same results as my experiment?

Thanks!
Steve

**Comment by lukeblevins** [comment]
Hey, Steve!
Sorry for the late response. 
With my original question I was actually implying that the Windows Shell is not remembering the user's default app preference. My application is a file explorer situation which displays a DataGrid of StorageItems clicking on a **file** typed item will prompt the user which app to use in this instance, but opting to associate an app with a file type is not remembered by the Windows shell. The source code for this app is available on my GitHub. That's why I was not sure if it required further logic from my app.

Regards,
Luke Blevins

**Comment by lukeblevins** [comment]
Also, I have tested this situation with many files. For instance, PNG, JPG, MP4, TXT all demonstrate this issue. Below is a relevant snippet of code. Maybe I am overriding the set user preferences with the LauncherOption to DisplayApplicationPicker. I feel that the docs should highlight this option better to provide developers with a better understanding.

```
public static async void List_ItemClick(object sender, DoubleTappedRoutedEventArgs e)
{
     if (page.Name == "GenericItemView")
     {
          var index = GenericFileBrowser.data.SelectedIndex;
          if(index > -1)
          {
               var clickedOnItem = ItemViewModel.FilesAndFolders[index];
               if (clickedOnItem.FileExtension == "Folder")
               {
                        ItemViewModel.TextState.isVisible = Visibility.Collapsed;
                        History.ForwardList.Clear();
                        ItemViewModel.FS.isEnabled = false;
                        ItemViewModel.FilesAndFolders.Clear();
                        ItemViewModel.ViewModel = new ItemViewModel(clickedOnItem.FilePath, false);
                        GenericFileBrowser.P.path = clickedOnItem.FilePath;
                        GenericFileBrowser.UpdateAllBindings();
               }
               else if (clickedOnItem.FileExtension == "Executable")
               {
                        message = new MessageDialog("We noticed you’re trying to run an executable file. This type of file may be a security risk to your device, and is not supported by the Universal Windows Platform. If you're not sure what this means, check out the Microsoft Store for a large selection of secure apps, games, and more.");
                        message.Title = "Unsupported Functionality";
                        message.Commands.Add(new UICommand("Continue...", new UICommandInvokedHandler(Interaction.CommandInvokedHandler)));
                        message.Commands.Add(new UICommand("Cancel"));
                        await message.ShowAsync();
               }
               else
               {
                        StorageFile file = await StorageFile.GetFileFromPathAsync(clickedOnItem.FilePath);
                        var options = new LauncherOptions
                        {
                            DisplayApplicationPicker = true
                        };
                        await Launcher.LaunchFileAsync(file, options);
               }

          }
          else
          {
                    // Note to self: Placeholder for row sorting logic
          }

     }
 }
```

**Comment by stevewhims** [comment]
Hi, Luke,

I did my experiment again (using the code in the "Open With launch" section of this topic), this time using the TXT file extension (which is one of the extensions you mention having trouble with). Same experiment I describe above, and again the Windows Shell does remember the app I pick when I check "always use this app". For example, this time I picked WordPad, checked "always use this app", and when I returned to File Explorer, I could double-click that file and it opened in WordPad. Same behavior for any othe TXT file, or even one I just created from scratch. Even File Explorer > right-click > New > Text Document shows WordPad's icon. Even calling the code in the 'Default launch" section of this topic opens that same file directly in WordPad.

In my experiments, I'm seeing that the Windows Shell *is* remembering the user's default app preference for a given extension. So I'm not seeing anything in the topic that needs changing.

So that we can get a baseline of expected behavior, are you able to follow my experiments and get the same results? If we can establish that at least the scenario in the topic works, then we can move forward from that.

Many thanks,
Steve

**Comment by stevewhims** [comment]
Hi, Luke, I'll go ahead and close this issue now. Please reopen it if you need to, and we can pick up where we left off.

~Steve

**Comment by edwardchanjw** [comment]
If anyone interested, just info. There is no bug, that would be a restriction enforced by [Reserved file and URI scheme names](https://docs.microsoft.com/en-us/windows/uwp/launch-resume/reserved-uri-scheme-names)

**Comment by TylerMSFT** [comment]
Thanks @edwardchanjw
