### ISSUE TITLE
Renaming/Deleting folders

### ISSUE THREAD

**Issue by ahojnnes** [MicrosoftDocs/windows-uwp#662]
The same actions that are available for files, should also work on (potentially empty) folders.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ae1ab644-ee7d-3dec-cd0f-cbb1e4d8b6ac
* Version Independent ID: 97eecc36-8e2e-d4c7-1ecb-948e0846bda5
* Content: [Device Portal core API reference - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/debug-test-perf/device-portal-api-core)
* Content Source: [windows-apps-src/debug-test-perf/device-portal-api-core.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/debug-test-perf/device-portal-api-core.md)
* Product: **windows**
* GitHub Login: @PatrickFarley
* Microsoft Alias: **pafarley**

**Comment by loarabia** [comment]
Hi @ahojnnes , WDP's core API doesn't surface this today but it is on our backlog. One thing that helps us is understanding what device you're using WDP against (WDP runs on many form factors) and what you're trying to accomplish. Depending on the scenario, we can often come up with more holistic solutions.

**Comment by eliotcowley** [comment]
Hey @ahojnnes, would you mind answering @loarabia's questions below? It will help us figure out how to support your scenario. Thanks!

**Comment by ahojnnes** [comment]
The specific thing I needed to do is recursively deleting folders (empty or not) using the API. As far as I could tell, this was or is still not possible, with which you can only delete individual files.

**Comment by Karl-Bridge-Microsoft** [comment]
Hi @ahojnnes - This feedback is not specifically about the documentation, but rather a feature/product request. Please contact the following support channel.

- The [Feedback Hub app](https://support.microsoft.com/help/4021566/windows-10-send-feedback-to-microsoft-with-feedback-hub-app) is the right place to lobby for a change, a feature, or to make a suggestion.

For future reference, here are all of the developer support resources.

- For developer issues, or suspected product bugs, there's [Microsoft Support](https://support.microsoft.com/contactus); a support engineer will look at the repro and see whether the issue is a Microsoft product bug, or something else. If it's a bug with a Microsoft product then the ticket will be free of charge.
- For community assistance with development questions, there are our [forums](https://social.msdn.microsoft.com/Forums/newthread?category=windowsapps&forum=wpdevelop&prof=required), and [StackOverflow](https://stackoverflow.com/questions).
- The [Windows developer support](https://developer.microsoft.com/windows/support) site explains other support options.
- The [Visual Studio developer community](https://developercommunity.visualstudio.com) is available, and responsive. The former User Voice feature is now there on the **Suggest a feature** tab, if you want to lobby for a change, a feature, or to make a suggestion.

If you receive assistance via any support resource, and you believe that information would help us improve the docs, then please come back and let us know.
