### ISSUE TITLE
Unexplained change from StaticResource to ThemeResource

### ISSUE THREAD

**Issue by tca9** [MicrosoftDocs/windows-uwp#668]
In step 4.6 the following element is provided.
&lt;TextBlock Text="What's your name?" Style="{StaticResource BaseTextStyle}"/&gt;

But in the next step the "StaticResource" becomes "ThemeResource" without explanation.

&lt;TextBlock Style="{ThemeResource BaseTextBlockStyle}" FontSize="18" Text="What's your name?"/&gt;

Thanks for the great documentation and great site!
+tom

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 592392b3-226e-4277-4ed3-7f8789ab93de
* Version Independent ID: dc387625-6acb-52bb-ea7e-020af9913d80
* Content: [Create a Hello World app in C++ (Windows 10) - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/get-started/create-a-basic-windows-10-app-in-cpp)
* Content Source: [windows-apps-src/get-started/create-a-basic-windows-10-app-in-cpp.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/get-started/create-a-basic-windows-10-app-in-cpp.md)
* Product: **windows**
* GitHub Login: @GrantMeStrength
* Microsoft Alias: **jken**

**Comment by GrantMeStrength** [comment]
Thanks for finding this.

Both should use both should be “"{ThemeResource BaseTextBlockStyle}"”. This is probably a result of the original code being written for Windows 8, and ThemeResource being introduced in Windows 8.1 – the update was probably just missed.
 
If you want the full story, follow this link and find the “When and how to use {ThemeResource} rather than {StaticResource}” section.

https://docs.microsoft.com/en-us/windows/uwp/xaml-platform/themeresource-markup-extension

**Comment by tca9** [comment]
John,

Thanks much for the personal reply and for the link to the very interesting “When and how to use” info.  I’m glad my feedback was useful.

Regarding *that* document, I think there is another typo.  There is an example that compares “Default” versus “HighContrast” resources, but the contents of those two dictionaries are swapped, since the Default version provides high-contrast values.

Have a great day.


+tom

Tom Allen
tom.allen@cricketsoft.com | 408-821-6455 Mobile
Cupertino, CA | Sent from Mail for Windows 10

________________________________

**Comment by GrantMeStrength** [comment]
Ah, a doc-cascade bug :-) I'll take a look at this one too, thanks for letting us know!

**Comment by GrantMeStrength** [comment]
I checked with Jim, our XAML writer. He tells me that the content is correct in this instance. The default settings is black and white, not high contrast, because text _is_ black and white. And for the high contrast values, it picks up the system values. If you check the resources.xaml file, you can see the values associated with each setting and confirm this for yourself. Let me know if this isn't clear.

Thank you again for your feedback!

**Comment by tca9** [comment]
Thanks, John.  That is a clear explanation. Perhaps the example is a bit confusing because the black and white resources feel like high contrast.  😉 thx again.

+tom

Tom Allen
tom.allen@cricketsoft.com | 408-821-6455 Mobile
Cupertino, CA | Sent from Mail for Windows 10

________________________________

**Comment by GrantMeStrength** [comment]
Yes, I thought the same initially. Now we know! Thanks.
