### ISSUE TITLE
doesnt work for Lumia950xl

### ISSUE THREAD

**Issue by fredstoolbox** [MicrosoftDocs/windows-uwp#670]
For some reasons, this does not work on a Lumia 950, but works fine on a Lumia 640.
On Lumia 950, the PhotoCaptured event returns exactly the same Softwarebitmap for all frames (event though the controlvalues indicated exposure times are different each frame) .

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 72ffe237-7ddb-2ad9-2ad4-3890dcf6b55d
* Version Independent ID: 8dd33558-1265-d695-e797-1c8d40606616
* Content: [Variable photo sequence - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/audio-video-camera/variable-photo-sequence)
* Content Source: [windows-apps-src/audio-video-camera/variable-photo-sequence.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/audio-video-camera/variable-photo-sequence.md)
* Product: **windows**
* GitHub Login: @drewbatgit
* Microsoft Alias: **drewbat**

**Comment by drewbatgit** [comment]
Thanks for taking the time to let us know about this and we sincerely apologize for the delayed response. Due to the sheer volume of feedback in our repo, we are currently prioritizing new Issues. If you believe your feedback is still actionable, let us know either directly in this thread or by filing a new Issue and we’ll work to incorporate the suggestions into the documentation. Though the Issue will be marked as Closed, I will monitor any replies that come afterwards so feel free to treat this like an open Issue. Many thanks!
