### ISSUE TITLE
Finding reference manuals is hard

### ISSUE THREAD

**Issue by arkadye** [MicrosoftDocs/windows-uwp#673]
It would be really useful if a link to the reference for this library was put somewhere on this page.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7582404b-14df-79e3-643c-202afea30bb5
* Version Independent ID: c1e7a230-aaf8-916d-6d43-a15e380ed438
* Content: [Game Chat 2 overview - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/xbox-live/multiplayer/chat/game-chat-2-overview)
* Content Source: [windows-apps-src/xbox-live/multiplayer/chat/game-chat-2-overview.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/xbox-live/multiplayer/chat/game-chat-2-overview.md)
* Product: **windows**
* GitHub Login: @KevinAsgari
* Microsoft Alias: **tomco**

**Comment by mattwojo** [comment]
Thank you for taking the time to let us know about this issue. Apologies for the delayed response. Due to the volume of feedback in our content, we are currently prioritizing new issues. 

If you believe your feedback still requires action to be taken, please let us know either directly in this thread, by filing a new issue, or by filing a [Pull Request ](https://github.com/MicrosoftDocs/windows-uwp/pulls) with your recommended updates.

Though the Issue will be marked as closed, we will still receive replies and are able to reopen the issue if necessary. 

Thanks again for taking the time to contribute.
