### ISSUE TITLE
ControlChannelTrigger with WebSockets not working

### ISSUE THREAD

**Issue by IgorX2** [MicrosoftDocs/windows-uwp#685]
The ControlChannelTrigger with WebSockets example is not working and throwing an exception when a connection is established. The example in its presented form is not usable and has to be modified to even compile.

Details are available in the related [StackOverflow question](https://stackoverflow.com/questions/50860072/using-web-sockets-in-uwp-background-tasks).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 43204f04-7962-a734-18a7-86003ce5a257
* Version Independent ID: 67f8943c-758f-2ced-c8bb-b699c69d6443
* Content: [Network communications in the background - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/networking/network-communications-in-the-background)
* Content Source: [windows-apps-src/networking/network-communications-in-the-background.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/networking/network-communications-in-the-background.md)
* Product: **windows**
* GitHub Login: @stevewhims
* Microsoft Alias: **stwhi**

**Comment by stevewhims** [comment]
Thanks for the heads up, Igor, and my apologies for the issues with the topic. I'll take a look at what's going on here with a view to fixing it. I'll report back when I have progress. ~Steve

**Comment by stevewhims** [comment]
@IgorX2, really sorry about the delay getting to this. I have no progress to report yet, but I haven't forgotten about it. ~Steve

**Comment by stevewhims** [comment]
I have an update, although an unsatisfactory one. I've taken a look at the issue with a dev team person, but so far neither of us has been able to devote enough cycles to it to resolve it. The sample apps are a mix of Win10 and Win8.x, and in this case I've been trying to port the 8.x sample to 10 without success (I wanted to port it before I addressed this particular issue). I'm running into build errors, though. The current error I'm getting is, I believe, to do with using Task<T> instead of using WinRT async types such as IAsyncAction. However, the topic does say "when using a StreamWebSocket with the ControlChannelTrigger, your app must use a raw async pattern." The error and that quote might be related, assuming that the quote I just gave is true for Win10. We haven't forgotten this, but other things are before it in pri order, so it may be some time before we get to this. ~Steve

**Comment by IgorX2** [comment]
I could successfully build the code, but, as mentioned, I got an exception during runtime. I believe this is more of an OS/runtime bug, than a bug in your presentation. Although, the presentation could be clearer, as you yourself mentioned.

**Comment by mrjfalk** [comment]
@stevewhims I'm also experimenting with an app which would require using websockets in a background task, but I also get an runtime exception when using the MessageWebSocket with the ControlChannelTrigger: `"Exception from HRESULT: 0x80072F75"`. It occurs when connecting when I've done `controlChannelTrigger.UsingTransport(_socket);`, if I omit this line the websocket connection works fine (but of course not in the background task).

Is there just something missing in the documentation that you can quickly address or is it simply not possible right now in the current UWP platform?

**Comment by stevewhims** [comment]
Thanks for the message, @mrjfalk, I'll try and find time to get to this issue soon. I have higher-pri tasks in my queue right now, but once I've cleared those I'll try to get back to investigating this and working on understanding the problems here, and possibly updating the sample code. ~Steve

**Comment by jimm98y** [comment]
Any progress on this? I am running into the same issue: "Exception from HRESULT: 0x80072F75". It looks like ControlChannelTrigger does not work in Windows 10 at all.

**Comment by stevewhims** [comment]
Hi, @jimm98y. Thanks for commenting, this does feel higher priority each time someone comments. I'll boost its priority. I haven't made a start on it yet, but it'll hit the top of my backlog sooner now. Thanks for the patience, everyone. -Steve

**Comment by stevewhims** [comment]
Just a heads up that I'm closing this GitHub issue because I'm tracking it internally in my work items (so that it's not being tracked and counted twice). You'll still be able to leave comments here. I'll come back and (possibly reopen and) comment when I have a resolution for my work item.

Thanks!
Steve
