### ISSUE TITLE
Warning: MIDI API is still unusable.

### ISSUE THREAD

**Issue by Noemata** [MicrosoftDocs/windows-uwp#687]
Since the initial release of the new MIDI API back in 2014 during the early days of Windows 8.x, this API has had a serious device enumeration flaw, and a crippling inability to transmit SysEx messages.  Microsoft has repeatedly promised to fix this.  It's 2018, 4 years out from when these flaws were first identified, and 3 years out from when these flaws became common knowledge and we still wait for a fix.  Please either remove this broken API, or fix it.  Presently, only the old Win32 Midi APIs are viable on Windows.  So for Windows 10 S users, our kids based on Microsoft's educational emphasis, there is no music.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 90265caf-b1af-f015-674a-a015e3a35d65
* Version Independent ID: bf193eb6-cd09-7538-12ef-da3cd0188e8d
* Content: [MIDI - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/audio-video-camera/midi)
* Content Source: [windows-apps-src/audio-video-camera/midi.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/audio-video-camera/midi.md)
* Product: **windows**
* GitHub Login: @drewbatgit
* Microsoft Alias: **drewbat**

**Comment by Dianoya** [comment]
There are so many bugs and glitches that anyone who writes music applications are disappointed. I already regret that I climbed entirely UWP. :-( It's no wonder that there are almost no musical applications - only toys.

**Comment by Dianoya** [comment]
I hope that a lot of activity in writing problems will cause Microsoft to stir. :-)

**Comment by Noemata** [comment]
This issue is in a hopelessly neglected state.  All the devs that should be working on this within Microsoft are either purposely disregarding this issue (have directly contacted all of them) given the dozens of related postings since 2015, or Microsoft management has decided Music composition/creation under UWP is irrelevant.


Either way, it's clear this problem will never be resolved.  I for one have given up given how many bigger problems remain to be resolved with UWP.  Use the following search terms in combination to see all the related postings: UWP MIDI API BROKEN

The press is also a problem here.  They have been contacted and taken no action to look into this.  So much for oversight by the press.

**Comment by Dianoya** [comment]
> or Microsoft management has decided Music composition/creation under UWP is irrelevant.

I think this is most likely. :-(

**Comment by drewbatgit** [comment]
Hello, GitHub issues in this repository are for feedback specifically about the documentation. It seems like your issue is a developer support request. Here are all of the developer support resources:

- The [Feedback Hub app](https://support.microsoft.com/help/4021566/windows-10-send-feedback-to-microsoft-with-feedback-hub-app) is the right place to lobby for a change, a feature, or to make a suggestion.
- For community assistance with development questions, there are our [forums](https://social.msdn.microsoft.com/Forums/newthread?category=windowsapps&forum=wpdevelop&prof=required), and [StackOverflow](https://stackoverflow.com/questions).
- The [Windows developer support](https://developer.microsoft.com/windows/support) site explains other support options.
- The [Visual Studio developer community](https://developercommunity.visualstudio.com) is available, and responsive. The former User Voice feature is now there on the **Suggest a feature** tab, if you want to lobby for a change, a feature, or to make a suggestion.
- For developer issues, or suspected product bugs, there's [Microsoft Support](https://support.microsoft.com/contactus); a support engineer will look at the repro and see whether the issue is a Microsoft product bug, or something else. If it's a bug with a Microsoft product then the ticket will be free of charge.

If you receive assistance via any support resource, and you believe that information would help us improve the documentation, then please come back and let us know.
