### ISSUE TITLE
How to access scan response data

### ISSUE THREAD

**Issue by dandresky** [MicrosoftDocs/windows-uwp#694]
I have set the watcher scanning mode to active and have confirmed on my peripheral device (sensor based on Nordic SDK) that a SCAN REQUEST was received and that a SCAN RESPONSE was transmitted. However, I am unable to access the SCAN RESPONSE in my UWP application. I tried adding a test to my OnAdvertisementReceived event handler:

BluetoothLEAdvertisementType advertisementType = eventArgs.AdvertisementType;
if(advertisementType == BluetoothLEAdvertisementType.ScanResponse)
{
    rootPage.NotifyUser("Scan Response received", NotifyType.StatusMessage);
}

However, this if statement never evaluates to true. How do I capture and access the scan response data?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 19628977-4829-d46d-d5c5-d4675f3c3f07
* Version Independent ID: b091c621-c26f-e678-2f80-946b68172854
* Content: [Bluetooth Advertisements - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/devices-sensors/ble-beacon)
* Content Source: [windows-apps-src/devices-sensors/ble-beacon.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/devices-sensors/ble-beacon.md)
* Product: **windows**
* GitHub Login: @msatranjr
* Microsoft Alias: **misatran**

**Comment by ntsig** [comment]
I am having the same problem has anybody come up with a solution?

**Comment by w00233051** [comment]
I am having the same problem has anybody come up with a solution?

**Comment by mxi1** [comment]
Hi  @msatranjr,  could you forward this issue to the developer/maintainer of the windows Bluetooth subsystem, so they can consider how to handle it?  I am afraid the maintainer of Microsoft Docs doesn't care this issue.

**Comment by marsukhongduoi** [comment]
Hi @dandresky, have you found a solution for this issue yet?

**Comment by Karl-Bridge-Microsoft** [comment]
Hi @dandresky - This feedback is not specifically about the documentation, but rather a feature/product bug or issue. Please contact the following support channel.

- [Microsoft Support](https://support.microsoft.com/contactus); a support engineer will look at the repro and see whether the issue is a Microsoft product bug, or something else. If it's a bug with a Microsoft product then the ticket will be free of charge.

For future reference, here are all of the developer support resources.

- For developer issues, or suspected product bugs, there's [Microsoft Support](https://support.microsoft.com/contactus); a support engineer will look at the repro and see whether the issue is a Microsoft product bug, or something else. If it's a bug with a Microsoft product then the ticket will be free of charge.
- For product feedback, the [Feedback Hub app](https://support.microsoft.com/help/4021566/windows-10-send-feedback-to-microsoft-with-feedback-hub-app) is the right place to lobby for a change, a feature, or to make a suggestion.
- For community assistance with development questions, there are our [forums](https://social.msdn.microsoft.com/Forums/newthread?category=windowsapps&forum=wpdevelop&prof=required), and [StackOverflow](https://stackoverflow.com/questions).
- The [Windows developer support](https://developer.microsoft.com/windows/support) site explains other support options.
- The [Visual Studio developer community](https://developercommunity.visualstudio.com) is available, and responsive. The former User Voice feature is now there on the **Suggest a feature** tab, if you want to lobby for a change, a feature, or to make a suggestion.

If you receive assistance via any support resource, and you believe that information would help us improve the docs, then please come back and let us know.
