### ISSUE TITLE
On Apache server.

### ISSUE THREAD

**Issue by Nandajit** [MicrosoftDocs/windows-uwp#715]
give the configuration for apache server.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3eebf940-9282-41a2-f236-55984ff76aeb
* Version Independent ID: a1b3c572-c6ba-eff7-637d-cbcb20801c57
* Content: [Create an App Installer file with Visual Studio - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/packaging/create-appinstallerfile-vs)
* Content Source: [windows-apps-src/packaging/create-appinstallerfile-vs.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/packaging/create-appinstallerfile-vs.md)
* Product: **windows**
* GitHub Login: @ridomin
* Microsoft Alias: **rmpablos**

**Comment by the-jedi-code** [comment]
+1

**Comment by birbilis** [comment]
at https://docs.microsoft.com/el-gr/windows/uwp/packaging/troubleshoot-appinstaller-issues it writes:

Files not accessible

When installing from an HTTP endpoint, it is important to verify that all files are accessible with the correct MIME type. The easiest method to verify these files is by following the links provided in the HTML page generated by Visual Studio. You must check these files:

    .appinstaller file, available as an application/xml
    .appx and .appxbundle files, available as application/vns.ms-appx

**Comment by mcleanbyron** [comment]
Thanks for taking the time to let us know about this and we sincerely apologize for the delayed response. 

Due to the sheer volume of feedback in our repo, we are currently prioritizing new Issues. If you believe your feedback is still actionable, let us know either directly in this thread or by filing a new issue by using the Feedback control at the bottom of [the Installing Windows 10 apps from a web page article](https://docs.microsoft.com/en-us/windows/msix/app-installer/installing-windows10-apps-web). 

Though the issue will be marked as closed, I will monitor any replies that come afterwards so feel free to treat this like an open Issue. Thank you.
