### ISSUE TITLE
No mention of api/networking/ipv4config

### ISSUE THREAD

**Issue by Snipsnoop** [MicrosoftDocs/windows-uwp#717]
Bit silly there is no mention of ipv4config.

Can be found at api/networking/ipv4config
Which is real handy for changing IP and switch between DHCP. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ae1ab644-ee7d-3dec-cd0f-cbb1e4d8b6ac
* Version Independent ID: 97eecc36-8e2e-d4c7-1ecb-948e0846bda5
* Content: [Device Portal core API reference - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/debug-test-perf/device-portal-api-core)
* Content Source: [windows-apps-src/debug-test-perf/device-portal-api-core.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/debug-test-perf/device-portal-api-core.md)
* Product: **windows**
* GitHub Login: @PatrickFarley
* Microsoft Alias: **pafarley**

**Comment by PatrickFarley** [comment]
Hi Snipsnoop, 
Thanks for your feedback. I will reach out to a feature PM and see if there is any case against documenting ipv4config here.

**Comment by snobu** [comment]
Should be fine to just link to this page -
https://docs.microsoft.com/en-us/windows/uwp/debug-test-perf/device-portal-api-core#set-a-static-ip-address-ipv4-configuration

However, please add an example for a `NetworkConfiguration` request payload for both a static IP address and DHCP, since it's not obvious how that looks like.

**Comment by PatrickFarley** [comment]
I added ipv4config to that doc a while ago, as you can see. But snobu's request is new

**Comment by snobu** [comment]
What I'm really after is a sample request that sets an interface to DHCP. Sending IPAddress as null doesn't cut it.

E.g.

```
{
    AdapterName = "{xxx-xxx-xxx-xxx}",
    IPAddress = null
};
```

**Comment by snobu** [comment]
So, okay, looks like this is all you need:

```csharp
    object DhcpNetworkConfiguration = new
    {
        AdapterName = "{XXXXXX-XXXX-XXXX-XXXX-XXXXXXXXX}"
    };
```

You serialize that in a PUT to `/api/networking/ipv4config`, you get back a `200 OK` and you're all set. The interface is now in DHCP.

Since i believe this should be clearly stated in the docs, here's a PR for it - https://github.com/MicrosoftDocs/windows-uwp/pull/1161

**Comment by eliotcowley** [comment]
@snobu Thanks for this! I've approved your pull request so I'm closing this issue.
