### ISSUE TITLE
I still not get payment after few month?

### ISSUE THREAD

**Issue by nguyenthanhliemfc** [MicrosoftDocs/windows-uwp#722]
Sorry because I don't know where to contact support about payment. 
My Payout summary Microsoft Advertise over 100$, Why I still not get my payment. I don't turn on "Payout hold status"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 52b80a63-ba2e-ea74-83d3-c63fa1d4904f
* Version Independent ID: 5e8b56c6-a964-1d5d-c040-55254e582da8
* Content: [Payout summary - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/publish/payout-summary#downloading-payment-transactions)
* Content Source: [windows-apps-src/publish/payout-summary.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/publish/payout-summary.md)
* Product: **windows**
* GitHub Login: @JnHs
* Microsoft Alias: **wdg-dev-content**

**Comment by JnHs** [comment]
Please open a support request at https://developer.microsoft.com/windows/support so that we can look into this for you. (This link is also available in the dashboard, under the question mark icon near the top right corner). From that page, select "Contact us", then choose "Dashboard issue" and Payout".
