### ISSUE TITLE
Does non responsive designed application developed for desktop only can be uploaded in Microsoft Store ?

### ISSUE THREAD

**Issue by buricanu** [MicrosoftDocs/windows-uwp#726]
In this section, we are presented the responsive techniques, but I cannot find anywhere I it's possible to upload a non responsive application developed for desktop only to Microsoft store

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7371c6d4-c3b8-f6ed-dc2c-11e62504adde
* Version Independent ID: 9f674922-6d8b-4293-756f-0036ad9cbcff
* Content: [Responsive design techniques - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/design/layout/responsive-design)
* Content Source: [windows-apps-src/design/layout/responsive-design.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/design/layout/responsive-design.md)
* Product: **windows**
* GitHub Login: @mijacobs
* Microsoft Alias: **mijacobs**

**Comment by mijacobs** [comment]
Thanks for the question, @buricanu! Response design is a recommendation, not a requirement. You can upload an application designed only for the desktop to the Microsoft Store. However, just because an app is only for the desktop doesn't meant it shouldn't be responsive--there are a variety of monitor sizes and resolutions. Also, the user can make the app window smaller and larger.
