### ISSUE TITLE
Is there docs about .idl file?

### ISSUE THREAD

**Issue by moyanming** [MicrosoftDocs/windows-uwp#733]
Hi all,
It seems that the .idl file can't use the standard C++ data types when I [define the interfaces in the .idl file](https://docs.microsoft.com/en-us/windows/uwp/cpp-and-winrt-apis/author-events#create-a-windows-runtime-component-bankaccountwrc). There is an Error when I use the "int" data type (the "Int32" is OK):

MIDL5148	[msg]Classic WinRT IDL constructs cannot be used in Modern WinRT IDL types [context]: [ Procedure 'Add2' ( Interface 'BankAccountWRC.IBankAccount' ) ]	BankAccountWRC	C:\file\temp\BankAccount\BankAccountWRC\BankAccountWRC\BankAccountWRC.idl	10	

Is there docs about the idl file?
Best regards.
![qq 20180629204245](https://user-images.githubusercontent.com/13234209/42093057-a1ed6da6-7bdd-11e8-9147-bd096a8fdd20.jpg)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cbf411b4-9c85-5831-c425-a009d47811e7
* Version Independent ID: 3d0dc3b5-a7da-2755-0a9e-599f39a51acd
* Content: [Author events in C++/WinRT - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/cpp-and-winrt-apis/author-events#create-a-windows-runtime-component-bankaccountwrc)
* Content Source: [windows-apps-src/cpp-and-winrt-apis/author-events.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/cpp-and-winrt-apis/author-events.md)
* Product: **windows**
* GitHub Login: @stevewhims
* Microsoft Alias: **stwhi**

**Comment by stevewhims** [comment]
Hi, @moyanming, thanks for the question. If you're putting MIDL 3.0 into an IDL file, then you must use MIDL 3.0 types, which you'll recognize if you've looked at Common Type System (e.g. .NET) types. So, yes, you'll use Int32 rather than int, for example. MIDL 3.0 is documented here: https://docs.microsoft.com/uwp/midl-3/intro. You may see/hear/read MIDL 3.0 being referred to as "Modern IDL", but that's not its official name. Its official name is MIDL 3.0. :) And it's the content of the IDL file, and the command-line switches passed to the MIDL compiler tool, that determine whether the contents of the IDL file are considered to be to classic MIDL or MIDL 3.0. There are also plenty of examples of MIDL 3.0 in practical use in the C++/WinRT docs here: https://docs.microsoft.com/windows/uwp/cpp-and-winrt-apis/index. Regards, Steve.

**Comment by moyanming** [comment]
Hi @stevewhims,
Thank you for your answers.

Best regards.

**Comment by stevewhims** [comment]
@moyanming, I'll go ahead and close this issue now since it's been a while and it feels resolved. Please reopen if I made a mistake in closing. ~Steve
