### ISSUE TITLE
2 app services

### ISSUE THREAD

**Issue by dongle-the-gadget** [MicrosoftDocs/windows-uwp#745]
Can I use 2 app services to communicate with 2 apps. Such as in app 1 it sends 'Hello from 1!' and that shows in App 2's UI and when App 2 send 'Hello from 2!', it does the same with App 1's UI.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 728fa4a8-ade5-b31a-c07f-de82f2402a5b
* Version Independent ID: af5243e9-37a7-ed2f-a535-ce3ba3779b79
* Content: [Create and consume an app service - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/launch-resume/how-to-create-and-consume-an-app-service)
* Content Source: [windows-apps-src/launch-resume/how-to-create-and-consume-an-app-service.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/launch-resume/how-to-create-and-consume-an-app-service.md)
* Product: **windows**
* GitHub Login: @TylerMSFT
* Microsoft Alias: **twhitney**

**Comment by eliotcowley** [comment]
Hi @superkid200, sorry for the delayed response. Are you talking about having two different apps and two different app services within the same project? I don't see why you wouldn't be able to do this, if you also had two different app service providers, one for each app service. If you wanted to have an app call an app service in a different project, I believe you can do that as well, since that's the scenario described in the intro paragraph:

"An app service runs as a background task in the host app and can provide its service to other apps. For example, an app service might provide a bar code scanner service that other apps could use. Or perhaps an Enterprise suite of apps has a common spell checking app service that is available to the other apps in the suite."

So you could create a project with an app service provider and an app service, then create a separate project with a client app, and then run both apps so they can communicate. Does that make sense? Maybe it would be worth creating a doc about it?

**Comment by eliotcowley** [comment]
Closing due to lack of response. @superkid200 please feel free to re-open if you're still having this issue.
