### ISSUE TITLE
No example of BackgroundActivatedEventArgs.TaskInstance.Task.Name in the the Background Activation Sample.

### ISSUE THREAD

**Issue by ceituna** [MicrosoftDocs/windows-uwp#758]
The document says "If your app has multiple background tasks, the Background Activation Sample shows how you can use BackgroundActivatedEventArgs.TaskInstance.Task.Name to identify which task is being initiated.", but I can't find an example in any of the C# files in the Background Activation Sample. I would expect something in OnBackgroundActivated in SampleConfiguration.cs.

Also, the documentation is lacking info about what to do with regards to task entry points.
I also think it would be more helpful to have code examples in the document itself instead of just pointing to some sample that might not be in sync with what's mentioned in the docs. 😉

Thanks in advance! 👍

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 17939b8f-6356-dffa-2968-9df0d7be6607
* Version Independent ID: 520af202-2267-aba5-0821-1e91f7e58093
* Content: [Convert an out-of-process background task to an in-process background task - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/launch-resume/convert-out-of-process-background-task)
* Content Source: [windows-apps-src/launch-resume/convert-out-of-process-background-task.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/launch-resume/convert-out-of-process-background-task.md)
* Product: **windows**
* GitHub Login: @TylerMSFT
* Microsoft Alias: **twhitney**

**Comment by stevewhims** [comment]
Hi, @ceituna, thanks for raising this issue. In fact, the sample's OnBackgroundActivated passes the `args` object's task instance to BackgroundActivity.Start, which passes the same task instance to BackgroundActivity.Run, which accesses .Task.Name on that task instance object. So the full chain is in fact accessing BackgroundActivatedEventArgs.TaskInstance.Task.Name in order to "identify which task is being initiated".

Do you still feel that the illustrative code is out of sync with the content of the topic? I think it's helpful to choose either code examples inline in the topic, OR a sample app, rather than both. The in-topic code is usually just to show very targeted patterns. The sample app is a more rounded and applied scenario. But I think that duplicating code in two places is undesirable.

Regarding "the documentation is lacking info about what to do with regards to task entry points". Do you mean this topic, or the background tasks documentation in general? Could you give me details around which topics are missing which info?

Many thanks!
Steve

**Comment by ceituna** [comment]
Hi @stevewhims , thank you for your reply.
I understood the flow of the chain and that the task instance gets passed through to the Run method, but I was expecting something in OnBackgroundActivated like a switch statement to identify the task and then choose what to do next. But I guess just passing the task instance to the Run method and writing the task name to the debug console is enough of an example of identifying the task. It leaves the specific implementation of how to choose what to do with that info to the reader which is ok in hindsight I guess.

I agree with you about duplicate code in this scenario.

As for my comment on task entry points, I missed this part of the code in the sample in the BackgroundTaskRegistration method:
`if (taskEntryPoint != null)`
`{`
`               // If you leave the TaskEntryPoint at its default value, then the task runs`
`               // inside the main process from OnBackgroundActivated rather than as a separate process.`
`                builder.TaskEntryPoint = taskEntryPoint;`
`}`
So that's clear for me now.

This issue can thus be closed.

Thanks again and keep up the good work! I love the new MS docs site! 👍

**Comment by stevewhims** [comment]
Great! Thanks, @ceituna! :) ~Steve
