### ISSUE TITLE
Replace package

### ISSUE THREAD

**Issue by OsDelToro** [MicrosoftDocs/windows-uwp#761]
Is there a way to replace a package? When I submit the version let say 1.2.3, but I found a bug and to fix in the same build and replace, there is no way to upload or replace the 1.2.3 build (2) because the store say the version 1.2.3 was already uploaded even after removing it. Is there a way to replace a package without increasing the version number? or is there a way to use build numbers like 1.2.3.45678?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0098ee34-7905-a879-190b-10f783f638a6
* Version Independent ID: beb7fc7d-233c-5a15-a9a6-ffe86639527c
* Content: [Upload app packages - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/publish/upload-app-packages)
* Content Source: [windows-apps-src/publish/upload-app-packages.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/publish/upload-app-packages.md)
* Product: **windows**
* GitHub Login: @JnHs
* Microsoft Alias: **wdg-dev-content**

**Comment by JnHs** [comment]
You do need to increment the package number when uploading a new package. (You can upload multiple packages with the same version number, but they must have different architectures. The full identity for each package must be unique.) Incrementing the version number is what lets the Store know that there is a new version that should be delivered to customers on your previous version, so in your scenario (fixing a bug) you would definitely want to do that, so that we can make sure your customers get updated to the new version. For more about package version numbering, see https://docs.microsoft.com/en-us/windows/uwp/publish/package-version-numbering
