### ISSUE TITLE
Store app listing "People also like" section should be removed 

### ISSUE THREAD

**Issue by nielscup** [MicrosoftDocs/windows-uwp#769]
I recently updated the Windows Store listing of one of my apps when I saw the "People also like" section right above my own apps screen shots, very distracting and disturbing. I am trying to sell a business app and the first thing I see in my store listing are pictures of Britney Spears, Nicki Minaj etc. before my own screenshots. This is absolutely ridiculous. I was also running an app campaign for one of my Windows apps. My ad was clicked very often but never got installed, I now know why: people go to my app's listing page and the first thing they see is other apps. So I stopped the ad campaign and am spending the money on my iOS and Android campaigns.

The "People also like" section HAS TO BE REMOVED or at least moved to the very bottom of the page. People have already clicked an app so they want to see that app and not something else. I can't add a link to my Windows app anywhere because I don't want people to see Britney Spears and Nicki Minaj when they expect to see my app. Save the "People also like" section for the search- or category page.

**Comment by JnHs** [comment]
Thanks for sharing these comments. I've passed them along to the Store team, and was able to confirm that if the customer hasn't acquired the app, the "People also like" section is shown after the screenshots in the web listing, not before them. You can confirm this by looking at an app in the Store that you don't own. If the customer owns the app already then the "People also like" is shown higher up. Also, since this is product feedback, you may want to leave feedback at https://wpdev.uservoice.com/ (where other people can also see and/or upvote it).
