### ISSUE TITLE
Images

### ISSUE THREAD

**Issue by Shannarra** [MicrosoftDocs/windows-uwp#782]
The images captured and saved could not be opened.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 24369830-1467-4392-7f21-3721c8953bcb
* Version Independent ID: 2e982ac4-1dcf-554d-a3c5-2e6b367a5b6e
* Content: [Basic photo, video, and audio capture with MediaCapture - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/audio-video-camera/basic-photo-video-and-audio-capture-with-mediacapture)
* Content Source: [windows-apps-src/audio-video-camera/basic-photo-video-and-audio-capture-with-MediaCapture.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/audio-video-camera/basic-photo-video-and-audio-capture-with-MediaCapture.md)
* Product: **windows**
* GitHub Login: @drewbatgit
* Microsoft Alias: **drewbat**

**Comment by drewbatgit** [comment]
Can you provide some more details about the issue you are experiencing? The code in this article has worked for other developers, so more information is needed in order to diagnose your issue.

**Comment by drewbatgit** [comment]
Because this issue has been open for so long with no additional information provided, I am closing the issue. If you still want to pursue an answer for this issue, the community of experts and Microsoft Engineers over at [Microsoft Q&A](https://docs.microsoft.com/en-us/answers/topics/windows-uwp.html) offer timely answers to a multitude of technical questions surrounding windows-uwp.
