### ISSUE TITLE
ScreenCapture Framepool.Dispose() causes application crash

### ISSUE THREAD

**Issue by oliverluethi** [MicrosoftDocs/windows-uwp#791]
I'm using the new ScreenCapture feature based on the Microsoft sample. On a clean installed VM (newest Windows 10 version) the application crashes while calling `_framepool.Dispose()` in the `StopCaptureInternal()` method of the `ScreenCaptureHelper` class. The Win32 exception is raised in the GraphicsCapture.dll.

On my development machine everything seems to work fine. I've added the sample code.

Steps to reproduce:

1.) Open the application
2.) Hit "Source" for changing the source
3.) Hit "Source" again and choose another one.
4.) Repeat Step 3.) a few times, after that the application crashes.
5.) Alternatively hit the "Stop" button. It executes the same `StopCaptureInternal()` method.

[ScreenCapture.zip](https://github.com/MicrosoftDocs/windows-uwp/files/2197343/ScreenCapture.zip)

**Comment by ginami** [comment]
Hi @oliverluethi -- can you tell me what page this refers to? The URL will help me locate the right author to respond. Thank you!

**Comment by oliverluethi** [comment]
@ginami This is the [sample](https://docs.microsoft.com/en-us/windows/uwp/audio-video-camera/screen-capture) I mentioned.

**Comment by eliotcowley** [comment]
Hi @oliverluethi, according to the feature team, screen capture should work fine in VMs, so that's weird that you're having this issue. However, there are several bug fixes coming in the next Windows update, so I would try getting on an Insider build or waiting until the next SDK. I would also contact [Windows developer support](https://developer.microsoft.com/windows/support); there are lots of knowledgeable people on there that can help.
