### ISSUE TITLE
Resolution

### ISSUE THREAD

**Issue by v01pe** [MicrosoftDocs/windows-uwp#792]
I'd love to see the resolution limit mentioned here. Took ma a few days of trial and error and a post to the forums to find out, that using 4k resolution is not possible for UWP games right now. I didn't see this mentioned anywhere in the documentation. I also don't understand why this limit there in the first place.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cadac27a-0221-3d25-65a2-6f52cc1adf7f
* Version Independent ID: 2c90b166-8a59-15b5-dd8a-63a840a34d88
* Content: [System resources for UWP apps and games on Xbox One - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/xbox-apps/system-resource-allocation)
* Content Source: [windows-apps-src/xbox-apps/system-resource-allocation.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/xbox-apps/system-resource-allocation.md)
* Product: **windows**
* GitHub Login: @mtoepke
* Microsoft Alias: **mstahl**

**Comment by mattwojo** [comment]
Thank you for taking the time to let us know about this issue. Apologies for the delayed response. Due to the volume of feedback in our content, we are currently prioritizing new issues. 

If you believe your feedback still requires an update to the documentation, please let us know either directly in this thread, by filing a new issue, or by filing a [Pull Request ](https://github.com/MicrosoftDocs/windows-uwp/pulls) with your recommended updates.

Though the Issue will be marked as closed, we will still receive replies and are able to reopen the issue if necessary. 

Thanks again for taking the time to contribute.

**Comment by v01pe** [comment]
> If you believe your feedback still requires an update to the documentation, please let us know either directly in this thread, by filing a new issue, or by filing a [Pull Request ](https://github.com/MicrosoftDocs/windows-uwp/pulls) with your recommended updates.

Since this issue was 2 years old, I have no idea, if the 4K limitation still exists on UWP. If yes, it would still be good to know on that page.
