### ISSUE TITLE
Intellisense doesn't work for some WinRT types.

### ISSUE THREAD

**Issue by Gavin-Williams** [MicrosoftDocs/windows-uwp#797]
Uri testUri{ L"http://www.contoso.com" };
		WINRT_ASSERT(testUri.ToString() == L"http://www.contoso.com/");

When i type the above code ToString() isn't suggested, in fact nothing is after testUri.

Intellisense: 'No members available'

Edit: I notice that some methods are visible in other types. For example, the Visual type in UI.Composition shows via intellisense.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2a12e6aa-e62e-3602-5436-00325ee9e045
* Version Independent ID: 8a769921-26b7-e1c7-a2f9-dd0dcdcb16b0
* Content: [Consume APIs with C++/WinRT - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/cpp-and-winrt-apis/consume-apis)
* Content Source: [windows-apps-src/cpp-and-winrt-apis/consume-apis.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/cpp-and-winrt-apis/consume-apis.md)
* Product: **windows**
* GitHub Login: @stevewhims
* Microsoft Alias: **stwhi**

**Comment by stevewhims** [comment]
Hi, @Gavin-Williams, thank you for mentioning this issue. It actually is something that we're aware of and working on. Data such as this helps us prioritize efforts. So, in that spirit you could, if you like, bring this up on the [Visual Studio User Voice](https://visualstudio.uservoice.com) feedback website, or in the [Developer Community](https://developercommunity.visualstudio.com). Since this doesn't seem to be something that I can remedy in the documentation, do you mind if I close the issue? Thanks again! ~Steve

**Comment by stevewhims** [comment]
@Gavin-Williams, I'll go ahead and close this issue now since it's been a while and it feels as resolved as we can make it here. Please reopen if I made a mistake in closing. ~Steve

**Comment by Gavin-Williams** [comment]
Yeah no worries, if you're aware of it already, then that's OK. Thanks.
