### ISSUE TITLE
Code not work!

### ISSUE THREAD

**Issue by dongle-the-gadget** [MicrosoftDocs/windows-uwp#798]
I hardly can see this works!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d156d985-2791-6521-331c-8d5ac9283f0e
* Version Independent ID: 794ddc4b-6660-8008-29fd-d4b696541b87
* Content: [Display a splash screen for more time - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/launch-resume/create-a-customized-splash-screen#essential-code-for-an-extended-splash-screen-class)
* Content Source: [windows-apps-src/launch-resume/create-a-customized-splash-screen.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/launch-resume/create-a-customized-splash-screen.md)
* Product: **windows**
* GitHub Login: @TylerMSFT
* Microsoft Alias: **twhitney**

**Comment by ginami** [comment]
Hi @superkid200 -- can you be more specific about your problems with the code? Thank you!

**Comment by dongle-the-gadget** [comment]
I want to customize the Splash Screen with XAML and delay it for 3 seconds. But the app navigated to the first page in the first place!

**Comment by knicholasa** [comment]
Thanks for reaching out with your feedback. You'll find quicker support by consulting our developer support resources. For community assistance with development questions I recommend that you ask on our [forums](https://social.msdn.microsoft.com/Forums/newthread?category=windowsapps&forum=wpdevelop&prof=required) or [StackOverflow](https://stackoverflow.com/questions). Otherwise, please see [the developer support page](https://developer.microsoft.com/windows/support) for your support options. If you get assistance through these other resources and believe that information would help us improve the docs, please come back and let us know.
