### ISSUE TITLE
Is this still available on 10.0.17134.4056

### ISSUE THREAD

**Issue by mslade-c4** [MicrosoftDocs/windows-uwp#799]
From https://docs.microsoft.com/en-us/windows/uwp/xbox-apps/uwp-remoteinput-api

Is this api endpoint 'ext/remoteinput' still available on 10.0.17134.4056?

My attempt to make a connection to the websocket just hangs.

**Comment by mattwojo** [comment]
Thank you for taking the time to let us know about this issue. Apologies for the delayed response. Due to the volume of feedback in our content, we are currently prioritizing new issues. 

If you believe your feedback still requires an update to the documentation, please let us know either directly in this thread, by filing a new issue, or by filing a [Pull Request ](https://github.com/MicrosoftDocs/windows-uwp/pulls) with your recommended updates.

Though the Issue will be marked as closed, we will still receive replies and are able to reopen the issue if necessary. 

Thanks again for taking the time to contribute.
