### ISSUE TITLE
"PanePosition" property link is incorrect

### ISSUE THREAD

**Issue by ghost** [MicrosoftDocs/windows-uwp#811]
In the first line of the "Pane" section the link navigates to "PaneFooter" property.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 745ab6c5-cfbe-a56f-dccd-ab55123f9223
* Version Independent ID: 54455a9f-a92f-e462-558d-78fb696dba8c
* Content: [Navigation view - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/design/controls-and-patterns/navigationview#related-topics)
* Content Source: [windows-apps-src/design/controls-and-patterns/navigationview.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/design/controls-and-patterns/navigationview.md)
* Product: **windows**
* GitHub Login: @serenaz
* Microsoft Alias: **sezhen**

**Comment by Silic0nS0ldier** [comment]
I think `PanePosition` may in itself be a mistake too. Unless there was an API change (seems likely for documentation of pre-release content).

Anyway, should be `PaneDisplayMode` which accepts an enum value from `NavigationViewDisplayMode`.
Values are `Auto`, `Left`, `Top`, `LeftCompact`, `LeftMinimal` btw. I suggest replacing "Left" with "Side" if possible since the `FlowDirection` property affects it.

**Comment by serenaz** [comment]
Removed the faulty link - thanks for the catch! `PanePosition` is not a mistake; take a look at the code example!
