### ISSUE TITLE
BluetoothLEAdvertisementWatcher Received notifications stop 

### ISSUE THREAD

**Issue by PTmv** [MicrosoftDocs/windows-uwp#812]
My UWP application runs in RPI 3 as a BLE GATT client. When started, the BluetoothLEAdvertisementWatcher correctly detects advertisements from the peripheral BLE devices to handle in its Received event handler. But persistently after about one hour the advertisements stop to be detected despite that I manually start the peripheral devices advertising.   I tried to solve this problem by looking at the BLE filters settings, etc. but nothing worked. Finally I made an application based on the BluetoothAdvertisement Scenario1_Watcher sample code and set up a timer to trace the BluetoothLEAdvertisementWatcher status. Even this simple application continued to show exactly the same problem. After the BluetoothLEAdvertisementWatcher stopped detecting advertisements, on a timer event I verified the BluetoothLEAdvertisementWatcher status. The status was still "Started".  No useful information was shown in the watcher object properties to help finding the reason for this behavior. Only a complete RPI power OFF-ON can reset the BLE stack to a working state and I have to restart my application in order to start detecting the peripheral devices advertisements for a while. Please advise me how to solve this problem.

Here is an update: the above described problem does not happen with the Dragonboard 410C.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 19628977-4829-d46d-d5c5-d4675f3c3f07
* Version Independent ID: b091c621-c26f-e678-2f80-946b68172854
* Content: [Bluetooth Advertisements - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/devices-sensors/ble-beacon)
* Content Source: [windows-apps-src/devices-sensors/ble-beacon.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/devices-sensors/ble-beacon.md)
* Product: **windows**
* GitHub Login: @msatranjr
* Microsoft Alias: **misatran**

**Comment by ljfischer** [comment]
Ive seen this same thing.

**Comment by Karl-Bridge-Microsoft** [comment]
Hi @ljfischer - This is not a developer doc issue, please try to find assistance from one of the following:

- For developer issues, or suspected product bugs, there's [Microsoft Support](https://support.microsoft.com/contactus); a support engineer will look at the repro and see whether the issue is a Microsoft product bug, or something else. If it's a bug with a Microsoft product then the ticket will be free of charge.
- The [Feedback Hub app](https://support.microsoft.com/help/4021566/windows-10-send-feedback-to-microsoft-with-feedback-hub-app) is the right place to lobby for a change, a feature, or to make a suggestion.
- For community assistance with development questions, there are our [forums](https://social.msdn.microsoft.com/Forums/newthread?category=windowsapps&forum=wpdevelop&prof=required), and [StackOverflow](https://stackoverflow.com/questions).
- The [Windows developer support](https://developer.microsoft.com/windows/support) site explains other support options.
- The [Visual Studio developer community](https://developercommunity.visualstudio.com) is available, and responsive. The former User Voice feature is now there on the **Suggest a feature** tab, if you want to lobby for a change, a feature, or to make a suggestion.

If you receive assistance via any support resource, and you believe that information would help us improve the docs, then please and let us know through this issue.
