### ISSUE TITLE
Package using a normal UWP project

### ISSUE THREAD

**Issue by dongle-the-gadget** [MicrosoftDocs/windows-uwp#816]
How can I package my app using Blank App (Universal Windows)?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f9f4864c-3cf6-a957-dd26-c16cb4a3015e
* Version Independent ID: c9543586-cf91-3c13-50e0-1837cf4138a4
* Content: [Package an app by using Visual Studio (Desktop Bridge) - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/porting/desktop-to-uwp-packaging-dot-net#first-prepare-your-application)
* Content Source: [windows-apps-src/porting/desktop-to-uwp-packaging-dot-net.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/porting/desktop-to-uwp-packaging-dot-net.md)
* Product: **windows**
* GitHub Login: @normesta
* Microsoft Alias: **normesta**

**Comment by normesta** [comment]
Hello - the recommended path forward is to use the Windows Application Packaging project. Before the Windows Application Packaging project was introduced, folks had to use a UWP blank app project (in most cases a JavaScript-based version of the UWP Blank app). However, that process was pretty complicated. To help folks who were working with solutions that contained that JavaScript-based UWP project, we kept those instructions online (along with the Windows Application Packaging Project) instructions for about a year after the Windows Application Packaging Project was introduced. Do you have a specific requirement to use a Blank App (Universal Windows) to package your win32 app?

**Comment by dongle-the-gadget** [comment]
No, but I see in many samples in GitHub, most samples used that kind of project, before Windows Application Packaging Project was introduced.

**Comment by normesta** [comment]
Hi superkid200 - Yes, using a UWP project to package a win32 app use to be the approach that our docs advocated. After the Windows Application Packaging project was introduced, we kept the guidance for using a UWP project side-by-side with the guidance for using the new Windows Application Packaging project. Via GitHub history, you can see that guidance in this version of the topic - https://github.com/MicrosoftDocs/windows-uwp/blob/dfd6f0f9a9a711c839c5731bcbf00eec018e7132/windows-apps-src/porting/desktop-to-uwp-packaging-dot-net.md.
After the new packaging project was out for a while, we removed the guidance for stand-alone UWP because that is no longer the supported approach.  Unfortunately, there are still a lot of samples in the wild that have the old UWP packaging project approach.
