### ISSUE TITLE
Outdated API?

### ISSUE THREAD

**Issue by JunielKatarn** [MicrosoftDocs/windows-uwp#832]
The type IAsyncAction in 'Write a coroutine' seems wrong.
According to this link (), it doesn't have a `.get()` method.

How do I get the describe behavior from such action object?
Also, what is `winrt::init_paramenter(https://docs.microsoft.com/en-us/uwp/api/windows.foundation.iasyncaction)` for?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a087153a-b34a-b9fc-0ba6-e96d14764455
* Version Independent ID: 4db9d519-6a9d-a8f9-bd58-f67b32cd8548
* Content: [Concurrency and asynchronous operations with C++/WinRT - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/cpp-and-winrt-apis/concurrency#write-a-coroutine)
* Content Source: [windows-apps-src/cpp-and-winrt-apis/concurrency.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/cpp-and-winrt-apis/concurrency.md)
* Product: **windows**
* GitHub Login: @stevewhims
* Microsoft Alias: **stwhi**

**Comment by stevewhims** [comment]
Yes, this is an important point. I have just updated both topics that you mention in order to add clarification. I expect these changes to be live within 24 hours, but until then here is the info that I added:

The **get** function exists on the C++/WinRT projection type **winrt::Windows::Foundation::IAsyncAction**, so you can call the function from within any C++/WinRT project. You will not find the function listed as a member of the [**IAsyncAction**](/uwp/api/windows.foundation.iasyncaction) interface, because **get** is not part of the application binary interface (ABI) surface of the actual Windows Runtime type **IAsyncAction**.

> How do I get the describe behavior from such action object?

If you use the code in the topic (and your own code based on the same patterns and based on the understanding of the concepts in the topic), then you will get the described behavior.

> what is winrt::init_paramenter?

winrt::init_parameter, right? I don't see that token in any of the SDKs that I have installed. I'm curious where you've seen that.

Thanks!
~Steve

**Comment by stevewhims** [comment]
@JunielKatarn, I'll go ahead and close this issue now since it's been a while and it feels resolved. Please reopen if I made a mistake in closing. ~Steve
