### ISSUE TITLE
Using DirectX in a UWP app

### ISSUE THREAD

**Issue by sjointer** [MicrosoftDocs/windows-uwp#838]
In the note above, it's stated that "...you can create a UWP app with C# and XAML that uses DirectX, if you wrap the DirectX calls in a separate Windows Runtime metadata file..." Do I create the DirectX calls as a C++ runtime component, or a C# runtime component?  Could you please expand on this note?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 755df31e-5686-f3d1-b589-d0f064587701
* Version Independent ID: 8d641a01-a27d-118e-7438-a41aa0c24c7d
* Content: [DirectX and XAML interop - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/gaming/directx-and-xaml-interop#xaml-and-directx)
* Content Source: [windows-apps-src/gaming/directx-and-xaml-interop.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/gaming/directx-and-xaml-interop.md)
* Product: **windows**
* GitHub Login: @mtoepke
* Microsoft Alias: **mtoepke**

**Comment by mtoepke** [comment]
Thanks for your question sjointer.

Create a C++ Windows runtime component, and make your C++ DirectX calls from there.  Then that component can expose runtime calls to your main C# program.

There's also some XAML/DirectX interop guidance here: https://docs.microsoft.com/en-us/windows/uwp/gaming/directx-and-xaml-interop.

**Comment by sjointer** [comment]
Thanks for the answer.  Be aware that the link you provided directs back to the same page that I posted my question on.

**Comment by Gavin-Williams** [comment]
Great idea, why doesn't Microsoft write DirectX as proper Window Runtime code so that we don't need to write the wrappers? That would surely be a lot easier for everybody and the end result would probably be optimal. And wouldn't that be the correct design philosophy for where MS are going with UWP?

Until Microsoft actually provide such interoperation between DirectX and C# I recommend using SharpDX which gives you full DirectX functionality in a C# code style.

https://www.nuget.org/packages?q=Tags%3A%22SharpDX%22

https://github.com/sharpdx/SharpDX

**Comment by mtoepke** [comment]
Thanks for the links and recommendation @Gavin-Williams.

**Comment by Gavin-Williams** [comment]
I should note that SharpDX will be coming to and end soon, as the creator doesn't have time to manage commits, so there will be no managed wrapper for DirectX within a couple of years.
