### ISSUE TITLE
Are there any samples implementing background tasks using C++/WinRT?

### ISSUE THREAD

**Issue by MihaiUdrea** [MicrosoftDocs/windows-uwp#839]
I've found samples about registering background task using C++/WinRT code but how about implementing the actual task in C++/WinRT.

Thank you.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1e9daac3-b416-9a90-39ff-55ada1d9d461
* Version Independent ID: fecefe30-8a56-5da4-1123-7e822d96ae8a
* Content: [Create and register an out-of-process background task - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/launch-resume/create-and-register-a-background-task)
* Content Source: [windows-apps-src/launch-resume/create-and-register-a-background-task.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/launch-resume/create-and-register-a-background-task.md)
* Product: **windows**
* GitHub Login: @TylerMSFT
* Microsoft Alias: **twhitney**

**Comment by stevewhims** [comment]
Hi, @MihaiUdrea, I'm sorry for the delay in getting back to you. You raise an important question. Providing illustrative code is an ongoing workstream, and it's driven by priorities (those priorities are in turn driven by customer input such as this issue, and the fact that you're asking about this). What I'll do here is to make a record of this ask, and put it onto my backlog. Since I don't have a schedule that I can share around when a C++/WinRT sample app that implements a background task might be published, I'll close this issue for the time being. We can revisit progress at some time in the future.

Thanks again. ~Steve

**Comment by godlytalias** [comment]
I have a sample here for the same, https://github.com/godlytalias/Win32_Samples/tree/main/BackgroundTask
