### ISSUE TITLE
Need To Include Info on CoreWindow.CharacterReceived

### ISSUE THREAD

**Issue by jlinstrum** [MicrosoftDocs/windows-uwp#846]
This is an excellent article, but there needs to be somewhere where all of this information is integrated with hints on how to use the CoreWindow events (such as CoreWindow.CharacterReceived), and when to use CoreWindow instead of attaching to a UIElement keyevent.  CoreWindow.CharacterReceived is pretty much the only way in UWP to receive keyboard inputs as Unicode characters (super important for globalization), but it took me many hours of web searches and finally reaching out for help on the msdn forum to figure this out. I haven't found the CoreWindow.CharacterReceived method mentioned anywhere but in it's class documentation, which is a shame because it's very useful.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 32569952-2610-a154-ae03-20dfdf09476a
* Version Independent ID: 857856a1-3984-ce9d-3aaa-d41fda28a845
* Content: [Keyboard events - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/design/input/keyboard-events#related-articles)
* Content Source: [windows-apps-src/design/input/keyboard-events.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/design/input/keyboard-events.md)
* Product: **windows**
* GitHub Login: @Karl-Bridge-Microsoft
* Microsoft Alias: **kbridge**

**Comment by Karl-Bridge-Microsoft** [comment]
Thanks for submitting your feedback and I apologize for the delayed response. I went ahead and created an internal work item (with a link to this issue) to address your concerns and suggestions. 

Due to the age of this issue and as the timeframe for addressing this work item is unknown, I will close this issue and try to notify you when any related updates go live. 

Though the Issue will be marked as Closed, I will monitor any subsequent replies. Many thanks!
