### ISSUE TITLE
Compiler errors using winrt::make<>

### ISSUE THREAD

**Issue by schlzber** [MicrosoftDocs/windows-uwp#849]
When I use the apropriate call to winrt::make&lt;&gt; in the constructor of my class I get compiler errors (translated from German):

musiclibrary.cpp(10): error C2672: "winrt::make": no matching overloaded function found
musiclibrary.cpp(10): error C2974: "winrt::make": invalid template argument for "D", Type expected.
1&gt;c:\program files (x86)\windows kits\10\include\10.0.17713.0\cppwinrt\winrt\base.h(8501): note: See declaration of "winrt::make"

The line in my code is this:

m_Artists = winrt::make&lt;single_threaded_observable_vector&lt;Windows::Foundation::IInspectable&gt;&gt;();

And m_Artists is defined like this:
        public:
		IVector&lt;IInspectable&gt; Artists();
	private:
		IVector&lt;IInspectable&gt; m_Artists;

and in IDL:

		Windows.Foundation.Collections.IVector&lt;IInspectable&gt; Artists{ get; };

Any ideas what I'm missing?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f06f7371-d17a-c3aa-c0f9-795c213c7cdc
* Version Independent ID: 551a7594-9637-4eca-2400-b14a6541ab76
* Content: [XAML items controls; bind to a C++/WinRT collection - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/cpp-and-winrt-apis/binding-collection)
* Content Source: [windows-apps-src/cpp-and-winrt-apis/binding-collection.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/cpp-and-winrt-apis/binding-collection.md)
* Product: **windows**
* GitHub Login: @stevewhims
* Microsoft Alias: **stwhi**

**Comment by stevewhims** [comment]
Hi, @schlzber, thanks for opening this issue: it looks like I need to improve this topic. winrt::make<D> is expecting D to be a type; and the compiler error you're seeing can happen when you supply an identifier or a function as D, instead of a type. Are you using the released version of the SDK (which is 17134), or are you using a later Insider version of the SDK (version 17661 or later)? If you're using 17661 or later, and you're not using the single_threaded_observable_vector class that's provided with the topic, then you'll be using winrt::single_threaded_observable_vector, which is a function. If that's the case then that's consistent with the compiler error. I haven't properly updated the topic to show how to use winrt::single_threaded_observable_vector, because it's still in Preview and hasn't yet been released. But there's info about it in this video: https://www.youtube.com/watch?v=nOFNc2uTmGs&feature=youtu.be&t=1h5m46s.

For folks using the released SDK (version 17134), one thing I forgot to add to the topic is that you need to #include "single_threaded_observable_vector.h" in BookstoreViewModel.h.

I'll go ahead and make these fixes to the topic asap. Please let me know if you're still blocked with the info above.

-Steve

**Comment by schlzber** [comment]
Hello Steve,

thanks for you explanation. I was  using the 17713  Preview SDK. I switched back to the 17134 SDK and included the header and now it works. Thanks. :-)

Daniel

**Comment by stevewhims** [comment]
Great, thanks, Daniel!
