### ISSUE TITLE
Registration and de-registration protocol

### ISSUE THREAD

**Issue by Shenn299** [MicrosoftDocs/windows-uwp#852]
Hi,
on the registration and de-registration protocol schema, in the provisioning step, the companion app sends the DeviceKey to the companionAuth Service, but the deviceKey doesn't  appear next to the AuthKey. The deviceKey is stored on the device, isn't it ? So, why the service needs to get the deviceKey ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cc468ad2-97d4-011a-7155-82db4d495224
* Version Independent ID: 4f211ad7-9278-ebff-3eef-4b1604f0320c
* Content: [Windows Unlock with Windows Hello companion (IoT) devices - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/security/companion-device-unlock#registration-and-de-registration-protocol)
* Content Source: [windows-apps-src/security/companion-device-unlock.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/security/companion-device-unlock.md)
* Product: **windows**
* GitHub Login: @msatranjr
* Microsoft Alias: **misatran**

**Comment by hickeys** [comment]
It looks like your feedback concerns the product itself, rather than the documentation for the product. Unfortunately, GitHub issues in this repo are only used for documentation issues. 

The best way to leave product feedback is through the [Feedback Hub app](https://support.microsoft.com/help/4021566/windows-10-send-feedback-to-microsoft-with-feedback-hub-app). If you return to the documentation page related to this issue and scroll to the bottom, there is a button to **leave feedback about this product**

For completeness' sake, here is a list of developer resources:

- The [Feedback Hub app](https://support.microsoft.com/help/4021566/windows-10-send-feedback-to-microsoft-with-feedback-hub-app) is the right place to suggest or lobby for a change or feature.
- Try our [forums](https://social.msdn.microsoft.com/Forums/newthread?category=windowsapps&forum=wpdevelop&prof=required) and [StackOverflow](https://stackoverflow.com/questions) for community assistance with development questions.
- The [Windows developer support](https://developer.microsoft.com/windows/support) site explains other support options.
- The [Visual Studio developer community](https://developercommunity.visualstudio.com) is helpful and responsive. You can also suggest or lobby for a change or feature by clicking the **report a problem** or **suggest a feature** buttons.
- For developer issues or suspected product bugs, visit [Microsoft Support](https://support.microsoft.com/contactus). A support engineer will determine whether the issue is a Microsoft product bug. If it is, the ticket will be free of charge.

If you receive assistance via any support resource and you believe that information would help us improve the docs, then please let us know or consider submitting a pull request.

Thanks,
Shawn
