### ISSUE TITLE
Any Toast notifications for VB winforms?

### ISSUE THREAD

**Issue by blogcraft** [MicrosoftDocs/windows-uwp#854]
In my company we have a very large 10 year old product built in VB.NET, is there a way to get the win10 apis like toast notifications?

**Comment by mijacobs** [comment]
Hi @blogcraft , 
Is your application using WinForms or WPF? Adding @normesta  and @andrewleader, our cross-compatibility and notifications experts.

**Comment by andrewleader** [comment]
Hey @blogcraft, yes you can use notifications on Windows 10 from Win32 apps! Here's the docs: https://docs.microsoft.com/en-us/windows/uwp/design/shell/tiles-and-notifications/toast-desktop-apps

**Comment by normesta** [comment]
Hello - provided that your application conforms to these guidelines ([Prepare a Package](https://docs.microsoft.com/en-us/windows/uwp/porting/desktop-to-uwp-prepare)), you can use Win10 APIs such as notifications. 
In fact, this topic goes into specifics about what sort of file references you'll need along with a notification code example  [Enhance for Windows 10](https://docs.microsoft.com/en-us/windows/uwp/porting/desktop-to-uwp-enhance).
You'll have to create a package for your app before you can use the APIs. There's guidance here for how to do this [Desktop Bridge](https://docs.microsoft.com/en-us/windows/uwp/porting/desktop-to-uwp-root). 
One thing to note here, is that the process for creating a package will become easier in the coming months as we release enhanced tools for creating packages.

**Comment by andrewleader** [comment]
@normesta you don't need to package your application with Desktop Bridge to use toast notifications.

@blogcraft simply look at the docs I linked. If you want to use additional Windows 10 features, like Live Tiles, location APIs, etc, then you should look into using Desktop Bridge!

**Comment by normesta** [comment]
Hmm. My understanding was that applications required identity to use notifications.  Is that not the case for this specific API? Many APIs do require identity. I was under the impression that this was one of them. It's very hard to get a definitive list of which do and which don't and I actually have not attempted to access notifications in a straight desktop application with no identity.

**Comment by andrewleader** [comment]
I'm the PM owner of toast notifications in Windows, long ago (since Windows 8.1) we created ways for desktop apps (non-WinRT/non-UWP) to send notifications, before the Desktop Bridge days. Our APIs require identity, but we provided a different way to provide that identity. That's how Outlook Win32 has been able to send notifications since the first days of Windows 10.

**Comment by normesta** [comment]
Thanks Andrew. Is your alternative approach to obtaining identity well documented somewhere so that we can point @blogcraft to it?  

The conventional approach that we've been advocating for is to use the Bridge. If there is a better, more convenient approach to getting that identity without having to package an app, and we have that officially documented, I think this would be immensely helpful for folks. We could even showcase this approach in our scenarios as a way to kick the tires on APIs without committing to full app packaging.

**Comment by andrewleader** [comment]
I already linked to it in my first answer: https://docs.microsoft.com/en-us/windows/uwp/design/shell/tiles-and-notifications/toast-desktop-apps

It only works for notifications. It has a full code sample linked for both C# and C++ desktop apps. For anything outside of notifications, Desktop Bridge is the only way to use APIs that require identity.

**Comment by normesta** [comment]
Great. Thank you all! Ok closing issue as it seems we have a path forward for @blogcraft . @blogcraft, if your just planning to use notifications, then you can do that by using the guidance that Andrew provided. If you plan to use most other WinRT APIs, it's best to create an app package for your desktop application, and then use the guidance here (https://docs.microsoft.com/en-us/windows/uwp/porting/desktop-to-uwp-enhance) to set your project up with the right references to use those APIs. Thanks for asking! I learned something from this.
