### ISSUE TITLE
Link to Dev Center Dashboard redirects to partner dashboard

### ISSUE THREAD

**Issue by guillaumecouture** [MicrosoftDocs/windows-uwp#864]
Good afternoon, 

We are trying to assist a customer in completing the above procedure, but we always get redirected to the https://partner.microsoft.com/en-us/dashboard/directory when clicking the link http://developer.microsoft.com/dashboard ... As you can imagine, the detailed procedure does not seem to apply.  Can you please advise of the location of the new procedure to Associate an Azure Active Directory with a Dev Center account / access the developer dashboard ?  Thank you !

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 262768e8-ad91-7af3-1541-4f2d2f9de5ba
* Version Independent ID: cc035cc8-ce25-57c4-2d2d-389451442d98
* Content: [Associate Azure Active Directory with your Dev Center account - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/publish/associate-azure-ad-with-dev-center#feedback)
* Content Source: [windows-apps-src/publish/associate-azure-ad-with-dev-center.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/publish/associate-azure-ad-with-dev-center.md)
* Product: **windows**
* GitHub Login: @JnHs
* Microsoft Alias: **wdg-dev-content**

**Comment by JnHs** [comment]
We have recently changed some URLs but I believe they should be redirecting to the right location - I will investigate this with our team. In the meantime, I'm guessing you are seeing the Directory page because you are not already logged in to the Partner Dashboard. Please be sure to log in with a valid Dev Center account and then try again. I'll leave this issue open so you can let me know if that doesn't work, and I'll respond again if I find out you need to use a different URL or do anything different. We'll be updating the URLs in the help content shortly (but again, I believe they will generally redirect to the right location if you are signed in).

**Comment by guillaumecouture** [comment]
Thank you for the quick response.  I might have forgot to indicate this information, but even signed in using a Dev Account, the settings option is not available. 

Thanks !

**Comment by JnHs** [comment]
That seems strange if you are signed in. Do you see the gear icon in the upper right corner of the dashboard? There should be a "Developer settings" or "Account settings" link here. After you select that you should see "Tenants" in the left menu of the page that appears (as long as you have the Manager permission for the account you're working in). If you aren't able to see this I would suggest opening a support request at http://aka.ms/storesupport so they can help troubleshoot further.

**Comment by JnHs** [comment]
I'm going to close this issue out now. If you have more doc feedback please let us know.
