### ISSUE TITLE
Failed store certification

### ISSUE THREAD

**Issue by fredstoolbox** [MicrosoftDocs/windows-uwp#868]
The nuget packages provided in this article fail to pass the app certification process. ALL dlls in these package failed the store security tests with AppContainer checks. If you need OpenCV, download from the source and build your own with the correct flag.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dada0a82-fb87-4e86-24d2-92dd76f6f7be
* Version Independent ID: 47f02307-a825-d580-0d83-362107fa285a
* Content: [Use OpenCV with MediaFrameReader - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/audio-video-camera/use-opencv-with-mediaframereader)
* Content Source: [windows-apps-src/audio-video-camera/use-opencv-with-mediaframereader.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/audio-video-camera/use-opencv-with-mediaframereader.md)
* Product: **windows**
* GitHub Login: @drewbatgit
* Microsoft Alias: **drewbat**

**Comment by drewbatgit** [comment]
Thanks for the info. I updated the section that recommended installing the Nuget packages to the following: 
"To get started developing quickly, you can include the OpenCV library in a UWP app project by using NuGet packages, but these packages may not pass the app certification process when you submit your app to the Store, so it is recommended that you download the OpenCV library source code and build the binaries yourself before submitting your app. "

Also, it turns out that OpenCV is no longer under active development. So, this whole article may become obsolete at some point. For now, I've added a note that the project is no longer actively supported.
