### ISSUE TITLE
Start Screen Management capability and secondary tiles

### ISSUE THREAD

**Issue by gabrieloria** [MicrosoftDocs/windows-uwp#869]
Hi,

With the Start Screen Management capability I was able to pin the app itself silently like the doc says, but when I tried to pin a secondary tile the confirmation dialog was still displayed, is that the expected behavior?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 30a70676-883b-801e-2f07-881923cb0b96
* Version Independent ID: f968708e-33cd-ba83-fe9a-71672c961044
* Content: [App capability declarations - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/packaging/app-capability-declarations)
* Content Source: [windows-apps-src/packaging/app-capability-declarations.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/packaging/app-capability-declarations.md)
* Product: **windows**
* GitHub Login: @msatranjr
* Microsoft Alias: **misatran**

**Comment by mcleanbyron** [comment]
Our apologies for not responding to this issue sooner, and thanks for reaching out to us. It looks like you have a technical question about how the startScreenManagement capability works instead of direct feedback on the docs. 

For assistance with development questions I recommend that you ask on our [forums](https://social.msdn.microsoft.com/Forums/newthread?category=windowsapps&forum=wpdevelop&prof=required) or [StackOverflow](https://stackoverflow.com/questions). Otherwise, please see [the developer support page](https://developer.microsoft.com/windows/support) for your support options. If you get assistance through these other resources and believe that information would help us improve the docs, please come back and let us know. 

Note that startScreenManagement is a [restricted capability](https://docs.microsoft.com/en-us/windows/uwp/packaging/app-capability-declarations#restricted-capabilities), and as such is not available to most developers.
