### ISSUE TITLE
Ad customization

### ISSUE THREAD

**Issue by dongle-the-gadget** [MicrosoftDocs/windows-uwp#871]
Can I customize my ads by my own way?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b08c6292-c94c-2d95-e800-b14d404879f9
* Version Independent ID: 83029484-dc65-6c17-80f3-e75a6bbc6732
* Content: [Display ads in your app with the Microsoft Advertising SDK - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/monetize/display-ads-in-your-app)
* Content Source: [windows-apps-src/monetize/display-ads-in-your-app.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/monetize/display-ads-in-your-app.md)
* Product: **windows**
* GitHub Login: @mcleanbyron
* Microsoft Alias: **mcleans**

**Comment by mcleanbyron** [comment]
Thanks for reaching out. Can you provide more details and/or examples that explain the scenario you're trying to achieve? If you're asking from the perspective of an app developer, when you use the Microsoft Advertising SDK your app is served banner, interstitial, video, or native ads from one of our [supported ad networks](https://docs.microsoft.com/en-us/windows/uwp/publish/in-app-ads#supported-paid-ad-networks). If you're looking to exercise as much control as possible over the way the ads are integrated into your application, [native ads](https://docs.microsoft.com/en-us/windows/uwp/monetize/native-ads) are likely the best choice.

**Comment by dongle-the-gadget** [comment]
Such as, I wanted to create an Azure advertisement of my own, can I have the option to do that?

**Comment by mcleanbyron** [comment]
As an application developer, no, there is no option for creating your own advertisements. When you use the Microsoft Advertising SDK your app is served ads from one of our [supported ad networks](https://docs.microsoft.com/en-us/windows/uwp/publish/in-app-ads#supported-paid-ad-networks).


If you work for or otherwise represent an ad network and want to investigate your options for partnering with Microsoft to serve ads to developers using our platform, please reach out to our advertising team at aiacare@microsoft.com. For more details, see the section about ad networks on [this page](https://developer.microsoft.com/en-us/windows/ad-monetization-platform). 


I'm closing this issue because there appears to be no actionable feedback on the developer documentation.
