### ISSUE TITLE
about type convertion

### ISSUE THREAD

**Issue by cjw1115** [MicrosoftDocs/windows-uwp#882]
how can I convert a Windows::UI::Xaml::DependencyObject to Windows::UI::Xaml::Controls::TextBlock in cppwinrt.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8a44d893-2ad9-830f-a4d8-908e725432e1
* Version Independent ID: 81a91de0-9c13-7d3a-c680-b45370be492e
* Content: [XAML custom (templated) controls with C++/WinRT - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/cpp-and-winrt-apis/xaml-cust-ctrl)
* Content Source: [windows-apps-src/cpp-and-winrt-apis/xaml-cust-ctrl.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/cpp-and-winrt-apis/xaml-cust-ctrl.md)
* Product: **windows**
* GitHub Login: @stevewhims
* Microsoft Alias: **stwhi**

**Comment by stevewhims** [comment]
Hi, @cjw1115, you can do that like this.

```cppwinrt
// In MainPage.xaml, have the element <TextBlock x:Name="textBlockInMarkup"/>

// MainPage.h
...
void Foo(Windows::UI::Xaml::DependencyObject const& dependencyObject)
{
    auto textBlock{ dependencyObject.as<Windows::UI::Xaml::Controls::TextBlock>() };
    textBlock.Text(L"b");
}

MainPage()
{
    InitializeComponent();

    textBlockInMarkup().Text(L"a");
    Foo(textBlockInMarkup());
}
```

If you're in any doubt that the DependencyObject you have is a TextBlock, then [use try_as](https://docs.microsoft.com/uwp/cpp-ref-for-winrt/windows-foundation-iunknown#iunknowntryas-function) instead of [the as function](https://docs.microsoft.com/uwp/cpp-ref-for-winrt/windows-foundation-iunknown#iunknownas-function). as will throw if the "cast" fails; try_as will return nullptr or false depending which overload you call. I say "cast" in inverted commas because what's really taking place is an IUnknown::QueryInterface.

**Comment by cjw1115** [comment]
So quick response. Thank you very much

As your description, It succeed.

BTW, I try to use reinterept_cast<Windows.UI.Xaml.Controls.TextBlock&>(dependencyObject) in my project, it converted successfully too.

**Comment by stevewhims** [comment]
The reinterpret_cast is interesting, and good to know. Of course, it's a technique that depends on the binary layout of a particular object; and assumptions about that are likely to be thwarted at some point. I now realize that my example is flawed. It was my intention to highlight what's happening in Foo(), but even so I really should have called it like this.

```cppwinrt
Foo(textBlockInMarkup().as<Windows::UI::Xaml::DependencyObject>());
```

As you know, to be super-robust, one should prefer the "as" or "try_as" function over casts or conversions. Because doing so delegates the responsibility of providing the requested interface to the object itself, via the tried-and-trusted (and reliable) mechanism of QueryInterface. As we know, there are many ways that an implementation of IUnknown can deliver a requested interface (which might not even be in the inheritance hierarchy of the class itself). :) ~Steve

**Comment by stevewhims** [comment]
I'll close this issue now, since we resolved it. Thanks! ~Steve
