### ISSUE TITLE
Navigation View bug in narrow mode while extend acrylic into the title bar

### ISSUE THREAD

**Issue by hupo376787** [MicrosoftDocs/windows-uwp#887]
[Enter feedback here]
Hi, I found a bug in narrow mode, while extend to title bar, the scrollviewer may overlay the title bar.
And  [github url](https://github.com/hupo376787/NewNavigationView)

![111](https://user-images.githubusercontent.com/14960168/43958667-c9268ad4-9cde-11e8-8b46-f18acfda1b9b.gif)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 745ab6c5-cfbe-a56f-dccd-ab55123f9223
* Version Independent ID: 54455a9f-a92f-e462-558d-78fb696dba8c
* Content: [Navigation view - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/design/controls-and-patterns/navigationview#scroll-content-under-top-pane)
* Content Source: [windows-apps-src/design/controls-and-patterns/navigationview.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/design/controls-and-patterns/navigationview.md)
* Product: **windows**
* GitHub Login: @serenaz
* Microsoft Alias: **sezhen**

**Comment by YuliKl** [comment]
Hi @hupo376787, thank you for reporting this bug. Drawing into the title bar makes this situation a bit tricky because the control doesn't really know where you expect it to clip. As a workaround, I suggest adding ```Header=" "``` to your NavigationView declaration. The Header helps impose a hard stop on the Content area.

Going forward, we would appreciate your opening any other controls bugs that you encounter directly in the [WinUI repo](https://github.com/Microsoft/microsoft-ui-xaml). You can choose to either [report a bug or request a new feature](https://github.com/Microsoft/microsoft-ui-xaml/issues/new/choose).
