### ISSUE TITLE
App Service Not available

### ISSUE THREAD

**Issue by dongle-the-gadget** [MicrosoftDocs/windows-uwp#890]
App Service is not available in the client app. Here is my code:
&lt;uap3:Extension Category="windows.appExtension"&gt;
          &lt;uap3:AppExtension Name="MathExt"
                             Id="Divide"
                             DisplayName="x/y"
                             Description="Divide"
                             PublicFolder="Public"&gt;
            &lt;uap3:Properties&gt;
              &lt;Service&gt;divideservice&lt;/Service&gt;
            &lt;/uap3:Properties&gt;
          &lt;/uap3:AppExtension&gt;
        &lt;/uap3:Extension&gt;

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f3298b92-cea5-7d7e-c25e-3fd090420eeb
* Version Independent ID: fdb61ad4-a542-db99-bc9c-36c613b86162
* Content: [Create and consume an app extension - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/launch-resume/how-to-create-an-extension#related-topics)
* Content Source: [windows-apps-src/launch-resume/how-to-create-an-extension.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/launch-resume/how-to-create-an-extension.md)
* Product: **windows**
* GitHub Login: @TylerMSFT
* Microsoft Alias: **twhitney**

**Comment by hkhmsft** [comment]
Thanks for taking the time to let us know about this and we sincerely apologize for the delayed response. Due to the sheer volume of feedback in our repo, we are currently prioritizing new Issues. If you believe your feedback is still actionable, let us know either directly in this thread or by filing a new Issue and we’ll work to incorporate the suggestions into the documentation. Though the Issue will be marked as Closed, I will monitor any replies that come afterwards so feel free to treat this like an open Issue. Many thanks!
