### ISSUE TITLE
when_all() method

### ISSUE THREAD

**Issue by sjointer** [MicrosoftDocs/windows-uwp#896]
In the code for GameRenderer::CreateGameDeviceResourcesAsync above, you use a method "when_all()" to await the completion of an entire vector of tasks.  Please is this a method that is part of the project, and, if so, could you point to it's source code?  I couldn't find it anywhere in the C++ documentation for asynchronous programming.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6fbaa3a5-cc6a-7907-660f-282f45956716
* Version Independent ID: 463276d5-0dc7-32d8-5365-e1e6b32170a1
* Content: [Set up - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/gaming/tutorial-game-rendering)
* Content Source: [windows-apps-src/gaming/tutorial-game-rendering.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/gaming/tutorial-game-rendering.md)
* Product: **windows**
* GitHub Login: @joannaleecy
* Microsoft Alias: **joanlee**

**Comment by stevewhims** [comment]
HI, @sjointer, and apologies for the long delay in responding. **concurrency::when_all** is documented here: https://docs.microsoft.com/cpp/parallel/concrt/reference/concurrency-namespace-functions#when_all.

However, as you can see, this topic has changed since you created this issue. The topic now shows C++/WinRT code (and not C++/CX code), so it no longer uses **concurrency::when_all**.

Thanks!
Steve
