### ISSUE TITLE
Page does not explain why OS changes are required to run Visual Studio

### ISSUE THREAD

**Issue by kwebble** [MicrosoftDocs/windows-uwp#910]
I got here from the link that was shown when starting a new project in Visual Studio. This page fails to explain to me why I have to change the operating system settings to run the development tools. That is something I do not expect from GUI design tools and compilers. 

The page includes _Developer Mode replaces the Windows 8.1 requirements for a developer license_. Does the same apply to the developer license of Windows 10, the version I use?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f35d7dc2-a5e9-9f86-7e8a-88e6afe40c99
* Version Independent ID: b57b8c51-e2f6-e5e1-1d93-14f26691bc39
* Content: [Enable your device for development - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/get-started/enable-your-device-for-development)
* Content Source: [windows-apps-src/get-started/enable-your-device-for-development.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/get-started/enable-your-device-for-development.md)
* Product: **windows**
* GitHub Login: @QuinnRadich
* Microsoft Alias: **quradic**

**Comment by QuinnRadich** [comment]
The same does not apply to the developer license of Windows 10. I'll be removing the text that you quoted - now that it's been a couple years since the initial Windows 10 release, I think that information can be de-emphasized. The final section of this article covers the same information for developers for whom it is relevant.

The reason why Developer Mode is necessary is because - when developing a UWP app for Visual Studio - you aren't simply running a set of development tools. When you test an app you wrote, you're running code on your machine that doesn't come from the Microsoft store or another external source you trust.

If you're worried about keeping Developer Mode enabled on your machine but still want to use Visual Studio to write and test apps, you might want to consider using a Virtual Machine as a development environment.

**Comment by kwebble** [comment]
> When you test an app you wrote, you're running code on your machine that doesn't come from the Microsoft store or another external source you trust.

Well, isn't that normal with nearly all software? I only got 1 application from the store. Everything else, browsers, dev tools, database etc., was downloaded from the internet, installed and runs fine without the special mode. 

If I knew up front about the required deep integration between Visual Studio and Windows, I would not have installed it.

I thought about a VM but it requires an additional Windows license.

**Comment by QuinnRadich** [comment]
I assume your machine is currently set to "Sideload Apps." You've installed other apps from trusted external sources, yes, but those apps still all have trusted certificates.

When you're debugging and testing your own code on your machine, you're running uncertified code, hence the need for Developer Mode. It doesn't change anything about your machine other than lifting all restrictions about the programs you can run on it.

As for a VM, you can download a free evaluation version of a Windows dev VM here: https://developer.microsoft.com/windows/downloads/virtual-machines . It's a trial version with a limited lifespan, but it might prove useful nonetheless.

**Comment by kwebble** [comment]
OK, thanks for the explanation and link.
