### ISSUE TITLE
NavigationViewItem in PaneFooter

### ISSUE THREAD

**Issue by daullmer** [MicrosoftDocs/windows-uwp#914]
Is there a NavigationViewItem inside the PaneFooter in the screenshot? The documentation of PaneFooter is explicitly states that you cannot place NavigationViewItems in NavigationView.PaneFooter. Will this change in future version because this is a Preview version of the documentation?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 745ab6c5-cfbe-a56f-dccd-ab55123f9223
* Version Independent ID: 54455a9f-a92f-e462-558d-78fb696dba8c
* Content: [Navigation view - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/design/controls-and-patterns/navigationview#pane)
* Content Source: [windows-apps-src/design/controls-and-patterns/navigationview.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/design/controls-and-patterns/navigationview.md)
* Product: **windows**
* GitHub Login: @serenaz
* Microsoft Alias: **sezhen**

**Comment by YuliKl** [comment]
@Ullmie02 Thank you for reaching out. You found an error in the documentation that we have since corrected. You may place any content into PaneFooter, including a NavigationViewItem. But keep in mind that NVIs in the PaneFooter won't have all the built-in behaviors of NVIs inside the MenuItems list. For example, the selection indicator's animation won't work, and the parent NavigationView will not raise its ItemInvoked event when users click on a NVI in the PaneFooter.
