### ISSUE TITLE
w

### ISSUE THREAD

**Issue by gilmanjo** [MicrosoftDocs/windows-uwp#932]
"We'll be publishing docs in the future showing how to use this option."

Where those docs at tho

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c815de33-3b2b-cf99-74fc-6b14caf0844f
* Version Independent ID: a463bd05-455f-011e-5282-7d4532e3298b
* Content: [Toast notifications from desktop apps - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/design/shell/tiles-and-notifications/toast-desktop-apps)
* Content Source: [windows-apps-src/design/shell/tiles-and-notifications/toast-desktop-apps.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/design/shell/tiles-and-notifications/toast-desktop-apps.md)
* Product: **windows**
* GitHub Login: @anbare
* Microsoft Alias: **mijacobs**

**Comment by mijacobs** [comment]
Hi @gilmanjo,
It looks like we don't have any additional documentation other than this guidance:

Essentially, for Desktop Bridge apps, just send toast notifications like a UWP app would. When the user clicks on your toast, your app will be command line launched with the launch args that you specified in the toast.

For classic Win32 apps, set up the AUMID so that you can send toasts, and then also specify a CLSID on your shortcut. This can be any random GUID. Don't add the COM server/activator. You're adding a "stub" COM CLSID, which will cause Action Center to persist the notification. Note that you can only use protocol activation toasts, as the stub CLSID will break activation of any other toast activations. Therefore, you have to update your app to support protocol activation, and have the toasts protocol activate your own app.
