### ISSUE TITLE
How is the "rescap" namespace defined?

### ISSUE THREAD

**Issue by lovettchris** [MicrosoftDocs/windows-uwp#934]
You show &lt;rescap:Capability Name="extendedBackgroundTaskTime"/&gt;  but you didn't show how the rescap namespace is defined with an xmlns:rescap="???" namespace definition, so the documentation is not complete.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9f08a1cd-54da-9647-5f88-12ff5dcd9bab
* Version Independent ID: 1de44f88-2e90-cc63-9707-b415be120237
* Content: [Run in the background indefinitely - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/launch-resume/run-in-the-background-indefinetly)
* Content Source: [windows-apps-src/launch-resume/run-in-the-background-indefinetly.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/launch-resume/run-in-the-background-indefinetly.md)
* Product: **windows**
* GitHub Login: @TylerMSFT
* Microsoft Alias: **twhitney**

**Comment by AuriR** [comment]
There's a link with detail, but I still can't add the entry. It says text isn't allowed where I placed it, odd. Here's the link, though: https://docs.microsoft.com/en-us/windows/uwp/packaging/app-capability-declarations

**Comment by hkhmsft** [comment]
Thanks for submitting your feedback and I apologize for the delayed response. I see that updates have not been made since the creation of this Issue so I went ahead and created an internal work item to incorporate your suggestions. The timeline for this may vary, so I will go ahead and close this and circle back when the changes are live. 

Though the Issue will be marked as Closed, I will monitor any replies that come afterwards so treat this like an open Issue. Many thanks!
