### ISSUE TITLE
Please Fix the Documentation

### ISSUE THREAD

**Issue by IrakliLomidze** [MicrosoftDocs/windows-uwp#946]
XAML code need to be included 

  xmlns:uap5="http://schemas.microsoft.com/appx/manifest/uap/windows10/5"

otherwise it does not work.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0d92df11-eaec-44ea-d130-e84304af9b8f
* Version Independent ID: d8ada2a7-dcea-96cc-210b-5b446ee88cad
* Content: [File access permissions - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/files/file-access-permissions)
* Content Source: [windows-apps-src/files/file-access-permissions.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/files/file-access-permissions.md)
* Product: **windows**
* GitHub Login: @laurenhughes
* Microsoft Alias: **lahugh**

**Comment by ShogunHirei** [comment]
I really like to thank you for this tip! Wouldn't find this myself...

**Comment by hkhmsft** [comment]
Thanks for submitting your feedback and I apologize for the delayed response. I see that updates have not been made since the creation of this Issue so I went ahead and created an internal work item to incorporate your suggestions. The timeline for this may vary, so I will go ahead and close this and circle back when the changes are live. 

Though the Issue will be marked as Closed, I will monitor any replies that come afterwards so treat this like an open Issue. Many thanks!
