### ISSUE TITLE
C++ XAML for DirectX and Bridge

### ISSUE THREAD

**Issue by ghost** [MicrosoftDocs/windows-uwp#962]
Please provide C++ code samples to make this work for DirectX with XAML project template with bridge?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5ba89d6c-71c3-4583-8d7f-8db231a96b07
* Version Independent ID: ce5b525b-597c-0859-ed9c-aa3104498b8b
* Content: [Extend your desktop application with Windows UIs and components - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/porting/desktop-to-uwp-extend)
* Content Source: [windows-apps-src/porting/desktop-to-uwp-extend.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/porting/desktop-to-uwp-extend.md)
* Product: **windows**
* GitHub Login: @normesta
* Microsoft Alias: **normesta**

**Comment by QuinnRadich** [comment]
Our apologies for the delayed response to this issue.

Due to the volume of feedback in our repo and the variety of samples we produce, we're not currently prioritizing creation of code samples for specific cases like this. If you believe your feedback is still actionable and the sample is still necessary, please let us know by filing a new issue, and we'll re-evaluate this case. Many thanks.
