### ISSUE TITLE
Keyboard Accelerators with copy/paste is very Difficult

### ISSUE THREAD

**Issue by robloo** [MicrosoftDocs/windows-uwp#970]
As an example say there is a ListBox. The ListBox is full of ListBoxItems which each contain a TextBox. The objective is to support copy/paste of ListBoxItems themselves. However, because each TextBox within the list also has copy/paste, the Keyboard Accelerator is invoked whenever you copy/paste text in the TextBox itself. This breaks the ability to copy/paste ListBoxItems and ScopeOwner is unable to help you in this case.

It seems TextBox does not use Keyboard Accelerators and therefore does not set Handled=true. Therefore, in order to handle this situation you must add OriginalSource to the KeyboardAcceleratorInvokedEventArgs. It is the only way to cleanly implement this case.

As for the documentation, please add a method in the documentation that shows how to do copy/paste with KeyboardAccelerators (instead of falling back to KeyUp/KeyDown events that have OriginalSource). This is probably the most used use of Keyboards.

**Comment by ginami** [comment]
Hi @robloo -- which page in in our docs are you referring to? (This will help me route your comments to the correct author.) Thanks!

**Comment by robloo** [comment]
Hi @ginami, sorry about that, link is below

https://docs.microsoft.com/en-us/windows/uwp/design/input/keyboard-accelerators

**Comment by ginami** [comment]
No worries, @robloo !

**Comment by Karl-Bridge-Microsoft** [comment]
Thanks for submitting your feedback and I apologize for the delayed response. I see that you have submitted a suggestion to the WinUI team to revise the functionality of the TextBox control.

Due to the age of this issue and the follow up you have initiated with the WinUI team, I'm closing this issue.

Though the Issue will be marked as Closed, I will monitor any subsequent replies. Many thanks!
