### ISSUE TITLE
Clarification in retrieving password from background task

### ISSUE THREAD

**Issue by LonelyTiger** [MicrosoftDocs/windows-uwp#972]
Hi,
 I was able to store the credentials in the password vault and I was able to retrieve it within the 
app. But when I was trying to get the password from vault using background task it throws exception "cannot get credentials from vault". Password vault is unique to app, I was just wondering why I was unable to retrieve it through background task.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6a69ed63-5119-76bf-848b-b8846e7d3556
* Version Independent ID: 5fa9078c-be4f-3a28-6ec6-4b880fe7ff23
* Content: [Credential locker - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/security/credential-locker)
* Content Source: [windows-apps-src/security/credential-locker.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/security/credential-locker.md)
* Product: **windows**
* GitHub Login: @msatranjr
* Microsoft Alias: **misatran**

**Comment by QuinnRadich** [comment]
We apologize for the delayed response to this issue. If this problem is still relevant, I would suggest that you pursue the problem with a support channel to get a more detailed answer. The community of experts and Microsoft Engineers over at [Microsoft Q&A](https://docs.microsoft.com/answers/topics/windows-uwp.html) offer timely answers to a multitude of technical questions surrounding windows-uwp.

If you do create a thread over at Microsoft Q&A, we would appreciate if you could share that link here so we can track the progress and incorporate any technical details into our documentation. Though I'm marking this Issue as closed now, please treat this thread as an open thread for follow-ups. Thank you!
