### ISSUE TITLE
Is this list up-to-date ?

### ISSUE THREAD

**Issue by ErwanJes** [MicrosoftDocs/windows-uwp#982]
The system recognizes Swahili – Tanzania (sw-tz) although it does not appear on this list.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dfe8af46-b88e-cba9-ae17-ec6898257f34
* Version Independent ID: 67c81930-1b91-b442-1657-085d93517590
* Content: [Supported languages - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/publish/supported-languages?f=255&MSPPError=-2147217396)
* Content Source: [windows-apps-src/publish/supported-languages.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/publish/supported-languages.md)
* Product: **windows**
* GitHub Login: @JnHs
* Microsoft Alias: **wdg-dev-content**

**Comment by JnHs** [comment]
Thanks for reporting this! I'm working to confirm the list of languages now and will close this issue after we've made any needed updates.

**Comment by JnHs** [comment]
Thanks for your patience. After consulting with the team it seems that we may allow you to upload packages targeting languages which don't appear on this list, but these languages won't be distributed to customers since they aren't supported by the Microsoft Store. I've updated the topic to make that clearer - appreciate your bringing it up.
