### ISSUE TITLE
I am searching for C/C++ guidelines

### ISSUE THREAD

**Issue by akhzarna** [MicrosoftDocs/windows-uwp#987]
Can anybody send me the code for c/c++ ??

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9f89409a-b108-603f-9279-c59f5ae5d188
* Version Independent ID: 5bd07919-59ac-4fca-b997-a472ae24bfb1
* Content: [Bluetooth GATT Client - UWP app developer](https://docs.microsoft.com/en-us/windows/uwp/devices-sensors/gatt-client)
* Content Source: [windows-apps-src/devices-sensors/gatt-client.md](https://github.com/MicrosoftDocs/windows-uwp/blob/docs/windows-apps-src/devices-sensors/gatt-client.md)
* Product: **windows**
* GitHub Login: @msatranjr
* Microsoft Alias: **misatran**

**Comment by microelec** [comment]
yes, I searched c++ examples for days. Could somebody help out.

**Comment by EquiGym** [comment]
this might help
https://github.com/ozapara/Heart-Rate-Bluegiga/blob/master/Heart_Rate_Bluegiga/main.c

**Comment by viperscape** [comment]
@EquiGym that's using a custom Bluetooth SDK and driver stack, not Windows

**Comment by stevewhims** [comment]
Hi, @akhzarna, and thanks for filing this issue. Until we have a C++ code example in this topic, one suggestion would be for you to study the [C++/WinRT](https://docs.microsoft.com/windows/uwp/cpp-and-winrt-apis/index) documentation, which contains lots of code examples showing many different techniques for calling Windows Runtime APIs from C++. It's likely that you'll learn enough there to convert the C# code here to C++/WinRT. In addition, any topic (across the Windows dev content) that has a C++/CX code example now also has a C++/WinRT code example.

Providing in-topic code examples illustrating usage of individual Windows APIs, and patterns of API usage including cross-feature patterns, is an important and ongoing workstream that's driven by priorities (those priorities are in turn driven by customer input such as this issue, and the fact that you're asking about this). Our priorities come in tiers of increasing urgency. If you take a topic that has *no* code examples then, naturally, we'd first want to provide a code example in one language. After that, in multiple languages. Ultimately, in *all* languages.

This topic has C# code examples, so it's not in the tier of highest priority for attention. So, I'll make a record of this ask, and put it onto my backlog. Since I don't have a schedule that I can share regarding when I might find time to convert the C# code here into C++/WinRT, I'll close this issue for the time being. We can revisit progress at some time in the future.

Thanks!
Steve
