### ISSUE TITLE
Can a JS usage be provided for using SQLite in docs?

### ISSUE THREAD

**Issue by ns6482** [MicrosoftDocs/windows-uwp#993]

**Comment by ginami** [comment]
Hi @ns6482 -- which page in our docs are you referring to? (This will help me route your request to the correct author.) Thank you!

**Comment by ns6482** [comment]
@ginami ...https://docs.microsoft.com/en-us/windows/uwp/data-access/sqlite-databases

**Comment by ginami** [comment]
Thanks!

**Comment by hkhmsft** [comment]
Thanks for taking the time to let us know about this and we sincerely apologize for the delayed response. Due to the sheer volume of feedback in our repo, we are currently prioritizing new Issues. If you believe your feedback is still actionable, let us know either directly in this thread or by filing a new Issue and we’ll work to incorporate the suggestions into the documentation. Though the Issue will be marked as Closed, I will monitor any replies that come afterwards so feel free to treat this like an open Issue. Many thanks!
